### ISSUE TITLE
nethunter not detecting wlna1 but it is wlan 0 wtf plz help

### ISSUE THREAD

**Issue by killergast113** [offensive-security/kali-nethunter#1000]
### Built from repo (date and build command) or downloaded from website (links):
1 link https://build.nethunter.com/nightly/3.20-20170903-2143/
2 link 
https://build.nethunter.com/nightly/3.20-20170903-2143/nethunter-generic-i386-kalifs-full-rolling-3.20-20170903-2143.zip
3 link https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-herolte-marshmallow-3.20-20170903-2143.zip

**Comment by lightakun** [comment]
what help do you need regarding ur wifi adapter 
be more specific! :)

**Comment by lightakun** [comment]
what help do you need regarding ur wifi adapter 
be more specific! :)

**Comment by lightakun** [comment]
what help do you need regarding ur wifi adapter 
be more specific! :)

**Comment by killergast113** [comment]
srry what u need kind for information???

**Comment by lightakun** [comment]
what help do u need. say ur problem?

**Comment by killergast113** [comment]
my problem is my wifi adapter is detected as wlan 0 not wlan 1
so if i type iconfig -a dusnt show shit

**Comment by killergast113** [comment]
Last login: Sat Sep 23 18:45:37 UTC 2017 on pts/2

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0b05:17d1 ASUSTek Computer, Inc. AC51 802.11a/b/g/n/ac Wireless Adapter [Mediatek MT7610/Ralink RT2870]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:~#

**Comment by lightakun** [comment]
type 'ifconfig' in terminal and paste here

**Comment by killergast113** [comment]
srry if it aint enugh info

**Comment by killergast113** [comment]
k

**Comment by lightakun** [comment]
ifconfig

**Comment by lightakun** [comment]
not lsusb

**Comment by killergast113** [comment]
root@kali:~# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0                                   inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 716  bytes 1447698 (1.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 716  bytes 1447698 (1.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

p2p0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::8cf5:a3ff:fe6e:7da9  prefixlen 64  scopeid 0x20<link>
        ether 8e:f5:a3:6e:7d:a9  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.101  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::8ef5:a3ff:fe6e:7da9  prefixlen 64  scopeid 0x20<link>
        ether 8c:f5:a3:6e:7d:a9  txqueuelen 1000  (Ethernet)
        RX packets 145875  bytes 184491952 (175.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 84814  bytes 10178098 (9.7 MiB)
        TX errors 0  dropped 8 overruns 0  carrier 0  collisions 0

root@kali:~#

**Comment by killergast113** [comment]
oh srry

**Comment by killergast113** [comment]
wrong one

**Comment by killergast113** [comment]
root@kali:~# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0                                   inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 716  bytes 1447698 (1.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 716  bytes 1447698 (1.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

p2p0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::8cf5:a3ff:fe6e:7da9  prefixlen 64  scopeid 0x20<link>
        ether 8e:f5:a3:6e:7d:a9  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.101  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::8ef5:a3ff:fe6e:7da9  prefixlen 64  scopeid 0x20<link>
        ether 8c:f5:a3:6e:7d:a9  txqueuelen 1000  (Ethernet)
        RX packets 145875  bytes 184491952 (175.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 84814  bytes 10178098 (9.7 MiB)
        TX errors 0  dropped 8 overruns 0  carrier 0  collisions 0

root@kali:~# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 722  bytes 1449874 (1.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 722  bytes 1449874 (1.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

p2p0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::8cf5:a3ff:fe6e:7da9  prefixlen 64  scopeid 0x20<link>
        ether 8e:f5:a3:6e:7d:a9  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.101  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::8ef5:a3ff:fe6e:7da9  prefixlen 64  scopeid 0x20<link>
        ether 8c:f5:a3:6e:7d:a9  txqueuelen 1000  (Ethernet)
        RX packets 146028  bytes 184564356 (176.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 84941  bytes 10214510 (9.7 MiB)
        TX errors 0  dropped 8 overruns 0  carrier 0  collisions 0

root@kali:~#

**Comment by killergast113** [comment]
is it the right stuff u need ?

**Comment by lightakun** [comment]
yes.
open this file /etc/udev/rules.d/persistent-net.rules in notepad and paste herr

**Comment by killergast113** [comment]
how

**Comment by killergast113** [comment]
i.m on a phone and no laptop broght with me srry

**Comment by killergast113** [comment]
k

**Comment by killergast113** [comment]
opend it in nano

**Comment by killergast113** [comment]
GNU nano 2.8.6     File: /etc/udev/rules.d/persistent-net.rules   

















                                  [ New File ]
^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C ^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line

**Comment by jcadduono** [comment]
we have no reason to support that adapter as your internal adapter can already do everything that it can

**Comment by lightakun** [comment]
use any root explorer

**Comment by lightakun** [comment]
is ur phone rooted?

**Comment by killergast113** [comment]
yes
superuser

**Comment by killergast113** [comment]
i.mean super su

**Comment by killergast113** [comment]
i.mean super su

**Comment by killergast113** [comment]
it dus not show the prisint folder in es file exploder pro

**Comment by killergast113** [comment]
so what can i.do help

**Comment by lightakun** [comment]
ok just wait 10 mins

**Comment by lightakun** [comment]
ok just wait 10 mins

**Comment by lightakun** [comment]
ok just wait 10 mins

**Comment by killergast113** [comment]
why

**Comment by lightakun** [comment]
type this in ur terminal
sudo iw dev wlan0 del
sudo iw dev wlan1 del
reboot ur phone then type ifconfig and paste herr

**Comment by killergast113** [comment]
Last login: Sat Sep 23 20:07:23 UTC 2017 on pts/2

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# sudo iw dev wlan0 del
root@kali:~# sudo iw dev wlan1 del
command failed: No such device (-19)
root@kali:~#

**Comment by killergast113** [comment]
wtf?

**Comment by jcadduono** [comment]
wrap pastes with triple ` on bottom and top

lol sudo as root thats silly

ok so looking up more info, huh, didnt know mt7610 actually had some mon mode features, doesnt actually work on AC though does it?
anyways, afaict its not officially supported by linux, at least not linux 3.18, so the driver is not included in the kernel and needs to be ported manually

**Comment by killergast113** [comment]
is it easy to port it manualy ?

**Comment by killergast113** [comment]
and can u give me a guide for the samsung galaxy s7 ?

**Comment by killergast113** [comment]
s7 flat not ege

**Comment by lightakun** [comment]
@jcadduono please help me

**Comment by lightakun** [comment]
@jcadduonojust one problem with me. Please

**Comment by killergast113** [comment]
? are u serius?

**Comment by killergast113** [comment]
@jcadduono can u send me some links for the galaxy s7 flat kernel code a tutorial or somthing?

**Comment by jcadduono** [comment]
i don't have any kind of special tutorial or the time to write one,
but i don't think it would be worth the effort, if you look into mt7610 driver here...
https://github.com/ulli-kroll/mt7610u
```
MT7610U for Linux

Driver for 802.11ac USB Adapter with
MT7610U/MT7630u/MT7650u chipset
Only STA/Monitor Mode is supported, no AP.

At least v4.0 is needed to compile this module
sorry people with older kernels, the code is removed.
```
porting an entire wireless driver from linux 4.0+ down to linux 3.18 could be asking for a lot of trouble (changing thousands of lines of code)

**Comment by killergast113** [comment]
@jcadduono rip

**Comment by killergast113** [comment]
@jacdduono why is sudo as root silly?

**Comment by killergast113** [comment]
hey

**Comment by killergast113** [comment]
wana get help agian

**Comment by killergast113** [comment]
found this rn may be working link

https://github.com/maage/mt7610u_wifi/blob/some_changes/README.md

**Comment by icefireCZ** [comment]
Are you really sure? Because wlan0 as default is mobile builtin interface which you are connecting to wifi with.

**Comment by killergast113** [comment]
yes

**Comment by yesrab** [comment]
root@kali:/# sudo iw dev wlan0 del
root@kali:/# sudo iw dev wlan1 del
command failed: No such device (-19)
root@kali:/# sudo iw dev wlan1 del
command failed: No such device (-19)
root@kali:/#

**Comment by 0E800** [comment]
Don't plug in your WiFi adapter till after you boot up the device and
already have a internet connection on the integrated WiFi.
