### ISSUE TITLE
Y-cable charging service is down

### ISSUE THREAD

**Issue by ahmadkar** [offensive-security/kali-nethunter#1002]
### Built from repo (date and build command) or downloaded from website (links):

https://www.google.jo/amp/s/forum.xda-developers.com/htc-one-m8/development/kali-nethunter-htc-one-m8-t3398588/amp/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-perf-ga6393e1 (and@AABM) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Thu Jan 7 16:39:16 CST 2016

## Issue:

I'm new to Kali nethunter and I'm trying to connect my TP-link  tl-wn722n via the Y-cable 
But it doesn't blink when I connect it and the device only recognize wlan0 (internal wifi )

Also when I try to turn on the Y-cable charging service it's keep going off by itself 

Any help please 😞

Thanks anyway

**Comment by jcadduono** [comment]
y cable charging requires a hacky kernel patch that must be custom tailored to each device, so only a few devices can even support it (mako, hammerhead are only ones off the top of my head)

**Comment by ahmadkar** [comment]
So is there anything that I can do ?

**Comment by ahmadkar** [comment]
Android kernel patch
Or Kali nethunter kernel patch? 😀

**Comment by phoenixelijah** [comment]
Yeah this one is a bummer! It's on my list of "Kali Services" in the UI and seems like it should be useful.
bamboozle
