### ISSUE TITLE
80211 could not configure driver mode on wlan0

### ISSUE THREAD

**Issue by geoff-github** [offensive-security/kali-nethunter#1003]
### Device:
Nexus 6P

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from build.nethunter.com

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.94+ (root@kali) (gcc version 4.9.x-google 20140817 (prerelease) (GCC) ) #4 SMP PREEMPT Fri Jan 8 19:14:10 UTC 2016

## Issue:
I'm trying to use rmnet_data0 as my upstream and use wlan0 as the serving AP using MANA, but when I try I get the error

nl80211: Could not configure driver mode
nl80211 driver initialization failed.
hostapd_free_hapd_data: Interface wlan0 not started

I have a feeling this is from the native Android OS locking the wlan0, but is there way to use the onboard wlan card to act as my MANA AP?  I've been able to hotspot my phone using the normal Android OS way, is there a way to make it my MANA?

**Comment by argtje99** [comment]
what is the output of lsmod?
