### ISSUE TITLE
Install script does not work.

### ISSUE THREAD

**Issue by seperatis** [offensive-security/kali-nethunter#1004]
### Device:
Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmellow

## Issue:
Everything works fine until the script reboots the device into TWRP. When TWRP loads it asks for a password to DECRYPT the data. I have never set a password on this device. No did I encrypt any data. 
I have tried wiping it completely and flashing back to Marshmellow (clean install), then tried again. Same thing occurs. I have read a lot of other people are having the same issue. Is there a fix for this? Why does TWRP think my data is encrypted??

**Comment by jcadduono** [comment]
misleading title, has nothing to do with install script

probably because it is encrypted as that is the default on marshmallow.... if the default password is correct then it should decrypt without issues

boot into your device, set a boot up password, this will rebuild your crypto keys and allow you to use that password to decrypt in twrp. you can remove the password at any time after and it will change it to the default password again, which twrp should auto-detect.
this is a normal thing to run into after an OS upgrade due to keymaster changes

**Comment by seperatis** [comment]
Yeah, that was the first thing I tried. It _does not_ work.
I even wiped and flashed a clean install of Marshmallow, setup the device from the beginning with a **boot password**. Boot into TWRP, it prompts for password again, I enter the password I set as a boot password, and it says _"Incorrect Password"_ and it fails to decrypt the device.

One thing that seemed promising was going to the **Wipe Data** function within TWRP. It warns that it will Un-encrypt the device by wiping the data. And it in fact does work. I was able to verify it worked by going to the "Install" function afterwards and I was able to browse the Internal Memory of my device. The problem is though, when I re-run the script to install Nethunter it re-boots the device and re-encrypts it when the script re-flashes TWRP and then it prompts for the password again when it boots into TWRP during the final part of setup which is flashing Nethunter. I've spent about 36 hours trying everything under the sun to work around this to no avail. I'm beginning to think that Nexus 9 and Nethunter are in fact _not compatible_.

**Comment by jcadduono** [comment]
sounds to me like the build of twrp you are using has some issues decrypting

you can just format data and flash https://build.nethunter.com/android-tools/no-verity-opt-encrypt/no-verity-opt-encrypt-5.1.zip then boot up and it should no longer encrypt, from there do whatever

**Comment by seperatis** [comment]
Thank you for your replies. I actually resolved the issue this morning. This in fact is not a problem with the Install Script. The problem was (as you previously stated) that Marshmallow if Force Encrypted by default.
The fix that worked for me was to flash back to a clean install of Marshmallow, then use Nexus Root Toolkit to flash No-Force-Encrypt to the Boot[Kernel].
After I flashed that to the Boot[Kernel], the LRT script was able to successfully flash Nethunter to my device.
I am guessing that this fix will work for anyone who is having an issue with an encrypted device.

**Comment by jcadduono** [comment]
probably an even easier method would have been to just install the nethunter kernel after format data, then boot up, then install the rest of nethunter using generic (from nightlies)

(installing the nethunter kernel disables encryption on boot as well)
