### ISSUE TITLE
Build.py

### ISSUE THREAD

**Issue by madScript01** [offensive-security/kali-nethunter#1005]
I don't know what happened to the build.py script or any other thing, but from like a month I can build my zip "update-nethunter-xx..." but then always when I flash I get a error saying:

"Error: Unpack boot image failed!
Aborting...
Failed to patch boot image
Updater process ended with ERROR: 1"

Now if I want to test a kernel "Image" file I have to go to my old flashable zip and replace the old "Image" file with the one I want to test.

Does this script requires any dependencies (just thoughts)?

**Comment by jcadduono** [comment]
Maybe building device for wrong architecture has to match twrp arch

**Comment by madScript01** [comment]
Tried another but still doesn't work. Anyway, about a month  ago I've built a test kernel and I built it and flashed it sucessfully, but now with the same "Image" file i can't build a new flashable zip :/
