### ISSUE TITLE
Alternative to mac80211 injection patch?

### ISSUE THREAD

**Issue by FFY00** [offensive-security/kali-nethunter#1006]
### Device:
Redmi Note 4 (mido)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
7.0

### Built from repo (date and build command) or downloaded from website (links):
https://github.com/FFY00/android_kernel_xiaomi_msm8953 with the `mac80211.compat08082009.wl_frag+ack_v1` patch.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Just my kernel name (3.18). Built with linaro 5.4.

## Issue:
When the patch is applied, the stock android wifi doesn't work. It can't be enabled. I am opening this issue because in the [porting documentation](https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel#patching), you say this patch is used by default, so I wanted to know if there are other options available? Or if perhaps you have ran into this issue when porting the rom and know how to fix it.

Thanks for your time,
FFY00

**Comment by jcadduono** [comment]
Are you sure this patch is the issue, I can't see how it could possibly cause an issue with your internal wifi, it sounds more like your wifi driver didn't build and install correctly (might be a separate kmod)

**Comment by FFY00** [comment]
Yes, I'm sure. I compiled with and without the patch and the issue only is present when I patch the kernel.

**Comment by jcadduono** [comment]
your kernel uses pronto wlan which does not even depend on mac80211 driver so this really does not make any sense at all

**Comment by FFY00** [comment]
Ok, sorry. Looks like it was a bad build. I cleaned the local repository and made a clean build with the latest version of the remote repository (which includes the aircrack patch) and the issue is gone. The problem is that the patch still doesn't work, I still get the the -1 channel error. I don't know if you are able or want to help, if you do I would appreciate.
