### ISSUE TITLE
Unable to find kernel image at: devices/oreo/bullhead

### ISSUE THREAD

**Issue by h3xcmd** [offensive-security/kali-nethunter#1007]
### Device:
Bullhead - Nexus 5x 

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo 8.0.0 (OPR4.170623.006, Sep 2017) | Link | e876a2762a721ba12abbe6849d31b4aa2c5eeff8decdc558d9964a1ee0403936

### Build Number: 
OPR4.170623.006

### Kernel: version Kernel: 
3.10.73-gf712c0503a8

### Built from repo (date and build command) or downloaded from website (links):
nethunter-bullhead-oreo-kalifs-full-20170929_133807.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
```
~ # cat /proc/version
Linux version 3.10.73-g9868d5b (jenkins@5f51a4c0d870) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Wed May 17 03:59:01 UTC 2017

```
### Issue:

> Error: Unable to find kernel image at: devices/oreo/bullhead
> Removing temporary build directory

The devices folder that ./bootstrap.sh builds does not include an "oreo" directory or devices sub directories ex: "bullhead" to include a Image.gz-dtb kernel. 

the ./bootstrap.sh has to be updated to support oreo because it is missing devices/oreo/bullhead/Image.gz-dtb directory and file. 

## Resolution 

```
git clone https://github.com/offensive-security/kali-nethunter
cd kali-nethunter/nethunter-installer
./bootstrap.sh
cd devices/
mkdir oreo/bullhead
```

go to https://android.googlesource.com/device/lge/bullhead-kernel/+/oreo-r4-release/Image.gz-dtb

[Image.gz-dtb](https://android.googlesource.com/device/lge/bullhead-kernel/+/oreo-r4-release/Image.gz-dtb) <- Right click on hyperlink go to the web link right click on file 'save taget as' and save to 

> kali-nethunter/nethunter-installer/devices/oreo/bullhead

```
python build.py -d bullhead --oreo --rootfs full
```

finished result: **nethunter-bullhead-oreo-kalifs-full-20170929_133807.zip**

### Issue 2
Root access disappears Causing no boot. Stuck at "press power to pause" or Bootloader 

## Resolution 
Right after installing `nethunter-bullhead-oreo-kalifs-full-20170929_152828.zip` in TWRP
You have to install `SuperSU-v2.82-201705271822.zip ` again. 

Alternatively, I have had to re-flash the stock boot.img  

```
fastboot flash boot bullhead-opr4.170623.006-factory-e876a276/bullhead-opr4.170623.006/image-bullhead-opr4.170623.006/boot.img
```

to boot google android and verify that root was removed. (at this point nethunter is installed) 

I also had to install TWRP again at the boot loader. 

```
fastboot flash recovery twrp-3.1.1-0-bullhead.img
```

and then install the SuperSU-v2.82-201705271822.zip clear cache and reboot
Kali nethunter Boot flash display then works.

**Comment by ozz86** [comment]
## build: kali-nethunter-oreo-nexus_5x



[Documentacion: por h3xcmd ](https://github.com/offensive-security/kali-nethunter/issues/1007)

traslate: ipoc1386

recuperado octubre-28-17



Build zip 



```
git clone https://github.com/offensive-security/kali-nethunter
cd kali-nethunter/nethunter-installer
./bootstrap.sh
	y
	y
	n

cd devices/
mkdir oreo/bullhead
```

 Bajar el archivo del siguinte link [Image.gz-dtb](https://android.googlesource.com/device/lge/bullhead-kernel/+archive/oreo-r4-release.tar.gz)  y cambialo de nombre a *"Image.gz-dtb"*
pegalo en la ruta que creaste */oreo/bullhead*



ve a la siguiente ubicacion

cd kali-nethunter/nethunter-installer

ejecuta:

```
python build.py -d bullhead --oreo --rootfs full
```

si compila sin problema terminara con tu archivo nethunter.zip sino es por que:


**Existe un error en la compilacion del archivo build durante la descarga del archivo de Super_su.zip, esto debido a que la pagina del programador no tiene certificados SSL, para solucionar cambie el codigo del archivo *nano buil.py* de la siguinte manera y asi corregi el error de compilacion del archivo:**


```
dl_supersu = {
	'beta': ['https://download.chainfire.eu/supersu-beta', False],
	'stable': ['https://s3-us-west-2.amazonaws.com/supersu/download/zip/SuperSU-v2.82-201705271822.zip', '936c6c20bde8685856a50871039a47cc24cfb56c303dafb66625a5098ebca1436b46e6f62f44897d7a04e2d886eb323ac8e0c2f29d113757f376e80ccd10a3ad'],
```

Existe un fallo al iniciar ya que no reconoce el OS la particion de super usuario, por lo que se debe reintalar el mismo archivo zip del SUperSU del link anterior para solucionar el problema.

En este blog se recomienda que si no funciona, existen mas pasos checa el comentario completo de arriba:
 **sugiero se armen de paciencia y descarguen la room original por si las dudas dejo el [link](https://developers.google.com/android/images)**



Ademas la jaula chroot, que trae por default no funciona, por lo que recomiendo quitarla o desintalarla y reinstalar desde la aplicacion de kali linux.

Suerte : by Ozz

**Comment by jcadduono** [comment]
or you could just build generic, since Image.gz-dtb is actually a nethunter kernel specifically tailored for the device, NOT a stock kernel like you downloaded.
bullhead does not have Oreo support on nethunter yet.

**Comment by DeVvil1** [comment]
@jcadduno I have a custom kernel with kalinethunter patches! Can you just tell me what to proceed?
