### ISSUE TITLE
Another terminal for Nethunter?

### ISSUE THREAD

**Issue by SyedTahseen** [offensive-security/kali-nethunter#1010]
Can I add another terminal **Like Material Terminal**  for nethunter app as Intent terminal ?

**Comment by keeganjk** [comment]
You can use other terminals, I believe you can use the command `bootkali` to boot into the Kali shell.

**Comment by bozwald** [comment]
in another terminal emulator app 

su 
bootkali_login 

If your nethunter terminal is crashing you may wish to  download term-nh.apk from github and installing it after allowing unknown sources.

**Comment by kimocoder** [comment]
I would anyway recommend using the one that comes with NetHunter, as it is a modified fork with changes to fit NetHunter.

**Comment by SyedTahseen** [comment]
Thanks friends
