### ISSUE TITLE
wiki: few updates to the wiki

### ISSUE THREAD

**Issue by kimocoder** [offensive-security/kali-nethunter#1011]
Few things should be added to the wiki, for informational/usage purposes.

* OnePlus 5 should be added to "devices supported"
* 'Modifying kernel' should include the carl9170 injection patch from [here](https://github.com/offensive-security/wireless-patches) for additional adapter injection support.

**Comment by bozwald** [comment]
@kimocoder hi mate just got a better env for dev built last night but i have some questions which might seem somewhat trivial but hopefully can help me get

**Comment by bozwald** [comment]
Hey @kimocoder i have a few questions about compilation i was wondering if i could shoot your way they may end up being trivial just not getting right info off net atm, just built a better enviornment for dev on and i was hoping we could start an IM dialogue, can you message me @bozwald on telegram or perhaps i can email your email on your profile?

**Comment by bozwald** [comment]
@kimocoder i got bluetooth tools working and it finds my alfa 036h but cant work out how to get the usb wifi working on monitor mode or how to get HID running yet, did you come across those two? everything else is working afaik now.

**Comment by kimocoder** [comment]
well, as we talked about some work needs to done with kernel.. the more easy way would be waiting for lineageos to be working wirh S8 (dreamlte), the progress (bounty XDA thread) could be seen [here](https://forum.xda-developers.com/galaxy-s8/how-to/lineage-os-samsung-galaxy-s8-t3639720)
