### ISSUE TITLE
Screenrotation galaxy s5 nightly kernel

### ISSUE THREAD

**Issue by argtje99** [offensive-security/kali-nethunter#1012]
### Device:
Galaxy S5 (klte)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 
Last login: Sat Oct  7 13:35:26 UTC 2017 on pts/2

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# cat /proc/version
Linux version 3.4.113-nethunter-klte-xx-3.0 (jc@arkyn) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP PREEMPT Sat Sep 2 14:08:48 EDT 2017
root@kali:~#

-----------------------------------
Hello, 
I am using a galaxy s5 klte version with nethunter.
Everything is working fine till now.
I flashed the kernel from nethunter nightly. 
Also the armhf full rolling zip file.
But now my screenrotation isn't working anymore.
Its not a big issue but i would like to fix it.

Regards
Argtje99

**Comment by jcadduono** [comment]
On latest LineageOS 12.1 nightly?

**Comment by argtje99** [comment]
@jcadduono i'm running resurrection remix now. Without any problems except the screen rotating.

**Comment by argtje99** [comment]
@jcadduono its based on lineageos

**Comment by argtje99** [comment]
Fixed by factory reset
