### ISSUE TITLE
nethunter not detecting tp link TL-WN722N

### ISSUE THREAD

**Issue by killergast113** [offensive-security/kali-nethunter#1013]

**Comment by kimocoder** [comment]
which version of the TL WN-722n do you got?

**Comment by killergast113** [comment]
150 mbps high gain

**Comment by killergast113** [comment]
what do you actualy mean ?

**Comment by killergast113** [comment]
oh srry v2.0

**Comment by killergast113** [comment]
so i.m using a v2.0 so what next ?

**Comment by kimocoder** [comment]
well, v1 is supported (using the ath9k_htc chipset), while v2.xx uses the r8188eu chipset.. Not supported

**Comment by killergast113** [comment]
can i.port it ?

**Comment by kimocoder** [comment]
it does not support either monitor mode or injection.
the driver could anyway be found [here](https://github.com/lwfinger/rtl8188eu/tree/master)

**Comment by killergast113** [comment]
so i.can not capture a hand shake and plz give me the link for the v1 tp link tl wn 722 n to buy it ty

**Comment by kimocoder** [comment]
well, the v1 is not for sale anymore.. it's replaced with v2, which got a cheaper chipset :/

**Comment by killergast113** [comment]
any others i.can use with out usb y cable ?

**Comment by kimocoder** [comment]
Googling (some research) allways pays off, but [here](https://forums.kali.org/showthread.php?22955-best-external-wifi-dongle-to-use-with-nethunter-for-wifi-attacks) is a start 👍

**Comment by killergast113** [comment]
i yet have a other one witch is kernel 4.0 and its removed for older kernels but any way usb ac51 wirless ac600 so it would be nice to have a 3.18 kernel for it but u know so that would be osome

**Comment by mohamedmks** [comment]
@killergast113 TL-WN722N v1  no more in the market   but there is v 1.10 alongside V2 (yes brand new V 1.10 i don't know how they make it maybe because no one buys v2 lol)  and it works (monitor mode supported)   
V 1.10 pic https://imgur.com/6302c23

**Comment by killergast113** [comment]
send link to buy one plz so v2 monitor mode is soported ??

**Comment by kimocoder** [comment]
Monitor mode is NOT supported on v2.

**Comment by killergast113** [comment]
plz send link for tp link TL-WN722N V1.10 WOULD BE nice

**Comment by killergast113** [comment]
@mohamedmks send buy link for  v1.10 plz

**Comment by mohamedmks** [comment]
@killergast113  I bought it locally  ,sorry i can't recommend something online .  search carefully on http://www.ebay.com

**Comment by darksty** [comment]
i got a wn722n v1 but it doesn't be detected on my Oneplus3T

**Comment by darksty** [comment]
already solved

**Comment by ppisljar** [comment]
@darksty what was the solution ?

**Comment by darksty** [comment]
@ppisljar Just use "modprobe ath9k_htc"

**Comment by ppisljar** [comment]
the device (nexus 6p) reboots after entering above command.

android 8.0, kernel 3.1 nethunter 2.0
lsmod shows the device, dmesg shows the device found and no errors listed

**Comment by Juanito1** [comment]
and de version 3.0?
