### ISSUE TITLE
external ip not getting forwaded to local ip!!!

### ISSUE THREAD

**Issue by Sharik7** [offensive-security/kali-nethunter#1014]
### Device:
one plus 2 kali nethunter rom

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

nougat
### issue###
i have set local ip with a new port in my router to get connected to my using external ip but whenever i create a payload or try to web clone  by setting my no-ip hostname as payload lhost  n listener set as my local ip  but the payload is still working only on my wifi connected device  example i created a web clone with reverse tcp and i  sent cloned link to my another device which are connected with my wifi  n it works fine but it is not working on device which is not connected to my wifi.....m new on kali linux so  plzzz  guide me n thanx in advance.....

**Comment by jcadduono** [comment]
Are you trying to port forward over cell data? Most carriers do not allow incoming connections to a mobile device.

**Comment by Sharik7** [comment]
i have port forwarded on my wifi ip n i have set port 4444 , so while creating payload i use my external ip and  listeners port has been set as local ip...... then also the created payload doesn't works out of wlan network ....

**Comment by Sharik7** [comment]
upnpc -a 192.168.1.100 4444 4444 TCP
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:49152/wps_device.xml
 st: uuid:00000000-0000-1000-0000-001ea66e59a6

 desc: http://192.168.1.1:49152/wps_device.xml
 st: upnp:rootdevice

 desc: http://192.168.1.1:1900/igd.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:1900/ipc
Local LAN ip address : 192.168.1.100
ExternalIPAddress = 172.16.2??.18?
InternalIP:Port = 192.168.1.100:4444
external 172.16.2??.18?:4444 TCP is redirected to internal 192.168.1.100:4444 (duration=0)
