### ISSUE TITLE
Custom Commands - where is the backup file?

### ISSUE THREAD

**Issue by gamer06** [offensive-security/kali-nethunter#1016]
### Device:
Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
7.1.1

### Built from repo (date and build command) or downloaded from website (links):
kali website

## Issue:
This is not really a issue. I want know how i do backup in "Custom Commands". Il have a "Backup DB" but i wont see this backup file. Where it is save?

Thanks!!

**Comment by simonpunk** [comment]
/data/data/com.offsec.nethunter/databases

the “KaliLauncher” file

**Comment by binkybear** [comment]
If you click backup db you should see it in /sdcard/ as nh_bak_KaliLauncher

For the code used see:

https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/CustomCommandsSQL.java#L172
