### ISSUE TITLE
WN722N DOESN'T WORK ON OnePlus3T

### ISSUE THREAD

**Issue by darksty** [offensive-security/kali-nethunter#1017]
### 7.1.1 (Nougat)

root@kali:/# uname -a
Linux kali 3.18.31-perf++ #1 SMP PREEMPT Mon Jul 17 13:44:23 CDT 2017 aarch64 GNU/Linux

root@kali:/# cat /proc/version
Linux version 3.18.31-perf++ (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jul 17 13:44:23 CDT 2017

root@kali:/# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:/# lsmod
Module                  Size  Used by
ath9k                  89692  0
ath9k_common           27230  1 ath9k
ath9k_hw              437928  2 ath9k_common,ath9k
mac80211              556488  1 ath9k
ath                    30516  3 ath9k_common,ath9k,ath9k_hw
wlan                 5801819  0

**Comment by jcadduono** [comment]
modprobe ath9k_htc

**Comment by darksty** [comment]
I also tried ifconfig wlan1 up but get an error

root@kali:/# ifconfig wlan1 up
wlan1: ERROR while getting interface flags: No such device

and when i tap on nethuner-Mac changer-RESET wlan0 MAC the nh app will close and back to desktop

**Comment by darksty** [comment]
@jcadduono

Wow use this command and use ifconfig wlan1 up amd it worked

**Comment by jcadduono** [comment]
hopefully automatic module loading will be fixed by next app release but until then you can just use that command
