### ISSUE TITLE
hackerskeyboard found, then connection aborted, reset by peer

### ISSUE THREAD

**Issue by fallenreaper** [offensive-security/kali-nethunter#1019]
### Device:
Mac OSX

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
marshmallow

### Built from repo (date and build command) or downloaded from website (links):
latest repo, pulled devices, ran:   python build.py --marshmallow -d oneplus2oos

## Issue:
When i attempt to build, it fails some point after finding the hackerskeyboard.

`kali-nethunter/nethunter-installer $python build.py -d oneplus2oos --marshmallow
Downloading: Hackerskeyboard.apk (1303164 bytes)
    1303164  [100.00%]
SHA512: 8c861c7540e6eeb006070d0f2d80134e75637066591d705b987e164c3fe87521ed694ac844c945eb74449aff8723ff039f793b2e3743aac73865f74bb248edf5
Expect: 8c861c7540e6eeb006070d0f2d80134e75637066591d705b987e164c3fe87521ed694ac844c945eb74449aff8723ff039f793b2e3743aac73865f74bb248edf5
Hash matches: OK
Download OK: update/data/app/Hackerskeyboard.apk
Error: ('Connection aborted.', error(54, 'Connection reset by peer'))
`

**Comment by jcadduono** [comment]
just try again another time, their server might be overloaded or doing maintainance
