### ISSUE TITLE
Nexmon change, not an issue

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#1020]
## Issue:
According to the Nexmon project Github, the Nexus 5 can now support monitor mode and frame injection. Does this change the fact of the Nexus 5 needing an external wifi card? From what I can tell, this should mean the Nexus 5 can use the internal card by itself without issue

**Comment by bozwald** [comment]
from everything ive read about it in the last couple of days, yes. I hoped it may have worked on the qualcomm chip in my 5x but its just for the 5!

**Comment by BearChavez** [comment]
@bozwald I've been told that I, as well as others, will have to work on getting that to work on our own because of the chipset the 5X has. The 5 and others use Broadcom, the 5X uses Qualcomm

**Comment by bozwald** [comment]
@BearChavez ive gotten my external adapter working, looking for a lower powered one now.

Youre right about Nexmon, for it to work for Qualcomm youd have to take the project back to the beginning.
