### ISSUE TITLE
[Question] In Kali Services menu OpenVPN service is a client or a server?

### ISSUE THREAD

**Issue by MPeti1** [offensive-security/kali-nethunter#1022]
### Device:

Xiaomi Redmi 3S Prime (unrelevant, installed without kernel)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

6.0.1

### Built from repo (date and build command) or downloaded from website (links):

don't remember, but app and chroot is up to date, and chroot is a full installation of kali-linux-nethunter

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-g0a93be6 (builder@mi-server) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Jun 15 01:10:11 WIB 2017

## Issue:

The mentioned service is a client or a server?

I've installed one instance with `apt-get install openvpn` but it stops with this error: 

> TCP/UDP: Socket bind failed on local address [AF_INET][undef]:443

I've read it can be caused by bad configuration in the `proto` line. I've written tcp4 here, because i need to run the server on port 443 to encrypt it (the lan where i want to use it has deep packet inspection, and does not allow vpn connections).
What could i do here?

If it's a server, how can i manage it and set up?
If it's a client, then how can i run the server which i installed on tcp port 443?

**Comment by Dave-ee** [comment]
Bump, as I would also like to know this.
