### ISSUE TITLE
TWRP createTarFork() 255 error when resulting data when Nethunter is installed, restoring it, and trying to make another backup

### ISSUE THREAD

**Issue by keeganjk** [offensive-security/kali-nethunter#1023]
I've used Kali Nethunter with a Magisk module from @atarii on XDA, but if I try to make a backup of data in TWRP that includes /data/local/nhsystem, all TWRP backups fail with 255 createTarFork() errors. If I run  `rm -rf /data/local/nhsystem` in the TWRP terminal, backups will then succeed.

Is there any way Nethunter could just be run from Internal Storage instead of data?

**Comment by jcadduono** [comment]
no because internal storage uses fs overlays that do not allow loop mounting capabilities or executable permissions, its possible with sdcard partitioning if you have one
try to just rm -rf /data/local/nhsystem/dev

**Comment by keeganjk** [comment]
@jcadduono What does that command do? Will it prevent any network adapters from working?

**Comment by keeganjk** [comment]
I believe this error was from lack of space. Closing now.
