### ISSUE TITLE
Angler Nexus 6P - Oreo - external Wifi

### ISSUE THREAD

**Issue by BesoBerlin** [offensive-security/kali-nethunter#1025]
### Device:
angler

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oreo 8.0

### Built from repo (date and build command) or downloaded from website (links):

kernel-nethunter-angler-oreo-2017.10-20171013-0449.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Wed Sep 6 16:27:46 EDT 2017

## Issue:

First of all THANK YOU for providing this Kernel!
At the moment it seems like i cant get external wireless cards to be recognised. Neither awus nor tp-link works. 
Any ideas?

Also it is now possible to save duckhunter Scripts, nur loading them ist still not. The location "does not exist" even when loading directly from nh_files.

THANK YOU again anyway and in advance for fixing.

**Comment by jcadduono** [comment]
Use modprobe to load modules for your adapter
Open an androidsu terminal and do su -c setenforce 0 to fix other broken functions if not already in permissive mode

**Comment by BesoBerlin** [comment]
Well... This ist where my knowledge ends...
modprobe ath9k_htc
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.73-nethunter-angler-2.0/modules.dep.bin'
modprobe: FATAL: Module ath9k_htc not found in directory /lib/modules/3.10.73-nethunter-angler-2.0

**Comment by BesoBerlin** [comment]
well its possible that my usb-c - microUSB adapter is causing the issue...
ill check that as soon i can get an usb-c OTG....

**Comment by BesoBerlin** [comment]
well no... doent work ... any suggestions? 
As well:
how can i fix the issue of not loading ducky scripts within duckhunter?

**Comment by cegi** [comment]
@BesoBerlin Using external wifi card is pointless on Nexus6p 8.0, the internal wifi card support monitor and injection + 5ghz, check Nexmon on github.

**Comment by BesoBerlin** [comment]
@cegi but the integratiion in nethunter is not given yet, is it?
so far thank for the advice, i'll check tht directly!

**Comment by cegi** [comment]
@BesoBerlin, hi i was busy, about your question i don't know myself and would like to know but if you're interested => https://build.nethunter.com/nightly/2017.10-20171013-0449/

There's work on it, check Angler Oreo Build, also five days ago, Nexus 5X got Oreo Support for Nethunter, so keep an eye on Nexus 6p nightly build.

**Comment by jcadduono** [comment]
as far as I can tell external adapters work fine on Nexus 6P, you just need to modprobe for your specific adapter

**Comment by kimocoder** [comment]
Confirmed. Working fine on Nexus 6P.

**Comment by cegi** [comment]
I don't know how good the Nexus 6P Oreo is on NetHunter, is there major issues, minor, or none at all ? Since it is an upgraded Nexus 5 but also with total Nexmon support on Oreo, i'm interested about it.

**Comment by Tyrell777** [comment]
How did you get the external wifi card working on Nexus 6P Exactly ?
I run Oreo with nethunter.

**Comment by Tyrell777** [comment]
Im stuck at this point:

- Nethunter works (but no monitor mode from nethunter kali terminal)
- Nexmon works (Monitor Mode in Nexmon works "outside of Kali terminal")
- Injection /Deauth etc. does not work
- How can you integrate monitor mode in kali terminal (internal wifi chip) on Nexus 6P ?
- Or atleast get injection at Nexmon working ?

I flashed this kernel again
kernel-nethunter-angler-oreo-2017.10-20171013-0449.zip

And i still do not find any additional wifi interface.

Would be glad with ur advices.

**Comment by jcadduono** [comment]
modprobe your device's drivers

**Comment by Tyrell777** [comment]
How can I do that exactly for the Nexus 6P ?
