### ISSUE TITLE
(REQUEST) Nethunter for Nexus 6P 8.0 ((Nexmon))

### ISSUE THREAD

**Issue by catest0** [offensive-security/kali-nethunter#1028]
## Issue: Only Nexus 5 and 6P has total support from Nexmon, but Nexus 6p only on Oreo, which means a support nethunter for it would mean no need for external card on 6p anymore which is amazing...

Thanks for the hard work

**Comment by sylar1233** [comment]
You can Help me ? 
https://github.com/offensive-security/kali-nethunter/issues/1104
