### ISSUE TITLE
NOT DETECTING USB WIFI ADAPTER

### ISSUE THREAD

**Issue by baheejtp123** [offensive-security/kali-nethunter#1031]
### Device:
s7 edge (sm-g935f)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

7.1

## Issue:
i unpacked boot.img now where to edit to detect external usb wifi adapter for nethunter.
im using galaxy s7 edge (sm-g935f) note 8 port.plz help @binkybear
i tried SuperKernel-TW70-s8port , but not detecting twrp recovery showing invalid zip format! error...

**Comment by bozwald** [comment]
what is the output of your cat /proc/version
