### ISSUE TITLE
Wifi internal adapter doesnt work

### ISSUE THREAD

**Issue by zivlazarov** [offensive-security/kali-nethunter#1033]
### Device:
OnePlus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):
http://build.nethunter.com/nightly/
the lastest

## Issue:
My phone can't find any available wifi networks and it can't turn wifi on. I've rebooted several times and nothing's changed. It's like the installation of the kernel is the cause of that. I've tried install without the kernel and the wifi worked narmally.

**Comment by keeganjk** [comment]
This has happened to me before. What are you rooted with? Try a simple wipe in TWRP to factory reset.

**Comment by keeganjk** [comment]
Try re-flashing what you've flashed.

**Comment by bozwald** [comment]
The builds on build.nethunter.com/nightly usually include the kernel, flash
zip from twrp, might need to root if it wasnt included but it is usually.
No need to flash 2 kernels
