### ISSUE TITLE
oneplus3  latest nightly build

### ISSUE THREAD

**Issue by Viseria** [offensive-security/kali-nethunter#1035]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):Nougat(7.1.1)+Oxygen OS
(4.5.1)

### Built from repo (date and build command) or downloaded from website (links):
http://build.nethunter.com/nightly/
kernel-nethunter-oneplus3-oos-nougat-2017.10-20171013-0449

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.31-perf++ (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Mon Jul 17 14:07:39 CDT 2017

## Issue:
Doesn't recognize wifi adapter TL-WN722N and TL-WDN3200.
Previous builds recognize both adapters but crush after few minutes.

**Comment by chhc007** [comment]
Hi,i am using op3t and the new kernel for oneplus 3t have the same problem.
It can not recognize any wifi adapter.
My os is oos4.0.2 andriod 7.0 .

**Comment by Viseria** [comment]
i guess we just need to wait for a new build

**Comment by jcadduono** [comment]
hi contact me on irc between 3pm and 2am eastern time for test builds

**Comment by Viseria** [comment]
i prefer to wait when it will be released on original website

**Comment by bozwald** [comment]
Without people to test it that time may not come I dont think jcadduono has
a one plus.

**Comment by Viseria** [comment]
they have test builds on original website
and even if he has something I would never flash it on my phone ;P

**Comment by bozwald** [comment]
you've already flashed his stuff on your phone from the original website 


<img width="670" alt="screen shot 2017-11-22 at 18 57 54" src="https://user-images.githubusercontent.com/26123637/33145101-23eecb84-cfb7-11e7-8b53-d0ce7a65dbf1.png">

**Comment by jcadduono** [comment]
On what original website where and why

**Comment by Viseria** [comment]
his or not it doesn't matter cuz its official website not directly from stranger

**Comment by jcadduono** [comment]
not sure if you realize that I run build.nethunter.com lol

**Comment by Viseria** [comment]
cool then I'll wait when you'll post it there ;)

**Comment by Viseria** [comment]
oh,I just checked there is new build released on 18.11.Gonna try it, thanks!

**Comment by Viseria** [comment]
Well...flashed kernel-nethunter-oneplus3-oos-nougat-2017.11-18-1618
Getting same version like in previous one:
 Linux version 3.18.31-perf++ (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Mon Jul 17 14:07:39 CDT 2017
![screenshot_20171123-084228](https://user-images.githubusercontent.com/33448084/33161174-5f89803a-d02a-11e7-880f-090e78a6b11d.jpg)

**Comment by jcadduono** [comment]
i do put the files on build.nethunter.com for testers to download, but i won't make it available to the public through nightlies (although they can browse the test-builds folder if they dare)
i just won't upload it without someone to be in direct contact with for test feedback on IRC.

**Comment by Viseria** [comment]
Uuumm..oke

**Comment by Viseria** [comment]
Is the build for Oreo coming soon?

**Comment by jcadduono** [comment]
no, no one has volunteered to test

**Comment by Viseria** [comment]
I would volunteer if i knew how it works but I don't 🤔
