### ISSUE TITLE
Install Nethunter in external sd card

### ISSUE THREAD

**Issue by paradoxnafi** [offensive-security/kali-nethunter#1037]

**Comment by paradoxnafi** [comment]
OK, I have already solved my problem.
1. Convert SD card as `ext4`
2. Mount `/data/local/nhsystem/` with `/mnt/expand/d590af-c74e2a-...../`
3. Normally install Chroot of Nethunter

**Comment by MrSouravPaul** [comment]
plz help me to install it on my sdcard..

**Comment by NghiaPham0909** [comment]
help me ple
