### ISSUE TITLE
External wifi adapter not working

### ISSUE THREAD

**Issue by Prodject** [offensive-security/kali-nethunter#1039]
### Device:

Nexus 5 [Hammerhead]

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/2017.10-20171013-0449/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-g24e5f11 (chris@LinuxVirt) (gcc version 4.6.x-google 20120106 (prerelease) (GCC) ) #11 SMP PREEMPT Tue May 30 17:24:23 EEST 2017

## Issue:

After installing Nethunter 2017.1 stopped to see my external wifi adapter [TP-Link TL-WN722N], I tried to install a different version of NetHunter, but that didn't help. I also tried to put the NetHunter OS, have tried a few different OTG cables. Here's the output of dmseg | grep usb:

[ 979.169204] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[ 979.169633] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 979.169869] usb usb1: Product: xHCI Host Controller
[ 979.170278] usb usb1: Manufacturer: Linux 3.4.0-g24e5f11 xhci-hcd
[ 979.170510] usb usb1: SerialNumber: xhci-hcd
[ 979.187361] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[ 979.187791] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 979.188207] usb usb2: Product: xHCI Host Controller
[ 979.188442] usb usb2: Manufacturer: Linux 3.4.0-g24e5f11 xhci-hcd
[ 979.188857] usb usb2: SerialNumber: xhci-hcd
[ 979.519914] bq24192_external_power_changed: usb host mode = 1
[ 980.325888] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[ 980.357103] usb 1-1: New USB device found, idVendor=0cf3, idProduct=9271
[ 980.357218] usb 1-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 980.357281] usb 1-1: Product: USB2.0 WLAN
[ 980.357391] usb 1-1: Manufacturer: ATHEROS
[ 980.357452] usb 1-1: SerialNumber: 12345
[ 980.358087] usb 1-1: ep 0x1 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 980.358468] usb 1-1: ep 0x82 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 980.358932] usb 1-1: ep 0x5 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 980.359224] usb 1-1: ep 0x6 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 980.360778] usb 1-1: ath9k_htc: Firmware htc_9271.fw requested
[ 980.647323] usb 1-1: ath9k_htc: Transferred FW: htc_9271.fw, size: 51008
[ 981.151612] usb 1-1: ath9k_htc: USB layer deinitialized

**Comment by keeganjk** [comment]
Do you have a custom kernel installed?

**Comment by Prodject** [comment]
Yeah,I tried to put a different kernel like from the site build.nethunter.com (kernel-nethunter-hammerheadcm-nougat, kernel-nethunter-hammerheadmon-nougat) and compile from source, there is no result.

**Comment by keeganjk** [comment]
Are you using USB OTG?

**Comment by Prodject** [comment]
I now flashed the stock firmware and put the engine to drain. Everything is still, and is it in stock android there is a separate item connect otg?

**Comment by keeganjk** [comment]
I don't know, I'm not on stock Android, but you should find an OTG setting somewhere.

**Comment by Prodject** [comment]
they are in the night release lineage?

**Comment by keeganjk** [comment]
I'm not sure, I'm on OxygenOS (for OnePlus devices)

**Comment by Prodject** [comment]
There may be a problem in the technical part of the smartphone? Usb port or controller?

**Comment by keeganjk** [comment]
Maybe... Does a normal flash drive work when you plug it in via OTG?

**Comment by bioteknik** [comment]
Htc_9271 is the firmware for your external TP link. It's deinit your arthros usb. It's detecting it and loading the firmware.   Just # ifup wlan1 it's gotta be a setting somewhere. Not the firmware. 
Which hammerhead is it?

**Comment by Prodject** [comment]
Yes, but your command will not help me because the device is not shown as wlan1, or rather nothing at all.

**Comment by geoff-github** [comment]
Having the same issue, I can read USB thumbdrives just fine and have tried two different USB-C adapters and two different wifi chipsets.  I  can see the wifi cards in lsusb, but not in ifconfig or iwconfig using the kernel 

/proc/version
Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Wed Sep 6 16:27:46 EDT 2017

dmesg | grep usb
[    0.429296] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    0.431357] usbcore: registered new interface driver usbfs
[    0.431415] usbcore: registered new interface driver hub
[    0.431691] usbcore: registered new device driver usb
[    0.462716] gdsc_usb30: no parameters
[    0.615543] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    0.639005] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    1.377373] usbcore: registered new interface driver rndis_wlan
[    1.377409] usbcore: registered new interface driver ath6kl_usb
[    1.377433] usbcore: registered new interface driver catc
[    1.377457] usbcore: registered new interface driver kaweth
[    1.377498] usbcore: registered new interface driver pegasus
[    1.377523] usbcore: registered new interface driver rtl8150
[    1.377543] usbcore: registered new interface driver r8152
[    1.377568] usbcore: registered new interface driver asix
[    1.377590] usbcore: registered new interface driver ax88179_178a
[    1.377614] usbcore: registered new interface driver cdc_ether
[    1.377636] usbcore: registered new interface driver rndis_host
[    1.420676] msm-qusb-phy f9b39000.qusb: invalid resource
[    1.465119] usbcore: registered new interface driver cdc_acm
[    1.465157] usbcore: registered new interface driver usb-storage
[    1.465181] usbcore: registered new interface driver ums_eneub6250
[    1.465202] usbcore: registered new interface driver ums-onetouch
[    1.465225] usbcore: registered new interface driver ums-realtek
[    1.465249] usbcore: registered new interface driver emi26 - firmware loader
[    1.465272] usbcore: registered new interface driver emi62 - firmware loader
[    1.465296] usbcore: registered new interface driver usb_ehset_test
[    1.466316] tusb320_i2c_init: entry
[    1.466378] tusb320_probe: start
[    1.467813] dual_role_usb otg_default: driver failed to report `mode' property: -22
[    1.470934] tusb320_current_advertise_set: current advertise set to 2
[    1.470939] tusb320_probe: schedule_work 
[    1.470949] tusb320_probe: end
[    1.470968] tusb320_intb_work: start
[    1.471032] tusb320_i2c_init: end
[    1.471247] usbcore: registered new interface driver xpad
[    1.471280] usbcore: registered new interface driver usb_acecad
[    1.471312] usbcore: registered new interface driver aiptek
[    1.471334] usbcore: registered new interface driver gtco
[    1.471357] usbcore: registered new interface driver hanwang
[    1.471431] usbcore: registered new interface driver kbtab
[    1.471455] usbcore: registered new interface driver wacom
[    1.472146] tusb320_intb_work: attached_state is 1
[    1.472579] tusb320_intb_work: current mode is 2
[    1.472591] tusb320_intb_work: end
[    2.526693] usbcore: registered new interface driver dvb_usb_rtl28xxu
[    2.526743] usbcore: registered new interface driver uvcvideo
[    2.795159] usbcore: registered new interface driver bcm203x
[    2.795185] usbcore: registered new interface driver bpa10x
[    2.795211] usbcore: registered new interface driver bfusb
[    2.795239] usbcore: registered new interface driver btusb
[    2.795267] usbcore: registered new interface driver ath3k
[    2.914667] usbcore: registered new interface driver usbhid
[    2.914675] usbhid: USB HID core driver
[    3.646921] usbcore: registered new interface driver snd-usb-audio
[    3.673788] usb_otg_vreg: no parameters
[    3.673877] reg-fixed-voltage usb-otg-switch.66: Failed to find supply vin
[    3.673925] reg-fixed-voltage usb-otg-switch.66: Failed to register regulator: -517
[    3.673936] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    3.733650] qpnp-smbcharger qpnp-smbcharger-17: SMBCHG successfully probed batt=1 dc = 0 usb = 1
[    3.739448] usb_otg_vreg: no parameters
[    3.739473] usb_otg_vreg: supplied by smbcharger_external_otg
[    3.999866] usb_otg_vreg: disabling
[    4.043712] android_usb gadget: Mass Storage Function, version: 2009/09/11
[    4.043719] android_usb gadget: Number of LUNs=1
[    4.043958] android_usb gadget: android_usb ready
[    4.834951] init: Added '/init.usb.rc' to import list
[    4.835003] init: Added '/init.usb.configfs.rc' to import list
[    4.836237] init: Parsing file /init.usb.rc...
[    4.836800] init: Added 'init.angler.usb.rc' to import list
[    4.838040] init: Parsing file init.angler.usb.rc...
[    4.838773] init: Parsing file /init.usb.configfs.rc...
[    4.843185] ueventd: /sys/ rule /sys/devices/virtual/usb_composite/* enable
[    5.912247] init: Parsing file /vendor/etc/init/android.hardware.usb@1.0-service.rc...
[    6.885231] init: computing context for service 'usb-hal-1-0'
[    6.885638] init: starting service 'usb-hal-1-0'...
[    7.315203] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/mux_enabled': No such file or directory
[    7.315230] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/no_fwd_rmnet_links': No such file or directory
[    7.315257] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/no_rmnet_insts_per_dev': No such file or directory
[    7.315284] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/rmnet_data_init': No such file or directory
[    7.319499] init: starting service 'save-usb-config'...
[    7.320497] init: processing action (persist.sys.usb.config=* && boot)
[    7.320998] init: processing action (sys.usb.config=none && sys.usb.configfs=0)
[    7.321132] enable_store: android_usb: already disabled
[    7.412836] init: Service 'save-usb-config' (pid 515) exited with status 1
[   18.678325] init: processing action (sys.usb.config=none && sys.usb.configfs=0)
[   18.678655] enable_store: android_usb: already disabled
[   18.679956] init: processing action (sys.usb.config=mtp)
[   24.810856] msm-dwc3 f9200000.ssusb: DWC3 in low power mode
[  188.704317] init: processing action (sys.usb.config=none && sys.usb.configfs=0)
[  188.706082] init: processing action (sys.usb.config=adb && sys.usb.configfs=0)
[  188.706366] enable_store: android_usb: already disabled
[  869.006704] tusb320_irq_handler: start
[  869.006963] tusb320_intb_work: start
[  869.011027] tusb320_intb_work: attached_state is 0
[  869.011681] tusb320_current_advertise_set: current advertise is 2 already
[  869.011733] tusb320_intb_work: end
[  869.068558] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[  869.075971] msm-dwc3 f9200000.ssusb: DWC3 in low power mode
[  873.424160] tusb320_irq_handler: start
[  873.424478] tusb320_intb_work: start
[  873.429042] tusb320_intb_work: attached_state is 2
[  873.429092] tusb320_intb_work: Sink detected, perform TrySNK
[  873.431305] tusb320_current_advertise_set: current advertise set to 0
[  873.431327] tusb320_soft_reset
[  873.458501] tusb320_soft_reset
[  873.460292] tusb320_intb_work: schedule wdog work
[  873.460307] tusb320_drp_duty_cycle_set: set to 6
[  873.461811] tusb320_intb_work: end
[  873.663418] tusb320_irq_handler: start
[  873.663764] tusb320_intb_work: start
[  873.666851] tusb320_intb_work: attached_state is 2
[  873.666874] tusb320_intb_work: TrySNK fail, Sink detected again
[  873.666914] tusb320_drp_duty_cycle_set: set to 0
[  873.669964] tusb320_intb_work: end
[  873.692895] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[  873.736738] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[  873.736763] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  873.736774] usb usb1: Product: xHCI Host Controller
[  873.736785] usb usb1: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  873.736795] usb usb1: SerialNumber: xhci-hcd.0.auto
[  873.747874] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[  873.747887] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  873.747898] usb usb2: Product: xHCI Host Controller
[  873.747908] usb usb2: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  873.747919] usb usb2: SerialNumber: xhci-hcd.0.auto
[  874.199890] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[  874.235197] usb 1-1: New USB device found, idVendor=0cf3, idProduct=9271
[  874.235273] usb 1-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[  874.235288] usb 1-1: Product: UB93
[  874.235312] usb 1-1: Manufacturer: ATHEROS
[  874.235328] usb 1-1: SerialNumber: 12345
[  883.965993] init: processing action (sys.usb.config=none && sys.usb.configfs=0)
[  883.966262] tusb320_port_mode_set: REG_MODE_SET 0aH is 0x0
[  883.966602] usb 1-1: USB disconnect, device number 2
[  883.966746] tusb320_port_mode_set: port mode set to 1
[  883.967865] tusb320_rd_rp_disable: set
[  883.968221] tusb320_soft_reset
[  883.969171] usb usb2: USB disconnect, device number 1
[  883.974200] usb usb1: USB disconnect, device number 1
[  883.975828] type=1400 audit(1511360317.389:304): avc: denied { getattr } for pid=29 comm="kdevtmpfs" path="/bus/usb/002/001" dev="devtmpfs" ino=123585 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  883.976713] type=1400 audit(1511360317.389:304): avc: denied { getattr } for pid=29 comm="kdevtmpfs" path="/bus/usb/002/001" dev="devtmpfs" ino=123585 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  883.995034] tusb320_port_mode_set: REG_MODE_SET 0aH is 0x10
[  883.995380] tusb320_port_mode_set: port mode set to 1
[  883.995872] tusb320_rd_rp_disable: clear
[  884.009449] ueventd: removing platform device soc.0/f9200000.ssusb/f9200000.dwc3/xhci-hcd.0.auto
[  884.024419] init: processing action (sys.usb.config=midi,adb)
[  884.039062] msm-dwc3 f9200000.ssusb: DWC3 in low power mode
[  885.496850] tusb320_port_mode_set: REG_MODE_SET 0aH is 0x10
[  885.497618] tusb320_port_mode_set: port mode set to 1
[  885.499238] tusb320_rd_rp_disable: set
[  885.499907] tusb320_soft_reset
[  885.527860] tusb320_port_mode_set: REG_MODE_SET 0aH is 0x10
[  885.528579] tusb320_port_mode_set: port mode set to 0
[  885.529369] tusb320_rd_rp_disable: clear
[  885.723829] tusb320_irq_handler: start
[  885.724192] tusb320_intb_work: start
[  885.727272] tusb320_intb_work: attached_state is 2
[  885.727321] tusb320_intb_work: Sink detected, perform TrySNK
[  885.729266] tusb320_current_advertise_set: current advertise is 0 already
[  885.729317] tusb320_soft_reset
[  885.756017] tusb320_soft_reset
[  885.757786] tusb320_intb_work: schedule wdog work
[  885.757810] tusb320_drp_duty_cycle_set: set to 6
[  885.759754] tusb320_intb_work: end
[  885.959555] tusb320_irq_handler: start
[  885.959900] tusb320_intb_work: start
[  885.962664] tusb320_intb_work: attached_state is 2
[  885.962686] tusb320_intb_work: TrySNK fail, Sink detected again
[  885.962727] tusb320_drp_duty_cycle_set: set to 0
[  885.965727] tusb320_intb_work: end
[  885.985410] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[  886.030309] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[  886.030342] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  886.030353] usb usb1: Product: xHCI Host Controller
[  886.030363] usb usb1: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  886.030374] usb usb1: SerialNumber: xhci-hcd.0.auto
[  886.033815] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[  886.033828] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  886.033838] usb usb2: Product: xHCI Host Controller
[  886.033848] usb usb2: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  886.033858] usb usb2: SerialNumber: xhci-hcd.0.auto
[  886.483279] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[  886.509392] usb 1-1: New USB device found, idVendor=0cf3, idProduct=9271
[  886.509449] usb 1-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[  886.509474] usb 1-1: Product: UB93
[  886.509498] usb 1-1: Manufacturer: ATHEROS
[  886.509520] usb 1-1: SerialNumber: 12345


lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by bioteknik** [comment]
I'm having same issue. With newest Nethunter. Proper firmware installed did
reinstall. Same problem Same atheros chipset in TP Link- TL-WN722N

Older versions did not have this issue. Got to be from the update?

Anybody know which Kernel to install nethunter on Amazon Fire HD 8 (6th
Gen). I want to see if I have same issue on Fire HD tablet.

I have read you can put nethunter on A Fire HD tablet.

Only other device I have for comparison is a Galaxy s7 edge (2nd release)

And Galaxy Note 4

**Comment by jcadduono** [comment]
@geoff-github just use `modprobe ath9k_htc` in androidsu or kali terminal to load wifi driver

**Comment by geoff-github** [comment]
@jcadduino when I do that my terminal freezes and my device restarts

**Comment by jcadduono** [comment]
try unplugging device before doing that command

**Comment by geoff-github** [comment]
Tried that too, no errors when I run the command, but when I connect my USB WiFi Card, the phone locks up and restarts if its not connected when i run modprobe

**Comment by Prodject** [comment]
> use modprobe ath9k_htc in androidsu or kali terminal to load wifi driver
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0-g6af4dfa/modules.dep.bin'
modprobe: FATAL: Module ath9k_htc not found in directory /lib/modules/3.4.0-g6af4dfa

in latest nightly 2017.11-18-1618

**Comment by tjt263** [comment]
It's closed, but I see no solution.
