### ISSUE TITLE
nexus 7 nougat support

### ISSUE THREAD

**Issue by Jinovas** [offensive-security/kali-nethunter#1040]
This is more of a general question since I don't really see it in the nightly's link, but is there or will there be nougat support for nethunter on the nexus 7 2013 WiFi device? I only see the kernels going up to marshmallow. 

Reason I ask is I was wanting to install the lineage OS 14 on it along with nethunter.

Thx! =]

**Comment by computer777** [comment]
I am a bit curious as to the nexus 7 2012.

**Comment by bozwald** [comment]
Nexus 2012 7 has been declared unsupported as it is currently on an older type of linux kernel and has glibc issues.

**Comment by 0E800** [comment]
This looks promising in that it has an updated kernel. Just needs nethunter
kernel modules for HID and wifi injection.

https://builds.unlegacy-android.org/aosp-7.1/grouper/

**Comment by bozwald** [comment]
Nice ill check if it boots later. This is for the 2012 afaik thats grouper

**Comment by bozwald** [comment]
The kernel still needs to be updated for the grouper, https://forum.xda-developers.com/nexus-7/development/rom-beanstalk-rom-t3312870 is a nougat kernel for grouper wifi but it still runs on the kernel version that my non-updatable grouper is on. Its an old device too, not many devs are interested in updating it, I don't know how too.

**Comment by Jinovas** [comment]
Damn =( cuz I'm liking lineage os 14.1 with nethunter on my nexus 5. Especially due to storage limitations

**Comment by aLiArLa** [comment]
any updates? Is the 2013 model (flo) still supported? Where can I find the kernel for nougat? thanks

**Comment by ckz666** [comment]
looking also for a nougat kernel for my nexus 7 2013 deb. tried several custom kernel but no luck. external wifi ( awus036neh) don't come up. i use cm 14.1 (lineageos nightly).
