### ISSUE TITLE
Need libnexmonkali.so lib or sources of libfakeioctlkali.so

### ISSUE THREAD

**Issue by g3td0wn** [offensive-security/kali-nethunter#1043]
Currently having a Nexus 6P (angler) with Android O with Nexmon. Everything works excellent except frame injection, which was fixed in libnexmon release.
Currently we have only libfakeioctlkali to enable internal wifi monitoring from chroot, so please update it to libnexmon or release sources of it for community development.

**Comment by BesoBerlin** [comment]
do external wificards work with your setup?
And if so, which kind of OTG are you using? Any adapter or USB C OTG?
Thanks for answer!

**Comment by g3td0wn** [comment]
I don't use any external wificard. Nexmon is a thing to enable monitor mode and frame injections on internal wifi card. Also, everything seems to be working fine except frame injection, which was fixed by libnexmon lib

**Comment by BesoBerlin** [comment]
How did you built it to include nexmon? Did you integrate it yourself?

**Comment by Tyrell777** [comment]
Im stuck at this point:

- Nethunter works (but no monitor mode from nethunter kali terminal)
- Nexmon works (Monitor Mode in Nexmon works "outside of Kali terminal")
- Injection /Deauth etc. does not work

>> How can you integrate monitor mode in kali terminal (internal wifi chip) on Nexus 6P ?
>> Or atleast get injection at Nexmon working ?

Would be glad with ur advices. Im on it.

**Comment by rafaleon69** [comment]
Hey g3td0wn , can you or anyone share instructions on how to get libnexmon to work with Nexus 6p Oreo? 

I will really appreciate your inputs.
