### ISSUE TITLE
No HID Interfaces Detected

### ISSUE THREAD

**Issue by mehedishakeel** [offensive-security/kali-nethunter#1046]
### Device:
HTC Desire 630 Dual Sim

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

https://drive.google.com/file/d/0BzYhUtfIGkT1R0JqYW9JSXltQm8/view

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.4.0-perf-g0f068ea (and@AABM) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Thu Aug 18 14:53:56 CST 2016

## Issue:
No HID Interfaces Detected.
So HID Attack & Duckyhunter Attack not working

**Comment by jcadduono** [comment]
This is not a supported device by us. You will need to contact whoever made the zip. We have no idea who that is, sorry.

**Comment by sanam2n** [comment]
Hey, does it work on a Galaxy S4-i9500 Lollipop or do I have to install Full Chroot? (@jcadduono )
