### ISSUE TITLE
Duckhunter HID attaks not working while normal HID ttaks work

### ISSUE THREAD

**Issue by j3223** [offensive-security/kali-nethunter#1047]
### Device:
Nexus 5x Bullhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.0.0

### Built from repo (date and build command) or downloaded from website (links):
Custom Build for nougat android..

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.73kali-gddc7121 (root@nhbuild.box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) #2 SMP PREEMPT Wed Aug 2 4 20:47:30 CDT 2016

## Issue:
HI, every time I start a ducky script via the play button I get a popup reading "Launching Attak" and "Attak Launched", but nothing happens on the computer. And the normal HID Attaks work without a problem. BTW I had to manually update the terminal for it to work, but now it works fine...
THX for your help:)

**Comment by bozwald** [comment]
Hi is it working for you then

**Comment by j3223** [comment]
No, that's the Problem... The normal HID attaks work but the Duckhunter HID attaks don't work, but it gives me the "attaks launched" notification

**Comment by bozwald** [comment]
Hmm mine works opened a text editor on my Mac plugged in and ran it and it worked as expected. I'm on a new build, try it, Bluetooth updated Hid working updated kernel,

https://bozwald.com/nethunter/nethunter-bullhead-nougat-kalifs-full-2.0.zip

To use, flash twrp, then latest magisk zip, then the zip I linked.

Then once installed reinstall terminal like u did here and add this to your custom commands in NH app to exec from boot in Kali terminal to get hid up

setprop sys.usb.config none. && sleep 1 && setprop sys.usb.config hid

**Comment by bozwald** [comment]
U can see source on my page and its build with nethunter build.py

**Comment by j3223** [comment]
Thx, TWRP already Installed, but what do u mean with magisk zip?
Again thank you for the fast reply!

**Comment by bozwald** [comment]
Download the latest version of magisk and flash that zip and check it boots
and then go back into twrp and boot the new nethunter zip

**Comment by bozwald** [comment]
I downloaded the latest 7.1.2 nougat build for bullhead from google

Ran the flash-all.sh or .bat,

Booted and went through setup

Rebooted into download mode and fastboot flash recovery twrp(latest
bullhead)

Fastboot reboot-bootloader
Fastboot erase cache

Fastboot reboot-bootloader

Enter recovery mode twrp

Install latest magisk 14.3

Stay in twrp and back to advanced wipe wipe cache and cache dalvik

Boot up if all ok boot back into twrp

Flash zip, advanced wipe cache

Booted up for me, may have bootlooped once maybe even into twrp but I just
system rebooted from menu if that did happen 

Then add the custom boot command in nethunter menu

**Comment by j3223** [comment]
Hi, I am in TWRP installing the new nethunter zip, the steps before worked flawlessly:] I will comment again and close the Issue when the install is complete and the HID works. Bye

**Comment by j3223** [comment]
THANK YOU!! It all worked perfectly, now the Duckhunter scripts also work! I am happy to have everything up and running. 
THX and have a nice day :] :]
