### ISSUE TITLE
Nexus 7 2013 (flo) Android 6.0.1 (marshmallow) + TP-LINK TL-WN722N (v2) = Not working

### ISSUE THREAD

**Issue by novicov** [offensive-security/kali-nethunter#1054]
### Device:
Nexus 7 2013 (flo)  WIFI

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
 Android 6.0.1 (marshmallow)
Nethunter: nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip
Kernel: kernel-nethunter-flo-marshmallow-2017.11-18-1618.zip 

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/2017.11-18-1618/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gae95f7e-dirty (root@nhbuild-box) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Jul 29 23:09:11 CDT 2016

## Issue:
 TP-LINK TL-WN722N (v2) with usb hub with power (gembird uhb-otg-02) not working (led on Tp-link not blinking)

**Comment by seventhplug** [comment]
Your wifi adapter s not supported

**Comment by novicov** [comment]
Stock ROM, Android 6.0.1. But here (https://github.com/offensive-security/kali-nethunter/wiki/Wireless-Cards) this WiFi card is in supported list.

**Comment by kimocoder** [comment]
v1 is ath9k_htc (which has good support) but v2 uses rtl8188eu chipset (which got no support for either monitor or injection)

**Comment by novicov** [comment]
OMG. I search info about this and i know about TP-Link TL-WN822N v4, that not supported. TP-LINK TL-WN821N  is supported or not? And TL-WN821N is better than WN722N?

**Comment by kimocoder** [comment]
The TL-WN821N v1 and v3 is supported because someone (infact med with some others) digged up a solution for the carl9170 injection issue. BUT! the kernel NEEDS to be patched in order to be supported.

The patch may be found [here](https://github.com/offensive-security/wireless-patches)
Info about the bug report & solution is also postes there.

It's only 2 months since the solution was releases, so the kernel would most likely have to be downloaded, patched and compile.

**Comment by novicov** [comment]
I tried to connect the model TP-LINK TL-WN822 v3, but the indicator for some reason did not blink the adapter. This model always has a RTL8192CO chipset and is suitable for 100% for nethunter and nexus devices or not?

**Comment by sezusatish** [comment]
hi admin
i am using Device : Nexus 7 2013 (flo) WIFI
Android 6.0.1 (marshmallow) 
Nethunter: nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip
Kernel: kernel-nethunter-flo-marshmallow-2017.11-18-1618.zip
i download the file from this links and install them using  TWRP   and using Y cable to connect tp link wn722n v1 but  its not even led on Tp-link not blinking in lsusb able to see but i use wiconfig not able to see or detect sir kindly asst me

**Comment by novicov** [comment]
@Re4son it was fixed?

**Comment by Re4son** [comment]
Doesn't look like it and, whilst I hate saying it, I don't think it will ever come.
The last kernel was released 3 years ago supporting all the hardware that was current at that time and for which patches were available. If no one has felt inclined to update that kernel to support newer hardware then it is very unlikely to ever happen.
