### ISSUE TITLE
aw1ck's nethunter fork of djb77's tgp kernel for Galaxy S8

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#1055]
I have loooked at aw1cks forked kernel and it looks to have most of what NH needs. I spoke to djb77 via telegram and he said as far as he can tell it has nothing different to do with nethunter. I dont have a pc/laptop and am having trouble building the kernel inside nethunter chroot to tell which is correct. Any body willing to test?

**Comment by aw1cks** [comment]
I haven't really had any time to test the kernel any further. Last time I tried I couldn't get the kernel to build and a few of the recommended patches don't work on the 4.x branch. I'd be happy to keep trying if anyone could suggest how I should be going about patching the 4.x branch kernels... I've ported nethunter to other devices before but always on the 3.x branch where I didn't have trouble patching the kernel.
