### ISSUE TITLE
Oneplus 3t  android7.1.1  not detecting  TL-WN722N v1(AR9271)

### ISSUE THREAD

**Issue by KILAsteins** [offensive-security/kali-nethunter#1056]
### Device:
oneplus3T H2OS3.5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
h2os v3.5 ,  android 7.1.1

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-arm64-kalifs-full-rolling-2017.11-18-1618.zip
https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-oneplus3T-oos-nougat-2017.11-18-1618.zip

## Output of cat /proc/version in adb shell or NetHunter Terminal:
Linux version 3.18.31-perf++ (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jul 17 13:44:23 CDT 2017

## Issue:
It seems nothing wrong but oneplus3T didn't detected any devices already...i tried reinstall linux-firmware without any issues but nothing changed.  thanks for any answers

**Comment by domald** [comment]
root@kali:~# modprobe ath9k_htc
root@kali:~# lsmod
Module                  Size  Used by
ath9k_htc              64779  0
ath9k_common           27230  1 ath9k_htc
ath9k_hw              437928  2 ath9k_common,ath9k_htc
mac80211              556488  1 ath9k_htc
ath                    30516  3 ath9k_common,ath9k_htc,ath9k_hw
wlan                 5801819  0
root@kali:~

**Comment by domald** [comment]
then
root@kali:#ifconfig wlan1 up
