### ISSUE TITLE
GS5 (klte) duckhunter HID keyboard not working

### ISSUE THREAD

**Issue by rhinedev** [offensive-security/kali-nethunter#1057]
### Device:
Galaxy S5 (klte)

### OS version (Nougat):
Nougat, lineage-14.1-20171123-nightly-klte-signed.zip

### Built from repo (date and build command):
update-nethunter-klte-nougat-20171127_050752

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.113-nethunter-klte-xx-3.0(jc@arkyn) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP PREEMPT Sat Sep 2 14:08:48 EDI 2017

## Issue:
When I try to run the Duckhunter HID keyboard attack it doesn't work

**Comment by rhinedev** [comment]
i did some additional research and found out that HID keyboard is not supported for klte? https://github.com/pelya/android-keyboard-gadget

**Comment by jcadduono** [comment]
it should work just fine, i tested it not long ago, i dont know why its not working for you

**Comment by ishmaria** [comment]
I have this problem too. I'm using GS5 Verizone with Resurrection Remix (Nougat version). I flashed nougat kernel of klte (I tried kltevzw version and lollipop version first as RR rom is based on lollipop but they were giving errors in mounting storages). 
Now my HID mouse is working fine but HID keyboard and HID attacks are not working. I've flashed kernel many times.
Is there any solution? Please guide.

**Comment by ishmaria** [comment]
I noticed a thing. When I start HID from nethunter app it creates (or modifies) usb.config.tmp_hid files in /data/local. But there is no file in this folder with this name. Only usb.config.tmp file. Also kali terminal can't see /data folder. Only ESexplorer shows this folder.

**Comment by jcadduono** [comment]
Pressing the hid enable button in NetHunter app will likely break all usb features on klte. Klte has HID passively enabled on boot and should not need enabling.
Yeah NetHunter app needs to ask for shell permission to see /data/local as nonroot. Strange it should be running in root mode.
Just boot phone normally, make sure it's in permissive, then see if hid keyboard app works
