### ISSUE TITLE
error in kali

### ISSUE THREAD

**Issue by neetesshhr** [offensive-security/kali-nethunter#1058]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
kali linux

## Issue:
 apt-get update
Ign:1 http://security.kali.org/kali-security sana/updates InRelease
Ign:2 http://http.kali.org/kali sana InRelease
Err:3 http://security.kali.org/kali-security sana/updates Release
  404  Not Found
Err:4 http://http.kali.org/kali sana Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://security.kali.org/kali-security sana/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://http.kali.org/kali sana Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by neetesshhr** [comment]
please fix this problem

**Comment by kimocoder** [comment]
Open /etc/apt/sources.list and change "sana" to "kali-rolling" since "sana" is outdated and not in repos anymore.
