### ISSUE TITLE
Airodump fixed channel with Nexmon on Nexus 5

### ISSUE THREAD

**Issue by PeaCarChoo** [offensive-security/kali-nethunter#1062]
### Device:
Nexus 5 D821

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Stock OS: hammerhead-m4b30z-factory-625c027b.zip
SuperSU rooted.
nethunter-generic-armhf-kalifs-full-rolling-3.15.4-2017.11-18-1618.zip
kernel-nethunter-hammerheadmon-nougat-3.15.4-2017.11-18-1618.zip
Had to install Nexmon from Nexmon app: Nexmon ROOT Broadcom WiFi_v2.1.3.apk

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-ElementalX-NS-7.09 (root@AutinDroid) (gcc version 4.8 (GCC)) #1 SMP PREEMPT Mon Jan 23 18:34:26 EST 2017

## Issue:
I have freshly installed as above. I can capture WiFi using the internal Wifi card (Nexmon) with airodump-ng quite well. However if I want to target a particular channel using "airodump-ng --channel 6 wlan0" then airodump does predominately capture on channel 6 but annoyingly hops as well, which must be caused by an external process. If I run "airomon-ng check" then I see only wpa_supplicant is running, I can kill this with "airomon-ng check kill" but it restarts as another process. If I try to to do a capture before another wpa_supplicant process starts then doing monstart-nh lists "__nex_driver_io: error" twice and running airodump works but no WiFi is captured. Also if I remove wpa_supplicant the same happens. It seems like the Nexmon driver needs the wpa_supplicant running to work.
Also if I turn off WiFi in Settings->Wi-Fi again source monstart-nh has the same error.
I'll add I'm not using the Wifi to connect to a network and all network credentials have been forgotten.
Note: I have also seen this issue on the Nethunter OS

Apologies if this is more a Nexmon issue than a nethunter issue. But I'd appreciate knowing if others see the same.

**Comment by numaphlex** [comment]
Mate, let me try to understand. As i`m trying to accomplish something similar, maybe we could help each other.

You said hammerhead-m4b30z-factory and pointed Nougat as the OS, i think that m4b30z image is 6.0.1 Marshmallow. So you gonna need another kernel than kernel-nethunter-hammerheadmon-nougat-3.15.4-2017.11-18-1618.zip you wanting the marshmallow one instead this one. It`s cool and easy to build your own Nethunter just running a script on Mac or Linux, all automated. In the end you will get a more updated image. Or you gonna need another Stock, BUT they have to match. Stock and Kernel. You can't mix them up.

I`m trying with:
1 - twrp flash cm-13.0-20161222-SNAPSHOT-ZNH5YAO3Z2-hammerhead + opengaps nano + supersu and reboot
2 - configure adb and reboot to recovery and twrp flash my own nethunter-hammerheadmon-marshmallow-nobrand-kalifs-full-20180212_164839

I`m trying with hammerhead mon, cm and the just hammerhead one. But with no lucky yet on running the Nexmon apk wich would be cool to have both, if possible.

If i put Nexmon, before step 2 the Airdump option from that Apk shows all APs around, if i put after the Nethunter flash it does all weird stuff to the Wlan0. I know about the monstart-nh and stuff. But don't known the right order to input it while im testing so i haven't made it work yet.

I read on other thread or somewhere that the Nexmon developer saying:
"In the end, you only need to integrate the bcmdhd driver and the resulting firmware from https://dev.seemoo.tu-darmstadt.de/bcm/bcm-public/tree/master/firmware_patching/nexmon into the Nethunter kernel to activate monitor mode and frame injection for Nethunter on the Nexus 5."

So i think next step is to install nethunter only and inside the Kali shell compile it by hand and install this .ko file after copying the firmware to /lib/firmware/brcm/, or something. I don`t like to ask for help and stuff, but i`m seeking it as a ultimate resource, i wanted bad to have them both, even tho i prefer the nethunter, it`s more a matter of OCD than something else.
