### ISSUE TITLE
Nexus 6p with nexmon

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#1064]
### Device:

6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat / Oreo

### Built from repo (date and build command) or downloaded from website (links):

Latest Nightly for either.

## Issue:

I just purchased a 6p and im having troubles getting nexmon to work.
On stock Oreo I couldnt install the tools and on lineage i can istall tools but it wont recognise that the wifi chip is broadcom. 
Could some please tell me which roms, kernels and nethunter versions they have working with their 6p.
Thanks

**Comment by anonimo0001** [comment]
io ho risolto con questa rom https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e e il  kernel  https://github.com/nethunteros/android_kernel_lge_hammerhead
