### ISSUE TITLE
Terminal Crash || No Title) || root permission is granted /system/bin/bootkali-login/ ||

### ISSUE THREAD

**Issue by activious** [offensive-security/kali-nethunter#1065]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
No title terminal crash

**Comment by D13man** [comment]
Try uninstalling the terminal that Nethunter comes with and install the one from here: https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/Term-nh.apk

In my case, this fixed it.

Hope it helps.

**Comment by somnath003** [comment]
Me too suffering from same problem help me..
