### ISSUE TITLE
Can't install NetHunter 

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#1066]
### Device: 
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Download from site:
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
After attempting to reinstall from the app to fix the terminal issue, I get this error:
javax.ssl.SSLHandshakeException: No valid pins found in chain!

## Issue:
Can't reinstall via NetHunter app, app on latest

**Comment by bozwald** [comment]
You can use the build I'm running if you want to try it out

https://bozwald.com/nethunter/nethunter-bullhead-nougat-kalifs-full-2.0.zip

Everything working here you'd need to install twrp..magisk...my zip

Fyi jcadduono effectively made my zip kernel is feature rich

**Comment by BearChavez** [comment]
@bozwald  I'm guessing I'd install the nexmon kernel too so I can use monitor mode and such?

**Comment by bozwald** [comment]
Nexmon isn't for 5x you'd need an adaptor and a WiFi dongle, nexmon is for
5 and 6, 5x has a different WiFi chip

**Comment by BearChavez** [comment]
@bozwald I have Nexus 5

**Comment by bozwald** [comment]
Ah in the op it says 5x I can't help sorry

**Comment by spaul13** [comment]
@bozwald, your link work perfectly well for me on an android device where Nougat is installed. Thanks for that.

But can u (or anyone else) please give any NetHunter version for Android Oreo and for Lineage OS (15.1)?
Thanks in advance
