### ISSUE TITLE
Installation successful, No OS

### ISSUE THREAD

**Issue by descaraito** [offensive-security/kali-nethunter#1067]
![4](https://user-images.githubusercontent.com/34683270/34173727-71689a80-e4c4-11e7-94a5-50aecb841efb.jpg)
### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 

 E:error opening /data/local/nhsystem/kali-armhf/dev/ram3
.
.
.

**Comment by JasonDemitri** [comment]
For one did you wipe the caches after installation, secondly read on another post these red errors are the installation trying to follow symlinks that no longer exist and should be ignored ?

**Comment by descaraito** [comment]
Hi JasonDemitri, Yes I wiped the caches and also after seen the  red errors I ignored them and reboot the device, that is when it got stuck in the google logo, and if I go back to recovery it says there is no OS installed.  After that I went and installed the stock image, re rooted it and reinstalled nethunter and same thing happened.  I am wondering if I have to installed a custom android image first and then install nethunter after.

**Comment by JasonDemitri** [comment]
Just to clarify installation instructions for Nexus 7 (2013) flo
Make sure you have adb & Fastboot :)
Download the original rom for google >>https://dl.google.com/dl/android/aosp/razor-mob30x-factory-52684dff.zip 
Unzip into location on your computer
Connect Phone in debug mode and run the flash-all script 
This will make sure you have the correct STOCK OS
REBOOT THE DEVICE
Next Download and flash TWRP for the flo device
REBOOT THE DEVICE
Next Download the nethunter ROM from here >>https://www.offensive-security.com/kali-linux-nethunter-download/
Load onto usb-otg or push the the devices using adb
I then flash superSu from their site however the installer gives the option 
REBOOT THE DEVICE
Run the nethunter installer from TWRP making sure to clear the cache after
REBOOT THE DEVICE
Install the latest kernel from the nightlies if needed :)
I have just done this and had it working same devices same OS im having issues with Cyogenmod13 and nethunter
