### ISSUE TITLE
Kernel not found for htc_pme

### ISSUE THREAD

**Issue by Sofianebens** [offensive-security/kali-nethunter#1068]
### Device:
HTC pme

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
nougat

### Built from repo (date and build command) or downloaded from website (links):
downloaded

## Issue:

Hi,

I've been trying to install nethunter and everything goes fine except for the fact that there is no kernel in /device/nougat for the htc 10. I tried to find one in the internet but it's like I'm the only one using this device...
Any recommendations?

**Comment by bozwald** [comment]
I'm by no means HTC expert but you can try with the lineage os kernel they
built them for pme

**Comment by sylar1233** [comment]
You much to change to HTC pmewl 
But you pay by sunshine for the unlock 
And you can change too us version 
This kernel is for HTC stock rom us not compatible to other roms
