### ISSUE TITLE
SIM detect issue,decteded and undecteded 

### ISSUE THREAD

**Issue by zcyang668** [offensive-security/kali-nethunter#1070]
### Device:
oneplus5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
2017.11.18-1618

## Issue:
no SIM

**Comment by BesoBerlin** [comment]
same issue, it detects and looses again, continuesly. have you soled this iisue?
