### ISSUE TITLE
changing build.py to use environment to locate python binary

### ISSUE THREAD

**Issue by Divyangchauhan** [offensive-security/kali-nethunter#1072]
General issue with build.py script

## Issue:
I was using virtualenv for building nethunter but it didn't work as it was using system python executable which is python3.

changing first line of script from #!/usr/bin/python to #!/usr/bin/env python solves this issue.

**Comment by JonasCardoso** [comment]
This problem? I have this

Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by Divyangchauhan** [comment]
you need to install requests by using pip

use pip install requests to install.

**Comment by Divyangchauhan** [comment]
I created pull request to do that hope it gets accepted.
https://github.com/offensive-security/kali-nethunter/pull/1075
