### ISSUE TITLE
Camera and Flashlight is not working on Samsung Galaxy S5 (KLTESPR) using Nightly Kernel

### ISSUE THREAD

**Issue by Mhegumi** [offensive-security/kali-nethunter#1074]
### Device:

Samsung Galaxy S5 (KLTESPR)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

Ressurection Remix Marshmallow 6.0.1_r74 - MOB31K

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

kernel-nethunter-kltespr-marshmallow-3.15.4-20170629-1630

## Issue:

Hi, 

I am using a Samsung Galaxy S5 kltespr version with nethunter.
Everything is working fine but after I flashed the kernel from nethunter nightly, Camera and Flashlight isn't working anymore.

ROM: ResurrectionRemix-M-v5.7.4-20161121-kltespr
BASE ON: CyanogenMod 13

Thanks in advance :)

**Comment by Shubhamjuggu** [comment]
Hi, Mhegumi. I have Samsung Galaxy S5 G900H (k3g, not klte). Can I install this ROM on my phone?

**Comment by Shubhamjuggu** [comment]
Hi, Mhegumi. I have Samsung Galaxy S5 G900H (k3g, not klte). Can I install this ROM on my phone?
Any other alternatives ?

thanks in advance.

**Comment by Mhegumi** [comment]
Sure but I'm not sure if the rom will compatible on your device since you have a different variant.
You can get the rom from this link below:
https://forum.xda-developers.com/galaxy-s5/unified-development/rom-ressurrection-remix-mm-t3275340

**Comment by Mhegumi** [comment]
I was also tried another updated rom of resurrection remix and then every thing is working except of having a problem with MTP connection while connected to PC. (after then installation of kethunter kernel)

Resurrection Remix N KLTE [5.8.5]
ROM File: RR-N-v5.8.5-20171231-kltedv-Final (stable for SPR variant)
Android Version: 7.1.2
Base rom: Lineage OS

Nightly Kernel Used: kernel-nethunter-kltespr-nougat-2017.11-18-1618


https://forum.xda-developers.com/galaxy-s5/unified-development/rom-resurrection-remix-n-klte-t3510376

**Comment by Shubhamjuggu** [comment]
Thanks for replying bro.
Will this ROM also work for k3g/galaxy s5 sm-g900h ?

**Comment by Shubhamjuggu** [comment]
ohkie apart from MTP is there any other bug you are facing ? Fingerprint
scanner is working or not ?

**Comment by Shubhamjuggu** [comment]
Is there any possible way to port this ROM for k3g variant ?

**Comment by tomford007** [comment]
Can someone point me to the proper kernel to use with Samsung S5 klte T-Mobile 900T with CM14 on Nougat 7.1 please? Thanks!
