### ISSUE TITLE
Nexus 6P OREO Dongle-less Monitor Mode/Injection HELP

### ISSUE THREAD

**Issue by geek-str1k3** [offensive-security/kali-nethunter#1077]
### Device:

Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

OREO 8.0

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/2017.11-18-1618/ Angler Oreo

## Issue:

Please can somebody help with that thing [binkybear/NETHUNTEROS.MD], Is it possible to somehow move/transfer this project to Oreo is there anything could be done for donlge-less injection and monitor mode in chroot, i think radio patch is needed and libfakeioctlkali+libnexmonkali.so, Please HELP
SOS

**Comment by LazerL0rd** [comment]
Hopefully Oreo support for Kali comes to the Nexii soon.
