### ISSUE TITLE
Unable to detect wlan1 with wifi usb adapter alfa awus036neh  and zenfone 2

### ISSUE THREAD

**Issue by moziiTL** [offensive-security/kali-nethunter#1083]
### Device:
Zenfone 2

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
lollipop 5.0

## Issue:
Hi guys,

Well I'm pretty new into this, so I did what I could, please try to help me with simple words ;-)

I have bought 2 wifi usb adapter : the first on was TL-wn722n in v2.0 thus i understood that it could not work with nethunter anymore (due to chipset issue) then I have bought an alfa awus036neh which is seen as a good one to be used with kali nethunter.
Still, both of theme, but let's work on the alfa one is not recognized by kali while I do the airmon-ng command, this is what I get :

phy0 wlan 0 ?????? unable to detect for sdio 0x02d0 : 0x4335

However, when I plug the alfa on my phone, the blue light is on.

What could I do, what information can I bring to you making it more clearly ?

Thank guys !

**Comment by moziiTL** [comment]
Well, I have tried to reinstall Nethunter from the recovery mode, apparently succesfull but now I cannot even open the kali terminal. Thus windows just shut down.
Any ideas guys ?

Thanks

**Comment by moziiTL** [comment]
Ok, I keep answering myself, just to let you know, I got back the kali terminal working again, but still not have the wlan1 with the usd adapter pluged in.

What can I do guys ?

**Comment by bozwald** [comment]
Its getting power which is clear from the light but perhaps not enough have
you used a powered usb hub? To give the adaptor 5v from elsewhere?

Could also be that the kernel doesn't support the device, therefor not
bringing the interface up.. what kernel are you using and from what build?
If we can look at the source git then we can look to see if it's listed
what was the output of your cat /proc/version

Can you also provide a dmesg | tail from when you plug in the device?

**Comment by moziiTL** [comment]
Hi bozwald,

>  Its getting power which is clear from the light but perhaps not enough have
> you used a powered usb hub? To give the adaptor 5v from elsewhere?

Not i'm not using a powered usb hub, direct pluged with a OTG cable from the phone to the usb adapter.

> what kernel are you using and from what build?

The kernel I use is this one :
FlareX_V1.0_Nethunter _ AnyKernel 2.0

> If we can look at the source git then we can look to see if it's listed
> what was the output of your cat /proc/version

How should I give you this information ?

> Can you also provide a dmesg | tail from when you plug in the device?
![screenshot_2018-01-25-14-33-39](https://user-images.githubusercontent.com/35452919/35390895-3cf77966-01dd-11e8-9346-7cb87e05696f.jpg)

**Comment by moziiTL** [comment]
cat /proc/version is :

> Linux version 3.10.101_Flarex_V1.0 (FlareM@Zenfone2-Dev) (gcc version 5.3.1 20160113 (Linaro GCC 5.2-2016.02) ) #0 SMP PREEMPT Thu Apr 21 21:37:19 IST 2016

**Comment by bozwald** [comment]
Kernel source: https://github.com/Zenfone2-Dev/Flare-AEL-X
found via https://forum.xda-developers.com/zenfone2/development/ze551ml-kernel-flarex-t3366039

with my noob eyes it show that mac80211 support was added to that kernel... which leads me to think it could be that you'd need an externally powered USB Hub to power it, you can get DC/AC ones or a USB Micro powered ones, which a standard phone charger could power which can grant mobility. 

I know this is odd too, but when you connect your USB Adaptor, do you plug in the device to the adaptor first then into the phone, or do you plug the adaptor in the phone, then the wifi into the adaptor?

I had an issue with a nexus that it would bring the interface up only when I plugged the wifi into the adaptor and then into the phone. 

what do you get when it's plugged in and the blue light is on and perform the command 
`dmesg | grep usb`

I want to help you isolate whether it's a power issue, or kernel :)

**Comment by moziiTL** [comment]
Thank you Bozwald,

I am downloading that kernel version and will try to install it.

Regarding the connecting order, I plug the wifi to the adapter then to the phone.

When wifi is plugged plus the command dmesg | grep usb, this is what I get :
![screenshot_2018-01-25-16-27-21](https://user-images.githubusercontent.com/35452919/35396403-05bab0a2-01ed-11e8-828b-67a832948a6d.jpg)

Thanks

**Comment by bozwald** [comment]
No sorry for bad formatting, that infact is the kernel you're using as far
as I can see, but go ahead anyway fresh builds surprise us all sometimes.

**Comment by moziiTL** [comment]
Ok I'll try it.

Regarding a powered usb hub, I am actually trying this :
- USB hub plugged on power.
- Phone plugged on the hub
- Wifi usb plugged on the hub

Then, the airmon-ng command on kali, it shows the same issue : nothing only phy0 wlan0 unable to detect sdio etc ...

I get back soon to you with the kernel I have downloaded.

Thanks

**Comment by moziiTL** [comment]
Oops, this seems to be a not flashable kernel. I don't know how to install it, this seems so complex when I look at the description page.
Must I install this version ? Isn't there any other way to solve my issue ? :-)

Thanks

**Comment by bozwald** [comment]
That's the kernel source, it would need to be built with a relevent
toolchain, I'm not proficient at building kernels but if you're adventurous
there are some guides at building them but then again when I tried I got
stuck adding features to the kernel but was able to build them with the
guides and maybe a couple of googled tweaks/fixes unfortunately I'm not
sure if this device is supported by people so it's best endeavours really

**Comment by moziiTL** [comment]
Ok Thanks Bozwald,

I will try to get closer to the man who built  the kernel at xda-developers.
Thank you anyway for your time, if you have any other idea feel free.

Cheers.
