### ISSUE TITLE
Awus036h crash nethunter

### ISSUE THREAD

**Issue by keysersoze930** [offensive-security/kali-nethunter#1085]
### Device:

Nexus 4

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Lollipop

## Issue:
hello I have a problem with my alpha card "awus036h" when I plug it with my Y cable it is detected by "lsusb" but when I try to switch to monitor mode the phone crash and reboot. I tried on "lollipop" and "kitkat" always the same problem and on "cm13" the card is not even detected. Please help (sorry for my bad English I'm french)

**Comment by keysersoze930** [comment]
@binkybear help please

**Comment by sylar1233** [comment]
Wath say the Command airmon-ng ?
Is rhat a Plug and Play Adapter or your need drivers?

**Comment by keysersoze930** [comment]
I tried with a card alfa AWUS036NEH and there is no problem I can put it in monitor mode and do my attack, but with the AWUS036H that I plug the phone freezes and redemare so I think it uses too much power the drivers are well install and airmon displays wlan1

**Comment by alphaomicron** [comment]
Stay with the first card then. If it works you're ok
