### ISSUE TITLE
Can't update or install metapackages

### ISSUE THREAD

**Issue by bpartin2009** [offensive-security/kali-nethunter#1087]
### Built from repo (date and build command) or downloaded from website (links):
Rolling-generic-armfh-full-zip Nov 17 then
Kernal-nethunter-shamu-nougat-11-18-17.zip both from nightly.

## Issue:
root@kali:~# cat /proc/version
Linux version 3.10.40-g90f4f12 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Jan 25 18:18:56 CST 2017
root@kali:~# ls
root@kali:~# ls
root@kali:~# cd ..
root@kali:/# ls
bin       dev          home   mnt   root  sdcard  system  var
boot      etc          lib    opt   run   srv     tmp
captures  external_sd  media  proc  sbin  sys     usr
root@kali:/# cd sdcard/
root@kali:/sdcard# ls
Alarms         Podcasts
Android        Ringtones
DCIM           TWRP
Download       Tasker
Movies         kaliNethunter.zip
Music          kernel-nethunter-shamu-nougat-2017.11-18-1618.zip
Notifications  nh_files
Pictures       supersu.zip
root@kali:/sdcard# cd ~
root@kali:~# ls
root@kali:~# apt-get update
Hit:2 https://packages.microsoft.com/ubuntu/14.04/prod trusty InRelease
Get:1 http://archive-7.kali.org/kali kali-rolling InRelease [30.5 kB]
Err:1 http://archive-7.kali.org/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: GPG error: http://archive-7.kali.org/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@kali:~#

Last login: Sat Feb  3 14:04:46 UTC 2018 on pts/2

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# busybox
BusyBox v1.27.2 (Debian 1:1.27.2-1) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, acpid, adjtimex, ar, arp, arping, ash, awk, basename,        blkdiscard, blockdev, brctl, bunzip2, bzcat, bzip2, cal, cat, chgrp,
        chmod, chown, chroot, chvt, clear, cmp, cp, cpio, cttyhack, cut, date,
        dc, dd, deallocvt, depmod, devmem, df, diff, dirname, dmesg,        dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, egrep, env,
        expand, expr, factor, fallocate, false, fatattr, fgrep, find, fold,
        free, freeramdisk, fsfreeze, fstrim, ftpget, ftpput, getopt, getty,
        grep, groups, gunzip, gzip, halt, head, hexdump, hostid, hostname,
        httpd, hwclock, i2cdetect, i2cdump, i2cget, i2cset, id, ifconfig,
        ifdown, ifup, init, insmod, ionice, ip, ipcalc, ipneigh, kill, killall,
        klogd, last, less, link, linux32, linux64, linuxrc, ln, loadfont,
        loadkmap, logger, login, logname, logread, losetup, ls, lsmod, lsscsi,
        lzcat, lzma, lzop, md5sum, mdev, microcom, mkdir, mkdosfs, mke2fs,
        mkfifo, mknod, mkpasswd, mkswap, mktemp, modinfo, modprobe, more,
        mount, mt, mv, nameif, nc, netstat, nl, nproc, nsenter, nslookup, od,
        openvt, partprobe, paste, patch, pidof, ping, ping6, pivot_root,
        poweroff, printf, ps, pwd, rdate, readlink, realpath, reboot, renice,
        reset, rev, rm, rmdir, rmmod, route, rpm, rpm2cpio, run-parts, sed,
        seq, setkeycodes, setpriv, setsid, sh, sha1sum, sha256sum, sha512sum,
        shred, shuf, sleep, sort, ssl_client, start-stop-daemon, stat, strings,
        stty, svc, swapoff, swapon, switch_root, sync, sysctl, syslogd, tac,
        tail, tar, taskset, tee, telnet, test, tftp, time, timeout, top, touch,
        tr, traceroute, traceroute6, true, truncate, tty, ubirename, udhcpc,
        udhcpd, uevent, umount, uname, uncompress, unexpand, uniq, unix2dos,
        unlink, unlzma, unshare, unxz, unzip, uptime, usleep, uudecode,
        uuencode, vconfig, vi, w, watch, watchdog, wc, wget, which, who,
        whoami, xargs, xxd, xz, xzcat, yes, zcat
root@kali:~#
Last login: Sat Feb  3 04:58:05 UTC 2018 on pts/2

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# airmon-ng check

Found phy0 with no interfaces assigned, would you like to assign one to it? [y/n] y

 ERROR adding monitor mode interface: command failed: Operation not supported (-95)

Found 1 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

  PID Name
 1514 wpa_supplicant

root@kali:~# kill 1514
root@kali:~# airmon-ng check

Found phy0 with no interfaces assigned, would you like to assign one to it? [y/n] y

 ERROR adding monitor mode interface: command failed: Operation not supported (-95)

Found 1 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

  PID Name
32111 wpa_supplicant

root@kali:~# ifconfig
dummy0: flags=195<UP,BROADCAST,RUNNING,NOARP>  mtu 1500
        inet6 fe80::ac77:c7ff:fe74:aec7  prefixlen 64  scopeid 0x20<link>
        ether ae:77:c7:74:ae:c7  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 210 (210.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 290  bytes 37978 (37.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 290  bytes 37978 (37.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

rmnet_usb0: flags=65<UP,RUNNING>  mtu 2000
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether e0:98:61:c6:be:39  txqueuelen 1000  (Ethernet)
        RX packets 624280  bytes 910953385 (868.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 202840  bytes 17232239 (16.4 MiB)
        TX errors 0  dropped 10 overruns 0  carrier 0  collisions 0

root@kali:~# airmon-ng start wlan0

Found phy0 with no interfaces assigned, would you like to assign one to it? [y/n] y

 ERROR adding monitor mode interface: command failed: Operation not supported (-95)

Found 1 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

  PID Name
32111 wpa_supplicant

PHY     Interface       Driver          Chipset

phy0    wlan0           ??????          non-mac80211 device? (report this!)

ERROR adding monitor mode interface: command failed: Operation not supported (-95)
root@kali:~# supersu
-bash: supersu: command not found
root@kali:~#
root@kali:~# monstart
-bash: monstart: command not found
root@kali:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 05c6:90a4 Qualcomm, Inc.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:~# cat /proc/version
Linux version 3.10.40-g90f4f12 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Jan 25 18:18:56 CST 2017
root@kali:~# ls
root@kali:~# ls
root@kali:~# cd ..
root@kali:/# ls
bin       dev          home   mnt   root  sdcard  system  var
boot      etc          lib    opt   run   srv     tmp
captures  external_sd  media  proc  sbin  sys     usr
root@kali:/# cd sdcard/
root@kali:/sdcard# ls
Alarms         Podcasts
Android        Ringtones
DCIM           TWRP
Download       Tasker
Movies         kaliNethunter.zip
Music          kernel-nethunter-shamu-nougat-2017.11-18-1618.zip
Notifications  nh_files
root@kali:~# apt-get install kali-linux-full -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kali-linux-full                         root@kali:~#

**Comment by Megaeloelo** [comment]
Use: apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 7D8D0BF6

**Comment by bpartin2009** [comment]
Awesome..... worked perfect  thanks
