### ISSUE TITLE
Can't update nethunter. No update from Exp Keys --> No Keys from unistalled dirmngr --> no dirmngr in repo

### ISSUE THREAD

**Issue by bpartin2009** [offensive-security/kali-nethunter#1088]
### Built from repo (date and build command) or downloaded from website (links):
SU: SR5-SuperSU-v2.82-SR5-20171001224502.zip
twrp: twrp-3.2.1-0-flounder.img
stock image: volantis-n9f27m-factory-a0d47736.zip
Kali Nethunter: build.py -d flounder --nougat --rootfs full
nethunter-flounder-nougat-kalifs-full-20180206_182600.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.103-gcbed67d00ed-dirty (root@kali) (gcc version 4.9 20150123 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Mar 8 13:01:47 GMT 2017

## Issue:
Can't update, upgrade, or install Kali-full see below.
![screenshot_20180206-194102](https://user-images.githubusercontent.com/30868857/35894257-a8940ae2-0ba9-11e8-8090-b8c00ef1cecb.png)

**Comment by Lexso25** [comment]
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7D8D0BF6
apt update

**Comment by jmingov** [comment]
Please, follow the official instructions. (thanks @Lexso25 )

> If you don’t update Kali regularly (*cough*), then your archive-keyring package is outdated, and you’ll get key mismatches when working with our repositories. Sucks for you, but at least you can manually update the new key :
> 
> `wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add`
> 
> <3

SOURCE:  https://twitter.com/kalilinux/status/959515084157538304

**Comment by svoji** [comment]
This instruktion is working , just use it ...  👍😉

**Comment by bpartin2009** [comment]
It worked for me too. I did not have internet access at the time on my Nexus 9 when the solution was given so I just went to https://archive.kali.org/ and downloaded the archive-key.asc file using my work computer and transfered the file to my Nexus 9 over the OTG cable and ran "apt-ket add archive-key.asc" and if worked. When I got home I was able to update, upgrade, and install full-kali
