### ISSUE TITLE
YU YUPHORIA kali nethunter kernel not found please help me

### ISSUE THREAD

**Issue by gokulbabu** [offensive-security/kali-nethunter#1090]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
lolipo

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

linux version 3.10.49-g57b68c3(shenyiling@shenyiling) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT wed sep 23 12:28:16 CST 2015

## Issue:
kali nethunter kernel not found for my device and hid keyboard not working. please help me.

**Comment by Learnbydoin** [comment]
You need chroot and then make open kali terminal and this moment write kali nethunter in the app your kernel ect and you read the app found the kernel
