### ISSUE TITLE
Kali-nethunter

### ISSUE THREAD

**Issue by Somnathnr** [offensive-security/kali-nethunter#1091]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Can't execute /bin/bash:no such file or directory

**Comment by shumon123** [comment]
Nice

**Comment by BesoBerlin** [comment]
Check if kernel is installed via settings,
Check if chroot is installed via nethunter app...

**Comment by shumon123** [comment]
Nice

**Comment by BesoBerlin** [comment]
--close--
