### ISSUE TITLE
I can't set up wlan0 gateway!

### ISSUE THREAD

**Issue by EastwindZL** [offensive-security/kali-nethunter#1093]
### Device:

Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/2017.11-18-1618/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

root@kali:~# cat /proc/version
Linux version 3.10.94+ (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #4 SMP PREEMPT Fri Jan 8 19:14:10 UTC 2016
![tim 20180224100009](https://user-images.githubusercontent.com/29472751/36624431-296aa57e-194a-11e8-9e0d-82f85fc776e4.jpg)

## Issue:

I used "route add default gw 192.168.7.1" Unable!

**Comment by Learnbydoin** [comment]
For waht you want make this?

**Comment by pyc0de** [comment]
try reading about iproute2
