### ISSUE TITLE
can i install kali nethunter on s7 with Nougat

### ISSUE THREAD

**Issue by killergast113** [offensive-security/kali-nethunter#1095]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

## Issue:

can i install kali nerhunter and a kernel on the samsung galaxy s7 exonys  sm-g930f  becuse theres no roms for android 6.0.1 without thw aroma or could any body be nice and make one for me becuse i wana dual boot my roms but aroma is not suported in dual boot patcher.... thanks in advance (:

**Comment by ThatOneTurd** [comment]
I'm also looking for a nougat rom. Unfortunately, i don't think there are any at this point. Right now I'm using "Hydrarom 1.4.5" 
https://forum.xda-developers.com/s7-edge/development/rom-hydra-rom-v1-2-aroma-t3455653 
which is a note 7 port running android marshmallow. Kali works great, the only bug i've been able to find is the camera which refuses to work after installing the kali kernel(Not related to hydrarom i don't think). Here's the latest kernel + kali arm64 
https://forum.xda-developers.com/galaxy-s7/development/kernel-kali-nethunter-galaxy-s7-t3475407.

**Comment by killergast113** [comment]
well im looking for a rom like hydra rom its a realy nice rom i still have the zip and superman rom with android 6.0.1 its very nice i might make a aroma less rom of one off those but my knolage is not very good never done it

**Comment by ThatOneTurd** [comment]
Yeah, i was even trying to look into stuff like lineage 13 which runs marshmallow i think, but everything seems to die out 2016, can't find anything anywhere. I wish there was a herolte nethunter kernel for nougat, i think it would make things so much easier :( If ever you find something, post it here and i'll give it a try too!

**Comment by killergast113** [comment]
well it worked the aroma less worked but after the dual boot i could no longer boot to my primary rom so i reseted the whole phone wiped everything and gues what ima not a noob but i did not know wtf could hapen so my dumass reseted every thing and the fiking efs partition got corupted  but i still have hope i have 2 twrp backups with efs backup lol but that did the job but now my isue is the simcard is not working so yeah im quit happy that my dam phone still boots lol so if u want the download for the aroma less rom i got u coverd but i warn u it might rape ure phone  but i will be trying to fix my imei number becuse thats the isue so wish me luck

**Comment by killergast113** [comment]
but i never give up on stuff so yeah ill be working on my phone for another 2 weeks lol so yeah if u want the download just comment on this thread but i have not did anything els than just booting the rom and after that it basicly got corrupted i will look i the configs of the installer probs in about 2 day no ps4 for me haha

**Comment by killergast113** [comment]
oh and before you ask my phone is samsung galaxy s7 sm-g930f and it is android 6.0.1 marchmellow so the rom works just nice right but i hope ill fix the dam imei    oh and the aroma less rom is based on the superman rom v1.19 or so the link  http://www.phonandroid.com/forum/superman-rom-v1-19-1-galaxy-s7-edge-sm-g935f-t149037.html

**Comment by killergast113** [comment]
i will upload the rom later or tomorrow on mega or mediafire

**Comment by killergast113** [comment]
would you like me to port a kernel to nougat i have a few people who would help me like the current herlote is marchmellow and needs to bee 7.0 lol might be worth the try or i will make notorius kernel best kernel out there for me anyways awsome support and i could probs with a bit off help put all of the stuff form nethunter kernel in to the notorius kernel     but first ineed anougat allmost same procesor and stuff with nougat andt port it to ure devices but thats just the future

**Comment by ThatOneTurd** [comment]
The possibility of creating a kernel would be amazing, cause for some reason i can't get my camera to work on 6.0.1, i'm even thinking about getting a nexus 5 for the internal monitor mode and packet injection. Might be easier because I bricked my phone again last night, now i'm trying to get the sim to work too lol

**Comment by bkr32** [comment]
i previously worked on porting oneplus one's kernel from marshmallow to nougat, although it was a different kernel base, all that was really needed was patches for wifi and usb most of which was enabled in the kernel options? i forgot the file name.
coming to a s7 edge to replace my opo i'm actually baffled to find no kernel for nougat
