### ISSUE TITLE
Hid Keyboard Not Detected

### ISSUE THREAD

**Issue by onrefin** [offensive-security/kali-nethunter#1097]
### Device:

Xiaomi Mi4

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat 7.1.2

### Built from repo (date and build command) or downloaded from website (links):
Built by Kali 2017/10/12

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-lineageos-gbbe002f (jenkins@AICP-BOX-3) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Thu May 18 04:06:46 CEST 2017

## Issue:
Duckhunter Hid attack doesn't work 
This says that there is no hidg* file or directory
echo h | hid-keyboard /dev/hidg* keyboard
/dev/hidg*: No such file or directory

**Comment by jcadduono** [comment]
Nethunter requires each device to be ported individually. You are using the lineageos kernel and thus have no support for nethunter specific functions.

**Comment by onrefin** [comment]
Is there any way to solve this problem
