### ISSUE TITLE
Questions about the installer: 

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#1098]
### Device:
Mi A1

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oreo 8.1

## Issue:

I was wondering if I need to adapt the installer to my device model or just to build the kernel and leave flash the installer? 

I took a look at the installer and I see folders named chromeos and I don't know if they are just things added after flashing. 

Another thing that I've seen is the boot-patcher. Do I need that in the installer or is just for official devices? 

Thanks and sorry if some questions makes me look like a noob :)

**Comment by jcadduono** [comment]
I wrote readmes in the GitHub repos to explain it see the nethunter-installer folder

**Comment by alexandrumarcel** [comment]
Ok, I'll read them ^^ thanks for the answer :)

**Comment by alexandrumarcel** [comment]
@jcadduono one more question if you don't mind: 

Do I need all the device tree? Because for now we have only the kernel source available not the vendor/device.

**Comment by jcadduono** [comment]
Only kernel. See my kernel repos for build script examples if you want to build kernels standalone. I usually commit a single commit with build.sh menuconfig.sh and VERSION file and use a linaro toolchain to compile (gcc 5 or newer for 3.18 or newer, gcc 4.9 for older kernels)
