### ISSUE TITLE
Issue with source.list on Nethunter on oneplus one

### ISSUE THREAD

**Issue by stoookie** [offensive-security/kali-nethunter#1099]
Hey can anyone help, 

I’m getting the update error on oneplus one, I’ve tried to edit the source.list , however when I move the file to another so I can view it it’s not visible
 By this I mean 

If I do mv /etc/apt/source.list /sdcard 

The file moves and I can see it by doing
Cd /sdcard 

Then ls 

However if I use file manager it doesn’t show up as there so I can’t edit it to the correct info

**Comment by BesoBerlin** [comment]
Don't use any file manager...
Use ES or rather do it in terminal directly by using vi / VIM or nano. 
But the error probably is because old keys...
Try:
wget -q -O - archive.kali.org/archive-key.asc | apt-key add
It should work...

**Comment by stoookie** [comment]
Hi thank you for your reply, 

Should have said it was ES I was using but it still wasn’t visible.

Will try the method suggested and see how it goes, will give feedback after. 😀

**Comment by stoookie** [comment]
Ok well issue seems to be resolved, but not sure.

It no longer says 404 error but it also no longer shows unpacking

**Comment by BesoBerlin** [comment]
So what exactly does it show after apt update && apt dist-upgrade ?

**Comment by Learnbydoin** [comment]
Hey BasoBerlin kannst du mir bei meinem problem helfen betreffend wifite und kali ?

**Comment by BesoBerlin** [comment]
Ich kann's versuchen! Was ist dein Problem!?

**Comment by Learnbydoin** [comment]
@BesoBerlin also ich habe das nexus 6p 
software 8.0.0
kernel nethunter angler oreo 
nexmon app auch installier und die tools wie auch denn firmware chip die man bei der app auswählen kann
So nun habe ich nexmon kali nethunter und denn passenden kernel, so um doch z.b denn monitor modus starten zu können benötige ich doch die f
datei monstart-nh. Ok die habe ich eingach von der zip nethunteros genommen und ins system/xbin kopiert wie auch monstart-nh und nexutil 
Nun meine ist das richtig was ich dort gemacht habe ?
Liegt es daran das wifite keine acces point findet ?

**Comment by alphaomicron** [comment]
Much better if you ssh into your mobile from a computer. Then you can fix your source.list
