### ISSUE TITLE
is there a Kali Nethunter for the OnePlus 5T ?

### ISSUE THREAD

**Issue by sshsampire** [offensive-security/kali-nethunter#1100]
### Device:
OnePlus 5T 

## Issue:
Hey together, is there a stable custom version of Nethunter for the op5t, witch supports usb-
wifi and ethernet dongles?
:) thank you

**Comment by simonpunk** [comment]
See my XDA post.
https://forum.xda-developers.com/oneplus-5/development/burgerhunter-t3638810

**Comment by sshsampire** [comment]
TopTyp! =) 
I'll go try 'n' test it instantly

**Comment by simonpunk** [comment]
Please read the instruction carefully and I cannot confirm that which dongle works for my kernel. Think twice before doing it.
