### ISSUE TITLE
Some files in /usr/bin/ are corrupted and reboot the smartphone

### ISSUE THREAD

**Issue by yadox666** [offensive-security/kali-nethunter#1101]
### Device:
Oneplus 5T A5010

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
OxygenOS 4.7.6
Android 7.1.1

### Built from repo (date and build command) or downloaded from website (links):
latest   kalifs-armhf-latest-full.tar.xz

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 4.4.21-perf+ (root@simonpunk) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #2 SMP PREEMPT Fri Feb 23 16:48:00 CST 2018

## Issue:
I used simonpunk's kernel, magisk 16.0.0 and kali_nethunter_magisk_module.zip (version 15.0.0) and installed nethunter chroot using kali nethunter apk. Everything works fine, except a failure I've found:

Everytime I execute "ls /usr/bin" the phone reboots automatically without leaving anything in the logcat window or in Android Studio log monitor. I investigated, and some files (specially X11) seem to be corrupt in the ext4 fs. I tried also to repair it from TWRP terminal by launching e2fsck, deleting manually the files from terminal or file manager. Every time I try to remove them the FS /dev/block/sda13 remounts read only, because filesystem errors. I have deleted many times data fs and reinstalled from different kalifs zips. When it's recently installed the "ls /usr/bin" works, but after a system reboot I get same failures. I cannot make it stable. Can you please help me or point me to any possible solutions.

**Comment by simonpunk** [comment]
Hey, please try oreo, as nougat was compiled with official source, and oreo is compiled from elementx's kernel. But I have deleted the nougat kernel drive already, as I dont want to do it for different version. 

You can also try my modded magisk module, follow the instrction again on XDA's post
https://forum.xda-developers.com/oneplus-5/development/burgerhunter-t3638810

And please, try to comment on XDA, as there is almost no one can help if the kernel is not officially approved by them. For me, It's hard to say what the main cause is, as you said that no logs can be found.

**Comment by yadox666** [comment]
Thank you simonpunk. I appreciate it so much to get your help directly. I will continue on xda.

**Comment by yadox666** [comment]
I will double post this ticket. I think you can consider it as closed or solved, based on my findings.

As I said, after installing TWRP, Android Oreo,  magisk 16.0.0, simonpunk's kernel based on ElementalX kernel, I installed and magisk nethunter module for Oreo from simonpunk's google repository. I formated data partition and reconfigured everything in Android. 

I also installed Kali Nethunter latest filesystem from Kali Nethunter APK, copying it to sdcard. And again, I got this crazy filesystem error when executing "ls /usr/bin" that forced an Android reboot or just a remount of the system partition in Read Only mode (ro). Also from Android (adb shell) I get similar results when executing "ls /data/local/nhsystem/kali-armhf/usr/bin/". There are corrupt files in this path (specially X11) that can't even be deleted.

After trying the process many times and getting the same result, I made a filesystem check and repair from TWRP and adb shell, using this command:

**e2fsck -pvf /dev/block/sda13**
_/dev/block/sda13: recovering journal
      197913 inodes used (5.63%, out of 3515680)
         573 non-contiguous files (0.3%)
         277 non-contiguous directories (0.1%)
             # of inodes with ind/dind/tind blocks: 0/0/0
             Extent depth histogram: 171594/71
     2610843 blocks used (18.57%, out of 14059707)
           0 bad blocks
           1 large file

      155294 regular files
       16085 directories
           7 character device files
           0 block device files
           0 fifos
          66 links
       26510 symbolic links (26226 fast symbolic links)
           8 sockets
------------
      197970 files_

This procedure didn't also fix the error.

When I tried to delete one of the corrupt files I observed in kernel messages:
rm /data/local/nhsystem/kali-armhf/usr/bin/X11

_<2>[ 6797.109000] EXT4-fs error (device sda13): _ext4_fname_disk_to_usr:331: inode #2233177: comm rm: encrypted inode too small
<3>[ 6797.109448] Aborting journal on device sda13-8.
<2>[ 6797.109819] EXT4-fs (sda13): Remounting filesystem read-only_

So I got into the solution. Forced /data partition encryption is causing corrupt files in Kali Nethunter chrooted file system. I installed from TWRP no_verity_op5_v2.zip to force no encryption of data partition, formated data again and installed Magisk, magisk module, and chroot in Kali Nethunter APK. I checked that there wasn't any encryption in data, and checked everything. 

**NOW EVERYTHING WORKS OK.** 

So, my conclusion is that Kali Nethunter filesystem can not coexist at the moment with Android forced encryption!
