### ISSUE TITLE
Errors after editing the defconfig

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#1102]
### Device:
Xiaomi Mi a1

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oreo

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.71-perf-g2a99c9e-dirty (Abhishek@DominatingMachine) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #4 SMP PREEMPT Fri Mar 2 00:10:23 IST 2018

## Issue:

https://del.dog/usegilokiy.rb

I know this might not be an issue with the kali-nethunter or the patch we made for our device but we get these errors that come only after we build using our modified defconfig after the tutorial from below:

`https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel`

This tutorial is made for arm 3.4 kernel version while our kernel version is arm64 3.18.

There are other steps to follow for the newer kernel or the tutorial above can be used to modify the newer kernel?

Also, in "SDR" part of the tutorial there's the "DVB for Linux" option that isn't available in the 3.18 kernel and the errors above are related to this option. Does this have to do anything with the missing option or it was moved somewhere else?

**Comment by alexandrumarcel** [comment]
Tissot_Nethunter_defconfig: https://del.dog/obutikiqax.shell

If this helps with something
