### ISSUE TITLE
Kali nethunter two problem

### ISSUE THREAD

**Issue by sylar1233** [offensive-security/kali-nethunter#1103]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat/proc/version
-bash: cat/proc/version: No such file or directory
root@kali:~# cat /proc/version
Linux version 3.10.73-gc4a42c7 (root@nh-buildbox) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Dec 8 19:29:57 CST 2016
root@kali:~#
## Issue: 
Hello I have two problems that I could not solve until now. The first problem is: I do have TL-WN722N V 2.0 
not unfortunately v1.0
So to use the v2.0 I need the drivers, can someone tell me how to install them?
The second problem is: 
root @ kali: ~ # source monstart-nh
root @ kali: ~ # wifite -i wlan0
################################################## ##

  .; ' `;,
 .; ' ; ' `;,` ;, WiFite v2 (r87)
.; ' ; ' ; ' `;,`;, `;
:: ::: () :: :: automated wireless auditor
'. '. '. / _ \,: ',:',: '
 '. '. / ___ \,: ',:' designed for Linux
  '. / _____ \,: '
           / \

 [+] set interface: wlan0

 [+] scanning for wireless devices ...
 [!] could not find wireless interface "wlan0"
 [+] quitting

root @ kali: ~ #
What do I have to do to successfully complete wifite?
Please help me I do not know how to continue

**Comment by EastwindZL** [comment]
TLWN722N V2 Unsupported monitor mode

**Comment by sylar1233** [comment]
And the the other problem ?
