### ISSUE TITLE
Nexus 6p Oreo Kali nethunter

### ISSUE THREAD

**Issue by sylar1233** [offensive-security/kali-nethunter#1104]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo 8.0.0

### Built from repo (date and build command) or downloaded from website (links):

root@kali:~# cat /proc/version
Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Wed Sep 6 16:27:46 EDT 2017
root@kali:~#

## Issue: What im much doing next for to Work wifite ect 
Sorry for this noob question but i learn more and more from your answer
Then I started the nexus and installed kali nethunter and see no crash.
Then I downloaded kalifs-armhf-full.tar.xz and renamed it to kalifs-full.tar.xz and pushed it to path / sdcard. The kalifs were successfully unpacked by nethunter. Ok so far so good, I downloaded the nexmon app and installed the tools as well as the firmware. But now the problem is that I can not find it in kali or in android terminal monstart-nh.
So what do I have to do now ?

**Comment by rafaleon69** [comment]
Nexmon App allows you to patch intercal wifi firmware of Nexus 6P in your case to enable monitor mode and in your case, 8.0 paket injection as well. There is another project developed by Chris that included that functionality in his app called Hijacker for easy and quick operation. 

You can operate Nexmon tools from terminal SU not kali but it is not connected with Kali chroot. You can run standalone tools included in the Hijacker app but it is pain. If you decided to go down that road you would need to use libfakeioctl to summon those functionalities as described on Nexmon github repo.

Dont give up, the harder you try the more you learn.

Good luck
