### ISSUE TITLE
kali nethunter/wifite no found target

### ISSUE THREAD

**Issue by Learnbydoin** [offensive-security/kali-nethunter#1107]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo

### Output of `cat /proc/version` in adb shell or NetHunter Terminal: Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# cat /proc/version
Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Wed Sep 6 16:27:46 EDT 2017

## Issue:Helo wifite find no targets and clients.
Any can help me for this problem ?

![screenshot_20180315-152416](https://user-images.githubusercontent.com/37378439/37475925-1d393462-2874-11e8-869c-1820e5b16968.png)
![screenshot_20180315-161110](https://user-images.githubusercontent.com/37378439/37475848-f641e322-2873-11e8-9ab0-cea983772e7a.png)
![screenshot_20180315-161103](https://user-images.githubusercontent.com/37378439/37475856-fb8251e6-2873-11e8-8733-eed8c079ea38.png)

**Comment by Learnbydoin** [comment]
![screenshot_20180315-152416](https://user-images.githubusercontent.com/37378439/37469922-add51b02-2866-11e8-9347-b6c94f927f8b.png)
Here screenshoot

**Comment by Learnbydoin** [comment]
Any can help me ?

**Comment by BesoBerlin** [comment]
Wie hast du wlan0 in Monitormode gebracht?
Mir airmon-ng oder mit monstart_nh ?
Also ehrlich gesagt habe ich nexmon auch noch nicht in chroot eingebunden und kann somit wifite unter Kali chroot auch nicht nutzen. 
Was willst du denn damit machen? Vieles funktioniert auch über die nexmon App (z.B. aircrack-ng womit auch die meisten wifite Funktionen abgedeckt wären)...

**Comment by Learnbydoin** [comment]
Mit monstart-nh 
wie kann ich denn es mit airmon-ng  zum laufen bekommen?

**Comment by Learnbydoin** [comment]
Hier mal ein bild von der eingabe airmon-ng
![Uploading Screenshot_20180319-134339.png…]()

**Comment by Learnbydoin** [comment]
H[
![screenshot_20180319-134339](https://user-images.githubusercontent.com/37378439/37596220-c96de250-2b7b-11e8-93d4-a22f9c61458f.png)
](url)

**Comment by BesoBerlin** [comment]
Ja das war auch nur eine Ausschluss Frage, mit airmon-ng wirst du es wohl nicht hinbekommen. Hmm.. nach dem was du in dem anderen Thread beschrieben hast hört sich das erstmal gut an. Ich kann mir nicht vorstellen, dass es bei dir keine APs gibt. Findest du denn mit "airodump-ng wlan0" APs (nachdem du mit monstart_nh" wlan0 in den Monitormode gebracht hast!? Ich vermute nicht, wenn doch, dann liegt es an wifite selbst... 
Wie sieht's denn in der Nexmon App aus!? Findest du dort APs, wenn du von der App aus in Monitor Modus gehst und die aircrack-ng Suite nutzt?
Ich habe wie gesagt selbst auch die Einbindung in chroot nicht gemacht und in diversen issue-threads gab es auch keine Antwort für ein Walk through for lunch dafür. Je nachdem was du machen möchtest, müsste eigentlich auch alles mit nexmon selbst funktionieren.

Bin mittlerweile auf OnePlus 5 umgestiegen, aber wenn ich heute Abend etwas Zeit finde kann ich ja mein Nexus Mal rausholen und es selbst versuchen.

**Comment by Learnbydoin** [comment]
So sieht es mit airidump-ng aus
![screenshot_20180319-140554](https://user-images.githubusercontent.com/37378439/37597166-e028e834-2b7e-11e8-88eb-256dac4592de.png)

**Comment by Learnbydoin** [comment]
und wegen nexmon ich habe kein plan wie man dort aircrack startet 
Hab mich bis jetzt noch nicht damit befasst

**Comment by Learnbydoin** [comment]
Ich denke es liegt an der einbindung von nexmon in die chroot

**Comment by Learnbydoin** [comment]
aber das ist wenn ich airodump mach auf der nexmon app
![screenshot_20180319-165413](https://user-images.githubusercontent.com/37378439/37606914-efb6d294-2b96-11e8-93fa-83f43e4a7860.png)

**Comment by Learnbydoin** [comment]
@BesoBerlin bist du noch da ?

**Comment by Learnbydoin** [comment]
@Rafaleon69 Helo you can help me by this problem?

**Comment by BesoBerlin** [comment]
Also..  keine Chance.. du musst schon selbst hart hand anlegen, wenn du das zum laufen bringen willst. Dazu ist eigentlich bei GitHub alles dokumentiert, wenn du hier in den issues suchst, findest du die Vorgehensweise und kannst sie vielleicht auf deinem Nexus nachvollziehen (du musst dazu den Kernel modifizieren). Ist machbar, aber Arbeit die sich bisher halt keiner gemacht hat...

**Comment by Learnbydoin** [comment]
Kannst du mir deine mail sagen ?
Damit ich dir meine nr senden kann und wir uns kurz über whatsapp unterhalten können denn ich habe noch einige fragen an dich

**Comment by TheMMcOfficial** [comment]
@Learnbydoin I know it's not related with this issue but can you help me to get nexmon working on my Nexus 6p on oreo 8.0.0 ?
https://github.com/seemoo-lab/nexmon/issues/195

**Comment by Learnbydoin** [comment]
Correkt you can not install the tools by the app?

**Comment by TheMMcOfficial** [comment]
Thanks for the quick response, no I got the version 2.1.3 and the nexmon creator told me to compile the app because the one on the playstore is outdated. And i'm stock here. I try to change the path in the "tools" tab but nothing seems to work...

![screenshot_20180323-145439](https://user-images.githubusercontent.com/34872211/37848425-7fca512e-2eaa-11e8-9abc-750ae2eac89c.png)

**Comment by Learnbydoin** [comment]
What you have installed supersu or magisk or kingoroot ?

**Comment by TheMMcOfficial** [comment]
supersu

**Comment by Learnbydoin** [comment]
You have the directory /su ?
And the folder bin in the directory su?
With the files su etc ?

**Comment by TheMMcOfficial** [comment]
no ... I don't understand I should got it ? Because everything work fine but I don't have any su folder in the root of my device. I have install the lastest version of superSU in TWRP.

**Comment by Learnbydoin** [comment]
You ned the directory su with the folder su ect
And the files 
Go too twrp flash unsu zip and restore the Original boot image 
And flash again the latest zip supersu

**Comment by TheMMcOfficial** [comment]
Ok i reinstall superSU with the lastest version on their site and I got the /su folder. I think that i had a beta version... or something like that

**Comment by TheMMcOfficial** [comment]
ok in the app i install .manualy. in the tools tab and it work. Do you know how to put the internal wifi card into monitor mode ?

**Comment by Learnbydoin** [comment]
You can crap the files monstart-nh ect from the zip file 
The zip is from nethunteros but you can see no working with wifite ect in my screenshots that not work
