### ISSUE TITLE
btusb_probe compiling error

### ISSUE THREAD

**Issue by lazerl0rd** [offensive-security/kali-nethunter#1111]
### Device:
Nexus 5X

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
It's not applicable to my issue however I am using a modded _OREO port_ to OnePlus5T by @simonpunk .

### Built from repo (date and build command) or downloaded from website (links):
Zest Kernel (my own kernel) which is based off the latest franco kernel source with a few patches (that aren't anything to do with the error).

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
`Linux version 3.10.108 (xxx@XXX) (gcc version 4.9.x 20150123 (prerlease) (GCC) ) #4 SMP PREEMPT Sun Mar 19 23:48:03 STD 2018`

## Issue:
After following the [modifying the kernel instructions](https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel) I came across the following error during compilation.
```
drivers/built-in.o: In function `btusb_probe':
sensors_ssc.c:(.text+0x42eb28): undefined reference to `get_rome_version'
sensors_ssc.c:(.text+0x42eb70): undefined reference to `rome_download'
Makefile:806: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1
```

The kernel builds fine when I do not follow the steps to enable all the stated components and use my default defconfig with the mac80211 patch.

**Comment by LazerL0rd** [comment]
For all with a similar issue you can remove the function that uses rome on the Atheros chip by editing btusb.c.
