### ISSUE TITLE
"USB in low power mode" (OTG Wn722N)

### ISSUE THREAD

**Issue by sfrmattos** [offensive-security/kali-nethunter#1113]
Nexus 7 2013 Flo

Marshmallow

Latest build from website

Issues using both ElementalX and Nethunter Kernel

## Issue:

My usb-wifi dongle (Wn722n / Qualcomm) doesnt work. I am now using OTG cable (not the Y cable).
dmesg shows up that the dongle is recognized,  but msm_otg: shows up "USB in low power mode", "OTG runtime idle" and "OTG runtime supended". Days ago my setup was working well.

I reinstalled nethunter, but the problem persists (with two of my Wn722n). Looks like the tablet is not giving enough power to run the wifi adapter. Any advice on how to disable low power mode?
On my latest test now, the tablet was with 85% battery.

Also, I read somewhere that using a wakelock app from appstore could work, but no progress with this too.

Thank you guys,

**Comment by alphaomicron** [comment]
Look at the back of the WN722N at tell us what version is. If it is other than v.1.0 or v.1.10 then it doesn't work and you should try one with the version I mentioned

**Comment by sfrmattos** [comment]
@alphaomicron 
Its V1.10.
Its strange because sometimes it works (gets recognized and up), sometimes its gets recognized by lsusb and cant go up with ifconfig, and sometimes its gets recognized and just enters in low power mode.

**Comment by sfrmattos** [comment]
ok, first of all, thank you for help.

I have two differente usb cables: One thats bulky and works well, and a connector, like a one piece OTG connector:

https://pasteboard.co/HdLXn1D.jpg

**Comment by alphaomicron** [comment]
the bulky one works for me. or a similar one. Start troubleshooting on the power options ie if the Nexus is recognized by your computer etc there is a very rare case that the usb inside the phone is not attached properly. Not saying that's the case but you have to look all the options

**Comment by alphaomicron** [comment]
Ok this is where you go wtf. I feel you. Try to remember every step you take from now on to see what might be causing this.

**Comment by 0E800** [comment]
From:  https://community.nxp.com/docs/DOC-332225

>As for the USB module, there has two different interrupts for a USB resume event. One asynchronous to be able to wake from a low power mode, which is triggered by change in the state of the USB lines. The other is synchronous and is triggered only after 2.5 us of detecting a K state (D+ = 0, D- = 1, for Full Speed). The application is responsible to transition to the low power mode whenever it requires it, and for this purpose it must check the device state as reported by the USB stack. When a suspend condition is detected in the bus, the SLEEP interrupt triggers and the stack changes its state to suspend; then the application will transition to the low power mode. When this SLEEP interrupt occurs, the asynchronous wake interrupt is enabled, and is disabled when it is triggered (this is required by the module to clear the interrupt). In normal conditions, the synchronous resume interrupt or the reset interrupt will be triggered afterwards, causing the stack to transition its state to other than suspend. The application can then know that communication is active again and will avoid entering the low power mode again.

Review: 
https://stackoverflow.com/questions/45351924/how-do-kernel-get-to-know-when-a-usb-device-goes-to-low-power-mode-by-itself-no?rq=1

**Comment by sfrmattos** [comment]
@0E800 Hey buddy!
First of all, thank you for your reply.
I think I get the "explaination", but I cant realize why it (low power mode) happens sometimes, and why not. Second, I cant realize how to solve this problem. I will really appreciate any sugestion. Thank you again.

**Comment by alkalinelito** [comment]
Hi, I'm having the same problem with a new install (nexus 7 2013 wi-fi - flo), I tried many nethunter versions and kernels ,  OTG goes low power and not even a usb mouse works .   

This happends -after- installing nethunter kernel. Before nethunter installation otg works fine.   The problem is in the kernel, I saw in other thread that maybe disabling y cable support in the kernel fixs this.

**Comment by 0E800** [comment]
The y charging settings is disabled until you enable it in Kali System App Settings . 

If your on a N7 2013 it may be worth your while to try the kernel I just released for Nougat. It should be compatible with majorty of Nougat roms for Flo.

https://github.com/0E800/nethunter-devices/releases

I'll be posting Flo Oreo kernels with HID and injection compatibility soon. Only issue with Oreo is it seems the nethunter apps are compatible.

**Comment by alkalinelito** [comment]
Thanks, installing cm14 right now, should I install latest kalifs ? (https://build.nethunter.com/nightly/2017.11-18-1618/ )

**Comment by alkalinelito** [comment]
Used lineage-14.1-20180523-nightly-flo-signed.zip and nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip

Glitch kernel hangs when launcher is starting,  ElementalX  kernel works, but NetHunter terminal crashes

**Comment by 0E800** [comment]
Thats expected. You need to uninstall the Nethunter, Terminal and USBKeyboard Gadget. 
Then reinstall using most current builds:

https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer/update/data/app

**Comment by 0E800** [comment]
In my test  I also noticed that the ElemX kernel works with Lineage and AICP, but Glitch works well on AICP.

**Comment by alkalinelito** [comment]
Updated to latest Term-nh.apk, and now it works. Still have same problem:
[https://i.imgur.com/cP2IxpS.png](url)

**Comment by 0E800** [comment]
I think that is because the Lineage rom you are using does not have the kernel modules built in prior to nethunter patching. I am upload a custom Rom, it already has the modules installed and flashes most current SuperSu and Busybox. 

Eventually I hope to get a single zip to install everything. If you dont mind, I would appreciate it if you could test and validate my findings.

Upload should be done in about 24 minutes

**Comment by alkalinelito** [comment]
Thanks a lot, that was the same problem I was having with stock rom too

**Comment by 0E800** [comment]
@alkalinelito Here you are:
	
NEXUS_7_2013_(FLO)_AICP_NOUGAT_NETHUNTER-signed.zip  380.3 MB
https://cloud.keys-daggers.org/s/NnJz2nKz5QAxqxT

It will appear as though its finished flashing, and show "Done!" but its misleading, just wait for it to complete.

**Comment by 0E800** [comment]
I think because those builds that work are Kitkat , Lolipop or Marshmallow , with every new version comes changes in the OS. Locations of firmware, dependencies change or get removed, new security additions that destroy what worked perfectly on a earlier OS.

**Comment by 0E800** [comment]
Btw - you will see at the end of install that a unmount of /data failed, its not an issue as you have to reboot anyway.

**Comment by alkalinelito** [comment]
I tried Lollipop and Marshmallow with the Nexus 7 2013, with many versions of nethunter and never works, always the same message in dmesg I posted. I tried many wi-fi adapters, and usb otg cables and the same.

Thanks again for the aicp rom, I'll post here if it works .

**Comment by 0E800** [comment]
If you turn on the nexus with the otg cable connected to the ext tplink, the device will use it as wlan0.
Best to plug in tplink 5 secs before trying to enable Monitor/

**Comment by alkalinelito** [comment]
It doesn't work , I flashed NEXUS_7_2013_(FLO)_AICP_NOUGAT_NETHUNTER-signed.zip and kernel-nethunter-flo_gl-nougat-20180521_074512.zip using TWRP 3.0.2-0 and after rebooting just hangs at "Google" never boots

**Comment by alkalinelito** [comment]
Ok, I just flashed only NEXUS_7_2013_(FLO)_AICP_NOUGAT_NETHUNTER-signed.zip  and it dosnt work ,  it hangs on "Google", never boots

**Comment by 0E800** [comment]
May you do a custom wipe. select all options and wipe, do not reboot, go back twice and select full data wipe, them type yes, then reboot back to twrp. Do a normal wipe and do not reboot, go back twice and select install and wait for it to boot.
It should loop one time and then show aicp for about 5 min.

**Comment by sfrmattos** [comment]
@0E800 Im gonna try your uploads. I spent the last two days researching to try to make it work, or at last to find out the reason for that instability.

**Comment by 0E800** [comment]
Okay, I'll post a working Rom and a Nethunter+kernel.zip that will get you to a place that you can test wifi and HID.

Probly will be a hour or so.

Thank you for your time , bandwidth and willing to test .

**Comment by 0E800** [comment]
Please do a complete wipe and full data wipe then reboot into twrp.
Try installing this Rom.
`aicp_flo_n-12.1-UNOFFICIAL-20180521-elemx.zip`   288.5 MB
https://cloud.keys-daggers.org/s/NPo949XAtHgCSp2

Then as soon as the Nethunter + Kernel is done uploading;
download and flash it after you have rebooted the device a few times.

You may need to hold off on installing Gapps until after you flash the Nethunter+kernel.

**Comment by 0E800** [comment]
@alkalinelito 
Here is Nethunter+kernel, flash this after you reboot after you install the aicp rom above.

`nethunter-flo_ex-nougat-kalifs-full-v3.2.zip`   802.3 MB
https://cloud.keys-daggers.org/s/Ly5bMnS83zMsg7A

You will most likely need to uninstall nethunter.apk, nh-term.apk and usbkeyboard, then install those apks manually after your done flashing.

**Comment by alkalinelito** [comment]
@0E800  Thanks for the help, I'll try that rom nethunter version and let you know.  

Another thing, is that I fixed my problem, I pluged a powered usb hub to the otg cable and it works!, wn722n works with all the version of nethunter and roms I tried.  

It was power issue , weird thing is that many people use hte wn722n with just the otg cable ? maybe because of the version ? . I have wn722n  v1.10 (atheros) and theres just v1 around, So I don't know

**Comment by 0E800** [comment]
On my N7 2013 w/16GB 

I use reg OTG w/ TP V1 atheros , it works but if I unplug it, it makes the device reboot.

If I turn on device with OTG + TPlink the device will use the TPlink as wlan0 and not use the embedded wifi.

I can use YCable charge only if I set it that way in Nethunter options .
