### ISSUE TITLE
Nexus 6p kali nethunter no detectet alfa network awus036neh

### ISSUE THREAD

**Issue by Learnbydoin** [offensive-security/kali-nethunter#1114]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
oreo

## Issue:
i can not find the external wifi card please help me
![screenshot_20180322-235513](https://user-images.githubusercontent.com/37378439/37802953-d45e77c0-2e2c-11e8-84dc-cc067be4bd57.png)
![screenshot_20180322-235158](https://user-images.githubusercontent.com/37378439/37802965-dd987c96-2e2c-11e8-98fd-cac5d808e75f.png)
![screenshot_20180322-235134](https://user-images.githubusercontent.com/37378439/37802966-ddbd29e2-2e2c-11e8-99a7-19b16a322e16.png)
![Uploading Screenshot_20180322-235143.png…]()
![screenshot_20180322-235117](https://user-images.githubusercontent.com/37378439/37803075-561f38e4-2e2d-11e8-8577-7336ba5af61c.png)

**Comment by alphaomicron** [comment]
Maybe try a different OTG cable. Also try airmong-ng and see what it says

**Comment by Learnbydoin** [comment]
This say me the terminal by input airmon-ng
![screenshot_20180323-141109](https://user-images.githubusercontent.com/37378439/37830940-17ce23da-2ea4-11e8-9a8a-77c42a38c308.png)

**Comment by Learnbydoin** [comment]
![screenshot_20180323-182532](https://user-images.githubusercontent.com/37378439/37844279-9829d970-2ec7-11e8-858a-1deef983a8f1.png)

**Comment by alphaomicron** [comment]
try dmesg | grep lsusb andd see what it says

**Comment by Learnbydoin** [comment]
![screenshot_20180324-135356](https://user-images.githubusercontent.com/37378439/37864133-e07648aa-2f6a-11e8-8541-d4862c55a187.png)

**Comment by Learnbydoin** [comment]
![screenshot_20180324-140621](https://user-images.githubusercontent.com/37378439/37864274-b29ff3a2-2f6c-11e8-831b-47c3a97f58f2.png)

**Comment by Learnbydoin** [comment]
Last login: Sat Mar 24 19:58:35 UTC 2018 on pts/2

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# dmesg | grep -i usb
[    0.420651] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    0.422768] usbcore: registered new interface driver usbfs
[    0.422825] usbcore: registered new interface driver hub
[    0.423096] usbcore: registered new device driver usb
[    0.454274] gdsc_usb30: no parameters
[    0.611101] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    0.634601] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    1.425767] usbcore: registered new interface driver rndis_wlan
[    1.425806] usbcore: registered new interface driver ath6kl_usb
[    1.425829] usbcore: registered new interface driver catc
[    1.425851] usbcore: registered new interface driver kaweth
[    1.425857] pegasus: v0.9.3 (2013/04/25), Pegasus/Pegasus II USB Ethernet driver
[    1.425893] usbcore: registered new interface driver pegasus
[    1.425917] usbcore: registered new interface driver rtl8150
[    1.425938] usbcore: registered new interface driver r8152
[    1.425963] usbcore: registered new interface driver asix
[    1.425983] usbcore: registered new interface driver ax88179_178a[    1.426006] usbcore: registered new interface driver cdc_ether
[    1.426028] usbcore: registered new interface driver rndis_host
[    1.442747] msm-qusb-phy f9b39000.qusb: invalid resource
[    1.486042] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.487377] usbcore: registered new interface driver cdc_acm
[    1.487383] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[    1.487417] usbcore: registered new interface driver usb-storage
[    1.487437] usbcore: registered new interface driver ums_eneub6250
[    1.487456] usbcore: registered new interface driver ums-onetouch[    1.487480] usbcore: registered new interface driver ums-realtek
[    1.487503] usbcore: registered new interface driver emi26 - firmware loader
[    1.487524] usbcore: registered new interface driver emi62 - firmware loader
[    1.487549] usbcore: registered new interface driver usb_ehset_test
[    1.488587] tusb320_i2c_init: entry
[    1.488699] tusb320_probe: start
[    1.490059] dual_role_usb otg_default: driver failed to report `mode' property: -22
[    1.490120] dual_role_usb otg_default: driver failed to report `mode' property: -22
[    1.491682] tusb320_current_advertise_set: current advertise set to 2
[    1.491688] tusb320_probe: schedule_work
[    1.491696] tusb320_probe: end
[    1.491714] tusb320_intb_work: start
[    1.491773] tusb320_i2c_init: end
[    1.492022] usbcore: registered new interface driver xpad
[    1.492062] usbcore: registered new interface driver usb_acecad
[    1.492084] usbcore: registered new interface driver aiptek
[    1.492105] usbcore: registered new interface driver gtco
[    1.492182] usbcore: registered new interface driver hanwang
[    1.492204] usbcore: registered new interface driver kbtab
[    1.492230] usbcore: registered new interface driver wacom
[    1.492979] tusb320_intb_work: attached_state is 0
[    1.493416] tusb320_current_advertise_set: current advertise is 2 already
[    1.493426] tusb320_intb_work: end
[    2.535657] usbcore: registered new interface driver dvb_usb_rtl28xxu
[    2.535721] usbcore: registered new interface driver uvcvideo
[    2.535725] USB Video Class driver (1.1.1)
[    3.784188] usbcore: registered new interface driver bcm203x
[    3.784214] usbcore: registered new interface driver bpa10x
[    3.784245] usbcore: registered new interface driver bfusb
[    3.784270] usbcore: registered new interface driver btusb
[    3.784298] usbcore: registered new interface driver ath3k
[    3.896916] usbcore: registered new interface driver usbhid
[    3.896924] usbhid: USB HID core driver
[    4.616712] qcom,qpnp-power-on qpnp-power-on-12: PMIC@SID2 Power-on reason: Triggered from USB (USB charger insertion) and 'warm' boot
[    4.629006] usbcore: registered new interface driver snd-usb-audio
[    4.655986] usb_otg_vreg: no parameters
[    4.656073] reg-fixed-voltage usb-otg-switch.66: Failed to find supply vin
[    4.656120] reg-fixed-voltage usb-otg-switch.66: Failed to register regulator: -517
[    4.656129] platform usb-otg-switch.66: Driver reg-fixed-voltage requests probe deferral
[    4.717358] qpnp-smbcharger qpnp-smbcharger-17: SMBCHG successfully probed batt=1 dc = 0 usb = 0
[    4.723170] usb_otg_vreg: no parameters
[    4.723198] usb_otg_vreg: supplied by smbcharger_external_otg
[    4.875364] usb_otg_vreg: disabling
[    4.919113] android_usb gadget: Mass Storage Function, version: 2009/09/11
[    4.919119] android_usb gadget: Number of LUNs=1
[    4.919356] android_usb gadget: android_usb ready
[    5.724315] init: Added '/init.usb.rc' to import list
[    5.724366] init: Added '/init.usb.configfs.rc' to import list
[    5.725614] init: Parsing file /init.usb.rc...
[    5.726119] init: Added 'init.angler.usb.rc' to import list
[    5.727365] init: Parsing file init.angler.usb.rc...
[    5.728098] init: Parsing file /init.usb.configfs.rc...
[    5.732460] ueventd: /sys/ rule /sys/devices/virtual/usb_composite/* enable
[    6.485790] msm-dwc3 f9200000.ssusb: DWC3 in low power mode
[    6.777276] init: Parsing file /vendor/etc/init/android.hardware.usb@1.0-service.rc...
[    7.353773] init: computing context for service 'usb-hal-1-0'
[    7.354072] init: starting service 'usb-hal-1-0'...
[    7.449054] healthd: Unknown power supply type 'USB_Parallel'
[    7.734878] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/mux_enabled': No such file or directory
[    7.734907] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/no_fwd_rmnet_links': No such file or directory
[    7.734936] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/no_rmnet_insts_per_dev': No such file or directory
[    7.734964] init: write_file: Unable to open '/sys/module/rmnet_usb/parameters/rmnet_data_init': No such file or directory
[    7.739014] init: starting service 'save-usb-config'...
[    7.740505] init: processing action (persist.sys.usb.config=* && boot)
[    7.741133] init: Service 'save-usb-config' (pid 504) exited with status 127
[    7.741180] init: processing action (sys.usb.config=none && sys.usb.configfs=0)
[    7.741287] enable_store: android_usb: already disabled
[   51.874784] tusb320_irq_handler: start
[   51.874860] tusb320_intb_work: start
[   51.876754] tusb320_intb_work: attached_state is 2
[   51.876773] tusb320_intb_work: Sink detected, perform TrySNK
[   51.877661] tusb320_current_advertise_set: current advertise set to 0
[   51.877680] tusb320_soft_reset
[   51.903594] tusb320_soft_reset
[   51.905015] tusb320_intb_work: schedule wdog work
[   51.905038] tusb320_drp_duty_cycle_set: set to 6
[   51.905890] tusb320_intb_work: end
[   52.108289] tusb320_irq_handler: start
[   52.108403] tusb320_intb_work: start
[   52.109858] tusb320_intb_work: attached_state is 2
[   52.109877] tusb320_intb_work: TrySNK fail, Sink detected again
[   52.109896] tusb320_drp_duty_cycle_set: set to 0
[   52.115114] tusb320_intb_work: end
[   52.134057] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[   52.159240] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[   52.167662] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[   52.167684] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   52.167691] usb usb1: Product: xHCI Host Controller
[   52.167699] usb usb1: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[   52.167706] usb usb1: SerialNumber: xhci-hcd.0.auto
[   52.169392] hub 1-0:1.0: USB hub found
[   52.169860] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[   52.169935] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[   52.169944] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   52.169952] usb usb2: Product: xHCI Host Controller
[   52.169959] usb usb2: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[   52.169966] usb usb2: SerialNumber: xhci-hcd.0.auto
[   52.171432] hub 2-0:1.0: USB hub found
[   52.475446] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[   52.507462] usb 1-1: New USB device found, idVendor=148f, idProduct=3070
[   52.507485] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   52.507493] usb 1-1: Product: 802.11 n WLAN
[   52.507501] usb 1-1: Manufacturer: Ralink
[   52.507508] usb 1-1: SerialNumber: 1.0
[   90.433216] init: processing action (sys.usb.config=none && sys.usb.configfs=0)
[   90.433438] enable_store: android_usb: already disabled
[   90.434845] init: processing action (sys.usb.config=adb && sys.usb.configfs=0)
[  388.813267] usb 1-1: USB disconnect, device number 2
[  388.821308] tusb320_irq_handler: start
[  388.821822] tusb320_intb_work: start
[  388.826150] tusb320_intb_work: attached_state is 0
[  388.827391] tusb320_current_advertise_set: current advertise set to 2
[  388.827421] tusb320_intb_work: Sink removed
[  388.827469] tusb320_intb_work: end
[  388.829731] usb usb2: USB disconnect, device number 1
[  388.833647] xhci-hcd xhci-hcd.0.auto: USB bus 2 deregistered
[  388.833757] usb usb1: USB disconnect, device number 1
[  388.857959] xhci-hcd xhci-hcd.0.auto: USB bus 1 deregistered
[  388.862567] ueventd: removing platform device soc.0/f9200000.ssusb/f9200000.dwc3/xhci-hcd.0.auto
[  388.895214] msm-dwc3 f9200000.ssusb: DWC3 in low power mode
[  470.848378] tusb320_irq_handler: start
[  470.848429] tusb320_intb_work: start
[  470.851659] tusb320_intb_work: attached_state is 2
[  470.851677] tusb320_intb_work: Sink detected, perform TrySNK
[  470.853286] tusb320_current_advertise_set: current advertise set to 0
[  470.853305] tusb320_soft_reset
[  470.879575] tusb320_soft_reset
[  470.880696] tusb320_intb_work: schedule wdog work
[  470.880708] tusb320_drp_duty_cycle_set: set to 6
[  470.881849] tusb320_intb_work: end
[  471.084676] tusb320_irq_handler: start
[  471.084876] tusb320_intb_work: start
[  471.088178] tusb320_intb_work: attached_state is 2
[  471.088205] tusb320_intb_work: TrySNK fail, Sink detected again
[  471.088229] tusb320_drp_duty_cycle_set: set to 0
[  471.090349] tusb320_intb_work: end
[  471.111307] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[  471.132581] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[  471.144869] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[  471.144889] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  471.144896] usb usb1: Product: xHCI Host Controller
[  471.144903] usb usb1: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  471.144910] usb usb1: SerialNumber: xhci-hcd.0.auto
[  471.148777] hub 1-0:1.0: USB hub found
[  471.149120] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[  471.149217] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[  471.149226] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  471.149233] usb usb2: Product: xHCI Host Controller
[  471.149240] usb usb2: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  471.149247] usb usb2: SerialNumber: xhci-hcd.0.auto
[  471.150984] hub 2-0:1.0: USB hub found
[  471.465963] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[  471.502128] usb 1-1: New USB device found, idVendor=148f, idProduct=3070
[  471.502163] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  471.502173] usb 1-1: Product: 802.11 n WLAN
[  471.502182] usb 1-1: Manufacturer: Ralink
[  471.502191] usb 1-1: SerialNumber: 1.0
[  558.569816] usb 1-1: USB disconnect, device number 2
[  558.572787] type=1400 audit(1521920852.906:379): avc:  denied  { getattr } for  pid=29 comm="kdevtmpfs" path="/bus/usb/001/002" dev="devtmpfs" ino=120934 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  558.579284] tusb320_irq_handler: start
[  558.579451] tusb320_intb_work: start
[  558.583464] tusb320_intb_work: attached_state is 0
[  558.584835] tusb320_current_advertise_set: current advertise set to 2
[  558.584873] tusb320_intb_work: Sink removed
[  558.584927] tusb320_intb_work: end
[  558.590449] usb usb2: USB disconnect, device number 1
[  558.606415] xhci-hcd xhci-hcd.0.auto: USB bus 2 deregistered
[  558.606520] usb usb1: USB disconnect, device number 1
[  558.636642] xhci-hcd xhci-hcd.0.auto: USB bus 1 deregistered
[  558.637204] ueventd: removing platform device soc.0/f9200000.ssusb/f9200000.dwc3/xhci-hcd.0.auto
[  558.666377] msm-dwc3 f9200000.ssusb: DWC3 in low power mode
[  571.843141] tusb320_irq_handler: start
[  571.843204] tusb320_intb_work: start
[  571.845377] tusb320_intb_work: attached_state is 2
[  571.845387] tusb320_intb_work: Sink detected, perform TrySNK
[  571.846774] tusb320_current_advertise_set: current advertise set to 0
[  571.846781] tusb320_soft_reset
[  571.872942] tusb320_soft_reset
[  571.874028] tusb320_intb_work: schedule wdog work
[  571.874038] tusb320_drp_duty_cycle_set: set to 6
[  571.875105] tusb320_intb_work: end
[  572.077719] tusb320_irq_handler: start
[  572.077787] tusb320_intb_work: start
[  572.079452] tusb320_intb_work: attached_state is 2
[  572.079460] tusb320_intb_work: TrySNK fail, Sink detected again
[  572.079473] tusb320_drp_duty_cycle_set: set to 0
[  572.083434] tusb320_intb_work: end
[  572.105076] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[  572.129137] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[  572.142012] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[  572.142029] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  572.142035] usb usb1: Product: xHCI Host Controller
[  572.142041] usb usb1: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  572.142048] usb usb1: SerialNumber: xhci-hcd.0.auto
[  572.143821] hub 1-0:1.0: USB hub found
[  572.143995] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[  572.144054] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[  572.144062] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  572.144068] usb usb2: Product: xHCI Host Controller
[  572.144075] usb usb2: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  572.144081] usb usb2: SerialNumber: xhci-hcd.0.auto
[  572.145318] hub 2-0:1.0: USB hub found
[  572.455414] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[  572.489542] usb 1-1: New USB device found, idVendor=148f, idProduct=3070
[  572.489602] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  572.489613] usb 1-1: Product: 802.11 n WLAN
[  572.489620] usb 1-1: Manufacturer: Ralink
[  572.489628] usb 1-1: SerialNumber: 1.0
root@kali:~#

**Comment by Learnbydoin** [comment]
the command lsmod give me no outpot thats not normal 
![screenshot_20180325-142154](https://user-images.githubusercontent.com/37378439/37874955-b93e5204-3038-11e8-9a4a-f90fa0e81819.png)

**Comment by Learnbydoin** [comment]
![screenshot_20180325-145507](https://user-images.githubusercontent.com/37378439/37875223-8a5c372c-303c-11e8-8be3-88d98f121ae9.png)

**Comment by Learnbydoin** [comment]
@BesoBerlin hast du es hin bekommen mit dem externen wifi ?
wenn ich das mit modprobe mache...
findet es denn adapter trotzdem nicht

**Comment by alphaomicron** [comment]
You need to try a new usb OTG cable. Its probably now powering up properly the wifi card

**Comment by Learnbydoin** [comment]
i have a logitech keyboard connected to it with glowing buttons.
The works without problems, she had two usb ports to which I have connected alfa and the alfa shone.
So the energy can not be there because the keyboard works fine.
So if it's on the cable, what do I have to look out for?
Does the cable have to have a special function?
Since I have to buy one, it would be good if I knew what to look for when buying.
So can someone tell me what the cable s.functions must have?

**Comment by BesoBerlin** [comment]
it seems not the be the cable. in Android 8.* i was not able to get this working... if I modprobe to load the kernel, the phone reboots.

**Comment by Learnbydoin** [comment]
Bei mir startet es nicht neu wenn ich modprobe rtl8187 eingebe

**Comment by BesoBerlin** [comment]
tja... da bin ich auch überfragt... habe das von Anker für 7 euro oder so bei amazon gekauft... funktioniert super! versuch mal modprobe im Android SU terminal zu starten und dann rtl bzw RTL einzugeben und dann mit Tab zu arbeiten, so gehst du sicher, dass der Treiber auch im Kernel ist. (Sollte er aber sein).
Nur leider führte das bei mir seit Android 7 direkt zum Absturz. Hauptentwickler fürs 6P ist Jaccaduino, blöd ist halt dass es bei ihm warum auch immer klappt... und da er gerade eh super beschäftigt scheint oder nethunter auf opensource basis hier auch schon seit 3 monaten tot ist, wird da auch nicht mehr viel passieren. Wenn du das 6P als dein normales telefon nutzt, scheiße... wenn nicht... flash Marshmellow drauf  und installiere Nethunter da. da klappt wirklich noch alles von Duckhunter Integration über Mana bis hin zu Externen Wifi Karten. Nur NEXMON klappt unter Marshmellow nicht...

**Comment by BesoBerlin** [comment]
oh gar nicht gesehen... lsmod ergibt ja bei dir garnichts... ja dann mag es am OTG liegen...

**Comment by Learnbydoin** [comment]
Wie lsmod ergibt garnichts?
Doch da steht nach dem ich modprobe rtl8187 eingeben habe
rtl8187 ect

**Comment by Learnbydoin** [comment]
Oh ja das war ein Screenshot wo ich noch nicht wusste das wie man denn treiber lädt

**Comment by Learnbydoin** [comment]
![screenshot_20180327-021540](https://user-images.githubusercontent.com/37378439/37939751-e67ee328-3164-11e8-8026-0e951ecaf36b.png)

**Comment by BesoBerlin** [comment]
Hmm... Aber rtl8187 ist doch für die Alfa awus036h  ... Laut lsusb hast du doch awus036Nh!? Also musst du den rt2870 laden...

**Comment by alphaomicron** [comment]
Yeap the keyboard might work but the wireless adapter might not work. had the same problem.

**Comment by Learnbydoin** [comment]
also es ist ja kein rt2870  da  bzw es existiert  keine datei in lib mit diesem namen 
ich habe ja RT3070 / RT 2870 
Und ich liege doch richtig das RT 3070 der treiber RTL8187 ist oder?

**Comment by Learnbydoin** [comment]
![screenshot_20180327-133709](https://user-images.githubusercontent.com/37378439/37965042-fa67f438-31c3-11e8-8365-e56fbe11ec00.png)
auch danach wird nichts erkannt

**Comment by BesoBerlin** [comment]
Tja dann bin ich raus...

**Comment by Learnbydoin** [comment]
du hast dieses kabel oder?
![screenshot_20180327-140219](https://user-images.githubusercontent.com/37378439/37966122-c1a27890-31c7-11e8-98c4-a1753e13c5cd.png)

**Comment by BesoBerlin** [comment]
Ja! Funktioniert auf jeden Fall! Sowohl bei meinem Oberplus 5 (USB 2.0) als auch beim Nexus 6p (USB 3.0) - Nexus 6P bekomme ich aber wie gesagt die Treiber nur unter Marshmallow geladen. Unter Nougat und Oreo gibt's direkt neben reboot, wenn ich entweder die Treiber KDE und dann meine wlankarte anschließe oder wenn es bereits abgeschossen ist, sobald ich die Treiber lade. 
Aber das Kabel ist richtig...;-) lass mich wissen ob's dann bei dir klappt!

**Comment by Learnbydoin** [comment]
Bin gerade am suchen wo ich es kaufen kann 
Bis jetzt nichts gefunden

**Comment by BesoBerlin** [comment]
Amazon!?

**Comment by Learnbydoin** [comment]
Ne 
![screenshot_20180327-150032](https://user-images.githubusercontent.com/37378439/37968895-b5e44ada-31cf-11e8-8149-d128d3a0564f.png)

**Comment by Learnbydoin** [comment]
Auch ebay liefert es nicht ich muss echt schauen wie ich das bekommen kann...
Eventuell kann digitec es mir besorgen aber nicht mal das ist sicher 
sonst finde ich keine andere möglichkeit

**Comment by BesoBerlin** [comment]
Oha... Das hab ich ja auch noch nicht gesehen... Wohnst also etwas ländlicher!?

**Comment by Learnbydoin** [comment]
Schweiz

**Comment by ozsteyr** [comment]
I have found it to be the kernel, both the nightlies and built from the repo. Nougat and Oreo. All oreo from nightlies and nougat from 26/01/2017. I havent gone back in the repo.

**Comment by Learnbydoin** [comment]
what is it on the kernel and not on the cable do you want to tell me?

**Comment by hussaini1** [comment]
Use 
Modprobe ath9k_htc

If u hv tp link

**Comment by Learnbydoin** [comment]
@hussaini1 i have not tp link you can read the titel

**Comment by Learnbydoin** [comment]
@BesoBerlin das kabel ist denn auf dem weg... 
Bald sollte ich es erhalten

**Comment by Learnbydoin** [comment]
@BesoBerlin das kabel ist angekommen trotzdem geht es immer noch nicht...
Hab jetzt auf marshmallow gewechselt 
Und diese Version von kali nethunter https://build.nethunter.com/release/marshmallow/
Geflasht.
Aber es buggt rum in bezug wenn ich von der nethunter APP aus z.b custom comman oder mana starte passiert nichts 
Bzw das terminal bleibt danach einfach schwarz über die direkte Eingabe geht es mit wifite also im terminal 
Welche custom Rom würdest du mir empfehlen für nethunter ? 
Und warum buggt es rum ?

**Comment by Learnbydoin** [comment]
Hab es neu geflasht jetzt klappt es.
Wenn ich aber mana starte und mich mit einem anderen gerät im wlan dann verbinde das geht nicht
Da es zu wenig schnell 
Wie kann man das beheben ?

**Comment by Learnbydoin** [comment]
@BesoBerlin naja wifite geht auch nicht
Kannst du mir sagen welches kali build du geflasht hast auf deinem nexus 6p ?
Da du ja geschrieben hast das es bei dir läuft

**Comment by BesoBerlin** [comment]
Hey... Also ich hab mein Nexus dann zurück auf Android 6 gesetzt ... Da geht alles noch ... Allerdings nutze ich es auch nicht als persönliches Handy, sondern nur für Testzwecke... Hab jetzt ein Oneplus 5 und bin damit wirklich super zufrieden... Mal gucken wie lange nethunter noch aktiv (gratis) supportet wird. Die Main Devs haben längst andere Dinge zu tun und die wenigen engagierten Devs die hier noch aktiv mitentwickeln werden mangels Support vermutlich auch nicht mehr lange machen...  Deshalb versuch dir ein stabiles System zu schaffen, welches du nicht zwingend absagen musst...

**Comment by Learnbydoin** [comment]
@BesoBerlin  ja ich habe die custom rom resurrection remix 6.1 drauf. Aber du hast meine frage immer noch nicht beantwortet welcher kernel hast du drauf und welche chroot build ? Kannst du mir das bitte mitteilen danke

**Comment by Learnbydoin** [comment]
@BesoBerlin und ?

**Comment by Learnbydoin** [comment]
@BesoBerlin huhu besoberlin lebst du noch ?
