### ISSUE TITLE
Add languages/keyboard layout for ducky script (duckhunther)

### ISSUE THREAD

**Issue by TheMMcOfficial** [offensive-security/kali-nethunter#1115]
### Device:
Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
oreo 8.0.0

### Built from repo (date and build command) or downloaded from website (links):
build date march 19

## Issue:
**Is it possible to add languages/keyboard layouts for the ducky script ?**

**Comment by rafaleon69** [comment]
Which layout are you looking for ? I know UK one was incomplete and I managed to get it working. I can share the layout if you need it.

**Comment by rafaleon69** [comment]
Ducky language support is being handled by keyseed.py in /sdcard/nh_files/modules you will have to add coresponding keys to that file in order for it to work but dont canadians just use standard us keyboard ?

**Comment by TheMMcOfficial** [comment]
Maybe it's depend where you live but personally I use those two. Does I need to add something to be able to use the language in the nethunther app ? Or I just add a section for my keyboard and everithing will be there ?

**Comment by rafaleon69** [comment]
The problem that can sometimes appear is that if the comp is running windows with US layout and you set DUCKY to execute script for eg. GB layout the keyboard mapping is not going to be 100% matched. The script is going to stop with error. Some layouts are already provided in duckhunter hid, three dots languages but i have noticed that some were incomplete hence i had to modify keyseed.py the file from which said languages are provided to the app.

**Comment by jmingov** [comment]
Hola @rafaleon69, hi @TheMMcOfficial ,

Adding a full new lang layout is not the same as updating an existing one.

- Updating an existing one: As @rafaleon69 pointed, you can edit and update the file located in the nethunter phone: `/sdcard/nh_files/modules/keyseed.py`

- Adding a full new lang layout: You'll need to rebuild the nethunter app.

1. Add a full dictionary to https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/keyseed.py (one for each lang you need)
2. Update `choices` in https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/duckhunter.py#L13 and https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/filetohid.py#L16
3. Add a name in https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/DuckHunterFragment.java#L53
4. Add a case in https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/DuckHunterFragment.java#L143 with the lang name.

Br, Jaime

**Comment by TheMMcOfficial** [comment]
Ok thanks for the answer I will try to do it. For rebuild the app is their a procedure or something special that I should know?

**Comment by jmingov** [comment]
Hi,

Can you show the changes performed @TheMMcOfficial (push them to a repo or something) so i can see whats wrong.

Br, Jaime

**Comment by TheMMcOfficial** [comment]
[Add_Canadian_multilang.zip](https://github.com/offensive-security/kali-nethunter/files/1974835/Add_Canadian_multilang.zip)
This is my change !

**Comment by TheMMcOfficial** [comment]
I found the bug.... I forgot to close the dictionary in keyspeed.py with "}," ... Now I can test it thanks ! I will add and correct my keyboard and if you whant them I can create a pull request !

**Comment by TheMMcOfficial** [comment]
I need to make some little change but yes the keyborad layout for all language id different and the Canadian mutilingual work well exept some caracters. I will try to make it work and add the french canadian layout too. I may forget some caraters but the main one will be their!! The pullresquest will be push after my test!

**Comment by TheMMcOfficial** [comment]
https://github.com/offensive-security/nethunter-app/pull/184
A have made my change and this is my pull request! ;)

**Comment by TheMMcOfficial** [comment]
@jmingov How can I add a ducjyscript to the preset menu ? I found something about it in the "DuckHunterFragment.java" but it not work.
