### ISSUE TITLE
Wifite and airodump-ng not working

### ISSUE THREAD

**Issue by Nethunterlover** [offensive-security/kali-nethunter#1116]
### Device:
Nexus 5
Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

## Issue:
When I start wifite it scans some networks then it send some deauth packets to target
After couple of seconds it says 
Airodump-ng exited with status 1
Same issue with airodump-ng
When it start scanning after while it says
Network is down
Wlan1 not found
No such device
I'm using wn722n v1

**Comment by Nethunterlover** [comment]
Anyone help please

**Comment by TheMMcOfficial** [comment]
Do you have try to put your card in monitor mode before launch wifite ? I have see some similar issues on forums.

**Comment by Nethunterlover** [comment]
@TheMMcOfficial
Thanks for reply
Yes I'm able to go in Monitor mode I tested the otg and adapter with other device it works fine
The problem I have found is with aireplay-ng
When it send deauth packets it stop I have tried --ignore negative one
But no lock it's problem in aireplay-ng
Some time before I have captured handshake with wifite and airodump-ng
But for switching to another version (mm to nougat) the problem occurs
Now I go back to previous version but the problem continuous
Help me
Thanks
Waiting for your reply

**Comment by Nethunterlover** [comment]
Anyone can help me
