### ISSUE TITLE
mitmf is not working - not capturing network traffic

### ISSUE THREAD

**Issue by alphaomicron** [offensive-security/kali-nethunter#1117]
### Device:
Redmi Note 4

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Android version 7.1.2 on LineageOS 14.1-mido

### Built from repo (date and build command) or downloaded from website (links):
version 3.16 2017-04-17

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.31-perf-g818479a (builder@mi-server) (gcc version 4.9 20150123 
(prerelease) (GCC) ) #1 SSMP PREEMPT Thu Mar 16 09:18:28 WIB 2017

## Issue:
I installed mitmf as `apt-get install mitmf` and although I get the proper screen there is no feedback. There seems to be a problem with the version of Twisted that need to be 15.5.0 and no a newer in order to work which I have already downgraded but no luck....

**Comment by Nethunterlover** [comment]
Kali nethunter is officialy for Nexus and opo devices only

**Comment by alphaomicron** [comment]
Sorry I have to disappoint you but it finally works.

**Comment by devishtank** [comment]
Are you changing its kernel?
