### ISSUE TITLE
Unable to install kalifs-amd64-full.tar.xz using Nethunter.apk

### ISSUE THREAD

**Issue by R3dy** [offensive-security/kali-nethunter#1118]
### Device:
HTC Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):
downloaded from website https://build.nethunter.com/kalifs/kalifs-latest/

## Issue:
The install of the chroot from within the .apk fails due to an invalid SSL handshake.
`error: java.net.ssl.SSLHandshakeException`

 The usesdcard option would be fine accept it is looking for a hard coded path '/storage/emulated/0/kalifs-full.tar.xz' which does not exist on my device which has no sdcard.  I have tried creating the path manually on the internal storage partition with no success.

My proposed solution would to add a simple feature to browse to and select a file.  This way tablets without an internal SD card could simply drop the file on their local storage partition and install the chroot from there.

Alternatively fix the ssl issue probably being triggered by either an invalid SSL cert or a broken URL.  perhaps an option to specify a custom URL would be helpful.

**Comment by R3dy** [comment]
Well this is embarrassing.

To whomever out there is unfortunate enough to be as dumb as me and stumbles on this issue via a Google search.  You literally just need to place the chroot on the root of your internal storage which happens to be simlinked to `/storage/emulated/0` and then rename the file from

`kalifs-amd64-full.tar.xz`

to

`kalifs-full.tar.xz`

**Comment by droolingwithsanity** [comment]
Tried this rename and i get the same error. Error file does not exist. It may be a delay on my file explorer sidebto paste or name change ill need to troubleshoot or just use a laptop to edit the file name and location. Just to be clear the location is root dir of internal sd card. The same mounted partition i see in my computer ?

**Comment by mrbanzeras** [comment]
Busybox installed ?

**Comment by droolingwithsanity** [comment]
Yes i have busybox installed

**Comment by mrbanzeras** [comment]
superSU or magisc root?

**Comment by yesrab** [comment]
Magisk root

**Comment by 0E800** [comment]
Majisk don't work well with Kali.
Use SuperSu.
