### ISSUE TITLE
Not able to use anything in nethunter NOT FOUND ERROR

### ISSUE THREAD

**Issue by pswalia2u** [offensive-security/kali-nethunter#1120]
### Device:
Nexus 7

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
Official net hunter for nexus 7 is installed.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

sh: apt-get: not found

**Comment by sfrmattos** [comment]
install chroot again via latest kali apk

**Comment by jmingov** [comment]
Wrong installation. No answer in 1 month from op. Closed.
