### ISSUE TITLE
Build 8812au.ko for Nexus 6P

### ISSUE THREAD

**Issue by alammer884** [offensive-security/kali-nethunter#1122]
### Device:

Nexus 6P

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170629-1630/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.73-nethunter-angler-1.1 (jc@westerley) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Mon Jan 16 12:30:18 EST 2017

## Issue:

Hi! And sorry for my poor english:)
I'm install NH sometimes ago and it's worked great, but now i need connect to my Nexus 6P any wi-fi device that can work with N or AC data traffic in monitor mode. I take sources from https://github.com/aircrack-ng/rtl8812au and try to build it on PC with Ubuntu 14.04x64. My main trouble was I cant find linux-headers files which usually uses for cross-compiling or direct link to kernel sources for my Nexus. Nearest was https://github.com/jcadduono/android_kernel_huawei_angler which allowed me build module 8812au.ko without any errors, but standard "insmod 8812au.ko"  under kali chroot return "insmod: ERROR: could not insert module 8812au.ko: Invalid module format" in shell and "8812au: disagrees about version of symbol module_layout" from dmesg | grep 8812. Google says that my mistake in different versions of the kernel in Nexus and cross-compiler and i dont known how fixed it. In the last couple of years there have been quite a lot of projects related to the drivers for devices with RTL8812 chipset but almost nothing on the NH pages about it, is the work with 802.11AC external adapters under  NH real?

**Comment by Learnbydoin** [comment]
what you speak for language ?

**Comment by kimocoder** [comment]
Mostly "C" but some python too :)

**Comment by jcadduono** [comment]
If you are able to build the module then you should be able to build the kernel with it, and use the nethunter installer repo or lazyflasher to install the fresh kernel with the new module and matching layout. You can see the toolchain I used in build.sh within my kernel repository. I highly suggest forking the repo and using the provided scripts, then committing your changes. It might also be a good idea to rebase on newer sources.

**Comment by alammer884** [comment]
Hi!
At the moment I was able to compile the driver for realtek8812 with kernel sources 3.10.73-nethunter-angler-2.0 from https://github.com/jcadduono/android_kernel_huawei_angler/tree/nethunter-7.1_2. I tested it on my 6P with Asus USB-AC56. By itself driver+adapter works fine, but i faced with some problems which i never got on  nethunter-angler-1.1:
1) I could not get the autoload module. Every time after plug adapter i must use insmod or modprobe for recognize it. Even after copy driver to its default path /lib/modules/$(KVER)/kernel/drivers/net/wireless/, create link to it in /lib/modules, depmod -a and modprobe in su/kali w/o errors. I found this post https://forum.xda-developers.com/showpost.php?p=73693505&postcount=47, does it mean that use modprobe for load module  after reboot device becomes standard procedure for nethunter kernels  above v.7.1?
2) Unplug adapter from device after load his module with insmod or modprobe cause silent reboot device    after 2-3 seconds away. If module wasn't load plug/unplug adapter don't affected on device state. I cant get any errors in catlog.
3) I tested supported tl -wn722n v.1.1 and result was even worse. Every attempt to use modprobe ath9k_htc cause reboot device  if the adapter was plugged during the load module or plugged after it.

For testing i use kernel-nethunter-angler-nougat-2017.11-18-1618.zip and nethunter-generic-arm64-kalifs-full-rolling-2017.11-18-1618.zip from nightly repo w/o any changes. No errors during installation from twrp. Nethunter app start w/o any errors too. 

A huge difference with my initial conifiguration on 3.10.73-nethunter-angler-1.1. Over the past few months, I have not come across any of the listed errors. Every adapter which have driver in NH (such as wn-722n or asus usb-n53) recognize and work perfect w/o any additonal commands like insmod or modprobe. Even default nh-term.apk which installed with kali image start to work w/o reinstall. 

Unfortunately the available versions available on https://github.com/jcadduono/android_kernel_huawei_angler only nethunter-angler-1.0 and nethunter-angler-2.0. Is there any way to get kernel sources for 3.10.73-nethunter-angler-1.1?

**Comment by alammer884** [comment]
To previous post:

I found in commit changes that the main difference between the kernels v.1.1 and 2.0 is that most wirelesss drivers are no longer built-in and should be downloaded directly by the user. Thus, the issue of automatic adapter init is removed, however, my main problem remains to reboot the device after modprobe for the supported drivers (if adapter already plugged or plugging after modprobe ) or reboot after modprobe my 8812 driver and manually unplug adapter some time later.

**Comment by alammer884** [comment]
Also, after fresh  install on stock PureNexus 7.1.1 and Oreo 8.0.0 images from nightly repo on kernel v.2.0 get similar errors in dmesg after modprobe ath9k_htc:

[  570.678169] ath9k_htc: Unknown symbol ieee80211_start_tx_ba_cb_irqsafe (err 0)
[  570.678293] ath9k_htc: Unknown symbol ath9k_hw_reset_calvalid (err 0)
[  570.678391] ath9k_htc: Unknown symbol ath_key_config (err 0)
[  570.678411] ath9k_htc: Unknown symbol ath9k_hw_btcoex_init_3wire (err 0)
[  570.678536] ath9k_htc: Unknown symbol ieee80211_free_hw (err 0)
[  570.678555] ath9k_htc: Unknown symbol ath9k_hw_reset (err 0)
[  570.678605] ath9k_htc: Unknown symbol ath9k_hw_setuptxqueue (err 0)
[  570.678623] ath9k_htc: Unknown symbol ath9k_hw_startpcureceive (err 0)
[  570.678661] ath9k_htc: Unknown symbol ieee80211_alloc_hw (err 0)
[  570.678680] ath9k_htc: Unknown symbol ieee80211_start_tx_ba_session (err 0)
[  570.678711] ath9k_htc: Unknown symbol ath9k_hw_setmcastfilter (err 0)
[  570.678758] ath9k_htc: Unknown symbol ath9k_hw_btcoex_set_weight (err 0)
[  570.678777] ath9k_htc: Unknown symbol ieee80211_register_hw (err 0)
[  570.678827] ath9k_htc: Unknown symbol __ieee80211_create_tpt_led_trigger (err 0)
[  570.678845] ath9k_htc: Unknown symbol ath9k_hw_setpower (err 0)
[  570.678877] ath9k_htc: Unknown symbol ath9k_hw_phy_disable (err 0)
[  570.678913] ath9k_htc: Unknown symbol ath_hw_setbssidmask (err 0)
[  570.678959] ath9k_htc: Unknown symbol ath9k_hw_setrxabort (err 0)
[  570.678976] ath9k_htc: Unknown symbol ath9k_hw_btcoex_bt_stomp (err 0)
[  570.678996] ath9k_htc: Unknown symbol ieee80211_get_buffered_bc (err 0)
[  570.679014] ath9k_htc: Unknown symbol ieee80211_find_sta (err 0)
[  570.679032] ath9k_htc: Unknown symbol ath9k_hw_beaconinit (err 0)
[  570.679159] ath9k_htc: Unknown symbol ath9k_hw_settsf64 (err 0)
[  570.679178] ath9k_htc: Unknown symbol ath9k_cmn_count_streams (err 0)
[  570.679237] ath9k_htc: Unknown symbol ath9k_hw_init_global_settings (err 0)
[  570.679256] ath9k_htc: Unknown symbol ath9k_hw_name (err 0)
[  570.679301] ath9k_htc: Unknown symbol ath9k_hw_beaconq_setup (err 0)
[  570.679331] ath9k_htc: Unknown symbol ieee80211_stop_tx_ba_cb_irqsafe (err 0)
[  570.679350] ath9k_htc: Unknown symbol ath9k_hw_init_btcoex_hw (err 0)
[  570.679385] ath9k_htc: Unknown symbol wiphy_to_ieee80211_hw (err 0)
[  570.679404] ath9k_htc: Unknown symbol ath_reg_notifier_apply (err 0)
[  570.679435] ath9k_htc: Unknown symbol ieee80211_queue_delayed_work (err 0)
[  570.679454] ath9k_htc: Unknown symbol ath9k_hw_write_associd (err 0)
[  570.679473] ath9k_htc: Unknown symbol ath9k_cmn_update_ichannel (err 0)
[  570.679580] ath9k_htc: Unknown symbol ieee80211_rx (err 0)
[  570.679610] ath9k_htc: Unknown symbol ath_is_world_regd (err 0)
[  570.679653] ath9k_htc: Unknown symbol ath9k_hw_ani_monitor (err 0)
[  570.679671] ath9k_htc: Unknown symbol ath9k_hw_getrxfilter (err 0)
[  570.679688] ath9k_htc: Unknown symbol ath9k_hw_btcoex_disable (err 0)
[  570.679717] ath9k_htc: Unknown symbol ieee80211_wake_queues (err 0)
[  570.679750] ath9k_htc: Unknown symbol ath9k_hw_set_tsfadjust (err 0)
[  570.679768] ath9k_htc: Unknown symbol ath9k_hw_set_sta_beacon_timers (err 0)
[  570.679846] ath9k_htc: Unknown symbol ath9k_hw_gettsf64 (err 0)
[  570.679864] ath9k_htc: Unknown symbol ath9k_hw_resettxqueue (err 0)
[  570.679901] ath9k_htc: Unknown symbol ath9k_hw_disable (err 0)
[  570.679928] ath9k_htc: Unknown symbol ath9k_hw_setopmode (err 0)
[  570.679956] ath9k_htc: Unknown symbol ath_printk (err 0)
[  570.679975] ath9k_htc: Unknown symbol ieee80211_tx_status (err 0)
[  570.680013] ath9k_htc: Unknown symbol ieee80211_stop_queues (err 0)
[  570.680055] ath9k_htc: Unknown symbol ath9k_hw_reset_tsf (err 0)
[  570.680073] ath9k_htc: Unknown symbol ath9k_hw_get_txq_props (err 0)
[  570.680151] ath9k_htc: Unknown symbol ath9k_hw_releasetxqueue (err 0)
[  570.680171] ath9k_htc: Unknown symbol ath9k_hw_setrxfilter (err 0)
[  570.680203] ath9k_htc: Unknown symbol ieee80211_iterate_active_interfaces_atomic (err 0)
[  570.680259] ath9k_htc: Unknown symbol ieee80211_unregister_hw (err 0)
[  570.680284] ath9k_htc: Unknown symbol ath9k_cmn_get_curchannel (err 0)
[  570.680322] ath9k_htc: Unknown symbol ath_regd_init (err 0)
[  570.680342] ath9k_htc: Unknown symbol ath9k_hw_gpio_get (err 0)
[  570.680361] ath9k_htc: Unknown symbol ieee80211_beacon_get_tim (err 0)
[  570.680399] ath9k_htc: Unknown symbol ath9k_cmn_update_txpow (err 0)
[  570.680418] ath9k_htc: Unknown symbol ath_key_delete (err 0)
[  570.680437] ath9k_htc: Unknown symbol ath9k_hw_stopdmarecv (err 0)
[  570.680455] ath9k_htc: Unknown symbol ath9k_cmn_get_hw_crypto_keytype (err 0)
[  570.680474] ath9k_htc: Unknown symbol ath9k_hw_wait (err 0)
[  570.680492] ath9k_htc: Unknown symbol ath9k_hw_btcoex_enable (err 0)
[  570.680525] ath9k_htc: Unknown symbol ieee80211_queue_work (err 0)
[  570.680545] ath9k_htc: Unknown symbol ath9k_cmn_init_crypto (err 0)
[  570.680563] ath9k_htc: Unknown symbol ath9k_hw_set_gpio (err 0)
[  570.680606] ath9k_htc: Unknown symbol ath9k_hw_cfg_output (err 0)
[  570.680625] ath9k_htc: Unknown symbol ath9k_hw_deinit (err 0)
[  570.680650] ath9k_htc: Unknown symbol ath9k_hw_init (err 0)
[  570.680667] ath9k_htc: Unknown symbol ath9k_hw_set_txq_props (err 0)
[  570.859283] usbcore: registered new interface driver ath9k_htc

and this logs before reboot after plug WN-722N:

[  735.263870] tusb320_soft_reset
[  735.292586] tusb320_soft_reset
[  735.294214] tusb320_intb_work: schedule wdog work
[  735.294250] tusb320_drp_duty_cycle_set: set to 6
[  735.295318] tusb320_intb_work: end
[  735.491336] tusb320_irq_handler: start
[  735.491626] tusb320_intb_work: start
[  735.494593] tusb320_intb_work: attached_state is 2
[  735.494616] tusb320_intb_work: TrySNK fail, Sink detected again
[  735.494652] tusb320_drp_duty_cycle_set: set to 0
[  735.495925] SMBCHG: smbchg_external_power_changed: smbchg_external_power_changed: current_limit = 0
[  735.497557] tusb320_intb_work: end
[  735.500568] healthd: battery l=69 v=3923 t=35.7 h=2 st=3 c=-256 chg=
[  735.503255] healthd: battery l=69 v=3923 t=35.7 h=2 st=3 c=-256 chg=
[  735.521835] msm-dwc3 f9200000.ssusb: DWC3 exited from low power mode
[  735.524844] SMBCHG: smbchg_external_power_changed: smbchg_external_power_changed: current_limit = 0
[  735.526152] healthd: battery l=69 v=3923 t=35.7 h=2 st=3 c=-256 chg=
[  735.527111] healthd: battery l=69 v=3923 t=35.7 h=2 st=3 c=-256 chg=
[  735.547566] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[  735.547606] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[  735.548806] xhci-hcd xhci-hcd.0.auto: irq 163, io mem 0xf9200000
[  735.565210] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[  735.565235] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  735.565245] usb usb1: Product: xHCI Host Controller
[  735.565255] usb usb1: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  735.565264] usb usb1: SerialNumber: xhci-hcd.0.auto
[  735.566365] type=1400 audit(1523624638.270:297): avc: denied { setattr } for pid=29 comm="kdevtmpfs" name="hidg0" dev="devtmpfs" ino=67010 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  735.566817] type=1400 audit(1523624691.360:298): avc: denied { write } for pid=29 comm="kdevtmpfs" name="/" dev="devtmpfs" ino=1025 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
[  735.567201] xHCI xhci_add_endpoint called for root hub
[  735.567209] xHCI xhci_check_bandwidth called for root hub
[  735.567247] type=1400 audit(1523624691.360:298): avc: denied { write } for pid=29 comm="kdevtmpfs" name="/" dev="devtmpfs" ino=1025 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
[  735.567266] type=1400 audit(1523624691.360:299): avc: denied { add_name } for pid=29 comm="kdevtmpfs" name="bus" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
[  735.567542] type=1400 audit(1523624691.360:299): avc: denied { add_name } for pid=29 comm="kdevtmpfs" name="bus" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
[  735.567557] type=1400 audit(1523624691.360:300): avc: denied { create } for pid=29 comm="kdevtmpfs" name="bus" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
[  735.567729] type=1400 audit(1523624691.360:300): avc: denied { create } for pid=29 comm="kdevtmpfs" name="bus" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
[  735.567744] type=1400 audit(1523624691.360:301): avc: denied { mknod } for pid=29 comm="kdevtmpfs" capability=27 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=1
[  735.567899] type=1400 audit(1523624691.360:301): avc: denied { mknod } for pid=29 comm="kdevtmpfs" capability=27 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=1
[  735.567914] type=1400 audit(1523624691.360:302): avc: denied { create } for pid=29 comm="kdevtmpfs" name="001" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  735.568065] type=1400 audit(1523624691.360:302): avc: denied { create } for pid=29 comm="kdevtmpfs" name="001" scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  735.568079] type=1400 audit(1523624691.360:303): avc: denied { setattr } for pid=29 comm="kdevtmpfs" name="001" dev="devtmpfs" ino=80491 scontext=u:r:kernel:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[  735.570240] hub 1-0:1.0: USB hub found
[  735.570286] hub 1-0:1.0: 1 port detected
[  735.570580] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[  735.570605] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[  735.570687] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
[  735.570698] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  735.570708] usb usb2: Product: xHCI Host Controller
[  735.570717] usb usb2: Manufacturer: Linux 3.10.73-nethunter-angler-2.0 xhci-hcd
[  735.570726] usb usb2: SerialNumber: xhci-hcd.0.auto
[  735.572087] xHCI xhci_add_endpoint called for root hub
[  735.572099] xHCI xhci_check_bandwidth called for root hub
[  735.572877] hub 2-0:1.0: USB hub found
[  735.572920] hub 2-0:1.0: 1 port detected
[  736.030664] usb 1-1: new high-speed USB device number 2 using xhci-hcd
[  736.054903] usb 1-1: New USB device found, idVendor=0cf3, idProduct=9271
[  736.054935] usb 1-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[  736.054946] usb 1-1: Product: USB2.0 WLAN
[  736.054956] usb 1-1: Manufacturer: ATHEROS
[  736.054966] usb 1-1: SerialNumber: 12345
[  736.081717] usb 1-1: ath9k_htc: Firmware htc_9271.fw requested
[  736.087411] ueventd: firmware: loading 'htc_9271.fw' for '/devices/soc.0/f9200000.ssusb/f9200000.dwc3/xhci-hcd.0.auto/usb1/1-1/firmware/htc_9271.fw'
[  736.158708] ueventd: loading /devices/soc.0/f9200000.ssusb/f9200000.dwc3/xhci-hcd.0.auto/usb1/1-1/firmware/htc_9271.fw took 0.0717114 seconds

what's wrong with me, both of my 6P and 3.10.73-nethunter-angler-2.0?:)
