### ISSUE TITLE
Nethunter does not see the network card on the AR9271 OnPlus3T

### ISSUE THREAD

**Issue by fedor3099** [offensive-security/kali-nethunter#1125]
### Device:
OnePlus 3T

### Built from repo (date and build command) or downloaded from website (links):
https://drive.google.com/uc?id=1fj4Zy3yRr5QKAhPn1ounzbKnuzmqh4KM

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.66-perf+ (OnePlus@ubuntu-142) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Dec 27 22:52:00 CST 2017

## Issue:
iwconfig does not see the wn721n card on the Ar9271, the drivers have installed, the entire system is updated, lsusb shows the connected card, but modprobe does not see the module, I want to stay on OREO and believe that this problem can be solved, tell me please what can I do, can be compiled the kernel itself based on the stock?
![screenshot_20180414-115735](https://user-images.githubusercontent.com/34012347/38767286-03b78fd6-3fe7-11e8-9d5d-2b8249c68fe3.jpg)
![screenshot_20180414-130848](https://user-images.githubusercontent.com/34012347/38767288-086f4c4e-3fe7-11e8-80bd-e5d51a5ec85e.jpg)
![screenshot_20180414-130545](https://user-images.githubusercontent.com/34012347/38767290-0bc5a0f0-3fe7-11e8-96c2-934844dc1abb.jpg)
![screenshot_20180414-115834](https://user-images.githubusercontent.com/34012347/38767291-0bec7c3e-3fe7-11e8-96a0-1a67854344ef.jpg)

I understand such topics already probably a lot, direct me to the right one, I'm just a beginner here

**Comment by svdvmxwl** [comment]
@binkybear I am using Nethunter on Oneplus 3 and I am facing same issue with latest Oreo.
I flashed Generic-arm64 kernel and Generic-arm64-full-kalifs.
lsusb has given same result. i.e, I was able to detect the wireless adapter. 
But it doesnot show up in wifite command or any other commands.
Please hep us.
Thanks :)

**Comment by 0E800** [comment]
@svdvmxwl 
Review:
https://github.com/offensive-security/nethunter-devices/tree/master/nougat/oneplus3

If you check out the other devices you will notice that alot of the devices only contain a zImage or -dtb.
Your device requires modules folder to be included.

I suggest you git clone Kali-Nethunter Installer and create a new oneplus3 folder in devices/oreo/ and make sure to copy over the module folder from the nougat oneplus3 folder.

Next you will need to get a zImage from your current Rom, there is a python script that will seperate zImage from boot.img. Put the zImage inside your nethunter-installer/device/oreo/oneplus3 and build the kernel.

Else you can try to manually copy over the modules from the module folder in devices/nougat/oneplus3/modules into their respective folders in your android system folder.

**Comment by svdvmxwl** [comment]
@0E800 
Hi, sorry that I didn't notice this thread. I actually created a new thread for this issue and you replied to it.
Thanks for that. So, shall I follow this steps? or shall I wait for your Kernel ?
I can try to manually copy the modules folder. It seems to be direct method for me. Let me know your comments :+1:
