### ISSUE TITLE
nexus 6p kali nethunter wifite problem

### ISSUE THREAD

**Issue by Learnbydoin** [offensive-security/kali-nethunter#1127]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
marshmallow 

### Built from repo (date and build command) or downloaded from website (links):

https://build.netthunter.com/release/marshmallow/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.94+ (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #4 SMP PREEMPT Fri Jan 8 19:14:10 UTC 2016
root@kali:~#

## Issue: Wifite dont work please help me
![screenshot_20180415-022306](https://user-images.githubusercontent.com/37378439/38773756-3a305944-4055-11e8-93f7-bf8687e1e0f2.png)

**Comment by EastwindZL** [comment]
Rewrite wifite2 : https://github.com/derv82/wifite2

fix bug!

**Comment by Learnbydoin** [comment]
auch bei wifite 2 trettet das selbe problem auf...
hab das schon vorher versucht
