### ISSUE TITLE
Nexus 6p wifi ALFA Realtek or Atheros cards not working 

### ISSUE THREAD

**Issue by patkszen** [offensive-security/kali-nethunter#1128]
### Output of 
cat /proc/version in adb shell or NetHunter Terminal:
`Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Wed Sep 6 16:16:05 EDT 2017`

## Issue:
I have two wireless cards AWUS036H and AWUS036NHA, realtek and atheros respectively. None of the cards seem to be working, multiple OTG cables tried, some logs below. Let me 

```
root@kali:/# ifconfig wlan1 up
wlan1: ERROR while getting interface flags: No such device

root@kali:/# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@kali:/# lsmod
Module                  Size  Used by

root@kali:/# lspci - probably not useful 
0001:00:00.0 PCI bridge: Qualcomm Device 0300
0001:01:00.0 Network controller: Broadcom Limited BCM4358 802.11ac Wireless LAN SoC (rev 03)

root@kali:/# modinfo ath9k_htc
filename:       /lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/net/wireless/ath/ath9k/ath9k_htc.ko
firmware:       htc_9271.fw
firmware:       htc_7010.fw
description:    Atheros driver 802.11n HTC based wireless devices
license:        Dual BSD/GPL
author:         Atheros Communications
alias:          usb:v0CF3p20FFd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v04DAp3904d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0411p017Fd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v083ApA704d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0846p9018d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0CF3p7010d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v1668p1200d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0CF3p7015d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v057Cp8403d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0CF3pB002d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0CF3pB003d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v040Dp3801d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v04CAp4605d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13D3p3350d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13D3p3349d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13D3p3348d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13D3p3346d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13D3p3328d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13D3p3327d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v07D1p3A10d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0846p9030d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0CF3p1006d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0CF3p9271d*dc*dsc*dp*ic*isc*ip*in*
depends:        ath9k_hw,ath9k_common,mac80211,ath
intree:         Y
vermagic:       3.10.73-nethunter-angler-2.0 SMP preempt mod_unload modversions aarch64
sig_id:         X509
signer:         Magrathea: Glacier signing key
sig_key:        3D:47:91:33:C5:86:2A:7E:4D:6F:24:38:1B:74:EE:D0:CF:81:E3:3A
sig_hashalgo:   sha512
signature:      02:00:0B:5E:FA:D1:36:28:68:2C:3C:AA:18:0D:94:99:7C:84:18:FC:
		05:2E:26:D4:B8:5B:DB:74:04:AD:CC:BC:53:95:0B:37:22:20:E6:3E:
		6E:7D:43:2B:1B:CA:7C:5C:83:C4:2B:64:E0:73:B2:3E:E7:2A:66:28:
		94:6F:1F:71:D1:43:E4:52:13:8A:51:CB:78:49:3F:98:93:DB:B2:6D:
		C2:38:C5:40:09:5E:CF:44:48:91:06:7F:5A:36:9C:19:80:F4:E9:E1:
		7A:1B:91:1E:3D:83:08:BE:CF:78:CC:06:64:73:68:47:D0:D4:FE:00:
		6A:F2:E2:2D:38:F5:2C:54:21:63:37:14:F7:F8:9A:01:58:F1:29:AE:
		A6:12:C0:95:04:55:B8:E4:7C:25:59:1A:E8:EC:6A:90:C2:5F:E3:5B:
		FB:5A:09:14:7E:82:59:39:A4:A8:BB:CA:88:37:CE:59:92:44:87:87:
		D2:E5:B7:78:91:1C:94:33:92:2E:8E:06:C0:F8:66:D8:21:B6:89:2E:
		47:3C:5A:F3:9E:E3:CE:84:94:8D:AB:28:41:75:F4:BA:8F:85:31:60:
		47:D4:14:6B:4C:18:F0:2E:CE:99:1F:E8:B6:07:4D:EA:C2:5E:5C:4D:
		0B:C5:33:AB:AB:95:D8:46:C0:D5:5C:F2:49:2F:78:02:3D:CB:21:99:
		16:85:92:67:CC:A4:91:15:36:34:DC:82:67:C6:1A:E6:7D:D9:CE:9C:
		E7:B0:01:B8:66:7A:CC:9F:3F:12:DA:D1:C9:82:E5:AD:BF:DA:43:3F:
		AF:2E:7F:5F:B4:08:B8:8F:BF:D1:C9:8A:73:57:FB:74:12:15:DE:42:
		5B:4A:82:CE:D7:41:63:B4:0D:AE:83:A9:CA:5F:77:58:33:20:F5:3A:
		25:1B:3D:11:47:22:AD:2C:90:2C:F5:02:F6:33:4B:08:F9:46:6A:29:
		03:0F:DB:92:2D:3B:76:59:5A:7F:A0:DE:E2:4D:3A:64:6C:D2:23:B2:
		BE:5F:D6:B5:19:7C:76:1C:8B:BE:15:1C:78:C5:BC:B9:C0:82:6B:1E:
		EF:A2:E7:BD:20:9C:42:5C:36:8F:5E:0F:17:CB:B7:A2:83:31:76:9D:
		07:34:3B:E7:15:6C:D9:D3:39:F9:AC:86:C3:5B:62:DB:76:CA:50:98:
		16:4D:92:F5:11:01:41:A8:4B:9E:08:42:49:F2:01:62:E3:45:C5:71:
		0F:06:59:BD:83:6F:33:97:6E:B7:7A:84:FA:C4:7E:32:9D:7A:6E:BC:
		37:F3:2F:99:5B:15:5D:FE:79:13:00:01:E3:05:2E:E2:94:81:75:8A:
		F1:C0:D7:03:B8:E1:69:AF:D7:2C:7B:0F:A5:1C
parm:           debug:Debugging mask (uint)
parm:           nohwcrypt:Disable hardware encryption (int)
parm:           btcoex_enable:Enable wifi-BT coexistence (int)

root@kali:/# modprobe ath9_htc #phone reboots after this and issues still persists 

```

**Comment by ozsteyr** [comment]
For me, use https://build.nethunter.com/nightly/3.15.4-20170126-2226/
Any newer kernels will not work for wireless cards, older kernels are ok. Building from the repo is no good. 
The Devs have yet to understand there is a problem.

**Comment by alammer** [comment]
I'm happy to see that I'm not the only victim of the nethunter-angler-2.0 kernel:) . For me, the most successful configuration was Android 7.1.1-> PureNexus 7.1.1->https://build.nethunter.com/nightly/3.15.4-20170629-1630/. It works perfectly with almost any of the recommended cards without any additional  actions with drivers or system. I was able to run monitoring on angler-2.0 even the AC card on Realtek RTL8812AU chipset with extenal build driver (except that the Nexus reboot if card unplug from USB port:) ), but can't get a working Alfa036HN or  TL-WN722N (Atheros). I want o try build angler-2.0 wih jcadduono build config except return Atheros and RT2800 back to built-in (angler-1.1) from loadable (angler-2.0) and may be roolback SE policy changing.

**Comment by ozsteyr** [comment]
whats the differences between 1.1 and 2.0 in relation to wifi modules?

**Comment by patkszen** [comment]
did https://build.nethunter.com/nightly/3.15.4-20170126-2226/ and
      https://build.nethunter.com/nightly/3.15.4-20170629-1630/ had any issues with bluetooth?

I went back to 7.1.1 b=N4F26J, built from the repo, just doing update/upgrade but so far either wifi or bluetooth not detected

**Comment by alammer** [comment]
1)take 6p with any OS 
2)flash angler-n4f26u-factory-131d7b01.zip from fastboot and start Android
3)copy purenexus_angler-7.1.1-20170317-OFFICIAL.zip, NUF26N_vendor.img, kernel-nethunter-angler-nougat-3.15.4-20170629-1630.zip, nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170629-1630.zip to /sdcard/Download and poweroff
4)flash twrp-3.1.1-0-angler.img from fastboot
5)reboot bootloader W/O system reboot
6)go to twrp recovery
7)Wipe->Advanced->wipe everything EXCEPT "Internal Storage"
8)return to Install
9)flash NUF26N_vendor.img
10)flash purenexus...zip
11)reboot system, start Android, make start settings, poweroff
12)go to twrp recovery
13)flash nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170629-1630.zip
14)flash kernel-nethunter-angler-nougat-3.15.4-20170629-1630.zip
15)reboot sysytem
16)run NH app

Two different 6P, above a year, no problems with chipsets on rt2800usb or ath9k_htc drivers. Just plug card to usb, run NH app or NH terminal, make ifconfig wlan1 down &&  iwconfig wlan1 mode monitor && ifconfig wlan1 up and  got wlan1 in monitor mode. 
No additional action such as Insmod or modprobe is required for driver, just plug card to usb and set monitor mode in NH app/nh_term.

**Comment by patkszen** [comment]
I bet this is stupid question but what exactly is pure android, isn't this a separate image that supposed to be installed on its own rather than with factory image ?

**Comment by alammer** [comment]
Yes, most likely :) Now, when testing various modifications of the NH kernel, I just flash PureNexus w/o factory image.
But this is a procedure that guarantees me the full capacity of wi-fi cards on the "factory" NH. Last summer, I spent the whole day to find the best combination of firmware versions.
I'm sure that you will be able to substantially optimize this process for your own purposes :) But I have so far switched to solving other problems with NH :)

**Comment by randontracking** [comment]
alammer, thank you! I have been banging my head on this for weeks trying to get nethunter to recognize my TL-WN722N on my 6P! Thank you! I'm now back to dual booting Kali and Lineage 15.1!

**Comment by ASHERH4X** [comment]
@alammer , much appreciated.  I plan on blogging about this with some working download links.  took me a bit to find the vendor image.
