### ISSUE TITLE
Issues from URL https://github.com/offensive-security/nethunter-devices/issues/145

### ISSUE THREAD

**Issue by Twilight-Dream-Of-Magic** [offensive-security/kali-nethunter#1130]
******
## Google Nexus 6P

******
## Oreo (Android 8.0)

******
### Built from repo (date and build command) or downloaded from website (links):
**Use command from build.py script file**

##### Then reboot goto TWRP recovery mode, install done build the zip file

******
## **Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017-05) ) #1 SMP PREEMPT Wed Sep 6 16:27:46 EDT 2017**

******
## Issue:
@binkybear 
@offensive-security 
@jcadduono 
@chrisk44 
@nethunteros 

##### root@kali# `lsusb > /sdcard/Linux-List-Show-USB.log`

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

##### root@kali# `iwconfig | grep wlan > /sdcard/Linux-Wireless-Network-Interfaces-Extensions.log`

wlan0     IEEE 802.11abgn  ESSID:off/any  

##### root@kali# `modinfo /system/lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/wireless/ath/ath9k/ath9k_htc.ko > /sdcard/ath-wireless-driver-module-info.log`

filename:       /system/lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/net/wireless/ath/ath9k/ath9k.ko
license:        Dual BSD/GPL
description:    Support for Atheros 802.11n wireless LAN cards.
author:         Atheros Communications
depends:        ath9k_hw,ath9k_common,mac80211,ath
intree:         Y
vermagic:       3.10.73-nethunter-angler-2.0 SMP preempt mod_unload modversions aarch64
sig_id:         X509
signer:         Magrathea: Glacier signing key
sig_key:        35:AB:F7:28:65:21:2B:FF:D6:41:D5:40:96:A4:C2:68:6D:08:70:9E
sig_hashalgo:   sha512
signature:      02:00:85:82:86:95:8C:3B:53:F1:E8:7E:55:73:75:9B:86:06:84:B0:
		BB:10:15:C3:18:30:C5:8C:2E:BF:C9:37:2B:23:6E:FA:4C:08:24:39:
		A0:93:E6:0D:9A:47:05:68:13:43:08:FD:B5:84:64:3A:36:08:43:C0:
		A6:7D:FC:99:0B:F8:CC:E2:AA:65:4A:8C:7A:AA:30:F2:5D:A9:89:EC:
		F7:F0:60:99:C2:4B:35:C4:99:EC:0F:5B:42:13:5B:40:16:06:EB:6D:
		49:D8:8F:89:99:4D:9F:CF:91:1E:B9:30:4E:5A:2E:81:5C:67:29:81:
		A2:9A:0E:A5:C4:1C:56:0B:72:AA:CF:B3:1C:56:6C:7F:F4:5C:A3:DB:
		0B:EF:9A:5E:95:F8:DF:EA:9C:38:1B:4F:E3:3E:1A:A0:E5:19:39:3D:
		4C:7B:C1:94:0E:35:C1:46:35:3C:CB:53:D4:D6:51:54:4E:75:CE:58:
		72:A5:5D:EC:68:7E:47:4A:5E:5D:D7:A5:1A:7F:4F:2B:6F:C7:F4:5B:
		4E:7F:F4:91:DA:25:02:7B:AF:BB:7F:EC:26:14:6B:8B:81:B2:A1:50:
		75:02:FD:D1:BD:F4:15:77:AE:F8:22:82:8D:B0:45:F6:44:77:B9:C6:
		06:F7:B7:DC:21:EA:D3:FD:76:62:1D:BC:77:ED:F5:30:F2:81:78:D0:
		AC:E0:5C:2B:ED:84:28:68:8C:2E:D7:1C:29:28:21:70:CD:56:2E:F2:
		C6:1D:36:C1:8E:69:39:33:84:83:2A:42:C0:2A:67:34:CA:8A:FC:1A:
		A0:67:1F:30:93:14:00:D5:5A:BD:43:3E:7A:F7:20:6A:76:6E:4C:45:
		41:2E:92:7B:75:CA:68:74:D8:78:5D:78:EF:EE:44:E7:FA:90:FA:20:
		6A:3C:3F:4F:CF:99:5D:C0:58:F2:EF:0C:C8:16:72:9A:18:A3:25:AD:
		29:21:C7:10:A9:31:20:29:7C:53:E4:02:84:05:E0:79:02:65:5C:24:
		B3:A0:98:B9:90:78:66:AD:07:78:0A:55:68:83:C5:65:0C:44:DD:36:
		13:D9:59:63:95:84:47:66:FD:17:F3:9A:F8:98:78:79:C6:69:86:B6:
		D3:A3:5A:EB:CC:90:35:EE:CA:9B:43:66:A3:65:A3:B4:C8:C8:18:91:
		DD:D3:0A:71:8D:F1:56:02:F8:AC:C2:48:75:B0:70:CF:BD:C8:E0:24:
		D2:51:A2:7B:F9:C4:3F:84:5A:A4:B4:57:38:2C:89:C2:AD:EB:B5:EC:
		A9:D1:58:67:D5:ED:70:0F:BD:76:68:AF:89:F8:B5:57:57:B7:46:1B:
		23:41:B3:0B:E7:09:86:6A:3E:CA:24:38:69:55
parm:           debug:Debugging mask (uint)
parm:           nohwcrypt:Disable hardware encryption (int)
parm:           blink:Enable LED blink on activity (int)
parm:           btcoex_enable:Enable wifi-BT coexistence (int)
parm:           enable_diversity:Enable Antenna diversity for AR9565 (int)

##### root@kali# `modprobe --dry-run --verbose ath9k_htc > /sdcard/ath-wireless-driver-module-dry-run.log`

insmod /lib/modules/3.10.73-nethunter-angler-2.0/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/net/wireless/ath/ath.ko 
insmod /lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/net/wireless/ath/ath9k/ath9k_hw.ko 
insmod /lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/net/wireless/ath/ath9k/ath9k_common.ko 
insmod /lib/modules/3.10.73-nethunter-angler-2.0/kernel/drivers/net/wireless/ath/ath9k/ath9k_htc.ko 

##### root@kali# `dmesg --ctime > /sdcard/dmesg-error-reboot.log` (Tag: dmesg-error-reboot )

# From https://pastebin.com/ 
# (After modification, upload log files to pastebin)
******

## Before the device is normal and restarts
Tile: Nethunter Angler(Nexus 6P) Kernel dmesg Log (Runing)
View Resource Link: https://pastebin.com/W857RXHH

******

## After an abnormality occurs on the device, after restart
Tile: Nethunter Angler(Nexus 6P) Kernel dmesg Log (Error Reboot)
View Resource Link: https://pastebin.com/rMv3h2Vz

******

## Tag: dmesg-full-no-ctime
View Resource Link:
https://github.com/Twlilght-Dream-Of-Magic/kali-linux-nethunter-error-logs/blob/master/2018-04-23/dmesg-full-no-ctime.log
https://raw.githubusercontent.com/Twlilght-Dream-Of-Magic/kali-linux-nethunter-error-logs/master/2018-04-23/dmesg-full-no-ctime.log

******

**Comment by ozsteyr** [comment]
Any luck?

**Comment by 0E800** [comment]
You cannot / should not have a personal IoT that is secure and up to date and also have a fully functioning IoT vulnerability auditing device.
The same way you cannot goto a single Chinese restaurant and expect the best chow mein and the best West Lake soup and also serves proper Manchurian beef. Its one or the other.
For the same reasons why you don't run at the pool with scissors in your hand and you don't chose to stare at the sun. 
Long story short, you would use a iPhone3 if it was the only device that could pop APs with minimal effort. Use a Lollipop or Nougat build if there is one, and make it work how it's supposed to. Then try experimenting with porting to Oreo or whatever.



I don't believe there is a high percentage of Nethunter users running Oreo as successfully as the official offsec releases provide. Most of em are just icon junkies and parlor trick 20 minute show and tell types.

The logs were difficult to read and then at the end you has a pastebin link. Maybe next time just include the link. 

You don't shoot a gun in your bedroom, and you don't purvey penetration attempts with your personal or business phone.
