### ISSUE TITLE
Custom kernel ?

### ISSUE THREAD

**Issue by TurtleForGaming** [offensive-security/kali-nethunter#1131]
### Device:
Oneplus one

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lineage os 14.1 (Nougat)

### Built from repo (date and build command) or downloaded from website (links):
Build the 25-04-2018 (dd-mm-yyyy)

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.112-cyanogenmod-g385e327 (root@kali) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jan 23 11:46:32 CST 2017

## Issue:

Can we have the source of the kernel and the build instruction to make a custom build kernel

**Comment by jmingov** [comment]
Check the wiki: https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter, sources are located here: https://github.com/offensive-security/nethunter-devices/blob/master/kernels.txt
