### ISSUE TITLE
Postgresql problem

### ISSUE THREAD

**Issue by BZBaXraM** [offensive-security/kali-nethunter#1134]
Device: Oneplus One

OS: Oreo

Kernel version: Linux kali 3.4.113-lineageos #1 SMP PREEMPT Sat Apr 28 13:46:53 CEST 2018 armv7l

- Problem: postgresql not working!
https://youtu.be/cDAKf8etZ3o

**Comment by darksty** [comment]
same problem

**Comment by darksty** [comment]
Android doesn't support POSIX or System V shared memory. It has its own non-standard API, ashmem.

PostgreSQL does not support ashmem. To make the PostgreSQL server run on Android I expect you'd need to either use a custom kernel that does support either POSIX or System V shared memory, or add support for ashmem to PostgreSQL.

There's a also wrapper tool, android-shmem that emulates System V shared memory using ashmem transparently either by direct linking or LD_PRELOAD. You could try that.
