### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by dimpol** [offensive-security/kali-nethunter#1135]
### Device:
Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/2017.11-18-1618/

Kernel and generic

## Issue:
No sound

**Comment by TheMMcOfficial** [comment]
Check this issue: https://github.com/offensive-security/kali-nethunter/issues/752
You will probably find what is wrong! I can't help you further I don't have a nexus 6 sorry.

**Comment by dimpol** [comment]
Yeah saw that. Downgraded to 6.0.1 for stability. Thanks for your help though.
Closing the issue...
