### ISSUE TITLE
Can't perform update

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#1136]
### Device:
Nexus 5X

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/release/nougat/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016
root@kali:~#

## Issue:
I'm not able to update due to this wrong signatures

Output:
root@kali:~# sudo apt-get update
Get:1 http://archive-7.kali.org/kali kali-rolling InRelease [30.5 kB]
Err:1 http://archive-7.kali.org/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive-7.kali.org/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>         W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@kali:~#

**Comment by keysersoze930** [comment]
Type in kali shell : wget -q -O - archive.kali.org/archive-key.asc | apt-key add . And type apt-get update
