### ISSUE TITLE
Wireless Cards

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#114]
What wireless cards are support (any limitations)? 

Would you recommend the AWUS036NEH due to low power consumption and small size? 

I also have the H and NHR models.

I'm using the Nexus 7 2013 Wi-Fi model, if that matters. Thanks.

**Comment by cr1p70** [comment]
TP-link WN722N works out the box for Nexus10.
should work fpr n7 from all ive found on google should be just fine for N7 devices.

**Comment by jmingov** [comment]
https://github.com/offensive-security/kali-nethunter/wiki/Wireless-Cards
