### ISSUE TITLE
Boot Loop

### ISSUE THREAD

**Issue by YRe4per** [offensive-security/kali-nethunter#1140]
Device: One Plus 3t
OS version: Oxygen 4.0.2
[url]https://downloads.oneplus.com/oneplus-3t/oneplus_3t_oxygenos_4.0.2/[/url]

Built from repo (date and build command) or downloaded from website (links):
[url]https://forum.xda-developers.com/oneplus-3t/development/kernel-kali-nethunter-oneplus-3t-t3507816[/url]

[url]https://build.nethunter.com/nightly/3.15.4-20170629-1630/[/url]

Kernel I've used:
[url]https://build.nethunter.com/nightly/3.15.4-20170629-1630/kernel-nethunter-oneplus3-nougat-3.15.4-20170629-1630.zip[/url]

I used the kernel and nethunter zip file of this link.
Also I've followed this guide.

Just changed the twrp to a modded one cuz it did not work to install nethunter

Output of cat /proc/version in adb shell or NetHunter Terminal:
Linux version 3.18.66-blu_spark-OOS-OREO (engst@sparky)
(ggc version 7.2.1 20171011 (blu_naro-7.2-2017.10) ) #2
08 SMP PREEMPT Wed Dec 6 18:37:09 WET 2017

Issue: I am stuck in a boot loop after installing nethunter succesfully.
I waited 30 minutes but no change, had the animated start of kali around 100 times i guess.
Also after reinstalling the os with adb sideload no change.
At the boot up it gives the dm-verity is not enforced error but since dm-verity is disabled while the nethunter install I guess thats right ...
After forcing a shutdown while the bootloop, after i get the same without the animation while startup, but just a black screen instead.

Thanks already :)

About the nethunter zip, I am not sure which one I've used since I just mentioned now that there are 4 different ones, but I am sure I've taken the kalifs full version and one of the 800 MB ones. 
https://i.imgur.com/zgcxB18.png

**Comment by 0E800** [comment]
@Battlereaper 
Usually that is related to kernel incompatibility.
I am fairly certain that the commits shown here:
 https://github.com/jcadduono/android_kernel_oneplus_msm8996/commits/android-7.1
Are not included in the kernel you downloaded.

I am not familiar with OxygenOS what version of Android is it? Nougat?
