### ISSUE TITLE
Error when installing the kernel

### ISSUE THREAD

**Issue by Dulzber** [offensive-security/kali-nethunter#1141]
Device Information
Xiaomi Redmi 4 (prada)
CyanogenMod 13
Android 6.0.1

Flashing files
https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-generic-armhf-2017.11-18-1618.zip
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip

Issue
Flashing the nethunter went without a problem. An error occurred while flashing the kernel.

Code from Twrp
Unpacking the installer, this may take a while...
Installing busybox applets to /sbin
Freeing up some space on /system
Coping firmware to /system/etc/firmware
Installing /system/xbin binaries
Running busybox installer...
- Installing busybox...
Running boot image patcher...
- Found boot partition at /der/blodx/mmcblk0p54
- Dumping & unpacking oryginal boot image...
- Error: Unpacking boot image!
- Aborting...
Failed to patch boot image!
Updater process ended witch EROR: 1

**Comment by Log1c1** [comment]
I have the same error, please help!
