### ISSUE TITLE
hello which building and which kernel work?

### ISSUE THREAD

**Issue by Learnbydoin** [offensive-security/kali-nethunter#1142]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
at the time nougat

### Built from repo (date and build command) or downloaded from website (links):
Looking for one that works

## Issue:
Can someone please tell me what kernel and building for the nexus 6p works so I wifite, mana wireless toolkit etc can use?
My wlan card is alfa awus036neh
Thanks for the help and in advance so I save a lot of time so I do not have to test all buildings and kernel myself

**Comment by Learnbydoin** [comment]
Helo can anyone help me?

**Comment by Learnbydoin** [comment]
possibly because there are people here who have already done so and thus know which kernel and which building works.
I ask you not to test for me but I ask that to the people who have already done it to me to tell me what works

**Comment by Learnbydoin** [comment]
Can me please ah people answer

**Comment by Learnbydoin** [comment]
Helo any body can help me?

**Comment by Learnbydoin** [comment]
Hello ????

**Comment by phoenixelijah** [comment]
I don't have the answer. My setup is different. What I can say though is that you're going to have to play with it until it works. If you are looking for easy or simple this might not be the field for you. Try one, if it doesn't do what you want then try the next. It's how we all got here...

**Comment by phoenixelijah** [comment]
Different. It's different than yours. I cannot offer advice about the specific configuration you are using.
I can offer advice about the process. It's difficult and you need to be ok with failing until you succeed.

**Comment by Learnbydoin** [comment]
@phoenixelijah and ?

**Comment by Learnbydoin** [comment]
@phoenixelijah please answer

**Comment by Learnbydoin** [comment]
Helo please help
