### ISSUE TITLE
Hid patch for kernel 4.1.x 

### ISSUE THREAD

**Issue by sriram407** [offensive-security/kali-nethunter#1143]
### Device:

Honor 6x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat 7.0, emui 5.0.2 

## Issue:
Can anyone tell me how to make own HID Patch or give me a HID patch for 4.1.x Honor 6x,Berlin,hi6250

**Comment by 0E800** [comment]
Look at the patches for the other devices and other kernels. The patch usually consists of adding 1 word to Makefile, creating 2 new files, and inserting code inbetween areas of android.c.

If you cannot locate the string by the line numbers, search for the unique string and locate where to include the new code.

**Comment by sriram407** [comment]
@0E800 Thanks Bud I will try

**Comment by kimocoder** [comment]
There are only 2 devices which supports HID currently I think. I was looking at those patches some time ago, supported are OnePlus 5 and Nexus 5x. Takena look around, but I they may be hard to add to other devices as they doesn't with only minor edits

**Comment by sriram407** [comment]
@kimocoder I have a moto g4 plus with hid patch.working perfectly.But there is a small problem.Moto g4 plus nougat is 32 bit os.so i cant install nethunter and use hid perfectly.so i have decided to build a kernel for honor 6x.In honor 6x everything is working perfectly except HID.So if anybody can help me It would be glad

**Comment by 0E800** [comment]
@sriram407 Im not sure the issue with your moto g4 has to do to its architecture being arm vs arm64.
The newer kali file system requires a kernel above 3.2.

I would try this kernel for the G4. Grab the source, modify the .config to include modules, atheros, ipv, etc. Put the generated zimage in the device tree for nethunter-installer and see if it works.

**Comment by sriram407** [comment]
@0E800 Thanks Bud I will TRy

**Comment by sriram407** [comment]
@binkybear can you make hid generic patches for 4.1.x

**Comment by 0E800** [comment]
@sriram407 If you can zip up your kernel/drivers/usb/gadget directory, I will try to patch it for you.

**Comment by sriram407** [comment]
@0E800 
[gadget.zip](https://github.com/offensive-security/kali-nethunter/files/2019215/gadget.zip)
Here you go
Thanks in advance

**Comment by sriram407** [comment]
@0E800 Basically i use stock source
http://download-c1.huawei.com/download/downloadCenter?downloadId=96012&version=415794&siteCode=worldwide

if that didnt work then try 
https://github.com/codeofhonor-dev/android_kernel_huawei_hi6250/tree/o-emui5

merge_hi6250_defconfig

**Comment by 0E800** [comment]
This is the closest match I could find that would be worth testing.
https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.18.patch

However, it looks like some of the patches have already been made.

You would also have to include the android.c in kernel/drivers/usb/gadget/Makefile
Similar to:
https://android.googlesource.com/kernel/msm/+/android-7.1.0_r0.2/drivers/usb/gadget/Makefile

I spent a little time with patching:
usb/gadget/function/Makefile
usb/gadget/function/f_hid.c

Ill try to work on it some more tomorrow.

**Comment by sriram407** [comment]
@0E800 Thanks

**Comment by sriram407** [comment]
@0E800  did you complete.AM soo eagerly waiting for it

**Comment by 0E800** [comment]
Apologies, my 6 year old is sick and haven't had time to power up the computer . I'll try taking another stab at it tonight or tomorrow.

**Comment by sriram407** [comment]
@0E800 anytime.Take care of you kid.

**Comment by sriram407** [comment]
@0E800 If you feel that is hard then Use https://github.com/OpenKirin/android_kernel_honor_berlin/tree/6.x
i felt this is more easy.And i have downgraded to 6.0

**Comment by 0E800** [comment]
This should work:
https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_not_tested/by-manufacturer-and-device-codename/motorola__athene_______kernel_3.10.patch

**Comment by sriram407** [comment]
@0E800 just now i have checked my nougat kernel and i have realized your pain 

i think we  need to edit make file in gadget/function

**Comment by sriram407** [comment]
@0E800 i have found a way to patch hid file.as we know that kernels use ANDROID COMPOSITE DEVICE (android.,andorid.h) in usb configuration.In the same way my device use CONFIGFS(configfs.c,configfs.h)

can you please try once again 
[gadget.zip](https://github.com/offensive-security/kali-nethunter/files/2042295/gadget.zip)

**Comment by sriram407** [comment]
hey with https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_not_tested/by-manufacturer-and-device-codename/motorola__athene_______kernel_3.10.patch
i got only 3 hunks 

this may work

**Comment by kimocoder** [comment]
Again, manually edit files solves hunks

**Comment by sriram407** [comment]
@kimocoder am soo confuced.can you help me with that 
[gadget.zip](https://github.com/offensive-security/kali-nethunter/files/2042693/gadget.zip)
this is my gadget zip

**Comment by kimocoder** [comment]
Im om holidays still, don't have my computer near.
But from scratch, look at the patch which files ut patches, what lines to remove/edit/add lines to and to it manually by finding the strings. Patches crossover devices would most likely "hunk" because the code is slighty different. That's all really

**Comment by sriram407** [comment]
@kimocoder if you want i will give you a cloud server with vnc access 
I have already tried to edit.But i am totally confused.

Msg to me mail.qwerty.byte@gmail.com

**Comment by kimocoder** [comment]
Not from my phone. I'm back in 3 days and could take a look then though

**Comment by sriram407** [comment]
@kimocoder Hey i have sucessfully edited f_hid.c and Makefile . my kernel source dont have android composite gadget(android.c,android.h).My stock kernel use configfs 
now what should i edit ?

**Comment by sriram407** [comment]
@kimocoder @0E800 the only patch which works is https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.18.patch

[gadget.zip](https://github.com/offensive-security/kali-nethunter/files/2045167/gadget.zip)

try editing this

**Comment by sriram407** [comment]
@kimocoder @0E800 @binkybear anyone help me please

**Comment by wangmu0579** [comment]
@sriram407 Could you share how you build Berlin and install to Honor6x?
I have downloaded the Berlin from http://download-c1.huawei.com/download/downloadCenter?downloadId=96012&version=415794&siteCode=worldwide.

Actually I have another problem: How to bring my wifie adapter work for the Honor6x?
https://github.com/derv82/wifite2/issues/126

Could you share some instruction e.g build kernel, patch for nethunter, install the new build kernel?

**Comment by sriram407** [comment]
@wangmu0579 if you just need wifi adapter support then just follow my youtube video https://goo.gl/d3KCqp.if you want hid patch.then it only works fine in emui4.1.in emui 5 it is fully unstable.and if you want hid patch your sdcard will not work in phone.it works in twrp.if you restore your kernel back then you will get back

**Comment by wangmu0579** [comment]
Yes. I have followed your video on youtube about compile/flash nethunter kernel for honor6x. 
It's been successed. 
I have rtl8188eu usb wifi adapter. I already included rtl8188eu driver during make menuconfig.
 lsusb can identify the rtl chip(rtl chip can be identify both before/after flash the compiled kernel)
Ifconfig still not working for my usb wifi adapter.  Some NetHunter forum tell me I should disable internal wifi before using external WIFI. But maybe I have missed something.

Do you have idea bring rtl8188up and can be seem using cmd ifconfig? thanks﻿
Try to contact you @QWERTYBYTE on telegram but seems sending message failed as not we were not mutual contacts.

**Comment by Muslim90** [comment]
PLEASE YOU COULD NOT CREATE A CORE (kernel) FOR Nethunter redmi note 6 pro.OS Lineages 16 android pie 9

**Comment by Muslim90** [comment]
PLEASE YOU COULD NOT CREATE A CORE (kernel) FOR Nethunter redmi note 6 pro.OS Lineages 16 android pie 9

**Comment by bhasiththamis** [comment]
> Yes. I have followed your video on youtube about compile/flash nethunter kernel for honor6x.
> It's been successed.
> I have rtl8188eu usb wifi adapter. I already included rtl8188eu driver during make menuconfig.
> lsusb can identify the rtl chip(rtl chip can be identify both before/after flash the compiled kernel)
> Ifconfig still not working for my usb wifi adapter. Some NetHunter forum tell me I should disable internal wifi before using external WIFI. But maybe I have missed something.
> 
> Do you have idea bring rtl8188up and can be seem using cmd ifconfig? thanks﻿
> Try to contact you @QWERTYBYTE on telegram but seems sending message failed as not we were not mutual contacts.

@wangmu0579  hey bud, do u know how to add hid patch to samsung galaxy grand prime g530h ? I followed the @sriram407  tutorial in YouTube ...but, he doesn't include how to add the hid feature to our kernel...if u know means pls help with this...
Thanks in advance !
Waiting for ur replay :)
