### ISSUE TITLE
Apps aren't showing up

### ISSUE THREAD

**Issue by MonkeysHack** [offensive-security/kali-nethunter#1146]
### Device:
Nexus 7

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmello w

### Built from repo (date and build command) or downloaded from website (links):

Downloaded from website

## Issue:
The nethuntee apps aren't showing up after installing

**Comment by Andrewerr** [comment]
I've had the same problem with my Nexus 10.I've just rebooted it several times and apps finally appeared.

**Comment by 0E800** [comment]
Also notice apps don't show up when installed on Oreo. Also when installing
SuperSU, app doesn't show nor does it prompt for accepting root access,
just auto accepts root.

**Comment by MonkeysHack** [comment]
I've tried rebooting about 10 times still nothing and I'm running Marsh mellow not Oreo or nougat

**Comment by 0E800** [comment]
Try manually installing them. Open the zip, the apk are in data/app.

**Comment by MonkeysHack** [comment]
Thank you very much worked perfectly manually installing them

**Comment by 0E800** [comment]
I am glad that worked for you. You may have to find the apk for the keyboard gadget app as well.

Please mark as solved.
