### ISSUE TITLE
Anyone patch HID patch for 3.10.x

### ISSUE THREAD

**Issue by sriram407** [offensive-security/kali-nethunter#1147]
### Device:
honor

 6x
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmellow

## Issue:
Someone patch generic or a HID patch for my device 

SoC hi6250

https://github.com/OpenKirin/android_kernel_honor_berlin/tree/6.x

**Comment by 0E800** [comment]
@sriram407 
This looks to be  a match:

https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_not_tested/by-manufacturer-and-device-codename/motorola__athene_______kernel_3.10.patch

**Comment by sriram407** [comment]
@0E800 patch: **** Only garbage was found in the patch input.

**Comment by sriram407** [comment]
@0E800 

patching file drivers/usb/gadget/android.c
Hunk #1 FAILED at 62.
Hunk #2 FAILED at 1417.
Hunk #3 succeeded at 918 with fuzz 2 (offset -1036 lines).
Hunk #4 succeeded at 1473 with fuzz 2 (offset -1523 lines).
Hunk #5 FAILED at 3387.
3 out of 5 hunks FAILED -- saving rejects to file drivers/usb/gadget/android.c.rej
patching file drivers/usb/gadget/f_hid.c
Hunk #2 succeeded at 61 (offset -4 lines).
Hunk #3 succeeded at 214 (offset -23 lines).
Hunk #4 succeeded at 289 (offset -23 lines).
Hunk #5 succeeded at 308 (offset -23 lines).
Hunk #6 succeeded at 352 (offset -23 lines).
Hunk #7 succeeded at 461 (offset -23 lines).
Hunk #8 succeeded at 478 (offset -23 lines).
Hunk #9 succeeded at 641 (offset -23 lines).
Hunk #10 succeeded at 708 (offset -23 lines).
Hunk #11 succeeded at 727 (offset -23 lines).
patching file drivers/usb/gadget/f_hid_android_keyboard.c
patching file drivers/usb/gadget/f_hid_android_mouse.c

**Comment by kimocoder** [comment]
You may need to do it manually

**Comment by sriram407** [comment]
@kimocoder Thanks i will try

**Comment by sriram407** [comment]
@kimocoder @0E800 i have patched that file.But didnot find hidg* at /dev.Should i do anything else in menuconfig

**Comment by 0E800** [comment]
What is the exact error?

**Comment by sriram407** [comment]
@0E800 there are no errors while compiling kernel 
but there are errors while patching the patch 
patching file drivers/usb/gadget/android.c
Hunk #1 FAILED at 62.
Hunk #2 FAILED at 1417.
Hunk #3 succeeded at 918 with fuzz 2 (offset -1036 lines).
Hunk #4 succeeded at 1473 with fuzz 2 (offset -1523 lines).
Hunk #5 FAILED at 3387.
3 out of 5 hunks FAILED -- saving rejects to file drivers/usb/gadget/android.c.rej
patching file drivers/usb/gadget/f_hid.c
Hunk #2 succeeded at 61 (offset -4 lines).
Hunk #3 succeeded at 214 (offset -23 lines).
Hunk #4 succeeded at 289 (offset -23 lines).
Hunk #5 succeeded at 308 (offset -23 lines).
Hunk #6 succeeded at 352 (offset -23 lines).
Hunk #7 succeeded at 461 (offset -23 lines).
Hunk #8 succeeded at 478 (offset -23 lines).
Hunk #9 succeeded at 641 (offset -23 lines).
Hunk #10 succeeded at 708 (offset -23 lines).
Hunk #11 succeeded at 727 (offset -23 lines).
patching file drivers/usb/gadget/f_hid_android_keyboard.c
patching file drivers/usb/gadget/f_hid_android_mouse.c

and there is no hidg* in /dev

**Comment by 0E800** [comment]
What do you mean by there is no hidg* in /dev.

Where are you getting that from?

**Comment by sriram407** [comment]
![screenshot_2018-05-22-00-51-53](https://user-images.githubusercontent.com/27294472/40325865-e53d49c4-5d5a-11e8-8f94-0a8f2af11dde.png)
![screenshot_2018-05-22-00-52-02](https://user-images.githubusercontent.com/27294472/40325866-e5732fee-5d5a-11e8-9c1c-2f372b9150fc.png)
![screenshot_2018-05-22-00-52-08](https://user-images.githubusercontent.com/27294472/40325867-e5a011a8-5d5a-11e8-8222-f8e3124a96d1.png)
i dont have hidg0 and hidg1 even after patching

**Comment by 0E800** [comment]
How did you patch the failed patch parts?

**Comment by sriram407** [comment]
@0E800 actully i left that thing.

Any solution?

**Comment by sriram407** [comment]
[gadget.zip](https://github.com/offensive-security/kali-nethunter/files/2023910/gadget.zip)
this is my drivers/usb/gadget without patching

**Comment by 0E800** [comment]
Thats why it didnt work.

Im looking at it now

**Comment by sriram407** [comment]
@0E800 Thanks for spending time for me

**Comment by 0E800** [comment]
Sorry man, all thought that patch is the closest to it, its not it.
Looks like the other patches worked except for android.c patches.

Closer examination of android.c I notice that the hid functions are replaced with hdb.

Not sure how to incorporate the patches for that without breaking stuff.

**Comment by 0E800** [comment]
I am going to patch the parts that failed and give you back android.c to try.

**Comment by 0E800** [comment]
@sriram407 May you please provide the android.c file that had the failed patches?

**Comment by sriram407** [comment]
@0E800 
it is in the patched gadget zip in my previous post

**Comment by 0E800** [comment]
Try replacing your patched android.c with this and try building.
Rename android.zip to android.c after you download it.

[android.zip](https://github.com/offensive-security/kali-nethunter/files/2024125/android.zip)

**Comment by sriram407** [comment]
@0E800 thanks .i will try now

**Comment by kimocoder** [comment]
Instead of using a patch that mismatches the source, edit the files manually. Run the patch in reverse and edit all files manually. Takes more time, but that's how it should be done when the sources doesn't match. If 1 line fails, the patch would most likely be useless.

**Comment by sriram407** [comment]
@0E800 
/home/dev/honor/android_kernel_honor_berlin-6.x/scripts/Makefile.build:316: recipe for target 'drivers/usb/gadget/android.o' failed
make[4]: *** [drivers/usb/gadget/android.o] Error 1
/home/dev/honor/android_kernel_honor_berlin-6.x/scripts/Makefile.build:468: recipe for target 'drivers/usb/gadget' failed
make[3]: *** [drivers/usb/gadget] Error 2
make[3]: *** Waiting for unfinished jobs....

**Comment by 0E800** [comment]
@sriram407  I need to see the actual error. Usually you gotta scroll up a bunch to find it. It will give me a location of the error and file.

**Comment by sriram407** [comment]
@0E800 
[error.log](https://github.com/offensive-security/kali-nethunter/files/2024833/error.log)

this is my log

**Comment by 0E800** [comment]
@sriram407 Okay, I reviewed and think ill be able to drunken-luck my way through them and at the least get something closer to a solution. The reason this is difficult for me is because I came from a broad and not a computer. I am no programmer, just stubborn and sometimes persistent for no reason I can determine yet. We will keep trying until we get lucky. 
None of the other patches out account for `hdb` being used where `hid` or `hidg` would normally be.
This time ill try to account for having `hdb` and include `hid` or `hidg`.

**Comment by sriram407** [comment]
@0E800 I have already raised the issue but nobody  replied there

**Comment by sriram407** [comment]
@0E800 hey i have got one patch
https://github.com/qyadong/Android_HID_Keyboard/blob/master/MOFD_HID/Patches/kernel-USB-Gadget-Emulation-of-Android-USB-HID-Device.patch
with this patch i have only got 2 errors 
[gadget-patched.zip](https://github.com/offensive-security/kali-nethunter/files/2030835/gadget-patched.zip)

Plzz 

hope this works for me

**Comment by 0E800** [comment]
I received the file. Way to go, i'll take a look at it shortly.

**Comment by 0E800** [comment]
[android.zip](https://github.com/offensive-security/kali-nethunter/files/2033373/android.zip)
That was a simple edit. I hope it works, thank you for providing alternative sources.

Download android.zip and rename it android.c and replace the one there.

**Comment by sriram407** [comment]
@0E800 Hey that thing worked 
but you forgot to add hidg1 mouse patch 

keyboard is working sucessfully

**Comment by 0E800** [comment]
I'll take a look to see where I missed it, at least we are making forward progress . Wtg

**Comment by sriram407** [comment]
@0E800 hey no need i have edited your android.c and added a file into gadget folder from my previous patched folder 

and now it works very fine

thanks for the help you did until today

**Comment by 0E800** [comment]
That's awesome. I'm glad we were able to find success , thank you for your persistence. Would you mind uploading or attaching a zip of the corrected files? Be well.

**Comment by sriram407** [comment]
@0E800 
[gadget-patched-emui4.1.zip](https://github.com/offensive-security/kali-nethunter/files/2034964/gadget-patched-emui4.1.zip) This thing worked for me

**Comment by sriram407** [comment]
@0E800 if you dont mind will you help me with my nougat kernel.cause i love nougat

**Comment by 0E800** [comment]
For Honor? 

Sure, I can't promise too much if I cant get it to build but I'll try .

**Comment by bhasiththamis** [comment]
@sriram407 bro i need the patches for galaxy grand prime g530h codename : fortunave3g
I don't know how to find the patch...pls help me???
