### ISSUE TITLE
My oneplus 3 is not able to connect to Edimax EW-7811Un

### ISSUE THREAD

**Issue by svdvmxwl** [offensive-security/kali-nethunter#1148]
### Device:
OnePlus 3
OnePlus3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo

### Built from repo (date and build command) or downloaded from website (links):

Kernel 
:kernel-nethunter-generic-arm64-2017.11-18-1618.zip  
link:
https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-generic-arm64-2017.11-18-1618.zip

Nethunter:
nethunter-generic-arm64-kalifs-full-rolling-2017.11-18-1618.zip
link: 
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-arm64-kalifs-full-rolling-2017.11-18-1618.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.99-perf+ (OnePlus@ubuntu-210) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Web May 9 22:37:14 CST 2018

## Issue:
When I check with lsusb,
I am getting the name od the wireless displayed. In all other commands, not abe to detect this device. wlan1 i absent in all the cases.

**Comment by 0E800** [comment]
What does dmesg say about it?

**Comment by svdvmxwl** [comment]
[mydmesg.log](https://github.com/offensive-security/kali-nethunter/files/2033970/mydmesg.log)
This was the log. 
I can see avc denied.  Please check it once

**Comment by 0E800** [comment]
You have many underlying issues with  using that generic kernel.
Too many for me to sort out. Best to compile a kernel yourself and use the nethunter builder to create your patched kernel.

**Comment by kimocoder** [comment]
https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

**Comment by svdvmxwl** [comment]
@kimocoder thanks 😊

**Comment by kimocoder** [comment]
Kernel sources are found in the list here:
https://github.com/offensive-security/nethunter-devices/blob/master/kernels.txt

**Comment by svdvmxwl** [comment]
@kimocoder  
@0E800
Hi, in this method I can only see the mac80211 injection package.  
will this patch the HID and other stuff like DuckHunter HID, Bad USB, MITM framework, pineaple and wardriving? 
i  case my question isn't clear, if I follow and somehow complete flashing the Kernel successfully, will all the features on NetHunter work? 
or this process is exclusive for wlan1?

**Comment by 0E800** [comment]
All of those things can vary between the different types of devices . 

I'll try to build you a flash able nethunter kernel for your device if you can provide me with it's model name . 

It will most likely be a nougat build as I think the nethunter apps don't work well enough on Oreo

**Comment by svdvmxwl** [comment]
@0E800 
Hi!! 
First of all, thanks for your support. 

device: OnePlus3 
current android: Oreo 
latest Nougat : Oxygen OS 4.5.1 
latest Nougat Beta: Oxygen Open Beta 24 
arch : arm64 
chipset: SnapDragon 820 
currently using external wifi: Edimax EW-7811Un 

Device specific Kernel for Nougat is already available in Nightly builds page. I don't know whether it has issues. 

However, since I want to use it as daily driver on primary device, I'm trying for the latest Oreo Oxygen OS. 

since  this is my Primary device, I might wanna buy another device if Oreo is not supported . 
I'm considering to buy Lenovo ZUK Z2 plus which has same SD820 chipset.

So, also Please let me know whether you will be able to provide  kernel for that device. 
If not,  Iwould downgrade my device to Nougat and flash the Kernel you provide me. 

Thanks again!!

**Comment by 0E800** [comment]
@svdvmxwl 
````
Package Complete: /root/aicp/out/target/product/oneplus3/aicp_oneplus3_o-13.1-UNOFFICIAL-20180524.zip


      ##### ####****   ########****     
    ############**** ##########******   
   ####     ####****#####  ****  *****  
   ###       ###****####   ****   ****  
   ####     ####****#####  ****  *****  
    ############**** ##########******   
      ##### ####****   ########****     
                           ****         
                           ****         
www.aicp-rom.com   -   Get your flash ON

#### build completed successfully (01:26:36 (hh:mm:ss)) ####
````

Here is link to AICP Oreo Rom:
	
aicp_oneplus3_o-13.1-UNOFFICIAL-20180524.zip  547.7 MB
https://cloud.keys-daggers.org/s/79rMeZ2e3tS8CyN
If it boots then I can try enabling modules and patch for injection.
I will only need to provide you with a kernel at this point, until everything is confirmed working.

I do not have OxygenOS build environment, but I have just recently cloned FreedomOS which is a Nougat Rom for OneplusX models. I do not have any OnePlus devices to test with.

**Comment by svdvmxwl** [comment]
@0E800 
Thanks for the build.
I'll flash it once I reach home after my work(9 hours of nonsense).

I can test the kernel for you for Oneplus3, if you want. 

Please try Freedom OS Oreo for Oneplus3 also. And all of this can happen after I get a secondary device(which can happen in 2 days).

**Comment by 0E800** [comment]
Here is the default build of FreedomRom for OnePlus3. Its a big file because of all the Aroma options it provides.

If it boots up for you, then I will try to modify the kernel for Nethunter functionality.
	
FreedomOS-op3-0E800-3.3-1.0.zip   1.5 GB
https://cloud.keys-daggers.org/s/qJ3Qj5YXXSaYDZn

**Comment by svdvmxwl** [comment]
@0E800 
Hi,
The ROM installation stopped at 94%, waited for one hour, but not working.. It stil hhung up there!!

**Comment by svdvmxwl** [comment]
@0E800 
So, I installed the AICP to check it and used some g-apps I downoaded for omni-rom 8.1//
The install was success. And then the boot started...
Successfully booted up the AICP but it encrypted my data,. unable to go after the 'Checking for updates screen" it hung up and I waited for 1 hr before formatting my entire ROM to factory settings..
Can you suggest which g-apps to use?

**Comment by 0E800** [comment]
@svdvmxwl 
I dunno what wrong with the FreedomRom did it launch the Aroma installer and allow you to select options to install ?

For the AICP, I have created a modified kernel that include the kernel options needed for packet injection. I am going to try and create a Nethunter flashable zip that would be used to add Nethunter to the AICP rom that works.

Ill try to have a DL up within a few hours.

**Comment by svdvmxwl** [comment]
@0E800 
Yes, it launched the Aroma installer and allowed me to select  options.. however, it stopped at 94%, as I said. It stuck there for 1 hour. So, I decided to force shutdown and it went to bootloop.

Later, AICP installation was successful and is stable..
I have one doubt though..  you have created a modified kernel that include the kernel options needed for packet injection.. will HID Interfaces also work in it??
Thanks for the update :)

**Comment by 0E800** [comment]
I think it's possible that one of those aroma options  is causing the boot loop. If you don't mind, may you please try freedom room and try only installing the bare minimal options? Then I can root out what package is causing the failure .

As for USB keyboard HID gadget, I'll patch the kernel for that before I send you the zip.

The goal is to have a consistent installation workflow of:

1. Flash AICP room
2. Flash Pick Gapps
3. Flash Nethunter+kernel
4. Flash Supersu (unless I can get Supersu to be installed by Nethunter)

**Comment by svdvmxwl** [comment]
@0E800 
I'l give Freedom OS a try, again.
regarding supersu, I am using Magisk SU for SuperUser. Is it possible to exclude SU installation ?
so that I can install magisk in the 4th step..

**Comment by svdvmxwl** [comment]
@0E800 
In the second phase of installation, the installation stuck up at 94%
This is same as previous problem.
" Applying Your Settings  "  --> " Setting up Google Assistant " is the option that I can see where it stopped..

**Comment by 0E800** [comment]
Thank you.

Regarding Magisk , if you use Magisk then I don't believe you will get the bennifits of the custom kernel . So no point in using Magisk else you don't get packet injection or HID gadget.

**Comment by svdvmxwl** [comment]
Ok then I'll use Supersu

**Comment by svdvmxwl** [comment]
Hi @0E800 
Due to power issues in my area.. I am not able to flash the device. I'll let you know the results of flashing aicp 2morrow (15hrs from now)

**Comment by svdvmxwl** [comment]
Hi @0E800 
Sorry for the delay. I was engaged in my works.
I'll tell you the result of AICP tomorrow.

**Comment by svdvmxwl** [comment]
@darksty 
But Oreo Kernel is created for some other devices like Nexus.

**Comment by darksty** [comment]
@svdvmxwl 

Yes and there is already have 3t oreo kernel.just need to rebuild by nethunter
