### ISSUE TITLE
Can't use apt-get

### ISSUE THREAD

**Issue by AndroTX** [offensive-security/kali-nethunter#1150]
### Device: 
Samsung J3

### OS version (KitKat/Lollipop/Marshmallow/Nougat): 
Lollipop

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
"Linux version 3.10.65-12303860 (dpi@SWDG9704) (gcc version 4.8 (GCC) #2 SMP PREEMPT

## Issue:
Can't use apt-get:
"apt-get: error while loading shared libraries: libapt-private.so.0.0: cannot open shared object file: No such file or directory"

**Comment by 0E800** [comment]
Lmgtfy link here.
