### ISSUE TITLE
problems with the installation full wipe doesn't solve it ..

### ISSUE THREAD

**Issue by n1n741** [offensive-security/kali-nethunter#1152]
### Device:

nexus 5 

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

6.0

### Built from repo (date and build command) or downloaded from website (links):

downloaded from https://www.offensive-security.com/kali-linux-nethunter-download/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gb7558f2 (root@kali) (gcc version 4.7 (GCC) ) #2 SMP PREEMPT Wed Oct 7 02:16:12 UTC 2015

## Issue:

i was having some problems with the updates so i decided to update the gpg keys first but it don't solve the issue .. 

so i was reading in forums and some users was talking about reinstalling nethunter 

( flash it again using twrp ) 

when i tried it was stucks at 90% i left it 30' but it doesn't go forward the "progress bar"

then i try to wipe data and wipe cache

but when i do it again ( flash the rom) it still stucks at 90% ..  

so more later i choose to make a full wipe ( wipe data/factory reset, format system & wipe dalvik cache)

i saw the error opening /data/local/nhsystem/kali-armhf/dev/ram12 ( not a directory)

how i could avoid or fix this? i know is a careless error but i don't know clearly if this has something to do with the installation...

thank you so much

**Comment by n1n741** [comment]
updates:

now i try this

rm -rf /data/local/nhsystem in the terminal of twrp

the error related before has disappeared

then i wipe cache and data & flash the zip file 

it shows checking for kali chroot in installer ...

kernel installation completed ( but it's stucked in 90% and the progress bar doesn't have any movement..) 

what should i do ?

thanks

**Comment by 0E800** [comment]
Make a full wipe ( wipe data/factory reset, format system & wipe dalvik cache)
DONT REBOOT
Go Back and click on Format Data or Wipe Drive and type "yes"
REBOOT to TWRP

In TWRP do a standard / default factory wipe, verify no errors.

If:  `error opening /data/local/nhsystem/kali-armhf/dev/ram12`

Mount System
Open TWRP File Manager
Delete: `/data/local/nhsystem/kali-armhf`

Flash Stock or Custom ROM
REBOOT
Flash GAPPS
REBOOT
Flash Nethunter zip
REBOOT
Flash SuperSU

Turtle Power!

**Comment by n1n741** [comment]
Thanks you so much OE800 

I did It and now it's installed successfully

:D
