### ISSUE TITLE
Kali Kernel for z2 plus help needed for compiling

### ISSUE THREAD

**Issue by theimprobableoneATSH** [offensive-security/kali-nethunter#1153]
### Device:
Zuk Z2 Plus

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo 8.1.1

### Built from repo (date and build command) or downloaded from website (links):

commands used:
As mentioned on Kali modifying kernel instructions.
https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

## Issue:
I followed all the instruction I tried more than 50 times the kernel gets compiled but whenever I try to boot into kernel it runs into kernel panic and doesn't boot.
This is the source code I used for kernel
https://github.com/DD3Boh/android_kernel_zuk_msm8996
I tried the latest branch 8x-caf-treble and lineage-os-15.1 

Pls guide me with the commands I can use since the kernel is based on arm64 if there are any extra commands or why is it running into kernel panic.

@0E800 hope u and other people can help . Thanks a ton!

**Comment by sriram407** [comment]
@theimprobableoneATSH Hey Bud,Try this patch https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.18.patch

By the way.To mention someone in github use @andtheirname

**Comment by theimprobableoneATSH** [comment]
@sriram407
Thanks for ur reply sir
I will definetly try compiling it with the changes.
I'm just a bit confused which modules shld I copy to my device. Are you talking about those modules which are created after compiling the kernel?

Before you insmod another wifi drivers use modinfo somedrivers.ko .Then you will see dependencies.Use insmod in order of dependencies.Once you know the order goto nethunter app.Then goto custom commands and add your commands with su before all commands in android mode.
Can you explain the above , my sncere apologies for such big query. Can you share your number so I can discuss further problems if I face if u don't mind?

**Comment by sriram407** [comment]
Which WiFi adapter do you have

**Comment by theimprobableoneATSH** [comment]
@sriram407
Tp link 722n

**Comment by sriram407** [comment]
@theimprobableoneATSH Have you compiled modules

**Comment by theimprobableoneATSH** [comment]
@sriram407
I have only compiled the kernel then this is the final result I get

GZIP    arch/arm64/boot/Image.gz
  CC      drivers/video/backlight/backlight.mod.o
  CC      crypto/ansi_cprng.mod.o
  CC      drivers/video/backlight/generic_bl.mod.o
  CC      drivers/video/backlight/lcd.mod.o
  CC      net/bridge/br_netfilter.mod.o
  CC      net/ipv4/tcp_bic.mod.o
  CC      net/ipv4/tcp_htcp.mod.o
  LD [M]  crypto/ansi_cprng.ko
  LD [M]  drivers/video/backlight/backlight.ko
  LD [M]  drivers/video/backlight/generic_bl.ko
  LD [M]  drivers/video/backlight/lcd.ko
  LD [M]  net/bridge/br_netfilter.ko
  LD [M]  net/ipv4/tcp_bic.ko
  LD [M]  net/ipv4/tcp_htcp.ko
  CAT     arch/arm64/boot/Image.gz-dtb

So which modules u require?

**Comment by sriram407** [comment]
@theimprobableoneATSH not these.You need to make modules of mac80211 and wirelesss drivers by using m instead of y in menuconfig

**Comment by theimprobableoneATSH** [comment]
@sriram407
I compiled the kernel making the changes by changing Y to M but still no change the device still shows kernel panic any help here can u get me the file complied?

**Comment by theimprobableoneATSH** [comment]
@sriram407
I compiled the kernel making the changes by changing Y to M but still no change the device still shows kernel panic any help here can u get me the file complied?

**Comment by theimprobableoneATSH** [comment]
@sriram407
I made the following changes still the device runs into kernel panic. Can u get me this file compiled?

**Comment by theimprobableoneATSH** [comment]
@sriram407 I have successfully compiled the same but I m getting remote dtb error while flashing it pls do guide me.....I have seen ur video on YouTube thanks for ur guidance...

**Comment by theimprobableoneATSH** [comment]
LINK    vmlinux
  LD      vmlinux.o
  MODPOST vmlinux.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
  DTC     arch/arm64/boot/dts/qcom/msm8996-v3-pmi8996-mtp-z2_plus.dtb
  Building modules, stage 2.
  MODPOST 11 modules
  CC      drivers/net/wireless/rt2x00/rt2500usb.mod.o
  CC      drivers/net/wireless/rt2x00/rt2800lib.mod.o
  CC      drivers/net/wireless/rt2x00/rt2800usb.mod.o
  CC      drivers/net/wireless/rt2x00/rt2x00lib.mod.o
  GZIP    arch/arm64/boot/Image.gz
  CC      drivers/net/wireless/rt2x00/rt2x00usb.mod.o
  CC      drivers/net/wireless/rt2x00/rt73usb.mod.o
  CC      drivers/net/wireless/rtlwifi/rtl8192c/rtl8192c-common.mod.o
  CC      drivers/net/wireless/rtlwifi/rtl8192cu/rtl8192cu.mod.o
  CC      drivers/net/wireless/rtlwifi/rtl_usb.mod.o
  CC      drivers/net/wireless/rtlwifi/rtlwifi.mod.o
  CC      lib/crc-itu-t.mod.o
  LD [M]  drivers/net/wireless/rt2x00/rt2500usb.ko
  LD [M]  drivers/net/wireless/rt2x00/rt2800lib.ko
  LD [M]  drivers/net/wireless/rt2x00/rt2800usb.ko
  LD [M]  drivers/net/wireless/rt2x00/rt2x00lib.ko
  LD [M]  drivers/net/wireless/rt2x00/rt2x00usb.ko
  LD [M]  drivers/net/wireless/rt2x00/rt73usb.ko
  LD [M]  drivers/net/wireless/rtlwifi/rtl8192c/rtl8192c-common.ko
  LD [M]  drivers/net/wireless/rtlwifi/rtl8192cu/rtl8192cu.ko
  LD [M]  drivers/net/wireless/rtlwifi/rtl_usb.ko
  LD [M]  drivers/net/wireless/rtlwifi/rtlwifi.ko
  LD [M]  lib/crc-itu-t.ko
  CAT     arch/arm64/boot/Image.gz-dtb
make[1]: Leaving directory '/root/Desktop/android/out'


This is my output 
Error is remote dtb not found how can I fix it???
