### ISSUE TITLE
Net Hunter for Huawei P10 Lite?

### ISSUE THREAD

**Issue by infectedw** [offensive-security/kali-nethunter#1154]
Any possibility to Huawei P10 Lite get Net Hunter?

**Comment by VoltixIGS** [comment]
Tra i have p8 lite 2017 and i run Kali nethunter widout problems only not work hid attacks

**Comment by mirzaatifbaig** [comment]
You can compile it from source by yourself There is a simple guide.

**Comment by TheMMcOfficial** [comment]
If you want the able the make HID injection you need to compile a kernel for your phone with a patch.
You can follow the steps here: https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

The hid patch can be found here: https://github.com/pelya/android-keyboard-gadget
