### ISSUE TITLE
Move To GitLab

### ISSUE THREAD

**Issue by keeganjk** [offensive-security/kali-nethunter#1159]
This should be moved to GitLab for... reasons.

**Comment by jcadduono** [comment]
i don't see any valid reasons to do so, just a bunch of people making a big fuss over microsoft ownership

**Comment by kimocoder** [comment]
Agreed with jcadduono. Microsoft allready told is everything will be "business as usual", besides doing the opposite would make people flee.. and who wants that

**Comment by jmingov** [comment]
Hi,

Sorry, but its up to Offensive Security, if they move the whole account we move, if not, we don't. 

Is not an issue or something to be discussed here.
Closing it by now, reopen it if required @jcadduono @offensive-security.
