### ISSUE TITLE
I use oneplus3T phone ,For  2017.11-18-1618 version , what H2OS version should I choose ?

### ISSUE THREAD

**Issue by shangdiaibide** [offensive-security/kali-nethunter#1161]
I use oneplus3T phone ,For  2017.11-18-1618 version ,this is the latest one I saw at 
https://build.nethunter.com/nightly/

 what H2OS version should I choose ?

**Comment by Twilight-Dream-Of-Magic** [comment]
You have oneplus 3T? 

First,  use third party android recovery mode the image file and flash this data to the device, then now changed android recovery mode partition.

Second, you need use android recovery mode to flashing this kernel binary-package.(update linux kernel)
https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-oneplus3T-cm-nougat-2017.11-18-1618.zip

Then, what is your smartphone CPU architecture?
You have to check it. 
ARM or ARM64 (Maybe Impossible is of CPU architecture I386)?

Last, flash one linux subsystem image-package in the you android device and reboot you android system of the device.(update android system)

If you device CPU architecture crafts of equal to ARM.
Push this binary zip file and update system for this smartphone.
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-amd64-kalifs-full-rolling-2017.11-18-1618.zip

Else if you device CPU architecture crafts of equal to ARM64.
Push this binary zip file and update system for this smartphone.
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip

**Comment by darksty** [comment]
7.1.2的都可以，有kernel可以用

8.0的kernel还没出来
