### ISSUE TITLE
Terminal crashing

### ISSUE THREAD

**Issue by IanSteg** [offensive-security/kali-nethunter#1162]
### Device:
Nexus 7 2012

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from website

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.1.10-Bricked-v0.591-g0a2e5f6 (root@kali) (gcc version 4.7 (GCC) ) #2 SMP PREEMPT Tue Oct 27 23:53:13 UTC 2015

## Issue:
When I try to start terminal in KALI mode, it just crashes and closes. I can open it in ANDROID and ANDROIDSU mode fine

**Comment by 0E800** [comment]
Search for the newest release, there is a link around . Get the one for
nethunter.apk and nh-term.apk.

If you can't find it I'll try to

Make sure you uninstall old ver. first.
Make sure you run nh-term and accept SuperSU permission before you run
Nethunter.

Side note : would you be willing to beta test a Nougat and/or Oreo build
ROM + Nethunter ?

I got to a point where its mostly working and would like to verify if its
just me before I release public.

Be well.

**Comment by 0E800** [comment]
Here:


https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer/update/data/app

**Comment by IanSteg** [comment]
Would the Nougat/Oreo build work on mine? I currently have Lollipop.

**Comment by 0E800** [comment]
Tbh I got it working for nougat and then decided to try Oreo . then you
know uh life drama happened and now that I've settled down as a single
father I'm ready to pick the torch up again.

I was hoping to add your email to list, I would send you a DL link .
hopefully within a few weeks.

**Comment by IanSteg** [comment]
I think I'll pass for now. Maybe if I get another device.

**Comment by IanSteg** [comment]
Those new apk's didn't work. Same issue.

**Comment by 0E800** [comment]
Do you have supersu installed ?

**Comment by IanSteg** [comment]
Yes

**Comment by 0E800** [comment]
When you reinstalled nh-term and ran it , did it prompt you to accept
SuperSU permissions?

**Comment by IanSteg** [comment]
The message that shows just before it closes is
> The Kali chroot is already running!

**Comment by IanSteg** [comment]
Still an issue...
