### ISSUE TITLE
Required key not available

### ISSUE THREAD

**Issue by Benimautner** [offensive-security/kali-nethunter#1167]
I've installed nethunter today over the magisk module. But now, every time I start a new Kali terminal it says 
```
bash: /etc/profile: required key not available
bash: /root/.bash_profile: required key not available
```

This also happens every time I try to run a command (e.g. cat)
 
```
bash: /bin/cat: required key not available
```

The only way to open a terminal which works is by installing/updating an metapackage because then, there is a root terminal. Then everything works.

Since I haven't found anything on the web, I'd be very happy if someone could help me out.

I'm running everything on my `OnePlus 6`  , rooted with `magisk`.

Android: 8.1

OxygenOS version: 5.1.8

Magisk version: v16.7

**Comment by 0E800** [comment]
In don't believe Kali is compatible with majisk .

Supersu is necessary.

**Comment by DrillNBlast** [comment]
That has been my experience also! The only configuration in which Magisk was ever successful was when installed in conjunction with SU also being present.

I installed on a galaxy s5 on various versions of android OS's and samsung firmware and can't be certain if my inability to make it work is device/OS specific.

Sent from my iPhone

On 19 Jul 2018, at 02:29 pm, "0E800" <notifications@github.com<mailto:notifications@github.com>> wrote:

In don't believe Kali is compatible with majisk .

Supersu is necessary.

**Comment by 0E800** [comment]
Good info regarding the differences between the root methods .
https://www.xda-developers.com/magisk-vs-supersu/

Looks like someone got it working but I am not sure external WiFi monitor /
injection works:
https://forum.xda-developers.com/android/software-hacking/nali-kethunter-modded-kernel-supported-t3770455

**Comment by DrillNBlast** [comment]
Thanks now I haven't read the info you linked to yet but I recall during my research it has to do with the folders each root method use which affects the root folder path for kali install files if I'm remembering correctly!

My best suggestion to anyone taking this endeavor on is to do your homework on how it was made to work by the developer and why you ought to understand why each install is unique and should be treated as such! Also I found the most success when following the authors suggestion to and install and verify each section of the installation to avoid as many issues as possible!

That said I'd like to officially and publicly thank all the developers for their hard work and a brilliant idea to extend kali distro to work over top of android devices!

Sent from my iPhone

On 19 Jul 2018, at 02:50 pm, "0E800" <notifications@github.com<mailto:notifications@github.com>> wrote:

Good info regarding the differences between the root methods .
https://www.xda-developers.com/magisk-vs-supersu/

Looks like someone got it working but I am not sure external WiFi monitor /
injection works:
https://forum.xda-developers.com/android/software-hacking/nali-kethunter-modded-kernel-supported-t3770455
