### ISSUE TITLE
Did anyone manage to make Nexmon work on a nexus 6p (angler) oreo ?

### ISSUE THREAD

**Issue by TheMMcOfficial** [offensive-security/kali-nethunter#1172]
### Device:
nexus 6p (angler) oreo

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo 8.0.0 or 8.1.0

## Issue:
I have create an issue on the nexmon git and hijacker git but no one can help me there so I hope someone will be able to help me here. 
https://github.com/seemoo-lab/nexmon/issues/195
https://github.com/chrisk44/Hijacker/issues/53

I have try to compile all the lib and the app. But I can't enable the monitor mode. I have read that I must be able to enable it on the Android terminal but not in the kale term. If you can help me with this issue I will be verry grateful.  All the detail is in the nexmon issue. 

Where i'm stuck:
```
angler:/ $ LD_PRELOAD=libnexmon.so tcpdump -i wlan0   
CANNOT LINK EXECUTABLE "tcpdump": library "libnexmon.so" is 64-bits instead of 32-bits.
```

The app was compile with the lastest version with my computer.

**Comment by TheMMcOfficial** [comment]
@binkybear Did you succeed to install Nexmon on a Nexus 6P on android 8?

**Comment by TheMMcOfficial** [comment]
I think the libnexmon.so need to be 64 bit but I still got an error.

```
LD_PRELOAD=/system/su/lib64/libnexmon.so /system/su/xbin/airodump-ng wlan0                                                  
CANNOT LINK EXECUTABLE "/system/su/xbin/airodump-ng": "/system/su/lib64/libnexmon.so" is 64-bit instead 
```

**Comment by TheMMcOfficial** [comment]
Ok I have test the whole thing in nethunter and I got this:

```
root@kali:~# LD_PRELOAD=/system/su/lib64/libnexmon.so airodump-ng wlan0
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/system/su/lib64/libnexmon.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ioctl(SIOCSIWMODE) failed: Operation not supported
ioctl(SIOCSIWMODE) failed: Interrupted system call
Error setting monitor mode on wlan0
```

**Comment by TheMMcOfficial** [comment]
I have talk with the Nexmon dev And the Hijacker dev and my setup seems ok. I need the libnexmon.so 64 bits (arm64-v8) and the libraries in 32 bits (armeabi-v7a) because we can't built them in 64 bits.

The nexmon patch for the Nexus 6p (bcm4358) was compiled and apply in /vendor/firmware. 

I have compiled the Nexmon libs and bin with kali 64 bits and ubuntu 64 bit nothing change. I have no error and the architecture was add like the Nexmon Readme told me to do: sudo dpkg --add-architecture i386

I have test the NethunterOS on Nougat and the app Hijacker work well (I didn't change anything just install the app and ruen the tools). I msut miss something because it suppose to support the frame injection with the latest Nexmon firmware.

**Comment by ozsteyr** [comment]
@TheMMcOfficial would you be  OK with posting your patches for 4358?

**Comment by TheMMcOfficial** [comment]
[fw_bcmdhd.zip](https://github.com/offensive-security/kali-nethunter/files/2517068/fw_bcmdhd.zip)
@ozsteyr there you go. Sorry for the delay !

**Comment by yweiss0** [comment]
@TheMMcOfficial so it is working for you on the nexus 6p? 
I will really appreciate it if you could explain me how to make it work on the 6p

**Comment by TheMMcOfficial** [comment]
On oreo I can't manage to make it work... It's why I open this issue but I know it's possible because the NethunterOS is working I tested it.

**Comment by yweiss0** [comment]
So in nethunter you managed to make it work? if i will install nethunter on nugat/oreo it will work with packet injection ?

**Comment by TheMMcOfficial** [comment]
It has been a long time when I try it I don't remember... but nethunter os is base on nougat not on oreo.
