### ISSUE TITLE
why is mana trying to find start-nat-full-lollipop.sh?

### ISSUE THREAD

**Issue by burntGit** [offensive-security/kali-nethunter#1173]
### Built from repo (date and build command) or downloaded from website (links): burgerhunter/dumplinghunter

I posted this in mana-toolkit's github as well. This may be better suited over there, depending on what the correct solution turns out to be.

Android 8.1.0
Oxygen 5.1.3
Kali Nethunter "Burgerhunter" Kernel installed over stock oos
TWRP codeworkx 3.2
Magisk 16.7
Mana-toolkit 1.3.1-0kali

I am trying to run the mana-toolkit from the nethunter apk on my android. Every time that I try to start mana-nat-simple, my nethunter terminal opens and looks for "start-nat-full-lollipop.sh" a script that is not in the run-mana directory. Is this a version issue with my chroot? I have tried installing from apt-get after purging mana-toolkit, (and fruitywifi just incase) with no luck... on one install i tried, i compiled mana-toolkit from source but it threw way too many errors to list.

Here is the error it throws in cli:

bash: /usr/share/mana-toolkit/run-mana/start-nat-full-lollipop.sh
: No such file found

when i cd to run-mana the following scripts are listed:

fire-lamb-view.sh
start-nat-full.sh
start-nat-simple.sh
start-noupstream-all.sh
start-noupstream-eap.sh
start-noupstream-eaponly.sh
start-noupstream.sh

how can i point mana towards the correct script?

this is my first post here.

Thank you for any assistance

**Comment by 0E800** [comment]
Unless something happened officially that I wasn't aware about.
Nethunter requires SuperSU and is not really compatible with majisk.

Why you running a lolipop script on Oreo?

Google start-nat-full-lollipop.sh
Then copy paste the contents and try it if you think that's the cause .

**Comment by 0E800** [comment]
https://github.com/offensive-security/nethunter-utils/blob/master/usr/share/mana-toolkit/run-mana/start-nat-full-lollipop.sh

**Comment by burntGit** [comment]
![screenshot_20180725-221041](https://user-images.githubusercontent.com/37469011/43242745-ac807f90-9057-11e8-85de-d54bb63a069c.jpg)
so mana responded with that. Could my nethunter apk  be forr loolipop?  

kernel-nethunter-oneplus5-oos(5.1.2)-oreo-20180531_014449.zip
![screenshot_20180725-221445](https://user-images.githubusercontent.com/37469011/43242852-2db44150-9058-11e8-846e-83e36ed0b803.jpg)

**Comment by 0E800** [comment]
I'm not sure. You probably are not going to get much support from devs. as you are not using official build .

Me personally , I think there are no 100% working official builds for Oreo .

I also haven't had any luck with majisk or however its spelled.

Think the issue with most of these issues is that the user doesn't want to have to wipe or go through the process of having to wipe 3 - 10 times before they figure out all the finicky possible issues that can occur .

A lot of people trying to make this work haven't tried flashing custom ROMs and have no experience with linux.

This would be like jumping on a motorcycle without knowing how to ride a bike first. Or say water ski'ing and you don't know how to ski or how to swim.

So if it was me and the phone was not my work phone, I would use whatever official build there is .
If that means downgrading to nougat or lollipop then so be it.
Verify you can get that to work and then try working on using a custom build .

I looked up the custom burger ROM / firmware . looks like there is quite a instructional for installing it.

Did you follow steps exactly ?

I would hit up that xda thread for answers .

**Comment by burntGit** [comment]
thank you... yes i posted there as well. i did follow the installation guide exactly. it is the ctrl scripts from the version of nethunter i havr that are calling for the lollipop svript. i cant find where nerhunter falls the functions from
