### ISSUE TITLE
How to fix Transport endpoint is not connected?

### ISSUE THREAD

**Issue by thenickvendetta** [offensive-security/kali-nethunter#1174]
### Device:
Lenovo Vibe P1 Turbo (P1a42)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.0.1

### Built from repo (date and build command) or downloaded from website (links):
I use this guide to install nethunter on my device:
https://kalinethunter.blogspot.com

I downloaded kalifs files using this link:
https://build.nethunter.com/kalifs/kalifs-latest/

I use this:
kalifs-armhf-full.tar.xz

## Issue:
root@kali:/# cd /external_sd
-bash: cd: /external_sd: Transport endpoint is not connected.

**Comment by pyc0de** [comment]
Just reboot.
