### ISSUE TITLE
How to install zipalign?

### ISSUE THREAD

**Issue by thenickvendetta** [offensive-security/kali-nethunter#1175]

**Comment by thenickvendetta** [comment]
sudo apt-get install zipalign
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package zipalign is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'zipalign' has no installation candidate

**Comment by kimocoder** [comment]
Check if it's packed under another name, "apt-cache search zipalign"

**Comment by 0E800** [comment]
I figured it out.

Its part of android-build.

` apt install android-sdk`

Location on Kali is:
 ` /usr/share/android-sdk/tools `


I think you need to add it to $PATH.

When I try running it I get a bash error though.

**Comment by 0E800** [comment]
I figured it out.

Its part of android-build.


`apt install android-sdk
`

Location on Kali is:


` /usr/share/android-sdk/tools`



I think you need to add it to $PATH.

When I try running it I get a bash error though.
