### ISSUE TITLE
HID Attacks and DuckHunter HID doesn't work, but Bad USB MITM Attack does work for my device.

### ISSUE THREAD

**Issue by TheNickVendetta** [offensive-security/kali-nethunter#1176]
Device:
Lenovo Vibe P1 Turbo (P1a42) 

OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.0.1 (Stock ROM)

Built from repo (date and build command) or downloaded from website (links):
I use this guide to install nethunter on my device:
https://kalinethunter.blogspot.com

I downloaded kalifs files using this link:
https://build.nethunter.com/kalifs/kalifs-latest/

I used this:
kalifs-armhf-full.tar.xz

Issue:
HID Attacks and DuckHunter HID doesn't work, but Bad USB MITM Attack does work for my device.
#373

**Comment by yesimxev** [comment]
Have you installed kernel too? Also you should install generic kalifs installee from build.nethunter.com/nightly which has the kalifs you linked so it installs apps and supersu too. Then install the appropiate kernel
