### ISSUE TITLE
Nethunter terminal

### ISSUE THREAD

**Issue by somnath003** [offensive-security/kali-nethunter#1177]
### Device:
Redmi 4a Rolex 
I am using a custom ROM AICP

### OS version (Nougat):

7.1.2
## Issue:
I flashed nethunter I completed all setups when I touch Kali in terminal it automatically comes out..Please help me it's says no title.

**Comment by FkeyboardM** [comment]
busybox maby?  Most likely :D what version you device  running?

**Comment by hubrisnxs** [comment]
It's probably because you don't have busybox installed to su/xbin

**Comment by somnath003** [comment]
@hubrisnxs I installed busy box in su/xbin but it's doesn't work..@amzker reinstalled chroot many times but doesn't work..@FkeyboardM 7.1 android version

**Comment by amzker** [comment]
Now perfect way



DOWNLOAD Nethunter.zip 

Amd extract Chroot From It 

Paste In Sdcard

And install

**Comment by FkeyboardM** [comment]
Somnath003 what version of busybox you got installed?  What root you got?  Magisk or superSU?

**Comment by somnath003** [comment]
@amzker already done it shows some time 
Out error @FkeyboardM i am using magisk root also tried SuperSU..Version 62 busybox

**Comment by FkeyboardM** [comment]
Did you installed Nethunter from Magisk Rep?  [http://i66.tinypic.com/263zpty.jpg](url)

**Comment by somnath003** [comment]
@FkeyboarfdM yeah tried but not working

**Comment by somnath003** [comment]
I changed my custom rom and re flashed nethu get when I open kali in terminal it doesn't opens and after i type exit it will open root@kalk.. Thankyou very much for replying me friends...

**Comment by Re4son** [comment]
Fixed in the 2019.1 release
