### ISSUE TITLE
Customizing Nethunter zip

### ISSUE THREAD

**Issue by puma827** [offensive-security/kali-nethunter#1179]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com

## Issue:
i'm really really confused , i flashed my nexus 5 which had nethunter installed for one year and now i'm gonna install it again,there are many possible ways to do that,download the standard v 3.0 from 
https://www.offensive-security.com/kali-linux-nethunter-download/
or building by git tutorial orrr for me who had downloaded latest kalifs is it possible to extract the original v 3.0 and replace the kalifs and apps (like vnc , terminal) with updated one and then zip it again?

another question:
is it possible to download 
https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip
and flash it on clean nexus?
or i have to put kernel to it?
please helppp

**Comment by jcadduono** [comment]
the best way would be to flash generic armhf like the one you linked, then boot up to ensure things are working properly, then flash nexus 5 kernel zip from the same place

you can definitely replace apks and whatnot in the new zips on build.nethunter.com 
the install script will search for them so even if they dont exist in the zip as built and you add them (in the right location), it will install them
