### ISSUE TITLE
My nexus 6 is connect and disconnect automatically

### ISSUE THREAD

**Issue by pun92** [offensive-security/kali-nethunter#1180]
Device : Nexus 6
OS : android 6.0.1

After I changed my Mac address with Nethunter app, my WiFi was broken and it did not connect to any WiFi network. after that, I decided to disable DHCP and manually enter the IP, then WiFi got stuck on the optaining ip address . So I decided to change mac address to the default with Nethunter app and after I've done my WiFi connect and disconnect automatically from any WiFi i connect to it.
Please help me and sorry for bad English.

Sincerely...

**Comment by amzker** [comment]
Restore Your Original Mac

**Comment by pun92** [comment]
I do but its still connect and disconnect.

**Comment by amzker** [comment]
Re-Flash Rom
With Wiping DATA

**Comment by pun92** [comment]
Is there another way ? if not please explain just flash Nethunter or flash the 6.0.1 android and after that flash Nethunter ?
I'm asking because I'm afraid to break after Re-Flash

**Comment by pun92** [comment]
My problem has been resolved. I have two Nexus 6 phones,that both have the same problem one of them fixed by Re-Flash the the 6.0.1 android & then install Nethunter (Kali installation from0 to100).and the another one get fixed by restore the macaddress  by Nethunter app to default and change the hostname too and then restart the phone and you gonna be  OK...i keep searching the search engines for long time but believe it it just that simple but it was interested to me why the other one not getting fix by restoring the Mac to default ... To be alert as far as possible don't change the Mac for internal network adapter.
I hope I could help you and sorry for bad English . and especially thanks to amzker
