### ISSUE TITLE
Problem with airmon-ng and OnePlus3

### ISSUE THREAD

**Issue by Nick468** [offensive-security/kali-nethunter#1182]
### Device:
OnePlus 3
Realtek RTL8192CU Wireless Adapter

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Tried both, Marshmallow 6.0.1 and Nougat 7.0

### Built from repo (date and build command) or downloaded from website (links):
I picked about ten random versions for each one from about 3.1.4 to 3. 20

## Issue:
I wanted to try out hwo easy it is to crack the password of a network. As it turns out it is really hard. On my kali installation on my pc everything worked flawlessly. (At least sending deauth packages)
However on my phone it doesn't work. I start by activating the monitor mode on the external wireless card. This works. Then I kill the interfering processes. Then I can scan for wireless networks with:
airodump-ng wlan1mon
This still works and I get the list of all networks surrounding me. Now the problem starts. I type:
airodump-ng -c THE CHANNEL FROM ABOVE --bssid BSSID OF NETWORK wlan1mon
I have attached a screenshot of the terminal. No device appeares altough I am certain, that there is a device connected
![screenshot_20180806-191549 1](https://user-images.githubusercontent.com/40504392/43731089-b9018a98-99ad-11e8-8544-3640c94f6444.png)
I would appreciate any help regarding this problem.

**Comment by raypar766** [comment]
try wlan0mon. make sure you look at the name of  monitor mode it could be a
different.

**Comment by Nick468** [comment]
Sorry for my late response, I was on vacation.
If I try any command with wlan0mon I get :"ioctl(SIOCGIFINDEX) failed: No such device"
Do you have another idea what the problem could be?

**Comment by 0E800** [comment]
Are you certain the device on the network is connected wirelessly ?

If the computer connected to the network is in sleep mode then it's not going to be transmitting packets and your not going to see any action.

Get yourself a tester router to test with so you can simulate different scenarios .

**Comment by yesimxev** [comment]
Have you ran airmon-ng check kill before your step? It can remove running processes which can interfere. Also make sure firmware-realtek is installed using apt-get install. Not sure if it's needed though. Does airmon-ng show the driver itself?
