### ISSUE TITLE
tp link tl wn722n not detected in nethunter

### ISSUE THREAD

**Issue by thenickvendetta** [offensive-security/kali-nethunter#1183]
### Device:
Vibe P1 Turbo

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow (Stock ROM) 

## Issue:
tp link tl wn722n not detected in nethunter

**Comment by raypar766** [comment]
It has to be tl wn722n " v1.0"  1.2 and above will not work. open and look
on back of board.
