### ISSUE TITLE
Cannot uninstall chroot for the life of me.

### ISSUE THREAD

**Issue by BrandonHall6518** [offensive-security/kali-nethunter#1184]
## Issue:
My issue is that whenever I try to uninstall the kali chroot I get the following errors. 

rm: /data/local/nhsystem/kali-armhf/usr/bin/cpp: Operation not permitted
rm: /data/local/nhsystem/kali-armhf/usr/bin/setxkbmap: Operation not permitted
rm: bin: Directory not empty

I tired busybox chattr -a /data/local/nhsystem and then tried to delete it but still didn't work, can someone please help me because this is baffaling me on why it won't allow me to delete it.

**Comment by amzker** [comment]
You Can Able To Remove Chroot Manually 
also Able To Use Nethunter App 

manually


/data/local/
and delete nhsystem

**Comment by BrandonHall6518** [comment]
Okay I tried that even in a root file manager and mounting as r/w but guess what, it didn't do anything. Also tried from a terminal and that where I got the errors. Sooo yeah

**Comment by amzker** [comment]
Command is wrong
rm  -r use it

========
Finel way
========
Go To TWRP Recovery
And Than File Manager
And Delete
Also If Say Error
Change CHMOD

**Comment by BrandonHall6518** [comment]
Tried that too and it didn't work either, gave me the same error it gave when trying to delete it in my terminal emulator

**Comment by 0E800** [comment]
Boot to recovery (TWRP)

Mount System

Goto Advanced ->  File Manager

Navigate to /data/local/  

Delete nhsystem folder

Pat back for job well done.

**Comment by BrandonHall6518** [comment]
Also flashed a new rom, guess what didn't delete it. Also 0E800 THATS IS LITERALLY EXACTLY WHAT I TRIED. Next time try and read what I said😂😂

**Comment by jmingov** [comment]
Guys, 

If you run "rm ..." on the installation folders, with the chroot enabled, the SdCard is mounted and it will be deleted with the nethunter install. 

Be sure the chroot is not mounted before performing a manual wipe.

Doing if from the recovery is safe. Don't try it from the Android System.

Kr,
Jaime
