### ISSUE TITLE
Kernel for Samsung Galaxy s8+ ?

### ISSUE THREAD

**Issue by miguelebf** [offensive-security/kali-nethunter#1185]
some kernel for the samsung galaxy s8+ that works with nethunter

**Comment by 0E800** [comment]
Does wireless auditing work?

You are able to put external WiFi into monitor mode and also inject packets
to death and  capture WPA/WPA2 packets and grap handshakes ?

**Comment by kimocoder** [comment]
WIFI tools using kernel patches would not work, HID injection based on kernel would not work..
