### ISSUE TITLE
Error when update & upgrade

### ISSUE THREAD

**Issue by thenickvendetta** [offensive-security/kali-nethunter#1186]
root@kali:/# apt-get update && apt-get upgrade
Get:1 https://packages.microsoft.com/ubuntu/14.04/prod trusty InRelease [2846 B]
Get:3 http://security.debian.org/debian-security wheezy/updates InRelease [54.0 kB]
Get:4 https://packages.microsoft.com/ubuntu/14.04/prod trusty/main amd64 Packages [42.8 kB]
Get:5 http://security.debian.org/debian-security wheezy/updates/main armhf Packages [576 kB]
Get:6 http://security.debian.org/debian-security wheezy/updates/main Translation-en [338 kB]
Get:2 http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease [30.5 kB]
Err:2 http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: GPG error: http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by threeway** [comment]
See https://www.kali.org/news/kali-linux-2018-1-release/ under Package updates

**Comment by thenickvendetta** [comment]
Reading package lists... Done
E: Failed to fetch http://58.27.38.18/ftp.yzu.edu.tw/Linux/kali/dists/kali-rolling/main/binary-armhf/Packages.gz  File has unexpected size (15753799 != 15753773). Mirror sync in progress?
   Hashes of expected file:
    - Filesize:15753773 [weak]
    - SHA256:a2b677e09fb47139885ddc255297380d29a0f3e3f260543b9e1a7a56a27ac616
    - SHA1:7ce8729205e1881c7b9871f5ff914db0ad03ffc8 [weak]
    - MD5Sum:7987bd76df1e646b7867bdeef35f11ac [weak]
   Release file created at: Tue, 14 Aug 2018 20:45:08 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by thenickvendetta** [comment]
How to fix that?

**Comment by 0E800** [comment]
For real?

![Img](https://i.imgur.com/b0EI9yd.gif)

**Comment by thenickvendetta** [comment]
Lol
