### ISSUE TITLE
new app build detected

### ISSUE THREAD

**Issue by ilyxa769** [offensive-security/kali-nethunter#1188]
### Device:
Leeco le 2 x527

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

**Comment by ilyxa769** [comment]
[
![screenshot_2018-08-19-06-06-34-044_ru fourpda client](https://user-images.githubusercontent.com/42494874/44305023-0b8c1b80-a376-11e8-8a77-db1ec313567c.png)
](url)

**Comment by ilyxa769** [comment]
I downloaded chroot, started installing, then the installation window popped up, then this thing popped up, I rebooted the phone, and the chroot file disappeared.

**Comment by ilyxa769** [comment]
I did not have time to confirm the installation because this window popped up and then the nethunterr application flew out

**Comment by yesimxev** [comment]
You should install kalifs from TWRP recovery or so. Then start the nethunter app and install chroot
