### ISSUE TITLE
Add HID patch to the latest lineageOS Kernel for the Nexus 6P (angler)

### ISSUE THREAD

**Issue by TheMMcOfficial** [offensive-security/kali-nethunter#1189]
I'm working on a new kernel for my nexus 6p (angler) base on the LineageOS 15.1 (android 8.1) kernel because the available kernel (android 8.0) makes bootloop. 
source: https://github.com/LineageOS/android_kernel_huawei_angler

I follow the step those steps: https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel
But the HID doesn't work and I know that I need those packets: https://github.com/pelya/android-keyboard-gadget
but the procedure is not clear... 
Can somebody help me ?

**Comment by TheMMcOfficial** [comment]
I managed to make it work! I simply followed this: https://github.com/flar2/angler/commit/829f4afb6040d22a84e37ae5ae0ba0dd15733db1

**Comment by dragarok** [comment]
@TheMMcOfficial Have you built the 8.1 kernel with hid support? I tried compiling but i am a beginner in this stuff and failed.
