### ISSUE TITLE
Why Kali-Net.hunter not showing anything when i click check app update(nothing happened)

### ISSUE THREAD

**Issue by pun92** [offensive-security/kali-nethunter#1190]
### Device:
Nexus 6 (shamu)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.0.1
Build Number MMB29K

Hi...
I recently installed Kali Net Hunter in my Nexus 6 again and in Net Hunter app when i click check app update to get newer version Net Hunter app nothing happens and i lost Pineapple connector & Wardriving  & DeAuth options in net hunter app.
I've been there before please help me and sorry for bad englsih

sincerely...

**Comment by kimocoder** [comment]
The same happens over here too, nothing happens.
Bit if you're missing out on the latest app, [here](https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/nethunter.apk?raw=true) it is

**Comment by pun92** [comment]
I was trying it before i uninstall the net hunter app and install the new one Pineapple connector & Wardriving & DeAuth was back to my application list but some features like HID attacks and DuckHunter HID and etc not working after i doing this...

**Comment by yesimxev** [comment]
Sorry I can't google the nethunter apk builder. Pretty much I could find everything like kernel, nethunter fs builder and used them. Please provide a link because update button doesn't work for me too (easier to check the updates often)

**Comment by bozwald** [comment]
Build.nethunter.com

**Comment by yesimxev** [comment]
I built fs and created installer zip bit it juat pulls the apk from the repo. I thought I can build one just like a kernel from sources

**Comment by yesimxev** [comment]
Found it!
https://github.com/offensive-security/nethunter-app
