### ISSUE TITLE
No app Icons after installation on Nexus 5x and Oreo

### ISSUE THREAD

**Issue by ToySldr** [offensive-security/kali-nethunter#1191]
### Device:
Nexus 5X Bullhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Oreo 8.1.0

### Built from repo (date and build command) or downloaded from 
Built from repo
23 August 2018
python build.py -d bullhead -o -fs full

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
No Nethunter apps displayed

## Issue:
I installed via TWRP 3.2.1-0 then installed SuperSu v2.82 finally installed the NH build.  The installation seems to have gone without a problem, but there are no app icons on the phone.  I can't access the application.

**Comment by 0E800** [comment]
Nerhunter wasn't created with Oreo in mind. Use a official build. Or try manually installing each of the nethunter apks.

**Comment by amzker** [comment]
Install manually


Just Open That (Nethunter) Zip

Go to /data/app


And Install All Manually

If chroot have problem after that


In Zip You Found /local/kalifs-armh-full

That File Copy in Internal Storege
And rename it kalifs-full

Extension required of that kalifs i forget so i not writed



Than Open Nethunter app


And Install Chroot By Using Sdcarf
