### ISSUE TITLE
OnePlus One on LineageOS 15.1 or 14.1

### ISSUE THREAD

**Issue by ajes** [offensive-security/kali-nethunter#1194]
### Device:
OnePlus One (bacon/oneplus1)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
LineageOS 14.1 or 15.1

## Issue:
Please rebuild/add kernel image build for LineageOS 14.1 or 15.1 (both are stable for this device), or at least please provide .config file for 3.4.x kernel for this device that was used for building currently available kernels and please include all "patch" files that are required to apply.

This issue probably can be applied to all other "supported" devices - in short, please update kernels for devices to latest stable roms like LineageOS.

**Comment by yesimxev** [comment]
There is a kernel for 15.1 on androidfilehost, seems fine for me
