### ISSUE TITLE
Unable to "apt update"

### ISSUE THREAD

**Issue by DovaMerith** [offensive-security/kali-nethunter#1197]
### Device:
Samsung Galaxy S5 G900TL KLTE

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Resurection Remix 5.8.5
AOSP 7.1.2 (Nougat)

### Built from repo (date and build command) or downloaded from website (links):
Dont know when i downloaded the zip files, but was withing the past year. approx 6months

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.113-nethunter-klte-xx-3.0 (jc@arkyn) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP PREEMPT Sat Sep 2 14:08:48 EDT 2017

## Issue:
Unable to install any software because `apt update` spews errors at me, below is the error

`root@kali:~# apt update
Get:1 http://security.debian.org/debian-security wheezy/updates InRelease [54.0 kB]
Get:3 https://packages.microsoft.com/ubuntu/14.04/prod trusty InRelease [2,846 B]
Get:2 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease [30.5 kB]
Get:4 https://packages.microsoft.com/ubuntu/14.04/prod trusty/main amd64 Packages [44.2 kB]
Get:5 http://security.debian.org/debian-security wheezy/updates/main armhf Packages [576 kB]
Err:2 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Get:6 http://security.debian.org/debian-security wheezy/updates/main Translation-en [338 kB]
Reading package lists... Done                              
W: GPG error: http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by DovaMerith** [comment]
didnt work, 
`root@kali:~# apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 7D8D0BF6
Executing: /tmp/apt-key-gpghome.vtAJcHMw2A/gpg.1.sh --keyserver hkp://keys.gnupg.net --recv-keys 7D8D0BF6
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.vtAJcHMw2A/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
root@kali:~# 
`

**Comment by kimocoder** [comment]
rm -rf /var/lib/apt/lista && apt-get update

**Comment by DovaMerith** [comment]
`root@kali:~# rm -rf /var/lib/apt/lists && apt-get update
Get:2 http://security.debian.org/debian-security wheezy/updates InRelease [54.0 kB]
Get:3 https://packages.microsoft.com/ubuntu/14.04/prod trusty InRelease [2,846 B]
Get:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease [30.5 kB]    
Get:4 https://packages.microsoft.com/ubuntu/14.04/prod trusty/main amd64 Packages [44.2 kB]
Get:5 http://security.debian.org/debian-security wheezy/updates/main armhf Packages [576 kB]
Err:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Get:6 http://security.debian.org/debian-security wheezy/updates/main Translation-en [338 kB]
Reading package lists... Done                              
W: GPG error: http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@kali:~# 
`

So i ran the key add again and
`root@kali:~# apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 7D8D0BF6
Executing: /tmp/apt-key-gpghome.LoRMq7oLaf/gpg.1.sh --keyserver hkp://keys.gnupg.net --recv-keys 7D8D0BF6
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.LoRMq7oLaf/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
`

**Comment by kimocoder** [comment]
apt-get install dirmngr

**Comment by DovaMerith** [comment]
it says its already intalled

`root@kali:~# apt-get install dirmngr
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dirmngr is already the newest version (2.2.2-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
`

**Comment by DovaMerith** [comment]
fixed by adding `[trusted=yes]` after deb in `/etc/apt/sources.list` for that repo

**Comment by DovaMerith** [comment]
Okay, installing `kali-archive-keyring` fixed this,
