### ISSUE TITLE
How to make a DuckHunterscript that uses android variables?

### ISSUE THREAD

**Issue by Merith-TK** [offensive-security/kali-nethunter#1198]
So i am trying to make a duckhunter script that autotypes my phones ssh command into a linuxPC shell, i want it do go something like this

command
`# hostname -I 
(my current ip)`

what i want it to do is type out 
`ssh bunny@(my current ip`
`{sleep 2 seconds for connection}`
`{type my passwd}`

**Comment by DovaMerith** [comment]
Bump?

**Comment by TheMMcOfficial** [comment]
Like you said it's a feature that turn your phone into a rubber ducky so if you can't do it with a rubber ducky (with a rubber ducky script) you can't do it with a ruber ducky script in nethunter. 

The best you can do is check your ip before lauch your ducky script and manually change the ip if it is not the right one. 

You should know that all the input is perform on an other device than your phone so it seems impossible to play with linux variables store on your phone. 

I think you can manage to make something if you are able to launch your duckyscript throught the nethunter terminal with an "echo "$variable" some script" personaly I don't know how and if it will work good luck. You can check the github of the nethunter app to learn more how this feature (DuckHunterscript) works.

**Comment by 0E800** [comment]
The rubber ducky tool just injects keyboard commands. It tricks the computer into thinking it's a keyboard and not a USB HDD . 

So as I said , find out how to do it with your keyboard . Different Linux desktop environments have different keyboard shortcuts. 
All you are wanting to do is have the ducky script bring up a terminal ('WINKEY +T' on XFCE) then type your ssh command ..wait.. Type the password.

Right ?

**Comment by DovaMerith** [comment]
That's.... Not what I want, I want to use my phone and nothing else! I
can't afford a specialty keyboard with macros and has inboard storage! I
want/need to use my phone!

How would I cut off the bloat to the Chroot at the very least?

**Comment by bozwald** [comment]
Just look up the rubber ducky commands for android,

I set up a test script to brute force the pin on my android phone and it
worked fine

**Comment by 0E800** [comment]
You need to compile the kernel yourself. 

Review:
https://android.stackexchange.com/questions/160292/android-as-rubber-ducky
