### ISSUE TITLE
Kali menu doesn't show in xfce desktop (VNC)

### ISSUE THREAD

**Issue by SecurityAddicted** [offensive-security/kali-nethunter#12]
Kali menu seems to not show into Application Menu in XFCE.
A fix that worked for me was to reinstall kali-menu package:
apt-get remove kali-menu
apt-get install kali-menu

ps: Nexus 7 2012 image

**Comment by majesty8** [comment]
Does anyone know how to save the scan result into text file and save into SD card when we perform scanning through kali nethunter terminal shell? Do I need to write script? How﻿ to update kali menu and reinstall it in nexus 5?

**Comment by binkybear** [comment]
@majesty8 
You can output > /sdcard/save.txt or whatever you want to call the file from terminal.

**Comment by majesty8** [comment]
@binkybear 
In the kali nethunter terminal shell, there is a menu button in the top right corner where we can choose the "email to", when we click it, it will save all scan results in the screen into the mail for sending, but in my case, I want it to save the scan result into a txt/csv file instead, how can I achieve that? where should I edit the script to approach that result? Better to customize the menu to add one button "save to txt file" something like that..please help

**Comment by binkybear** [comment]
@majesty8 
If you want to save airodump-ng you could just use the write tac:
```
airodump-ng -w /sdcard/outputfilewhatever wlan1
```
Airodump will save to csv file then you could use a file manager to access sdcard.

**Comment by majesty8** [comment]
@binkybear 
Thanks! It works.

Can I make the scanning of this command: "su -c bootkali -> airmon-ng start wlan0 -> airodump-ng wlan1" with just a single button click? Make an app like nethunter when we click the "launch wifite" button, straight it will perform wifite scan, we dont need to key command. How can I do that too?

**Comment by ianpaine** [comment]
Why am I being sent copies of all these questions assigned to a closed bug
report?

**Comment by majesty8** [comment]
@ianpaine 
Sorry about it, I need to clear out my last doubt above which I think @binkybear can help up. Sorry again about that, please allow me to do so. Thanks
