### ISSUE TITLE
Install without Chroot? 

### ISSUE THREAD

**Issue by Merith-TK** [offensive-security/kali-nethunter#1201]
### Device:
Galaxy S5 klte, 

## Issue:
How would I install it without a Chroot? Having about 16gb on my phone leaves just between 4-5gb left over with all my apps (and files I have no clue where it's stored) and that Chroot takes about 4gb which leaves barely any room.

I only use it for the Duck Hunter and Keyboard really, is there a way I can have a minimal install of the software, where I manually install the other components as I need them?

**Comment by DovaMerith** [comment]
Is it possible to have a MINIMAL installation? Where I only have the tools for the Nethunter App to work and that's that?

**Comment by 0E800** [comment]
Curious what you think the tools Nethunter app provides. You can do anything you want with open source software.

I just don't think you fully grasp what nethunter is. An app that opens but does nothing is not a tool.

What does Kali Linux do for you?
What do you think Nethunter is?

**Comment by 0E800** [comment]
You can customise your own kernel to support HID keyboard gadget and not have to include the Kali file system.

Nethunter is android app that manages / interfaces with the Kali filesystem. Its a tool for security enthusiasts and professional pentesters to have a more mobile arsenal at their disposal. 

Its not a Baskin Robbins for general public to mix and match 31 flavors. Yaddadamean?

**Comment by 0E800** [comment]
I think a rooted device with a ssh vnc rdp etc app and added kernel modules 
to provide the HID USB gadget support is all you need . Oh and Mac changer 
app for unlimited Mac bans ;-)

You could use the minimal filesystem as apposed to full kalifs and install 
as normal then use an app like Apps2SD to move the nethunter and the Kali 
minimal  filesystem to sdcard .

I would suggest offering computer services to friends and family members in 
exchange for their old or broken screen android devices.

The more devices you have to fiddle with the better, they all have their 
use still. Like a butter knife in the hands of an assassin, still formidable.

Right now I'm experimenting with android phones without a screen . The 
screen isn't needed and only takes up battery. Hardware button key 
combination sequences to launch apps and 'hey google' to manage contacts 
and audio control.

Even if you have the credentials , how would you access a phone without a 
screen?

What model phone do you have and what is the custom ROM or kernel are you 
using ? If its not too complicated I can attempt to patch the kernel for 
HID keyboard gadget use.
@0E800
╔█████╗ ╔███████╗
██╔═████║██╔════╝
██║██╔██║█████╗
████╔╝██║██╔══╝
╔██████═╝███████╗
╚════≪8⊘⊘≫═════╝
   🅼🅸🅽🅳 ᵃˢ ⲱⲉⲁⲣⲟⲛ

**Comment by DovaMerith** [comment]
I am using a Galaxy S5 (G900TL:KLTE) with Resurection Remix 5.8.5, which is
android 7.1.2

Download Page
https://forum.xda-developers.com/galaxy-s5/unified-development/rom-resurrection-remix-n-klte-t3510376
and the direct Download
http://downloads.resurrectionremix.com/klte

Which now looking, it seems v6 is ported...

**Comment by DovaMerith** [comment]
Okay, just tested v6.1 RESURRECTION REMIX,... Don't like it, staying with
the 5.8.5 build
