### ISSUE TITLE
It goes straight to recovery instead of loading the OS

### ISSUE THREAD

**Issue by majivaxeru** [offensive-security/kali-nethunter#1202]
### Device:
Nexus 5 (D821, 32 GB)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow (6.0.1 (M4B30Z, Dec 2016)

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from website (Nexus 5 Marshmallow, 3.0)

## Issue:
I've installed, from TWRP (latest release), kali nethunter and the installation was 100% complete. I then restarted the phone but instead of loading the OS it goes straight to recovery. 
I've also tried to format all the partitions, flash again the original stock rom, flash TWRP, install supersu and busybox and then flash again nethunter. Again, installation 100% complete. However I'm still facing the same issue.
I wiped cache and dalvik both times.
During installation I check all the optionals installs.

**Comment by amzker** [comment]
Don't Flash Nethunter Zip

1.Flash Stock Rom 
And Boot Up 
Not Work

2.Flash Custom ROM 

Than Extract Your Nethunter Zip 

3.Install All Apps From Zip 

4.Copy Kalirootfs From Zip To Internal Storage
You Found In Zip/Data/Local 

5. Copy Busybox (zip/tools) To /system/xbin And /root

6. Givr Exute Permission To Both 

7.Open Nethunter 
8.Allow All Permission And Close App
9.Re-Open And Give Root Permission And Again Close 
10.Now Open Again And Go To " Chroot Install "
11.Than Install From Sdcard 
12.Now It Installed 

(IF NETHUNTER NOT FIND CHROOT FILE CHANGE FILE NAME AS APP NEED)

**Comment by yesimxev** [comment]
Both could work if you get the proper kernel from eg. build.nethunter.com
Whenever I had booting issues it was always wrong kernel installed from TWRP

**Comment by 0E800** [comment]
Sometimes you need to mount system in TWRP and do full wipe and then go back and to factory wipe. Then boot back to twrp to verify no errors occur by doing a second coat of wipe.

**Comment by majivaxeru** [comment]
Issue solved by installing custom ROM. Thanks!
