### ISSUE TITLE
Stuck on kali logo screen

### ISSUE THREAD

**Issue by majivaxeru** [offensive-security/kali-nethunter#1204]
### Device:
Nexus 5 (D821, 32 GB)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
CyanogenMod 13  (Marshmallow 6.0.1)

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from website (Nexus 5 Marshmallow, 3.0)

## Issue:
Flashed CM13 from TWRP. Everything works fine. Flashed SuperSU 2.82 from TWRP. Finally flashed nethunter zip from TWRP. I selected all the available options (Csploit, DriveDroid, Router Keygen, Shodan, USBKeyboard, nano binary, boot animation, etc) except SuperSU since I already installed it. Wiped cache and dalvik and restarted the phone but it get stuck on kali logo screen. 
Maybe I should have installed busybox before installing nethunter? Or maybe I should have installed gapps?

**Comment by 0E800** [comment]
How long was it stuck on loading screen before you got impatient ?

Try turning it on and see what it does after 15 minutes .

**Comment by majivaxeru** [comment]
I waited 30 minutes, nothing has changed.

**Comment by 0E800** [comment]
Try these instructions by Sword_of_a_1000_truths


```

I finally was able to get kali nethunter installed and working with multirom, but with a different installation method from the OP

1)I already have CM13 installed on my phone. Installed multirom from play store, installed everything needed for multirom. 
2)boot into recovery, flashed secondary ROM, you can either flash CM13 or stock MOB30Y, flash GApps if needed/wanted. In my case i flashed http://forum.xda-developers.com/goog...xus-5-t3394810 . 
3)went to this site https://idlekernel.com/nethunter/nig...20160816-0223/ and flashed the nethunter kernel kernel-nethunter-hammerhead-marshmallow-3.1.0-20160816-0223.zip. 
(If you plan on running nethunter over CM13 then flash the CM kernel kernel-nethunter-hammerheadcm-marshmallow-3.1.0-20160816-0223.zip ) reboot to make sure the kernel works with your ROM
4)Reboot back into recovery and flash nethunter-generic-armhf-kalifs-full-rolling-3.1.0-20160816-0223.zip over the secondary ROM . It says it might take up to 25mins to unpack and install, for me it took about 7-10mins.
5)when its done, boot into secondary ROM, launch the nethunter app and let it update chroot and then youre done.

kernel works with my TP-link wn722N wifi adapter with an otg Y-cable and even supports OTG charging. Im able to put wifi adapter into monitor mode and use it with wifite.

this is the original thread where i discovered alternate nethunter installer https://forums.kali.org/showthread.p...nate-installer
````

Reference:  

https://forum.xda-developers.com/google-nexus-5/general/kali-linux-net-hunter-nx5-install-noob-t3335779/page3/

**Comment by majivaxeru** [comment]
I'm trying to build Nethunter by my own but I'm not sure which one I should choose from the device options: hammerheadmon, hammerheadcm or hammerhead? What are the differences between these three?
