### ISSUE TITLE
Can't find Crazyradio PA USB dongle

### ISSUE THREAD

**Issue by Droid-MAX** [offensive-security/kali-nethunter#1205]
Device: Nexus 5
Android Version: 6.0.1
My Nexus5 mobile phone with NetHunter installed also encountered the same problem. The Crazy PA USB dongle could not be found. It is not recognized after the branch in the nrf24.py file has no backend modification, but the device information can be seen when dmesg is executed.

**Comment by TheMMcOfficial** [comment]
Do you install the nethunter kernel ? 
There is all the wifi card supported: https://github.com/offensive-security/kali-nethunter/wiki/Wireless-Cards

If your card/chipset is not supported you need to compile a kernel for your Nexus 5 with the module for it.
You can follow those steps and add a patch for your wifi card: https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

**Comment by Droid-MAX** [comment]
Can the official add the usb serial device driver to the kernel at the next update? Enable ttyACM* or ttyUSB* device files when accessing some usb devices

**Comment by Droid-MAX** [comment]
Does anyone know which kernel source code is used by the latest NetHunter kernel in Nexus5? There are several Nexus5 kernel source download addresses in the kernel.txt file.

**Comment by Droid-MAX** [comment]
I am using the nexus5 kernel source provided by binkybear, but in the process of compiling, I have not reported any options, I can't successfully compile the kernel, let alone add custom modifications.

**Comment by TheMMcOfficial** [comment]
You can maybe try this source: https://github.com/LineageOS/android_kernel_lge_hammerhead

And you will need to find an android patch to add with the kernel source. 
After all those steps you will need to "activate" it in the "make menuconfig". If everything is done correctly and the kernel is compiled. You need to flash it in your Nexus 5. You can do a zip file with the nethunter build.py in this repo. 

https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter
