### ISSUE TITLE
Msfconsole Not Starting & No Payload Genrating 

### ISSUE THREAD

**Issue by amzker** [offensive-security/kali-nethunter#1207]
### Device:
Hero2lte

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oreo

## Issue:
When When I Make Payload Or I Strat Msfconsole I Get This Type Error 
--------------

root@kali:/# msfconsole
/usr/share/metasploit-framework/lib/msf/core/payload/android.rb:86:in `not_after=': bignum too big to convert into `long' (RangeError)
	from /usr/share/metasploit-framework/lib/msf/core/payload/android.rb:86:in `sign_jar'
	from /usr/share/metasploit-framework/lib/msf/core/payload/android.rb:117:in `generate_jar'
	from /usr/share/metasploit-framework/modules/payloads/singles/android/meterpreter_reverse_https.rb:50:in `generate_jar'
	from /usr/share/metasploit-framework/lib/msf/core/payload/android.rb:38:in `generate'
	from /usr/share/metasploit-framework/lib/msf/core/payload.rb:204:in `size'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:91:in `block in recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:78:in `each_pair'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:78:in `recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:250:in `block in load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:247:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:247:in `load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:219:in `initialize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/bin/msfconsole:48:in `<main>'
root@kali:/# 

-----------------
Please help Thank You

**Comment by GetRektBoy724** [comment]
Me too...my problem is like your problem

**Comment by GetRektBoy724** [comment]
My metasploit is latest version
