### ISSUE TITLE
Nexus5 OTG stopped working after update to Kali Rolling

### ISSUE THREAD

**Issue by tjt263** [offensive-security/kali-nethunter#1208]
### Device:  
Nexus5 Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):  
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):  
Flashed with stock Marshmellow from  official Google developers repository https://developers.google.com/android/images. Possibly this one (or similar) https://dl.google.com/dl/android/aosp/hammerhead-m4b30z-factory-625c027b.zip. 

I got nethunter from https://images.offensive-security.com/nethunter-release/nethunter-hammerhead-marshmallow-3.0.zip via https://www.offensive-security.com/kali-linux-nethunter-download/. 
Standard procedure. The same as always.

### Output of `cat /proc/version`:  
`Linux version 3.4.0-gcf10b7e (android-build@wpiv11.hot.corp.google.com) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Mon Sep 19 22:14:08 UTC 2016`

### Output of `uname -a`:
`Linux kali 3.4.0-gcf10b7e #1 SMP PREEMPT Mon Sep 19 22:14:08 UTC 2016 armv7l GNU/Linux`

## Issue:
I upgraded the Kali version manually with `apt`, just like a regular computer. It broke a few things, but I managed to work most of it out. 
The problem is, it no longer seems to recognize external USB devices and I can't find any specific OTG options in the settings. Is there a package for the USB drivers, or something like that, that I can just install?

**Comment by yesimxev** [comment]
I have the same thing, lsusb did not show anything anymore. However, 
`lsusb -t `
shows the device tree, including loaded drivers. What is your result?

It seems like you need the flash the kernel as well though to get everything working through OTG.
[(https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-hammerhead-marshmallow-2017.11-18-1618.zip)]

**Comment by nikmel420** [comment]
this might sound strange but i can get otg on 5 still but only with a regular cable. it doesnt work with a y cable. i just go with it i cant undersant why.

**Comment by tjt263** [comment]
@yesimxev So you think I'll have more luck with OTG if I flash this instead?:
https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-hammerhead-marshmallow-2017.11-18-1618.zip

FYI: `lsusb` and `lsusb -t` both output nothing for me, at the moment.

**Comment by tjt263** [comment]
@nikmel420 I think that sounds normal. If I understood correctly.
