### ISSUE TITLE
hostapd-wpe: No such file or directory

### ISSUE THREAD

**Issue by Dead3ch** [offensive-security/kali-nethunter#1210]

**Comment by yesimxev** [comment]
Try a latest build: Nethunter Kalifs (with Apps), with SU: https://www.androidfilehost.com/?fid...78262904029166

**Comment by Dead3ch** [comment]
> Try a latest build: Nethunter Kalifs (with Apps), with SU: https://www.androidfilehost.com/?fid...78262904029166

Limk Dead, No download.

**Comment by Dead3ch** [comment]
**yesimxev** Sorry I do not understand you. What exactly do I need to find and download ?? You can give me this file.

**Comment by NghiaPham0909** [comment]
Thank for sharing :)

**Comment by Dead3ch** [comment]
Оке, I found this. 
1) Well, but what will she give me for my Nexus 6 ? 
2) Will it kill my phone ? 
3) Install TWRP ?

**Comment by yesimxev** [comment]
Yes it is the same generic kalifs full installer without kernel. Every instruction should be the same as before. 1 year older than the 2017.11

**Comment by Dead3ch** [comment]
Very large file size, not downloadable... :(

**Comment by yesimxev** [comment]
I will build a minimal kalifs for you. By the way why is it not doenloadable?

**Comment by Dead3ch** [comment]
**yesimxev** File size 1.2 GB.

**Comment by yesimxev** [comment]
Did you install generic kalifs minimal or full from Nightly build 2017.11-18-1618 folder? Full is about 1GB so I guess you used minimal

**Comment by Dead3ch** [comment]
No minimal. My Nightly build: "nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618" I prefer full. 
I can not download your archive, because of my Internet speed, or region...

**Comment by Dead3ch** [comment]
**yesimxev** Could you throw your archive on the torrent, so that I could download ?

**Comment by yesimxev** [comment]
https://file.io/WSAMiv

**Comment by Dead3ch** [comment]
![46666](https://user-images.githubusercontent.com/44181975/47049304-d09b3e00-d194-11e8-86e0-5859e3a0b28f.PNG)

**Comment by yesimxev** [comment]
I will try drive later

**Comment by yesimxev** [comment]
https://drive.google.com/file/d/1_l9Ct6h2BpKdSFKAuDSEUg1mPI8I0CJ3/view?usp=sharing

**Comment by Dead3ch** [comment]
Hi, Tell me you have a Nexus 6 ?
1) I need to do a svayp sections in TWRP, and what ?
2) SuperSU is in your archive, I already have SuperSu.

**Comment by yesimxev** [comment]
OnePlus1

1. Only remove chroot in nethunter app, then uninstall app and nethunter terminal.
2. You can overwrite SuperSu
3. Just a latest build (my dbus service became extra slow after 2017.11 + apt-get upgrade)
4. If you install the kernel you did already
5. If you install the kernel you did already

**Comment by Dead3ch** [comment]
Sorry, another question: 
1) Will BusyBox.apk fit or install BusyBox.zip ?
2) Can I leave my SupeSu ?

**Comment by yesimxev** [comment]
As long as I know, busybox will be v1.25 nethunter. So I never used any
different apk.
You can leave SuperSu


Dead3ch <notifications@github.com> ezt írta (időpont: 2018. okt. 19., Pén
23:30):

**Comment by Dead3ch** [comment]
If I install the latter for Nexus 6 Android 7.1.1, will your build work correctly, kernel-nethunter-shamu-nougat-2017.11-18-1618 ?

**Comment by yesimxev** [comment]
Yes that "old" kernel should work fine if it worked already
