### ISSUE TITLE
Chroot download fails

### ISSUE THREAD

**Issue by AidanBoyer** [offensive-security/kali-nethunter#1212]
### Device:
OnePlus 5T

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
8.1

### Built from repo (date and build command) or downloaded from website (links):
Magisk module KaliNethunter

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

OnePlus5T:/ # cat /proc/version
Linux version 4.4.78-perf+ (OnePlus@ubuntu-119) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Oct 10 20:11:37 CST 2018

## Issue:
I followed the installation instructions, up to the step "Click "Install Kali Chroot" - "Download latest". This gave the error attached.
![screenshot_20181017-122837](https://user-images.githubusercontent.com/8503478/47032741-15958500-d141-11e8-96e4-268aa8df0ef5.jpg)
![screenshot_20181017-123500](https://user-images.githubusercontent.com/8503478/47032742-15958500-d141-11e8-841e-0617a61000b3.jpg)

**Comment by yesimxev** [comment]
Please find the proper kernel for your device in case if you need wifi injection, hid, etc. 

Also I never used magisk, can you install kalifs before updating chroot in nh app?

**Comment by AidanBoyer** [comment]
Where would I find said proper kernel?

**Comment by yesimxev** [comment]
Looking at https://github.com/offensive-security/nethunter-devices/blob/master/kernels.txt

Seems like kernel for your OS version is not built yet (or not shared). However, you can port Nethunter to your device.

Download kernel source:

https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998 -b oneplus/QC8998_O_8.1

Using the toolchain from the kernels.txt above, you should build the proper kernel using these instructions

https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter

https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

I also recommed enabling rfcomm & rfcomm tty in the bluetooth menu which is not mentioned.

By the way for installing chroot, kernel is not needed yet.
My latest kalifs 
https://www.androidfilehost.com/?fid=1322778262904029164
Then you should start nethunter and initialize chroot then update

**Comment by 0E800** [comment]
The error you are receiving, I believe is due to you not having Busybox installed.
Install Busybox from Magisk modules. Then try re-running.

Not sure why you want to install via Magisk if it says wifi and keyboard attacks dont work.

More custom Magisk modules are needed. Best to use Supersu.

**Comment by yesimxev** [comment]
Built it - Generic NetHunter arm64 full without su
https://www.androidfilehost.com/?fid=11410932744536983517

**Comment by 0E800** [comment]
@yesimxev,

I had boot loops (not getting past Google logo) but so I just copied your kalifs-full and was able to include that updated chroot in my own custom Oreo ROM.
When I replaced the supersu.zip with my own it booted.

Thanks for your contribution.

**Comment by yesimxev** [comment]
Great! Is your kernel still the custom one?

**Comment by 0E800** [comment]
Yeah. Is there a kernel included in your zip?
Maybe that was it. But I did move your busybox and supersu to my build but could only boot when I removed the su.

BTW I'm using a Nexus 7 2013 flo. You save me lots of time having to apt install all the updates

**Comment by 0E800** [comment]
I forgot to mention that I compiled my own kernel prior so thats why hid keyboard and WiFi injection still worked .

**Comment by yesimxev** [comment]
No kernel but not sure if it reverts to factory kernel of the device. Did with mine so I reflashed my kernel after it

**Comment by heywoodlh** [comment]
Running into this same issue.

@yesimxev are there build instructions somewhere that I could use to build my own?

**Comment by yesimxev** [comment]
You can build fs if you download the installer
```
Git clone https://github.com/offensive-security/kali-nethunter.git
```
Replace the needed errors in the scripts as mentioned here:

https://github.com/offensive-security/kali-nethunter/issues/1196

Then build fs in nethunter-fs. When done, move the kalifs to the nethunter-installer then build installer. READMEs should be enough for instructions
