### ISSUE TITLE
OnePlus 6 Android 9 kernel

### ISSUE THREAD

**Issue by kimocoder** [offensive-security/kali-nethunter#1217]
### Device:
OnePlus 6 Android 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
9 Open Beta 5

## Notes:

NetHunter actually seems to work fine on OnePlus 6 with Android 9.
No issues so far.

But for full usages it should have a custom kernel with injection/hid patches and wifi drivers included. A perfect base would be the ElementalX kernel found here  

https://github.com/kimocoder/OnePlus6/tree/ElementalX-3.00

Will try get ut working when I got time.

**Comment by kimocoder** [comment]
![screenshot_20181020-172939](https://user-images.githubusercontent.com/4252297/47257455-4c93cf80-d48e-11e8-961c-3e67bfbdf23b.jpg)

**Comment by yesimxev** [comment]
Does the bluetooth service start for you?

**Comment by WEIWULUNLUN** [comment]
HID  ？？

**Comment by 0o0will0o0** [comment]
Any more information on the port yet?

**Comment by theoneandonly-vector** [comment]
> Any more information on the port yet?

here you go:
https://github.com/johanlike/Oneplus6-or-6T-Nethunter-Kernel

**Comment by 0o0will0o0** [comment]
Anything about it in English? The Google translation doesn't make sense to me. I know the A/B partition thing was complicated, so I really don't want to mess up on the instructions
