### ISSUE TITLE
Nethunter Smasung Galaxy S7

### ISSUE THREAD

**Issue by broesel233** [offensive-security/kali-nethunter#1218]
### Device:

SM-G930F

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

LineageOS 15.1 (Android 8.1)

## Issue:

Is there a Kali Nethunter Version for LineageOS 15.1 for the Samsung Galaxy S7?

**Comment by amzker** [comment]
Yes I Also On It
My device is S7 edge
And i am using Lineage 15.1 Unofficial

**Comment by broesel233** [comment]
Can you give me a link please?

**Comment by amzker** [comment]
https://forum.xda-developers.com/s7-edge/development/lineageos-15-android-8-0-0-s7-edge-t3710101

Download Unofficial File That Better Than Official

**Comment by broesel233** [comment]
I ment the Nethunter Link but i got it working now
