### ISSUE TITLE
Oreo OS Ready?

### ISSUE THREAD

**Issue by snoski3** [offensive-security/kali-nethunter#1219]
There has not been a nightly build for almost 1 year.  Is this project still active?  There are no builds for Oreo and Pie is almost ready to be released.

Thanks.

**Comment by kiranreddyrebel** [comment]
any kernel for oneplus 3 oreo ? plz.

**Comment by yesimxev** [comment]
My long comment on this issue should help you to compile kernel. Just find the needed kernel sources.

https://github.com/offensive-security/kali-nethunter/issues/1212
