### ISSUE TITLE
External Wifi card not detected Nexus 7 2013

### ISSUE THREAD

**Issue by byt3bl33d3r** [offensive-security/kali-nethunter#122]
Hi guys!
I just compiled from source and flashed my Nexus 7 2013.. everything works except for the external wireless card... I'm using the TP-LINK TL-WN722N 
dmesg says ```USB in low power mode``` don't know if that has anything to do with it

**Comment by byt3bl33d3r** [comment]
@binkybear sorry for the late reply... the terminal issue i mentioned seems to be related to the kernel you compiled without y-cable charging, when I reflashed with the usual kernel the problem goes away.. kinda weird though lol

**Comment by binkybear** [comment]
Yeah, this is a bit weird.  Let me recompile and reflash 4.4.4 and see if I can track down problem.

**Comment by tarrinho** [comment]
Hi @binkybear, I'm having the same issue that @byt3bl33d3r was having. Can you supply with the compiled kernel without the y-cable? 
Or this issue was already solved some other way?

Thanks

**Comment by binkybear** [comment]
The one that byt3bl33d3r has should be in the latest version of nethunter.  Did you use the latest one?  Is it having trouble recognizing device?

**Comment by tarrinho** [comment]
Yes, just downloaded 2 days ago from your site. And did a apt-get update + upgrade. And yes I'm having problems detecting the device.
If I do a lsusb it detects but in wifite it doesn't.

Btw, the external wifi works in a 2012 nexus 7.

**Comment by tarrinho** [comment]
Using wrong distro. I'm going to install PA and give it a go.

**Comment by tarrinho** [comment]
Looks like it has the same issue with the Alpha AWUS036H. I got it to work, but it looks like it was luck. I mean, some times it works, sometimes (most of them) it doesn't.
Any ideas?

**Comment by binkybear** [comment]
@tarrinho - I'm glad you got it to work, although I'm unsure why it would work sometimes and not others.  It seems like if it works it should stay working.

You could always try playing with usb settings: disable/enable mtp, disable/enable usb debugging.  I can't really say why it works sometimes and not though.

**Comment by 0E800** [comment]
Just want to comment some trouble-shooting techniques.

1: to verify y-cable is working, test with usb-mouse before testing with wifi adapter.
2: along with ifconfig and iwconfig, try using airmon-ng to detect your wifi adapter.
3:sometimes u need to unplug the device from y-cable, and re-plugin. (try using a mouse)

**Comment by ferby09** [comment]
I hope you can help me with my problems as well:

I just got nethunter on my Nexus 7 (2013) and I can't get my Edimax AC-1200 with RTL8812AU chipset to work with it.

I copied the text from a dmesg in terminal after connecting the adapter (couldn't find out how to get the log file):
`[   23.568145] ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   23.577972] wlan: [742:E :SME] sme_FTUpdateKey: Unhandled state=0
[   23.578491] wlan: [742:E :SME] sme_FTUpdateKey: Unhandled state=0
[   24.230468] wlan: [706:E :SME] sme_QosPmcDeviceStateUpdateInd: 7219: nothing to process in PMC state 6
[   24.509155] type=1400 audit(1424716319.480:14): avc:  denied  { getattr } for  pid=1347 comm="zygote" path="socket:[8192]" dev="sockfs" ino=8192 scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_stream_socket
[   24.509429] type=1400 audit(1424716319.480:15): avc:  denied  { getopt } for  pid=1347 comm="zygote" path="/dev/socket/zygote" scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_stream_socket
[   26.970153] type=1400 audit(1424716321.942:16): avc:  denied  { getattr } for  pid=1561 comm="android.vending" path="/data/app" dev="mmcblk0p30" ino=1556481 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=dir
[   27.415496] init: untracked pid 1621 exited
[   27.943603] SELinux: 512 avtab hash slots, 1354 rules.
[   27.944030] SELinux: 512 avtab hash slots, 1354 rules.
[   27.944030] SELinux:  1 users, 2 roles, 287 types, 1 bools, 1 sens, 1024 cats
[   27.944061] SELinux:  84 classes, 1354 rules
[   28.136505] type=1403 audit(1424716323.378:17): policy loaded auid=4294967295 ses=4294967295
[   28.141540] init: untracked pid 1624 exited
[   28.146972] EXT4-fs (mmcblk0p22): re-mounted. Opts: (null)
[   28.155853] EXT4-fs (mmcblk0p22): re-mounted. Opts: (null)
[   28.210388] EXT4-fs (mmcblk0p22): re-mounted. Opts: (null)
[   28.223602] EXT4-fs (mmcblk0p22): re-mounted. Opts: (null)
[   28.247222] SELinux: initialized (dev tmpfs, type tmpfs), uses transition SIDs
[   28.352600] init: untracked pid 1658 exited
[   28.656982] type=1400 audit(1424716323.898:18): avc:  denied  { getattr } for  pid=1734 comm="zygote" path="socket:[8192]" dev="sockfs" ino=8192 scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_stream_socket
[   28.657257] type=1400 audit(1424716323.898:19): avc:  denied  { getopt } for  pid=1734 comm="zygote" path="/dev/socket/zygote" scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_stream_socket
[   28.682983] type=1400 audit(1424716323.928:20): avc:  denied  { getattr } for  pid=1734 comm="earchbox:search" path="/data/app" dev="mmcblk0p30" ino=1556481 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=dir
[   34.132049] mipi_JDI_set_backlight: pwm disable
[   34.166717] mipi_JDI_lcd_off+
[   34.166717] mipi_JDI_lcd_off, JDI display off command+
[   34.282073] mipi_JDI_lcd_off, JDI display off command-
[   34.282073] mipi_JDI_lcd_off-
[   34.282104] mipi_dsi_panel_power+, on=0
[   34.373199] mipi_dsi_panel_power-
[   34.380554] EXT_COMMON: hdmi_common_wta_hpd: '1' (unchanged)
[   34.381072] request_suspend_state: sleep (0->3) at 34379080269 (2015-02-23 18:32:09.634552772 UTC)
[   34.381256] early_suspend: call handlers
[   34.381347] [ektf3k]:[elan] elan_ktf3k_ts_suspend: enter
[   34.381713] active wake lock PowerManagerService.WakeLocks
[   34.381866] active wake lock PowerManagerService.Display
[   34.381958] active wake lock msm_otg
[   34.382141] PM: Syncing filesystems...
[   34.407745] sync done.
[   35.052032] wlan0: no IPv6 routers present
[   35.262176] gpio_keys: Pressed KEY_POWER
[   35.269287] request_suspend_state: wakeup (3->0) at 35267294381 (2015-02-23 18:32:10.522766884 UTC)
[   35.269409] late_resume: call handlers
[   35.269531] [ektf3k]:[elan] elan_ktf3k_ts_resume: enter
[   35.270202] [ektf3k]:[elan] dump repsponse: 58
[   35.270324] late_resume: done
[   35.277465] mipi_dsi_panel_power+, on=1
[   35.352050] mipi_dsi_panel_power-
[   35.357696] mipi_JDI_lcd_on+
[   35.357696] mipi_JDI_lcd_on, JDI display on command+, command bl
[   35.452056] gpio_keys: Released KEY_POWER
[   35.502258] mipi_JDI_lcd_on, JDI display on command-
[   35.502258] mipi_JDI_lcd_on-
[   35.516448] EXT_COMMON: hdmi_common_wta_hpd: '1' (unchanged)
[   35.528991] mdp4_overlay_mdp_perf_upd mdp clk is changed [1] from 0 to 200000000
[   35.622070] mipi_JDI_set_backlight: pwm enable
[   36.253234] bcm2079x-i2c 0-0077: 10,90
[   38.594055] wlan: [706:E :HDD] hdd_tx_rx_pkt_cnt_stat_timer_handler: Disable split scan
[   40.387176] apr_tal: SMD_EVENT_OPEN
[   40.433258] setting pm_qos in msm_pcm_playback_copy with 1000
[   40.433349] done setting pm_qos in msm_pcm_playback_copy
[   41.281341] type=1400 audit(1424716336.521:21): avc:  denied  { execute_no_trans } for  pid=1944 comm="sh" path="/data/local/bin/busybox" dev="mmcblk0p30" ino=82475 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:system_data_file:s0 tclass=file
[   41.364929] type=1400 audit(1424716336.611:22): avc:  denied  { read write } for  pid=1913 comm="ffsec.nethunter" name="kgsl-3d0" dev="tmpfs" ino=7776 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=chr_file
[   41.365081] type=1400 audit(1424716336.611:23): avc:  denied  { open } for  pid=1913 comm="ffsec.nethunter" name="kgsl-3d0" dev="tmpfs" ino=7776 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=chr_file
[   41.365600] type=1400 audit(1424716336.611:24): avc:  denied  { ioctl } for  pid=1913 comm="ffsec.nethunter" path="/dev/kgsl-3d0" dev="tmpfs" ino=7776 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=chr_file
[   44.859924] type=1400 audit(1424716340.104:25): avc:  denied  { execute } for  pid=2066 comm="Thread-124" name="libestool2.so" dev="mmcblk0p30" ino=114714 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:app_data_file:s0 tclass=file
[   44.860198] type=1400 audit(1424716340.104:26): avc:  denied  { execute_no_trans } for  pid=2066 comm="Thread-124" path="/data/data/com.estrongs.android.pop/files/libestool2.so" dev="mmcblk0p30" ino=114714 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:app_data_file:s0 tclass=file
[   45.964538] type=1400 audit(1424716341.205:27): avc:  denied  { read } for  pid=2103 comm="su" name="/" dev="selinuxfs" ino=1 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:selinuxfs:s0 tclass=dir
[   45.964782] type=1400 audit(1424716341.205:28): avc:  denied  { search } for  pid=2103 comm="su" name="/" dev="selinuxfs" ino=1 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:selinuxfs:s0 tclass=dir
[   45.964965] type=1400 audit(1424716341.205:29): avc:  denied  { read } for  pid=2103 comm="su" name="enforce" dev="selinuxfs" ino=4 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:selinuxfs:s0 tclass=file
[   45.965148] type=1400 audit(1424716341.205:30): avc:  denied  { open } for  pid=2103 comm="su" name="enforce" dev="selinuxfs" ino=4 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:selinuxfs:s0 tclass=file
[   46.668640] init: untracked pid 2110 exited
[   46.888519] init: untracked pid 2114 exited
[   48.401000] updating pm_qos value to default msm_pcm_playback_close
[   48.401336] done updating pm_qos value to default msm_pcm_playback_close
[   48.427703] SLIM_CL: skip reconfig sequence
[   50.882171] usb 1-1: new high-speed USB device number 2 using msm_hsusb_host
[   51.040588] usb 1-1: New USB device found, idVendor=7392, idProduct=a822
[   51.040954] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   51.041320] usb 1-1: Product: 802.11n NIC
[   51.041534] usb 1-1: Manufacturer: Realtek
[   51.041748] usb 1-1: SerialNumber: 123456`

However my other adapter Edimax EW-7811Un (RTL8188CUS) is detected, but when using it with Wifite it neither recognises handshakes nor does it WPS pin attacks...
Other issues here on github with this problem didn't help yet.
Sometimes it stays at 0/0 and sometimes just the second digit counts up (ttl).

I appreciate every help I get! Thank you.

**Comment by mrhand1113** [comment]
Hey everyone I am using a Alfa awus036h and I'm running on net hunter lolipop 1.2 nexus 7 2013. I'm having problems as well with my card being detected. I also am having another error in wifite, SIOCSIFFLAGS: No such device. I'm guessing this also has to do with my card not being detected in the first place. I am fairly new to linux in general so any help would be nice. I'm trying to understand this "language" considering I want to go to college for tcp/ip and so on. Anyway thanks for the help, if you need any information from my end just message me. Just made an account to post this :D

**Comment by binkybear** [comment]
@mrhand1113 - Are you on lollipop or kitkat with your n7 2013?

**Comment by mrhand1113** [comment]
Lolipop

**Comment by binkybear** [comment]
@mrhand1113 - The error is possibly related to https://github.com/offensive-security/kali-nethunter/issues/198.  If you are feeling adventurous I just built a kernel and uploaded it.

I've built a new kernel if you are comfortable flashing in recovery.  Just hold down power + volume down when starting device and go into recovery.  Copy this zip file over: https://transfer.sh/18pA4k/kernel-kali-n72013.zip to your device and install.

If you do install I suggest making a backup of your "boot" in the backup section of recovery (uncheck everything else).  If kernel doesn't work then you can easily go to restore and click on the boot portion.

**Comment by mrhand1113** [comment]
@binkybear Ok I will test now thanks in advance

**Comment by mrhand1113** [comment]
@binkybear I just tried to flash the new kernel in TWRP v2.8.6 and after i swipe to confirm it progresses for about 2 seconds and randomly restarts back to the TWRP recovery's main menu.

**Comment by binkybear** [comment]
@mrhand1113 - I will look into this error today and get back to you.

**Comment by 0E800** [comment]
Might want to verify md5 to rule out corrupt download.

**Comment by mrhand1113** [comment]
@0E800 thanks for the advice, but ive already tried that. :/

**Comment by binkybear** [comment]
@mrhand1113 - 0E800 was suggesting that I provide the md5 to make sure it was the correct kernel (I think).
MD5 (kernel-kali-n72013.zip) = 70bba45795b5ef6c7f82a6e24d202ee2

**Comment by mrhand1113** [comment]
@binkybear @OE800 oh OK sorry about that. I thought OE800 was telling me to
check the option in TWRP that verifys the md5. :😁.

**Comment by 0E800** [comment]
I wasnt aware that TWRP did that. I was just trying to be helpful. I only have the 2012 version of N7 or else I would be a better help at troubleshooting. Good luck folks.

**Comment by binkybear** [comment]
@mrhand1113 - I just tried the kernel I posted for the N7 2013 running lollipop 5.1 and it flashed.  I didn't check the zip file signature check (just the defaults).  I'm running TWRP 2.8.6.

**Comment by mrhand1113** [comment]
Ok. I believe I am running on 5.0, will update and retry

**Comment by mrhand1113** [comment]
@binkybear would you happen to know where I can find this ota update I
downloaded? It told me it had to restart to install and afterwards it
booted into twrp, where in the directory is the downloaded ota updates
stored?

**Comment by mrhand1113** [comment]
@binkybear After updating to android lolipop 5.1.1 yesterday, I redownloaded net hunter and reflashed it along with the kernel you provided and I am still getting stuck with the no such device error. I tried running wifite before I flashed the modified kernel and I also had the same error. I was before on lolipop 5.0 but I now am updated to 5.1.1 and still stuck at the error.

**Comment by binkybear** [comment]
@mrhand113 - Can you get me a dmesg when you plug/unplug externel wifi/device. If you could upload it to pastebin or something similar that would be handy.  I don't need a whole dmesg, just from the time you plug in device.

**Comment by mrhand1113** [comment]
Sorry for my lack of knowledge, could you elaborate what you mean by a
"dmesg"?

**Comment by binkybear** [comment]
From terminal on device type:
```
dmesg > /sdcard/dmesglog.txt
```
It can provide error msgs.

**Comment by mrhand1113** [comment]
![screenshot_2015-05-09-09-46-48](https://cloud.githubusercontent.com/assets/12261618/7550447/b3d942d2-f630-11e4-9f94-17194dd46b00.png)

**Comment by midlo** [comment]
I am having similar issues as above.  While I am not seeing errors when I run Wifite, it does not recognize any WIFI adapters connected through the OTG cable.  I can bring them up and down through a terminal via ifconfig as wlan 0 or 1 (shows as wlan0 if connected before boot and wlan1 if connected after).  iwconfig will only recognize the internal wifi adapter, which I thought was interesting.  Airmon-ng does not see them either.  I have tried the following wifi adapters with multiple otg cables:

TL-WN821N
SMCWUSB-N2
WNA1000
AWUS036H

I'm no expert, but here's what I am running...I am running a Nexus 7 2013 WIFI with 5.02 operating system and 1.2 nethunter.  One thing that I should note is the root methods described on the website did not work. I was able to unlock the boot loader, but the final step would not root the phone.  TWRP would load up and show a bunch of mount errors.  It seems that several people with this device had the same issues and ultimately used a different image loaded through the ADB terminal to get it up before installing nethunter from a zip.  Could be nothing, or could be part of the problem with the wifi cards.  Also, the Nexus reboots when the wifi adapter is removed, regardless of it's ifconfig state.  Bringing it down (ifconfig wlan1 down) first does not matter.  I did notice that the android will bring it back up and connect to saved networks with it even after I brought it down with ifconfig.  

Nethunter is a great product.  Hopefully we'll figure out how to get wifi working with the Nexus 7 2013.  It's the perfect size and speed for this platform.  Looking forward to using it on wfi audits.

-midlo

**Comment by HTCnexus7** [comment]
HI

i have a nexus 7 2012 have 
Kali linux nethunter 1.21 nakasi kitkat
modified boot nakasi 4.4.4_KTU84P.img
TWRP 2.8.6.0 grouper
Factory package nakasi ktu84p

But i can not start up wlan1  its not recognized in kalihunter 
using tplin722n checked otg checked usb stick
any one can help

**Comment by binkybear** [comment]
@HTCnexus7 - Can you go into settings > about and tell me the name of the kernel version. (If it says google that a problem)

**Comment by HTCnexus7** [comment]
3.1.10-gle42d16
android-build@vpbs1.mtv.corp.google.com #1

**Comment by binkybear** [comment]
Thats google's kernel so you should try reflashing the kernel.  You can download an older/working kernel here: http://photonicgeek.me/NetHunter/Kernels/grouper-tilapia/Kernel-groupertilapia-kitkat-12042014.zip

Go into recovery and just install the zip file and it should be fine.

Also, i'm closing this issue for the 2013 wifi not working as it seems to have gotten out of hand/scope.

**Comment by mental-boy** [comment]
I flashed pwnie express and I face same problem can you reupload your kernel because all old links are dead

**Comment by baheejtp123** [comment]
i unpacked boot.img now where  to edit to detect external usb wifi adapter for nethunter.
im using galaxy s7 edge  (sm-g935f) note 8 port.plz help @binkybear 
i tried   SuperKernel-TW70-s8port ,  but not detecting  twrp recovery showing invalid zip format! error...

**Comment by sezusatish** [comment]
hi  
i am using Device : Nexus 7 2013 (flo) WIFI (cm13)
 i try to building own nethunter base on this linke
https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter
Including the kernel full
using this commend :
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d flocm -m -su --rootfs full
 and able to make zip file and installed and all is working good
but external wifi  card TP-Link WN722N v1 is detected by NetHunter and working good for  max 120 min  only if I put device in sleep mode, next time onwards external WiFi  card is  not detected i am using the same card in kali os and i working good even i tryed with alfa card also use otg pen driver and mouse also working good , i tryed to check in lsusb it now shown or iwconfig not able to see any attached  max people are having issues, can any one  assist to find any solutions is it kernel issues or this nexus device is not support for external wifi card I check /etc/system/firmware having dump of firmware
