### ISSUE TITLE
Need Nethhunter for smasung sm n9005 

### ISSUE THREAD

**Issue by mahatherjo** [offensive-security/kali-nethunter#1220]
### Device:

Samsung note 3 SM N 9005

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oreo 

### Built from repo (date and build command) or downloaded from website (links):

Date May 6 2018 Lineage OS 15.1

## Issue:
Can anyone provide link to download Nethhunter for smasung sm n9005 for lineage 15.1 Oreo

**Comment by yesimxev** [comment]
Latest kalifs of mine found here
https://github.com/offensive-security/kali-nethunter/issues/1193

My long comment should help with kernel build too
https://github.com/offensive-security/kali-nethunter/issues/1212

**Comment by mahatherjo** [comment]
@yesimxev  Thanks for your post in #1193 found three types of kernel armhf , arm64 and i386 .. Which one I need to use for Sm N9005 Hlte Samsung note 3 phone

**Comment by yesimxev** [comment]
Please use google. Armhf
Architecture - Chipset	32bit - Qualcomm Snapdragon 800 MSM8974
https://www.phonemore.com/samsung-galaxy-note-3-lte-sm-n9005-32gb/specs/1103
