### ISSUE TITLE
airodump not working after usage of hcxpcaptool

### ISSUE THREAD

**Issue by pixeldublu** [offensive-security/kali-nethunter#1221]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Prebuilt cm14.1 from Binkybear ( https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e )
+ dist upgrade
+ remove print of nexmon to make latest wifite work

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-ElementalX-N5-7.09 (root@AutinDroid) (gcc version 4.8)

## Issue:
Latest wifite seems to use hcxpcaptool. After this the airodump does not find targets. Tried to run airodump manually. I have to kill the terminal and start again ( running monstart-nh again )

Anyone else had this issue ? Any ideas ?

Thank you!

**Comment by pixeldublu** [comment]
` [32m  .     [37m[2m     [0m[32m     .    [0m
 [32m.´  ·  .[37m[2m     [0m[32m.  ·  `.  [32mwifite [2m2.2.5[0m
 [32m:  :  : [37m[2m (¯) [0m[32m :  :  :  [0m[2mautomated wireless auditor[0m
 [32m`.  ·  `[37m[2m /¯\ [0m[32m´  ·  .´  [36m[2mhttps://github.com/derv82/wifite2[0m
 [32m  `     [37m[2m/¯¯¯\[0m[32m     ´    [0m

 [0m[2m[[0m[32m+[0m[2m][0m [36moption:[0m using wireless interface [32mwlan0[0m
 [0m[2m[[0m[32m+[0m[2m][0m [36moption:[0m ([32mpillage[0m) attack all targets after [32m10[0ms
 [0m[2m[[0m[32m+[0m[2m][0m [36moption:[0m verbosity level [32m3[0m



                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m Scanning. Found [32m0[0m target(s), [32m0[0m client(s). [33mCtrl+C[0m when ready 
[0m[2m   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT
   ---  -------------------------  ---  ----  -----  ----  ------[0m

                                                                                
   [32m  1  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 58db  [33m  no  [32m  11[0m

                                                                                
   [32m  2  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 58db  [33m  no         [0m

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m Scanning. Found [32m2[0m target(s), [32m11[0m client(s). [33mCtrl+C[0m when ready 
[0m[2m   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT
   ---  -------------------------  ---  ----  -----  ----  ------[0m

                                                                                
   [32m  1  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 59db  [33m  no         [0m

                                                                                
   [32m  2  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 58db  [33m  no  [32m  14[0m

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m Scanning. Found [32m2[0m target(s), [32m14[0m client(s). [33mCtrl+C[0m when ready 
[0m[2m   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT
   ---  -------------------------  ---  ----  -----  ----  ------[0m

                                                                                
   [32m  1  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 57db  [33m  no  [32m  16[0m

                                                                                
   [32m  2  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 56db  [33m  no         [0m

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m Scanning. Found [32m2[0m target(s), [32m16[0m client(s). [33mCtrl+C[0m when ready 
[0m[2m   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT
   ---  -------------------------  ---  ----  -----  ----  ------[0m

                                                                                
   [32m  1  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 56db  [33m  no  [32m  17[0m

                                                                                
   [32m  2  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 55db  [33m  no         [0m

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m Scanning. Found [32m2[0m target(s), [32m17[0m client(s). [33mCtrl+C[0m when ready 
[0m[2m   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT
   ---  -------------------------  ---  ----  -----  ----  ------[0m

                                                                                
   [32m  1  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 56db  [33m  no  [32m  17[0m

                                                                                
   [32m  2  [36wifiname ...[35m   [32m  8  [33m WPA  [32m 55db  [33m  no         [0m

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m Scanning. Found [32m2[0m target(s), [32m17[0m client(s). [33mCtrl+C[0m when ready 
 [0m[2m[[0m[32m+[0m[2m][0m ([32m1[0m/[32m2[0m) Starting attacks against [36m00:11:22:33:44:55[0m ([36wifiname 2.4Ghz[0m)

 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m29s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m28s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m27s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m26s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m25s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m24s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m23s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m22s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m21s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m20s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m19s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m18s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m17s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m16s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m15s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m13s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m12s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m11s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m10s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m9s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m8s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m7s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m6s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m5s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m4s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m3s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m2s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m1s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m0s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mPMKID [36mCAPTURE[0m: [31mFailed[33m to capture PMKID
 

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname 2.4Ghz[0m[0m ([36m56db[0m) [32mWPA [36mHandshake capture[0m: Waiting for target to appear... 
 [33m[[31m![33m][0m [31mError: [33mTarget did not appear after 60 seconds, stopping

 [33m[[31m![33m][0m [33mFull stack trace below

 [33m[[31m![33m][0m    Traceback (most recent call last):
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/attack/all.py", line 86, in attack_single
 [33m[[31m![33m][0m [36m       result = attack.run()
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/attack/wpa.py", line 42, in run
 [33m[[31m![33m][0m [36m       handshake = self.capture_handshake()
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/attack/wpa.py", line 94, in capture_handshake
 [33m[[31m![33m][0m [36m       airodump_target = self.wait_for_target(airodump)
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/model/attack.py", line 24, in wait_for_target
 [33m[[31m![33m][0m [36m       raise Exception('Target did not appear after %d seconds, stopping' % Attack.target_wait)
 [33m[[31m![33m][0m [36m [31mException: [33mTarget did not appear after 60 seconds, stopping

 [0m[2m[[0m[32m+[0m[2m][0m ([32m2[0m/[32m2[0m) Starting attacks against [36m00:11:22:33:44:55[0m ([36wifiname Guest[0m)

 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m29s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m28s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m27s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m26s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m25s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m24s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m23s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m22s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m21s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m20s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m19s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m18s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m17s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m16s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m14s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m13s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m12s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m11s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m10s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m9s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m8s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m7s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m6s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m5s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m4s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m3s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m2s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m1s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: Waiting for PMKID ([36m0s[0m) 
 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mPMKID [36mCAPTURE[0m: [31mFailed[33m to capture PMKID
 

                                                                                

 [0m[2m[[0m[32m+[0m[2m][0m [32m[36wifiname Guest[0m[0m ([36m55db[0m) [32mWPA [36mHandshake capture[0m: Waiting for target to appear... 
 [33m[[31m![33m][0m [31mError: [33mTarget did not appear after 60 seconds, stopping

 [33m[[31m![33m][0m [33mFull stack trace below

 [33m[[31m![33m][0m    Traceback (most recent call last):
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/attack/all.py", line 86, in attack_single
 [33m[[31m![33m][0m [36m       result = attack.run()
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/attack/wpa.py", line 42, in run
 [33m[[31m![33m][0m [36m       handshake = self.capture_handshake()
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/attack/wpa.py", line 94, in capture_handshake
 [33m[[31m![33m][0m [36m       airodump_target = self.wait_for_target(airodump)
 [33m[[31m![33m][0m [36m   [0mFile "/usr/local/lib/python2.7/dist-packages/wifite/model/attack.py", line 24, in wait_for_target
 [33m[[31m![33m][0m [36m       raise Exception('Target did not appear after %d seconds, stopping' % Attack.target_wait)
 [33m[[31m![33m][0m [36m [31mException: [33mTarget did not appear after 60 seconds, stopping
 [0m[2m[[0m[32m+[0m[2m][0m Finished attacking [36m2[0m target(s), exiting`

**Comment by yesimxev** [comment]
Do you have the proper kernel installed from build.nethunter.com ?
Eg. https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-hammerhead-nougat-2017.11-18-1618.zip
Or
https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-hammerheadcm-nougat-2017.11-18-1618.zip
Maybe not a kernel issue, if injection works with wifite before triggering the error.

P.S.: Üdv!

**Comment by pixeldublu** [comment]
I have the hammerheadmon kernel flashed.
Not sure if injection works... did not have the chance to test but monitor mode works ok.

Btw: what os/build/kernel you guys recommend ?

**Comment by yesimxev** [comment]
I don't have a Nexus but, you can try to install a latest chroot from one of these, should be ok to install on top of current ROM, but remove chroot using the nethunter app, then TWRP install:
https://github.com/offensive-security/kali-nethunter/issues/1193

**Comment by pixeldublu** [comment]
also another question... things work after dist upgrade ?

Thanks!

**Comment by pixeldublu** [comment]
I remember now why i use Binkybears prebuilt. :)

Flashing latest built chroot from sources has alot of issues, ( and the same with the ones from #1193 ) like nethunter terminal not working ( simply says stopped and exists ). 

Going to see if i can find a solution for the nethunter terminal.

**Comment by pixeldublu** [comment]
Reinstalling from data/app the .apk fixed the issue with terminal

**Comment by pixeldublu** [comment]
airodump-ng does not see any ap/client... so not working. (Using chroot from #1193)

applied fix https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e#gistcomment-2355555

**Comment by yesimxev** [comment]
Yes, reinstalling the chroot over "not clean rom" does not reinstall apks successfully for me too. Do you have firmware-realtek (or the needed wireless driver) installed (or nethunter-wireless metapackage)? Airodump-ng works like a charm for me

**Comment by pixeldublu** [comment]
Actually i do it over clean rom. Wipe everything + lineageos14.1 nightly + su + chroot with kernel.
source monstart-nh and then wifite or airodump-ng ... dead... no error but also no ap/clients

**Comment by yesimxev** [comment]
Ah sorry. How about airmon-ng check kill && airmon-ng start wlan1 instead of monstart?

**Comment by pixeldublu** [comment]
Starting with airmon never worked.

**Comment by pixeldublu** [comment]
Tried fresh install, still no luck. Also tried to install hammerheadcm kernel and install nexmon manually but its worse. :(

Anyone can share a mini guide how to install latest nexmon or how to rebuild hammerheadmon image ( its 2 years old ) ?

**Comment by pixeldublu** [comment]
returning... does reaver work for you ? I am getting pcap handle error

**Comment by mirkorobocop** [comment]
I have the same problem, but doing it in this way: https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e#gistcomment-2355555
I have a working inject mode that works with most scripts like wifite but with the hcxdumptool installed, the wifite tool stops working - it stops after an unsuccessful attempt to obtain a PMKID hash and then  when attempts to intercept a handshake it's end with the status "Waiting for target to appear ...". Without hcxdumptool, the whole process is going well and the handshake is captured. 
@pixeldublu Did you find a way to fix it? compiling in this way:
`gcc -B ../../patches/include/ fakeioctl.c ../libnexio/libnexio.c -ldl -shared -o libfakeioctl_kali.so`
makes the airodump and other tools completely not work

**Comment by pixeldublu** [comment]
airodump works. But other things not really...
