### ISSUE TITLE
#CRASH# g955f nx17 kernel 

### ISSUE THREAD

**Issue by FUCKS3CURITY** [offensive-security/kali-nethunter#1223]

**Comment by yesimxev** [comment]
Which kalifs did you install? Rooted the phone? Kernel? Provide more details please

**Comment by FUCKS3CURITY** [comment]
i used the noxxkernel nx17 i used the installer that doesnt install kernel which i found on this repo and yes the phone is rooted with the latest busybox pro

**Comment by FUCKS3CURITY** [comment]
would it be the kernel that causes this or the rom?
BTW the rom is renovate ice oreo rom
