### ISSUE TITLE
i9100 bootlop

### ISSUE THREAD

**Issue by goldchester** [offensive-security/kali-nethunter#1225]
Device:Samsung Galaxy S2

OS version (KitKat/Lollipop/Marshmallow/Nougat):Nougat

Built from repo (date and build command) or downloaded from website (links):ddd

Output of `cat /proc/version` in adb shell or NetHunter Terminal:donthave

Issue:Instal KaliNethunter to my i9100 and get bootloop

**Comment by amzker** [comment]
Now flash Custom ROM

**Comment by yesimxev** [comment]
Yes, if it's not uploaded anywhere for your system, find my long "instruction" here to build:
https://github.com/offensive-security/kali-nethunter/issues/1212

**Comment by goldchester** [comment]
flashed Lineage 14.1

**Comment by goldchester** [comment]
> #1212

if i do it, app terminal is shuting down

**Comment by goldchester** [comment]
i9100 dont have magisk

**Comment by yesimxev** [comment]
Ignore that part of the issue, I meant only these instructions

Looking at https://github.com/offensive-security/nethunter-devices/blob/master/kernels.txt

Seems like kernel for your OS version is not built yet (or not shared). However, you can port Nethunter to your device.

Download kernel source (find the one you need for S2, i just googled the first)
git clone git://github.com/GalaxySII/samsung-kernel-galaxysii.git

Using the toolchain from the kernels.txt above, you should build the proper kernel using these instructions

https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter

https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

I also recommed enabling rfcomm & rfcomm tty in the bluetooth menu which is not mentioned.

**Comment by goldchester** [comment]
:fuckmybrainz:

**Comment by Re4son** [comment]
Please reopen if you need any more information

> > #1212
> 
> if i do it, app terminal is shuting down

Fixed in the latest nethunter-app build
