### ISSUE TITLE
External wifi adapters for Nexus 6p

### ISSUE THREAD

**Issue by BroskaCZ** [offensive-security/kali-nethunter#1226]
### Device:
Huawei Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Android 7.1.1 Nougat

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.73-nethunter-angler-2.0 (jc@arkyn) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Wed Sep 6 16:16:05 EDT 2017

## Issue:
Hey, can you recommend me some WIFI external adapters for my device which supports airxxxx-ng commands and my device can detect them?

**Comment by yesimxev** [comment]
Should be fine with these
https://github.com/offensive-security/kali-nethunter/wiki/Wireless-Cards
I am happy with Alfa Networks AWUS036NEH, although cheap chinese works too, I guess it will die sooner, also didn't test AP mode yet
https://www.ebay.co.uk/itm/292743302439

**Comment by BroskaCZ** [comment]
Thanks for your answer

**Comment by ghanimlk** [comment]
The tp link tl-wn722n v1, is the best adapter for nethunter cheap and convenient, but only v1 support monitor mode and pocket injection the v2 and v3 doesn't.
