### ISSUE TITLE
Force redownloading

### ISSUE THREAD

**Issue by bigbiz123** [offensive-security/kali-nethunter#1227]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
nougat

### Built from repo (date and build command) or downloaded from website (links):

--forcedown, -f 

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

not even made zip yet!!

## Issue: --forcedown, -f       Force redownloading
command what is it do?
do i need it or not??

**Comment by yesimxev** [comment]
What would you force redownload? nethunter app, kernel, chroot? Please provide more info about the situation
