### ISSUE TITLE
How much storage will rest on Nexus 5 16gb

### ISSUE THREAD

**Issue by Tutozz** [offensive-security/kali-nethunter#1228]
Hello, i Will buy a nexus 5 with 16gb but I've read the forums and somes says that on 32gb after install NetHunter that rest only 11gb of stockage.
So, I have a question how many GB will rest on a 16gb model after install
Thanks

**Comment by Tutozz** [comment]
Anybody ?

**Comment by yesimxev** [comment]
Nethunter wouldn't take up that much space, it's mostly taken by the android system. A full kali nethunter fs should be around 1,5gb (after install)

**Comment by Tutozz** [comment]
Thanks for your answer !!!
