### ISSUE TITLE
Nethunter app crashing!!

### ISSUE THREAD

**Issue by Mechonas** [offensive-security/kali-nethunter#1232]
### Device:
S8+ ( SM-G955F)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
8.0.0 Rom-renovate ice 13.4 Kernel - noxxx

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

dream2lte:/ $  cat /proc/version
Linux version 4.4.13-NX-R16 (Noxxx) (gcc version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701] (Linaro GCC 7.3-2018.05) ) #1 SMP PREEMPT Mon Aug 27 17:52:43 CEST 2018
dream2lte:/ $

**Comment by Re4son** [comment]
Looks like the nethunter app installed by the magisk module is outdated.
Use this one instead:
[https://github.com/offensive-security/nethunter-app/releases](https://github.com/offensive-security/nethunter-app/releases)
