### ISSUE TITLE
Add support tp link wn722n v2 it support monitor mode in kali

### ISSUE THREAD

**Issue by Ccracker22** [offensive-security/kali-nethunter#1241]
It support monitor mode in what i search

**Comment by nhunter1093** [comment]
In what do you mean?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Re4son** [comment]
It's being worked on.
The latest drivers with monitor and injection support can be found here:
[https://github.com/aircrack-ng/rtl8188eus](https://github.com/aircrack-ng/rtl8188eus)
