### ISSUE TITLE
Why does not my Oneplus one 64gb turn on when i used apt-get dist-upgrade command?

### ISSUE THREAD

**Issue by Lunpopo** [offensive-security/kali-nethunter#1242]
### Device:
Oneplus one

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
the OS file is nethunter-oneplus1-lollipop-3.0.zip

### Built from repo (date and build command) or downloaded from website (links):
Built this OS follow below:
1. Taking the TWRP Recovery 3.2.1.0 into Oneplus one 64gb device
2. Wiping data and cache
3. Installing nethunter-oneplus1-lollipop-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
cat /proc/version from Recovery terminal is following below:
Linux version 3.4.112-cyanogenmod-gd1ef0d2(jenkins@0fd045ccc84f)(gcc version 4.9.x-google20140827(prerelease)(GCC)) #1 SMP PREEMPT S at Dec 9 02:03:06 UTC 2017

## Issue:
When i finished apt-get dist-upgrade command my Oneplus one device cannot turn on.
What should i do? 
Please give me some help or suggestion, very thanks for you !!!!

**Comment by yesimxev** [comment]
Please use the instructions from nethunter-LRT (on github) + you can use my latest kalifs to add, and kernel found in my repository yo flash after, they are kind of latest. Strictly CM13 so google a signed ROM for the base system
