### ISSUE TITLE
Add support galaxy s4 please

### ISSUE THREAD

**Issue by Ccracker22** [offensive-security/kali-nethunter#1243]
Add support i9515 please

**Comment by Ccracker22** [comment]
Can you give me nethunter link for i9515

**Comment by 5un53tt3r** [comment]
currently running nethunter on s4 m919...fully functional, works great.

**Comment by Re4son** [comment]
https://forum.xda-developers.com/galaxy-s4/i9500-develop/finding-rom-developer-nethunter-gt-i9500-t3647311
