### ISSUE TITLE
[Nexus 10] HID Attack / Keyboard not working

### ISSUE THREAD

**Issue by 0x42424242** [offensive-security/kali-nethunter#125]
**Device:** Nexus 10
**Uname Output:** Linux kali 3.4.39-ga66e222 #1 SMP PREEMPT Mon Sep 29 15:57:24 EDT 2014 arv71 GNU/Linux
**Install Method:** Windows Nethunter Installer v1.0.9 with Kali-Nethunter v1.02 (Mantaray)

**Symptoms:** 
No HID based functions work on the tablet. This includes the "USB Keyboard" which responds with the image attached, or more importantly any HID based attacks. 

Examining the /dev/ folder there is no hidg0 or hidg1 listing created. 

**Attempted Remediation's:**
I've attempted installing all released version of Net Hunter (i.e. 1.0.0 / 1.0.1) but at this point no solution has been found. 

**Diagnostics:**
Please find the dmesg log here http://pastebin.com/HjfcsDVr and a capture of what displays when attempting to access the "USB Keyboard". The dmesg log show's trying to access the USB Keyboard function. 

![nethunter](https://cloud.githubusercontent.com/assets/10124857/5352742/d453a2aa-7fc0-11e4-931e-d895e658a531.jpg)

**Comment by AnarchyAngel** [comment]
I am having the same issue, kinda. I dont get an error message but the HID attack just never works "i hit execute attack" and nothing happens. I looked in /dev and i dont see the hidg0 it hidg1 file, is that why the HID attack is not working? When i opened the zip in photonicgeek/manta i dont see them files in there either.

**Comment by binkybear** [comment]
@AnarchyAngel - The /dev/hidg0 is generated on boot so you wouldn't see the files in there.  Could you verify that the kernel flashed (in settings > about) and also which ROM you are using (if you are using a different one).

**Comment by AnarchyAngel** [comment]
##MORE INFO
The hidg files are there only when i have usb debugging on. When I try to use the USB keyboard app, what ever box i touch first stays lit and nothing happens.

##REQUESTED INFO
@binkybear 
Kernel ver is 3.1.10-kangaroo root@fringe #1 Sat Jan 3 11:44:31 EST 2015. I am using the rom that comes with the NetHunter installer 1.1.6 by OffSec.

Thanks!

**Comment by binkybear** [comment]
@AnarchyAngel - Thanks, so it sounds like the keyboard is working then, just when usb debugging is on?  You have the right kernel and ROM.  Have you tried enabling and disabling mtp to see if that also makes a difference?

**Comment by AnarchyAngel** [comment]
MTP is currently off, I will turn it on and give it a try. Thank you.

**Comment by AnarchyAngel** [comment]
That was it! As soon as I enabled MTP it started working. Thank you very much @binkybear

**Comment by kokos300** [comment]
Hi ! 

I want to bypass the Mcafee DLP end point security for usb on my pc. The HID keyboard attack suppose to make the usb drive to present itself as keyboard device and therefore bypass the dlp security as my other peripherals do (keyboard and mouse). When i connect my nexus 5 on the pc it begings downlading and installing drivers for nexus 5, HID and MTP(media device) and automatically blocked by the DLP solution.

Is there a way that i can turn off the drivers for nexus 5 and MTP in order to avoid notifying the DLP ?? 
I have manage to find how to disable the MTP and now the drivers are not downloading for it. 

But i still can observe the nexus 5 drivers and I am getting blocked again and again...

Can you please provide me with a solution to this problem ??

Regards..

**Comment by akrolla** [comment]
Nexus 5 6.01 and 5.1.1 fresh installs it doeant work in either

**Comment by test123456676** [comment]
akrolla

did you find a fix yet

**Comment by akrolla** [comment]
no I will look into it more I haven't had that problem.

**Comment by akrolla** [comment]
Did you try reinstalling the kernel ?

**Comment by akrolla** [comment]
I had the usb keyboard app say that when when it didn't complete the kernel install and reverted back.

**Comment by akrolla** [comment]
Try the anykernel that's included with the nethunter zip install it separately then install nethunter after it helps ensure the kernel is changed to remove the protections selinux provides.

**Comment by akrolla** [comment]
Any news did that help?

**Comment by ashmitraj** [comment]
chmod: /dev/hidg0: No such file or directory
