### ISSUE TITLE
Kali Nethunter Terminal not working

### ISSUE THREAD

**Issue by HyperThred** [offensive-security/kali-nethunter#1269]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Pie

## Issue: I am very new to this. So I apologize if this has been covered. In fact the only thread I could find on it is closed already. I followed the thoughts of some other users suggestions but they didn't work. I tried a different version of NH Term and that didn't work either.
I installed Nethunter on my device but when I open the Nethunter terminal and choose Kali it closes the terminal. If I start it and choose Android or Androidsu and by entering su bootkali it still does not work. I can't find the root@kali: /#

**Comment by Re4son** [comment]
Could you please try the latest version of the nethunter app and let us know how you go with that?
[https://github.com/offensive-security/nethunter-app/releases/tag/v2019.1](https://github.com/offensive-security/nethunter-app/releases/tag/v2019.1)
Just install it, execute it once and reboot. The terminal should work after the reboot.

**Comment by HyperThred** [comment]
AHA! It worked! I'm very sorry, I thought I had the latest version. Is that link the link I find the newest releases?

**Comment by yesimxev** [comment]
What is your output of 

`cat /proc/version`

 in adb shell or NetHunter Terminal as of now?

**Comment by BZBaXraM** [comment]
Oneplus one cm12.1?😂😂😂😂😂

**Comment by yesimxev** [comment]
CM12.1 for OPO was ok, but OPO installer for Pixel 2XL?

**Comment by BZBaXraM** [comment]
You can build your own Nethunter Kernel + Nethunter installer.

**Comment by HyperThred** [comment]
> You can build your own Nethunter Kernel + Nethunter installer.

Thank you for the useful information and for laughing at me. It's like I'm back in grade school.

**Comment by HyperThred** [comment]
> CM12.1 for OPO was ok, but OPO installer for Pixel 2XL?

I'm not sure what the big deal is. It worked. The only thing I had to change was the .apk for kali nethunter. I think this will be the last time I ask for help in github.

**Comment by yesimxev** [comment]
I was just assumed/interested to ask if it installed the OPO kernel onto your Pixel 2XL
