### ISSUE TITLE
Unfortunately setting (or many other services ) has stopped.

### ISSUE THREAD

**Issue by noxeterna666** [offensive-security/kali-nethunter#1273]
### Device:
Nexus 5 Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmellow 

### Built from repo (date and build command) or downloaded from website (links):
https://images.offensive-security.com/nethunter-release/nethunter-mako-lollipop-3.0.zip
https://www.offensive-security.com/kali-linux-nethunter-download/

## Issue:
Hello,

So doing a clean install of Nethunter through Twrp. Didn't delete cache/dalvik after install was done (using an old version of twrp. Anyways, rebooting in the system and launching the phone is fine but as soon as i unlock the phone all these services start failing - phone, messaging, setting, keychain etc...If i try entering settings app it just fails and says ''unfortunately settings has stopped working.'' Is there any way to fix this ? What am I doing wrong ?

Thank you for your time.

**Comment by Re4son** [comment]
Looks like you flashed the nethunter build for lollipop on a phone running marshmellow. If that wasn't a typo then try flashing this image:
https://images.offensive-security.com/nethunter-release/nethunter-hammerhead-marshmallow-3.0.zip

**Comment by noxeterna666** [comment]
Oh, yes that was a typo that is the one i installed. (Marshmellow) I tried the lolipop once and it wouldn't even boot. :/

**Comment by noxeterna666** [comment]
Yeah even if i flash the marshmellow build on the phone all my services suddenly stop and i can't make use of them. Settings are gone so i can't access wifi options either. Maybe ill check if i can try an unstable build and see if that fixes it...otherwise i can't do much with the phone at all right now. Let me know if you have any ideas. Perhaps im missing something. Only thing i can think off is im using a really old twrp version. Other than that i don't know.

**Comment by Re4son** [comment]
I'm not sure, sorry; I don't have aNexus 5 to reproduce the problem.
Why don't you join this discussion:
[https://github.com/offensive-security/kali-nethunter/issues/1276](https://github.com/offensive-security/kali-nethunter/issues/1276)

They seem to have found the ideal workflow to get it to work.
Please reopen this issue if the other threat doesn't help
