### ISSUE TITLE
Question kalifs-minimal and HID Duckhunter

### ISSUE THREAD

**Issue by Svirusx** [offensive-security/kali-nethunter#1277]
### Device:
Samsung Galaxy s7

## Question:
Hey,
I have question about kalifs-minimal with HID duckhunter.
HID duckhunter works fine  with kalifs-full but i want save space. I want to have kalifs-minimal but duckhunter doesn't work on kali-minimal.  Which packages are needed from kali-linux-nethunter to could use duckhunter with kali-minimal??
Of course after apt-get install kali-linux-nethunter HID duckhunter works.. but now its kalifs-full...

**Comment by Re4son** [comment]
I dont' have a definite list but below are the steps I'd take to track down the absolute minimum:
- start with a kali-minimal fs
- install nethunter-utils, python-pip, python-setuptools
- try DuckHunter and add one package at a time that you see fit from this list:
[http://git.kali.org/gitweb/?p=packages/kali-meta.git;a=blob;f=debian/control;h=5572311a2a1042b4f0f80d584f6c91540285913b;hb=refs/heads/kali/master#l889](http://git.kali.org/gitweb/?p=packages/kali-meta.git;a=blob;f=debian/control;h=5572311a2a1042b4f0f80d584f6c91540285913b;hb=refs/heads/kali/master#l889)

Hope that helps and please let us know how you go

**Comment by Svirusx** [comment]
After long time of tests i found it :D 
Only those two packages are needed. (and another XX packages to those two could working... xD)
apt-get install python-setuptools sqlite3  and this is 26mb only 

So ultra lite nethunter in data partition and kali-linux-all on microsd :P
