### ISSUE TITLE
/system is not mounted in chroot

### ISSUE THREAD

**Issue by yesimxev** [offensive-security/kali-nethunter#1278]
### Device:
zerolte (Galaxy S6 edge)
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lineage14.1 Nougat
### Built from repo (date and build command) or downloaded from website (links):
nethunter-installer, own kernel
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.61-yesimxev-g90f94721dfb-dirty (root@kali) (gcc version 4.9 20140514 (prerelease) (GCC) ) #2 SMP PREEMPT Thu Mar 7 14:07:44 CST 2019
## Issue:
/system is not mounted in chroot, whereas I can see it in TWRP
How to mount? Couldn't google it

P.S it is fine on my OPO, and it was fine on this phone as well when I installed NH, nothing major modified since

**Comment by yesimxev** [comment]
![Screenshot_2019-03-29-07-26-07](https://user-images.githubusercontent.com/23633302/55232761-c6db3380-5226-11e9-9abc-fe1638adc019.png)
![Screenshot_20190329-132839](https://user-images.githubusercontent.com/23633302/55232766-cb075100-5226-11e9-9ced-dec9f72bf37f.png)

**Comment by yesimxev** [comment]
The latest (2019.02) NH apk causes this. Reinstalled 2019.1 and rebooted with proper mount @Re4son
![Screenshot_20190329-143424](https://user-images.githubusercontent.com/23633302/55236237-cdba7400-522f-11e9-8402-d59b8ed6f845.png)

**Comment by Re4son** [comment]
Just to make sure, this one works:
[https://github.com/offensive-security/nethunter-app/releases/tag/v2019.1](https://github.com/offensive-security/nethunter-app/releases/tag/v2019.1)
but this one doesn't:
[https://github.com/offensive-security/nethunter-app/releases/tag/v2019.2-rc1](https://github.com/offensive-security/nethunter-app/releases/tag/v2019.2-rc1)
correct?

**Comment by yesimxev** [comment]
Correct

**Comment by Re4son** [comment]
@kimocoder : `$busybox mount -r -o bind /system $mnt/system` seems to have slipped through the nets during the update

**Comment by Re4son** [comment]
Fixed in 2019.2-rc3
https://github.com/offensive-security/nethunter-app/releases/tag/2019.2-rc3
