### ISSUE TITLE
Linux headers error in nethunter

### ISSUE THREAD

**Issue by shakim24** [offensive-security/kali-nethunter#1279]
### Device:
Samsung Galaxy s5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Magisk Module

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
N/A

## Issue:
I'm running lineageOS 14.1 along with nethunter which I installed through Magisk Module. On top of that I installed the nethunter kernel for my device, klte. So I recently purchased a Panda wifi adapter, PAU0A, and it uses the MediaTek mt7610u chipset. When I try to build the driver in nethunter after running the "apt-get install linux-headers.3.4.113-nethunter-klte-spr-3.0" it errors out saying "couldn't locate package linux-headers.3.4.113-nethunter-klte-spr-3.0". I've read that ARM devices don't have Linux headers. In order to build this driver I need to install linux-headers. So is there a way to bypass this error and build this driver successfully or is there a mt7610u driver already available that I can just install and use through the command line? I've tried MrEngman script for mt7610u drivers but during the installation it couldn't be installed for to the fact that my kernel was outdated. Any suggestions would be appreciated, thanks.

**Comment by amzker** [comment]
well i like Your work ✔

Ohk If it's not found in repo plz try again 
`apt update && apt install-linux-head*.3.4.113-neth*-klte-spr-3.0`

If still not then install manually deb 
You can avle to contacr ne at telegram @amzker

**Comment by shakim24** [comment]
@amzker I'll try that, if all else fails how do I install it manually??

**Comment by jcadduono** [comment]
we don't make kernel header packages, you have to cross compile on a PC using sources from nethunter-devices kernels.txt

**Comment by shakim24** [comment]
@jcadduono I'm not familiar with cross compiling, can you explain further please.

**Comment by jcadduono** [comment]
see wiki guide

**Comment by shakim24** [comment]
Ok I will. But does it compile to the point where it creates a zip file that I'll have to flash?

**Comment by jcadduono** [comment]
see nethunter-devices readme

**Comment by yesimxev** [comment]
https://github.com/offensive-security/kali-nethunter/issues/1212#issuecomment-430357114

**Comment by shakim24** [comment]
@yesimxev I already have a nethunter kernel which I'm using from the nightly download link. So should I build another with the proper edits needed to cross compile a build?

**Comment by yesimxev** [comment]
This could be your one, never used at the end for my WN722 v2 but seems to be capable for cross compile + monitor mode (but no AP mode)
https://github.com/ulli-kroll/mt7610u

**Comment by shakim24** [comment]
@yesimxev I've seen that github that you have linked. I'm going to need to understand how to cross compile further. I understand the gist of it, I'm just confused about once its compiled on my desktop, will it be in zipfile format so it can be transferred to my device.....

**Comment by yesimxev** [comment]
The compiled zImage.dtb/Image from arch/arm/boot, and the modules from the folder where you have installed them, goes into the nethunter installer devices/nougat/klte folder. Then you simply build a kernel installer with
`./build.py -k -o -d klte`

**Comment by jcadduono** [comment]
if it helps, you don't even need to clone nethunter-devices, you could just grab any of the klte kernel installer zips, ex. https://build.nethunter.com/nightly/2019.03-13-0514/kernel-nethunter-klte-nougat-2019.03-13-0514.zip
and just open the zip and replace the zImage, dtb.img, and kernel module folder with your cross-compiled kernel build output.
I very much recommend using the build scripts (see the readme @ https://github.com/offensive-security/nethunter-devices) so that your kernel builds the modules correctly, or the build scripts included in my previous klte kernel sources.

**Comment by shakim24** [comment]
@jcadduono yeah I'll give it a shot, thanks guys and if I run into any hiccup's I'll just post it.

**Comment by shakim24** [comment]
This may be a noob question so forgive me in advance. How do I implement the compiled wifi driver into my made kernel for my device? I'm just lost because it seems from what I've read on compiling drivers a zip file isn't created. So if I'm building a WiFi driver, no files are present except for the source codes to build it with. Sorry again for my noobness.

**Comment by Re4son** [comment]
That would be great but unfortunately there is no "zipfile" target for make.
The kernel build process only compiles the kernel and kernel modules. Nothing else.
The scripts created by @jcadduono will do all the heavy lifting for you during that phase.

You can either manually copy the files across to the target system, which is clumsy and maybe a bit dangerous, or create an installer package, which is the standard way.
To do the latter, the resulting kernel image and modules have to be packaged up separately using the methods and tools designed specifically for the particular format of the target system (e.g. "deb" package format for debian, "rpm" for Red Hat, or "zip" for TWRP).
To flash a kernel through TWRP you need to create a flashable zip file.

This guide explains how to compile and package an Android kernel:
[https://forum.xda-developers.com/android/software-hacking/reference-how-to-compile-android-kernel-t3627297](https://forum.xda-developers.com/android/software-hacking/reference-how-to-compile-android-kernel-t3627297)

Hope that helps.

**Comment by shakim24** [comment]
@jcadduono after trying to follow your method building lineageOS 14.1 it appears lineage doesn't build with dtb.img, the zImage. How can I build it with a dtb.img?
