### ISSUE TITLE
Nexus 6p Oreo 8.1 External network card is not supported

### ISSUE THREAD

**Issue by LuckyFishGeek** [offensive-security/kali-nethunter#1285]
### Device:

Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oreo 8.1

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/2019.03-13-0514/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.73-nethunter-angler-3.0 (root@kimocoder) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Sun Feb 17 01:19:09 CET 2019

## Issue:
I tested the wn722n network card and other 3070 chips are not supported
![1](https://user-images.githubusercontent.com/29472751/56455092-f47e4d00-638c-11e9-9837-c76ee263fa32.png)
![IMG_20190420_165125](https://user-images.githubusercontent.com/29472751/56455095-fba55b00-638c-11e9-8a92-0a2e87f032db.jpg)

**Comment by jcadduono** [comment]
modprobe, there is no module autoloader service running in android

**Comment by W00DCH1P** [comment]
> 
> ### Device:
> 
> Nexus 6p
> ### OS version (KitKat/Lollipop/Marshmallow/Nougat):
> 
> Oreo 8.1
> ### Built from repo (date and build command) or downloaded from website (links):
> 
> https://build.nethunter.com/nightly/2019.03-13-0514/
> ### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
> 
> Linux version 3.10.73-nethunter-angler-3.0 (root@kimocoder) (gcc version 5.4.1 20170404 (Linaro GCC 5.4-2017.05) ) #1 SMP PREEMPT Sun Feb 17 01:19:09 CET 2019
> ## Issue:
> 
> I tested the wn722n network card and other 3070 chips are not supported
> ![1](https://user-images.githubusercontent.com/29472751/56455092-f47e4d00-638c-11e9-9837-c76ee263fa32.png)
> ![IMG_20190420_165125](https://user-images.githubusercontent.com/29472751/56455095-fba55b00-638c-11e9-8a92-0a2e87f032db.jpg)

Hey there @LuckyFishGeek 

I see you got nethunter running on 8.1 for 6P, I am struggling to get mine to run, could you assist me?

**Comment by kimocoder** [comment]
Do you have more output? attach the dmesg and lsusb also

**Comment by W00DCH1P** [comment]
> 
> 
> Do you have more output? attach the dmesg and lsusb also

Thank you @kimocoder for the quick response, was just trolling your profile for your email. :)

Yes, just to review my steps.

> I have done a fresh ./flash-all with the latest nexus OS 8.1.0 (OPM7.181205.001, Dec 2018)
> Reboot to bootloader and flash TWRP 3.3.0
> Boot into ROM and perform setup
> Boot back to recovery and flash the following 
> nethunter-generic-arm64-kalifs-full-rolling-2019.03-13-0514.zip
> nethunter-angler-oreo-kalifs-full-20190313_110928.zip
> Boot back into ROM see and see the following.
> I can see nethunter boot animation.
> Wallpaper changed.
> There are no APK's installed, no root either.

I will follow up now with dmesg and lsusb, just flashing superSU

**Comment by kimocoder** [comment]
Flash Magisk instead

**Comment by W00DCH1P** [comment]
OK, Magisk installed

**Comment by kimocoder** [comment]
And I use to build the kernel from the NetHunter installer and flash everything seperate in that matter

**Comment by kimocoder** [comment]
load the kernel module needed om androidsu, the run "bootkali" check with lsmod and lsusb, and attach dmesg

**Comment by W00DCH1P** [comment]
[dmesg.txt](https://github.com/offensive-security/kali-nethunter/files/3111874/dmesg.txt)

No output for lsusb, here is my dmesg.

Could you provide a guide on how you built the kernel?

**Comment by kimocoder** [comment]
If it's not in the lsusb, you sure that the OTG cable is supported?
Kernel source is https://github.com/kimocoder/android_kernel_huawei_angler/tree/nethunter-8.0 with build script and all. In basics, it's the v7.1.1 build with merges from upstream.

**Comment by kimocoder** [comment]
If you was asking to how I build the installer, using build.py or howto build/modify a kernel
Check wiki over here https://github.com/offensive-security/kali-nethunter/wiki

**Comment by kimocoder** [comment]
![IMG_20190424_131524](https://user-images.githubusercontent.com/4252297/56655497-3829cd00-6693-11e9-8a2d-168f47601b28.jpg)

Try building from build.py using the wiki article mentioned on Telegram :+1:
