### ISSUE TITLE
Autoit error

### ISSUE THREAD

**Issue by infinityguru** [offensive-security/kali-nethunter#133]
I Was trying to install hunter kali did everything well but now i am stuck on
autoit error while flashing rom
![untitled](https://cloud.githubusercontent.com/assets/10291221/5555219/84840556-8cc9-11e4-9add-3057fc60b122.png)

**Comment by Kruemmelmonster** [comment]
:+1: for dj mad dog ;) and now for a fix!
Go to c:\Program Files\NetHunter Install whatever its called\ 
there you have all needed files to install NetHunter on your device 
Next step is just to flash the device manually try to google "flash rom adb" if you dont know how to do it

**Comment by jmingov** [comment]
https://github.com/offensive-security/kali-nethunter/wiki#unlocking-and-rooting-your-android-device-windows
