### ISSUE TITLE
there is no directory found error Nexus 5

### ISSUE THREAD

**Issue by gitboy122** [offensive-security/kali-nethunter#136]
On my nexus 5 I installed nethunter on aosps like pa,slimroms,stock but as secondary ROM in multiboot.Kali server is working but terminal programs like wifite and Kali menu don't and start throwing following errors.and my kernal Says .furnance 

u0_a60@hammerhead:/ $
u0_a60@hammerhead:/ $ su
bootkali
kalimenu
bootkali
kalimenu
root@hammerhead:/ # bootkali
mountpoint: /data/local/kali-armhf/dev: No such file or directory
mount: mounting /system on /data/local/kali-armhf/system failed: No such file or directory
mount: mounting /sdcard on /data/local/kali-armhf/sdcard failed: No such file or directory
mount: mounting /dev on /data/local/kali-armhf/dev failed: No such file or directory
mount: mounting devpts on /data/local/kali-armhf/dev/pts failed: No such file or directory
mount: mounting proc on /data/local/kali-armhf/proc failed: No such file or directory
mount: mounting sysfs on /data/local/kali-armhf/sys failed: No such file or directory
kernel.shmmax = 268435456
net.ipv4.ip_forward = 1
/system/bin/bootkali[51]: can't create /data/local/kali-armhf/proc/sys/kernel/hostname: No such file or directory
Toolbox!
chroot: can't execute '/bin/bash': No such file or directory127|root@hammerhead:/ # kalimenu
sh: kalimenu: not found
127|root@hammerhead:/ #

**Comment by gitboy122** [comment]
@Zaxscdvf hey man how did u used nethunter installer with parandroid all I get is download page where I have to download factory image and recovery etc..

**Comment by Lypsis** [comment]
I had the same problem: manually installed Nethunter on a Android 4.4 and got the same "... not found" errors.
Installed the BASH Shell and it worked :) In the Terminal Emulator settings I configured bash as the shell to use.

Hint: You can easily install the Bash Shell with apps on the Android market, e.g. "Bash Shell X" (com.bitcubate.android.bash.installer)

**Comment by gitboy122** [comment]
@Lypsis sorry man didn't worked for me.was u using multirom

**Comment by Zaxscdvf** [comment]
hey has the problem been resolved where 

"The problem then it is problem with .zip scripts
And the fact that it is too big bcz I remember in multirom it said-- that zip is too big multirom is modifying it do not use it except for multirom--
I hope developer will fix it .i will try it in morning thank guys"

so i can use nethunter as a secondary rom or possibly install it on a usb.

**Comment by Somnathnr** [comment]
I too same issue can't execute /bin/bash when typed bootkali

**Comment by Nitinnm** [comment]
I am using samsung j700f
In kali nethunter when i wrote iwconfig wlan1 it shows no such device
