### ISSUE TITLE
ubertooth with nethunter

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#137]
https://github.com/greatscottgadgets/ubertooth/issues/44 what do you guys think?

**Comment by gitboy122** [comment]
@Zaxscdvf hey man how did u used nethunter installer with parandroid all I get is download page where I have to download factory image and recovery etc...

**Comment by Zaxscdvf** [comment]
@gitboy122 i installed nethunter as primary rom then used multi rom to install slim rom, paranoid android etc. Thats the way it worked for me.

**Comment by julianschweizer** [comment]
I used multiROM to keep my current Rom and flashed paranoid and nethunter by Hand (custom recovery). Easy task if you know how to use multiROM. Look it up on xda.



---- gitboy122 schrieb ----

**Comment by Zaxscdvf** [comment]
https://github.com/gnychis/ubertooth-android found this can any one test it and see if every thing works fine.

**Comment by Zaxscdvf** [comment]
Was wondering if the built in bluetooth dongles work with this https://github.com/gnychis/ubertooth-android if so would i need an external wifi adapter or would my built in adapter work fine?

**Comment by gitboy122** [comment]
I dont think internal wifi adapter works bcz cant be put into mon mode and dont know about Bluetooth one.

**Comment by Zaxscdvf** [comment]
@gitboy122  sorry i pasted the wrong link i was referring to snoopy-ng https://github.com/sensepost/snoopy-ng

**Comment by Zaxscdvf** [comment]
@0E800 were you able to get it working?

**Comment by Zaxscdvf** [comment]
can some one verify that ubertooth works with nethunter.

**Comment by 0E800** [comment]
Sorry, I ran into hardware complications with my device and have not had the time to retest. Please keep ticket open and I will do my best to update in the near future.

**Comment by Zaxscdvf** [comment]
@0E800 alright i understand.. can any one else do some testing?

**Comment by Fetan** [comment]
I know this is an older ticket so this is likely late. I can verify ubertooth works well with Nethunter. I am using version 1.2.1 on a 2013 N7. I have not quite figured out a way to use ubertooth-specan-ui with VNC yet, but I really haven't spent any time with it yet. You can use spectool_curses to get a very simple  spectrum analyser. I also am messing with the ubertooth-specan output to see what other possible ASCII or ncurses methods might be useful.

**Comment by maximcherny** [comment]
I've had mixed results on my Nexus 7. If you send it a lot of packets in LE mode, it seems to crash sporadically and requires dongle reset every now and again. I have seen comments about having issues on low-powered devices.

With regards to snoopy-ng, there is no code currently that supports Ubertooth-based sniffing, but I am looking into it.
