### ISSUE TITLE
Issue after toolchain - oneplusone

### ISSUE THREAD

**Issue by cucx** [offensive-security/kali-nethunter#138]
While building the development branch for the OnePlusOne I saw the following error:

> Build All - Kali rootfs and Kernel (Android 5)

<pre>Downloading Android Toolchian
Cloning into '/root/arm-stuff/kali-nethunter/android-001/toolchain'...
remote: Sending approximately 37.11 MiB ...
remote: Counting objects: 38, done
remote: Finding sources: 100% (38/38)
remote: Total 217 (delta 53), reused 217 (delta 53)
Receiving objects: 100% (217/217), 37.12 MiB | 6.08 MiB/s, done.
Resolving deltas: 100% (53/53), done.
Setting export paths

Downloading Kernel
Cloning into '/root/arm-stuff/kali-nethunter/devices/kernels/oneplus12'...
remote: Counting objects: 2765832, done.
remote: Compressing objects: 100% (439844/439844), done.
remote: Total 2765832 (delta 2299464), reused 2765832 (delta 2299464)
Receiving objects: 100% (2765832/2765832), 590.27 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (2299464/2299464), done.
Checking out files: 100% (42316/42316), done.
devices/one-bacon: line 155: cd: /root/arm-stuff/kali-nethunter/android-001/kernel: No such file or directory
chmod: cannot access `scripts/*': No such file or directory
chmod: cannot access `ramdisk/5/mkbootimg': No such file or directory
chmod: cannot access `ramdisk/5/dtbToolCM': No such file or directory
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `kali_defconfig'.  Stop.
Building Kernel
make: *** No targets specified and no makefile found.  Stop.
grep: .config: No such file or directory
Module support is disabled.
Detected exsisting /flash folder, copying kernel and modules
cp: cannot stat `/root/arm-stuff/kali-nethunter/android-001/flashkernel/system/lib/modules/*': No such file or directory
building file list ... 
rsync: change_dir "/root/arm-stuff/kali-nethunter/android-001/kernel/modules/lib" failed: No such file or directory (2)
0 files to consider

sent 12 bytes  received 12 bytes  48.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
Adding Kernel install to updater-script in main update.zip
devices/one-bacon: line 195: cd: /root/arm-stuff/kali-nethunter/android-001/kernel: No such file or directory
Creating dt.img
devices/one-bacon: line 198: /root/arm-stuff/kali-nethunter/android-001/kernel/ramdisk/5/dtbToolCM: No such file or directory
Creating boot.img
devices/one-bacon: line 201: /root/arm-stuff/kali-nethunter/android-001/kernel/ramdisk/5/mkbootimg: No such file or directory
cp: cannot stat `/root/arm-stuff/kali-nethunter/android-001/flashkernel/boot.img': No such file or directory
Reading package lists... Done</pre>

Extract of the devices/one-bacon file:

<pre>
f_kernel_build_init

cd ${basedir}
echo "Downloading Kernel"
if [[ $LOCALGIT == 1 ]]; then
  echo "Copying kernel to rootfs"
  cp -rf ${basepwd}/oneplus12 ${basedir}/kernel
else
        git clone https://github.com/binkybear/furnace-bacon.git -b cm-12.0 ${basepwd}/devices/kernels/oneplus12
fi

cd ${basedir}/kernel

chmod +x scripts/* ramdisk/5/mkbootimg ramdisk/5/dtbToolCM

make clean
sleep 10
make kali_defconfig

</pre>

Let me know if you need any further details

**Comment by binkybear** [comment]
The first error is because we never build any modules so that's normal (although ugly).

The second error with the ROM placement will be removed.  Adding to ROM's was just for testing and was never meant to be "official."  Although, I did like the idea but we use the installer instead so that won't be feature will keep.
