### ISSUE TITLE
OnePlus One

### ISSUE THREAD

**Issue by theoneandonly-vector** [offensive-security/kali-nethunter#141]
OnePlus One configuration file isn't there anymore.
I thought it was added officially.

**Comment by offensive-security** [comment]
which configuration are you talking about ?

**Comment by theoneandonly-vector** [comment]
https://github.com/offensive-security/kali-nethunter/tree/master/devices
there isn't any OnePlus One bacon file...

Here it was announced:
http://www.nethunter.com/prepare/

I installed it before it was integrated in the official repository for my OnePlus One, but now I will update to android 5 and because of this, I need also a android 5 Kernel, which have the modules for  nethunter...

**Comment by offensive-security** [comment]
Those website updates are for an upcoming release. We do not support lollipop yet with any of our builds. You can find the OPO file in our development branch - https://github.com/offensive-security/kali-nethunter/tree/development/devices

**Comment by theoneandonly-vector** [comment]
Thank you
