### ISSUE TITLE
Power Button Unresponsive

### ISSUE THREAD

**Issue by simonyeoh6** [offensive-security/kali-nethunter#143]
After i root to nethunter. My nexus 7 gave me the unresponsive black screen last night with 20% battery left. Power button tends to be unresponsive after few minutes the device turned on. 
Came back to life after holding power and volume down for 10 secs.

I currently using Nexus 7 (2012) 16GB wifi version

**Comment by binkybear** [comment]
@julianschweizer - Sadly, multirom will not give me your last dmesg so its hard for me to track down this issue.  I'm unsure on the issue but it may have something to do with processing power of devices as metasploit and openvas can take up a lot of memory.  

That's just a guess at the moment.  Please let me know if you come across these issues at other times.

**Comment by jmingov** [comment]
No comments in 12 months.
