### ISSUE TITLE
Main menu kalimenu option

### ISSUE THREAD

**Issue by Anotherenduser** [offensive-security/kali-nethunter#147]
Version 1.1 on Nexus 7 2013 the main menu button for "Launch Kali Menu in Terminal" does not launch the menu, just leaves me at a root prompt. Typing kalimenu from there will launch the menu.

**Comment by unknownpwn** [comment]
Which Android version are you using? You could try installing the latest version of the app and see if that works, https://github.com/offensive-security/kali-nethunter/raw/master/flash/data/app/nethunter.apk

**Comment by offensive-security** [comment]
Please note that  kalimenu is going to be depreciated in future versions of NetHunter, so further development will be halted.

**Comment by Anotherenduser** [comment]
Android version is 4.4.4.

**Comment by Anotherenduser** [comment]
Posted apk is same version I have now. Menu worked in previous version, not in this one. Since its going away anyway I'll just command it up as needed. Thanks guys!

**Comment by Anotherenduser** [comment]
OK, this is resolved. Whole thing was my fault. I upgraded nethunter but failed to realize the launcher ice on my home screen was still old one. Got to looking around and found, in my app drawer, a new icon called Nethunter Home.  Removed the old one, added this to home screen. Menu and everything else work properly. I will close this "issue".... My bad, sorry guys :(

**Comment by unknownpwn** [comment]
Glad that it worked out for you! :+1:

**Comment by Zaxscdvf** [comment]
@offensive-security why is the kalimenu being depreciated? i think its a good idea to keep it going, it saves me a lot of time.

**Comment by offensive-security** [comment]
The idea is to centralize the management of nethunter to one interface. I think the android app is better suited for that. I forsee most of the functionality of Kali Menu ending up in the native app.

**Comment by Zaxscdvf** [comment]
@offensive-security oh i see.
