### ISSUE TITLE
Nexus 7- Nethunter: Comnect External WiFi 

### ISSUE THREAD

**Issue by jevalenciap** [offensive-security/kali-nethunter#157]
I have a AWUS036H WiFi card, I am connecting my Nexus 7 (2012 Wifi) with OTG cable to a USB Hub, then I connect the Wifi External card to the USB hub with miniUSB cable, but Nethunter does not recognize the wlan1 card. I am not using Y- cable -Otg. My cuestión is:

Should I use Y-cable for Nexus detect my Wifi card, there is another way for reaching that?

The kernel of Nethunter is 
3.1.10- Kangaroo
Root@kali#1

Versión Android 4.4.2

**Comment by jmingov** [comment]
Hi, i dont know if nethunter has drivers/compatibility with the wireless adapter.

Is this adapter?

![](http://www.zero13wireless.net/wireless/drivers/awus036h/imagen.jpg)

About the Y-cable, isnt needed but you will need a miniusb-to-usb cable at least.

The Y-clable only gives you an additional interface to plug a battery etc but is not a requirement.

Saludos

**Comment by jevalenciap** [comment]
Yes, this is the Wifi adapter,  the AWUS036H adpater is supported by Nethunter.

http://www.nethunter.com/faq/#externalwifi

**Comment by offensive-security** [comment]
That adapter might be drawing too much power - try using a y-cable together with a power supply and see if you get different results.

**Comment by cr1p70** [comment]
Tplink TL-WN722N works out the box so far.and from everything ive read,if you do use an alpha it needs seprate power source to run properly.
