### ISSUE TITLE
iwlist scan reboots the device

### ISSUE THREAD

**Issue by cynom** [offensive-security/kali-nethunter#160]
Hi There,

I flashed the latest (1.10) image of nethunter to Nexus 5 (Android 4.4.4). I plugged in Alfa AWUS036H using OTG and executed the commands
1. ifconfig wlan1 up
2. iwlist wlan1 scan

After iwlist, the device simply freezes and reboots. I tried the same steps with TP-Link (TL-WN722N) and the results are same i.e. device reboots. Only Alfa AWUS051NH worked. 

If there something I can do to make the rest wireless cards work? Here is the /proc/last_kmsg captured just after the reboot: http://pastebin.com/Sx73N4uS

**Comment by binkybear** [comment]
Is it just iwlist or can you run things like airodump-ng? The kernel panic seems to involve wext/cfg80211 and I'm unsure if this is just an incompatibility with iwlist or if it's something deeper.

**Comment by tordhr** [comment]
Its just iwlist in this case. airmon, airodump work just seamless, no surprises.

**Comment by perrenialprick** [comment]
I've encountered the same issue. iwlist only.

**Comment by pgrohe** [comment]
Can confirm this also occurs on a Nexus 5 / Nethunter 1.2 / Lollipop with both the TP-Link WN722N & TP-Link WN821N.

Exact same steps as in the original issue. Bring interface up, iwlist scan.

I've also experienced reboots during Wifite WEP cracking on my test APs.

The last comment on this issue #8 suggests reboots are power related but I woudn't have expecte just doing an iwlist scan to draw enough power to trigger a reboot:
https://github.com/offensive-security/kali-nethunter/issues/8 

I don't have a Y OTG cable to test if this still occurs with external power.

**Comment by Bauta76** [comment]
Same thing happens with Nexus 7 ( WiFi 2013 ). Only with iwlist.

**Comment by TheNain38** [comment]
I also have the same issue, TL-WN722N on Nexus 7 (2013 Wifi). Only iwlist is causing me problems.

**Comment by Uvemode** [comment]
Same with Nexus 5 Marshmallow and AWUS036NHA.
Seems to be cause by something network-based, the device also reboots if I use other wifi-related but no infosec related tools, such as wicm-curses.

**Comment by 0E800** [comment]
Review:
https://ubuntuforums.org/showthread.php?t=1979338
Use techniques provided to dig, DIG DEEP.
