### ISSUE TITLE
nfc-list command not found

### ISSUE THREAD

**Issue by zjq777007** [offensive-security/kali-nethunter#162]
nfc-list command not found
My device is nexus5 32G LTE
I want to use nfc attack,I choice the 11 in kali menu and choice the 3 option
Then it says:nfc-list command not found
why ? thanks

**Comment by Zaxscdvf** [comment]
maybe you have nfc turned off.

**Comment by zjq777007** [comment]
@Zaxscdvf  No,my build-in NFC is turn on

**Comment by binkybear** [comment]
Inside Kali shell try:
apt-get install libnfc-bin
or 
apt-get install mfcuk

**Comment by zjq777007** [comment]
@binkybear ok,It works,but it display "no such device",why? My nexus5's build-in NFC is turn on

**Comment by offensive-security** [comment]
You need to use an external NFC dongle for these attacks (with an OTG cable), the internal does not support them.
