### ISSUE TITLE
Save all scan result nethunter in terminal shell

### ISSUE THREAD

**Issue by majesty8** [offensive-security/kali-nethunter#163]
Does anyone know how to save the scan result into text file and save into SD card when we perform scanning through kali nethunter terminal shell? Do I need to write script? How﻿ to update kali menu and reinstall it in nexus 5? I cant find the kalimenu in the directory...

**Comment by majesty8** [comment]
In the kali nethunter terminal shell, there is a menu button in the top right corner where we can choose the "email to", when we click it, it will save all scan results in the screen into the mail for sending, but in my case, I want it to save the scan result into a txt/csv file instead, how can I achieve that? where should I edit the script to approach that result?

**Comment by jmingov** [comment]
Try piping the command to a file!  

Something like:

`any_command_here > myFileWithResults.txt`

Jaime

**Comment by majesty8** [comment]
@jmingov 
Thanks!

Thanks a lot! It works.

Can I make the scanning of this command: "su -c bootkali -> airmon-ng start wlan0 -> airodump-ng wlan1" with just a single button click? Make an app like nethunter app, when we click the "launch wifite" button, straight it will perform wifite scan, we dont need to key command. How can I do that too with the above commands?

**Comment by jmingov** [comment]
Hi, the **Nethunter app is open Source** too, you need to know *java + some android + understand a bit the kali Nethunter architecture to build an app*.

Check the source code here:

https://github.com/offensive-security/nethunter-app

**Comment by majesty8** [comment]
Yes I know, please check this code in nethunter app:

addClickListener(R.id.button_launch_wifite, new View.OnClickListener() {
            public void onClick(View v) {
                Intent intent =
                        new Intent("jackpal.androidterm.RUN_SCRIPT");
                intent.addCategory(Intent.CATEGORY_DEFAULT);
                intent.putExtra("jackpal.androidterm.iInitialCommand", "su -c bootkali wifite");
                startActivity(intent);
            }
        }, rootView);

the intent is trying to call su -c bootkali wifite, but how in my case to perform "su -c bootkali -> airmon-ng start wlan0 -> airodump-ng wlan1"?

**Comment by jmingov** [comment]
As you can see, each command starts with su -c bootkali, this is because the bootkali script handles some important stuff(it mounts kali, manages the setenforce...)

Your command cant work since the airmon-ng command isnt handled with the bootkali script.

You need to modify the bootkali to get this change working.

Since is a really specific case. Not sure if its worth.

**Comment by majesty8** [comment]
maybe we can write a script to perform those command?

**Comment by jmingov** [comment]
Yes the best option is to build your own bootkali with custom options. Thats true.

**Comment by majesty8** [comment]
Any idea of how to write the custom script according to my case?

**Comment by jmingov** [comment]
Get a copy of the bootkali script.

The first 80 lines are a MUST.

After the line 81 https://github.com/offensive-security/kali-nethunter/blob/de00d664ca82102edb21e17508c1b4727f9c3f11/flash/system/bin/bootkali#L81

You will see the dirent commands. Add you implementation there.

rename it an try a intent like su -c customkali yourcmd.

Hope it helps.

Jaime

**Comment by majesty8** [comment]
Take the wifite as example:

#WIFITE

      if [ "$1" == "wifite" ]; then
         $busybox chroot $mnt /bin/bash -c "chmod 777 /dev/null"        
         ifconfig wlan1 up
         sleep 3
         LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/python /usr/bin/wifite
   	fi

There is only one command for running the wifite ("ifconfig wlan1 up"). In my case, there are more than one commands: airmon-ng start wlan0 -> airodump-ng wlan1". which is 2 commands, what is the way I should write?

**Comment by offensive-security** [comment]
Marking this issue s closed
