### ISSUE TITLE
Customize Bootkali File

### ISSUE THREAD

**Issue by majesty8** [offensive-security/kali-nethunter#165]
How can I make the scanning of this command: "su -c bootkali -> airmon-ng start wlan0 -> airodump-ng wlan1" with just a single button click? Make an app like nethunter app, when we click the "launch wifite" button, straight it will perform wifite scan, we dont need to key command in the terminal. How can I do that too with the above commands?

Take the wifite as example(script appear in bootkali):

#WIFITE

  if [ "$1" == "wifite" ]; then
     $busybox chroot $mnt /bin/bash -c "chmod 777 /dev/null"        
     ifconfig wlan1 up
     sleep 3
     LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/python /usr/bin/wifite
fi
There is only one command for running the wifite ("ifconfig wlan1 up"). In my case, there are more than one commands: airmon-ng start wlan0 -> airodump-ng wlan1". which is 2 commands, what is the way I should write?

And also what should we put for "LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/python /usr/bin/wifite" for my case?

**Comment by offensive-security** [comment]
Sounds like you need a bit of Android app development. The Kali NetHunter issue tracker should be reserved for bugs, issues and suggestions. You're better off posting questions like these in our Nethunter forums, or general Android development forums.

**Comment by majesty8** [comment]
@offensive-security 
Where should I post this question would be suitable?

**Comment by offensive-security** [comment]
I am not familiar with android development forums, Google is your friend.

**Comment by majesty8** [comment]
actually, android side is okay, just the problem is with the script to make those commands run
