### ISSUE TITLE
we want Kali Linux Net Hunter for YU YUREKA smartphone

### ISSUE THREAD

**Issue by Rakesh95** [offensive-security/kali-nethunter#166]
http://forum.xda-developers.com/yureka

https://github.com/YUPlayGod

**Comment by offensive-security** [comment]
Witohut the hardware it's difficult to build these images, but patches are welcome!

**Comment by stevenliuit** [comment]
we want too Kali Linux Net Hunter for YU YUREKA smartphone

**Comment by Rjrocks22** [comment]
Getting a clean tutorial will be helpful
