### ISSUE TITLE
External Wi-FI wlan1 not available - Nexus 7 2013 LTE Lollipop 5.0.2, Alfa AWUS036H

### ISSUE THREAD

**Issue by AndyKr0p** [offensive-security/kali-nethunter#167]
Guys,

Yet another issue found on the device above - I updated Android 4.4.4 ->5.0.2, complied latest Nethunter on Kali Linux and installed it via TWRP. Now, I tried to enable wlan1 but ifconfig said:

wlan1: ERROR while getting interface flags: No such device

dmesg said:
[ 3401.115631] msm_otg msm_otg: USB exited from low power mode
[ 3401.223266] init: untracked pid 14655 exited with status 69
[ 3401.379699] usb 2-1: new high-speed USB device number 6 using msm_hsusb_host
[ 3401.455566] init: untracked pid 14657 exited with status 0
[ 3401.537689] usb 2-1: New USB device found, idVendor=0bda, idProduct=8187
[ 3401.537811] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3401.537963] usb 2-1: Product: RTL8187_Wireless_LAN_Adapter
[ 3401.538024] usb 2-1: Manufacturer: Manufacturer_Realtek_RTL8187_
[ 3401.538177] usb 2-1: SerialNumber: 00C0CA7ED30A
[ 3401.716552] type=1400 audit(1423229557.808:346): avc: denied { write } for pid=14681 comm="app_process32_o" name="system@framework@boot.art" dev="mmcblk0p30" ino=1138692 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file
[ 3401.881103] init: untracked pid 14677 exited with status 89
[ 3402.106536] init: untracked pid 14681 exited with status 0
[ 3402.329925] type=1400 audit(1423229558.428:347): avc: denied { write } for pid=14701 comm="app_process32_o" name="system@framework@boot.art" dev="mmcblk0p30" ino=1138692 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file
[ 3402.537536] init: untracked pid 14699 exited with status 246
[ 3402.759735] init: untracked pid 14701 exited with status 0
[ 3411.086242] type=1400 audit(1423229567.177:348): avc: denied { create } for pid=14723 comm="ifconfig" scontext=u:r:init_shell:s0 tcontext=u:r:init_shell:s0 tclass=udp_socket
[ 3411.092559] type=1400 audit(1423229567.187:349): avc: denied { ioctl } for pid=14723 comm="ifconfig" path="socket:[87369]" dev="sockfs" ino=87369 scontext=u:r:init_shell:s0 tcontext=u:r:init_shell:s0 tclass=udp_socket
[ 3411.093017] type=1400 audit(1423229567.187:350): avc: denied { sys_module } for pid=14723 comm="ifconfig" capability=16 scontext=u:r:init_shell:s0 tcontext=u:r:init_shell:s0 tclass=capability
[ 3417.440673] bq27541_get_psp status: Not charging ret= 0x0100
[ 3417.441375] bq27541_get_psp status: Not charging ret= 0x0100
[ 3417.442138] bq27541_get_psp voltage_now= 4004000 uV
[ 3417.442810] bq27541_get_capacity = 72% ret= 73
[ 3417.443542] bq27541_get_psp temperature= 310 (0.1\xffffffa2XC)
[ 3417.444793] bq27541_get_psp current = 160 mA
[ 3417.446197] bq27541_get_capacity = 72% ret= 73
[ 3417.447021] bq27541_get_psp voltage_now= 4004000 uV
[ 3417.447753] bq27541_get_psp temperature= 310 (0.1\xffffffa2XC)
[ 3417.448577] bq27541_get_psp status: Not charging ret= 0x0100
[ 3417.450347] bq27541_get_psp current = 160 mA
[ 3417.450592] healthd: battery l=72 v=4004 t=31.0 h=2 st=4 c=0 chg=

Alfa connected to the Nexus 7 via Y cable USB OTG, powerbank is used to feed devices, output 5V 2100mA. On the previous configuration (KitKat 4.4.4 and Nethunter 1.0.2) that card worked fine.

What do you think?

**Comment by jmingov** [comment]
Is just the card or the rest of functionality isnt working too?

**Comment by AndyKr0p** [comment]
What do you mean by "the rest of functionality"? At least I installed openvas and it works. I was going to test wifite but stuck with that issue. I did not play too much yet with other stuff.

**Comment by jmingov** [comment]
Yes just if the rest of the attacks/core actions are working fine.(Anything that dont needs the wireless/monitor mode)

Since i doesnt have your card model i cant test it.

Can be a corrupted kernel build? 

or

The `avc: denied { write/create }` errors makes me think in the next: **SeLinux Permissions**

If  you have SELinux running in enforcing mode and it  is rejecting some processes to access another resources belong to different SELinux domain but i dont know why is this happening.

 @binkybear maybe can throw some light here.

**Comment by AndyKr0p** [comment]
To be honest I have no idea so far about SeLinux errors...Kernel build was installed without issues in TWRP logs, just smooth. Thank you anyway!

**Comment by binkybear** [comment]
@AndyKr0p - So, let go over the good news (we can call it that I guess).  Your device is recognized by kernel.  Bad news, y-cable is not enabled at the moment for 5.0.2.  I believe the 036H draws a lot of power which might be the issue.  Did you use it previously in 4.4.4 version?  If so, did you need to have a y-cable to use it?

@jmingov - The selinux errors will still show up even when its in permissive mode so those can be a bit misleading.  However, if the device isn't in permissive mode then that could also be the issue.

So what you could do as a small test is load up kali chroot (from app if you like), in a separate terminal window (outside of chroot/android terminal), type ```getenforce``` and make sure it's set to permissive.  If it isn't, then type ```setenforce 0```.

Please let me know about previous experience wireless card. Thanks!

**Comment by AndyKr0p** [comment]
@binkybear that's the same y-cable which I used with KitKat 4.4.4 with no issues conenecting Alfa and TP-LINK TL-WN722N too. I did not try another cable like straight mini-USB -USB femail, y-cable was used brom the beginning. now it does not work with WN722N too. 
However it perfectly works with usb stick and I can mount usbotg storage!

**Comment by AndyKr0p** [comment]
Gents,

I don't push anyone indeed but is there is workaround or solution that I could test? If negative I will revert all changes to Kitkat since I need working tablet:(

**Comment by binkybear** [comment]
@AndyKr0p - If you want stability I would suggest using 4.4.4.  If you want to test it is possible to use multirom and have 4.4.4 and 5 installed on one device.  But that a bit more complicated process.

As far as your issues with the N7 2013 I can enable y-cable support to see if it changes anything for you.  If you wish to try I can build a kernel this evening.

**Comment by AndyKr0p** [comment]
@binkybear Sure, I would test y-cable enabled kernel. Thank you and look forward to updates.

**Comment by binkybear** [comment]
@AndyKr0p - This might be a little easier actually.  Turns out I have y-cable support already built in, but it's turned off.  Can you go into terminal on device (or use adb) and type:
```
su
echo 1 > /sys/module/msm_otg/parameters/usbhost_charge_mode
```
That "should" turn it on, although I haven't tried.

**Comment by AndyKr0p** [comment]
@binkybear Thank you for advice but it did not help. I had to Downgrade to 4.4.4 :(

**Comment by balveer231** [comment]
Plzz help!!! I have Nexus 5 and I install nethunter on it and I started wifite attack but not showing wlan1 option
