### ISSUE TITLE
Not beautiful women after nethunter switching

### ISSUE THREAD

**Issue by free-man-** [offensive-security/kali-nethunter#17]
I read on http://www.kali.org/kali-linux-nethunter/ :

"I switched on my NetHunter and was immediately surrounded by beautiful women, it was amazing."

I have switched on my NetHunter (Device Nexus 10) and i have been waiting for 4 hours but not beautiful women arrived.

Thank you for everything. Well done everybody. Keep up !

**Comment by cr1p70** [comment]
LMFAO...
