### ISSUE TITLE
External wifi shows up on wlan0 not wlan1

### ISSUE THREAD

**Issue by mikehuggs** [offensive-security/kali-nethunter#170]
When I connect my external wifi (RTL8187) it is coming up on wlan0.  The Kali menu script seems to only check for external wifi on wlan1 which is the internal wifi.  This didn't happen on the previous version of Nethunter.  When I change the script and switch the 1's and 0's it works fine.  Anyone know why this is happening?  

I'm running Android 4.4.4 on a Nexus 7 2013 (wifi) with Nethunter 1.1.

**Comment by mf-ops** [comment]
try to connect ext. wifi after boot

**Comment by mikehuggs** [comment]
Thanks, I did and it works!
