### ISSUE TITLE
TP­Link TL­WN722N USB adapter (NO WAN1)

### ISSUE THREAD

**Issue by jdugat** [offensive-security/kali-nethunter#171]
My Nexus 7 (2013) doesn't recongize anything but the internal adapter. The green light flashes but ifconfig only shows wan0.  I am use the OTG cable.

**Comment by mikehuggs** [comment]
Are you connecting the tplink before you power on the nexus 7 or after?

**Comment by jdugat** [comment]
I'm connected to it when I power up.

On Tuesday, February 17, 2015, mikehuggs <notifications@github.com> wrote:

> Are you connecting the tplink before you power on the nexus 7 or after?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/171#issuecomment-74732073>
> .
>


-- 
Some people are like slinkies, not really good for anything, but they bring
a smile to your face when pushed down the stairs!

**Comment by mikehuggs** [comment]
Can you see it under iwconfig?

**Comment by jdugat** [comment]
Here's the wan1 iwconfig

See attached.

On Tuesday, February 17, 2015, mikehuggs <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Can you see it under iwconfig?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/171#issuecomment-74739668>
> .
>


-- 
Some people are like slinkies, not really good for anything, but they bring
a smile to your face when pushed down the stairs!

**Comment by mikehuggs** [comment]
I don't see the attachment.  

If you see your card under iwconfig then use ifconfig wlan1 up

For me it's wlan1 but your's could be wlan0.

**Comment by jdugat** [comment]
ifconfig wlan1 up

brings up the adapter. Not sure why its not seen during boot up.

**Comment by 0E800** [comment]
Just wanted to mention that ifconfig might not always show your device, so its best to check with airmon-ng.
