### ISSUE TITLE
building nethunter with sudo corrupted kali environment 

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#172]
Hi, since having built nethunter on a stock kali box when ever i try and run nano I get the following error message "/system/bin/linker: No such file or directory" and when I try and uninstall/reinstall nano I get this error message

dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin

What did the nethunter build scripts do to my machine?

**Comment by binkybear** [comment]
@thesle3p - I can confirm I've run into this error also.  I've had to resort to using vi in the meantime but thats not the ideal fix/solution.  We will look into this.

**Comment by binkybear** [comment]
Quick look, it seems that nano was replace:
```
/bin/nano: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked (uses shared libs), stripped```

**Comment by binkybear** [comment]
In the meantime, this worked for me as far as getting nano up and running.  You will ave to change package based on architecture.

wget http://ftp.us.debian.org/debian/pool/main/n/nano/nano_2.2.6-1+b1_amd64.deb
dpkg --install nano_2.2.6-1+b1_amd64.deb

**Comment by offensive-security** [comment]
A better temporary solution would be:
sudo rm /bin/nano
sudo apt-get remove nano
apt-get update 
apt-get install nano

**Comment by highchecker** [comment]
i am on a nexus 9 and have the same problem, i cant install anything, alwayss getting root path problem, i flashed dozens of times, always same problem. everything works fine with the kali launcher, but when i want to use kali on vnc or xserver, i cant install things, the webbrowser doesnt work etc

**Comment by jmingov** [comment]
I think with kali 2.0 and new installer is no longer happening. @binkybear  @offensive-security

 Confirm and close if solved.

**Comment by jcadduono** [comment]
possible solution, assuming this is the same problem i had (with all versions of nethunter)
go into terminal emulator / nethunter terminal settings and disable verify path entries. the verify path entries feature always removes paths based on what non-root users can't see, so it screws everything up once you are root.
i think nethunter terminal needs verify path entries feature fixed to be more su friendly, or disabled by default.

**Comment by binkybear** [comment]
@jcadduono - The error you mentioned is different then building the Kali chroot.  The chroot builder in latest builds should have fixed issue.

However, I did try to reproduce your error on a fresh install and did not see an issue.  If you have a screenshot or exact error that would be helpful, thanks.

**Comment by jmingov** [comment]
The issue refers to the kali host that builds the intaller ^^
