### ISSUE TITLE
VPN or access to the victim machine 

### ISSUE THREAD

**Issue by coldalfred** [offensive-security/kali-nethunter#173]
Sorry for my english ill do my best..

Hi community...

I have a nexus 5 with kali hunter with cable OTG

There is any way... when i connect trough the badUSB i can get some vpn? or any way to get into the net via USB? 

what im trying to do is to pentesting a remote location that doesn't have internet on the victim machine... ill put the cell phone to any victim machine that have internal net and activated the badUSB but i can't view any ip on the internet net

**Comment by offensive-security** [comment]
Sorry, not sure i understand what you are trying to do. Are you trying to connect the victim pc to the internet? Or are you trying to access the local network remotely via the phone?

**Comment by coldalfred** [comment]
Yes Im trying to access the local network remotely via the phone... when i connected via badUSB there any possibility to do it?

And what about badUSB and DLP or policy domains to shutdown USB interfaces there is any possibility to bypass them? when is only software protection?

I hope that you can understand sorry for my english

**Comment by coldalfred** [comment]
Please help me

**Comment by offensive-security** [comment]
BadUSB doesn't have any magic bypass features. If USB is disabled, then it's disabled. As for accessing the network remotely - BadUSB has little to do with that...i suggest you get a better understanding of what badUSB actually does.
