### ISSUE TITLE
NetHunter HID K Attack:How to hide/minimize the cmd Window on host.?:#

### ISSUE THREAD

**Issue by yo0x** [offensive-security/kali-nethunter#175]
Hi guys i was wondering if there is a way to hide/minimize the cmd windows on target? it remains open like this: http://i61.tinypic.com/2q89304.png
i would like to minimize it like Kautilya style... Any ideas?

**Comment by yo0x** [comment]
??????????????/

**Comment by offensive-security** [comment]
!!!!!!!
