### ISSUE TITLE
"NEXUS10" post for Nethunter Issues

### ISSUE THREAD

**Issue by cr1p70** [offensive-security/kali-nethunter#176]
I thought i would open new thread just for NEXUS10 everything i'm finding is for nexus 7, Now if there are no differences between N7 an N10 then i will just follow the stuff im finding for N7 and apply it to N10 if not then.
_____________
Here is what is happening to me on 
Nexus 10 
android 4.4.4
Fresh install of Nethunter 
used wuggs tool kit to unlock and root 
then kalinethunter nexus10 Windows installer to install ,but i skipped  the unlock as i was already unlocked did everything else 
followed all it said do and installed fine seems to work fine till i start trying to use nethunter tools

Nethunter has unfortunately stopped working,and will just keep saying that tll i reboot.

OR

if i start ssh and metasploit via gui menu
then run metasploit it may or may not load if it does load it will freeze my nexus either go black and reboot or i have to reboot.

wifite will not load via terminal menu,but will load and find wifi card via gui menu.

i can vnc to a kali desktop run armitage but it to will soon freeze and have to reboot 

kismit works,wifite works,most of the tools work NP im not sure if tcpdump is working it just pops up then gone instinly same for all tools in that menu.

info tools all work spiderfoot ,recon.ect

opvas don't work.

set tool kit works but did freeze once

not sure if beef is working right.

have tried open vpn yet.

and if i go to settings then create metasploit user and database, only thing i can type is exit and it starts setting up user exit ,password exit, database exit,  weird as hell.

here are then newest crash logs. , Pastebin

crashlog6 http://pastebin.com/raw.php?i=FB3BUKpc

crashlog7 http://pastebin.com/raw.php?i=d6bjFm82
 
here is video of what its doing

https://videobin.org/+8lg/bge.ogg
https://videobin.org/+8lg/bgf.ogg

ohh its upside down some not  lol but it still show whats up.

hope this was ok to post.

**Comment by cr1p70** [comment]
New Crash and log found errors  here is log:
http://pastebin.com/raw.php?i=AgFgjxVy

**Comment by cr1p70** [comment]
i cannot set RAM to 468435456 from 268435456 in /system/bin/bootkali ,Ive tried changing file permission's,i've tied opening it like this  cd /system/bin, nano bootkali 
I can edit the file just cant save the file, always says file is  read-only tried with su nano, sudo su nano tried vi cant save the file.. was trying to follow your directions from another post about RAM but just cant seem to get it out of read-only so i can edit an save it with new ram specs.

i will keep trying.

**Comment by binkybear** [comment]
```
su
mount -o remount,rw /system /system
```
This will allow you to edit bootkali by making /system writeable.

**Comment by cr1p70** [comment]
thx binky i wasn't sure if  i need to mount.

**Comment by binkybear** [comment]
cr1p70 - Does the screen go black or does it reboot?  If the screen goes black it might be a terminal issue. 

Also, I can try turning on swapping for you and we can test if that would work.  Would you be willing to try a new kernel?

**Comment by binkybear** [comment]
Let me update, I just checked the Nexus 10 and swapping is on.  So it's possible to add a swap file

**Comment by cr1p70** [comment]
OH yes most defiantly will try,i'm very baffled as to why this is happening so anything to solve it ill help out.

**Comment by cr1p70** [comment]
UPDATE: Ok i put a swap file of 1gb, and were off so far so good no crash as of yet Binky. 
i will run if for a few see how it gos then ill post up little tut on how i fix, so give me hr or so..

And always much appreciated help bro.

**Comment by cr1p70** [comment]
FIX METASPLOIT CRASHING NEXUS10
How to fix metasploit crashing on nexus 10

#1-First off we follow these directions from  http://www.nethunter.com/ 
to unlock/root/install Kali Nethunter to our Nexus 10.

Install With windows installer
#2-Open installer follow directions ,Now we install Google drivers once installed properly 
& you turn USB debugging "ON"  Hit "about tablet,hit build number 7 times, go back open developer options check USB Debugging is ON if not check the box and a box will pop up on tablet just check that box.

#3-Now go and cut  "MTU OFF", on your Nexus10 go to Settings ,storage ,upper right hand corner 3 little dots click them "uncheck MTU" 

Make Sure DRIVERS install correctly an USB Debugging ON,an MTU OFF  
![youre-going-to-have-a-bad-time-54b187940239e](https://cloud.githubusercontent.com/assets/11143603/6429601/96deac64-bfab-11e4-839d-baf5bc8ea267.png) quoteing  another forum user shit was funny but true!!
Now your  Install will go smooth .


#4-so with that out the way we Hit Next and Follow the rest of the directions in the Installer, if you have all ready unlocked your nexus10 then you can skip that part,
Once you Have Kali Installed,Reboot.

#5-Now  its time to Update,Start postgresql First before updating because of metasploit,
 "Service postgresql start" then you can apt-get update && apt-get upgrade && apt-get dist-upgrade
and chroot update kali 

#6-OK, so that's done. now to get Metasploit and other Ram intensive Tool's to run properly we need to make a swap Partition on our Nexus10,
 
we open terminal type "Su" without quotes that will put us in a ADB Shell root@manta: we don't want that,
so type "bootkali" an it will put us in a Kali shell,, root@kali if it don't say root@kali you need to reboot and do it again or it wont work.

#7-Ok Swap file is recommended to be stored in /var and we will call it : “swapnethunter.img”, also we must set file permissions to 600 so none of the other users could use or read the file, this can cause problems to the system memory. Write following commands:

root@kali:/# cd /var
root@kali:/var# touch swapnethunter.img
root@kali:/var# chmod 600 swapnethunter.img

Step 3. Set size for the Swap file

Now you should set Swap size , Swap can be set to 1Gb, if you have 1Gb of Ram, swap can be set to 2Gb,1Gb of swap, should be enough RAM.

Now we will fill the swap file with some size,and we will fill it with 1Gb of memory, follow the commands:

root@kali:/var# dd if=/dev/zero of=/var/swapnethunter.img bs=1024k count=1000
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB) copied, 4.0868896 s, 287 MB/s

After command, we will have to wait a minute, and we will get the results that bytes have been copied and at what speed rate.

Step 4. Initialize Swap filesystem

Follow the commands:

root@kali:/var# mkswap /var/swapnethunter.img

"CODE"Setting up swapspace version 1, size = 1020 GiB
no label, UUID=72761533-4bbe-316g-v02e-c0ssbe4cfdf2"/CODE"

If you got similar result, it means that swap was initialized.

Step 5. Enable Swap

To enable swap we will have just to turn it on, to check if it’s enabled type "free" 
root@kali:/var# swapon /var/swapnethunter.img

Now you will have to type that last command in, each and every boot till i can figure out how to auto run it for your swap file to be activated on each boot. .


Now Metasploit and few other things that had problems will work as they should without crashing,

You can also read above  to be able to change the ram specs on nexus10 from 268 to 468 if you need to,
so far i changed to and have left as 468 and no problems.

any problems just post up here i'm no guru but i will do my best to help out...


Much Respect and Thanks gos out to Binkybear for the Help in Resolving this issue
 .

**Comment by binkybear** [comment]
cr1p70 - Thanks for doing that write up.  The problem, as far as I can tell, seems limited to N7 2012 and the N10 based on your description.  I'm not sure if this something we will need to include a swap install in the setup process, but for the future this is a great reference and helpful post.

Thanks for your tireless testing.  I'm going to close this issue but feel free to let me know if you run into any more issues.

**Comment by cr1p70** [comment]
Thanks for that and ok N7 2012 an N10's ok i'll check it out on n7 2012 also it just arrived in mail.
I'm about to buy a n7 2013 4g model so ill give them both a look see. thx again Binky

**Comment by cr1p70** [comment]
Thanks Binky ..

**Comment by zvanderbilt** [comment]
Im having a problem running out of memory on my nexus 5. I was trying the above fix, but I get an error at swapon which basically says the function is not implemented. Is it just a matter of kernel support for the different devices?

**Comment by binkybear** [comment]
@zvanderbilt - I just need to build a kernel with swap enabled but you would have to do the steps above to generate a swap image.  The previous builds did not have swap enabled.

Which version of android are you using? 4.4.4 or 5+

**Comment by zvanderbilt** [comment]
That would be awesome. I am using 5.1.1.
