### ISSUE TITLE
Wifite captures aren't saved

### ISSUE THREAD

**Issue by ferby09** [offensive-security/kali-nethunter#178]
Nexus 7 2013
Stock 4.4.4 with latest Nethunter

Normally I'm using Wifite directly from the Kali Launcher. I already captured my handshake but I'm not able to find it anywhere.
When I use the save capture to SD feature in the Kali Menu, it creates some folders in the kali-nh directory but no files! I already looked into every damn folder on my Nexus.
When I try to capture again, it says that there is already a file for that network.
I executed Wifite from the shell and it didn't tell that there is already file. But I captured one then and now it's the same like Wifite from the Kali Launcher. So it seems like they are not connected.
Anyways the export from the Kali Menu still doesn't work.
I already updated chroot.

**Comment by jmingov** [comment]
I guess you found it but for the record, the nethunter wifite captures are saved in 
`/data/local/kali-armhf/hs/`

**Comment by ferby09** [comment]
I got another solution for it...
If I look in the folder mentioned by you, I won't even find the local folder.
But my solution is:
Start wifite only via kali shell (just type wifite)
After you got your handshake it is saved in the /hs directory but you won't find it.
Type cp -r hs /sdcard/Download
Now you should see a hs folder in your Download directory.
But if you connect your device to your pc, you might not see this folder.
Just copy the files in it to the root of your Download folder and you should be able to see them.
