### ISSUE TITLE
HID Keyboard attack fails with german layout

### ISSUE THREAD

**Issue by biejay** [offensive-security/kali-nethunter#18]
The attack itselfs starts and sends commands to the cmd shell, but instead of an '-' it is written a ß. I'm not quite sure if there are more letters wrong, but i noticed this one. Hope you are able to fix it soon :)
![unbenannt](https://cloud.githubusercontent.com/assets/8942784/4432580/a86bd75e-469d-11e4-9b50-57533c3b096d.JPG)

**Comment by TheNain38** [comment]
Is it fixed?

**Comment by jmingov** [comment]
No idea, we want native users to fix each lang, so we are sure the fixes are correct.

 By default we only added US ENG.
