### ISSUE TITLE
Nexus 4 Memory size inaccuarcy after flash

### ISSUE THREAD

**Issue by sinistermachine** [offensive-security/kali-nethunter#180]
After installation memory isn't correct, it thinks its got 8gb instead of 16gb.... thought I saw something the other day on the issue but now I cant find it. Any ideas on a fix?

**Comment by Skycrazy** [comment]
Check out issue 36, hope this helps

**Comment by binkybear** [comment]
Like skycrazy mentioned, also:

https://project500.squarespace.com/journal/2015/2/15/nethunter-nexus-storage-issue

**Comment by sinistermachine** [comment]
Sweet. Thanx

**Comment by sinistermachine** [comment]
So basically wingin it.....eventually it'll smartn up...   ?   If so excellent.. those be the exact articles I was lookin for
