### ISSUE TITLE
Buttons in nethunter menu not working in nexus 7

### ISSUE THREAD

**Issue by peterpt** [offensive-security/kali-nethunter#181]
the buttons from my nethunter do not work !!!
Shell button does not start bootkali automaticaly
kalimenu does not open 
wifite does not open
update kali chroot not working also .

I can get aroud this issue by starting a terminal session and writing 
su root
bootkali

and then after this point i can work normally inside kali system , i can also start the kalimenu from terminal by writing "kalimenu"

Is there a way to fix this bug by using apt or any other think ?

This happened after i apply "apt-get autoremove" because when i was making an update i notice that kali was telling that there was packages that were no longer needed .

**Comment by FliiFe** [comment]
Try doing that :
* Boot kali
* Run `cat /var/log/apt/history.log`
* Look at what was deleted
* Re-install packages via `apt-get install`

:+1:

**Comment by peterpt** [comment]
I was looking into the logs and i did not found the apt-get autoremove command !!!
and then i was going to take some screen captures of what was going on , so people here have an idea .
I use remote desktop app that creates a webserver and i can remotely get access thru my network to tablet explorer , i can take screen caps , view camera , etc ....
When i connected thru rdesktop i realize that the program was telling me that i have a root device but i was unable to see the screen captures that i was making !!!
So , i remembered that my tablet have SU app but it is the one that arrives with cyanogen mod ROM , and i never give the time to install the SU 2.46 that take over the original device SU app .
I install it , and then when i was going to take the screenshot of the terminal in kali i realize that everything was already fixed !!!
Everything is working now without a single touch in config !!!
When i installed the first time kali , everything worked fine until a few days ago .

Anyway , i gave the trouble to write all the story behind this issue just to let know everyone that may have the same issue in future that sometimes to fix the problems is more easy than we all think .

Thank for the reply , you reply toke me to another direction and then without knowing i fixed the issue .

**Comment by binkybear** [comment]
Glad you were able to fix the issue.
