### ISSUE TITLE
Oneplus OTG not working

### ISSUE THREAD

**Issue by cr1p70** [offensive-security/kali-nethunter#182]
model:A0001, cyanogen OS 11.0 xnph05q, android 4.4.4, kernel version 3.4.104,  build: KTU84Q brand new out the box 1+1 no upgrades, fresh kali install everything works great  except: 

The OTG  is not working on my 1+ i just bought, It either detects the external battery and charges and disregards my TP-Link USB , or it detects my TP-link USB  but doesn't charge, there is no both. Even if you put in the cables in the correct order, it only charges or powers the TP-link  

I Have to sets of cables get same results wit both.

Ive been reading up much as i can but nothing is been a solid hit on what i can do to remedy,
![img_20150321_162343](https://cloud.githubusercontent.com/assets/11143603/6766690/ddee082a-cfe6-11e4-888b-695d6a85e964.jpg)

**Comment by binkybear** [comment]
Y-cable is not working as of now for Oneplus.  That may change in the future if I can ever get it working.

It should work on a direct otg connection though.

**Comment by cr1p70** [comment]
ohh ok binky thanks, and yes it works directly one or the other just not at same time..

**Comment by binkybear** [comment]
The oneplus uses a different battery than the other devices in the way it handles OTG so there's been some problems getting it working.  But if there is an update I will let you know.

**Comment by cr1p70** [comment]
sweet thx binky.

**Comment by binkybear** [comment]
@cr1p70 
If you are comfortable I made a new kernel for kitkat oneplus one.

If you would like to try y-cable, I believe I have it semi-working.  It seems to keep the charge but doesn't gain any battery:

https://transfer.sh/TPIwS/kernel-kali-oneplus11.zip

Any testing is appreciated.

**Comment by palmerit** [comment]
binkybear,

This is awesome.   Is there any concern about which ROM's it'd work with?

I'd be interested in which commit enabled this, as I'd like totry getting
it into my OPO running lollipop.  (I'm more interested in the Y cable
keeping the phones battery draining, than anything else.)


On Wed, Apr 8, 2015 at 5:17 PM, binkybear <notifications@github.com> wrote:

> @cr1p70 <https://github.com/cr1p70>
> If you are comfortable I made a new kernel for kitkat oneplus one.
>
> If you would like to try y-cable, I believe I have it semi-working. It
> seems to keep the charge but doesn't gain any battery:
>
> https://transfer.sh/TPIwS/kernel-kali-oneplus11.zip
>
> Any testing is appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/182#issuecomment-91039539>
> .
>



-- 
Jeff Palmer
https://PalmerIT.net

**Comment by binkybear** [comment]
Hey jpalmer,

The commits were: 
https://github.com/binkybear/AK-OnePone/commit/303bd9ba7c09f03af01f2f0f7a5d3a11c1e965f0
https://github.com/binkybear/AK-OnePone/commit/238612148879172402fe8d0415eac18d7dd99cbf

It should work with any OnePlus 4.4.4 ROM that I'm aware of.  The 4.4.4 kernel was based on [Ak Kernel](http://forum.xda-developers.com/oneplus-one/orig-development/kernel-ak-t2832168).

As always though, in recovery make a backup of boot to backup kernel.

**Comment by cr1p70** [comment]
i will give it a try and see what happens..

**Comment by cr1p70** [comment]
well so far i'm not able to get it working with the new kernel Binky, could be the OTG cables i'm using idk. ill keep trying if you can think of anything let me know.

im still stock by the way not lollipop just as it was up packaged only thing did was install Nethunter.. 
anyway will continue to test.

**Comment by cr1p70** [comment]
So far i don't have it working Binky idk what it could be if you have it
working can send me the type of otg your using and ill go pick one up.

**Comment by binkybear** [comment]
No worries @cr1p70. I will keep working on the kernel and post updates.

**Comment by cr1p70** [comment]
ok cool thx bro.
