### ISSUE TITLE
OnePlus 64gb 'Bacon' No Logcat

### ISSUE THREAD

**Issue by evict** [offensive-security/kali-nethunter#184]
After installing Kali Nethunter on the Stock Rom, logcat does not seem to work.
I reflashed the stock rom, tried logcat and it worked. After that, I flashed kali nethunter and logcat again, shows no output.

OnePlus 64GB

**Comment by binkybear** [comment]
Logcat doesn't work from adb/terminal or both?

**Comment by evict** [comment]
Doesn't work from both. When I look at the logfiles:

130|root@A0001:/dev/log # ls -l
crw-rw-rw- root     log       10,  38 1970-02-10 17:28 events
crw-rw-rw- root     log       10,  39 1970-02-10 17:28 main
crw-rw-rw- root     log       10,  37 1970-02-10 17:28 radio
crw-rw-rw- root     log       10,  36 1970-02-10 17:28 system

1|root@A0001:/dev/log # stat system
  File: system
  Size: 0         	Blocks: 0          IO Block: 4096   character special file
Device: bh/11d	Inode: 8350        Links: 1     Device type: a,24
Access: (0666/crw-rw-rw-)  Uid: (    0/ UNKNOWN)   Gid: ( 1007/ UNKNOWN)
Access: 1970-02-10 16:28:16.000000000
Modify: 1970-02-10 16:28:16.000000000
Change: 1970-02-10 16:28:16.000000000

So it seems to that the logfiles are empty?
