### ISSUE TITLE
Tab completion not working in VNC

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#188]
When I open terminal emulator on VNC, there is no tab completion. However, when I SSH in with my application JuiceSSH, tab completion is normal and works fine.

**Comment by thedroidgeek** [comment]
That's because it's being used by XFCE as window switch key.
This should do: http://askubuntu.com/a/584846

**Comment by binkybear** [comment]
Thanks for the response @thedroidgeek.  This doesn't seem to be a nethunter issue so I will close.

**Comment by DrDinosaur** [comment]
This works perfectly in bVNC with my Bluetooth keyboard, but not so well
with androidVNC (installed by default?). For androidVNC, I have to "send"
the TAB key within the application; it won't work normally with the
keyboard like bVNC.
