### ISSUE TITLE
HID attack loses session 

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#189]
The HID attack works well for the most part, but it has one major issue. You get the shell and can interact with it well, but the command prompt is still open (http://gyazo.com/c6e45dfe97f1a2d4c373200d36b2a023). If you close it, you lose the ability to interact with your session. That should finish and close automatically, so you still have your shell when the prompt is gone.

**Comment by DrDinosaur** [comment]
A workaround could be to have "set autorunscript migrate -f" or something similar to spawn a new process. This seemed to work even after I closed the window, but it was also the first time the attack actually finished and gave the prompt with the directory (file path) again, so I don't know if that would also suffice.

**Comment by thesle3p** [comment]
If you pass nethunter a URL with  metrpreter served by multi/script/web_delivery it will do what you want. It also is more stable  and flexibleon 8.1 then powersploit.
