### ISSUE TITLE
Alfa AWUS036H not being identified 

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#191]
I plugged in the Alfa with USB. A USB Device Info app identifies the correct device is plugged in. I went to the Kali menu and selected Wireless Attacks. It says the wlan1 was found. However, it doesn't appear in ifconfig or iwconfig. When I try to use airmon-ng (or the Monitor Mode option in the menu) to bring it in monitor mode, it can't find wlan1. When you unplug it, the tablet reboots, even after selecting "Eject USB Wifi."

**Comment by binkybear** [comment]
Which device is this?

**Comment by DrDinosaur** [comment]
Nexus 7 2013 Wi-Fi Lollipop and latest NetHunter.

**Comment by binkybear** [comment]
Thank you, another individual was having issues with the N6 also.  I will need to purchase a 36H to test.

**Comment by Untide** [comment]
Same issue (interface doesn't show up in ifconfig) on Nexus 9 as well. Same model alfa.

**Comment by binkybear** [comment]
So the device is working for you now?

**Comment by Untide** [comment]
I jumped the gun for that last comment, it goes up and then goes back down after about 30ish seconds. Ordered a few other adapters to see if it's just the alfa. Also probably will mess with the power settings for the alfa, I have no idea how much power the nexus 9 can put out through OTG.

**Comment by midlo** [comment]
I am having similar issues as above. While I am not seeing errors when I run Wifite, it does not recognize any WIFI adapters connected through the OTG cable. I can bring them up and down through a terminal via ifconfig as wlan 0 or 1 (shows as wlan0 if connected before boot and wlan1 if connected after). iwconfig will only recognize the internal wifi adapter, which I thought was interesting. Airmon-ng does not see them either. I have tried the following wifi adapters with multiple otg cables:

TL-WN821N
SMCWUSB-N2
WNA1000
AWUS036H

I am running a Nexus 7 2013 WIFI with 5.02 operating system and 1.2 nethunter. One thing that I should note is the root methods described on the website did not work. I was able to unlock the boot loader, but the final step would not root the phone. TWRP would load up and show a bunch of mount errors. It seems that several people with this device had the same issues and ultimately used a different image loaded through the ADB terminal to get it up before installing nethunter from a zip. Could be nothing, or could be part of the problem with the wifi cards. Also, the Nexus reboots when the wifi adapter is removed, regardless of it's ifconfig state. Bringing it down (ifconfig wlan1 down) first does not matter. I did notice that the android will bring it back up and connect to saved networks with it even after I brought it down with ifconfig.

Nethunter is a great product. Hopefully we'll figure out how to get wifi working with the Nexus 7 2013. It's the perfect size and speed for this platform. Looking forward to using it on wfi audits.

-midlo

**Comment by binkybear** [comment]
Hi @midlo 

First off on the mount errors:
I did help out an individual with the mount errors.  It seems it only pertains to certain models of the Nexus 7 (2013) and you were lucky enough to have that one?  Either way, what fixed it for this individual was installing an older version of TWRP:

http://forum.xda-developers.com/showpost.php?p=59771335&postcount=28

Secondly on the wifi:

I'm a bit confused because you said you can bring up wlan1 so it is seeing the device.  The problem is monitor mode isn't working?

**Comment by midlo** [comment]
Thanks for the relpy binkybear.  I  was abled to get the wifi working in monitor mode (you are correct, ifconfig would bring it up, but iwconfig did not see it as wifi and airmon-ng).  I updated and played and did "stuff" and was able to get wlan1 up and in monitor mode from the command line.  It now comes up as 'wlan1mon'.  Wierd.  Also, it appears to stop monitoring after several (10-15) minutes of running airodump-ng and still is not recognized by WIFITE.  I'll reflash with your instructions and see if it makes a difference.  I really like the Nexus 7 for this application, I hope I can work out it's issues

**Comment by binkybear** [comment]
@midlo - wlan1mon is the new naming scheme from airmon-ng. You can see the Kali blog for update:
https://www.kali.org/penetration-testing/pixiewps-reaver-aircrack-ng-updates/

I found that putting the device into monitor mode first then starting wifite yields better results.  I'm unsure why it would stop monitoring after several minutes though.
