### ISSUE TITLE
OpenVPN not routing correctly

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#192]
I'm trying to use OpenVPN to route traffic so the external address differs from the actual address. I connect and it works well for the most part. However, the external address did not change. I see that it complains it cannot redirect the default gateway because it can't find the current default gateway. This is correct as route shows there is no default gateway. I add the local router as the default gateway and try again. The error is gone, and the default gateway for the VPN is now added (on top of the default gateway for the local router), but the external address still has not changed. I remove the default gateway of the local router (so now the default gateway is of the VPN), but the external address still has not changed. It works fine on a normal computer, so I think something is weird with NetHunter's networking.

**Comment by offensive-security** [comment]
I assume you're talking about lollipop, which now implements policy based routing. This is probably what's throwing you off as it is very different from the routing commands used in Kitkat. This is not a bug though.

**Comment by DrDinosaur** [comment]
Hmm, I didn't know that. How can accomplish it then? Any resources? Quick search couldn't find anything.

**Comment by offensive-security** [comment]
None that I know of...other than reading up on policy based routing. Another reason we're still sticking with our Kitkat builds internally.

**Comment by DrDinosaur** [comment]
Ah, bummer.
