### ISSUE TITLE
beef-xss implement in nethunter home

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#195]
When I use beef, I always have to change the metasploit config ip value, that's the reason I want to 
let you know that I lost a lot of time doing that.
I have an idea to implement configuration options in the application to save time like mana-toolkit, etc.

An other idea is that someone can change the services (add, remove) according as I want.
I.e: If I want to add postgresql to save time with metasploit, add mysql to save time with apache or
remove openvpn, becouse I don't use it.

I think that I am not the only one with those limitations in the aplication.

**Comment by binkybear** [comment]
Are you saying that the IP is not saving in config.yaml for beef (msf_callback_host)?  Or you need to change the IP a lot and you want to be able to change it through the app?

I see what you are saying about allowing people to add/remove services from app and I think that would be a long term enhancement.

**Comment by vay3t** [comment]
I haven't problems, all very stable, I like that. it's just a quick idea pentesting. if possible I will help in the development

**Comment by vay3t** [comment]
i have no problem. all the application is stable, i like that it was an idea. if it possible i can helping you to make that change in the application. i think that would be more interesting . my preference is beef

**Comment by jmingov** [comment]
All this can be done now via Custom Commands.
