### ISSUE TITLE
Start services on boot

### ISSUE THREAD

**Issue by glennzw** [offensive-security/kali-nethunter#197]
_Feature Request_

It'd be useful to run services on boot, e.g apache2, cron, ssh. The following usual approach doesn't work:

```
update-rc.d apache2 enable
```

**Comment by binkybear** [comment]
Just to update anyone who might read this, we discussed a little bit on freenode.

One way to do it is to modify a userinit.sh file located in /data/local.  

@jmingov stated he would look into adding something into the app in the future.

**Comment by glennzw** [comment]
Hi all - just wondering if there was any progress on this? Thanks!

**Comment by binkybear** [comment]
@glennzw - There was some progress on this from the app side. @fat-tire was able to integrate a startup /etc/init.d from the app: https://github.com/offensive-security/nethunter-app/commit/d0b9355369eeaf9d242023f3a4c5c6d5ef925d34

The app from the fattire branch will have a lot of changes to the way things are installed and handled so I pushed it into a new branch.  But we will eventually merge the changes into the new branch when we can test it more.

**Comment by zenware** [comment]
It would actually be kind of awesome if it used systemd instead of SysVInit, but that's like a whole different game.

**Comment by jmingov** [comment]
Is added in Nethunter app >> Custom Commands
