### ISSUE TITLE
Nexus 5 infinite loop

### ISSUE THREAD

**Issue by smtbrn** [offensive-security/kali-nethunter#199]
Hi, I just installed nethunter on my Nexus 5, everything was fine but when I finish the installation the phone go into infinite reboot cycle.
As I can solve the problem? thanks

**Comment by binkybear** [comment]
Sounds like there was an issue with kernel installation.  Have you tried reinstalling?  It's possible to maybe just flash a kernel over to quickly fix.  I can walk you through it if you like.  Are you using lollipop?

**Comment by smtbrn** [comment]
Hi thanks for your answer. The error was because I was confused and install the kitkat version . I resolved the problem by reinstalling the version lollipop and everything worked properly.
