### ISSUE TITLE
Nexus 7 2012 WiFi Bricked at Step 6

### ISSUE THREAD

**Issue by sous-studio** [offensive-security/kali-nethunter#200]
Hey!

I have Nexus 7 2012 WiFi Lollipop 5.1.x. Was going through nethunter, all steps up to 6th. Thne, suddenly 
![2015-04-24 01_49_20-administrator_ offensive security - stock android flash script](https://cloud.githubusercontent.com/assets/6961500/7309542/809fcf80-ea28-11e4-8c9c-2713630e59ca.jpg)
fastbooting stopped at waiting for device; Nexus 7's screen got black, windows notified me that device is disconnected. I waited 30 mins - nothing. Tried unplugging, rebooting, booting with Power+VolDown - nothing.

Bricked, right? Any way to unbrick it?

**Comment by sous-studio** [comment]
Update: Windows says USB device is malfunctioning. Tried opening Nexus 7, detaching and reattaching battery; booting - nothing, black screen.

Note: Before I started the procedures (installing Nethunter), battery was at 98%, so guess it wasn't an issue.

**Comment by binkybear** [comment]
Did you do a Nethunter build yourself or did you use the installer?  The reason I ask is because no version has been released yet for lollipop on n7 2012.  I've been working on a new build that is working on 5.1 but requires a manual installation.

You can always unbrick.  If you can get into fastboot/recovery you can reflash.  I would recommend using wugfresh toolkit if you are unfamiliar.

**Comment by sous-studio** [comment]
I used the installer. Never realized it is not compatible with lollipop 5.1 (after all, why would it be, if its flashes the device with kitkat anyway?).

How do I unbrick? I've got wugfresh, but the thing is I cannot turn on my Nexus 7. It's black screen. Any clue on how to see the light? =)

**Comment by binkybear** [comment]
A black screen might be a lack of power.  To get into fast boot you have to hold down power and volume down button at same time.

**Comment by sous-studio** [comment]
It doesn't work, I know, I've tried.

As for power - could it be that in 6 steps of processing it got from 98% to 0? I doubt.

Any other ideas?

**Comment by binkybear** [comment]
I had something similar with the Nexus 9 where I thought it was off but it was sitting at a black screen for a good while.  In my case I wasn't using the right wall charger to get the power back where it needed to be.

Have you tried different outlets/cables to see if it changes anything when powering on?  Sometimes having it plugged into wall then trying power/volume.

I agree it's not likely it went from 98 to 0 instantly.

**Comment by sous-studio** [comment]
I am trying... brought a new charger today. Tested to no results. Trying other sockets too.

Actually, talked to repair guy today, he told me he can recover it and cheaply, but I still do want to install NetHunter without getting bricked again, so I'd prefer to somehow unbrick it on my own...

Well, anyway, thanks for advices! Will try some other charger and sockets...

**Comment by sous-studio** [comment]
Damn, local repair folks told me "bricked to the end, only way is to replace motherboard, and only in authorized service".

Is there some JTag or similar thing I could try in-house?

**Comment by Skycrazy** [comment]
Had the same issue nexus 2013 a while a go, i tried multiple chargers. Only 1 would actually charge and power it up. The ones that didnt charge the nexus would be fine on other devices.  The one that came with the nexus was one of the ones that wouldnt charge up from a completely drained battery. To confuse even more when the nexus was on, all the chargers would charge the nexus fine. Kinda like jump starting your car. ;-)

**Comment by 0E800** [comment]
Just wanted to make sure that you already tested:

1) Keep N7 plugged into computer usb port, press and hold power (30+
seconds)
    - Hold power + vol keys (30+) seconds

2) Keep N7 plugged into usb-power adapter, press and hold power (30+
seconds)
   - Hold power + vol keys (30+) seconds

Hold N7 at an angle so you can tell when the screen flickers IE: power is
getting to it.

I have a few busted up N7's and have noticed a full battery drop to 0% and
still be running. You cant always rely on what the phone thinks its battery
status is. A N7 left with 0 battery for period of weeks to months takes
alot longer to charge.

I have other google os devices that also show inaccurate battery status.

Keep at it.

On Tue, Apr 28, 2015 at 3:12 AM, Skycrazy <notifications@github.com> wrote:

> Had the same issue nexus 2013 a while a go, i tried multiple chargers.
> Only 1 would actually charge and power it up. The ones that didnt charge
> the nexus would be fine on other devices. The one that came with the nexus
> was one of the ones that wouldnt charge up from a completely drained
> battery. To confuse even more when the nexus was on, all the chargers would
> charge the nexus fine. Kinda like jump starting your car. ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/200#issuecomment-97001638>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by sous-studio** [comment]
@Skycrazy , yes, I had this problem with my tablet sometimes becoming uncharable with perfectly fine chargers, and then becoming normal again. Unfortunately, I cannot try lots of chargers.

@0E800, I will keep trying, but actually, to my understanding it failed during flash process, so it might be that bootloader is corrupted. Is there somewhy perhaps to overwrite bootloader the low-level way? Some pins on the board? That seems logical and last resort aswell.

**Comment by 0E800** [comment]
Its funny. I had almost given up on one of the N7's I had. Trust me, I had
kept it plugged in over night to ac/usb adapter and all it would do is
barely flicker the screen when I pushed and held power button. It was this
thread that made me try again, and sure enough after about an hour of it
'charging' (there was no charge indicator) while it was flickering and then
another hour of charging after the flickering stopped, I was able to get it
to boot to twrp.

IMO your N7 battery is so depleted that it cant even display the battery
icon when it does its initial charging while the device is off. I would
suggest using the original asus charger. Just keep it plugged in, keep
trying to power it on while press and holding power + vol down for 30+
seconds. Eventually it will power on. Then you will be able to fix the boot.

On Thu, Apr 30, 2015 at 12:59 PM, Svyatoslav Alexandrovich <
notifications@github.com> wrote:

> @Skycrazy <https://github.com/Skycrazy> , yes, I had this problem with my
> tablet sometimes becoming uncharable with perfectly fine chargers, and then
> becoming normal again. Unfortunately, I cannot try lots of chargers.
>
> @0E800 <https://github.com/0E800>, I will keep trying, but actually, to
> my understanding it failed during flash process, so it might be that
> bootloader is corrupted. Is there somewhy perhaps to overwrite bootloader
> the low-level way? Some pins on the board? That seems logical and last
> resort aswell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/200#issuecomment-97950739>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by sous-studio** [comment]
@0E800 Used multimeter on battery. It says 3.7V and 3.5V (inner and outer pins respectively). So, to my understanding (and my poor electrical knowledges), it is charged? So the battery is not a problem, right?

What else could it be?

**Comment by 0E800** [comment]
First, when you have the N7 plugged into the power-adapter and press and
hold the power button plus the volume down key (aprox 30 seconds), do you
notice the screen flicker? Like its trying to power on but isnt?

If not, keep the N7 plugged in over night and try powering it on in the
morning.

Then plug it into a computer and try powering it on (hold power for 30
seconds)

Look for a flicker in the screen. If you notice the flicker, that means its
doesnt have a good enough charge and is a good sign; its trying to work.

Like i said earlier, I gave up on it, but then all of a sudden today I had
success. I have had the device now charging for well over 5 hours and its
still not fully charged. So really, keep that sucker plugged in. Dont give
up, its just being fickle.

On Thu, Apr 30, 2015 at 4:51 PM, Svyatoslav Alexandrovich <
notifications@github.com> wrote:

> @0E800 <https://github.com/0E800> Used multimeter on battery. It says
> 3.7V and 3.5V (inner and outer pins respectively). So, to my understanding
> (and my poor electrical knowledges), it is charged? So the battery is not a
> problem, right?
>
> What else could it be?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/200#issuecomment-98003770>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by sous-studio** [comment]
@0E800 So, that multimeter shows on the battery 3.7V and 3.5V doesn't mean it's charged?

If the charge is the only problem (which I have doubts now of), I'd go ahead and try to jump start the battery:
http://www.youtube.com/watch?v=I-pjLIVIslI

**Comment by 0E800** [comment]
I am fairly certain that was the issue with mine. However I was able to
achieve the same effect without having to open the device. I read about
other people putting their device away for a week and coming back to it
later after the battery fully discharged and having the device power on
normally after it was plugged in. Just keep at it.

**Comment by iw0k3upd34d** [comment]
Same here in terms of the device. The USB recognition is in an infinite loop. That includes access to charging, recovery, bootloader and adb. Glad to see I'm not the only one. Luckily I had another nexus seven that I bought damaged for parts. It pretty much screwed the logic board so I swapped them and no issues at all. The logic board I swapped  into the "shell/housing" wasn't modified with net hunter BTW. So I'm leaning towards this being an issue with the ROM. Hopefully this gets resolved because not everyone has spare parts laying around in the event of a hardbrick.

**Comment by TheBlackRabbit** [comment]
ive encountered this issue myself multiple times. you simply need to kill the adb server by opening a terminal and typing adb devices -l then it should find the old server to be out of date kill it, then respawn a new adbd/adb server.

However... Try pressing the space bar to exit the dos prompt after it fastboot flashes stock i many times have found that it tends to hold back the fastboot reboot command until you exit the cmd prompt ()to ensure instructions are understood?

Your not hard bricked, No one "logic board" (MB?)  is fouled and trust me it is VERY difficult to brick a nexus 9 and its nothing that cant be fixed fairly easily.

BTW if your flashing to a oneplus checkout the new oneplus bacon toolkit from wugfresh. NRT just for bacon =)

happy flashing

**Comment by iw0k3upd34d** [comment]
However difficult it may be it happens. Several people above stated the exact same issues. There isn't a way to access adb fastboot recovery. Like I said stuck in an infinite loop without charge or recognition through.  It may not be totally hardbricked but its really frustrating. I also attempted switching the USB components & batteries to the board and nothing. Its all good though, I'm up and running on PA again. I just hope this doesn't continue to happen.

**Comment by sous-studio** [comment]
@iw0k3upd34d, yes, exactly like you described. It seems bricked, it's not being recognized, it doesn't seem to charge at all, and most likely need some hardware replacement (in repair store, they said to me the only way is to go to official repair, since ROM chip replacement is necessary).

@TheBlackRabbit I have Nexus 7, not 9. I hardly use Windows anymore, so no dos prompt. Last time I hooked it up there, it said to me just "USB Device not recognized: One of the devices attached to this computer has malfunctioned and windows does not recognize it.". Killing or not killing adb doesn't make difference now. Maybe if I saw your advice the day it got bricked, there would be a chance, although I doubt, because it "died" in the process.

**Comment by TheBlackRabbit** [comment]
Most def hardware, to make sure it isn't totally dead batt/MB wise; let the
batt drain out. 2 days maybe 3. Then charge, should get a white blinking
(1-2s interval) under your screen indicating charge of a depleted batt (vs
just "0%") rules out some issues.

BTW I own a N7 as well, almost died on me too, new usb and lcd and she's
still kickin'

Good luck man, odds are in your favor

**Comment by sous-studio** [comment]
@TheBlackRabbit Done that for much longer time, nothing. If the problem is ROM, would be nice to know some lowlevel way of reflashing it. I don't know, maybe connecting it by pins to something like Raspberry PI and repogramming it. If only I knew how... that would be last try, though, because if it doesn't help, that means repairman was right and the problem is with CPU or MB, in which case only physical replacement can change the situation.
