### ISSUE TITLE
nethunter HID attack open failed EACCES(permission denied) error when setting powersploit url on lolipop 5.0 nethunter 2.21

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#201]
when trying to set the powersploit url for the  HID attack with the update button I repeadidly across multiple flashes get a  "open failed EACCES(permission denied)" error and the url is not set and the entered string is disappears upon context change  on a nexus 7 2013 wifi running  lolipop 5.0 with nethunter 2.21 installed via the windows installer.

**Comment by binkybear** [comment]
@thesle3p - Some googling indicates this might be a permission issue.  

Is it possible to get a logcat?  I'm unsure if it's app related at the moment or if it's a permission issue outside of app.

**Comment by thesle3p** [comment]
I found the issue in logcat 
04-24 17:41:20.086 E/Nethunter(6690): java.io.FileNotFoundException: /storage/emulated/0/files/powersploit-url: open failed: EACCES (Permission denied) which is odd as this is a fresh flash of android and nethunter via the windows app.

**Comment by thesle3p** [comment]
I also noticed that since flashing with the windows app my nexus won't respond to fastboot on Linux and tarp stopped working.

**Comment by binkybear** [comment]
Do you have a /files folder on your /sdcard?  Are you missing the powersploit-url?

**Comment by thesle3p** [comment]
Fixed it by downgrading to 4.4.4

----- Reply message -----
