### ISSUE TITLE
nexus 10, lolipop, rescue mode has no menu

### ISSUE THREAD

**Issue by ChrisFernandez** [offensive-security/kali-nethunter#202]
so i push the file from my blackarch distro adb push etc.. to /sdcard/
i tell it to reboot in recovery mode.. but i just got an android laid back wit ha "no command"
no menu.. no nothing to choose the nethunter zip file...

**Comment by binkybear** [comment]
Do you have TWRP installed for your recovery?  Are you rooted and unlocked?  I'm not sure this is an issue with nethunter itself.
