### ISSUE TITLE
net hunter on nexus 9

### ISSUE THREAD

**Issue by highchecker** [offensive-security/kali-nethunter#203]
all the net hunter apps work just fine, but as soon as i open kali with vnc or xserver, i run into problems.
there is a problem with the root PATH, wich makes it impossible to install new programs, like ice weasel.
i can fix the PATH, but it will be broken after every restart.
some applications like armitage and fern wifi don't open , nessus doesn't work either.
i did about 30 ( more) fresh rom flashes and tried really everything to rule out an error on my end.
to be sure, i installed normal kali with LINUX deploy, and everything works just fine, like on my laptop.
So the error must be in the net hunter image. 
if someone has a permanent PATH fix, that would be great !

**Comment by offensive-security** [comment]
Your report doesn't make any sense, and without proper debug info, there's not much we can do. Also, Nessus doesn't exist for ARM architectures.

**Comment by highchecker** [comment]
ok, i will provide you with the error messages i am getting, but what part of the PATH problem u don't understand ? if the path doesn't exist, i can't install stuff on it, and i am not the only one having that problem, others reported it with nano, except it appears over and over again, not on my nexus 5 , but on the nexus 9. when i try to install something i get the message that the root path xbin sbin etc doesn't exist, and so i can't install. i can fix that wit a line of code, but it doesn't stay after restarting.
export PATH=$PAth:/usr/local/sbin:/usr/sbin:/sbin

**Comment by jmingov** [comment]
7 months no logs...
