### ISSUE TITLE
 mystery wireless device 

### ISSUE THREAD

**Issue by ninjoe** [offensive-security/kali-nethunter#204]
error: SIOCGIFFLAGS (No such device)

  .;'                     `;,
 .;'  ,;'             `;,  `;,   WiFite v2 (r85)
.;'  ,;'  ,;'     `;,  `;,  `;,
::   ::   :   ( )   :   ::   ::  automated wireless auditor
':.  ':.  ':. /_\ ,:'  ,:'  ,:'
 ':.  ':.    /___\    ,:'  ,:'   designed for Linux
  ':.       /_____\      ,:'
           /       \

 [!] the program cowpatty is not required, but is recommended

 [+] scanning for wireless devices...
 [+] available wireless devices:
  1. PHY        Interface       Driver          Chipset
  2. phy0       wlan0           ??????          non-mac80211 device? (report this!)
 [+] select number of device to put into monitor mode (1-2):

**Comment by offensive-security** [comment]
Mystery solution! perhaps try adding some information to your bug reports, so that they are actually useful.

**Comment by No4h-** [comment]
I have the same error on my Nexus 6 Lollipop using image 1.21.
I'm not able to start monitor mode on my device.
It detects my external card as it should btw, but it's not possible to activate monitor mode.
Is there's an error log that I could send you?

**Comment by 0E800** [comment]
Just a guess, but it looks like your running wifite script. I do not think
that the script takes into account that airmon-ng no longer creates a
'mon0' but creates 'wlan0mon'. The script will have to be updated.
Airmon-ng replaced with airmon-zc?

Review change log:
http://www.aircrack-ng.org/doku.php?id=changelog

To verify, launch Nethunter Kali terminal and type 'airmon-ng start wlan0'



On Wed, May 13, 2015 at 3:17 PM, No4h- <notifications@github.com> wrote:

> I have the same error on my Nexus 6 Lollipop using image 1.21.
> I'm not able to start monitor mode on my device.
> It detects my external card as it should btw, but it's not possible to
> activate monitor mode.
> Is there's an error log that I could send you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/204#issuecomment-101835411>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by No4h-** [comment]
Thx 0E800 :)
=>
root@kali:~# airmon-ng start wlan0
Found 2 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to kill (some of) them!

  PID Name
 1066 wpa_supplicant
 1879 dhcpcd

PHY     Interface       Driver          Chipset

phy0    wlan0           ??????          non-mac80211 device? (report this!)
Failed to set wlan0mon up using ip
command failed: No such device (-19)

                (mac80211 monitor mode vif enabled for [phy0]wlan0 on [phy0]wlan0mon)
                (mac80211 station mode vif disabled for [phy0]wlan0)

Launching wifite from kali terminal fixed the issue

**Comment by 0E800** [comment]
Apologies, I neglected to take into account that wlan0 would be the devices internal wifi, which does not  support monitor mode. So you would use 'airmon-ng start wlan1' to enable monitor mode on  the TPlink usb wifi adapter. Glad you got it working.

**Comment by No4h-** [comment]
Monitor mode enabled on wlan1 of course ;)
... and it runs surprisingly smooth and fast on the Nexus 6.

**Comment by emadehsan** [comment]
@0E800 are you sure??

**Comment by ditonikola** [comment]
@0E800 i cant compile, it gives me this error

compilation terminated.
<builtin>: recipe for target 'aircrack-ng.o' failed
make[1]: *** [aircrack-ng.o] Error 1
make[1]: Leaving directory '/root/Downloads/aircrack-ng-1.1/src'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2

pls help
