### ISSUE TITLE
[nexus 5] - TWRP Manager does not detect BusyBox after Nethunter install using Nethunter Installer application

### ISSUE THREAD

**Issue by pgrohe** [offensive-security/kali-nethunter#205]
Hi guys,

When installing the Nexus 5 hammerhead lollipop Nethunter version using the all in one Windows installer application,  once the install is complete, TWRP Manager does not properly detect that BusyBox is installed and pops up an error message asking the user to install it from Play Store.

Reproduction Rate : 2/2 installs using all in one Windows installer

Steps to Reproduce
1. Install NetHunter Lollipop using the Windows installer application and all the default img files
2. OpenSU as instructed in post install steps
3. Open BusyBox as instructed in post install steps.  Grant super user,  change install path to /system/xbin,  press Install -> Smart Install
4. Wait for completion
5. Open TWRP Manager
6. Observe message stating that BusyBox (Stericson) needs to be installed
7. Open terminal, change directory to /system/xbin and run 'ls busybox' note presence of BusyBox.

On the second attempt at installing Nethunter I opened TWRP before even opening BusyBox Free (as BusyBox appears to be pre-installed by the install scripts) and it gives the same message about BusyBox not being present.

![twrp-busybox-message](https://cloud.githubusercontent.com/assets/359095/7635244/de5531be-fa2d-11e4-8f3e-6fd8a4a5e0ee.png)
![terminal-screenshot](https://cloud.githubusercontent.com/assets/359095/7635247/e34f120c-fa2d-11e4-8740-f77ac3d93cbe.png)

**Comment by pgrohe** [comment]
The actual Nethunter install works though.  Tools are functional,  Kali Launcher menus all work.

The message above appears when opening TWRP Manager.  If I dismiss it I can still get into the TWRPC app and navigate the menus but whenever I choose an operation (Reboot for example) there is no effect.   I'm guessing because the actual menus are not triggering anything in the  BusyBox 'back end' because it doesn't know it where to find it or something.

Let me know if any more info is needed.

**Comment by pgrohe** [comment]
I've confirmed that this does not occur when installing Nexus 5 KitKat Nethunter.  Only Lollipop.

Something odd that I noticed when this occured originally on the Lollipop version was at the top of the BusyBox Free installer screen, the space free on /system showed 0.  Just nowon KitKat it properly listed the free space on there.

**Comment by binkybear** [comment]
@pgrohe - I'm going to go with this is not a Nethunter issue so I will close this issue.  Feel free to post on if you get it working as others may run into same issue.

 Nethunter does come with busybox located in /data/local/bin in case busybox is not able to work.  Your screenshot shows busybox so i'm unsure on why you are getting an error but it's probably related to the way TWRP manager checks.

**Comment by pgrohe** [comment]
Cool, understood.

In the last pop up message of the installer it says to run BusyBox Free and press the Install button.  Is this step required if BusyBox is already in /data/local/bin?  What path should I be setting in the BusyBox installer?

I'm open to the possibility I may have done something incorrectly in the install.. I'm a little unclear on where BusyBox is actually supposed to be (/data/local/bin, /system/bin, system/xbin as recommended by the installer popup).

**Comment by binkybear** [comment]
@pgrohe - For the most part /system/bin is fine as /system/xbin is usually in your PATH also.  You can easily check in terminal to make sure you have both:
```
echo $PATH
```
That being said, I included busybox as a "just in case" option inside /data/local/bin, mainly it's only purpose is to launch chroot.  That location isn't in the PATH so having it in /system is useful for other reasons.

**Comment by pgrohe** [comment]
As a follow up, I installed Nethunter manually using the Wugfresh Nexus Root Toolkit, following the steps on the Nethunter site, and it's working fine now.

I installed BusyBox Free vai the Play store  to /system/xbin after rooting the device. And then TWRP manager.  I then went on to install the Nethunter ZIP using TWRP as described in the install docs and have had no issues with the TWRP Manager.

**Comment by binkybear** [comment]
Awesome, glad to hear.  I can point to this issue in the future for anyone having similar issues.
