### ISSUE TITLE
Nexus 9 USB Attacks

### ISSUE THREAD

**Issue by Untide** [offensive-security/kali-nethunter#208]
I am having an issue with getting any of the USB attacks to work on the Nexus 9. I have tried with and without USB debugging, with and without MTP enabled with no joy. I have tried it on 3 computers with the same results.

Android Version
5.0.1

Kernel Version
3.10.40-g6f3881e-dirty
root@kali #1
Sat Mar 28 00:22:24 EDT 2015

**Comment by binkybear** [comment]
Hi @Untide,

When you have some time can you check that you have /dev/hidg0 as one of your devices.  Just go into terminal on device and get a listing.  You can also double check with the usb keyboard app that should be installed.

Some other work around to try is a different usb cable (I noticed you tried the other work arounds).

**Comment by Untide** [comment]
Okay well I figured it out. PTP and USB Debug have to be enabled to get it to work. Thanks for the help though, much appreciated.


Also something I noticed while setting it up, the instructions don't say to but to unlock the bootloader you need to check the Enable OEM Unlock in developer options. 

Anyways thanks again for the help and awesome job on all this.

**Comment by binkybear** [comment]
Glad you were able to get it working, I can point others to your solution if needed.  Thanks and take care.
