### ISSUE TITLE
Nexus 9 Mana AWUS036H 

### ISSUE THREAD

**Issue by Untide** [offensive-security/kali-nethunter#209]
Everything looks like it runs pretty well when I do the full lollipop from command line. The only issue is the access point doesn't come up. The interface doesn't show up in ifconfig until I run the script a few times, but the AP still doesn't show. The following is what I get after getting wlan1 up from running the script.

Font: Small - Normal - Large
root@WRT54G:~# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:55750 errors:0 dropped:0 overruns:0 frame:0
          TX packets:55750 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:13861920 (13.2 MiB)  TX bytes:13861920 (13.2 MiB)
 
wlan0     Link encap:Ethernet  HWaddr 50:2e:5c:e5:1d:ce
          inet addr:192.168.2.47  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::522e:5cff:fee5:1dce/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:193699 errors:0 dropped:0 overruns:0 frame:0
          TX packets:61609 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:280625774 (267.6 MiB)  TX bytes:5103301 (4.8 MiB)
 
wlan1     Link encap:Ethernet  HWaddr 00:11:22:33:44:00
          inet addr:10.0.0.1  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
 
root@WRT54G:~# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:55772 errors:0 dropped:0 overruns:0 frame:0
          TX packets:55772 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:13863020 (13.2 MiB)  TX bytes:13863020 (13.2 MiB)
 
wlan0     Link encap:Ethernet  HWaddr 50:2e:5c:e5:1d:ce
          inet addr:192.168.2.47  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::522e:5cff:fee5:1dce/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:193849 errors:0 dropped:0 overruns:0 frame:0
          TX packets:61616 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:280633600 (267.6 MiB)  TX bytes:5104606 (4.8 MiB)
 
wlan1     Link encap:Ethernet  HWaddr 00:11:22:33:44:00
          inet addr:10.0.0.1  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
root@WRT54G:/usr/share/mana-toolkit/run-mana# start-mana-full-lollipop
-- wlan1: flushing interface --
-- wlan1: setting ip --
-- wlan1: starting the interface --
-- wlan1: setting route --
Configuration file: /etc/mana-toolkit/hostapd-karma.conf
nl80211: Could not configure driver mode
nl80211 driver initialization failed.
hostapd_free_hapd_data: Interface wlan1 wasn't started
Internet Systems Consortium DHCP Server 4.2.2
Copyright 2004-2011 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Wrote 0 leases to leases file.
Listening on LPF/wlan1/00:11:22:33:44:00/10.0.0.0/24
Sending on   LPF/wlan1/00:11:22:33:44:00/10.0.0.0/24
Can't bind to dhcp address: Address already in use
Please make sure there is no other dhcp server
running and that there's no entry for dhcp or
bootp in /etc/inetd.conf.   Also make sure you
are not running HP JetAdmin software, which
includes a bootp server.
/usr/share/mana-toolkit/run-mana
Non spoofing imap.gmail.com
Non spoofing www.google.com
Non spoofing www.apple.com
Non spoofing to 127.0.0.1
Specific domain IP .domain.com with 192.168.1.1
binded to UDP port 53.
waiting requests.
WARNING: No route found for IPv6 destination :: (no default route?)
Generated RSA key for leaf certs.
SSLsplit  (built 2014-05-26)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Features: -DDISABLE_SSLV2_SESSION_CACHE -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter:  IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
compiled against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
rtlinked against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
Using direct access workaround when loading certs
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.19-stable
rtlinked against libevent 2.0.19-stable
2 CPU cores detected
proxyspecs:
- [0.0.0.0]:10025 tcp plain netfilter
- [0.0.0.0]:10465 ssl plain netfilter
- [0.0.0.0]:10110 tcp plain netfilter
- [0.0.0.0]:10995 ssl plain netfilter
- [0.0.0.0]:10143 tcp plain netfilter
- [0.0.0.0]:10993 ssl plain netfilter
- [0.0.0.0]:10080 tcp http netfilter
- [0.0.0.0]:10443 ssl http netfilter
Loaded CA: '/C=ZA/ST=Gauteng/L=Pretoria/O=SensePost/OU=MANA/CN=MANA/emailAddress=research@sensepost.com'
Using libevent backend 'epoll'
Event base supports: edge yes, O(1) yes, anyfd no
Inserted events:
  0x489158 [fd 7] Read Persist
  0x488744 [fd 8] Read Persist
  0x4887ac [fd 9] Read Persist
  0x4891c4 [fd 10] Read Persist
  0x48922c [fd 11] Read Persist
  0x489944 [fd 12] Read Persist
  0x4899ac [fd 13] Read Persist
  0x489a14 [fd 14] Read Persist
  0x489a7c [fd 15] Read Persist
  0x489048 [fd 6] Read Persist
  0x485870 [fd 3] Signal Persist
  0x489be0 [fd 1] Signal Persist
  0x489cc0 [fd 2] Signal Persist
  0x489da0 [fd 13] Signal Persist
Initialized 4 connection handling threads
Started 4 connection handling threads
Starting main event loop.
MANA (FireLamb) : [+] Saving output to /var/lib/mana-toolkit/lamb_braai/
MANA (FireLamb) : [+] Listening for cookie traffic on interface wlan1
Traceback (most recent call last):
  File "sslstrip.py", line 110, in <module>
    main(sys.argv[1:])
  File "sslstrip.py", line 102, in main
    reactor.listenTCP(int(listenPort), strippingFactory)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 436, in listenTCP
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 641, in startListening
    raise CannotListenError, (self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:10000: [Errno 98] Address already in use.
Hit enter to kill me
Garbage collecting caches started.
Garbage collecting caches done.

Any idea what is going on here?

**Comment by offensive-security** [comment]
IIRC the AWUS036H doesn't support hostapd, but not sure if that is the issue at hand here.

**Comment by Untide** [comment]
It's possible, I ordered a few adapters and will test those out when they get here to see if it makes a difference.

**Comment by Untide** [comment]
Okay this is as far as I have gotten with this so far...not even sure if this rabbit hole is the right one...

Tried to manually start hostapd

root@kali:/etc/mana-toolkit# service hostapd start
[FAIL] Starting advanced IEEE 802.11 management: hostapd failed!


ran the script with debugging

root@kali:/etc/mana-toolkit# hostapd -d hostapd-karma.conf
random: Trying to read entropy from /dev/random
Configuration file: hostapd-karma.conf
ctrl_interface_group=0
KARMA: Enabled
Line 38: unknown configuration item 'karma_loud'
1 errors found in configuration file 'hostapd-karma.conf'

commented out karma_loud

root@kali:/etc/mana-toolkit# service hostapd start
[....] Starting advanced IEEE 802.11 management: hostapdmonitor socket bind: No such device
rmdir[ctrl_interface]: No such file or directory
 failed!

so now hostapd-karma.conf is fixed...I think (according to the debugger)
just need to figure out what this next error is...

**Comment by Untide** [comment]
Works fine with tplink I just had to comment out the karma lines to get it to work.

**Comment by Untide** [comment]
works otb with tplink, no modifications needed. I think @offensive-security is correct on this, although I couldn't find too much info else were.

**Comment by Untide** [comment]
Okay I tried this on a tplink adapter, seems like the hostapd doesn't like the karma settings but I can get the AP up with this adapter.

**Comment by Untide** [comment]
Well, I feel silly. I found that the AP goes down when the tablet goes into it's sleep mode.

**Comment by binkybear** [comment]
@Untide - You can do a wakelock in terminal application settings.  That should prevent AP from going down I believe.
