### ISSUE TITLE
windows installer app does not create  /files in lolipop

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#211]
After two flashes using the most up to date version of the windows app I can confirm that on lolipop the installer does not create  /files on the SD Card and TWRP can not boot into recovery or bootloader.

**Comment by binkybear** [comment]
Which device is this and what version are you flashing. Are you saying that the recovery is bad/not flashing?

**Comment by thesle3p** [comment]
I am flashing the most recent version of Nethunter using the windows app
onto a Nexus 7 2013 with lolipop (this is not the case when doing the
same with kitkat) and the recovery is not flashing the /files directory.

**Comment by jmingov** [comment]
The installer is no longer mantained, use NRT or BRT.

https://github.com/offensive-security/kali-nethunter/wiki#unlocking-and-rooting-your-android-device-windows
