### ISSUE TITLE
HID keyboard attack not working on Nexus 7 after flashing proper kernel

### ISSUE THREAD

**Issue by z0o0o0oz** [offensive-security/kali-nethunter#216]
Hello, I have a Nexus 7 wifi 2012, the HID attack worked after I installed nethunter on the device, however I could not start any of the services including apaches (even when trying from the command line), so I found a solution here and I flashed this kernel http://photonicgeek.me/NetHunter/Kernels/grouper-tilapia/Kernel-groupertilapia-kitkat-12042014.zip

Now the services work but I can't start HID attack, if I connect my device a windows laptop I can control mouse and keyboard from usb keyboard app but when I try to run the HID attack from the terminal I get:
chroot: cannot change root directory to /data/local/kali-armhf: no such file or directoyry

**Comment by binkybear** [comment]
Hi z0o0o0oz.  Let me verify that you are running kitkat (4.4.4).  Can you go into the terminal and verify there is a /data/local/kali-armhf?

For hid to work you should see a dev called hig0:
```bash
ls /dev/
```
We can try to troubleshoot more if you can get back with me.

**Comment by z0o0o0oz** [comment]
Thanks for your response.
Yes I have kitkat 4.4.4 but /data/local/kali-armhf does not exist

**Comment by 0E800** [comment]
Just wanted to chime in and mention that I also noticed that some files /
folders were missing. I attributed it to the Rom I was using. I would
suggest either manually adding those missing folders or try reflashing
Nethunter.



On Wed, Jun 24, 2015 at 12:58 PM, z0o0o0oz <notifications@github.com> wrote:

> Thanks for your response.
> Yes I have kitkat 4.4.4 but /data/local/kali-armhf does not exist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/216#issuecomment-114993492>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by binkybear** [comment]
@z0o0o0oz - So kali-armhf should be where your Kali installation is located but if it's not there then nothing should be working.  Nothing should be working for you without the folder and only a reinstallation can be bring it back.

Also, good advice @0E800.

**Comment by z0o0o0oz** [comment]
Well yeah all HID attacks don't work, bad USB doesn't work either.

And I've tried reinstalling again, when I do that, everything works, even the HID keyboard works, but I can't start any services such as apache or dnsmasq, to fix this issue I followed a solution here to flash the kernel I mention above, when I do that the service work but HID stops working

**Comment by 0E800** [comment]
Are you using stock ROM? How are you flashing nethunter and kernel, may you
please describe your steps. I will try to get time today to verify on my
own device.

**Comment by z0o0o0oz** [comment]
I used the windows installer to install NetHunter, so yes it would be using a stock Rom, the other kernel I'm flashing it from recovery by going on install and then selecting the kernel.

**Comment by z0o0o0oz** [comment]
I got everything working, here is what I did
1. Installed NetHunter using the windows installer.
2. Flashed the kernel above to get the service to work, this however removes /data/local/kali-armhf.
3. Reflashed NetHunter from recovery.

**Comment by binkybear** [comment]
I'm glad you got it working.  I'm surprised the kernel removes your chroot; it's not supposed to touch it.  Either way, I will close the issue for now.
