### ISSUE TITLE
Kismet + BlueNMEA + gpsd +WN772N adapter

### ISSUE THREAD

**Issue by caesartcs** [offensive-security/kali-nethunter#217]
Problem: When running Kismet to detect AP's and their GPS information, when Kismet ends it says:

Warning: no gps data found for BSSID: <someBSSID> ESSID: <someESSID>

and I get no GPS data to any of the AP's I find.

I see GPS data in Kismet, I see AP's. But when I exit out of it and Kismet does its database activity, I eventually get that Warning message for every AP i scanned. Any idea why?

I am using a Nexus (2012) 7 wifi tablet, with BlueNMEA 2.1.3, gpsd 3.6, Kismet 2013-03-R0 and a TP Link TL-WN772N wireless external adapter.

**Comment by binkybear** [comment]
It looks like it's related to giskismet during the conversion to a KML file:

https://code.google.com/p/kisgearth/issues/attachmentText?id=6&aid=60008000&name=kisgearth.pl&token=87BlW_bNbqK4KPZiuPiUwdn_5t8%3A1393236110060#1369

I couldn't say why it's not working without doing some debugging.  Giskismest should process the wireless.dbl file and produce the kml:

https://github.com/offensive-security/kali-nethunter/blob/master/menu/kalimenu#L210

If you are able to, you can check to see if you can do it manually.  Easiest way would probably be to ssh into tablet and try running commands to see if you get the same error msg.

**Comment by caesartcs** [comment]
Hi binkybear. I have read a lot of your troubleshooting and posts on these subjects. Thanks for responding. 

I am not getting that exact message from Kismet. But it is very similar.
The Warning error happens right after I kill Kismet, not during but before the giskismet conversion.

I also do not use the following giskismet command you posted:

giskismet --database "/captures/kismet_db/wireless.dbl" -q "select * from wireless" -o "/captures/kismet/kismet-$NOW.kml"

I used:
giskismet -x Kismet-20110221-08-56-26-1.netxml
giskismet -q "select * from wireless" -o giskismet_demo.kml

I am starting Kismet from the Kali Menu in Nethunter and when I exit it, it starts to do it's thing. However, when I start kismet from the shell and I kill it after it does it's thing, it just dies, it does not output any files. How would I do it manually? What are the commands to have Kismet output the files I need? I looked in the MAN pages but I couldn't find anything.

**Comment by caesartcs** [comment]
So I have gotten it to work.

giskismet -x Kismet-20110221-08-56-26-1.netxml
giskismet -q "select * from wireless" -o giskismet_demo.kml

The above commands are the correct commands to exporting the files from a nextkml to a kml.
We can close this issue.
