### ISSUE TITLE
Nexus 7 (2013) LTE + CM 12.1 + Nethunter for lollipop = sluggish/lag/reboot 

### ISSUE THREAD

**Issue by confuded** [offensive-security/kali-nethunter#219]
I have followed the steps (albeit on a Mac - same as the linux ones) for installing NetHunter on a Nexus 2013 LTE (razorg) device. Instead of using the stock rom I've flashed CM 12.1 (cm-12.1-20150701-NIGHTLY-deb) with GApps (gapps-lpmr1-20150607-signed).

1. On my first attempt I was using CWM and used CM's built in root (in developer options) with BusyBox. In this case I flashed nethunter (kali_linux_nethunter_1.21_razor_lollipop). 
2. On the second attempt I used TWRP to wipe the phone clean (of everything), flashed CM and GApps, installed CF Auto Root (chainfire) and BusyBox. Then flashed the same nethunter file.

The results are the same: the system boots and is very very sluggish to the point of unusability. Once I managed to unlock the screen (swipe - takes a few tries and some patience) I see the UI has some strange colors (I can post a screen if needed - however I would need to know how to do so from adb). 
I am currently on the 2nd setup and the system is also not so stable (just decides to reboot at its whim).

Will keep the current setup for the sake of resolving the issue (I really like CM and lollipop). Happy to post any logs or results of commands as necessary. Here (http://pastebin.com/qj5hdhtq) is an output of last_ksmg (no idea what it is - hope it helps; just saw this asked to be posted in a few places).

Thank you,
~confuded

**Comment by binkybear** [comment]
Hi @confuded,

I would say the main issue is the the kernel you are using was never meant to work with Cyanogemod.  CM forked off their kernels so it requires a different build then a stock kernel.

My guess/thought is that the kernel isn't playing nice with CM.

**Comment by confuded** [comment]
@binkybear thanks for the reply. 
I have read casual mentions of installing NetHunter with CM (probably not 12.1, rather KitKat). I guess I would have to live with the stock ROM.

There is no current goal to support CM (12.1)?

**Comment by 0E800** [comment]
I have a N7 2012 and have tested NH on various ROMs with mixed results. I
had best results with SlimRom. Please note that I have not tested with LP.
As a pentest tool, I would suggest aiming for what works vs having a
up-to-date android OS. As a pentester you should not be using your own
personal device as both daily driver and pentest tool..IMO.

**Comment by binkybear** [comment]
@0E800 - Very good suggestion about keeping them separate.

@confuded - I believe I made a CM kernel for kitkat but we stuck with stock because we use factory images for the windows installer so it didn't make sense to use CM.  I like CM, it's one of my favorite ROMs.  However, maintaining the number of devices as well as multiple kernels put the CM kernel on a wish list.

That's not to say that I wouldn't make one in the future, but at the moment I don't plan on making another one for lollipop.

**Comment by confuded** [comment]
@0E800 Indeed, the suggestion is great and in fact I do. I have a fake google account on the tablet and my aim was to use it as a tablet as well as a pen-test-tool. I guess it will simply have to remain a pen-test-tool.

@binkybear CM for KitKat you say? I guess I will go and flash that now... Having problems with the AWUS036H anyway on stock ROM with NT and Lollipop - just reboots) 

Thank you for the replies.

**Comment by binkybear** [comment]
@confuded - The kernel was never released but if you need a copy I can build one easily for you from sources here.

**Comment by confuded** [comment]
@binkybear yea, I was unable to find it. I will happily take it if you can be bothered =). Happy to provide any feedback on it.
I currently flashed 4.4.4 stock and it works (besides the unplugging of wi-fi card problem - reboots still).
