### ISSUE TITLE
Nethunter nexus 7 usb otg cable will not detect external wifi.

### ISSUE THREAD

**Issue by Bry-fi** [offensive-security/kali-nethunter#220]
Again with no reason, the cable used to work flawlessly and the only way I could take the cable out was yanking (detach usb from nethunter had no effect) So now my nexus will NOT detect the usb cable or wlan1. Please someone tell me how this happened I did a fresh install and still the same results.

**Comment by binkybear** [comment]
This is the Nexus 7 2012?

**Comment by Bry-fi** [comment]
@binkybear
Nexus 7 2013 wifi

**Comment by binkybear** [comment]
Lollipop or kitkat?

**Comment by Bry-fi** [comment]
@binkybear
Kitkat

**Comment by vremy** [comment]
You have to set your device in USB host mode to get it working. Follow this video to enable OTG support https://www.youtube.com/watch?v=Slx07fFCP3M
