### ISSUE TITLE
vbscan on NetHunter 

### ISSUE THREAD

**Issue by rezasp** [offensive-security/kali-nethunter#221]
VBScan on @kalilinux Nethunter Project (Nexus 5) <3

img : https://pbs.twimg.com/media/CJBIcqkWoAEJEMD.jpg:large

https://twitter.com/rezesp/status/617072815217491968

https://github.com/rezasp/vbscan

**Comment by binkybear** [comment]
It looks like an interesting scanner, thanks for bringing it to our attention.
