### ISSUE TITLE
HID Ducky Script Attacks

### ISSUE THREAD

**Issue by SMAPPER** [offensive-security/kali-nethunter#222]
It would be pretty useful to have the ability under the HID Ducky Script Attacks to save and load multiple ducky scripts.  Currently I just save various scripts and copy and paste them when needed but it would be nice to have it save/load in the same interface.

The same thing applies to the HID Keyboard Attack.  The HID Keyboard attack could have saved profiles that include the keyboard attack and payload parameters that way depending on the attack scenario you have a canned attack.

Nethunter has been extremely helpful (and awesome) and I think the more UI options given the more users will be drawn to it.

**Comment by binkybear** [comment]
Hi @SMAPPER ,

This functionality was actually added recently thanks to @aemaeth2501:

https://github.com/offensive-security/nethunter-app/commit/7d19deb5429194f6e7f3b13da32a4d8a1cf54418

It only applies to Ducky Scripts though.  I'm going to close the issue but label it as an enhancement for the second part (hid keyboard attack).

**Comment by binkybear** [comment]
I have updated the apk if you would like to test:

https://github.com/offensive-security/kali-nethunter/commit/22c1ec23d360b844e34414dba84b73f86f1b7659

**Comment by SMAPPER** [comment]
Thanks. I'll download and give it a try.

Glad to see the work being put into Nethunter.
