### ISSUE TITLE
Nethunter storage problem!

### ISSUE THREAD

**Issue by rsozdance** [offensive-security/kali-nethunter#225]
Hello,
I have nexus 5 16 gb.
my phone storge is full I search about any big data and found zip file called "kali_linux_nethunter_1.21_hammerhead_lollipop.zip" in my download dictionary!  Can I delete this file ? To give my divice more storage?

**Comment by binkybear** [comment]
Yes, you can delete the install file.

**Comment by rsozdance** [comment]
Thank you very much ^^
