### ISSUE TITLE
Feature request: Android/Chroot bridge

### ISSUE THREAD

**Issue by bwall** [offensive-security/kali-nethunter#226]
Please let me know if this is a duplicate or if this functionality already exists.

User story: A developer wishes to build an Android application which acts as an interface to a tool which resides in the kali chroot.

When I was working on a project which required this in the past, I modified my version of bootkali to take a base64'd command which it would run inside the chroot.  This did not send any information out.  That was just a quick hack though.

**Comment by binkybear** [comment]
The nethunter-app pretty much acts a bridge (using bootkali).  It's possible to modify bootkali to take any commands and run them in chroot.  Just thinking out loud, but you could output > or tee to a /tmp folder in chroot and read it.

**Comment by bwall** [comment]
My initial thoughts on a full reusable/distributable solution would be an authenticated TCP server (on localhost only) inside the chroot which would allow for execution of commands/code.  Essentially, the Android app would request access by passing arguments to an edited bootkali, including an authentication token (randomly generated at run time).  Then using that shared secret (or corresponding key depending), the app would then be able to have the ability to execute code inside the chroot, and have results come back without polling for a file at a specified position, as well as allowing for multiple applications to utilize it.

**Comment by jmingov** [comment]
Now you can communicate with kali using the new terminal @bwall

We added new intents, you just need to add the new permissions to you app.

See this examples:

https://github.com/offensive-security/nethunter-app/blob/master-2.1/src/com/offsec/nethunter/KaliLauncherFragment.java#L132

and this perms:

https://github.com/offensive-security/nethunter-app/blob/master-2.1/AndroidManifest.xml#L12

Jaime
