### ISSUE TITLE
Nexus 7 (2012 WIFI) with TL-WN722N with otg cable not working

### ISSUE THREAD

**Issue by matthewobrn** [offensive-security/kali-nethunter#227]
So I installed Nethunter with the windows installation program, on my nexus 7 2012 wifi only tablet. I bought a TL-WN722N usb wifi adapter.

When I tried it nothing happened. I tried ifconfig and it only shows up wlan0 p2p0 and lo0.

I have attached the dmesg output.

I dont have a y cable is it possible this is the issue?

Here is my dmesg output:
[ 4823.347809] cpu_up(1)+
[ 4823.370173] CPU1: Booted secondary processor
[ 4823.373923] cpu_up(1)-
[ 4823.377808] Switched to NOHz mode on CPU #1
[ 4825.447924] cpu_down(1)+
[ 4825.450121] stop_machine_cpu_stop smp=0
[ 4825.450148] stop_machine_cpu_stop smp=1
[ 4825.453783] CPU1: shutdown
[ 4825.456798] cpu_down(1)-
[ 4845.799284] tegra-otg tegra-otg: SUSPEND --> HOST
[ 4845.819651] phy->instance = 0, phy->xcvr_setup_value = 60
[ 4845.819853] create_regulator: fixed_reg_en_avdd_hdmi_usb_a01: Failed to create debugfs directory
[ 4845.820128] tegra_usb_phy_open instance 0 MAX77663_IRQ_ACOK_RISING
[ 4845.823888] tegra-ehci tegra-ehci.0: Tegra EHCI Host Controller
[ 4845.824238] tegra-ehci tegra-ehci.0: new USB bus registered, assigned bus number 2
[ 4845.847855] tegra-ehci tegra-ehci.0: irq 52, io mem 0x7d000000
[ 4845.867813] tegra-ehci tegra-ehci.0: USB 2.0 started, EHCI 1.00
[ 4845.867989] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002
[ 4845.868054] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 4845.868164] usb usb2: Product: Tegra EHCI Host Controller
[ 4845.868225] usb usb2: Manufacturer: Linux 3.1.10-g1e42d16 ehci_hcd
[ 4845.868334] usb usb2: SerialNumber: tegra-ehci.0
[ 4845.868712] hub 2-0:1.0: USB hub found
[ 4845.868833] hub 2-0:1.0: 1 port detected
[ 4845.869064] Wake39 for irq=52
[ 4845.869126] Enabling wake39
[ 4846.367963] usb 2-1: new high speed USB device number 2 using tegra-ehci
[ 4846.397982] INOK=L
[ 4846.399152] smb347_charger: [cable_type_detect] Reg39 : 0x11
[ 4846.400781] smb347_charger: [cable_type_detect] Reg3F : 0x00
[ 4846.401425] USBIN=0
[ 4846.411168] usb 2-1: New USB device found, idVendor=0cf3, idProduct=9271
[ 4846.411682] usb 2-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 4846.412188] usb 2-1: Product: USB2.0 WLAN
[ 4846.412457] usb 2-1: Manufacturer: ATHEROS
[ 4846.412724] usb 2-1: SerialNumber: 12345
[ 4856.617787] cpu_up(1)+
[ 4856.640645] CPU1: Booted secondary processor
[ 4856.643801] cpu_up(1)-
[ 4856.647831] Switched to NOHz mode on CPU #1
[ 4858.817933] cpu_down(1)+
[ 4858.820146] stop_machine_cpu_stop smp=0
[ 4858.820170] stop_machine_cpu_stop smp=1
[ 4858.823776] CPU1: shutdown
[ 4858.828250] cpu_down(1)-
[ 4865.728720] bq27541_get_psp status: Discharging ret= 0x0101
[ 4865.729616] bq27541_get_psp voltage_now= 3849000 uV
[ 4865.730406] bq27541_get_capacity = 61% ret= 63
[ 4865.731287] bq27541_get_psp temperature= 220 (0.1\xffffffa2XC)
[ 4865.732735] bq27541_get_psp current = -570 mA
[ 4865.736089] bq27541_get_capacity = 61% ret= 63
[ 4865.738565] bq27541_get_psp voltage_now= 3849000 uV
[ 4865.740472] bq27541_get_psp current = -570 mA
[ 4865.741298] bq27541_get_psp temperature= 220 (0.1\xffffffa2XC)
[ 4865.742043] bq27541_get_psp status: Discharging ret= 0x0101
[ 4865.742473] healthd: battery l=61 v=3849 t=22.0 h=2 st=3 c=0 chg=
[ 4877.777797] cpu_up(1)+
[ 4877.800296] CPU1: Booted secondary processor
[ 4877.802856] cpu_up(1)-
[ 4877.807806] Switched to NOHz mode on CPU #1
[ 4879.977878] cpu_down(1)+
[ 4879.980611] stop_machine_cpu_stop smp=0
[ 4879.980634] stop_machine_cpu_stop smp=1
[ 4879.983333] CPU1: shutdown
[ 4879.985879] cpu_down(1)-
[ 4925.889306] bq27541_get_psp status: Discharging ret= 0x0101
[ 4925.891581] bq27541_get_psp voltage_now= 3844000 uV
[ 4925.893185] bq27541_get_capacity = 61% ret= 63
[ 4925.895277] bq27541_get_psp temperature= 220 (0.1\xffffffa2XC)
[ 4925.897701] bq27541_get_psp current = -421 mA
[ 4925.901914] bq27541_get_capacity = 61% ret= 63
[ 4925.902877] bq27541_get_psp voltage_now= 3844000 uV
[ 4925.904467] bq27541_get_psp current = -421 mA
[ 4925.905529] bq27541_get_psp temperature= 220 (0.1\xffffffa2XC)
[ 4925.906473] bq27541_get_psp status: Discharging ret= 0x0101
[ 4925.907264] healthd: battery l=61 v=3844 t=22.0 h=2 st=3 c=0 chg=
[ 4931.957860] cpu_up(1)+
[ 4931.985425] CPU1: Booted secondary processor
[ 4931.987832] Switched to NOHz mode on CPU #1
[ 4931.996231] cpu_up(1)-
[ 4934.057882] cpu_down(1)+
[ 4934.060185] stop_machine_cpu_stop smp=0
[ 4934.060210] stop_machine_cpu_stop smp=1
[ 4934.063357] CPU1: shutdown
[ 4934.067339] cpu_down(1)-
[ 4936.457856] cpu_up(1)+
[ 4936.482369] CPU1: Booted secondary processor
[ 4936.483851] cpu_up(1)-
[ 4936.487817] Switched to NOHz mode on CPU #1
[ 4939.257905] cpu_down(1)+
[ 4939.270178] stop_machine_cpu_stop smp=0
[ 4939.270200] stop_machine_cpu_stop smp=1
[ 4939.273703] CPU1: shutdown
[ 4939.276816] cpu_down(1)-
[ 4946.857849] cpu_up(1)+
[ 4946.889228] CPU1: Booted secondary processor
[ 4946.897777] Switched to NOHz mode on CPU #1
[ 4946.900023] cpu_up(1)-
[ 4949.957947] cpu_down(1)+
[ 4949.960802] stop_machine_cpu_stop smp=0
[ 4949.960826] stop_machine_cpu_stop smp=1
[ 4949.963913] CPU1: shutdown
[ 4949.968028] cpu_down(1)-
[ 4955.127810] cpu_up(1)+
[ 4955.157067] tegra CPU: force EDP limit 1200000 kHz
[ 4955.157308] CPU1: Booted secondary processor
[ 4955.157773] Switched to NOHz mode on CPU #1
[ 4955.168703] cpu_up(1)-
[ 4959.227955] cpu_down(1)+
[ 4959.229971] stop_machine_cpu_stop smp=0
[ 4959.229993] stop_machine_cpu_stop smp=1
[ 4959.231610] CPU1: shutdown
[ 4959.236327] cpu_down(1)-
[ 4961.227852] cpu_up(1)+
[ 4961.251681] CPU1: Booted secondary processor
[ 4961.253622] cpu_up(1)-
[ 4961.257803] Switched to NOHz mode on CPU #1
[ 4961.627862] cpu_up(2)+
[ 4961.628986] CPU2: Booted secondary processor
[ 4961.630051] cpu_up(2)-
[ 4961.637840] Switched to NOHz mode on CPU #2
[ 4964.127859] cpu_down(1)+
[ 4964.129400] stop_machine_cpu_stop smp=0
[ 4964.129423] stop_machine_cpu_stop smp=2
[ 4964.129445] stop_machine_cpu_stop smp=1
[ 4964.131526] CPU1: shutdown
[ 4964.133983] cpu_down(1)-
[ 4966.327832] cpu_down(2)+
[ 4966.329235] stop_machine_cpu_stop smp=0
[ 4966.329257] stop_machine_cpu_stop smp=2
[ 4966.331145] CPU2: shutdown
[ 4966.333018] cpu_down(2)-
[ 4977.587786] cpu_up(1)+
[ 4977.610053] CPU1: Booted secondary processor
[ 4977.612736] cpu_up(1)-
[ 4977.617804] Switched to NOHz mode on CPU #1
[ 4980.087882] cpu_down(1)+
[ 4980.099712] stop_machine_cpu_stop smp=0
[ 4980.099735] stop_machine_cpu_stop smp=1
[ 4980.102660] CPU1: shutdown
[ 4980.104937] cpu_down(1)-
[ 4986.048869] bq27541_get_psp status: Discharging ret= 0x0101
[ 4986.050047] bq27541_get_psp voltage_now= 3830000 uV
[ 4986.051158] bq27541_get_capacity = 61% ret= 63
[ 4986.052521] bq27541_get_psp temperature= 230 (0.1\xffffffa2XC)
[ 4986.054361] bq27541_get_psp current = -679 mA
[ 4986.057905] bq27541_get_capacity = 61% ret= 63
[ 4986.059271] bq27541_get_psp voltage_now= 3830000 uV
[ 4986.061732] bq27541_get_psp current = -679 mA
[ 4986.063072] bq27541_get_psp temperature= 230 (0.1\xffffffa2XC)
[ 4986.064414] bq27541_get_psp status: Discharging ret= 0x0101
[ 4986.066150] healthd: battery l=61 v=3830 t=23.0 h=2 st=3 c=0 chg=
[ 4988.357810] cpu_up(1)+
[ 4988.379818] CPU1: Booted secondary processor
[ 4988.383591] cpu_up(1)-
[ 4988.387809] Switched to NOHz mode on CPU #1

**Comment by matthewobrn** [comment]
I've aso run lsusb and it shows up the device:

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by vremy** [comment]
From my own experience with the TL-WN722N wifi card you need the Y OTG cable to get enough power. It looks like the device is set to USB host mode so if the WIFI card has enough power and you see the green led from your wifi card running then it will work.

**Comment by Vdera** [comment]
Were you able to solve this?  I have the same issue.  I have the N7 2013 Wi-Fi model, running 4.4.4 and Nethunter 1.2.1

lsusb can identify the card, but when I do dmesg, it appears the sys tem detects the card, but makes no attempt to download firmware/drivers and install them.

**Comment by thebumblecat** [comment]
I have the Nexus 7 with 4G and a single OTG cable. It does work on 4.4.4 with nethunter 1.2.1
Prior to installing nethunter, i rooted and then flashed a photonicgeek.me kernel

This is the cable: http://www.amazon.com/dp/B00GM0OZ4O/

**Comment by Vdera** [comment]
So, maybe it doesn't like the Y cable?  Shame if that's the case as I bought an external battery pack to help keep the devices charged.

Does anyone have a link to the Kernel for the Wi-Fi version of the Nexus 7 (2013) The photonicgeek site seems to be unavailable atm.

Thanks.

**Comment by jtouug** [comment]
I've been using that adapter for a couple weeks on a Nexus 6 running 5.1.1, it won't work without the y cable for me.

**Comment by thebumblecat** [comment]
@Vdera I re-uploaded the photonicgeek kernel, but it was for the 2012 GSM Nexus 7 - https://mega.nz/#!4gd2RSiD!Ts-j7xdnFd1Snl8stnWDp6OLTKjYTglSrjrDnyhMGVo

I'll see if i can find an alternate.

**Comment by 0xicl33n** [comment]
Same problem with the Nexus 9 using NH 3.0

Worked fine in 2.0, i dont know what happened..

**Comment by lkobylski** [comment]
Any solution for NH 3.0?

**Comment by binkybear** [comment]
Trying flashing latest kernel.  Build from this repo or download zip: (https://idlekernel.com/nethunter/nightly/3.1.0-20160504-2330/)

**Comment by lkobylski** [comment]
It works! ;-) Thanks.

**Comment by worsedoughnut** [comment]
On a Nexus 7 2012, just tried flashing the Nightly kernel like @binkybear suggested, and it still isn't showing up / being recognized.
The TP-LInk shows up as "Aetheros Communiations, Inc. AR9271 802.11n" under `lsusb`, and the Nexus 7 receives power through the cable, but the TP-Link isn't lighting up at all.

`ifconfig wlan1 up` returned "No such device"
And I know the antenna's not broken, since it works on a windows 7 machine (after installing the drivers).

**Comment by Stooman** [comment]
I am quite new to kali Linux and the nethunter virsion, and I am trying to get my to link micro adapter (just very small still regular USB) to work with my nexus 7 2012 wifi only tablet. I have looked at a few tutorials but none of them have seemed to work. If anyone could shed some light on this issue for my it would be most appreciated.

**Comment by Stooman** [comment]
Tp link*

**Comment by Stooman** [comment]
I am quite new to kali Linux and the nethunter virsion, and I am trying to get my to link micro adapter (just very small still regular USB) to work with my nexus 7 2012 wifi only tablet. I have looked at a few tutorials but none of them have seemed to work. If anyone could shed some light on this issue for my it would be most appreciated.

**Comment by akrolla** [comment]
nexus 7 2012 grouper was discontinued +a few months back , you might be
able to find an answer to ur problem here
https://github.com/offensive-security/kali-nethunter/issues/639 or atleast
guide you on the right path towards your answer.

**Comment by 0xicl33n** [comment]
I had fixed this by coping the driver from the android system to the kali chroot. 

See #342

**Comment by crypt0b0y** [comment]
@0xicl33n, can you help me with that on Nexus 7 (2012)? Need make drivers for 3.1 Kernel for TL-WN722N and put it into chroot

**Comment by 0xicl33n** [comment]
@crypt0b0y 
> nexus 7 2012 grouper was discontinued 
and #342

**Comment by sezusatish** [comment]
hi  
i am using Device : Nexus 7 2013 (flo) WIFI (cm13)
 i try to building own nethunter base on this linke
https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter
Including the kernel full
using this commend :
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d flocm -m -su --rootfs full
 and able to make zip file and installed and all is working good
but external wifi  card TP-Link WN722N v1 is detected by NetHunter and working good for  max 120 min  only if I put device in sleep mode, next time onwards external WiFi  card is  not detected i am using the same card in kali os and i working good even i tryed with alfa card also use otg pen driver and mouse also working good , i tryed to check in lsusb it now shown or iwconfig not able to see any attached  max people are having issues, can any one  assist to find any solutions is it kernel issues or this nexus device is not support for external wifi card I check /etc/system/firmware having dump of firmware
