### ISSUE TITLE
Oneplus two?

### ISSUE THREAD

**Issue by theoneandonly-vector** [offensive-security/kali-nethunter#228]
Will there be a Oneplus two -Kernel avialable in the near future? (next 2-3 months)

**Comment by binkybear** [comment]
More than likely but I don't plan on building anything for Oxygen OS because it's closed.  I will probably build for any CM version that is released.

**Comment by theoneandonly-vector** [comment]
ok, thx
Am 30.07.2015 22:56 schrieb "binkybear" <notifications@github.com>:
