### ISSUE TITLE
Nexus 5 system partition full after installation

### ISSUE THREAD

**Issue by mayankmetha** [offensive-security/kali-nethunter#230]
there is no space to install busy box

**Comment by binkybear** [comment]
@mayankmetha - We run a  cleansystem.sh which should delete some system files during install.  However, in case of something like this we also install busybox to /data/local/bin I believe.

Did you run the installer or try to install busybox first?

**Comment by mayankmetha** [comment]
yes tried but busybox wont allow to install the busybox script 
System 0.0 MB space is shown on busybox

**Comment by ChrisFernandez** [comment]
i have the same issue on a nexus 10... and is been buggy i notice that nethunter did not install 100% is missing some files.. i had to make space and download from github and add them manually with adb push etc... is there a way to make system bigger and reinstall? one of the files missing was my driver for my alpha card.. first i was like why is not working.. i did a dmsg on the device after a adb shell 
and kernel could not find the firmware... i was like wtf... when to github for nethunter and the firware was there.. but not in my system.. had to manually also adb push it to the device.. now the alpha card is working fine.. but.. missing files im suspecting cause of /system partition full.. please ideas?

**Comment by ChrisFernandez** [comment]
did you guys try this?
https://github.com/offensive-security/kali-nethunter/issues/36

**Comment by mayankmetha** [comment]
Tried but still didn't work

**Comment by TheBlackRabbit** [comment]
@binkybear - correct, busybox is located in /data/local/bin/busybox and in newer images I've noticed it in /data/local/busybox as well.

Used it more than once to get me into 'sh' so I could run 'bootkali' when I was playing with Kali sana repos pre-release on CM12.1 nightlies. Mis/sing links, but '/data/local/bin/busybox sh' dropped me into a shell were I was able to access chroot.
