### ISSUE TITLE
nethunter 2.0 not working

### ISSUE THREAD

**Issue by TonyH4** [offensive-security/kali-nethunter#232]
when i open kali  shell in terminal
![screenshot_2015-08-12-19-36-39](https://cloud.githubusercontent.com/assets/7133339/9238663/a0d78848-412a-11e5-9487-96e1d0273ccb.png)
when i open kali menu
![screenshot_2015-08-12-19-51-11](https://cloud.githubusercontent.com/assets/7133339/9238803/9a4bc024-412b-11e5-8e1b-7f1abbd54c6a.png)

hi, this is what i get after installing nethunter 2.0 (downloaded from official page).
I also flashed my nexus bact to stock and went through all the process again but got the same result.
Device: Nexus 7 2013 WIFI
Rom: android 4.4.4 
![screenshot_2015-08-12-19-49-10](https://cloud.githubusercontent.com/assets/7133339/9238772/5a9c5a24-412b-11e5-9fc7-33c398da52c7.png)
kali_linux_nethunter_2.0_razor_kitkat.zip

UPDATE:
I also noticed that the istallation,  wich would take about 30 minutes, finishes in only 1 or 2 minutes.
Hereare some screenshot of the installation:
![recscreen_12_201346](https://cloud.githubusercontent.com/assets/7133339/9239098/e03a684e-412e-11e5-841a-28f3b89bbad0.png)
![recscreen_12_201406](https://cloud.githubusercontent.com/assets/7133339/9239099/e5ccd878-412e-11e5-85f0-0af012de038e.png)

**Comment by braichucha** [comment]
i have the same issue on my Oneplus One.

**Comment by binkybear** [comment]
@braichucha - Are you using kitkat or lollipop.

@TonyH4 - You seem to have a kali shell in the first picture but you are def missing /usr/bin/kalimenu.  It's possible that your kali-armhf was never replaced.  

I'm going off memory, but an easy fix to remove old kali would be to go into TWRP > advanced > file manager.  Click the folder in /data/local/kali-armhf and delete.  Then try to reinstall zip file.  It's possible that old kali is sticking around and they are conflicting.

Let me know if this helps.

**Comment by braichucha** [comment]
im using lollipop. anyway, i dont think the old kali is conflicting with the new one as i did a full format.

**Comment by binkybear** [comment]
@braichucha - I've done a full format (in TWRP) and have had kali-armhf still there.  I'm not saying that that's the case but something to keep in mind.

**Comment by braichucha** [comment]
that's good to know, okey maybe i was mistaken, but hey, so, kali-armhf is there but is it functioning?(the kali-armhf existed on my system but i had the same problem as the one who created this issue) are you using a oneplus one?

**Comment by binkybear** [comment]
I'm not having any issues with oneplus.  I assume if it's still there then there could be any issues with trying to install on top of it (i.e. mounted folders/read only files).  You have a better chance of removing it in recovery then while in system.

**Comment by TonyH4** [comment]
hi @binkybear ,thanks for the quick replay, i´ve tried you solution but got no luck, the installation is still taking just 1 or 2 minutes (when it should be taking about 30), can you give me a link to the older version (i have deleted from my drive and in the oS oage there aree only the latest version).

**Comment by braichucha** [comment]
@binkybear okey its there, but is it functioning?

**Comment by binkybear** [comment]
@TonyH4 - images.offensive-security.com/kali_linux_nethunter_1.22_bacon_kitkat.zip

**Comment by binkybear** [comment]
@braichucha - I dont know if its functioning.  You can boot into your system and run terminal then type bootkali.

**Comment by braichucha** [comment]
i've already downgraded to 1.22... i was asking you that because im considering upgrading to 2.0 again, maybe i skipped the part where i full format...

**Comment by binkybear** [comment]
@braichucha - Sorry for confusion.  1.22 was for kitkat and 2.0 had the option of kitkat or lollipop.  You should be able to install the 2.0 kitkat over the 1.22 without any issues (usually) and without formatting.  But I'm not quite sure whats causing your problems at the moment.

**Comment by braichucha** [comment]
okey... @binkybear ill do the following... listen... ill do a full format and then ill try 2.0 for kitkat... 2.0 for lollipop didnt worked last time(as i said maybe i made a mistake).
ill be back and ill tell you how did it go... understood?

**Comment by TonyH4** [comment]
can you give me the kitkat version for razor device?

**Comment by binkybear** [comment]
@TonyH4 : images.offensive-security.com/kali_linux_nethunter_1.21_razorg_kitkat.zip

**Comment by braichucha** [comment]
it work perfectly on my oneplus one on kitkat with nethunter 2.0. yet what are the changes between 1.22 and 2.0?

**Comment by TonyH4** [comment]
Thanks @binkybear ... The v1.21 worked fine after flashing the zip. I really don't know what may the issue be... I will try the v2.0 under lollipop.
Which version of lollipop nethunter supports (5.0, 5.1, 5.1.1)?

**Comment by 0m364** [comment]
Im on 5.1.1 and running fine n5 2.0 how do I get Kali sana on my Linux deploy ?? I'll be the test dummy I'm about to test changing the repository address inside the Kali install in Linux deploy

**Comment by TheBlackRabbit** [comment]
sorry to break this to you but many of us have been playing with the sana
repos for a couple months or more now after flashing custom kernel builds.
LD should pull the new 2.0 arm-hf image sp changing repos shouldn't he
neccessary. Unless your uncommenting your deb-src

**Comment by 0m364** [comment]
Thank you...

**Comment by 0m364** [comment]
Thank you..... Mine is still pulling 1.x... Backing up and factory reset
when I get home to try again
