### ISSUE TITLE
HID Attack - end user DLP solution bypass

### ISSUE THREAD

**Issue by kokos300** [offensive-security/kali-nethunter#233]
Hi all !

I was wondering if it is possible to bypass the Mcafee DLP end point security for usb on my pc. The HID keyboard attack suppose to make the usb drive to present itself as keyboard device and therefore bypass the dlp security as my other peripherals do (keyboard and mouse). When i connect my nexus 5 on the pc it begings downlading and installing drivers for nexus 5, HID and MTP(media device) and automatically blocked by the DLP solution.

Is there a way that i can turn off the drivers for nexus 5 and MTP in order to avoid notifying the DLP ?? 
I have manage to find how to disable the MTP and now the drivers are not downloading for it.

But i still can observe the nexus 5 drivers and I am getting blocked again and again...

Can you please provide me with a solution to this problem ??

Regards..

**Comment by thesle3p** [comment]
I don't know how to do this with Nethunter but with a teensy it can be done by changing a constant in the sketch, maybe Nethunter should have the option to specify a USB vendor ID to bypass such protections? I would make it where you at a user's request the nethunter app could download http://www.linux-usb.org/usb.ids and Nethunter would parse it and allow you to select a USB vendor ID to spoof based on what brand of keyboards you identify as being plugged into the target.

**Comment by binkybear** [comment]
@thesle3p - I haven't experimented with this but you "should" be able to change vendor ID's on android.  I belive it would be located here if you use the terminal or adb on android device:
```bash
su
cat /sys/class/android_usb/f_hid/device/idVendor
05c6
cat /sys/class/android_usb/f_hid/device/idProduct                              <
6765
```
I assume thats where you might be able to emulate vendor/product.

**Comment by thesle3p** [comment]
Cool, though what I outlined would be a nice, fast way of doing this in
Nethunter ;)

**Comment by kokos300** [comment]
Thanks for your reply !

I have experimented with your suggestions.

I have checked my keyboard id number (HP PR11010) and found the corresponding value for linux in the website that you have provided (http://www.linux-usb.org/usb.ids). The ID can be seen in the screenshot below:

![productid](https://cloud.githubusercontent.com/assets/13798635/9763508/9ba70350-5712-11e5-815f-e41e6508ccc9.PNG)

Then i changed the configuration files that you provided with the numbers found in the screenshot:

/sys/class/android_usb/f_hid/device/idVendor  --> This changed to 0461 

/sys/class/android_usb/f_hid/device/idProduct --> This changed to 0010

I have restarted my nexus 5 and run the HID keyboard attack once again but with no results again :(

When I turn on the Media Device (MTP) or enable the debugging mode the device is getting blocked by the Mcafee DLP end point security. When I turn those things off nothing happens but the attack still is not working.

Do you have any other ideas on how can i proceed with this issue ? 

Regards..

**Comment by thesle3p** [comment]
Try setting the idVendor and idPRoduct values without rebooting the device.

**Comment by kokos300** [comment]
I have tried without rebooting the device as well. The result is the same,
the attack is not happening.

I am sure that there is no problem with the attack configuration because it
is working fine without the DLP usb protection.

**Comment by binkybear** [comment]
I'm just throwing out ideas but if we look at the ramdisk we can see how they set the idProduct and idVendor at boot depending on device:

https://github.com/binkybear/kernel_msm/blob/android-msm-hammerhead-3.4-lollipop-release/ramdisk/source/init.usb.rc#L40

I'm not sure if this would totally take over usb (until reset).  But an equivalent way to set id/vendor with phone running would be a bash script on the android side, not chroot:
```bash
# Turn off USB
echo '0' > /sys/class/android_usb/android0/enable
# Set Vendor and Product
echo '0461' > /sys/class/android_usb/android0/idVendor
echo '0010'  >/sys/class/android_usb/android0/idProduct
# Set hid as the function
echo 'mtp,adb,hid' > /sys/class/android_usb/android0/functions
# Reenable
echo '1' > /sys/class/android_usb/android0/enable
```
It could be saved in /data/local/hidtest.sh and run from phone.

**Comment by kokos300** [comment]
Thanks binkybear !

The script that you have provided me is working !

I have now manage to execute the attack bypassing the Mcafee DLP end point security.

Thanks a lot :)

**Comment by binkybear** [comment]
Glad it worked!  I will point people to this issue if it comes up again.
