### ISSUE TITLE
BadUSB and HID attacks don't work on Nexus 7 GSM (2012) KitKat

### ISSUE THREAD

**Issue by shlyahten** [offensive-security/kali-nethunter#235]
HID attacks doesn't work on my tablet. Windows can't recognize it (driver error). I'm tring other windows PC - same trouble. 

**badusb.log:**
    iptables v1.4.11.1
rndis,hid
1

I'm tring with terminal too - no error messages in terminal output. So busybox and necessary services are working good.

**Comment by binkybear** [comment]
@shlyahten - Are you using a VM or actual box for hid attack?  Do you have a /dev/hidg0 on your android device?  Have you tried turning off mtp?

**Comment by shlyahten** [comment]
@binkybear Yes I have /dev/hidg0 and /dev/hidg1 (0 bytes). Tried to turn off|on mtp.

**Comment by binkybear** [comment]
hidg0 is keyboard and hidg1 is mouse so you should be able to send commands with hid.  If you are using a VM it sometimes has a hard time recognizing as keyboard (vmware especially).  What type of driver error are you seeing?

**Comment by shlyahten** [comment]
@binkybear I tried with VM anв have message about driver error, then I tried with normal windows 10 and windows 8.1 on different PC's. When I tap "Execute attack" or "start badusb" on device I have rndis0 up, but on PC in device manager I don't see any new network adapters or new devices.

**Comment by 0E800** [comment]
I think I am having similar issues on N7-2012.Loli(wifi). Is Windows supposed to recognize the device in order for the BadMitm to work? I watched the instructional video but I am not seeing packets show up.

MTP is disabled

`root@kali: # start-badusb-lollipop`
`iptables v1.4.21`
`rndis,hid`
`1`

`ifconfig -a = dummy0, ip6tn10, lo, p2p0, rndis0, sit0, wlan0`

tcpdump -i rndis0 -v
(pinging google.com on testpc, nothing showing up on tcpdump.)

Anything else I can try?

testpc = Win8.1 x64

**Comment by binkybear** [comment]
Badusb should be fixed in latest app: 

https://github.com/offensive-security/nethunter-app/commit/a0ea92a60a663b52504d6b881493d7cedc42a6b1
