### ISSUE TITLE
Chroot broken on Nexus 9

### ISSUE THREAD

**Issue by PentesterNL** [offensive-security/kali-nethunter#236]
Hi, 

I installed Nethunter 2.0 on a brand new Nexus 9, but the path of the chroot seems to be broken. I cannot run apt-get (even after a su -) and half the scripts give errors because of "command not found" errors.

How do I solve or troubleshoot this? Any help is GREATLY appreciated!

**Comment by binkybear** [comment]
@PentesterNL - Is it possible to verify that you have all your folders in /data/local/kali-armhf such as /usr/bin?

**Comment by PentesterNL** [comment]
Hi Binkybear,

Thanks for getting back to me! (And thx for the awesum nethunter development!)

Yes all of the commands are in /data/local/kali-armhf/usr/bin/ including apt-get

However if I try to run ./apt-get I end up with:
tpm-mksh: ./apt-get: no such file or directory

Does not matter if I do a SU first. Could this be a $PATH issue?

echo $PATH gives me:
/vendor/bin:/system/bin:/system/xbin

**Comment by PentesterNL** [comment]
Oh, and this is only from within the chroot which you get when you open the kali menu. If I open kali terminal and drop to the shell, I can run apt-get just fine (as root)

**Comment by binkybear** [comment]
@PentesterNL - It looks like the PATH is not getting copied over correctly from app or bootkali.  Those paths are for outside chroot (android system).  A quick fix might be to modify bootkali path statement in /system/xbin/bootkali.  At least it appears that everything is working so if you needed to get into bootkali > kalimenu from terminal that would work.

I will add this to my list of things to look at it.

**Comment by PentesterNL** [comment]
Hi,
Thanks. I am looking at /system/bin/bootkali but I am a little confused about the fix... there is an export PATH statement, but it seems none of the paths in there are actually copied over to the chroot. Am I looking at the ctorrect statement for this fix?

I would be happy to test this out so nethunter will run ok on the Nexus 9.

**Comment by binkybear** [comment]
https://github.com/offensive-security/kali-nethunter/blob/kali2/flash/system/bin/bootkali#L296

```bash
su
mount -o remount,rw /system
nano /system/bin/bootkali
```
Modify line 296 (link above) to:

LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/kalimenu

**Comment by PentesterNL** [comment]
Dude, that is awesome! It fixes a lot of errors right away. Beef is giving me a file not found, but will try to figure that out myself (now I knkw where to look). Will reboot now, hope the changes are persistent :-)

Keep up the good work!1

**Comment by PentesterNL** [comment]
Yes the fix is persistent. You made me an happy man, cant wait to play with the tools.

Thank you for your GREAT support. If you ever visit the Netgerlands, let me buy you a beer!

**Comment by PentesterNL** [comment]
One last question, I get:
/usr/bin/kalinenu kine 469, /opt/MITMf not found 
When starting the mitm tools. Is there a similar fix?

**Comment by binkybear** [comment]
@PentesterNL - You could install MITMf manually inside chroot inside the /opt folder: https://github.com/byt3bl33d3r/MITMf/wiki/Installation
