### ISSUE TITLE
Beef login

### ISSUE THREAD

**Issue by evertking** [offensive-security/kali-nethunter#237]
When I run BeEF I don't get a login page. I get the ui/auth and that's it.

**Comment by sqz0** [comment]
Same issue... I think it's an issue with ruby, although I'm probably wrong. Tried removing beef-xss and git cloning again, "bundle install" didn't like the more recent libv8-3xxxxx... Got frustrated and gave up... Fresh install of NH, still no joy.. Will come back with more soon

**Comment by jermzz** [comment]
I'm having this issue too. Just beef logo. I see when I run from panel it gives a ruby error for loading the UI auth. Started researching and found beef only runs on ruby 1.9? I wanted to try that so I 

Apt-get remove ruby 
Apt-get install ruby1.9

Still installed ruby 2.1 I domt know why, but issue persisted. 

So then I tried rvm, and forced ruby 1.9.2. Everything checkout out, I set the environmental variables, but then I started getting beef script errors and it wouldn't even start the script. 

Tried with KitKat 4.4.4 And lollipop 5.0.1

I'd like to know how others on nexus devices are getting this working properly. I'm out of ideas, and next step is to go back to Fry's and return this tablet.

**Comment by binkybear** [comment]
How is everyone starting beef? I am able to run it on oneplus (CM12) with Kali 2.0 by:
```bash
service beef-xss start
```
I even tried:
```bash
cd /usr/share/beef-xss
./beef
```
Then browsing to: 127.0.0.1:3000/ui/panel works for me also.  But seeing that it's not isolated I need to get an idea what could be causing issue.

**Comment by evertking** [comment]
I have tried one OnePlus and my nexus 5 and both have the same issue. But
I'm using KitKat on both. Cm on the OnePlus and pa on the nexus 5. Only way
I have tried is starting the service and get a browser pop up and the I
change the URL to ui/panel but nothing, on both.

**Comment by jermzz** [comment]
I've tried everything. Kitkat and lollipop. It's definitely a ruby issue. I even tried configuring the metasploit plugin to launch beef from the msf console. I just get more ruby errors. 

Are people not using beef on the nexus, or what?

**Comment by sqz0** [comment]
Tried ` service beef-xss start ` open browser > "htttp://127.0.0.1:3000/ui/panel" 
Just the beef logo..
Tried ` cd /usr/share/beef-xss `
 `./beef ` 
and
 ` ruby beef `
 open browser http://127.0.0.1:3000/ui/panel
Just the beef logo 
tried tried the proxy address, same..  
Am using a Nexus7 2012 nagasaki 2.0 .. Beef in all previous versions of Kali have worked
will try removing ruby and installing ruby 1.9 next

will be back with screenshots later

**Comment by sqz0** [comment]
http://imgbin.org/index.php?page=image&id=25942 1
http://imgbin.org/index.php?page=image&id=25943 2
http://imgbin.org/index.php?page=image&id=25944 3
http://imgbin.org/index.php?page=image&id=25945 4
http://imgbin.org/index.php?page=image&id=25946 5
http://imgbin.org/index.php?page=image&id=25947 6
skipped the photo of loading modules
http://imgbin.org/index.php?page=image&id=25948 7

**Comment by jermzz** [comment]
That's the exact same error I get. I'm on 2013 wifi nexus 7. My regular dist Kali on my MacBook works fine with beef and metasploit plugin on ruby 1.6.2 with rvm.

**Comment by binkybear** [comment]
@sqz: Thanks for the screenshots.  Do you see anything listening on 3000 if you do a netstat?  Can you try doing a netcat and seeing if anything returns?

**Comment by sqz0** [comment]
@binkybear Hi, netstat is showing listening ports for beef 3000 6789. Tried netcat, I'm not too affay with it.
 Tried ` nc -v 127.0.0.1 3000` and

` nc -vs 127.0.0.1 3000`
it showed the port as open, but the protocol unavailable?. I'll come back with screens when I've proper access... And a better understanding of netcat...

**Comment by sqz0** [comment]
http://imgbin.org/index.php?page=image&id=25979 beef running with purdy acsi art

http://imgbin.org/index.php?page=image&id=25978 netstat and netcat

**Comment by Jorandobnl** [comment]
I have exactly the same issue on my nexus 7 2013 

I think beef cannot find /ui/media/javascript-min/web_ui_auth.js 

Maybe someone else can check this

![screenshot_2015-09-17-23-34-19](https://cloud.githubusercontent.com/assets/4313089/9946611/ac4be774-5d94-11e5-8e2a-06ee7774b587.png)

**Comment by jermzz** [comment]
Confirmed, the U.S. files are not present in the directory. I'll push them to the SD card from my desktop Kali when I get home and report results back.

**Comment by jermzz** [comment]
*js files

**Comment by jermzz** [comment]
Ok, I fixed it. Beef is up and running properly on my 2013 nexus 7 wifi. Here's how I fixed it. 

First I tried moving the two js files over to the nexus, I was able to get the login UI up that way, but I was still getting all kinds of errors as it was running. I wasn't sure what other files may be missing so I went to my LIVE USB Kali install and dropped the whole beef-xss file to the SD card of the nexus, then 

rm -rf /usr/share/beef-xss/
mv /sdcard/beef-xss /usr/share

Then type this command into the terminal before you start beef:

export LC_CYTPE=en_US.UTF-8

Then navigate to beef dir and ./beef

Hope this works for you guys too.

**Comment by jermzz** [comment]
Above command only worked for one reboot. Use these to make it work every boot. I dunno how to make it perm. Maybe someone else can chime in. Dunno if you wanna permanently change encoding though. Hopefully someone who knows more about it can chime in. But metasploit, postgres, beef all up and running with those files and these commands:

# from your command line
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

**Comment by binkybear** [comment]
Thank you all for tracking down issue, this was added to bootkali and will be fixed in next update.
