### ISSUE TITLE
Nethunter 2.0 not working on YOG4PAS1N0

### ISSUE THREAD

**Issue by braichucha** [offensive-security/kali-nethunter#240]
I did a blank slate installation and it got stuck on boot loop.

**Comment by citymonk** [comment]
Hi @braichucha .After trying multiple solutions from various sites and mixing them , the Nethunter was flashed properly.

The steps I followed :
1.I flashed the YOG4PAS1N0 64GB image by following the steps from this link http://forum.xda-developers.com/oneplus-one/general/guide-return-opo-to-100-stock-t2826541. This will install CM12 on the mobile.
2.Used Windows Installer from http://www.nethunter.com/download/ till the step to flash the stock rom.(This will downgrade the system to CM11)
3.Downloaded the Kali Nethunter zip file for CM11 , from the Nethunter download page https://www.offensive-security.com/kali-linux-nethunter-download/
5.The install was successful after reboot.

ps : Also found that upgrading too CM12 after Nethunter installation , and also to 12.1 didn't give me any issues.

**Comment by braichucha** [comment]
wait wait, you got your COS12.1 working with nethunter?

**Comment by binkybear** [comment]
I have updated to latest kernel for testing: https://transfer.sh/18F3pH/kernel-kali-oneplus.zip  

This contains latest ramdisk and possible wlan1 reboot fix.

**Comment by braichucha** [comment]
thanks @binkybear. i just mailed you for a las build of kali nethunter or a nightly

**Comment by citymonk** [comment]
@binkybear  Can this be flashed over 12.1 ?

**Comment by citymonk** [comment]
@binkybear  I flashed the new kernel on Nethunter/CM11 and it was struck at the 1+ logo .

**Comment by braichucha** [comment]
im trying to update OTA incremental from COS12 to COS12.1 with nethunter installed but i get "error executing updater binary in zip". im gonna explode my phone to pieces.

**Comment by citymonk** [comment]
@braichucha I think COS 12 to 12.1 happens with out any issue but the Nethunter tools are not compatible. In any case lets see what @binkybear  has to say as to whether the new Kernel he compiled is compatible with COS 12.1 . It didn't work for me with COS11 . 

I am re-flashing old build using yesterday's method to keep my phone on track.

**Comment by citymonk** [comment]
Wait , I see something fishy , I see only 1Gig RAM lost , it shows only 1.8 GIG something on my mobile.Do I need to factory reset my phone ?

**Comment by braichucha** [comment]
@citymonk @binkybear said something about the ramdisk. maybe thats the problem

**Comment by TheBlackRabbit** [comment]
The error is most likely due to OS key validation. For example, a partition issues goes unnoticed during a dirty flash from one version of AOSP/CM to another, either from a previous ROM flash or restore from TWRP after taking an OTA. 

The issue seems to be caused by residual build.prop data, specifically lingering android os test/release keys which correspond to what is supposed to be your currently installed version of Android. For example even though you flashed or took an OTA to 5.0.2 (CM12), when taking an OTA to 5.1.1 (CM12.1) the OTA fails. When recovery checks your android os version it's catching the leftovers from a previous flash which in this case would most certainly be keys for CM11, stock flashed or otherwise.

Try a clean wipe, (including user.data and recovery) flash stock CM11 take OTAs up till CM12.1 THEN root/recovery/busybox/nethunter. 

This should keep your keys in proper order and give you a more solid base line to tinker with. Also, the "update recovery" option in CM can cause issues so I would read up a bit on that as well. (due to the new approach to system partition management in CM12.x)

**Comment by braichucha** [comment]
@TheBlackRabbit thats not an option. when i flash a nethunter build into COS12.1 i get a bootloop.
what im trying to do is to OTA from COS12 with NH2.0 to COS12.1.

**Comment by citymonk** [comment]
@TheBlackRabbit   Thanks for the response !!
 
I flashed Stock rom COS 11 , then flashed Nethunter using the Zip file from the Nethunter official download.I was able to recover my lost RAM . The OTA updates pushed in ,now I'm on 12.0-YNG1TAS213 but the Nethunter tools are missing , I lost my root permissions too.

@braichucha  @binkybear 
So , I think we can confirm that Flashing Nethunter official zip on the Stock ROM/COS 11 will work , it is not stable and is behaving weird with COS 12 and above versions.

Let me know if any of you guys find out if Nethunter is working on COS12 and about. I will take rest for the day!! Adios!!

**Comment by TheBlackRabbit** [comment]
Try searching xda for a firmware fix, I've heard around that it works for CM12.1 boot looping (pretty common issue actually)

It may only be fast boot flash, doubt that'll be a problem. Good luck. 

I'm fortunate a total wipe + flash-stock/root/busybox/nethunter worked out for me.
(Fyi: via latest Android SDK/ADB/Fast boot on a AMD x64 4.8GHz vishera w/ 32GB DDR3 w/ Kali Linux 2.0 sana)

**Comment by TheBlackRabbit** [comment]
It was working, but had to patch up some config/etc. Trying new kernel from @binkybear right... now.

**Comment by braichucha** [comment]
@TheBlackRabbit you managed to get working NH2.0 on COS12.1?

**Comment by binkybear** [comment]
So the latest kernel is for factory image: YOG4PAS1N0 which CM12.1.  Sorry, the problem with Oneplus is they have the nightlies and the factories.  I have an anykernel2 option which doesn't rely on the ramdisk and it worked for me:

https://transfer.sh/q0viF/oneplus-lollipop-remove-notifier.zip

But this is also for 12.1 but will probably on both factory and nightlies.

**Comment by citymonk** [comment]
@binkybear  Thanks man , Currently , I  flashed stock 12.1 with out root.I will try this out in tomorrow and will let you know how it goes.

**Comment by S0bek** [comment]
Thanks for your contribution all. I successfully updated the last COS 12.1 witj COS and KNH but had some issues with binaries too on my side... Hope future images will work with other ROM one day like blisspop or exodus.

**Comment by citymonk** [comment]
@S0bek  So , what do you say about the new build , is it working with COS 12.1  , should I apply it or wait ?

**Comment by highchecker** [comment]
Von: citymonkGesendet: Samstag, 19. September 2015 01:32An: offensive-security/kali-nethunterAntwort an: offensive-security/kali-nethunterBetreff: Re: [kali-nethunter] Nethunter 2.0 not working on YOG4PAS1N0 (#240)@S0bek  So , what do you say about the new build , is it working with COS 12.1  , should I apply it or wait ?

**Comment by Shnilj** [comment]
I tried COS12.1 (and CM12.1) with the oneplus-lollipop-remove-notifier.zip and the kernel-kali-oneplus.zip from further up this thread, neither seemed to work correctly. I either get a '+1 logo bootloop' or I get the +1 logo, Cyanogen or CyanogenMod logos that get stuck indefinitely. COS12 seems to work correctly (need to test further to confirm), except sometimes my OPO reboots/sticks when using the WN722N wireless adapter.

If by any chance I can help by testing ROMs, kernels, etc shoot me a mail/message.

**Comment by citymonk** [comment]
Same here , Nethunter isn't working on 12.1 COS . :(

**Comment by S0bek** [comment]
No it's not working with COS 12.1. Bootloop with setup and tools don't work with just the update.
 
All CM12 lastest nighlies don't work with KNH ramdisk and kernel. 

That's what I tried personaly  and read on the XDA forum. 

android_menu.sh + the kernel compilation for custom ROM didn't work for me neither with recent ROMs. The only one to work currently is COS 12 and old CM12 nighlies.

**Comment by l0rdg3x** [comment]
https://github.com/offensive-security/kali-nethunter/pull/215#issuecomment-142275382
wait for binkybear, when he accept my pull request (https://github.com/binkybear/AK-OnePone/pull/1)
Kali NetHunter will work on COS12.1

**Comment by binkybear** [comment]
I have an update with @l0rdg3x fixes for anyone that wants to try.

NH update image: https://transfer.sh/jF4JE/update-kali-oneplus-wlanfix.zip
Kernel only: https://transfer.sh/mjNqs/kernel-kali-oneplus-wlanfix.zip

**Comment by citymonk** [comment]
@binkybear  shall I directly flash on stock 12.1 ? Did it work from your side , I can try by flashing on my mobile.

**Comment by binkybear** [comment]
@citymonk - Should be flashed on stock 12.1.  I haven't tested this one, it's built straight from the menu with the kernel updates. 

I've been using a new method to flash using AnyKernel2 along with a new app.  If anyone is interested in testing that one let me know.

**Comment by Shnilj** [comment]
I tested the new NH update image on stock 12.1 and it seems to work flawlessly. Thanks @binkybear !

**Comment by Shnilj** [comment]
Nog sure if this is related but after flashing the NH update image my music playback seems tot be a little buggy. Sometimes it works, other times no sound at all.

I will try to find out if this issue is relared to the NH update or nog and open a new issue if it is.

Just wanted you to know :)

**Comment by binkybear** [comment]
@Shnilj -  Thanks for testing and I'm glad it's mostly worked for you.  I'm running the kernel and haven't noticed music playback issues at the moment but if anyone else notices let me know.  Nothing was changed music/volume wise.  I'm leaning toward more of a CM 12.1 issue.

**Comment by kendallgreen** [comment]
Installed NH update image and SuperSU on cm12.1 using TWRP 2.8.7.0. got past the 1+ logo. Updated kali chroot. Took about 1 hour. Wifite works.

**Comment by binkybear** [comment]
Everything should be working in next release/current github builds on newinstaller-fj.
