### ISSUE TITLE
rubber ducky file access

### ISSUE THREAD

**Issue by NoobieDog** [offensive-security/kali-nethunter#247]
On the rubber ducky, there is no option to load a pre made script other than overwriting the existing file.

I will have a go at writing this, any fix from your end would be nice!

Stu

**Comment by aemaeth2501** [comment]
There is (or will be) in the future update.
This load/save fucntionnality has been integrated in this PR:
https://github.com/offensive-security/nethunter-app/pull/36

**Comment by binkybear** [comment]
@aemaeth2501 - This was merged and is included in the latest release. (Thanks)  I think NoobieDog is referencing something else.
