### ISSUE TITLE
wrong use oft su in kalimenu.sh

### ISSUE THREAD

**Issue by mame82** [offensive-security/kali-nethunter#254]
The f_msuser() sub can't be working like expected, because "su postgres" invokes a new shell. The commands which should be run as user postgres (line 1210 to 1213) are runned after closing the subshell. There's no need for "su root" afterwards. The needed commands should be exported to seperate script or a sub which could be called using commandline-arguments to kalimenu, which could be used like "su postgres -c 'kalimenu init-postgres-db' " for example. 
Additionaly a database.yml could be created with the right values, thus there would be no need to call "db_connect" from within metasploit.

**Comment by binkybear** [comment]
Kalimenu is gong away, closing issue.
