### ISSUE TITLE
error in keyseed.py

### ISSUE THREAD

**Issue by mame82** [offensive-security/kali-nethunter#255]
The bytesequence for char '\x5c'  should start with "\x40" for RALT instead of "\x05" in dict_de (line 377 keyseed.py), otherwise a backslash doesn't get send.

The bytesequence for '\x2c' should start with "\x00" instead of "\x20" in line 325, otherwise a ',' get's converted to a ';' using a german layout.

**Comment by binkybear** [comment]
Please take a look a let me know if that fixes issue for you.
