### ISSUE TITLE
nethunter.apk needs to be updated

### ISSUE THREAD

**Issue by mame82** [offensive-security/kali-nethunter#256]
The delivered nethunter.apk Needs to be updated in order to make HID and duckhunter work using the  launcher (see issue #47 nethunter-app).

**Comment by binkybear** [comment]
@mame82 - Uploaded a new build with hid/duckhunter quotes.  Would you like to test?

**Comment by PommyGit** [comment]
Im willing blinky. i have the Samsung Galaxy s$ GT-9507 I am learning to port. Aus and HK are the only places with this variantso little support. I have finally managed to build A working Kernel with rtl8187 support. After rivers of tears and complete frustration. I want to see if your app can do it the easy way.

**Comment by binkybear** [comment]
@PommyGit - Send me an email binkybear@nethunter.com.  I can see about walking you through newinstaller git branch.
