### ISSUE TITLE
Need Help for OnePlus 2!

### ISSUE THREAD

**Issue by PurvC** [offensive-security/kali-nethunter#259]
Is the Kali Nethunter ready for OnePlus 2? If yes, then how can I download it?

**Comment by PurvC** [comment]
@binkybear Please Close this thread, I resolved my issue. Thank You for the 'newinstaller'!

**Comment by binkybear** [comment]
@PurvC - I need to fix extract chroot but should be working in the next couple of days (newinstaller).

**Comment by PurvC** [comment]
![screenshot from 2015-10-30 20 03 18](https://cloud.githubusercontent.com/assets/15320237/10848514/3daf7ffe-7f42-11e5-9a98-b05ce7aa2cac.png)
@binkybear Something needs to be fixed in build.py!
                    After every download it's showing "Finished Download All Apps".

**Comment by jmingov** [comment]
Hey @PurvC 

Looks like only the text is wrong (the build should fine)

Any way, its fixed tho.

**Comment by PurvC** [comment]
Hey @jmingov so what about 'No Arguments Supplied'?

**Comment by jmingov** [comment]
Well, the script can accept more than 1 argument so you can do for example:

    python build.py -d hammerhead --lollipop

But in the case of:

    python build.py -f

After the downloads the script checks if there are any other arguments remaining for processing.
If not, it shows that msg.

If @binkybear  confims that we dont want to chain the `-f` with other options like `python build.py -f -d hammerhead --lollipop` we just need to add:

    # lines 268 to 271
    if args.forcedown:
        supersu()
        allapps()
        exit(0)

And the error will be gone.

Anyways the -f step is executed without err.

**Comment by PurvC** [comment]
@jmingov Thank You!
If I find something else, I'll notify you. :)
