### ISSUE TITLE
Nethunter 2.0 on Nexus 9 results in endless loop of errors

### ISSUE THREAD

**Issue by glynx** [offensive-security/kali-nethunter#260]
On my Nexus 9 (Wifi version) Nethunter 2.0 the system starts with an endless loop for "Unfortunatly, Nfc Service has stopped" and "Unfortunately, Nfc Service has stopped" which makes the system totally unusable.

If required tell me if you need additional log information to resolve this issue

**Comment by binkybear** [comment]
@glynx - What version of Android are you running?  Did you install over clean/stock facotry image?

**Comment by glynx** [comment]
I tried both 5.0 and 5.0.1. The images were clean factory images downloaded from https://developers.google.com/android/nexus/images?hl=en 

After the installation they were rooted via Chainfire / Nexus Root Toolkit

For the installation of the ROM I tried Flashify and ROM Manager. MultiROM Manager which I would prefer is not yet available for Nexus 9. In addition TWRP was used.

**Comment by binkybear** [comment]
I believe you should be on 5.1.1.  The bootloop is mostly caused by incorrect ramdisk from the kernel.

**Comment by glynx** [comment]
Thank you, that did the trick. 

I did the following setup to get it up and running:
Factory Image: 5.1.1 (LMY48T)
Rooting via Nexus Toolkit
Installation of BusyBox 
Installation of Nethunter via SD Card and ROM Manager

The download page only claims it the Nethunter image is for Lollipop and does not specify any requirements for the version. Because there is currently no official guide and [guide in the forum](https://forums.kali.org/showthread.php?27431-How-to-safely-install-Nethunter-2-0-on-any-supported-device) also doesen't mention it. It would be helpful to put this information somewhere on the site.

**Comment by binkybear** [comment]
Glad that did the trick.  Yes, adding the version to the website would help. I always try to keep up with the latest versions for security issues/patches.
