### ISSUE TITLE
Fix For Building chroot

### ISSUE THREAD

**Issue by viperblood** [offensive-security/kali-nethunter#261]
Hello, i was running into some problems building a rootfs seems like kali removed the "kali" option from the dist list, this is how i got it to work:

Error: I: cant retrieve release http://http.kali.org/kali/dists/kali

Line #598: debootstrap --foreign --arch $architecture kali kali-$architecture http://http.kali.org/kali

Fix: debootstrap --foreign --arch $architecture sana kali-$architecture http://http.kali.org/kali

**Comment by binkybear** [comment]
Hi @viperblood 

Yes it was switched to sana (like you mentioned), I updated it in newinstaller branch: https://github.com/offensive-security/kali-nethunter/blob/newinstaller/nethunter-fs/stages/stage1#L217

I will fix main branch in the meantime.  Thanks!

**Comment by viperblood** [comment]
I tried the new installer aswell, however it didn't work right. Perhaps the files aren't fully uploaded ?

I will retry , thanks !

**Comment by binkybear** [comment]
@viperblood - There's a few things I need to check with the installer, the extract chroot script mostly.  It was designed originally to work with the fattire so I'm porting some things over.  It's possible something didn't work quite right.

Are you on IRC?  I would like to chat with you on freenode #nethunter or by email so I don't clog up this issue.

**Comment by binkybear** [comment]
Did a build last night and everything seems to be fine.  Closing issue.
