### ISSUE TITLE
Kali Nethunter kernel for OPO Cm12.1

### ISSUE THREAD

**Issue by AndyKr0p** [offensive-security/kali-nethunter#264]
Hey there,

I played with OTA for CM12.1 and overwritten kali nethunter kernel. How I can restore it without flashing all image?

Regards,
Andy

**Comment by binkybear** [comment]
This works for me on latest OTA: https://transfer.sh/ILwyu/kernel-kali-oneplus.zip

**Comment by AndyKr0p** [comment]
Many thanks @binkibear!
