### ISSUE TITLE
OnePlus 2, Flash Help!

### ISSUE THREAD

**Issue by PurvC** [offensive-security/kali-nethunter#265]
@jmingov @binkybear Hey Guys!

Can I flash the .zip file made through AnyKernel2 on the OxygenOS, or should I wipe the Data and the Cache first?

**Comment by jmingov** [comment]
Hello @PurvC ,

A clean install is allways good, i dont have a OP2 to test at the moment a dirty flash but it can work too.

> Since you are testing the new build in a new device, i recomend a clean flash. (So we avoid the posible (non-related) dirty flash problems)

(If you do a backup of the phone, so you can test roms, apk's ... then restore the backup so you dont lose settings configs etc..) But dont mix diferent nethunter versions.

**Comment by PurvC** [comment]
Hey @jmingov, 

As written in the README.md,

What is Nethunter?

Kali Linux Nethunter is not a ROM but is meant to be installed over an existing stock/factory image of Android. It can be installed over some Cyanogenmod based ROMs. It is heavily based on using custom kernels and only supports a select number of devices.

So I just wanted to ask if it would run on the OxygenOS!

**Comment by jmingov** [comment]
@PurvC , this is the answer about OxygenOS: https://github.com/offensive-security/kali-nethunter/issues/228

Recomendation:  flash CyanogenMod for OP2 then nethunter on top of it.

Maybe @binkybear has a kernel for it arround.

**Comment by binkybear** [comment]
If you are using the new installer branch there are two folders:

https://github.com/offensive-security/kali-nethunter/tree/newinstaller/AnyKernel2/kernels/lollipop

OnePlus2 is for OxygenOS and OnePlus2CM is for...CM.  Otherwise, main branch was tested only on CM.

**Comment by TheBlackRabbit** [comment]
Got my OP2 in September, been build/flashing nightly for the past week or so.. Due to the awesome newinstaller-fj. Works best and perfectly on Oxygen 2.1.1 and cm 5.1.1 simply note the oxygen and cyanogenmod kernel directives mentioned above when build for your kernel.

oneplu2 and oneplus2cm both work great, better every day.. Minus the chroot extraction (building and manually placing/extracting a chroot post install is easy enough though) Though it ight be fixed... Let me see...

**Comment by jmingov** [comment]
@TheBlackRabbit , thanks for the feedback!

This commit should fix the chroot extract problem: 

https://github.com/offensive-security/nethunter-app/pull/68/files#diff-42eabe2054c2b9a9e8b0e5d24b5b0159R635

I think the change is in the latest apk already. (If the problem persists, let us know)

**Comment by TheBlackRabbit** [comment]
Last night I built/flashed for flounder, OP2 and OP2CM and all builds were indeed up to date with the latest apk  (love the new interface BTW)

Built minimal and full chroots, Anykernel/nh-installer, cp to /data/local and zipped up... Chroots detected and configured. Cheers =D

FYI: built on kali 2.0 sana x64 (amd64 vishera), aarch64 (unbuntu trusty on rooted OP2 via linux deploy) Chromebook C100P (4GB RAM variant) w/ Rockchip RK3288 @ 1.8GHz (ARMv7l/Cortex A-17) running kali 2.0 sana via chrubuntu and sd imaged veyron img built from kali-arm-build-scrips repo.

Only deps missing for arm were multilibs of course, however no issues were presented. Point being... Haven't found a system I couldn't run this python build on yet!
