### ISSUE TITLE
Nethunter on YOG4PAS2QL and YOG4PAS1N0 - no sound in Google Play Music 

### ISSUE THREAD

**Issue by mrtadeo** [offensive-security/kali-nethunter#267]
Hello, I tried installing nethunter 2.0.1 on Oneplus One CM12.1 YOG4PAS2QL and YOG4PAS1N0, but on both there are some issues with sound. Any ideas?

**Comment by binkybear** [comment]
I just posted this yesterday for YOG4PAS2QL:

https://transfer.sh/ILwyu/kernel-kali-oneplus.zip

Although I updated the build today with a hid fix today, I haven't built a new kernel.  I'm sure there will be another release soon but in the meantime you are free to build a kernel or wait.  Let me know if it works for you and always backup first.

**Comment by AndyKr0p** [comment]
Hello @binkybear,

Don't you mind sharing your experience around OTA updates installation at https://forums.kali.org/showthread.php?28200-OTA-update-on-Nethunter-device? Yesterday CM issued yet another OTA YOG4PAS3JL incremental update and I guess everyone wants to understand how to deal with it with less pain than usual.
Thanks.

**Comment by mrtadeo** [comment]
Hi, Thank you **binkybear** for the update. I haven't compiled the kernel for android yet, but I will try and let you know how the update works.
Regards,
mrtadeo

**Comment by hahanov** [comment]
@binkybear 
No sound in Google Play Music.
What should I do?
YOG4PAS2QL

**Comment by binkybear** [comment]
@hahanov - Little more detail.  Which kernel did you flash?  Did you do a build from newinstaller-fj?

**Comment by hahanov** [comment]
@binkybear 
Promptly :)
The core standard cyanogen os

**Comment by binkybear** [comment]
But did you do a recent build/recent kernel flash?  Or did you use old installer?

**Comment by hahanov** [comment]
@binkybear 
What newinstaller-fj ?

**Comment by hahanov** [comment]
@binkybear 
Kernel old.
Where can I get a new build?

**Comment by binkybear** [comment]
You can try latest kernel: https://transfer.sh/h5Pyi/kernel-nethunter-oneplus1-lollipop-13122015-94558.zip.  Make backup first in TWRP of boot or everything in case something goes wrong.

**Comment by hahanov** [comment]
@binkybear 
Many thanks.
And when can we expect a new release nethunter 2.1?

**Comment by binkybear** [comment]
Soon is the best answer, but you are free to build anytime.  It's actually very easy to build, all you need is python.

**Comment by hahanov** [comment]
@binkybear 
Install the kernel
Music does not play

**Comment by binkybear** [comment]
@hahanov - I'm not experincing any issues but I've seen other threads where people have had issues with other kernels.  Once user, @whodunnit, has some commits which may help: https://github.com/whodunnit/AK-OnePlusOne-CM/commits/ak-12.1-official-CM?author=whodunnit

I have rebuilt the kernel for you with that users fixes. Let me know if this works: https://transfer.sh/kQBmS/kernel-nethunter-oneplus1-lollipop-13122015-1710.zip

**Comment by hahanov** [comment]
@binkybear 
Work!

**Comment by binkybear** [comment]
Added to newinstaller-fj branch, will be in next release.
