### ISSUE TITLE
Nexus 9 boot-animation incorrect size

### ISSUE THREAD

**Issue by TheBlackRabbit** [offensive-security/kali-nethunter#271]
I wasnt going to open an issue for this but since its persisted for awhile i thought id mention it. The splash animation is sized incorrectly for the nexus 9. Too small with about 2 in" margin. All the others including oneplus2 look fantastic though. animation lag seems to have dissaperared as well
- [ ] Nexus 9 boot-animation size incorrect

**Comment by jmingov** [comment]
not sure how a bootanimation can be resized. Any ideas?

**Comment by TheNain38** [comment]
I have this issue too, on a nexus 7. It's also too small with about 2 in" margin.

**Comment by Nekroze** [comment]
Nexus 6 has this issue was well.

**Comment by pahapoika** [comment]
Oneplus one got this issue too.
