### ISSUE TITLE
huawei g play mini

### ISSUE THREAD

**Issue by BEOWULF74** [offensive-security/kali-nethunter#291]
there's no custom recovery or rom for my device what I can do to install nethunter on my phone 
Notice:my device rooted with kingroot hope u help me guys

**Comment by jmingov** [comment]
Sorry, but the device is not suported by nethunter. 

Also:
> there's no custom recovery or rom for my device

Makes almost impossible to port nethunter to the device.

**Comment by BEOWULF74** [comment]
Thanks for help :) ill close the issue
