### ISSUE TITLE
Bad checksum error

### ISSUE THREAD

**Issue by nicking989** [offensive-security/kali-nethunter#293]
I am getting a bad checksum error when downloading the chroot from within the nethunter app. Is there any way to build a full chroot? I have noticed when I build one with nethunter-fs the file size is just over 65MB whereas the one the app downloads is ~290MB.
Also the folders that should be on the sdcard are  missing (I know one of them is named "files") which stops things like badusb from working unless I copy them over manually. There seem to be quite a few errors happening during my install though. I have lost my log of the install but will reinstall and upload it soon.
I am using a nexus 4 with the latest 4.1.1 lollipop update. I don't know if it is an issue specific to this phone/OS or not. Also if you ever need me to test anything on this phone I can as it is specifically for Nethunter. Cheers.

**Comment by jmingov** [comment]
Hey! Check
You need latest app build. (Updated few mins ago) Also has the fix for the 'term bug' included.

The chroot checksum has changed. (Thast why)

https://github.com/offensive-security/kali-nethunter/issues/196#issuecomment-158482395

Jaime

**Comment by nicking989** [comment]
Ok great. Thanks. I will check it out now.

**Comment by jmingov** [comment]
Oh @nicking989 about:

>I am using a nexus 4 with the latest 4.1.1 lollipop update. I don't know if it is an issue specific to this phone/OS or not. Also if you ever need me to test anything on this phone I can as it is specifically for Nethunter. 

@binkybear allways want good testers for N4 kernels. (We dont have the device to test on it.)

**Comment by nicking989** [comment]
@jmingov no problem. The current kernel seems to work fine. I can mount and use external wifi. But I can test any newer ones.
