### ISSUE TITLE
Files not writing

### ISSUE THREAD

**Issue by nicking989** [offensive-security/kali-nethunter#294]
My  duckhunter will not write anything to the 'duckout.sh' file. Also badusd will not update the interface in 'startbadusb-lollipop.sh'. I don't know if this an issue with the app or with the chroot. I can't see anything that would stop it from working though.

**Comment by nicking989** [comment]
I got badusb to work perfectly by modifying badusb-lollipop.sh:
There are two lines that need changing
"interface=rndis0" on my phone (nexus 4) I changed it to "interface = usb0"
"dnsmasq -C /sdcard/nh_files/dnsmasq.conf -x TMPDIR/dnsmasq.pid -i $INTERFACE"
to
"dnsmasq -C dnsmasq.conf -x TMPDIR/dnsmasq.pid -i $INTERFACE"

This allows it to run from the terminal by moving into the config directory and then executing with "sh badusb-lollipop.sh"

I am guessing that when badusb is added back into the bin directory:
"dnsmasq -C /sdcard/nh_files/dnsmasq.conf -x TMPDIR/dnsmasq.pid -i $INTERFACE"
will need to be:
"dnsmasq -C ../sdcard/nh_files/dnsmasq.conf -x TMPDIR/dnsmasq.pid -i $INTERFACE"

I believe duckhunter will be just a path issue aswell.
The paths need to be updated in the nethunter android app to make badusb work from there.
In the app the paths are showing "sdcard/files" instead of "sdcard/nh_files".

**Comment by nicking989** [comment]
Update it turns out that the shell executor in android is throwing an error:
tmp-mksh: <stdin>[1]: can't create... : Read-only file system

This is when it tries to update the badusb-lollipop.sh file in order to change the interface adapter.

**Comment by binkybear** [comment]
I noticed the part of the issue is its trying to run a script from the sdcard (outside chroot) which android does not allow.  Inside the chroot is OK but I will update with some of the changes you mentioned and move start-*.sh to /system/xbin instead of /sdcard.

**Comment by nicking989** [comment]
I also tried moving the 'nh_files' folder to the nethunter system directory and modified the android app to execute from there but still the same issue (I though it could be android needing permission from the user to modify files on the sdcard). If it's just this particular phone then I guess it's a firmware issue.

**Comment by binkybear** [comment]
@jmingov has submitted a fix: https://github.com/offensive-security/nethunter-app/commit/a0ea92a60a663b52504d6b881493d7cedc42a6b1

**Comment by nicking989** [comment]
Would it be easier to move everything back and then have the shell executor or a version of it execute commands to login to the chroot and then execute the given commands. It would fix all the attacks instead of just badusb.

**Comment by binkybear** [comment]
What other attacks are you having issues with?  Badusb executes outside of chroot since it uses android system.

**Comment by nicking989** [comment]
I just tried the new version of the app. And yip bad USB definitely works now which is awesome. However, stop-bad-usb doesn't and Duckhunter is doing the same thing. Duckhunter seems to be unable to write to the duckout.sh file. I'm not sure if it is executing correctly though but the USB keyboard application works perfectly on my phone and I also have the HID interfaces listed in the Nethunter app. Cheers.

**Comment by binkybear** [comment]
Thanks @nicking989 for your testing.  I will continue to look at these issues.

**Comment by nicking989** [comment]
No problem. I'm going to begin work on an attack that can hopefully be added into nethunter in the future. I Just hope it works how I want it to

**Comment by binkybear** [comment]
@nicking989 : Duckhunter fix pushed https://github.com/offensive-security/nethunter-app/commit/ef5a79ed0df832326f44870c4a1bb7ccf539c6bf

**Comment by nicking989** [comment]
Cool all seems to be working now. Great work guys. I'm just having an issue with the HID keyboard. However it may just be my computer as the keyboard has also stopped working in the USB keyboard application. The mouse is working fine though.

**Comment by binkybear** [comment]
Oddly enough I ran into some issue and I went into settings and checked tether usb and hid magically came back up.  Clossing issue.
