### ISSUE TITLE
fatal: Remote branch cm-11.0-ak not found in upstream origin

### ISSUE THREAD

**Issue by jakuta-tech** [offensive-security/kali-nethunter#296]
CM11 branch has been removed but is still referenced in androidmenu.sh

    git clone https://github.com/binkybear/AK-OnePone.git -b cm-11.0-ak oneplus11

Any chance this is coming back ?

**Comment by jakuta-tech** [comment]
fixed
git clone https://github.com/binkybear/AK-OnePone.git -b cm-11.0 oneplus11

**Comment by binkybear** [comment]
There's still some errors in build but I will fix it.

**Comment by jakuta-tech** [comment]
awesome thanks !
