### ISSUE TITLE
HID issue

### ISSUE THREAD

**Issue by nicking989** [offensive-security/kali-nethunter#297]
My HID attacks with Duckhunter aren't working properly. On one computer it opens a whole lot of UAC windows for chrome.exe (Varying amounts depending on how many characters are being typed) and on the other it opens up the windows store. Both computers are running windows 10. With the default attack the commands Space Space Enter work fine. It's only when typing characters that there is an issue. I have tried both US and GB languages. Is this happening with anyone else? The USB Keyboard app works perfectly fine. This is using the latest build of Nethunter and the Chroot As of a few hours ago.

**Comment by jmingov** [comment]
yes, the last time i tryed (inside linux-teminal) i saw a ton of weird input. Not sure whats going on. 

Added to check list.

**Comment by binkybear** [comment]
In the latest application I reverted back to the original duckhunter.py.  I'm curious if you had a chance to test it out.

**Comment by nicking989** [comment]
I tested it at the time you changed it and it made no difference. I just did a wipe and full reinstall and rebuild, still no change

**Comment by simonpunk** [comment]
Oh, @nicking989 I just opened a new issue yesterday and seems I have missed yours. Actually I have the exact same problem as yours, but I have tried to type in terminal, and the victim did successfully output the commands properly, so, I guess it's about the app problem...

**Comment by nicking989** [comment]
I can confirm that in the latest build this issue seems to be fixed. It is working as it should. Thanks so much guys.

**Comment by jmingov** [comment]
^^ yep.

**Comment by TheNain38** [comment]
Cool to see HID issues fixed ^^
