### ISSUE TITLE
Nexus 7 2012 unresponsive after plugging in TL-WN722N

### ISSUE THREAD

**Issue by chrisdare** [offensive-security/kali-nethunter#298]
Plugging in TL-WN722N causes my Nexus 7 (2012 Wifi) to become unresponsive, requiring a reboot. I've tried with a OTG Y cable and a standard OTG cable. The dongle worked once with the standard OTG cable but has caused a crash each time since. Output of /proc/last_kmesg below.

[last_kmsg.txt](https://github.com/offensive-security/kali-nethunter/files/53838/last_kmsg.txt)

I'm running version 5.1

**Comment by jmingov** [comment]
which nethunter version have you installed?

**Comment by chrisdare** [comment]
Version 2.0 Lollipop

**Comment by jmingov** [comment]
Hey @chrisdare, checked the kmsg (dint saw any really useful there). 

I suggest you to re-flash a clean stock rom and install latest nethunter from here (youll get a zip to flash using the recovery): 
https://github.com/offensive-security/kali-nethunter/tree/newinstaller-fj/AnyKernel2

**Comment by binkybear** [comment]
@chrisdare - There is no kernel oops in your last_kmsg and firmware/device seems to be recognized.  It doesn't provide any debugging at this time.  Like @jmingov mentioned, you may want to try newinstaller-fj  branch because it has (has y-cable on/off) and may be more stable.

**Comment by chrisdare** [comment]
Thanks @binkybear @jmingov doing the install from the update.zip seemed to make things a bit better. The tablet still go unresponsive occasionally for a few minutes (black screen, ssh down) then returns. I'm seeing the following in dmesg just before it happens, I'll have a bit more of a dig.

[  898.287498] ehci-tegra tegra_usb_resume wake-up/OTG-PLUG with smb347_deep_sle                                                           ep: special
[  898.416319] tegra_ehci_hub_control: timeout waiting for SUSPEND to clear
[  898.541319] usb 2-1: reset high speed USB device number 2 using tegra-ehci
[  898.873526] usb 2-1: ath9k_htc: Transferred FW: htc_9271.fw, size: 51272
[  899.971332] ath9k_htc 2-1:1.0: ath9k_htc: Target is unresponsive
[  899.976251] ath9k_htc 2-1:1.0: reset_resume error -110
