### ISSUE TITLE
Chroot won't update

### ISSUE THREAD

**Issue by Anotherenduser** [offensive-security/kali-nethunter#299]
Gives pretty much all 404s for well over a week. I'm guessing the repositories were wiped were wiped with the Kali 1.x stuff and I missed the memo on how to fix it?

Nexus 7 2013 wifi, was up to date...

**Comment by binkybear** [comment]
You need to update to Kali 2.0:
@http://docs.kali.org/general-use/kali-linux-sources-list-repositories
------------
On a standard, clean install of Kali Linux, you should have the following two entries present in /etc/apt/sources.list:

deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free

Let me know if that fixes your issue.

**Comment by Anotherenduser** [comment]
Expect that would fix it. unfortunately, I don't seem to have a 
sources.list on Nethunter. I have /etc but no further.... I'm tired, 
probably missing something. I'll look at it again tomorrow. Thanks much!

**Comment by Anotherenduser** [comment]
I cannot find sources.list. I have no /apt folder in /etc. I've used every search method I know, cannot find sources.list. Please point me in the right direction.

**Comment by binkybear** [comment]
Are you checking inside chroot or outside?

**Comment by Anotherenduser** [comment]
I used root explorer to search the tablet. I'm guessing this is not 
searching inside chroot? Also tried using find command from kali prompt. 
Clearly I don't really understand chroot so am unable to figure out how 
to search it.

**Comment by Anotherenduser** [comment]
I found sources.list

**Comment by Anotherenduser** [comment]
So, for the next clueless guy.... sources.list is located in /data/local/kali-armhf/etc/apt/sources.list , Changing the file as specified brings about a million updates. Thanks very much for your help!

**Comment by a904guy** [comment]
For future readers reference the root of the kali shell is at 

```/data/local/kali-armhf/```

So if you've ran ```su -c bootkali```

```/etc/apt/sources.list```

The file will appear in the normal debian spot.

**Comment by Lukodiablo** [comment]
Guys... iI am facing error 404 when i try run apt-get update on my Grouper - nexus 7 2012
I am sniffing around the damaged source.list for couple of hours.
ive try differend roms, differend nethunter zip, custom kernels, byut nothing fix the issue with update
ive also download again the latest nethunter image 3.0 for grouper, but even this doesnt resolve the issue.
so if i open the source.list i see:
deb http://http.kali.org/kali sana main non-free contrib
#deb-src http://http.kali.org/kali sana main non-free contrib
deb http://http.security.kali.org/ sana/updates main contrib non-free
#deb-src http://security.kali.org/ sana/updates main contrib non-free

when i edit the source and remove the HTTP for example: deb http://kali.org/kali sana main non-free contrib
then i get some updates bu still mostly face 404
I am not an expert, but this look like the nethunter gouper 3.0 image is damaged
Also when i plug in otg with tp-link dongle the nethunter doesnt recognise, wlen run lsusb i see the dongle but when i run iwconfig then is not there.
any advice is welcome

BTW -> BINKYBEAR -> kali get new updated images, it is there any nethunter version update soon ?

**Comment by jcadduono** [comment]
change them all to old.kali.org

**Comment by Lukodiablo** [comment]
ow thanx.... could you be so kind and mail me the sources? as i try replace
that.. but i already mess with te source.list and curently dont remember
where i back up the original list.
kindly regard

**Comment by Lukodiablo** [comment]
btw what you mean that Grouper is incompatible with kali rolling? what about my hammerhead device?

**Comment by Lukodiablo** [comment]
Hi Dude, after several flash my grouper i give up, after change the source.list we get some tiny update but still i can not enable any of my external wifi dongle, ive tryfew differend otg and differend dongle which are natively supported by linux but not in the nethunter...
i can upload some output from terminal but....
Now i am bit dissapointed as this is is my second nexus grouperwhich i purchased few weeks ago as my previous nethunter tablet burn down. If i know that my grouper is not supported in the next release ill go a head with different device.
Any advice how to get this grouper work properly, or advice for another nexus replacement? is is hammerhead supported in the kali rolling?
regard 
D!@BL0

**Comment by serpunja** [comment]
For Nethunter!
##I edited file - /etc/apt/sources.list :
deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free##

It works ))

**Comment by Nihal7899** [comment]
Did you really tried that source code

**Comment by bewarethealgorithm** [comment]
This may help some folks it helped me https://unix.stackexchange.com/questions/421821/invalid-signature-for-kali-linux-repositories-the-following-signatures-were-i/421827?stw=2#421827
