### ISSUE TITLE
Nexus 7 (2012) kitkat Nethunter 2.0 macchanger and other commands missing

### ISSUE THREAD

**Issue by udtfrogman29** [offensive-security/kali-nethunter#300]
Hello !

 I've installed nethunter 2.0 on a nexus 7 wifi (2012) with busybox 1.24.1 using the nethunter.com method with windows.
After the installation, I cannot find the macchanger command in either /system/bin or /system/xbin.

Has anyone had this problem?

**Comment by jmingov** [comment]
Are you checking from inside the chroot? 

If is not installed you can **boot into kali** and do: `apt-get install [programHere]`

**Comment by udtfrogman29** [comment]
Thank you jmingov,

 I believe that I wasn't in the kali mod. I assumed that booting the device would get into "kali mode" automatically.
What do you mean boot in kali? Is it booting in kali when turn on the nexus? Can you provide the steps? I can't find any information. Do I have to use a multiroom apk to do that?
I thought installing nethunter would boot in kali...

Thank you again for the info.

**Comment by jmingov** [comment]
Well @udtfrogman29, Kali Nethunter is not a Android Rom, instead is a Chroot environment. (This way we have the best of both worlds and potentially support any Rom).

`Booting into Kali` means mounting the chroot, to do this you can:

Option 1:
  - Open nethunter app > Go to Kali Launcher (in menu) > Click `Launch Kali Shell in Terminal`

Option 2: 
 - Open Terminal app > Type: `su -c bootkali`


Both are doing the same, you will see the kali shell prompt.

From there you can use Kali like in a desktop.

jmingov

**Comment by udtfrogman29** [comment]
Thank you a lot for the reply and for the info. It really clears my problem with the command. I wish this info was available at the official website (boot kali using a normal terminal).
