### ISSUE TITLE
Compatibility with other devices

### ISSUE THREAD

**Issue by jkomyno** [offensive-security/kali-nethunter#301]
What should one do to adapt the source to other Android devices, given the specs?
I.e, if I have a smartphone with 5' display FullHD, 3GB of RAM and Qualcomm processor, what should I do? Would it be safe to try to install? What should I change to prevent any dangerous issues? In brief: how to expand compatibility? Pdf guides are well accepted.

**Comment by jmingov** [comment]
... https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter

**Comment by jkomyno** [comment]
Many thanks.
Do you believe this kernel would do the trick for every mediatek Lollipop based device? https://android.googlesource.com/kernel/mediatek/+/android-mediatek-sprout-3.10-lollipop-mr1

**Comment by jmingov** [comment]
We dont own any mediatek device, but usually each device has his own kernel. 
(Diferent hardware, networkCard, chipset etc).

Each kernel should be ported and mantained, thats why we only support a 'few' devices.

Hope this makes things more clear.

jmingov
