### ISSUE TITLE
nethunter 2.0 on Nexus 7 2013 (WiFI) - WiFI cards not working

### ISSUE THREAD

**Issue by Bauta76** [offensive-security/kali-nethunter#304]
Hi guys, 

it is the first time I write here. I have recently purchased this Device, but my wifi cards are not revealed from Nethunter. I first tried on the "lollipop version", but then I re-flashed and I no have the "kitkat version". 

For now I can give you some details related to the kitkat version, but then if you need I will be happy to give you more details also on the lollipop version. 

WIFI CARDS TESTED (using two different OTG cables):
AWUS036NH
AWUS036NHA
AWUS051NH v.2
TP-LINK TL-WN722N

Except for the "AWUS036NHA" card, all the others are revealed by the "lsusb" command. 

For all of them, iwconfig does not reveal the new card

For all of them, the airmon-ng and wifite do not reveal the card. 

I see that only the wifi card "AWUS036NH" has its led turned on when I plug it to the device, but I;m not sure this is a useful information. 

KERNEL version:
3.4.0-g03485a6-dirty
desktop@ubuntu #1 
Sun Feb 22 08:06:52 PST 2015

Please let me know if you need any other detail. 

Cheers.

**Comment by Bauta76** [comment]
Ok guys, problem solved thanks to the following issue:
https://github.com/offensive-security/kali-nethunter/issues/238

I will give a bit more details for the internet users that are searching for a solution and these are the steps that i followed (I start from the beginning):

1) Use NRT (Nexus Root Toolkit ) to unlock the device
2) Use NRT to root the device
3) Go in flash stock and chose android 5.1.1 
4) After the flash, you need to flash also the recovery using the TWRP multirom ( search for "TWRP_multirom_flo_20150630.img" on google).
So, restart the device to the bootloader while it is connected to your pc and on your pc run the following command:
fastboot flash recovery TWRP_multirom_flo_20150630.img
5) restart and install busybox from the google play 
6) Now you need to flash the kernel ( I used elementalX: http://elementalx.org/devices/nexus-7-2013/. Chose the one related to 5.1.1.1 for example). Just copy the kernel on your device, restart in recovery mode and chose "install" from the menu and follow the instructions. ( if you don't know what to chose during the kernel configuration, just let the values to the default ones )
7) once finished, restart and copy nethunter to your device 
8) restart again in recovery mode and re-install nethunter. 

Sorry for this dummy step-by-step guide, but if I found something like that before it I would have saved a lot of time :)

Thank you all! 

P.S.
2 on 4 wifi are now working:
AWUS036NH
TP-LINK TL-WN722N

AWUS051NH v.2 is detected at first and then it crashes

**Comment by jmingov** [comment]
AWUS[XXXX] are pretty power hungry. Nice to see you have at least 2 running.

**Comment by TheNain38** [comment]
I have the same problem with the TP-LINK TL-WN722N, by installing the ElementalX kernel, and then nethunter?

**Comment by jmingov** [comment]
@TheNain38 the op got  that adapters running fine, follow the steps he did.

**Comment by TheNain38** [comment]
Ok, thanks

**Comment by Bauta76** [comment]
Hi @TheNain38 if you stuck on any of the steps (as me before understanding what I was doing wrong) let me know. I will be happy to help.

**Comment by TheNain38** [comment]
It worked! Thank you so much! But now I have another issue, sometimes I need to reboot to get it working with wifite, but I got it working thanks to you!

**Comment by Bauta76** [comment]
Why you need to reboot it? What's the problem? (I maybe had similar issues...)

**Comment by TheNain38** [comment]
Sometimes when wifite set the adapter to monitor mode, the LED blinks, and then sometimes it would stop and the interface would go down...

**Comment by Bauta76** [comment]
Ah in this case I don't know. I did not have this issue...

**Comment by TheNain38** [comment]
I think this is power related

**Comment by Bauta76** [comment]
Mmm not sure. I do not have any power issue with the tplink. Which version of nethunter are u using?

**Comment by TheNain38** [comment]
I have the latest, I builded it myself, and I also downloaded the latest version of ElementalX, it was flashed 1 hour ago

**Comment by Bauta76** [comment]
Ah ok. Wait. If you have the latest, u don't need to flash the kernel. I flashed the kernel becausenin the steps above I was using the versio downloaded from the website. Trybto reflash everything again keeping the original 3.4.0-Kali kernel

**Comment by TheNain38** [comment]
Yes, but before I tried your steps, Wifite couldn't even recognised the adapter, and now, it can (using your steps)

**Comment by Bauta76** [comment]
Yes but it is annoying to see the adapter going up and down. Try the steps above your built but without flashing the kernel.

**Comment by TheNain38** [comment]
I did the exacts same steps, but without flashing the ElementalX kernel and it won't detect the adapter

**Comment by Bauta76** [comment]
Which kernel do u have in this moment?

**Comment by TheNain38** [comment]
I have this kernel: 3.4.0-Kali-gc6b158c-dirty
