### ISSUE TITLE
Nexus 9 - chroot install from download still looking for local file - Anykernel2 build Install

### ISSUE THREAD

**Issue by jbagel2** [offensive-security/kali-nethunter#305]
After successful AnyKernal2 install Marshmallow 6.0.1 (Thanks for this BTW). When entering Kali Chroot Manager to Install Kali chroot, even when choosing download instead of from SDCard, get 
"java.io.FileNotFoundException: /storage/emulated/0/kalifs-full.tar.xz: open failed: EACCES (Permission denied)"

nh_install_~.log:
Dec 23, 2015 11:13:11 AM - New instalation log file: /storage/emulated/0/nh_install_20151223_111257.log
Dec 23, 2015 11:13:35 AM - Starting download. Standby&
Dec 23, 2015 11:13:36 AM - Error in the Chroot download, posible causes: server down or conection issues
Dec 23, 2015 11:13:45 AM - Error in the download, removing temp file...
Dec 23, 2015 11:13:48 AM - Checking for chroot at /data/local/nhsystem/kali-armhf
Dec 23, 2015 11:13:50 AM - No Kali chroot directory was found.
Dec 23, 2015 11:13:51 AM - Cleaning install directory
Dec 23, 2015 11:18:07 AM - New instalation log file: /storage/emulated/0/nh_install_20151223_111257.log
Dec 23, 2015 11:18:12 AM - Starting download. Standby&
Dec 23, 2015 11:18:14 AM - Error in the Chroot download, posible causes: server down or conection issues
Dec 23, 2015 11:20:03 AM - Error in the download, removing temp file...
Dec 23, 2015 11:20:06 AM - Checking for chroot at /data/local/nhsystem/kali-armhf
Dec 23, 2015 11:20:07 AM - No Kali chroot directory was found.
Dec 23, 2015 11:20:09 AM - Cleaning install director

Just getting ready to go grab the

**Comment by jmingov** [comment]
Hey, is a bit estrange, you cloned the repo today?

    Error in the Chroot download, posible causes: server down or conection issues
    Dec 23, 2015 11:20:03 AM - Error in the download, removing temp file...

Do you have a stable connection? Looks like the download is failing (im pretty sure).

About:

     /storage/emulated/0/kalifs-full.tar.xz

Thats ok, we are downloading the file to that location. 

But is extrange the permission error, since  `/storage/emulated/0/` is the internal sd  `/sdcard` (It is used by all apps is a world-readable folder.)

Can you confirm that `/storage/emulated/0/` exists in the device?


Jaime

**Comment by binkybear** [comment]
I would first make sure buysbox is installed.

**Comment by jbagel2** [comment]
busybox is installed, and yes it was a clone from the repo today.

**Comment by jbagel2** [comment]
I'm on a corporate network for a "to remain nameless" web company. No restrictions for me on internet traffic. Plenty of bandwidth. Very stable connection.

**Comment by jbagel2** [comment]
/storage/emulated/0 also does exist. (alias/symlink?) of /sdcard

**Comment by jbagel2** [comment]
just as a test. I tethered my nexus 9 to my phone to test over LTE. Still received the same error.
I'm just finishing up a fresh build of the chroot instance to manually copy over and install. (Assuming the error is actually related to the download). I'll probably dig in and debug this a little myself. Is this being initiated with a DownloadManager.Request?

**Comment by jmingov** [comment]
No is not download is not using the manager. 

Can you try with this apk please?

3bollcdn.com/nethunter/nethunter-app-release.apk

Is just to be sure you have the latest one (Just compiled it).


If you can debug try debugging the app. (Adb, CatLog App, Android studio) any of them should let you see more debug info.


Let us know how it goes. 

Jaime

**Comment by jbagel2** [comment]
Attached is logcat from dowload attempt.

[logcat_from_download_req.txt](https://github.com/offensive-security/kali-nethunter/files/71336/logcat_from_download_req.txt)

**Comment by jmingov** [comment]
Is that log from the apk i linked?

**Comment by jbagel2** [comment]
no, sorry. That I uploaded prior to seeing you had responded. Installing now. (It does show a declared permissions difference for the USB Storage)

**Comment by jbagel2** [comment]
it now actually has interfaces listed in the interface list (in the nethunter app), so thats a good sign

**Comment by jbagel2** [comment]
AND ITS DOWNLOADING!

**Comment by jbagel2** [comment]
I have to head home (before the wife kills me). But things are looking much better. I'll post back the result a little later.

**Comment by jmingov** [comment]
Nice, hope to hear notices soon ^^.

**Comment by jmingov** [comment]
https://github.com/offensive-security/kali-nethunter/commit/40781521a504ad8dd3873df4294ea50b664931ba

Feel free to close the issue when you try it.

**Comment by jbagel2** [comment]
That did take care of the chroot issue. Thank you for your help.

**Comment by T83wood** [comment]
@jmingov could you repost the apk? I have a beta version that was compiled yesterday actually and I've been trying to compile from github using aide from Android without luck yet, I think it's missing the proper libraries. Anyways I'm looking for the full tar.xz file to use with either app and since @jbagel  had success with your apk I'd like to give it a shot if you have time to throw up another link.

**Comment by binkybear** [comment]
@T83wood - Latest APK is up in repo: https://github.com/offensive-security/kali-nethunter/blob/c494084197f777b4f38700a134ba40c712290f8c/AnyKernel2/data/app/nethunter.apk

**Comment by T83wood** [comment]
Thanks @binkybear but the site tells me "this file is  too big to show, sorry!"

**Comment by TheNain38** [comment]
Go on this https://github.com/offensive-security/kali-nethunter/raw/c494084197f777b4f38700a134ba40c712290f8c/AnyKernel2/data/app/nethunter.apk

**Comment by T83wood** [comment]
Also I'm *cough "trying" to do this on a note 4. I have two roms setup using chroot, primary is the dok2 stock base with ael kernel 8.1 which is Android 5.1.1, secondary is Dynamickat Android 5.0.1 with ael kernel 14.5. The 14.5 kernel I've used before with a flashable zip which installed nethunter 1.2 and worked previously but I'm not sure what rom I was using so I'm trying to get it set up again on either of these. Any insight would be great!

**Comment by T83wood** [comment]
Also I'm *cough "trying" to do this on a note 4. I have two roms setup using chroot, primary is the dok2 stock base with ael kernel 8.1 which is Android 5.1.1, secondary is Dynamickat Android 5.0.1 with ael kernel 14.5. The 14.5 kernel I've used before with a flashable zip which installed nethunter 1.2 and worked previously but I'm not sure what rom I was using so I'm trying to get it set up again on either of these. Any insight would be great!

**Comment by T83wood** [comment]
Thanks @TheNain38! I'll report back. Is this the correct thread?

**Comment by T83wood** [comment]
Downloaded full and minimal, both are in /storage/emulated/0/, directories spelled exactly but the app is stating neither is there?

**Comment by jmingov** [comment]
We don't support custom roms, no idea what the problem can be.

Dont install the app alone since half of nethunter will be missing.

Use official builds: https://www.offensive-security.com/kali-linux-nethunter-download/
