### ISSUE TITLE
bootkali fails to launch

### ISSUE THREAD

**Issue by grayburn** [offensive-security/kali-nethunter#307]
Using the new installer-fj branch on Nexus 6 with Marshmallow. When using the Launch kali shell in terminal does not launch correctly. I need to manually type 'su' <enter> then type 'bootkali' <enter> will give me the proper shell. Not sure if this is an existing known issue at the moment, I checked any open issues but couldn't find any.

**Comment by jmingov** [comment]
Hello, you cloned the repo less than 2 days ago?

The app should ask for multiple permissions in the first run (nethunter app) and you need to give them all.


You saw the multiple dialogs?



Jaime

**Comment by grayburn** [comment]
Jaime thanks for the hints.

I did the clone on the 24th so a couple days ago.

I went ahead and reset everything, going back to a clean install of android 6.0.1, rooted, etc. then updated my local copy of the installer-fj branch. Built a new nethunter for shamu and pushed it to my device. Flashed the zip and ran through the install. I did see all of the pop ups for permissions and script fixes, clicked ok for all.

Unfortunately after all of this, I am still seeing issues running the kali terminal. Whenever I try to run the kali shell from the launcher, it just gives me the android shell. It only works if I manually do 'su' then bootkali_login.

**Comment by jmingov** [comment]
Well @grayburn, need you to do some test so we can debug this:

1. Which version of superSU you installed?

2. Open the terminal, type `su` and once you are root, do `which su` that will give you the path for the binary. 

3. Open the terminal, type `su` and once you are root, do `which bootkali_login` that will give you the path for the binary also.


I think the problem can be something related to that paths. Hope to hear something soon.

Jaime.

**Comment by jmingov** [comment]
I compiled the terminal with a few changes, maybe that can fix the issue, remove the Terminal (uninstall like any other app) and install this one :

[http://3bollcdn.com/nethunter/term-release.apk](http://3bollcdn.com/nethunter/term-release.apk)

Jaime

**Comment by grayburn** [comment]
Jaime, uninstalled and installed your new Terminal version. My issues are now fixed.
Tested the following:
* Kali Launcher >> Launch Kali Shell in Terminal - **Good**
* Kali Launcher >> Launch Android SU Shell - **Good**
* Kali Launcher >> Launch Android Shell - **Good**
* Kali Launcher >> Launch Kali menu in terminal - **Good**
* Kali chroot manager >> Add Metapackages >> install and update - **Good**

Thanks again for your help.

**Comment by jmingov** [comment]
So good. 

You welcome @grayburn. 

Updating repo apk asap.
