### ISSUE TITLE
newinstaller-fj not working well on ONEPLUS ONE

### ISSUE THREAD

**Issue by braichucha** [offensive-security/kali-nethunter#308]
Nethunter 2.0 not installing either, many apks arent available.

**Comment by binkybear** [comment]
Please provide more details.  What isn't working?  The builder?  The app?  Are you using CM or OXYGEN OS?  Why are the APKs not available for you?

**Comment by braichucha** [comment]
the apks arent installing, the CHROOT suposedly installs, and so does the kernel, so the OS boots.

but nethunter didnt get installed, and some others important apks have the same problem.

i tried with COS12.1 (every revision) and with resurrection remix (last revision).

**Comment by binkybear** [comment]
The chroot is installed in app.  Can you send me the zip file you are using to flash.  I flashed yesterday with a clean factory CyanogenOS and everything worked fine.

**Comment by braichucha** [comment]
@binkybear I sent you an email, i will upload my zip file to google drive and send you the link. would you send me your flashed file? i need it urgently. remember im using resurrection remix.

**Comment by binkybear** [comment]
We don't support ROMs other than stock CyanogenOS or CM for the OnePlus.  I can't say if thats the reason why it's not working for you but I suggest you use stock for best results.

I can't reproduce at the moment as I don't use or plan on using ROM so I'm closing.

**Comment by braichucha** [comment]
but i got the same result on COS12.1.
