### ISSUE TITLE
Question about AWUS036NH

### ISSUE THREAD

**Issue by braichucha** [offensive-security/kali-nethunter#309]
I want to know if kali nethunter works with AWUS036NH wifi adapter. Im deciding about buying some wifi adapter so for using wifite.
which is the best usb wifi adapter you can think of?

**Comment by jmingov** [comment]
https://github.com/offensive-security/kali-nethunter/wiki/Wireless-Cards

Only cards with thouse chipsets. Read the wiki. 

This is not a forum, is to track issues.

Thanks
