### ISSUE TITLE
HID not working in latest build for Nexus 6 marshmellow

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#310]
The issue that I have found so far is the HID attack failed to send correct key-combination to the target, but actually the keyboard app and is functioning, so I decided to look around into it.
And I found that when I execute with the following tow command in the terminal:
###  echo -ne "x00\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0
It did succeeded to output the digit "1" to my computer. But execute inside the app, when "execute attack", it failed to send out the above commands correctly to the computer and nearly kill my computer with bunch of unknown commands being executed. 

So, I think maybe that's the problem with the "execute attack" button inside the app.
I also tried put the above commands into .sh file, and execute with expected output.
And of course, the previous version was working fine. I really don't know where the problem is.

Btw, new version does look much better, the layout, the interface, the function, has improved a lot. Thanks for the great work.

**Comment by simonpunk** [comment]
@binkybear Hi, I just found a amazing key combination in duckhunter which is "1234", you know what? these four digits can just simply shut down my Mac book air within 3 seconds, the fastest way to power off my mac book ever! I was really shocked and amazed, haha........

Okay, back to the topic, I just tried to go further into the problem and see whether I can find some clues.
And lucky I found something interesting:

Take "1234" as my desired output to my mac book air, when I call this command in just a root shell terminal:
### [root@shamu: busybox chroot /data/local/nhsystem/kali-armhf/ /opt/duckout.sh] => it shutdown my mac. 
but if I change to:
### [root@shamu: busybox chroot /data/local/nhsystem/kali-armhf/ sh /opt/duckout.sh] => it succeeds to output "1234" to my mac!! How come????

So, I just took a look into the bookkali file in /system/bin, and I located this line:
### $busybox chroot $mnt $2
and changed to
### $busybox chroot $mnt sh $2

at that time, I though it could be solved already but when I tried either this command
### [root@shamu: bootkali duck-hunt-run /opt/duckout.sh] or
### [root@shamu: su -c 'bootkali duck-hunt-run /opt/duckout.sh']
, it still shutdown my mac!!!!

Now, So far I have run out of ideas and getting crazy, and just hope this can provide useful help...

**Comment by jmingov** [comment]
good find!

**Comment by simonpunk** [comment]
@jmingov @binkybear !!!!!WOW, I tried it out!!!
Edit the bootkali, locate the line
```$busybox chroot $mnt $2```
and simply change to
```<$busybox chroot $mnt /bin/bash $2```
Should be working now!!!! How come??
I Tried to add /bin/sh before $2, but no effort.
but ```/bin/bash``` just works instead.....so weird.

**Comment by binkybear** [comment]
@simonpunk - Thanks for all your work trying to track this down...seems like an easy fix.  I'll test it out and see if it works/breaks anything else.

**Comment by binkybear** [comment]
@simonpunk: pushed your fix suggestion.  I have generated a new apk for you (or anyone else) to test: https://transfer.sh/PjZHD/nethunter-app-release.apk

**Comment by simonpunk** [comment]
@binkybear Thank you so much, I will test it today, but may I ask a stupid question? Do I just need to install the apk like other apps? no need to completely remove the apk first, and then install again?
Or do I need to remove chroot first, and then re-download the chroot again?
I have tried install it in normal way, and seems the bootkali didn't change, just remain the same. So I wonder I am doing wrong or not..

**Comment by binkybear** [comment]
@simonpunk - I just pushed a lot of duckhunter fixes here: https://github.com/offensive-security/kali-nethunter/raw/master/AnyKernel2/data/app/nethunter.apk

With help of @jmingov, he was able to track down your marshmallow problem.  What worked in lollipop no longer worked in marshmallow.  Specifically, your fix is here:

https://github.com/offensive-security/nethunter-app/commit/07317d37e38e053921b6c99f2006a929555b9e15#diff-0409957e8c5ef29acbe691560f4a0abbR64

That fixes conversion error.  Also, moved everything to hid-keyboard and updated keyseed.py.

---------

As far as your question, you just need to update APK.  You may want to remove previous one if you have trouble.

**Comment by simonpunk** [comment]
Thanks @binkybear , and my bad, it successfully installed and changed the bootkali after a full remove. The r/w mount issue seems to be fixed as well, I can directly modify all the files in kali chroot. 

By the way, later I may want to open another issue, like the macchanger and the HID attack for powersploit against windows, but now I just want to test it and grab some information first before opening another issue.

**Comment by test123456676** [comment]
when i run a duckhunter script it does nothing can anyone help me.
