### ISSUE TITLE
Nexus 7 (2013) Wifi: some HID commands don't execute correctly

### ISSUE THREAD

**Issue by TheNain38** [offensive-security/kali-nethunter#311]
For example, when using: `TEXT X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*` The 'X' don't appear, and when I use `STRING`, then it outputs the 'X' correctly.
Also, the `REPEAT` command doesn't work... If I use:
````
SPACE
REPEAT 10
STRING echo TEST
````
it outputs only one space and next commands don't even get executed.
Also, `DEFAULT_DELAY` or `DEFAULTDELAY` don't even work.

**Comment by binkybear** [comment]
Let me update you on progress.

First off thanks for bringing up this issue.  I did confirm that X was not working, rewrote a lot and found errors thanks to @jmingov.  I noticed a "sleep" issue also which was not working as intended.

As far as REPEAT and DEFAULTDELAY, those are going to take some work.  Repeat is a little harder since we read the file line by line.  Either way, those two are going to have be in the works and are not currently working.

I will keep the issue open until I can add them (or someone else).

**Comment by TheNain38** [comment]
And also, `MOUSE` etc commands don't work too

**Comment by jmingov** [comment]
@TheNain38, be more precise please. With that `etc` we can not do too much.

We need to know which version of nethunter are you running, all the fixes are in latest apk as @binkybear said and all except the ` DELAY, DEFAULT_DELAY and REPEAT` commands are working fine, i tested it personally (mouse inc).


The command:
`MOUSE 100 100` is working fine in my nexus5 with marshmallow and latest nethunter build. 

If you running 2.0 from the kali website, no fixes will be applied there.

You can build the latest nethunter from https://github.com/offensive-security/kali-nethunter/tree/master/AnyKernel2

Jaime

**Comment by TheNain38** [comment]
@jmingov I will retry with the latest version

**Comment by TheNain38** [comment]
All the `MOUSE` commands still don't work and the letter 'g' can't be typed when in French layout and also, when the keyboard layout is set to American English, `STRING` don't add enter key at the end. Also, in American English layout it is typing super fast, but in French layout it isn't.

**Comment by binkybear** [comment]
Confirmed STRING was not working, pushed fix.  Unsure about MOUSE since its working for jmingov, so that will require more testing.

The speed increase is the way I redid keyseed.py.  I moved it to use hid-keyboard binary instead of echoing each hex.  That might have other side of effects on the US since I retyped everything by hand.

As far as French goes it probably does need to be fixed in keyseed.py.  There is no way now to take advanced  of hid-keyboard without rewriting binary.  If you feel comfortable doing that I will accept a push request.

**Comment by jmingov** [comment]
Ok, lets fill some info so we know where you guys testing:

I do tests with:

    COMPUTER: Desktop
    KEYBOARD_LANG: US
    KEYBOARD_EXTERNAL: True (QWERTY)
    MOUSE_EXTERNAL: True
    OS: Linux (kali Sana)


@binkybear @TheNain38 @simonpunk

**Comment by binkybear** [comment]
Test:
```
COMPUTER: Desktop
KEYBOARD_LANG: US
KEYBOARD_EXTERNAL: True (QWERTY)
MOUSE_EXTERNAL: False
OS: OSX
```

**Comment by binkybear** [comment]
Confirmed "g" is not working in french.  Equal sign also seems to replace period.

**Comment by TheNain38** [comment]
Test:
````
COMPUTER: Desktop
KEYBOARD_LANG: FR
KEYBOARD_EXTERNAL: True (AZERTY)
MOUSE_EXTERNAL: True
OS: Windows 8.1 (64 bits)
````

**Comment by TheNain38** [comment]
And also, maybe there could be a translation table, where for example in French layout `a` corresponds to `q` and `q` corresponds to `a` etc... So we could use the hid-keyboard binary

**Comment by binkybear** [comment]
@TheNain38 -   So the way hid-kebyoard binary works is here:

hid binary: https://github.com/pelya/android-keyboard-gadget/blob/master/hid-gadget-test/jni/hid-gadget-test.c#L20

Which really just defines these codes here:  http://www.mindrunway.ru/IgorPlHex/USBKeyScan.pdf

The way our python script works it reads the character as a byte and passes it here: https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/keyseed.py#L221.

I modified the US keyboard to use hid-keyboard here: https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/keyseed.py#L5

If you want to see the ascii conversions theres a folder of them used by rubber ducky here: https://github.com/midnitesnake/USB-Rubber-Ducky/blob/master/Encoder/resources/fr.properties

**Comment by TheNain38** [comment]
We could take the [ascii conversions](https://github.com/midnitesnake/USB-Rubber-Ducky/blob/master/Encoder/resources/fr.properties) used by rubber ducky and do the same, but just changing the format

**Comment by TheNain38** [comment]
Why didn't you handle the `backspace` character? And also, how should I do to handle dead keys (e.g. to add a space character?)

**Comment by binkybear** [comment]
@TheNain38 - I didn't add the backspace although it would be easy to add to keyseed.py:
    "\x7f": "backspace",     # backspace

But it much easier to handle it in duckhunter.py by looking for BACKSPACE then having it launch:
```
echo backspace | hid-keyboard /dev/hidg0
```
But in reality I'm not sure if it would be useful unless you have a use case I'm not thinking about.

I believe you need:
```
     #SDLK_RETURN,0x28
    "\x0a": "\\x00\\x00\\x00\\x28\\x00\\x00\\x00\\x00",
    "\x0d": "\\x00\\x00\\x00\\x28\\x00\\x00\\x00\\x00"
```
At the end to handle dead returns.  Spaces are handled with:
	"\x20": "space",

**Comment by TheNain38** [comment]
Thanks, but when I talked about dead keys, I was talking about that https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/keyseed.py#L261, the `+ Space`

**Comment by lavanoid** [comment]
I'd like to add that "GUI R", which would normally open the Run Dialogue on Windows, does not work.

Nexus 7 (2013),
British keyboard layout.

**Comment by TheNain38** [comment]
`GUI r` works normally for me

**Comment by lavanoid** [comment]
HHmm. I'll check that. I usually use a capitalised R

**Comment by lavanoid** [comment]
OOh, it does work. NVM then :+1:

**Comment by TheNain38** [comment]
Also, I don't know how to add these: https://github.com/midnitesnake/USB-Rubber-Ducky/blob/master/Encoder/resources/fr.properties#L61, https://github.com/midnitesnake/USB-Rubber-Ducky/blob/master/Encoder/resources/fr.properties#L65. Since they aren't in US keyboard layout.

**Comment by jmingov** [comment]
Hey @TheNain38,    

KEY_NON_US_100 is `<` 
KEY_NON_US_100 + SHIFT is `>`

I think in french the are both on the same key `> <`

**Comment by TheNain38** [comment]
Thank you @jmingov! Here is the pull request offensive-security/nethunter-app#99

**Comment by TheNain38** [comment]
Also, to handle the `REPEAT` command you could do a first pass, which would handle it and then a second pass which handle what's left. And duckhunter.py would need to handle the dicts by detecting if a _bin exists and use it, and if the key don't exists it would see if the key exists in the non _bin dict.

**Comment by TheNain38** [comment]
The new interface makes it impossible to update, or convert, without launching the attack, and also instead of always refreshing the converted script, you could refresh it only if it was reconverted

**Comment by binkybear** [comment]
I dont know if thats an issue though, having one button to execute.  It used to be two button but i don't think it was clear what was going on.  Maybe adding a "convert only" button below (away from top bar execute) might be in the future.

**Comment by TheNain38** [comment]
Before, it was 2 buttons, and an entry in a menu. Me, I was thinking of only two buttons, one that update the content and convert, and another which execute

**Comment by jmingov** [comment]
Now you only need to swipe to the preview fragment and the convert (only) is done.

**Comment by TheNain38** [comment]
Ah, ok, but it needs to be like that:
- if you change language whil being on the preview tab, it should update the preview
- if it was already converted, and that you click the button at the top, then it shouldn't reconvert it
- if you didn't changed anything in the convert tab, then it shouldn't reconvert it if you go to preview tab

**Comment by jmingov** [comment]
Prs are welcome, not a 'big problem' imo. Is more a enhacement.

**Comment by TheNain38** [comment]
It is a problem in the sense that, if you click the button at the top to launch the attack, it could take a while to convert a big script

**Comment by jmingov** [comment]
No, if you see a problem (a 1 sec delay is not imo) you can submit a pull request.

**Comment by TheNain38** [comment]
I will do some PRs when I have the time, because I'm also a Java developer ^^ But I won't be able to test, because I have some bugs when I compile myself the apk (Services don't have a name, instead they have "Unkown")

**Comment by jmingov** [comment]
Ill test dont worry.

**Comment by binkybear** [comment]
This issue is getting a bit out of hand and off the original issue into more enhancement.  I'm going to close this for now.  Feel free to open an issue on nethunter-app repo with enhancement so we can take care of it later.

**Comment by TheNain38** [comment]
offensive-security/nethunter-app#106

**Comment by marasvensson** [comment]
The letter g does not work in swedish layout and gui r command but The string command works fine

**Comment by Chbe** [comment]
@marasvensson in keyseed.py in nh-files/modules: 
in `In 'sv_bin' : {...}:`:
add `\x47": "left-shift g", "\x67": "g"`

Varsågod ;)
