### ISSUE TITLE
Wrong executing path in "HID" side menu (Nexus 6 Marshmallow)

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#312]
I wonder if anyone else is having the same issue as mine. 

Inside the side menu "HID", when launch ```execute attack```, I found that it did't output the strings from
`/sdcard/nh_files/scripts/rev-tcp`
but from
`/sdcard/nh_files/configs/rev-tcp` 
instead.

So, inside (chroot kali)/usr/bin, I just tried to edit `hid-all.sh` and `hid-all.py`,
for `hid-all.sh`, took out the strings
`/data/local/nhsystem/kali-armhf`
from line 20:
``encode="`cat /data/local/nhsystem/kali-armhf/var/www/html/powersploit-url | /usr/bin/iconv --to-code~and so on~``

And for `hid-all.py`, changed line 89, 93, 97, 101 which has the same strings
`read_file(filename = "/sdcard/nh_files/configs/rev-tcp")`
to
`read_file(filename = "/sdcard/nh_files/scripts/rev-tcp")`

and now seems it's back to normal function as before. it did work for my device after the above changes.

@jmingov @binkybear 
Hope this helps.

**Comment by jmingov** [comment]
Hey @simonpunk,

Confirmed that `/data/local/nhsystem/kali-armhf` is no needed in `hid-all.sh`.

About the second change, im not too sure, the file is here:
https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/configs/rev-tcp

(You can find it in the phone `/sdcard/nh_files/configs/rev-tcp it should be there)

So please, can you confirm that the file is there?

Thank you again,

Jaime

**Comment by simonpunk** [comment]
@jmingov yes
the `/sdcard/nh_files/configs/rev-tcp` has existed already after the apk is installed,
but what happened to me is that it generated the commands to another `rev-tcp` in `/sdcard/nh_files/scripts/' once I launched the attack. And it executed the commands  from `/sdcard/nh_files/scripts/rev-tcp'.

So after replacing `/configs/` to '/scripts/' in the hid-all.py, it seems back to work for me again.

**Comment by jmingov** [comment]
@simonpunk  you where correct, just pushed the needed changes to nethunter-utils package.

@offensive-security has just updated the package in the kali git repository.

To test the fix, open a kali terminal and issue this command `apt-get update && apt-get upgrade`

Youll see the nethunter-utils 0.8-1kali upgrading. (also burpsuite)

Fell free to close the issue when you confirm.

Thank you again.

Jaime

**Comment by simonpunk** [comment]
things settled.

**Comment by jmingov** [comment]
:dancer:
