### ISSUE TITLE
/system/bin/bootkali[272]: no closing quote

### ISSUE THREAD

**Issue by CharellKing** [offensive-security/kali-nethunter#313]
when i launch "kali nethunter shell menu" on nexus 6, error occurs as below:
 "/system/bin/bootkali[272]: no closing quote"

**Comment by jmingov** [comment]
Which version of nethunter are you running? Which rom?

 Please add more information to the report.

 Thanks

**Comment by CharellKing** [comment]
nethunter version 
Nexus 6 Lollipop	Download	0.8G	2.0	7e8d8bd8689a344b93225d8915a0737d680e433b
https://www.offensive-security.com/kali-linux-nethunter-download/

rom version:
android 6.0.1 (MMB29K)	Link	27dde1258ccbcbdd3451d7751ab0259d	9a76896bed0a0145dc71ff14c55f0a590b83525d
https://developers.google.com/android/nexus/images

**Comment by jmingov** [comment]
Sorry but, 2.0 doesn't support Marshmallow builds.

You need to install beta version of nethunter for that (you need to buid it).

So: 

Reflash stock marshmallow, install TWRP and **superSU BETA 2.64**, and install the zip youll get when building the beta.

For build intructions, go here: https://github.com/offensive-security/kali-nethunter/tree/master/AnyKernel2


Jaime

**Comment by CharellKing** [comment]
Thank you, I'll be back 5.11. Now it's OK
2015年12月31日 下午11:51于 "3boll" <notifications@github.com>写道：
