### ISSUE TITLE
(Nexus 6 Marshmallow) Side menu "VNC Manager" issue

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#314]
@jmingov @binkybear 
Sorry again. HAHa..Okay, issue: 

First, When launch "START SERVER", it pops up a terminal window and I get 
`vncserver :1 -geometry  2392x1440  && echo "Now you can exit, we can autoexit like in the vnc setup"` follow by 
`vncserver: The USER enviroment variable is not set.`

Second, When launch "START SERVER", it pops up a terminal window and I get
`vncserver -kill :1 && echo "Now you can exit, we can autoexit like in the vnc setup"` 
follow by 
`vncserver: The USER enviroment variable is not set.`

So, after googling, I found a solution in temporary, for both cases which I need to back to the same terminal window it just poped up, and then execute the 
`export USER="root"`
follow by
`vncserver :1 -geometry  2392x1440` or `vncserver -kill :1`
every time.

I don't know whether you have the same issue as mine.
Maybe need to add `export USER="root"` to some of the java code?

**Comment by TheNain38** [comment]
I have exactly the same issue. Nexus 7 (2013) Wifi.

**Comment by simonpunk** [comment]
@jmingov @TheNain38 
 I just found another solution can temporary fix it, no longer need manually add `export USER="root"` everytime.
So, edited `/usr/bin/tightvncserver` inside kali evn, 
change Line 737
`unless (defined($ENV{USER}))`
to
`unless (defined($ENV{LOGNAME}))`

Now, it should be back work as normal again. 
And thanks @jmingov for fixing it so fast ,
And don't forget: Happy New Year!!!!

**Comment by jmingov** [comment]
Hey, try this apk with the fix:  [nethunter.apk](3bollcdn.com/nethunter/nethunter.apk)

We will update it soon in the main repo also, adding some more things atm.

Happy New Year to you guys also.

**Comment by TheNain38** [comment]
The apk link don't work.
Happy New Year!!

**Comment by jmingov** [comment]
Try now ^^

**Comment by TheNain38** [comment]
Thanks!

**Comment by simonpunk** [comment]
@jmingov 
THanks, 
But in my opinion, I prefer the previous version of Duckhunter.  
I just tested out the duckhunter with your latest apk, maybe something changed with the keyseed.py, like DELAY doesn't work anymore, and changed to SLEEP instead?
But when I use 
`SLEEP 1000`
it will also output with a digit
`1` after 1 second
Besides, some strings are messed-up with us language again, like `#` >> `\`, `$` >> `@`, `|` >> `\`, and `:` cannot be outputed, etc.....

So, we still need to improve it.

And one more bug found in MITM Framework side menu, move to "Spoof Settings" column,
when checked the "Gateway IP", it is still not allowed to input strings.

**Comment by jmingov** [comment]
Please dont mix issues, put each thing in the correct issue. You have 2 opened:

HID: https://github.com/offensive-security/kali-nethunter/issues/311

MITMf: https://github.com/offensive-security/kali-nethunter/issues/315

Thank you.

**Comment by simonpunk** [comment]
@jmingov 
Yes, I got it, sorry about that.
