### ISSUE TITLE
MITM Framework: Can't set interface to usb0 and it incorrectly sends parameters I didn't set

### ISSUE THREAD

**Issue by TheNain38** [offensive-security/kali-nethunter#315]
I'm on a Nexus 7 (2013) Wifi.
I can't MITM a pc using a BadUSB attack because I can't set interface to usb0.
For example it sends `--black-ips` and `--white-ips` but I didn't set these parameters in the GUI and they give an error because they need some options: `mitmf.py: error: argument --black-ips: expected one argument`.

**Comment by binkybear** [comment]
@TheNain38 - Added usb0 in next build/commit.  Also, black/white ips should be under inject settings.  When you click "Inject only IP" a textbox will highlight underneath.

**Comment by jmingov** [comment]
@binkybear, we need to review mitmf. Added to the todo list.
