### ISSUE TITLE
(Nexus 6 Marshmallow) Macchanger issue

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#317]
@jmingov @binkybear 
I have done the apt-update and apt-upgrade, now it is working fine. Thank you very much.

But now comes to Macchanger, and I have totally no idea on how macchanger works.

First I tried with the app, it didn't work at all, mac address didn't change,
So, I tried another way that the folks used to do on internet, 
`ifconfig wlan0 down`
`ip link set wlan0 address 00:11:22:33:44:55`
`ifconfig wlan0 up`
and I could see it succeeded to change the mac address. However, I thought it would work but it failed to connect back to my wifi, so I think the mac address is literally changed only.

So, to go further, I decided to give a try on a third party app which is "Wifi Mac Changer", and there are two options given to me, which are  "hard change" and "simple change". 

"simple change" gives me the same result as the above three commands, mac address has changed, but not be able to connect to the wifi.

"hard change" gives me the expected result as it can both change the mac address and still have wifi connection, and seems it is needed to shutdown all my network connection first, turn my mobile to airplane mode, set the new mac address, and then turn back on the network. I think this takes half a minute or longer to work. 

And, of course, I don't know how the "hard change" works, maybe macchanger is deprecated for android 6.0 or above already? I am not sure anyway...

So, hope this info help.

**Comment by jmingov** [comment]
You are on a nexus 5?

wlan0 only works for that device. Last time i tested was in lollipop.

**Comment by jmingov** [comment]
Checked wlan1 and i see a null in a toast, something changed in marshmallow, tomorrow ill fix this.

Jaime

**Comment by simonpunk** [comment]
@jmingov 
Thanks, btw, do you mean I can only change mac address for wlan1? But how about wlan0? I do have wlan0 which is built-in and used for wifi connection as usual. And the third party app can change the mac address of my wlan0 and connect back to my wifi as well. Am I confused?

**Comment by jmingov** [comment]
Doing my work, dont worry well get wlan0 ^^.

**Comment by jmingov** [comment]
https://github.com/offensive-security/nethunter-app/commit/46fc0945a74b209e829944878509e77bc1db3f0e

**Comment by jmingov** [comment]
@simonpunk give this apk a try ^^. (Remove the old one before)

[nethunterMAC.apk](http://3bollcdn.com/nethunter/nethunterMAC.apk)

**Comment by TheNain38** [comment]
Also, @jmingov, I lose my original MAC on wlan0, is it an issue or not?

**Comment by jmingov** [comment]
no, dont worry, it can be restored in the top left menu.

**Comment by TheNain38** [comment]
Yes, but at that time, it didn't saved it... It was before you rewrote it

**Comment by jmingov** [comment]
Is restored, no need to save it. (Is in the hardware you cant loose that)

**Comment by TheNain38** [comment]
Yes I'm downloading it

**Comment by TheNain38** [comment]
No, I really lose it, your menu don't restore it to its original one

**Comment by jmingov** [comment]
mmm, you changet the mac with old nethunter app?

**Comment by TheNain38** [comment]
yes, and first time it didn't work, and then it worked and said to me that it needed to save the current mac to be able to restore it later, but it already changed it before saving it...

**Comment by TheNain38** [comment]
Can it cause problems?

**Comment by TheNain38** [comment]
Also your new code does not check if the custom mac entered is correct or not

**Comment by jmingov** [comment]
what do you mean? 01-23-45-67-89-ab-cd-ef  are valid chars, what checks you think i should add?

**Comment by TheNain38** [comment]
That it is complete

**Comment by jmingov** [comment]
The old app was only creating a file here: /persist/wifi/.macaddr if is there you can delete it. 

But that file is not able to change the hardware mac.

Ill add a check for not complete macs.

**Comment by TheNain38** [comment]
And also, I was doing a BadUSB attack and tried to change the MAC of usb0 (I'm on a nexus 7 (2013) wifi) and the application crashed. When relaunching it, if I go in macchanger menu, it crashes before I'm able to change anything.

**Comment by TheNain38** [comment]
And there is no file in /persist/wifi/.macaddr

**Comment by jmingov** [comment]
The mac you see is the original im pretty sure. You can check what the old code was doing here:

https://github.com/offensive-security/nethunter-app/commit/46fc0945a74b209e829944878509e77bc1db3f0e#diff-825d74810cc0de1deb1c1dda83211859L233


Also added the check for incomplete custom mac address here:

https://github.com/offensive-security/nethunter-app/commit/056fb9f2e030a79927565560df8803fc6e6fdb77


Feel free to close this.

**Comment by jmingov** [comment]
Note: in the remote/improbable case that the hardware mac changed, ther's no problem while the mac is a valid one.

The Media Access Control address is just for identification with other devices (routers pcs etc).

**Comment by TheNain38** [comment]
Yes, I know, but now I can't changed it anymore.

**Comment by jmingov** [comment]
which mac is the one you have now?

**Comment by TheNain38** [comment]
not the original one

**Comment by jmingov** [comment]
Ok, the issue is solved. Now all interfaces listed can be changed. Closing this.

**Comment by jmingov** [comment]
https://vimeo.com/150536122

**Comment by binkybear** [comment]
Confirmed working on OnePlus one.

**Comment by simonpunk** [comment]
@jmingov @binkybear 
I have tried, but still it din't change anything, no matter the random and custom mac. 
I got the same original mac address after refresh.
I guess maybe there is a slight different setting for Nexus 6?

**Comment by jmingov** [comment]
@Binkybear has a n6 (i think), maybe he can flash mm and tell you something.

**Comment by simonpunk** [comment]
@jmingov 
Now I can't even changer my mac to others manually, but the third party app still works for me. So strange....
May I know what's the sequence to change mac address? is it:
`Turn on airplane mode`
`ip link set dev wlan0 address`
`Turn off airplane mode`
???

Or maybe just wait for @binkybear to me something..

**Comment by TheNain38** [comment]
Maybe this is the same issue I encounter on my Nexus 7 (2013) when trying to change MAC, and I downloaded the third party app to test, and it works with the third party app, but not with your macchanger

**Comment by binkybear** [comment]
@jmingov fixed: https://github.com/offensive-security/nethunter-app/commit/d5898214e6eea23de9f1f3e2ec592b121555b860

**Comment by simonpunk** [comment]
@binkybear 
May I know how to compile the apk by myself? can I do it by myself?

**Comment by jmingov** [comment]
Si, download android studio, clone the proyect. Just that ^^.

But note: 

> Update: Looks like commit kills wifi. Not working ATM.

**Comment by simonpunk** [comment]
@jmingov 
Thank you very much~ succeeded to compile the apk. But yeap, now I see it changes the mac, but same as before, cannot connect back to wifi.

**Comment by simonpunk** [comment]
@TheNain38 Hi, I wonder if you have solved the macchanger issue already, it still not working for me, even though it changes the mac address, but cannot connect to wifi instead. So, any ideas??

**Comment by jmingov** [comment]
@binkybear tested on Nexus 6, worked fine for him tho.

**Comment by simonpunk** [comment]
@jmingov Sure, I am using nethunter 3.0, but still no effort, I am also wondering why it happens to me. 
Should I post some cat logs to you? But How???
One thing I can just know is I can't get a inet6 address after changing the mac address, and I think it's one of the reason causing this problem, but, I don't know.....

**Comment by binkybear** [comment]
@simonpunk 
Could you try the command manually and see if it works for you:
```
su
svc wifi disable && svc wifi enable && ip link set dev wlan0 address 00:11:22:33:44:55
```

**Comment by simonpunk** [comment]
@binkybear , No, it doesn't, I know thats what the apk has been doing here, but still not working for me.
But, I tried on a government wifi hotspot outside today, and it seems working for this type of network.
So, I am kinda out of ideas and clues that causing this problem...even google is not by my side now as well.

**Comment by Aporichito** [comment]
@binkybear for your information, when I do that command on terminal emulator then emulator reply- cannot found device "wlan0". At this time what should I do now?
