### ISSUE TITLE
sudo error - mounting problem?

### ISSUE THREAD

**Issue by Bauta76** [offensive-security/kali-nethunter#319]
Hi guys, 

I have an issue with the "sudo" command. 

I created a new user and set up the sudoers file in order to allow the user to run commands with no password, but when I run any command via sudo, I get the following error:

"sudo: effective uid is not 0, is /urs/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?"

I had the same error in the past and what I did was remounting the file system using the "suid" option. But in the case of nethunter I'm not sure what should I do. Could you please give me an hint to solve the issue?

**Comment by jmingov** [comment]
Hello @Bauta76, 

kali is mounted in `/data` so:

1st:
As superUser remount data (**outside** kali as root):
    
    busybox mount -o remount,suid /data

2nd:
Next you need to add the suid bit to sudo binary (**inside** kali shell as root):

    chmod +s /usr/bin/sudo


With that you should be able to use sudo w/o problems.

> Note: Step 1 should be repeated if you reboot the phone.


We will change this asap so is not needed to do it by hand.

Jaime

**Comment by Bauta76** [comment]
Thank you very much. It worked perfectly!
I was missing the chmod +s part. Now everything is working fine.

Thank you.

Cheers

**Comment by jmingov** [comment]
ill keep the issue opened until we add this to kali.

Thank you for the report.

cheers, 

Jaime

**Comment by jmingov** [comment]
Done, this is fixed in latest app commits. 

https://github.com/offensive-security/nethunter-app/commit/a66766d2332fe109c8470fc75ae64ee827f4228f
https://github.com/offensive-security/nethunter-app/commit/494c78eb6a794f642595591163a435acb37affb2
