### ISSUE TITLE
Nethunter - build from scratch

### ISSUE THREAD

**Issue by Bauta76** [offensive-security/kali-nethunter#320]
Hi guys, 

@jmingov fixed an issue related to sudo (https://github.com/offensive-security/kali-nethunter/issues/319) and I decided to build nethunter from scratch in order to get the new fix. 

I followed the instructions and, since I have a Nexus 7 2013 (WiFi), I build nethunter in this way:

python build.py -d flo --lollipop

I got the .zip file, I stored it on my device, then restarted it in recovery mode and installed the .zip file. Everything worked perfectly with no pain at all. 

The problem is that I do not see the nethunter icon anymore. So I can't access to the nethunter menu. I see there is a nethunter terminal icon, but when I click on that and I chose the "kali terminal" it just crashes. 

Not sure if I need to wipe my partitions first, reinstall first lollipop and then reinstall nethunter?

Or is there any other procedure that i may have missed?

Thank you in advance. 

Cheers

**Comment by jmingov** [comment]
Hey @Bauta76 

> reinstall first lollipop and then reinstall nethunter <-- thats the key think.

Looks like you coming from an old nethunter (2.0 from website).

Also to be sure, cd to the nethunter folder (the repo you cloned) and do: `git pull` so you get the latest changes (done few hours ago: https://github.com/offensive-security/kali-nethunter/commit/595a6be606736c67082a7c5f112aaec3771ae356)


So steps are:

- Flash stock (Lollipop or Marshmallow < you need to build new zip if going for marshmallow) 

- Install TWRP and superSu BETA 2.64 from: http://download.chainfire.eu/750/SuperSU/BETA-SuperSU-v2.64-20151220185127.zip

- Flash the zip you build from Anykernel.

Jaime

**Comment by jmingov** [comment]
You can use this to flash all this things: https://github.com/offensive-security/nethunter-LRT

**Comment by Bauta76** [comment]
Ah nice the LRT. Did not know about it. 
I will surely try it and follow the steps. 

Thank you for that.

Cheers

**Comment by jmingov** [comment]
@Bauta76, you built it ok?

 Ill close this in 24h if you dont confirm, since we have no issues building for n7 2013.

Jaime
