### ISSUE TITLE
Alfa AWUS036H cause system freeze and reboot

### ISSUE THREAD

**Issue by TomasAndersonvoid** [offensive-security/kali-nethunter#321]
Thanks binky and otherguys who did a great job on this. I am using the kernel uploaded 4th January 2016 on my Nexus 6P marshmallow. When I was trying to plug my Alfa AWUS036H wireless card through OTG, it results system freeze for 3 seconds then reboot again and again. Is there any solution for this?

**Comment by binkybear** [comment]
@TomasAndersonvoid - I dont have a Nexus 6P but i you could send me your kernel oops it would be a start in tracking down issue.  In android shell with root:

```
su
cat /proc/last_kmsg > /sdcard/kerneloops.txt
```

**Comment by TomasAndersonvoid** [comment]
Thanks binky for your reply here is the kernel oops file hopefully it helps. 
[kerneloops.txt](https://github.com/offensive-security/kali-nethunter/files/79361/kerneloops.txt)

Also I tried to enable and disable Y cable charging, there is no difference, error occurs. the file is generated in the condition Y cable carging enabled.

**Comment by TomasAndersonvoid** [comment]
Hi binky, the file keep showing
 "sush: /proc/last_kmsg: not found"

**Comment by offensive-security** [comment]
My gut feeling tells me that the AWUS036H would draw too much power from a phone, without being connected externally with a USB charger...

**Comment by TheNain38** [comment]
It draws 1 Watt if I remember. If I'm not wrong it means it needs 200mA, because with:
1W = 5V × A
A = 0.2
200mA

**Comment by TomasAndersonvoid** [comment]
I have managed to get the file from /data/system/dropbox. here is it hopefully it helps thanks guys
[SYSTEM_LAST_KMSG@1452053596506.txt](https://github.com/offensive-security/kali-nethunter/files/79999/SYSTEM_LAST_KMSG.1452053596506.txt)

**Comment by TomasAndersonvoid** [comment]
Sorry guys I was wrong on the model, it should be ALFA USB WIFI AWUS036NEH
It was working well on my nexus5

**Comment by binkybear** [comment]
@TomasAndersonvoid - Thank you for the kernel oops.  I found an oops patch that looks familiar to the problem you are having:

https://github.com/CyanogenMod/android_kernel_samsung_d2/commit/88e9526f041871c3733d9549668efdc23ca7568c

I have modified the above patch and applied to kernel here: https://github.com/binkybear/AK-Angler/commit/a9895a667aa1f3e0d3a9a7cd91809a45dcbdb82e.  I have uploaded updated zImage to this repo.  Feel free to test whenever.

**Comment by TomasAndersonvoid** [comment]
@binkybear thanks binky, I have test the new update, freeze and quit problem solved. However, the device can not reconize ALFA USB WIFI AWUS036NEH. The light on wifi card is not flashing (flashing means working). And ifconfig shows there is no external wifi devices.

**Comment by binkybear** [comment]
Can you send me output of your dmesg after you plug in and disconnect your alfa card?
```
su
dmesg > /sdcard/dmesg.txt
```
You can email it to me @ binkybear@nethunter.com

**Comment by TomasAndersonvoid** [comment]
@binkybear I can bring the wifi card up by using ifconfig wlan1 up lights flashing but wifite will not reconize the wifi card I am trying to get the dmesg however like before the dmesg.txt just output :/ # I am trying to find the file somewhere insted of a output

**Comment by binkybear** [comment]
So wifite is working for you if you enable monitor mode first?

**Comment by TomasAndersonvoid** [comment]
yes
