### ISSUE TITLE
wrong paths in the default MANA's config files

### ISSUE THREAD

**Issue by Bauta76** [offensive-security/kali-nethunter#323]
Hi guys, 

Not an issue, but I just wanted to notify that I the scripts "nat-mana-full" and "nat-mana-simple" have by default the variable "conf" pointing to a "wrong" path (I just downloaded and build the latest nethunter update). 

In particular, the conf variable is pointing to the path 

"/sdcard/....../hostapd-karma.conf"

instead of

"/etc/mana-toolkit/hostapd-karma.conf"

Nice work with version 3! Really love it. 

Cheers

**Comment by jmingov** [comment]
Hi @Bauta76 

The paths are correct, the config file is here:

https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/configs/hostapd-karma.conf

and is used by the script here:

https://github.com/offensive-security/nethunter-utils/blob/master/usr/share/mana-toolkit/run-mana/start-nat-full-lollipop.sh#L4


And the app uses that path here:

https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/ManaFragment.java#L87

Think that we modified mana to fit nethunter.

Which error you having?

**Comment by Bauta76** [comment]
Hi

When I run mana the first time, the error was saying that the file hostpad-karma.conf was not found at the following path:

/sdcard/nh_files/configs/hostapd-karma.conf

Infact I found that file in the folder /etc/mana-toolkit. So I changed the value of 'conf' in order to point to the path /etc/mana-toolkit

**Comment by jmingov** [comment]
Can you show me the error, i just did a clean install, pluged wlan1 external card, edited karma via app (first page of mana) changed ap name FreeInternet to FreeInternet2 and launched mana.

Result:

![mana](http://i.imgur.com/3imAbdf.png)

**Comment by jmingov** [comment]
We cant reproduce this. Closed.

**Comment by Bauta76** [comment]
Hi, 

sorry for the delay, but before answering I needed to reflash everything again. Ok what I was saying is that the first time I run mana, it was unable to find the file 

/sdcard/nh_files/configs/hostapd-karma.conf

and the the tool was exiting... 

This evening I wiped everything and re-flashed and finally it worked with no problems. 

Thank you!
