### ISSUE TITLE
[Lollipop] Kali Linux 2.0 boot problem for Nexus 5 

### ISSUE THREAD

**Issue by shmshd12** [offensive-security/kali-nethunter#324]
I recently flashed Kali Linus 2.0 Lollipop for Nexus 5 and now i only see Google screen! Does not boot up. Tried in my other N5 too same problem. Guess this is issue with the flashable zip.

**Comment by jmingov** [comment]
2.0 is now replaced with 3.0. 

Update your kali nethunter install.

Flash a clean stock rom and follow the wiki instructions: https://github.com/offensive-security/kali-nethunter/wiki#40-installing-nethunter-on-your-android


Also thats for any nethunter version: You should always check that the zip file you donwloaded is not corrupted.

**Comment by shmshd12** [comment]
Updated to 3.0 but now im stuck at installation 
http://imgur.com/X2c86Sl.jpg

**Comment by jmingov** [comment]
you flashed a clean stock before updating??

**Comment by shmshd12** [comment]
*updating to 3.0

It is freeing up space since 20min! Still waiting for it to finish! Guess it is stuck there

**Comment by shmshd12** [comment]
Yes!

**Comment by jmingov** [comment]
The aroma installer @binkybear sometimes stuck, try to rebooting the phone. (Usualy is the ui, the install process ends ok).

**Comment by shmshd12** [comment]
Is netHunter 3.0 marshmallow based on 6.0.1 or 6.0? Actually i flashed 6.0 and then tried 3.0 Marshmallow.

Will reboot now and check.

**Comment by jmingov** [comment]
Can you check the wiki please, all the info is there. (6.0.1) but you should not have problems with 6.0 anyways.

**Comment by shmshd12** [comment]
I rebooted and all the main apps gets stopped (settings too) will start again with a clwan flash again and then check

**Comment by shmshd12** [comment]
*clean

**Comment by jmingov** [comment]
which rom are you flashing, where you donloaded it?

**Comment by shmshd12** [comment]
Downloaded the ROM from official Google's factory image site. I do not have an edit option to edit my comments since im using this site from a mobile device.

**Comment by TheNain38** [comment]
You can click on Desktop version at the bottom of Github

**Comment by binkybear** [comment]
We are no longer supporting 2.0 builds, closing this issue.
