### ISSUE TITLE
y cable issue

### ISSUE THREAD

**Issue by nicking989** [offensive-security/kali-nethunter#325]
I'm having a problem with the y cable charging service. I am on the latest build on a Nexus 4.
The issue is that I start the service from the services tab, it seems to work as it used to.
Then if I go into a different fragment and back to the services one it will be off again.

Also I have found that in the nethunter terminal app, if I use either the suandroid or kali terminals my sdcard directory appears empty when using 'ls' after cding into it. When using the normal android terminal it works fine. I'm sure this never used to be the case? Just a permission issue?

**Comment by jmingov** [comment]
Hello nicking989,

Open one issue for each problem the next time please.

We need to know:

- Android version you using.

- SuperSu version you using.

- You flashed a clean stock before updating to 3.0?

- You can check the permissions of the terminal app in the Apps phone settings, but looks more like a mount issue. (Long press the app icon and drop it to the info icon you will see).

-

**Comment by jmingov** [comment]
@nicking989 for the sdcard problem we will use https://github.com/offensive-security/kali-nethunter/issues/332

(Give us this info when you can https://github.com/offensive-security/kali-nethunter/issues/332#issuecomment-169873171)

**Comment by nicking989** [comment]
Sorry about that. I am using stock 5.1.1 freshly flashed. Everything was the latest build from github as of when I created the issue. Supersu is the one that came with the nethunter install I built (2.64). Nethunter version 3.0.
I just did a full wipe and reinstall and have the same issue.

**Comment by ffaggiani** [comment]
Hi, just to say that I am having the same issue.

ROM: Cyanogenmod 5.1.1 latest stable build
Nethunter 3.0

NetHunter is not recoigozing USB connected by OTG using external power supply and Y-cable.

I u have news, please let me know.

REgards,
Fab

**Comment by John-Peter-Sofer** [comment]
Hi all,

I have the same issue on Nexus 6 with: 
- Marshmallow and Nethunter 3.0.5 
- Lollipop and Nethunter 3.0.5

Does anyone know if the hardware of Nexus 6 can support OTG+charging ?
In other words, on Nexus 6, is it an issue or it is normal that we cannot enable Y-cable Charging option?

Thank you,

Best Regards,
JPS

**Comment by jmingov** [comment]
No, it doesnt support it.

https://github.com/offensive-security/kali-nethunter/issues/363

**Comment by John-Peter-Sofer** [comment]
Thank you !

**Comment by ffaggiani** [comment]
And what about nexus 4?, i still cannot see tp-link 722n using otg-y cable.

**Comment by ffaggiani** [comment]
any news?

**Comment by binkybear** [comment]
@ffaggiani - Updated kernel for Nexus 4.  Switch to AK's kernel on lollipop (not CM).  Feel free to test.

**Comment by diimdeep** [comment]
Nexus 4
Y-cable
cm-13.0-20160820-SNAPSHOT-ZNH5YAO0J5-mako.zip
nethunter-generic-armhf-kalifs-minimal-rolling-3.15.2-20161010-0317
kernel-nethunter-makocm-marshmallow-3.15.2-20161010-0317

- (USB -> Ethernet) AX88772  - works.
- (SDR) Elonics e4000 - not recognized
- (USB -> WiFi) Atheros AR9271 AzureWave AW-NU137 - not recognized

**Comment by jcadduono** [comment]
Need USB ids for them

Vendor Id and product id, you can find them with lsusb

**Comment by diimdeep** [comment]
@jcadduono
- (USB -> Ethernet) AX88772 : `ID 0b95:772b ASIX Electronics Corp. AX88772B`
- (SDR) Elonics e4000: `ID 13d3:3327 IMC Networks`
-  AzureWave AW-NU137: ` ID 05c6:9048 Qualcomm, Inc.` 

from kali: rtl_test works.
from android: SDR Touch don't. (why ?)

Also..
Gettin random reboots at this nightly(kernel ?)

Also.. tried before
kernel-nethunter-makocm-marshmallow-3.1.0-20160831-1936
nethunter-generic-armhf-kalifs-full-rolling-3.1.0-20160831-1936
And.. (USB -> WiFi) Atheros AR9271 AzureWave AW-NU137 - worked only as wlan0, if attach it while wifi off and then enable wifi trough android pref it will use this external card as default wlan0.
But while built in wifi active it is also not recognized.

**Comment by ezdevelop** [comment]
@jcadduono 

There is a bug for check-ycable script (https://github.com/offensive-security/nethunter-app/blob/master/assets/scripts/check-ycable#L7), the value of $CHEKMSM should be 'Y'.

After started the y-cable service, the value of usbhost_charge_mode is 'Y'
cat /sys/module/msm_otg/parameters/usbhost_charge_mode
Y

Because the kernel will use 'Y/N' instead of  '1/0' for human readable.
https://github.com/jcadduono/nethunter_kernel_mako/blob/cm-13.0/kernel/params.c#L316

**Comment by jcadduono** [comment]
thanks @ezdevelop i will make the nethunter app check for both Y/1 and N/0

**Comment by jcadduono** [comment]
@ezdevelop  https://github.com/jcadduono/nethunter-app/commit/6c902257fe2f59ddf513e8872e08ca36eb70c0b0

**Comment by ezdevelop** [comment]
@jcadduono 

BTW, would you please update the ASIX AX8817x driver for makocm kernel or add a quick fix to support 'DLink DUB-E100 H/W Ver C1' and 'Lenovo U2L100P 10/100', both of them are AX88772B chip.

Here are the USB ids and quick fix for them:

> // DLink DUB-E100 H/W Ver C1
> USB_DEVICE (0x2001, 0x1a02),
> .driver_info = (unsigned long) &ax88772_info,
> 
> // Lenovo U2L100P 10/100
> USB_DEVICE (0x17ef, 0x7203),
> .driver_info = (unsigned long) &ax88772_info,

The ASIX AX8817x driver in makocm kernel is really too old :( , but the quick fix works for me. :)

**Comment by jcadduono** [comment]
can you join #nethunter on freenode irc for test builds

**Comment by jcadduono** [comment]
@ezdevelop https://github.com/jcadduono/nethunter_kernel_mako/commits/cm-13.0

**Comment by ezdevelop** [comment]
@jcadduono cool :+1: 

And sorry, I can't connect to freenode :(

Anyway I will try your nightly build and report if it works or not.

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/lge/kernel-nethunter-makocm-marshmallow-2.2-test1.zip
let me know if that works (or even boots)
i made a lot of changes

**Comment by ezdevelop** [comment]
@jcadduono 

I have flashed the test build, and yes, the new driver works fine for 'DLink DUB-E100 H/W Ver C1' and 'Lenovo U2L100P 10/100', the only problem is that DHCP failed, I need to manually set the IP address.

> init: no such service 'dhcpcd_eth0'
> init: no such service 'dhcpcd_eth0:-f /system/etc/dhcpcd/dhcpcd.conf -h android-wukong eth0'

![screenshot](https://cloud.githubusercontent.com/assets/676581/21430854/e8d12016-c89f-11e6-9deb-073b86127b09.png)

And there are some other kernel warning and error, please see the dmesg log:
[dmesg.txt](https://github.com/offensive-security/kali-nethunter/files/669103/dmesg.txt)

**Comment by jcadduono** [comment]
looks fine to me, the no such service thing is a rom issue, are you trying to use the adapter with android?
you can set up a dhcp client in kali root.
you should report the dhcp service issue to your android rom maintainer
the warning on vfs bounce is normal and can be ignored
