### ISSUE TITLE
Weird issuse

### ISSUE THREAD

**Issue by ViSioN-BluR** [offensive-security/kali-nethunter#326]
Hello so just today i installed nethunter 3 on my HTC one m9 was bored, so basicly everything is okay no errors only problem is on android i cant do command like iw, or ifconfig is empty.. but on putty when i do ssh everything works so how can i fix it?

**Comment by ViSioN-BluR** [comment]
solve it just need to use command "su -"

**Comment by marcocet** [comment]
Were could I get a download for the Kali nethunter rom for HTC One M9?
