### ISSUE TITLE
Nexus 9 Nethunter 3.0 wn722 firmware problem

### ISSUE THREAD

**Issue by yavuzgokhan** [offensive-security/kali-nethunter#327]
Hi, I flash Nethunter 3.0 on my Nexus device 6.0.1 stock Rom. But I can't start my external wifi Wn722. My dmesg result is "failed to get firmware htc_9271.fw "
When I type "lsusb" I see my atheros AR9271 device.
I tried  install firmware-atheros but not working. can you help me?
It was working on stock 5.1.1 and Nethunter 2.0

**Comment by binkybear** [comment]
@yavuzgokhan : Could you try flashing the kernel again by going into recovery and flashing the zip file below?  Missing firmware indicates it wasn't installed:

https://transfer.sh/nIH4a/kernel-nethunter-flounder-marshmallow-712016-135154.zip

If that doesn't help we can start looking at /system size issues.

**Comment by yavuzgokhan** [comment]
@binkybear thanks for yor attention. my kernel was 3.10.40-g6857980-dirty root@kali #2 
I flashed your kernel, nothing change kernel version is same and my ext wifi is not working. What can i do? I think I have some problems about my tablet, when I'm backing stock rom, I had too many problems. but I succeed but now my twrp recovery is very slow.  My build number is MMB29S for now. I think I have some issues. Maybe I should fresh flash stock rom again. what do you think about that?

**Comment by binkybear** [comment]
So on the Nexus 9 the boot into recovery is a few minutes.  Thats normal.

I am not sure why your firmware didn't copy but here is a zip copy of it: https://transfer.sh/19JxZ9/firmwarezip.zip

You will have to put it on your sdcard then either in adb or on terminal:
```bash
su
mount -o remount,rw /system /system
unzip /sdcard/firmwarezip.zip -d /system/etc/firmware
```
This is assuming that the only thing missing is the firmware.

**Comment by yavuzgokhan** [comment]
I tried that but when i write "mount -o remount,rw /system /system" it says "cannot remount system read-write,  is write-protecting"

**Comment by binkybear** [comment]
If you cant do it live you can mount /system in recovery and do it that way.  Just boot into recovery and: 
busybox mount /system

I'm not sure why you can mount your system as rewriteable.  Everyone with root should be able to.

**Comment by yavuzgokhan** [comment]
I think I was wrong because I wrote all of this command on terminal at kali shell. Should i try on androidsu shel?

**Comment by yavuzgokhan** [comment]
Ok i fixed my problem with usingnes explorer. Thank you my friend

**Comment by jmingov** [comment]
So nice @yavuzgokhan
