### ISSUE TITLE
Nexus 7 (2013) wifi only: Can't connect using wifi using DHCP on some network

### ISSUE THREAD

**Issue by TheNain38** [offensive-security/kali-nethunter#328]
If I setup a static IP it works, but using DHCP it won't on my home network. The router is an old one (e.g. highest wifi encryption standard available on it is WPA-PSK)

**Comment by jmingov** [comment]
Maybe is the router whos not assigning the ip?

**Comment by TheNain38** [comment]
It was working, and one day when booting up, it won't work anymore

**Comment by jmingov** [comment]
Why do you think is a nethunter issue then @TheNain38 ? You changed something in the phone?

**Comment by TheNain38** [comment]
No, it was after my MAC address was being bugged, and it was changing each time it I was rebooting, and then it wouldn't want to connect anymore using DHCP

**Comment by jmingov** [comment]
:/ sorry but we cant fix this/or reproduce it @TheNain38 no sure what happend to your phone.
