### ISSUE TITLE
Terminal error "1) no title" on Nexus 6 running 6.0.1

### ISSUE THREAD

**Issue by ExWoomera** [offensive-security/kali-nethunter#329]
Device: Nexus 6
ROM: stock rooted 6.0.1 (MMB29S)
Root: SuperSU v.2.66 BETA
ROM State: clean install + supersu + busybox
1. the kali kernel is installed. checked!
   2.the installation completes with no error during the process but when it finishes and twrp window appears again this is what i see:  
   https://dl.dropboxusercontent.com/u/435242/twrp-nethunter-error.jpg
   3.when rom loads up and i fire kali nethunter when i try to run anything like nmap or the terminal emulator itself an error message appears with the text "1) no title" and then nothing happens.
   4.tried flashing twice and same thing.

**Comment by binkybear** [comment]
@ExWoomera - The errors during install are more about symbolic directories and not really much to worry about.

The fact your terminal isn't working tells me its may be related to missing symlinks.  Can you check if you are missing:

/system/bin/bootkali_login
/system/bin/bootkali_bash

Easiest way is to use from computer:
```
adb shell
su
ls /system/bin/boot*
```

**Comment by ExWoomera** [comment]
this is the output:

/system/bin/bootanimation
/system/bin/bootkali
/system/bin/bootkali_bash
/system/bin/bootkali_login

**Comment by binkybear** [comment]
I forgot to ask you to check the make sure those were symlinked to /data/data/com.offsec.nethunter/files/scripts/boot*.  Can you check with ls -lisa?

**Comment by ExWoomera** [comment]
so i ran "ls -lisa /data/data/com.offsec.nethunter/files/scripts/boot*" and here is the output:

/data/data/com.offsec.nethunter/files/scripts/boot*: No such file or directory

**Comment by slick97477** [comment]
Is there a way to manually create the symlinks?

**Comment by binkybear** [comment]
@slick97477 and @ExWoomera - We are going to look into if the paths changed in recent updates to /data/user/0/com.offsec.nethunter instead of the usual location.  If that's the case we will have to change symlink locations.

**Comment by slick97477** [comment]
Thank You very much for looking into this

**Comment by 3mrgnc3** [comment]
I have a similar issue, but can't create the symlinks because my Nexus 6 is stuck in a boot loop.
I submitted it as a separate issue #330 but feel free to close it if you are dealing with it already.

I am a bit stuck now though :8ball: :(

**Comment by jmingov** [comment]
@3mrgnc3, you have a diferent issue, not related with this.

Install a clean stock, twrp and superSu beta 2.64, then install nethunter 3.0 from https://www.offensive-security.com/kali-linux-nethunter-download/

**Comment by 3mrgnc3** [comment]
Cheers, 

I already realised that after foolishly amusing it was the same issue because I had similar errors.

I'm closely and precisely following the wiki now :baby:  . A very good wiki it is too Well done to everyone who contributed and put the work it on it.

Got my Nexus 6 working again.

**Comment by jmingov** [comment]
@slick97477 and @ExWoomera, we are not able to reproduce this, the only thing diferent is we using superSU 2.64, (i doubt that this is the problem)

Some more questions: 

When you guys opened the nethunter app for the first time, it should ask for a few permissions, then for SU permission, and after that, the app will setupt some things and copy thouse files you guys are missing (in a app dialog).

Did you saw all this ?

Can you check that nethunter app have the correct permissions in `phone settings > apps > NetHunter > permissions`?

(It needs all this: Storage and the 5 additional permissions)

**Comment by craigsmooth** [comment]
I am experiencing a similar issue with grouper (nexus 7 2012). Can't run a kali shell. If I do a find / -type f -name "bootkali". I get no results.

**Comment by ExWoomera** [comment]
Hello Jimingov,

sorry for the late reply (time zone differences i guess).

1. all permissions has been granted, checked.
2./data/user/0/com.offsec.nethunter/   is empty! there is no file or folder.

**Comment by binkybear** [comment]
@craigsmooth -  Bootkali should be installed in app.  Usually its located in /data/data/com.offsec.nethunter/files/scripts/bootkali.  Can you check that you have that folder.

I did a complete install with Nexus 6 last night and everything is working OK.

**Comment by ExWoomera** [comment]
for me under /data there is only one folder and that is "0".

**Comment by craigsmooth** [comment]
@binkybear - fresh install of nethunter 3 (flash zip via twrp) on nexus 7 2012 (grouper):
Launching "Kali Shell" gives me no window
Launching "androidsu" shell:
 /data/data/com.offsec.nethunter/files/scripts/ directory is empty
Any ideas?
Thank you!

**Comment by binkybear** [comment]
@craigsmooth - Can you do a search for bootkali in androidsu?  The scripts folder should automatically have files from Nethunter app.

**Comment by craigsmooth** [comment]
@binkybear - i have the scripts directory but it is empty.

**Comment by JimWas** [comment]
Same issue here on a Nexus 6. Terminal immediately crashes. Have reinstalled from a fresh stock image. System links are as follows after running the app.

ls /system/bin/boot*
/system/bin/bootanimation
/system/bin/bootkali
/system/bin/bootkali_bash
/system/bin/bootkali_login

**Comment by clambert122** [comment]
reporting same issue on a HTC Nexus 9 wifi

**Comment by t0mps0n** [comment]
I put in the symlink and I'm still getting no title when I run anything from custom commands

**Comment by t0mps0n** [comment]
@binkybear what build did you use for installing nethunter and did you do nano install

**Comment by t0mps0n** [comment]
I got it working, had to reflash stock then install nethunter again my build is 6.0.1 MMB29V

**Comment by TaiSHiNet** [comment]
I ran into this issue, I was building the image without --rootfs, rebuilt with that and all good!

**Comment by NFIRE000** [comment]
@TaiSHiNet
I ran into this issue, I was building the image without --rootfs, rebuilt with that and all good!

If you don't mind. How do the output text look for making rootfs with the bluild of nethunter.

root@kali:~/kali-nethunter/nethunter-installer# python build.py -d bullhead --m.

**Comment by jcadduono** [comment]
./build.py -d bullhead -m -fs full

./build.py -h

**Comment by NFIRE000** [comment]
Thank you so much

**Comment by bossjones** [comment]
For anyone still dealing with this issue. Seems like you just need to uninstall your kali chroot, then re-install it. Once I did that, everything worked. Tested on 6.0.1 Nexus 5.

**Comment by luma420** [comment]
still haveing issues with the chroot ig^^
i reinstalled them via app but still i get the no title error if i try to open up kali terminal

**Comment by akrolla** [comment]
have you tried reflashing the kernel ? I had troubles with my nexus 5
installing the chroot. Try flashing the phone and then rooting and then
installing the kernel before installing the nethunter package , my nexus 5
kept locking up and I couldn't get a chroot installed and the.SHA1SUM
wasn't matching. the install was so large with the kernel and nethunter
package and chroot I couldn't get a proper install until I separated the
two .

**Comment by equi-design** [comment]
Possible solution for some users: 
After the "no title" window crashes, go into your superuser application & verify that Terminal Emulator has been granted full su privileges. On some systems (or su apps besides SuperSU by Chainfire), terminal crashes too quickly for su permissions to be granted the "normal" way.

**Comment by Subhesh7** [comment]
For 1) no title error pls follow the below steps
Required root explorer pro
a. symlink bootkali, bootkali_bash, bootkali_login in between /data/data/com.offsec.nethunter/files/scripts and /system/bin 
lots of guides are there how to do it
b. Give **Execute** permission to above 3 files in the owner section..in simple term bootkali, bootkali_bash, bootkali_login should be **rwx** in /data/data/com.offsec.nethunter/files/scripts.

Hope this will solve no title error in terminal...enjoy

**Comment by innovateworld** [comment]
I kept receiving `1) No Title` Error also after installing chroot. I went to Kali Services and turned on SSH then all (an by that I mean opening Kali Terminal and NMAP) was good.

**Comment by ius1122** [comment]
I installed kali net hunter but cannot select  kali shell it 's saying  no Title. Please please help me my phone j7 (6 )
Sdk 23
Arm 32

**Comment by bhavik9090** [comment]
I installed kali net hunter on my android device but it's saying setenforce: not found
Missing a required folder. Something isn't right

**Comment by Rob-B1** [comment]
on two seperate nexus 7's I have an issue where nethunter opens with unfortanately the android phone process has stopped and mobile netowrk configuration has stopped. This is with the wifi image 2013 nexus 7.   Then settings has stopped.   When i click settings it reults in unfortunately, settings has stopped. "

**Comment by 143Sarika** [comment]
In my case, everything is fine. All files are place at correct place. Still, when i open terminal it always gives no title and apt-get not found error.
P.s. using xiomi mi 5 pro, busybox pro already installed.
