### ISSUE TITLE
OnePlusOne - NetHunter 3.0 E:error opening /data/local/nhsystem/kali-armhf/dev/ram12

### ISSUE THREAD

**Issue by CarlisleChan** [offensive-security/kali-nethunter#331]
For some reason my nethunter 3 install is failing on OnePlusOne. I boot to TWRP to flash the zip and it appears to finish but I get a lot of repeat errors afterwards in the TWRP console (see below). I can not boot into my OnePlusOne. Any thoughts? Thank you!

Updating partition details...
E:error opening /data/local/nhsystem/kali-armhf/dev/ram12
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram14
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram16
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram10
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram13
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram15
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/loop6
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram4
E:error: Not a directory
...
...
...

**Comment by binkybear** [comment]
You can disregard those errors, they are symlinks that TWRP is trying to follow.  If you have any more issues with chroot let me know, but I believe you can close this issue unless you notice errors related to this.

**Comment by CarlisleChan** [comment]
But these are ignored, will enter into recovery mode after reboot. Could not get system

**Comment by jmingov** [comment]
Did you flashed a clean Cyanogen OS 12.1 (5.1.1)	 cm-12.1-YOG4PAS3JL before flashing the zip?

This is important

**Comment by CarlisleChan** [comment]
I flashed cm-13.0-20160107-NIGHTLY-bacon before flashing the zip.

**Comment by jmingov** [comment]
Check the wiki, that rom is not supported...

https://github.com/offensive-security/kali-nethunter/wiki#10-supported-devices-and-roms

**Comment by CarlisleChan** [comment]
My fault...
Thanks.

**Comment by jmingov** [comment]
No problem, you welcome

**Comment by marianobilli** [comment]
I have the same problem but according to the supported devices the CM 13.0 is supported for the oneplus one. Maybe on Jan 7 it was not?

**Comment by binkybear** [comment]
Correct it is supported but the issue was with TWRP and symlinks.  The error first posted can be ignored.

**Comment by tatramaco** [comment]
I am getting exactly the same issue running cm13. I get the symlink errors and then the constant rebooting into TWRP.
I followed the Nethunter-LRT but there is only a fastboot version of CM13 available on cyngn.com so cannot try a 12.1 version. Any thoughts ?

**Comment by tatramaco** [comment]
I am getting exactly the same issue running cm13. I get the symlink errors and then the constant rebooting into TWRP.
I followed the Nethunter-LRT but there is only a fastboot version of CM13 available on cyngn.com so cannot try a 12.1 version. Any thoughts ?

**Comment by tatramaco** [comment]
I have figured this out. You need to build nethunter with the marshmallow rather than lollipop flag, push the new zip and install. Happy pwnage !

**Comment by VanasriJithendar** [comment]
Im getting the same errors what is the solution @tatramaco

**Comment by jcadduono** [comment]
the simplest solution is to just delete the chroot in the app and have the app download the new chroot :)

**Comment by khatwanir111** [comment]
http://www.wugfresh.com/brt/ Try this Bacon Root Toolkit and there is option called Flash Stock + Unroot and then it will ask which Build you wanna get back!! I have the same errors so i am getting back to stock 12.1 Cyanogen OS from this toolkit!! This toolkit is recommended by Kali Official Documentation

**Comment by joelthepirate** [comment]
Hey was just wondering what the locations of those symlinks are... I goofed thinking there was a rom baked into the zip for NetHunter. Now trying to install LineageOs, but it won't and I believe it has to do with requiring a clean flash. Thx in advance. =)

**Comment by jcadduono** [comment]
@joelthepirate you generally need to back up your important things to your PC and format data partition before moving to different roms

**Comment by verniyb** [comment]
> the simplest solution is to just delete the chroot in the app and have the app download the new chroot :)
> 
> if you are unable to boot, you likely flashed the wrong kernel. the errors you are seeing are just harmless warnings.

It also works on my Nexus 5, good!

**Comment by txreplay** [comment]
@verniyb @jmingov Got the same error with Nexus 5, Lineage 14.1 and nethunter-hammerhead-marshmallow-3.0 🤔Installation looks fine until I got back to twrp with those errors and infinite bootloop. Can I change chroot without having NetHunter already installed ?

**Comment by jcadduono** [comment]
@txreplay use https://build.nethunter.com/nightly/2019.03-13-0514/kernel-nethunter-hammerhead-marshmallow-2019.03-13-0514.zip and https://build.nethunter.com/nightly/2019.03-13-0514/nethunter-generic-armhf-kalifs-full-rolling-2019.03-13-0514.zip for now until a new official release happens
