### ISSUE TITLE
 Terminal error "1) no title" on Nexus 6p running 6.0.1 

### ISSUE THREAD

**Issue by slick97477** [offensive-security/kali-nethunter#333]
I am on a Nexus 6p, I have almost the same issue as issue#329. I am on Stock rooted (MMB29M)I have nethunter installed, the kernel is installed, Chroot installed properly. However when ever i try to run anything the terminal comes for a second then closes, but superuser grants permissions becuase they are flashing up and closing but can never get into anything. If i use something like Juice SSH i can turn on the ssh service and login via ssh and run wifite or other things. I previously was PureNexus Rom with Elemental X kernel and had the same behavior so i went completely back to stock after a complete wipe of the device, then followed the instructions to install stock and went through the whole process and still having the same issue. In the Aroma Installer log it says that some of the symlinks failed.
[update-nethunter-angler-marshmallow-712016_185349.zip.log.txt](https://github.com/offensive-security/kali-nethunter/files/82094/update-nethunter-angler-marshmallow-712016_185349.zip.log.txt)

I ran this "
adb shell
su
ls /system/bin/boot*"

This is the result from that:
/system/bin/bootanimation

Some more info upon searching i found the bootkali script /data/data/com/offsec.nethunter/files/scripts but i dont think that is where the install points to with the symlink

**Comment by jmingov** [comment]
Nethunter is not well installed for some "unknown reason", maybe @binkybear can give us some more hints, but think that your device is still unsupported, is in early alpha (we dont own this model to do the needed tests atm) 

But i see in the logs 2 bad things:

> mount: mounting XXXXXX on /XXXX failed: Device or resource busy
    run_program: child exited with status 255
and also

> rm: can't remove '/XXXXXXX': Read-only file system

**Comment by slick97477** [comment]
I noticed that too, which i dont understand why?  Superuser is there and present when i boot into the stock rom, it appears to be working, not real sure why it would be saying that

**Comment by jmingov** [comment]
Note,

https://github.com/offensive-security/nethunter-app/tree/master/assets/scripts

All these files should be there... things are not well flashed.

**Comment by slick97477** [comment]
The files are actually there. Just were not symlinked. The files were in a different directory than what the installer was looking for. At least that is what it looks like.However though i am just diving into nethunter. Have learned alot so far. And still learning.

**Comment by jmingov** [comment]
Just were not symlinked (only bootkali's should be).

The files were in a different directory than what the installer was looking for...Which directory?

**Comment by binkybear** [comment]
I've seen other reports of system not being written to with the Nexus 6P.  I'm unsure if its a mounting issue or some other reason.  I know you have to allow TWRP to write to system when you first start and  assume everyone is allowing that.

But this is not an isolated case of system write issues on the Nexus 6P.

**Comment by slick97477** [comment]
After manually symlinking those 3 files mentioned above, Nethunter seems to be working so far. It is launching the terminal,wifite and other things i have checked so far. I am currently installing some other stuff to it too, If you need any logs or anything let me know and will gladly get it on here.

**Comment by slick97477** [comment]
Most of Nethunter is functioning on my 6P, Here are some screenshots. There are some things not functioning as expected, I dont have the kali launcher in the main menu but can launch "kalimenu" from ssh and it loads and functions. Also have screenshots of the output"lspci" of the internal card of the 6p if needed. Wifite loads, reaver, and many others seem to be working so far.
![screenshot_20160108-164932](https://cloud.githubusercontent.com/assets/16583112/12214348/6bfbad94-b645-11e5-8ee2-fa004984ba37.png)
![screenshot_20160108-165857](https://cloud.githubusercontent.com/assets/16583112/12214349/6c021dc8-b645-11e5-9b1d-96f727307e17.png)

**Comment by slick97477** [comment]
The directories were in the right places as they should have been upon install, however for some reason when going through the aroma installer, the log file is in the OP They did not symlink properly. After i created the symlinks manually Nethunter has been working, however i did run into another issue though, I am unable to load firmware as others have been reporting but on the nexus 6p, there is no /system/etc/firmware/ folder. There is firmware located at /vendor/firmware/ though. I plan to copy the firmware needed into the vendor/firmware/ folder to see if that solves the problem. Sorry took so long to get back to this, My wife is 4 months pregnant so lots of things to get done and work too.

**Comment by nmggithub** [comment]
OK. I have found a solution. Flash NetHunter, boot, run the app, tap Chroot Manager. **Don't do anything here.** Tap home and open the terminal and choose Kali. It will ask for SU access. Allow it and it will now open the NetHunter app and configure a few things. Once done, tap home and go and reopen the terminal app. Choose Kali. You are done! :) It worked for me, hopefully it will for you.

**Comment by Subhesh7** [comment]
For 1) no title error pls follow the below steps
Required root explorer pro
a. BusyBox should be installed
b. symlink bootkali, bootkali_bash, bootkali_login in between /data/data/com.offsec.nethunter/files/scripts and /system/bin
lots of guides are there how to do it
c. Most important give Execute permission to above 3 files in the owner section..in simple term bootkali, bootkali_bash, bootkali_login should be rwx in /data/data/com.offsec.nethunter/files/scripts.

Hope this will solve no title error in terminal...enjoy
