### ISSUE TITLE
live wallpaper is not supported shows "app isn't installed"

### ISSUE THREAD

**Issue by TomasAndersonvoid** [offensive-security/kali-nethunter#334]
I am using rooted android 6.0.1 on nexus 6P, flashed nethunter kernel. When I am trying to use live wall paper, it shows "app isn't installed" I am not sure if it's kernel's problem any ideas?

**Comment by jmingov** [comment]
Priority: low, prety low

**Comment by 0xicl33n** [comment]
Same problem with nexus 9 (lollipop 5.1.1,  build LMY47X) with NH 3.0 and a kernel i built using the anykernel2 in this github

This only seems to be a problem with NH 3.x because the other day i had a live wallpaper working just fine in 2.0

**Comment by vay3t** [comment]
you could try to find a solution. the priority is low because of no relevance to the operation of nethunter (It's not important, therefore it is not considered bug)

**Comment by offensive-security** [comment]
What more, having live wallpapers working is not a design goal for NetHunter. We are unlikely to spend time and resources tracking this down.
