### ISSUE TITLE
(Nexus 6 Marshmallow) "HID Attacks" cannot output any strings.

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#336]
@jmingov @binkybear 
In the latest version, "HID Attacks" cannot output any strings except the key "Enter".
When executes attack, I can only see it outputs "Enter" for 2 times, and nothing else.

I tried to replace the old keyseed.py, and it's back to work for "HID Attack"again, but failed with "Duckhunter", and vice versa..
Any ideas?

**Comment by TheNain38** [comment]
I know what's happening, I changed the structure in keyseed.py, and "HID attacks" code wasn't updated to use new structure.

**Comment by simonpunk** [comment]
@TheNain38 Oh, I see~ So, I just wait for the next fix, Thank you very much.
By the way, are you still having problem with the macchager?

**Comment by jmingov** [comment]
@TheNain38 chages broke some of the HID functionality.

We are working on it.
