### ISSUE TITLE
Found phy0 with no interface assigned when running airmon-ng

### ISSUE THREAD

**Issue by grayburn** [offensive-security/kali-nethunter#340]
Running a Nexus 6 with Marshmallow 6.0.1. I setup the Nexus with a clean install of stock using the Linux Root Toolkit and nethunter 3.0. I manually build nethunter using the build scripts under the AnyKernel2 folder 

Whenever I run Wifite, it will just hang at "Scanning for wireless devices" and never progress further. Since Wifite uses airmon-ng, I tried to just launch the kali terminal and manually run "airmon-ng start wlan1". This is where I get the  "Found phy0 with no interface assigned" message and is probably the reason why Wifite is hanging. I've reset my Nexus 6 (reflash with stock) a couple times to rule out a bad install on my part, but I always get this message.

When I get the "Found phy0 with no interface assigned" message, it asks if I would like to assign one to it. If I input 'Y', then it will eventually create the wlan1mon interface. This is not a one time thing. If I pull the card and replug it back in, I still get the "Found phy0 with no interface assigned" message.

A workaround I do, I've created a custom command to start a monitor interface on wlan1 before running wifite. My command is this: "iw wlan1 set type monitor"

Also, I have a Nexus 7 2013, setup using the Linux Root Toolkit, but it doesn't have this issue. Wifite runs fine and airmon-ng can bring up the monitor interface without issues.

**Comment by binkybear** [comment]
I have updated kernel for Nexus 6 with some airmon-ng specific changes.  Let me know if it improves/fixes your issue.  You should just be able to flash kernel.

**Comment by grayburn** [comment]
Hello and thanks for the quick turnaround, I flashed the new kernel and re-tested but I am still seeing the problem with airmon-ng. Not sure if it helps but my uname -r out is 3.10.40-gfaff1dd-dirty

**Comment by JohnRyk** [comment]
I had the same problem...    Have you solved ??
