### ISSUE TITLE
Problems with ADB in Android 6.0.X

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#341]
I'm having problems with the debug mode. I have no RSA key in Nexus 5 and Nexus 7 (2013) wifi. on any operating system

kernel version n5: 3.4.0-gb7558f2 root(a)kali #2 android 6.0.1 MMB29S
kernel version n7: 3.4.0-g61f11d0-dirty root(a)kali #6 android 6.0.1 MMB290

**Comment by jmingov** [comment]
Hey @vay3t,

For ssome reason, (still unknown), when flashing the kernel/rooting/twrp the ADB is gone (only happening in 6.0.X android version)

This is confirmed (we also suffer it), but by now, you can:

a)   Check https://forums.kali.org/showthread.php?27579-Testers-Wanted-New-application-installation-(feedback)&p=53436&viewfull=1#post53436

b) Reinstall stock, add adb keys for the pc you will be using, then once they are added, root, TWRP and then install nethunter.

**Comment by vay3t** [comment]
i have a possible solution, it's not necessary the adb for doing the stock reset, we made an alternative solution to the RSA problem with your script, My friend @acidobinario and I modify the script so that the verification skips adb and the user have to be in fastboot mode. if you can, you can name the script "DesesperatedStockRestaurationNexus.sh", only it has been tested on Nexus 7.

https://github.com/acidobinario/nethunter-LRT/commit/1bca4faf1a2ac0791a16c23e1c7a523a06433b5e (sorry for the sense of humor of my argentinean friend)

**Comment by binkybear** [comment]
@vay3t -  I can confirm the problem exists/existed on Marshmallow in our early testing.  It's a bit silly, but for me switching cables seemed to fix the issue and also revoking authorizations.

**Comment by H8to** [comment]
@vay3t Thanks for reporting this issue.

@all Any news on a workaround for Marshmallow that one can apply via terminal?
Reflashing everything is not an option. :/

**Comment by vay3t** [comment]
adb_key not found 
![screenshot_20160607-120833-02](https://cloud.githubusercontent.com/assets/6080369/15865623/8032ea7c-2ca9-11e6-8e61-088ae89daa68.jpeg)

**Comment by vay3t** [comment]
possible in the installation of nethunter (when it is TWRP) generate a adb for android 6?

**Comment by mpkosewski** [comment]
@H8to worked like a charm for one of my nexus devices! Copied over nexus 7's adbkey to my second nexus 5 and it got it out of that damn aunuthorized state in adb. 

My first nexus 5 seemed to have fixed itself and the RSA fingerprint prompt finally came up after several hours of being off. Ok, now lets try this again....

**Comment by jcadduono** [comment]
I think this might be due to some devices interaction with ro.secure prop, if built in release mode and you switch that to off it has some unintended consequences probably because ro.secure=0 on a release build isn't something aosp/Google devs are testing.
It might be a good idea to also remove that change from the installer?  @binkybear
I added ro.secure=1 to axon 7 kernel installer to fix USB issues as well.

**Comment by binkybear** [comment]
Yes I belive that:
```bash
ro.secure=1
```
will fix issue.
I previously only changed adb.secure: https://github.com/offensive-security/kali-nethunter/commit/cc96a68abda8e0e4977d252b99b7acb0a9b28977 but I think ro.secure should probably also be changed.

**Comment by dimpol** [comment]
Can we perform H8to's workaround with genymotion? I don't have a spare Android device...
