### ISSUE TITLE
Nexus 9: TL-WN722N does not work

### ISSUE THREAD

**Issue by 0xicl33n** [offensive-security/kali-nethunter#342]
Similar to https://github.com/offensive-security/kali-nethunter/issues/298, i cant get my TP to work on my N9 running 5.1.1 build LMY47K.

By doing some googlefu i was able to find i should just be able to `apt-get install firmware-atheros` and solve ths problem, but it didnt work.

	[ 1537.414647] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
	[ 1537.414672] usb usb3: Product: Tegra EHCI Host Controller
	[ 1537.414695] usb usb3: Manufacturer: Linux 3.10.40-g108581f-dirty ehci_hcd
	[ 1537.414719] usb usb3: SerialNumber: tegra-ehci.0
	[ 1537.419401] hub 3-0:1.0: USB hub found
	[ 1537.419471] hub 3-0:1.0: 1 port detected
	[ 1537.734383] usb 3-1: new high-speed USB device number 2 using tegra-ehci
	[ 1537.908641] usb 3-1: New USB device found, idVendor=0cf3, idProduct=9271
	[ 1537.908694] usb 3-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
	[ 1537.908731] usb 3-1: Product: USB2.0 WLAN
	[ 1537.908758] usb 3-1: Manufacturer: ATHEROS
	[ 1537.908784] usb 3-1: SerialNumber: 12345
	[ 1537.913541] usb 3-1: ath9k_htc: Firmware htc_9271.fw requested
	[ 1537.928436] usb 3-1: ath9k_htc: Failed to get firmware htc_9271.fw
	[ 1537.929301] usb 3-1: ath9k_htc: USB layer deinitialized
	[root@utukku2[~]$ls -l /lib/firmware/
	total 832
	drwxr-xr-x. 2 root root   4096 Jan 12 21:31 ar3k/
	-rw-r--r--. 1 root root 153416 Jul 29 15:52 ar5523.bin
	-rw-r--r--. 1 root root  70624 Jul 29 15:52 ar7010_1_1.fw
	-rw-r--r--. 1 root root  70624 Jul 29 15:52 ar7010.fw
	-rw-r--r--. 1 root root  15944 Jul 29 15:52 ar9170.fw
	-rw-r--r--. 1 root root  51312 Jul 29 15:52 ar9271.fw
	drwxr-xr-x. 4 root root   4096 Jan 12 21:31 ath10k/
	-rw-r--r--. 1 root root 246804 Jul 29 15:52 ath3k-1.fw
	drwxr-xr-x. 5 root root   4096 Jan 12 21:31 ath6k/
	-rw-r--r--. 1 root root  72684 Jul 29 15:52 htc_7010.fw
	-rw-r--r--. 1 root root  50980 Jul 29 15:52 htc_9271.fw
	[root@utukku2[~]$modprobe htc_9271
	modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.40-g108581f-dirty/modules.dep.bin'
	[root@utukku2[~]$depmod
	depmod: ERROR: could not open directory /lib/modules/3.10.40-g108581f-dirty: No such file or directory
	depmod: FATAL: could not search modules: No such file or directory

I can confirm my Alfa AWUS036H works perfectly however

**Comment by binkybear** [comment]
@0xicl33n - Can you check outside chroot in /system/etc/firmware.  The obvious error is: 

ath9k_htc: Failed to get firmware htc_9271.fw.

However, using apt-get install will install firmware to chroot but it won't help you because networking system is provided by android.  So it looks for firmware in /system/etc/firmware.

**Comment by 0xicl33n** [comment]
tmp-mksh: cd: /system/etc/firmware: No such file or directory

**Comment by jmingov** [comment]
So nice!

**Comment by 0xicl33n** [comment]
Android gave me many problems while doing this because originally i wanted to use `scp` or `rsync` from the chroot to make my life easier, i ended up making a tar.gz and dumping it on google drive before adb pushing it to the `/sdcard/Download` folder. I wanted to use adb to push it, but i couldnt get adb to mount `/system` as rw, so i used root explorer which, which is an app on the play store to move the files when i had the tar on my nexus

**Comment by st213497** [comment]
Hi,
Thank you guys for your effort. I am trying to solve this issue in my nexus 10 but I can't reach the drivers.
Where can I find the drivers?
Where chroot is located in the file system?

**Comment by binkybear** [comment]
Chroot: /data/local/nhsystem/kali-armhf
Firmware: /system/etc/firmware

@st213497 - If you are having issues also double check your logcat to see if it says anything about missing firmware for your device.

**Comment by st213497** [comment]
Strange enough, this I have three external usb wifi cards that works out of the box on nethunter 3.0 on nexus 10 running 5.1.1
However, I was trying each on wifite which didn't work and dove me to buy the next. After trying them all and failed, I successed by the following steps:
1: airmon-ng check kill
2: airmon-ng start wlan1
3: airodump-ng wlan1mon
....

Although dmesg shows error messages for cards that has Atheros ship, they worked with the "-ng" software family. I can confirm that the issue is with wifite. Also, when I run wifite the driver column shows question marks.

@binkybear

**Comment by m2dragon** [comment]
@0xicl33n When you copied the firmware from the chroot in what folder did you place it at?

**Comment by st213497** [comment]
@m2dragon 
I copied them to /system/etc/firmware
etc and firmware were not existing so I created them. In addition, I changed the permissions of all the files and folders to 777 in attempt to make wifite recognizes them but had no luck. 

To reproduce everything, I re-installed nethunter and run "-ng" tools and all worked fine without any firmware addition.

**Comment by st213497** [comment]
@0xicl33n please read the comment above as I mentioned m2dragon instead of you by mistake

**Comment by 0xicl33n** [comment]
@st213497 i solved the problem already lol like 2 months ago

**Comment by brockyakharai** [comment]
Hey anybody solved that wireless adaptor doesnt reconized by kali nethunter device???

**Comment by brockyakharai** [comment]
HeyOxicl33n how did you solved it please tell me in detail...

**Comment by belerweb** [comment]
@brockyakharai 
I got the same issue. After read this issue and do many times try, I solved it. The steps are below, hope it help you.

step 1: install driver in kali root terminal, if use atheros chipset, execute ``` apt-get install firmware-atheros ```, or if realtek ``` apt-get install firmware-realtek ```. When finished, you will have drivers in /lib/firmware

step 2: copy /lib/firmware to /sdcard, the command is ``` cp -r /lib/firmware /sdcard ```.  This command must execute in kali root terminal.

step 3: remote /system writeable, the command is ``` mount -o remount,rw /system ```. This command must execute in android su terminal.

step 4: copy firmware to system by command ``` cp -r /sdcard/firmware /system/etc```. This command must execute in android su terminal.

step 5: reboot device and replug in you use wifi. You can find wlan1 by command ``` iwconfig ```.

**Comment by c4rp3nt3r** [comment]
@0xicl33n @belerweb 
hello everyone, I have the same problem on my Nexus 9 + TL-WN722N and running 5.1.1 build LMY47X and Nethunter 3.0 . 

I have done the four steps what @belerweb said, but It still not work!
should I buy a Alfa AWUS036H ?
or does anyone know how to download the old version of kali nethunter (such as nethunter 2.0)?
please help me! thank you!!!

```
root@kali:/system/etc/firmware# ls -l
total 744
drwxr--r--. 2 root root   4096 Dec 18 15:21 ar3k
-rwxr--r--. 1 root root 153416 Dec 18 15:21 ar5523.bin
-rwxr--r--. 1 root root  70624 Dec 18 15:21 ar7010_1_1.fw
-rwxr--r--. 1 root root  70624 Dec 18 15:21 ar7010.fw
-rwxr--r--. 1 root root  15944 Dec 18 15:21 ar9170.fw
-rwxr--r--. 1 root root  51312 Dec 18 15:21 ar9271.fw
drwxr--r--. 4 root root   4096 Dec 18 15:21 ath10k
-rwxr--r--. 1 root root 246804 Dec 18 15:21 ath3k-1.fw
drwxr--r--. 5 root root   4096 Dec 18 15:21 ath6k
-rwxr--r--. 1 root root  72684 Dec 18 15:21 htc_7010.fw
-rwxr--r--. 1 root root  50980 Dec 18 15:21 htc_9271.fw

root@kali:~# lsusb
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Function not implemented
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:~# dmesg
......
[  765.967574] tegra-ehci tegra-ehci.0: irq 52, io mem 0x7d000000
[  765.982563] tegra-ehci tegra-ehci.0: USB 2.0 started, EHCI 1.10
[  765.982744] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002
[  765.982775] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  765.982799] usb usb3: Product: Tegra EHCI Host Controller
[  765.982820] usb usb3: Manufacturer: Linux 3.10.40-gbb66a39 ehci_hcd
[  765.982841] usb usb3: SerialNumber: tegra-ehci.0
[  765.989176] hub 3-0:1.0: USB hub found
[  765.989245] hub 3-0:1.0: 1 port detected
[  766.302583] usb 3-1: new high-speed USB device number 2 using tegra-ehci
[  766.477285] usb 3-1: New USB device found, idVendor=0cf3, idProduct=9271
[  766.477331] usb 3-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[  766.477359] usb 3-1: Product: USB2.0 WLAN
[  766.477383] usb 3-1: Manufacturer: ATHEROS
[  766.477406] usb 3-1: SerialNumber: 12345
!!!!but there is no "ath9k_htc..."
...
root@kali:/system/etc/firmware# modprobe htc_9271
modprobe htc_9271
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.40-gbb66a39/modules.dep.bin'

root@kali:/system/etc/firmware# uname -an
Linux kali 3.10.40-gbb66a39 #1 SMP PREEMPT Thu Apr 9 18:20:48 UTC 2015 aarch64 GNU/Linux


```

**Comment by akrolla** [comment]
Make sure your kernel supports packet injection not all kernels can .

what's the output of cat /proc/version

**Comment by c4rp3nt3r** [comment]
@akrolla 
```
root@kali:/system/etc/firmware# uname -an
Linux kali 3.10.40-gbb66a39 #1 SMP PREEMPT Thu Apr 9 18:20:48 UTC 2015 aarch64 GNU/Linux
```

**Comment by c4rp3nt3r** [comment]
@0xicl33n @binkybear @st213497 @akrolla 

Does any one have the `Kali NetHunter 2.0` download url ?

Thank you!

**Comment by c4rp3nt3r** [comment]
I found a 2.0 download url http://images.kali.org/kali_linux_nethunter_2.0_volantisg_lollipop.zip
but it's dead !

**Comment by akrolla** [comment]
Check out the wiki there should be s link there.

**Comment by Himura2la** [comment]
I'm stuck with my devices and was surprised they actually solve the issue here... I have Nexus 7 2013 and TL-WN727N v4 based on MT7601U.

```
299.764129] wlan: [1060:E :SME] csrMoveTempScanResultsToMainList: 2908: 11d AP Bssid ec:43:f6:d2:8c:ea chan= 11, rssi = -66, countryCode RU
[  299.764282] wlan: [1060:E :SME] csrMoveTempScanResultsToMainList: 2908: 11d AP Bssid 28:28:5d:e8:a1:04 chan= 2, rssi = -42, countryCode RU
[  299.764404] wlan: [1060:E :SME] csrMoveTempScanResultsToMainList: 2928: Information about current country Bssid 28:28:5d:e8:a1:04 chan= 2, rssi = -42, countryCode RU
[  301.017944] id_pin_irq_work_function: gpio_get_value(APQ_OTG_ID_PIN) = 0
[  301.017944] id_pin_irq_work_function: APQ_OTG_ID_PIN is low : Host mode
[  301.018066] msm_otg msm_otg: OTG runtime resume
[  301.020172] reg (HPM)
[  301.020202] msm_hsusb_config_vddcx: min_vol:1045000 max_vol:1320000
[  301.020202] msm_otg msm_otg: USB exited from low power mode
[  301.020294] b_idle work
[  301.020324] !id || id_A
[  301.020324] a_idle work
[  301.020324] !a_bus_drop && (a_srp_det || a_bus_req)
[  301.032348] vbus_otg is NULL.
[  301.032470] starting a_wait_vrise timer
[  301.132537] expired a_wait_vrise timer
[  301.132598] a_wait_vrise work
[  301.132598] a_vbus_vld
[  301.132598] msm_otg msm_otg: host on
[  301.132598] smb345_charger: [smb345_otg_status] otg function: on
[  301.133789] msm_otg msm_otg: phy_reset: success
[  301.138885] smb345_charger: [smb345_inok_isr] VBUS_DET = L
[  301.237915] Host mode: Set DC level as 0x68 for flo.
[  301.238037] msm_hsusb_host msm_hsusb_host: Qualcomm On-Chip EHCI Host Controller
[  301.238311] SELinux: initialized (dev usbfs, type usbfs), uses genfs_contexts
[  301.238372] msm_hsusb_host msm_hsusb_host: new USB bus registered, assigned bus number 1
[  301.267944] msm_hsusb_host msm_hsusb_host: irq 132, io mem 0x12500000
[  301.287933] msm_hsusb_host msm_hsusb_host: USB 2.0 started, EHCI 1.00
[  301.288146] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[  301.288238] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[  301.288299] usb usb1: Product: Qualcomm On-Chip EHCI Host Controller
[  301.288421] usb usb1: Manufacturer: Linux 3.4.0-gcc51ee3-dirty ehci_hcd
[  301.288482] usb usb1: SerialNumber: msm_hsusb_host
[  301.289337] hub 1-0:1.0: USB hub found
[  301.289398] hub 1-0:1.0: 1 port detected
[  301.542999] portsc = 88001205
[  301.607971] usb 1-1: new high-speed USB device number 2 using msm_hsusb_host
[  301.663421] portsc = 88001205
[  301.737915] notifying plugin
[  301.779388] usb 1-1: New USB device found, idVendor=148f, idProduct=7601
[  301.779510] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  301.779571] usb 1-1: Product: 802.11 n WLAN
[  301.779663] usb 1-1: Manufacturer: MediaTek
[  301.779724] usb 1-1: SerialNumber: 1.0
[  301.781280] B_CONN set
[  301.781311] deleting a_wait_vrise timer. remaining -648 msec
[  306.917938] type=1400 audit(1509435566.256:624): avc: denied { module_request } for pid=7189 comm="su" kmod="personality-8" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=system permissive=0
```

some more info

```
root@kali:/# iwconfig
rev_rmnet1  no wireless extensions.

rmnet6    no wireless extensions.

rev_rmnet5  no wireless extensions.

rmnet1    no wireless extensions.

lo        no wireless extensions.

rev_rmnet0  no wireless extensions.

rmnet5    no wireless extensions.

rev_rmnet4  no wireless extensions.

rmnet0    no wireless extensions.

rev_rmnet8  no wireless extensions.

rmnet4    no wireless extensions.

sit0      no wireless extensions.

dummy0    no wireless extensions.

rev_rmnet3  no wireless extensions.

wlan0     Qcom:802.11n  ESSID:"Solar-Eye"  Nickname:""
          Mode:Managed  Frequency:2.417 GHz  Access Point: 28:28:5D:E8:A1:04
          Bit Rate=72 Mb/s   Tx-Power=16 dBm
          RTS thr=2347 B   Fragment thr=8000 B
          Encryption key:9E9D-5EA2-4E0A-000D-DE5B-B651-0C3E-B6A9 [2]   Security mode:restricted

rev_rmnet7  no wireless extensions.

rmnet3    no wireless extensions.

rev_rmnet2  no wireless extensions.

rmnet7    no wireless extensions.

rev_rmnet6  no wireless extensions.

rmnet2    no wireless extensions.

p2p0      Qcom:802.11n  ESSID:off/any  Nickname:""
          Mode:Managed  Channel:0  Access Point: Not-Associated
          Bit Rate:0 kb/s   Tx-Power=0 dBm
          RTS thr=2347 B   Fragment thr=8000 B
          Encryption key:off

rmnet_smux0  no wireless extensions.

root@kali:/# lsusb
Bus 001 Device 002: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

I installed the drivers and copied them to Android, but that didn't help

```
root@flo:/storage/emulated/0 # ls -l /etc/firmware/
drwx------ root     root              2017-10-31 10:33 3com
drwx------ root     root              2017-10-31 10:33 advansys
-rw------- root     root        50698 2017-10-31 10:33 agere_ap_fw.bin
-rw------- root     root        65046 2017-10-31 10:33 agere_sta_fw.bin
-rw-r--r-- root     root        83968 2017-10-06 23:53 ar9170-1.fw
-rw-r--r-- root     root         3508 2017-10-06 23:53 ar9170-2.fw
-rw------- root     root        95500 2017-10-31 10:33 as102_data1_st.hex
-rw------- root     root        81820 2017-10-31 10:33 as102_data2_st.hex
-rw-r--r-- root     root        13424 2017-10-06 23:53 carl9170-1.fw
-rw------- root     root       655436 2017-10-31 10:33 ctefx.bin
-rw------- root     root         4120 2017-10-31 10:33 ctspeq.bin
drwx------ root     root              2017-10-31 10:33 cxgb3
drwx------ root     root              2017-10-31 10:33 cxgb4
drwx------ root     root              2017-10-31 10:33 dabusb
-rw------- root     root        18643 2017-10-31 10:33 dvb-fe-xc4000-1.4.1.fw
-rw------- root     root        12401 2017-10-31 10:33 dvb-fe-xc5000-1.6.114.fw
-rw------- root     root        16497 2017-10-31 10:33 dvb-fe-xc5000c-4.1.30.7.fw
-rw------- root     root        33768 2017-10-31 10:33 dvb-usb-dib0700-1.20.fw
-rw------- root     root         8128 2017-10-31 10:33 dvb-usb-it9135-01.fw
-rw------- root     root         5834 2017-10-31 10:33 dvb-usb-it9135-02.fw
-rw------- root     root        50222 2017-10-31 10:33 dvb-usb-terratec-h5-drxk.fw
drwx------ root     root              2017-10-31 10:33 e100
drwx------ root     root              2017-10-31 10:33 ene-ub6250
-rw------- root     root       180776 2017-10-31 10:33 f2255usb.bin
drwx------ root     root              2017-10-31 10:33 go7007
-rw------- root     root        32252 2017-10-31 10:33 hfi1_dc8051.fw
-rw------- root     root        16848 2017-10-31 10:33 hfi1_fabric.fw
-rw------- root     root        33296 2017-10-31 10:33 hfi1_pcie.fw
-rw------- root     root         5360 2017-10-31 10:33 hfi1_sbus.fw
-rw-r--r-- root     root        72992 2017-10-06 23:53 htc_7010.fw
-rw-r--r-- root     root        51272 2017-10-06 23:53 htc_9271.fw
drwx------ root     root              2017-10-31 10:33 i915
drwx------ root     root              2017-10-31 10:33 kaweth
drwx------ root     root              2017-10-31 10:33 matrox
drwx------ root     root              2017-10-31 10:33 moxa
-rw------- root     root        45412 2017-10-31 10:33 mt7601u.bin
-rw------- root     root       368220 2017-10-31 10:33 mt7650.bin
-rw------- root     root        81908 2017-10-31 10:33 mt7662.bin
-rw------- root     root        26350 2017-10-31 10:33 mt7662_rom_patch.bin
-rw------- root     root        13847 2017-10-31 10:33 mts_cdma.fw
-rw------- root     root        14067 2017-10-31 10:33 mts_edge.fw
-rw------- root     root        13847 2017-10-31 10:33 mts_gsm.fw
drwx------ root     root              2017-10-31 10:33 nvidia
-rw------- root     root       463612 2017-10-31 10:33 qat_895xcc.bin
-rw------- root     root       114176 2017-10-31 10:33 qat_895xcc_mmp.bin
-rw------- root     root       265444 2017-10-31 10:33 qat_c3xxx.bin
-rw------- root     root       114820 2017-10-31 10:33 qat_c3xxx_mmp.bin
-rw------- root     root       398144 2017-10-31 10:33 qat_c62x.bin
-rw------- root     root       114820 2017-10-31 10:33 qat_c62x_mmp.bin
-rw------- root     root           63 2017-10-31 10:33 rp2.fw
-rw-r--r-- root     root         8192 2017-10-31 10:33 rt2561.bin
-rw------- root     root         8192 2017-10-31 10:33 rt2561s.bin
-rw------- root     root         8192 2017-10-31 10:33 rt2661.bin
-rw-r--r-- root     root         8192 2017-10-31 10:33 rt2860.bin
-rw-r--r-- root     root         8192 2017-10-31 10:33 rt2870.bin
-rw-r--r-- root     root         4096 2017-10-06 23:53 rt3070.bin
-rw------- root     root         4096 2017-10-31 10:33 rt3071.bin
-rw------- root     root         4096 2017-10-31 10:33 rt3290.bin
-rw-r--r-- root     root         2048 2017-10-31 10:33 rt73.bin
drwxrwxrwx root     root              2017-10-06 23:53 rtlwifi
drwx------ root     root              2017-10-31 10:33 tehuti
drwx------ root     root              2017-10-31 10:33 tigon
lrw-r--r-- root     root              2009-01-01 11:00 tzapps.b00 -> /system/vendor/firmware/tzapps.b00
lrw-r--r-- root     root              2009-01-01 11:00 tzapps.b01 -> /system/vendor/firmware/tzapps.b01
lrw-r--r-- root     root              2009-01-01 11:00 tzapps.b02 -> /system/vendor/firmware/tzapps.b02
lrw-r--r-- root     root              2009-01-01 11:00 tzapps.b03 -> /system/vendor/firmware/tzapps.b03
lrw-r--r-- root     root              2009-01-01 11:00 tzapps.mdt -> /system/vendor/firmware/tzapps.mdt
drwx------ root     root              2017-10-31 10:33 ueagle-atm
-rw------- root     root        16382 2017-10-31 10:33 v4l-cx231xx-avcore-01.fw
-rw------- root     root       141200 2017-10-31 10:33 v4l-cx23418-apu.fw
-rw------- root     root       158332 2017-10-31 10:33 v4l-cx23418-cpu.fw
-rw------- root     root        16382 2017-10-31 10:33 v4l-cx23418-dig.fw
-rw------- root     root        16382 2017-10-31 10:33 v4l-cx23885-avcore-01.fw
-rw------- root     root        16382 2017-10-31 10:33 v4l-cx25840.fw
-rw-r--r-- root     root          212 2009-01-01 11:00 vidc.b00
-rw-r--r-- root     root         6540 2009-01-01 11:00 vidc.b01
-rw-r--r-- root     root       573440 2009-01-01 11:00 vidc.b02
-rw-r--r-- root     root        36864 2009-01-01 11:00 vidc.b03
-rw-r--r-- root     root         6752 2009-01-01 11:00 vidc.mdt
-rw-r--r-- root     root       605396 2009-01-01 11:00 vidc_1080p.fw
-rw-r--r-- root     root       610686 2009-01-01 11:00 vidcfw.elf
-rw------- root     root        11341 2017-10-31 10:33 vntwusb.fw
drwxr-xr-x root     root              2009-01-01 11:00 wcd9310
drwxrwxrwx root     root              2017-10-06 23:53 zd1211
root@flo:/storage/emulated/0 #
```

**mt7601u** is the required driver I suppose

**Comment by sezusatish** [comment]
hi  
i am using Device : Nexus 7 2013 (flo) WIFI (cm13)
 i try to building own nethunter base on this linke
https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter
Including the kernel full
using this commend :
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d flocm -m -su --rootfs full
 and able to make zip file and installed and all is working good
but external wifi  card TP-Link WN722N v1 is detected by NetHunter and working good for  max 120 min  only if I put device in sleep mode, next time onwards external WiFi  card is  not detected i am using the same card in kali os and i working good even i tryed with alfa card also use otg pen driver and mouse also working good , i tryed to check in lsusb it now shown or iwconfig not able to see any attached  max people are having issues, can any one  assist to find any solutions is it kernel issues or this nexus device is not support for external wifi card I check /etc/system/firmware having dump of firmware
