### ISSUE TITLE
Kali boot splash size is off on Nexus 6

### ISSUE THREAD

**Issue by Nekroze** [offensive-security/kali-nethunter#344]
It is not a functionality issue at all so my appologies but it is a tad unsightly.

The Kali boot splash offered in the Nethunter 3 installation does not fit the screen and has large black bars on all sides on Nexus 6 (shamu).

I suspect this might also occur on the other larger Nexus devices as well.

**Comment by binkybear** [comment]
Duplicate of https://github.com/offensive-security/kali-nethunter/issues/271

Known issue.  Closing to keep other one.

**Comment by Nekroze** [comment]
My apologies, must have missed that one.
