### ISSUE TITLE
Have no idea whats happening -_-

### ISSUE THREAD

**Issue by lavanoid** [offensive-security/kali-nethunter#345]
I'm trying to port nethunter to my htc one m7 but I have no idea what's happening.

I followed this tutorial: https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter  and used the following commands:

git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7 toolchain
export ARCH=arm
export SUBARCH=arm
export CROSS_COMPILE=`pwd`/toolchain/bin/arm-eabi-

After doing so, I downloaded the kernel for my device (HTC One M7 GPE, Android 5.1) from HTC Dev: http://dl4.htc.com/RomCode/Source_and_Binaries/m7ulstockui-3.4.10-ge0627be.zip  and extracted the archives inside.

I then continued onto this part of the wiki: https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel  but it errors out.

This is my terminal output (I'd make the output look nicer in the comment but I don't know how :/):

lavanoid@lavanoid-Aspire-E5-571:~/Downloads/htcone/kernel$ make menuconfig
 *** Unable to find the ncurses libraries or the
 *** required header files.
 *** 'make menuconfig' requires the ncurses libraries.
 *** 
 *** Install ncurses (ncurses-devel) and try again.
 *** 
/home/lavanoid/Downloads/htcone/kernel/scripts/kconfig/Makefile:190: recipe for target 'scripts/kconfig/dochecklxdialog' failed
make[1]: *** [scripts/kconfig/dochecklxdialog] Error 1
Makefile:498: recipe for target 'menuconfig' failed
make: *** [menuconfig] Error 2
lavanoid@lavanoid-Aspire-E5-571:~/Downloads/htcone/kernel$ sudo apt-get install http://dl4.htc.com/RomCode/Source_and_Binaries/m7ulstockui-3.4.10-ge0627be.zip
[sudo] password for lavanoid: 
lavanoid@lavanoid-Aspire-E5-571:~/Downloads/htcone/kernel$ sudo apt-get install ncurses-devel
[sudo] password for lavanoid: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ncurses-devel
lavanoid@lavanoid-Aspire-E5-571:~/Downloads/htcone/kernel$ 

Any help would be appreciated. Thanks.

**Comment by lavanoid** [comment]
Got the menuconfig working, yay.

New problem is that during the compilation process, it fails.

`
  CC      drivers/video/msm/mdp_dma_tv.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/bcmevent.o
  CC      drivers/video/msm/msm_dss_io_8960.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/wl_android.o
drivers/usb/gadget/android.c:2114:36: warning: 'hid_function' defined but not used [-Wunused-variable]
error, forbidden warning: android.c:2114
scripts/Makefile.build:307: recipe for target 'drivers/usb/gadget/android.o' failed
make[3]: *** [drivers/usb/gadget/android.o] Error 1
scripts/Makefile.build:443: recipe for target 'drivers/usb/gadget' failed
make[2]: *** [drivers/usb/gadget] Error 2
scripts/Makefile.build:443: recipe for target 'drivers/usb' failed
make[1]: *** [drivers/usb] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      drivers/net/wireless/bcmdhd_4335_mcc/wldev_common.o
  CC      drivers/net/wireless/rtl818x/rtl8187/rtl8225.o
  CC      drivers/video/msm/lvds.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/wl_linux_mon.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/wl_cfg80211.o
  CC      drivers/video/msm/mipi_dsi.o
  CC      drivers/net/wireless/rtl818x/rtl8187/leds.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/wl_cfgp2p.o
  CC      drivers/net/wireless/rtl818x/rtl8187/rfkill.o
  CC      drivers/video/msm/mipi_dsi_host.o
  LD      drivers/net/wireless/rtl818x/rtl8187/rtl8187.o
  LD      drivers/net/wireless/rtl818x/rtl8187/built-in.o
  LD      drivers/net/wireless/rtl818x/built-in.o
  CC      drivers/net/wireless/rndis_wlan.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/dhd_cfg80211.o
  CC      drivers/video/msm/mipi_toshiba.o
  CC      drivers/video/msm/mipi_novatek.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/dhd_wlfc.o
  CC [M]  drivers/net/wireless/at76c50x-usb.o
  CC      drivers/video/msm/mipi_orise.o
  CC      drivers/video/msm/mipi_renesas.o
  CC      drivers/video/msm/mipi_truly.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/dhd_ip.o
  CC      drivers/video/msm/mipi_NT35510.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/dhd_pno.o
  CC [M]  drivers/net/wireless/zd1201.o
  CC      drivers/video/msm/mipi_simulator.o
  CC      drivers/video/msm/mipi_tc358764_dsi2lvds.o
  CC      drivers/video/msm/msm_fb_panel.o
drivers/net/wireless/zd1201.c: In function 'zd1201_get_freq':
drivers/net/wireless/zd1201.c:940:10: warning: 'channel' may be used uninitialized in this function [-Wmaybe-uninitialized]
error, forbidden warning: zd1201.c:940
scripts/Makefile.build:313: recipe for target 'drivers/net/wireless/zd1201.o' failed
make[3]: *** [drivers/net/wireless/zd1201.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      drivers/video/msm/mipi_toshiba_video_wvga_pt.o
  CC      drivers/net/wireless/bcmdhd_4335_mcc/wl_iw.o
  CC      drivers/video/msm/mipi_toshiba_video_wsvga_pt.o
  CC      drivers/video/msm/mipi_toshiba_video_wuxga.o
  CC      drivers/video/msm/mipi_novatek_video_qhd_pt.o
  CC      drivers/video/msm/mipi_orise_video_720p_pt.o
  CC      drivers/video/msm/mipi_orise_cmd_720p_pt.o
  CC      drivers/video/msm/mipi_novatek_cmd_qhd_pt.o
  CC      drivers/video/msm/mipi_renesas_video_fwvga_pt.o
  CC      drivers/video/msm/mipi_renesas_cmd_fwvga_pt.o
  CC      drivers/video/msm/mipi_truly_video_wvga_pt.o
  CC      drivers/video/msm/mipi_NT35510_cmd_wvga_pt.o
  CC      drivers/video/msm/mipi_NT35510_video_wvga_pt.o
  CC      drivers/video/msm/mipi_simulator_video.o
  CC      drivers/video/msm/mipi_chimei_wxga_pt.o
  CC      drivers/video/msm/mipi_chimei_wuxga.o
  CC      drivers/video/msm/lvds_chimei_wxga.o
  LD      drivers/video/omap2/displays/built-in.o
  LD      drivers/video/omap2/built-in.o
  CC      drivers/video/cfbfillrect.o
  CC      drivers/video/cfbcopyarea.o
  LD      drivers/net/wireless/bcmdhd_4335_mcc/bcmdhd.o
  LD      drivers/net/wireless/bcmdhd_4335_mcc/built-in.o
scripts/Makefile.build:443: recipe for target 'drivers/net/wireless' failed
make[2]: *** [drivers/net/wireless] Error 2
scripts/Makefile.build:443: recipe for target 'drivers/net' failed
make[1]: *** [drivers/net] Error 2
  CC      drivers/video/cfbimgblt.o
  CC      drivers/video/msm/lvds_frc_fhd.o
  CC      drivers/video/msm/hdmi_msm.o
  CC      drivers/video/sysfillrect.o
  CC      drivers/video/syscopyarea.o
  CC      drivers/video/msm/external_common.o
  CC      drivers/video/sysimgblt.o
  CC      drivers/video/fb_sys_fops.o
  CC      drivers/video/vfb.o
  CC      drivers/video/minifb.o
  CC      drivers/video/msm/mdp4_wfd_writeback_panel.o
  LD      drivers/video/fb.o
  CC      drivers/video/msm/mdp4_wfd_writeback.o
  CC      drivers/video/msm/mdp4_overlay_writeback.o
  CC      drivers/video/msm/sii9234/sii9234.o
  CC      drivers/video/msm/vidc/common/init/vidc_init.o
  LD      drivers/video/msm/msm_mipi.o
  CC      drivers/video/msm/sii9234/i2c_master_sw.o
  CC      drivers/video/msm/sii9234/TPI.o
  CC      drivers/video/msm/sii9234/TPI_Access.o
  CC      drivers/video/msm/sii9234/Util.o
  CC      drivers/video/msm/vidc/common/vcd/vcd_api.o
  CC      drivers/video/msm/sii9234/sii_mhltx.o
  CC      drivers/video/msm/sii9234/mhltx_rcptable.o
  CC      drivers/video/msm/vidc/common/vcd/vcd_power_sm.o
  CC      drivers/video/msm/vidc/common/vcd/vcd_client_sm.o
  LD      drivers/video/msm/sii9234/built-in.o
  CC      drivers/video/msm/vidc/common/vcd/vcd_device_sm.o
  CC      drivers/video/msm/vidc/common/vcd/vcd_scheduler.o
  CC      drivers/video/msm/vidc/common/vcd/vcd_sub.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_helper.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_utils.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_interrupt_handler.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_properties.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_errors.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_shared_mem.o
  CC      drivers/video/msm/vidc/1080p/ddl/vidc.o
  CC      drivers/video/msm/vidc/1080p/ddl/vidc_pix_cache.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_vidc.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl.o
  CC      drivers/video/msm/vidc/1080p/ddl/vcd_ddl_metadata.o
  CC      drivers/video/msm/vidc/1080p/resource_tracker/vcd_res_tracker.o
  CC      drivers/video/msm/vidc/common/dec/vdec.o
  CC      drivers/video/msm/vidc/common/enc/venc.o
  CC      drivers/video/msm/vidc/common/enc/venc_internal.o
  LD      drivers/video/msm/vidc/vidc.o
  LD      drivers/video/msm/vidc/vidc_vdec.o
  LD      drivers/video/msm/vidc/vidc_venc.o
  LD      drivers/video/msm/vidc/built-in.o
  LD      drivers/video/msm/built-in.o
  LD      drivers/video/built-in.o
Makefile:951: recipe for target 'drivers' failed
make: *** [drivers] Error 2
lavanoid@lavanoid-Aspire-E5-571:~/Downloads/htcone/kernel$ 

`

**Comment by binkybear** [comment]
Looks like the hid patch you used is encountering an error.  Also you may want to disable zd1201.  This isn't really a place for help, just issues.  Feel free to email me instead at binkybear@nethunter.com
