### ISSUE TITLE
(Nexus 6 Marshmallow) Dumpmifare not found

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#347]
There should be missing the dumpmifare file in /system/bin...
And I think it is supposed to point to dumpmifare.sh in /usr/bin.

Btw, would it be good to add NFC hack to the side menu? Because now we just can mifare dump only, but without mifare clone. I remember NH2 has 3 options for NFC hacking, so is it a good idea?

**Comment by TheNain38** [comment]
I have the same problem on my Nexus 7 (2013) Wifi

**Comment by jmingov** [comment]
Thanks for the reports,

The file should be there, is just we looking for `dumpmifare` and the file is called ` dumpmifare.sh`.

@simonpunk, close this when you give it a test, and if you want, open a issue with the features request for NFC attacks in a new issue.

Jaime
