### ISSUE TITLE
Mitm Framework Bugs after multiple launches

### ISSUE THREAD

**Issue by nhjoker** [offensive-security/kali-nethunter#349]
This issue is similar to #315
One my one plus (cm12.1), when you launch the mitm attack from the nethunter app, the app launches the terminal correctly. But if you stop the attack and then start it again with the exact same parameters net hunter app sends now a bunch of new parameters causing the fail of mitmf. 
In particular, just like issus 315 :
- "black IP"
-white IP

Also, in "spoof menu" when ARP mode is selected (whether reply or request), if you choose a particular IP to target, you gotta leave a space after the IP you wrote inside the box because when you launch the attack there's a small typo -I think- that puts the IP you wrote directly next to the next parameter, so once more the attacks fails.

**Comment by nhjoker** [comment]
Also, the more you repeat the operation, the more nethunter app adds a bunch of useless and not asked/ticked parameters (even the same : for example multiple times "black-ip")

**Comment by jmingov** [comment]
Is the same as https://github.com/offensive-security/kali-nethunter/issues/315, so a duplicate, continue in the original issue.

**Comment by binkybear** [comment]
@nhjoker: I tried recreating the targets issue but couldn't.  I just want to confirm you are using the latest version of NH app also.

**Comment by nhjoker** [comment]
I do. Here's m'y settings:
One plus one 
Cm 12.1
Buikd : LMY48B
Nethunter app : com.offsec.nethunter 
Version : 3.0.1
Maybe a screenshot or a screen cast would be useful to you ? Tell me if you'd like one

**Comment by binkybear** [comment]
Yes, if you have the time you could send it to binkybear@nethunter.com or link here.
