### ISSUE TITLE
Kali Menu is Outdated (airodum-ng)

### ISSUE THREAD

**Issue by nhjoker** [offensive-security/kali-nethunter#350]
Kalimen - I don't know if you still support it- is a little bit outdated : The airmon-ng program creates a new interface (wlan0mon for example) but kalimenu script still uses mon0 as interface for airodump.

Just a little bug easily fixed by modifying a line

**Comment by jmingov** [comment]
Kalimenu is deprecated, you can add any of the commands via Custom commands tab in the app.
