### ISSUE TITLE
USB HID Attack (Nexus 6, Marshmallow 6.0.1, MMB29S)

### ISSUE THREAD

**Issue by sirulian** [offensive-security/kali-nethunter#351]
Just installed nethunter on my Nexus 6. I tried to use the USB HID attack but the nexus devices doesn't type anything and almost immediately I get a "Attack Execution Ended". Any help on the issue would be appreciated (Installed nethunter as of 6 pm Eastern time on the 20 Jan 16)

**Comment by binkybear** [comment]
Have you updated the app?  Is your hid working?  Also see https://github.com/offensive-security/nethunter-app/issues/114

**Comment by sirulian** [comment]
I just updated the App. Used the correct parameters, etc. but the hid is not working. hid device shows up as /dev/hidg0 on the home panel of nethunter. I still get the "attack launched" followed by the "Attack Execution Ended" right after, almost immediately

**Comment by jmingov** [comment]
@sirulian can tou use a external wireless card? (If not, probably the drivers aren't well installed) and also check inside a kali terminal which version of the package `nethunter-utils` you have and pastee it here, that can be other cause.

Jaime

**Comment by sirulian** [comment]
Nethunter - 3.10.40-g557ba38

I plugged in my TP-Link TL-WN722N and I couldn't get wifite to work or nethutner to recognize it.

**Comment by binkybear** [comment]
@sirulian: This sounds like the kernel didn't flash.  Maybe try flashing kernel again: https://idlekernel.com/nethunter/nightly/3.0.1-20160122-1305/kernel-only/kernel-nethunter-shamu-marshmallow-3.0.1-20160122-1305.zip

**Comment by sirulian** [comment]
Will do. I'll post back once I do it again.

**Comment by sirulian** [comment]
So flashing the kernel fixed the HID problem! It was able to open command prompt and then type in...a bunch of stuff. I put that in the picture attached. Can't get wifite to find the wireless card though.


![hid_output](https://cloud.githubusercontent.com/assets/11309259/12530889/463d26c6-c1aa-11e5-8d3b-c385cb370a4e.PNG)

**Comment by binkybear** [comment]
If you could send/post dmesg of when you plug in atheros we might be able to see issue.

**Comment by sirulian** [comment]
Once I plug it in, wifite just tells me it's looking for the device. My atheros doesn't light up or anything either. Back with the original nethunter, my nexus device didn't have a problem. Not sure what the issue is.

![image](https://cloud.githubusercontent.com/assets/11309259/12533068/c6f2915c-c1e1-11e5-98a7-4fa4858f959a.png)

**Comment by binkybear** [comment]
Have you tried: 
```sh
ifconfig wlan1 up
```

**Comment by sirulian** [comment]
so once i did that, the atheros card turns on, and i have the interace under ifconfig. but wifite still sits there looking for a wireless card...

**Comment by binkybear** [comment]
Try:
```sh
iw wlan1 set type monitor
```
May be similar to https://github.com/offensive-security/kali-nethunter/issues/340

**Comment by sirulian** [comment]
well I'll be damned. So If i do the "ifconfig wlan1 up" followed by the "iw wlan1 set type monitor", it doesn't load up (says device is busy). But unplugging it and plugging it back in, then doing the "iw wlan1 set type monitor" works perfectly. Wifite came right up. Thanks for your help! everything seems to be working great!

**Comment by jmingov** [comment]
Interface should be down so you can change the mode.

**Comment by jmingov** [comment]
https://github.com/offensive-security/nethunter-app/commit/d3776b38282792f199a824a6354092aedac74a2d
