### ISSUE TITLE
Metasploit Meterpreter webcam 

### ISSUE THREAD

**Issue by pahapoika** [offensive-security/kali-nethunter#352]
As seen in this picture https://mega.nz/#!dogUVYjB!HYkckli1SHYrHjFkZGdzJJ-mikoRd1UsZ9kN782cU7E
I cant view webcam snaps,streams or chat. Or do i need to download something?

**Comment by pahapoika** [comment]
+cant find where the screenshots are storaged. Didnt find anything on /root

**Comment by jmingov** [comment]
Hello,

1. Github lets you attach pictures, use the function, we dont download the thing you link here.

2. Think that android is separated of nethunter, so you cant open a picture using the kali-desktop programs, thats why you get that "error" in msf (think that nethunter is like a server, no a desktop)

3. Nethunter '/root' dir is not the android `/root` dir, nethunter `/root` is located at:

`/data/local/nhsystem/kali-armhf/root`

Jaime

**Comment by pahapoika** [comment]
Oh thanks. @jmingov
