### ISSUE TITLE
64-bit toolchain link not working

### ISSUE THREAD

**Issue by Leedl3** [offensive-security/kali-nethunter#357]
I was reading your wiki on the topic of Porting Nethunter whenever I saw that I would need to download a toolchain. My device has a Snapdragon 410 so I wanted to use the 64-bit capability for the device. Whenever I copied and pasted the link though, I got this:

git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b marshmallow toolchain64
Cloning into 'toolchain64'...
fatal: Remote branch marshmallow not found in upstream origin

thank you,
              Leedle

**Comment by binkybear** [comment]
Change the branch name to:

git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 marshmallow-release toolchain64
