### ISSUE TITLE
One Plus of the problem

### ISSUE THREAD

**Issue by MuTouRend** [offensive-security/kali-nethunter#358]
nethunter 3.0 successfully installed into the system in normal use, but constantly unplug USB after the restart to icon interface (not into the system desktop) I ask where is a problem Thank push with 1.0.3 software    Thanks

**Comment by jmingov** [comment]
This needs a better explanation dear.

**Comment by MuTouRend** [comment]
This is what happens Thanks
![Uploading QQ图片20160130004015.jpg…]()

**Comment by MuTouRend** [comment]
This is what happens Thanks
![qq 20160130004015](https://cloud.githubusercontent.com/assets/12621283/12681633/7528336e-c6ea-11e5-81fc-ce82149933d1.jpg)

**Comment by binkybear** [comment]
Those errors can be safely ignored.  It's TWRP trying to follow symlinks (I think).  Everything should be OK.

**Comment by MuTouRend** [comment]
However, there is no phone nethunter AP and Router ... / dsploit / like solving Thanks
Another problem, not the desktop phone kali it is in this picture does not matter

**Comment by binkybear** [comment]
I'm sorry we are still having language troubles.  I'm unsure what issues you are having.

Did it not install?

**Comment by MuTouRend** [comment]
FIG Step 
![2](https://cloud.githubusercontent.com/assets/12621283/12694241/9a170ca0-c761-11e5-931d-41e5b582f5c7.png)
![qq 20160129104914](https://cloud.githubusercontent.com/assets/12621283/12694242/9a198700-c761-11e5-9b80-d6cd71effd95.png)

**Comment by MuTouRend** [comment]
thanks

**Comment by MuTouRend** [comment]
Replied

 ------------------ 原始邮件 ------------------
  发件人: "binkybear";<notifications@github.com>;
 发送时间: 2016年1月30日(星期六) 凌晨1:41
 收件人: "offensive-security/kali-nethunter"<kali-nethunter@noreply.github.com>; 
 抄送: "小子"<769295869@qq.com>; 
 主题: Re: [kali-nethunter] One Plus of the problem (#358)

 

 
Those errors can be safely ignored. It's TWRP trying to follow symlinks (I think). Everything should be OK.

**Comment by MuTouRend** [comment]
![3](https://cloud.githubusercontent.com/assets/12621283/12694264/0db5b142-c763-11e5-999a-758820c8c695.png)
