### ISSUE TITLE
Nexus 6 mana and bad USB problem

### ISSUE THREAD

**Issue by kepzbro** [offensive-security/kali-nethunter#359]
Hello! When I try to launch mana toolkit from my Nexus 6 I get this error.

-- wlan1: flushing interface --                                     -- wlan1: setting ip --
-- wlan1: starting the interface --
-- wlan1: setting route --
sed: can't read /sdcard/nh_files/configs/hostapd-karma.conf: No such file or directory
Configuration file: /sdcard/nh_files/configs/hostapd-karma.conf
Could not open configuration file '/sdcard/nh_files/configs/hostapd-karma.conf' for reading.
Failed to set up interface with /sdcard/nh_files/configs/hostapd-karma.conf
Failed to initialize interface
Internet Systems Consortium DHCP Server 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /etc/mana-toolkit/dhcpd.conf
Database file: /var/lib/dhcp/dhcpd.leases
PID file: /var/run/dhcpd.pid
Wrote 0 leases to leases file.
Listening on LPF/wlan1/60:e3:27:0b:0e:bb/10.0.0.0/24
Sending on   LPF/wlan1/60:e3:27:0b:0e:bb/10.0.0.0/24
Can't bind to dhcp address: Address already in use
Please make sure there is no other dhcp server
running and that there's no entry for dhcp or
bootp in /etc/inetd.conf.   Also make sure you
are not running HP JetAdmin software, which
includes a bootp server.

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.
RTNETLINK answers: File exists
Can't find library for match `quota2'
root@kali:/#

I've tried to se other conf path but with no successivt åt all. Pleasd help me!

**Comment by kepzbro** [comment]
For my badusb the log says: /data/data/com.offsec.nethunter/files/scripts/start-badusb-lollipop[3]: cd: /sdcard/nh_files/configs: No such file or directory

**Comment by furiuz** [comment]
I'm having the exact same problem. I'm running nethunter on Oneplus One. And I can't seem to access anything referring to the /sdcard path, though I can see the files in /storage/emulated/0 in my file viewer. As a workaround for mana, I use the config files from /etc/mana-toolkit. For the badusb you can copy the config files to your kali root folder (/data/local/nhsystem/kali-arhmf/root/)

**Comment by kepzbro** [comment]
I can't seem to even find /etc/mana-toolkit or /data/local/nhsystem/kali-arhmf/root/ folders on my phone. ES file explorer don't find them atleast.

**Comment by furiuz** [comment]
Try to reflash nethunter, it worked for me. All paths found now.

**Comment by kepzbro** [comment]
I did a complete reflash of my nethunter 3.0 nethunter lollipop "rom". Still the same...

**Comment by jmingov** [comment]
We use the 10.0.X.X subnet, if your wlan0 is connected to a router that uses that subnet also, the attacks will fail.

> Can't bind to dhcp address: Address already in use
> RTNETLINK answers: File exists


Change the settings in the configurations so you use a different subnet.

Jaime
