### ISSUE TITLE
NEXUS 7 - Only 11gb available instead of 32gb

### ISSUE THREAD

**Issue by Arnaud-Burn** [offensive-security/kali-nethunter#36]
After a successfull install throught the windows "all-in-one",

I've got only get 11,29gb available instead of 32gb !
so it least me less than 6gb after all the process....

Any idea ?

It's a NEXUS 7 - LTE - 32gb

Thanks

**Comment by snoopypham** [comment]
it's work, thanks a lot mastermind !!!!

**Comment by XxShinsxX** [comment]
worked for me.  having my 20gb back makes me happy face.
