### ISSUE TITLE
Passing commands to term fails on secure setup

### ISSUE THREAD

**Issue by Nekroze** [offensive-security/kali-nethunter#361]
Perhaps poor wording for the title but. If you do not just blanket grant root access to the terminal app, but rather get SuperSU to prompt for a pin each time or just prompt for confirmation, then the passing of commands from the Nethunter app button to update the Kali chroot then it will just print the commands out, SuperSU will prompt and then you are left in the Kali shell. And as the shell was entered after the prompt the command that just got printed to the screen is now gone. 

It does work when you switch back to a blanket grant for the terminal app in SuperSU however I don't think it should force a (arguably) less secure configuration just to work as intended. 

Thank you all for your time and awesome work.

**Comment by jmingov** [comment]
We don suport that on nethunter. 
SuperSu is closed source so we cant to too much i think. 

Imo, nethunter is not designed for security, is for pentesting. 

Sugestions/pr's accepted.

**Comment by binkybear** [comment]
I agree with @jmingov, there isn't much we can do with SuperSU settings either.

**Comment by Nekroze** [comment]
Fair enough.
