### ISSUE TITLE
Wlan1: ERROR while getting interface flags: No such device.

### ISSUE THREAD

**Issue by kepzbro** [offensive-security/kali-nethunter#363]
Hello, I recently updated my nexus 6 from lollipop to 6.0 marshmallow since my nethunter 3.0 had problems locating files on lollipop install.

I've reflashed everything and installed Nethuner 3.0 for marshmallow. Installed seemed to be working just fine and everything went smooth. Then I plug in my Y-cable and my external wifi: Tp-link WN722N.
run the command apt-get install firmware-atheros and try the command: Ifconfig wlan1 up. (it worked on my previous lollipop installation of nethuner 3.0). but now I get this error Wlan1: Error while getting interface flags: No such device. Can't seem to find any fix for it from googling the problem.

**Comment by binkybear** [comment]
The Nexus 6 doesn't support y-cable charging at the moment.  Also make sure kernel flashed in settings> about and try using standard micro-usb>otg.
