### ISSUE TITLE
Nethunter 3.0 OnePlusOne - CreateChroot Java Runtime Error

### ISSUE THREAD

**Issue by xavkno** [offensive-security/kali-nethunter#365]
Hello,

Device: OnePlus One 64GB
CM 12.1
Nethunter - 3.0.1

After Download Full Chroot -> Checking file inegrity -> MATCH -> Unzipping and Uncompressing - > CreateChroot >> Error: java.lang.RunTimeException: java.lang.RunTimeException

Thanks.

**Comment by binkybear** [comment]
Try updating your busybox.

**Comment by xavkno** [comment]
The issue was openGapps

**Comment by MPeti1** [comment]
Same here. Redmi 3s prime (miui 8), openGapps not installed (google apps are installed in the stock system), busybox manager (stericson) says bb is up to date. I've found it in SuperSU logs: https://prnt.sc/fuiu39

**Comment by Elhammouti** [comment]
just install busybox in /system/xbin and /system/bin
