### ISSUE TITLE
Kernel Compiling Bluetooth error

### ISSUE THREAD

**Issue by Leedl3** [offensive-security/kali-nethunter#366]
I have the following error

drivers/bluetooth/btusb.c: In function '__check_reset':
drivers/bluetooth/btusb.c:1659:1: warning: return from incompatible pointer type [enabled by default]
error, forbidden warning: btusb.c:1659
scripts/Makefile.build:308: recipe for target 'drivers/bluetooth/btusb.o' failed
make[2]: *** [drivers/bluetooth/btusb.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/bluetooth' failed
make[1]: *** [drivers/bluetooth] Error 2
Makefile:820: recipe for target 'drivers' failed
make: *** [drivers] Error 2

What do I need to do to fix this?

**Comment by joeisgood99** [comment]
Leedl3 
Did you work this one out?

**Comment by jcadduono** [comment]
@joeisgood99 you can simply change variables declared in btusb.c from int to bool to match their param declarations below.

see btusb.c @ https://github.com/jcadduono/android_kernel_zte_msm8996/commit/3fabedd1bf23947bc5246a888c461fb6027890e0

`static int reset = 1;` = `static bool reset = true;`
