### ISSUE TITLE
i Have Nexus5X !

### ISSUE THREAD

**Issue by hny287** [offensive-security/kali-nethunter#368]
Heya , i Have Nexus 5X WITH ME and the Question is . Can i install NETHUNTER 3.0 in NEXUS 5X ? please :D Hope you Help me :D thanks

**Comment by jmingov** [comment]
Yes, you can build it yourself following the instructions:

https://github.com/offensive-security/kali-nethunter/tree/master/AnyKernel2

the command needed is:

`python build.py -d bullhead --marshmallow --noaroma`

Read the wiki for more information:

https://github.com/offensive-security/kali-nethunter/wiki#30-building-nethunter

Jaime

**Comment by hny287** [comment]
Thanks and regards :) hruday

**Comment by hny287** [comment]
But i Am Having an ERROR Over There ! 

"
honey1998: ~/kali-nethunter/AnyKernel2 $ python build.py -d bullhead --marshmallow --noaroma
Traceback (most recent call last):
  File "build.py", line 543, in <module>
    main()
  File "build.py", line 377, in main
    module_list = [f for f in os.listdir("system/lib/modules")]
OSError: [Errno 2] No such file or directory: 'system/lib/modules'
"

**Comment by hny287** [comment]
how do i recover From This ?

**Comment by aosius** [comment]
Build in kali or in ubuntu it works for me

**Comment by IvoPereira** [comment]
I'm afraid AnyKernel2 is not in the branch anymore. Any idea where can I find it?

**Comment by aosius** [comment]
https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer

**Comment by IvoPereira** [comment]
@aosius however that branch seems to not having noaroma option. How can I disable aroma?

**Comment by aosius** [comment]
https://www.dropbox.com/s/y0ghj0rnejdjw9f/update-nethunter-bullhead-marshmallow-922016_112855.zip?dl=0 builded few days ago before this update now i dont have time to check

**Comment by IvoPereira** [comment]
Hey @aosius,

Thanks, however I'm looking for hammerhead device. Isn't it possible to disable aroma in the current installer?

**Comment by jmingov** [comment]
Aroma is no longer in the repository, all builds are no-aroma by default now.

**Comment by mathewsdaniel** [comment]
Yes, you can. You can either build it yourself as other suggested or flash an already built Nethunter ROM for Nexus 5x. I got it from the XDA. Here are the links:- 
[NetHunter Bullhead Nougat ROM](https://www.androidfilehost.com/?fid=385035244224382416)
[NetHunter Bullhead Marshmallow ROM](https://www.androidfilehost.com/?fid=457095661767099319)
I followed this tutorial [Kali Nethunter for Nexus 5x Bullhead Installation Guide](http://www.hackcave.net/2017/02/kali-nethunter-for-nexus-5xbullhead-nougat-marshmallow-tutorial.html) and it is working like a charm. Wireless attacks works fine with all popular adapters. Personally tested Alfa AWUS036NH and  TP Link TL-WN722N and found working.
