### ISSUE TITLE
proxmark3 question

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#371]
Hi, so I am trying to get the proxmark3 to work with Kali Nethunter, it appears that like with desktop kali and stock debian or ubuntu the proxmark3  is scooped up by modemmanager before the client can use it (/dev/ttyACM0 is the path to the descriptor in most cases). on a desktop OS I would disable modem manager to fix this issue but it does not look like modem manager is installed in the chroot. Has anyone gotten the proxmark3 to work with Kali Nethunter 3 with Lolipop? What am I missing?

**Comment by TomasAndersonvoid** [comment]
If you are using CDC firmware on your PM3, there will be a Position Indipendent Execuritable (PIE) problem on android 5.0 above. (Same as mine) This problem still occur, you can find some information here: http://www.proxmark.org/forum/viewforum.php?id=14
Otherwise you can downgrade your firmware to suit this old proxdroid.

**Comment by jmingov** [comment]
Thank you @TomasAndersonvoid

**Comment by thesle3p** [comment]
I fixed the PIE issue by recompiling proxdroid with PIE but the issue is something (I think nethunter) is hooking /dev/ttyACM0 as soon as it’s loaded.

**Comment by TomasAndersonvoid** [comment]
I see, I am stucking at PIE, could you please give me some hint on how to complie proxdroid with PIE? And I will see if I have the same problem with yours.

**Comment by thesle3p** [comment]
Use the most recent version of the Android-NDK to compile it from git.

**Comment by binkybear** [comment]
@TomasAndersonvoid - You could use: https://github.com/jcadduono/nethunter-installer-tools

**Comment by TomasAndersonvoid** [comment]
I have managed to fix the PIE iessue. But afther I type proxmark3 in system/bin, it shows : Accessing a corrupted shared library. I dont know if is the same problem with sle3p.

**Comment by thesle3p** [comment]
The problem I get is proxmark runs but when /dev/ttyACM0 is created
something hooks it before the program can use it on ubuntu/debian/desktop
Kali that's modemmanager but as far as I know that's not installed on
nethunter.

**Comment by TomasAndersonvoid** [comment]
I see, could you please send me a copy of your libtermcap.so libreadline.so
and proxmark3. I want to try it on my phone.
On Feb 7, 2016 01:49, "thesle3p" <notifications@github.com> wrote:
>
> The problem I get is proxmark runs but when /dev/ttyACM0 is created
> something hooks it before the program can use it on ubuntu/debian/desktop
> Kali that's modemmanager but as far as I know that's not installed on
> nethunter.
> On Feb 6, 2016 12:09 AM, "TomasAndersonvoid" <notifications@github.com>
> wrote:
>
> > I have managed to fix the PIE iessue. But afther I type proxmark3 in
> > system/bin, it shows : Accessing a corrupted shared library. I dont
know if
> > is the same problem with sle3p.
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/offensive-security/kali-nethunter/issues/371#issuecomment-180684753

**Comment by thesle3p** [comment]
How would you like me to send it to you?

**Comment by TomasAndersonvoid** [comment]
My email is tomasanderson.void@gmail.com Thanks

**Comment by thesle3p** [comment]
Sorry for the delay, but after talking to the developer of proxdroid it is no longer supported or functional. The best option going forward is to add the proxmark3 client in the nethunter repos and run it in the linux chroot.

**Comment by prairie-guy** [comment]
How to compile Proxmark3 on Nethunter

1) Get Source:
git clone https://github.com/Proxmark/proxmark3.git

2) Update libreadline:
apt-get install libreadline6-dev

3) Add gcc-arm-none-eabi cross-compiler for ARM:
apt-get install gcc-arm-none-eabi 

4) Compile:
cd proxmark3
make

5) Plug-in PROXMARK3 hardware into USB/USB-C:

6)Find device:
dmesg | grep ttyACM    #--> /dev/ttyACM0

7) Launch proxmark3
cd proxmark3/client
./proxmark3 /dev/ttyACM0

8) Test:
hw version
hw tune
hw quit

**Comment by ebrinkster** [comment]
I also needed to install libncurses5-dev

**Comment by endciphers** [comment]
Also need to install pkg-config

**Comment by ceres-c** [comment]
Hi guys, i might need your help.

I have no problems in compiling and running the client, but I get no answer from the proxmark. with `dmesg` i can see the device registered as /dev/ttyACM0, but the client can get no response. `hw ping` fails, no matter what
I have tried with both stock and iceman's fork. Do you have any idea? Might it be an android kernel issue?

**Comment by bozwald** [comment]
Ive managed to use my PM3 v2 elechouse on a s8+/nexus 7 (2012)/nexus 5x and
hwtune/hf scan/lf scan works well and have brute forced with it.

what device are you using? Kernel? Can you quote the dmesg log from
/dev/ttyACM*? I will check tonight what firmare my pm3 is on.

Does your device work normally on a computer?

**Comment by ceres-c** [comment]
I am using a proxmark3 easy which works fine on all the PCs I have tested it with, but is not working with any phone I have access to

It was tested with a Nexus 6P (FrancoKernel) using termux (no kali chroot) and cross compiling proxmark's client for android on a linux machine. It's also not working on a Nexus 5 running Kali Rom (the one derivated from LineageOS). On both devices the pm3 is correctly (AFAIK) enumerated on port /dev/ttyACM0, but I get not response trying to connect to it.

dmesg output:
![screenshot_20171107-110156](https://user-images.githubusercontent.com/24912818/32488212-2de40ddc-c3ac-11e7-9fb0-1e65cbd219fc.png)
Proxmark's client output (as you can see there is no "hw info" on connect)
![screenshot_20171107-111119](https://user-images.githubusercontent.com/24912818/32488308-7e41258a-c3ac-11e7-97f8-9cd7b060451a.png)
Also, if I run straight away another pm3 client instance on the same port I get an "invalid serial port" error while, according to dmesg nothing has changed. I have to unplug and plug back the pm3. I have also tried to chmod 666 /dev/ttyACM0 to no avail
