### ISSUE TITLE
Duckhunter HID and HID attacks send nothing

### ISSUE THREAD

**Issue by Leedl3** [offensive-security/kali-nethunter#373]
I saw where someone had this similar problem and I made sure I had MTP disabled and had it to where it would only charge. It won't type anything on windows 7 or linux. I also saw where the two HID devices were working in the Nethunter app

**Comment by Leedl3** [comment]
The USB keyboard app  still runs even when i put the phone on charging mode. It works on linux and windows 7

**Comment by n00shE** [comment]
Had this problem recently too. Gave up and reinstalled. Open the nethunter app and check the HID Interfaces after initiating an attack.  After running an attack open terminal and type "cd /dev/" then ls. Look for hidg1 and hidg0 (keybooard and mouse). I believe these are created on boot. Seems to be an issue with HID interfaces.

**Comment by n00shE** [comment]
#125

**Comment by zlice** [comment]
i have the same issue. cd to $chroot/opt and manually running duckout.sh works, however the GUI does not pop-up a SU toast

**Comment by zlice** [comment]
just submitted a pull request

busybox location was not found by bootkali_init and killkali

also - /system was not sync'ed to chroot's /system mount
/system/xbin/hid-keyboard (which i had to manually extract from nethunter zip and place there) was not in /data/local/nhsystem/kali-armhf/system/xbin/

**Comment by jcadduono** [comment]
i don't think these issues are present in 3.15.2 installer?

**Comment by zlice** [comment]
installed 3.0 - updated to 3.15

**Comment by jcadduono** [comment]
ok, that's why, so i guess consider this issue resolved

**Comment by ichintu** [comment]
its not resolved. I am running 3.15 and its not working. tried it on a nexus 5 and a nexus 7

**Comment by jcadduono** [comment]
Which zips did you install?

**Comment by ichintu** [comment]
nethunter-hammerhead-lollipop-3.0 & nethunter-flo-marshmallow-3.0

**Comment by jcadduono** [comment]
Then yes it's resolved. Flash 3.15.2 zips from build.nethunter.com or wait for next official release.

**Comment by ichintu** [comment]
Apologies you are right. it's fixed. I just flashed kernel-nethunter-flo-marshmallow-3.15.2-20161014-0038 on my nexus 7 and duckhunter is working. I will confirm once i try nexus 5

**Comment by ichintu** [comment]
its probably a different issue but with nexus 5 when i try to install nethunter-hammerhead-lollipop-3.0 its hanging at like 20, 40, 90% and when i installed kernel-nethunter-hammerhead-lollipop-3.15.2-20161014-0038 on another nexus 5 that was running 3.0 it just went into a boot loop.

**Comment by jcadduono** [comment]
3.0 installer issues are all fixed at this point, 3.0 is old, outdated.

you may have better luck reflashing your rom (boot and system) and then flashing nethunter-generic-armhf-kalifs-rolling 3.15.2 zip followed by kernel-nethunter-hammerhead-lollipop 3.15.2 zip

**Comment by ichintu** [comment]
tried this if i only flash armhf-kalifs-rolling 3.15.2 i have nethunter but duckhunter does not work on nexus 5 but the rest works. the device boots up etc. however if i install kernel-nethunter-hammerhead-lollipop 3.15.2 on top then the phone boots to recovery and wont boot to system. I am running M4B30X

**Comment by zlice** [comment]
tried flashing a couple different zips also

https://www.offensive-security.com/kali-linux-nethunter-download/

^only page i could find with zips that include '/system/xbin/hid-keyboard' - where is a 3.15 zip?

is 'tools/symlinkxbin.sh' where 'hid-keyboard' is copied ?

**Comment by jcadduono** [comment]
hid-keyboard is in kernel zip since it is a kernel feature

You are installing lollipop kernel on marshmallow?! No wonder it isn't booting.... Install the right kernel!

If marshmallow kernel still not working on M4B30X then maybe the kernel needs an upgrade. I know it at least works on MOB30D.

**Comment by ichintu** [comment]
I feel so silly. I guess this is what happens from lack of sleep. The marshmallo option works perfect on the latest. thanks again

**Comment by binkybear** [comment]
@jcadduono - Flashed kernel yesterday for Nexus 5.  Still works fine on marshmallow.

**Comment by tehpenguin** [comment]
Hey noob question. HID isnt working for me and installed nethunter 3.0 on nexus 7 6.0.1. It looks like i need to flash the 3.15 armhf. Im confused how to flash the kernal afterwords?
