### ISSUE TITLE
TL-WN822N Problem

### ISSUE THREAD

**Issue by mackenziemueller** [offensive-security/kali-nethunter#375]
I'm running Kali Linux Nethunter 3.0 on a Nexus 6, and I'm trying to run Wifite with a TL-WN822N wireless adapter but when I open the Nethunter app and open custom commands and run Wifite, it says airmon-ng requires the program iw. I launch the command airmon-ng and try to register my adapter but it never shows up. And when I run Wifite through the Nethunter terminal it says cowpatty is suggested and the command airmon-ng stills does not detect my wireless adapter. I have downloaded the driver for it on my Nexus 6 but have not on Nethunter. Any help? (step by step process, I have basic knowledge of Linux)

My two OTG cables are:

http://www.amazon.com/Samsung-EPL-AU10WEGXAR-USB-Adapter/dp/B00D5R38HW

http://www.amazon.com/gp/aw/d/B017X2BOWA/ref=mp_s_a_1_6?qid=1454629381&sr=8-6&pi=AC_SX236_SY340_FMwebp_QL65&keywords=otg+cable&dpPl=1&dpID=31yajB0RtvL&ref=plSrch

**Comment by binkybear** [comment]
1) Make sure kernel flashed in settings > about > (look for root@kali)
2) If your kernel did not flash and you are on marshmallow, flash this: https://idlekernel.com/nethunter/nightly/3.0.5-20160204-0830/update-nethunter-shamu-marshmallow-3.0.5-20160204-0830.zip.
3) If it did flash, get a dmesg and look for firmware errors:
```sh
dmesg > /sdcard/dmesg.txt
```

**Comment by mackenziemueller** [comment]
I flash the image now I need to upload the driver because under driver it
displays ?????? I have the driver on my phone but need to know how to
upload it. (Here are some images of it)

**Comment by mackenziemueller** [comment]
Is there a way i can use my wifi adapter instead of my internal one in the
Nexus 6?
