### ISSUE TITLE
Phone freezes when downloading file

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#376]
I've been using nethunter on OPO cos12.1 for the past few days and i've found a very unusual bug, when downloading a file from chrome the device will start hanging and is unresponsive, the only way to reboot it is to force shutdown and restart, i've experienced this quite a number of times while using nethunter

**Comment by jmingov** [comment]
Hello @bkr32, 

Why do you think this has something to do with nethunter?

Nethunter doesnt care if Chrome is installed or not, nethunter neither do any changes to the  browser installed.

Jaime

**Comment by bkr32** [comment]
chrome was a example, when  a download is initiated in most of the time the phone just freezes up, i used chrome as a example since easy to replicate the issue with it @jmingov

**Comment by binkybear** [comment]
@bkr32 - If you can get a kernel oops from last_proc that can go a ways to understanding what is causing issue.
```sh
cat /proc/last_kmsg > /sdcard/oops.txt
```
Or something along that lines after a force restart.  But like jmingov mentioned, if it's not kernel related than its associated with something else on phone.

**Comment by bkr32** [comment]
[oops.txt](https://github.com/offensive-security/kali-nethunter/files/120348/oops.txt)

thats the log from my last force restart, unless it was downloading something from the background, it froze up while playing audio

**Comment by binkybear** [comment]
I have redone the power/y-cable charging for the 1+1 kernel and uploaded it here for anyones testing:

https://transfer.sh/qI7DY/kernel-nethunter-oneplus1-lollipop-20160206-145046.zip

@bkr32 - As far as the log does, I did not see a kernel oops so I'm still at a loss.  Maybe this will fix issues for you.

**Comment by bkr32** [comment]
I'll try it out thank you expect feedback :)

**Comment by bkr32** [comment]
Hi, can the above kernel please be re-uploaded,i lost it while doing a restore and it does fix the download crash issue, i also wanted to ask if weekly builds are made and if so where can i download updates from 
thanks

**Comment by binkybear** [comment]
@jcadduono is nice enough to provide nightlies: https://idlekernel.com/nethunter/nightly/

**Comment by bkr32** [comment]
Thanks for the link @binkybear flash over existing install?

**Comment by binkybear** [comment]
You should be able to flash just kernel over existing install.
