### ISSUE TITLE
Link in wiki is dead

### ISSUE THREAD

**Issue by Lucurus** [offensive-security/kali-nethunter#377]
Hi, I just wanted to inform you, that the last link in your wiki to the Nethunter app is dead. 
(https://github.com/offensive-security/kali-nethunter/blob/master/flash/data/app/nethunter.apk)

**Comment by binkybear** [comment]
https://images.offensive-security.com/latest.apk <-- Fixed.  Latest link in case you are looking for it.

**Comment by Lucurus** [comment]
Thank you

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
