### ISSUE TITLE
Unable to mount /data

### ISSUE THREAD

**Issue by SkylerNgC** [offensive-security/kali-nethunter#378]
Hi,

I recently got a Nexus 7 (2013). I've unlocked and flashed the stock with no problem. However, when I attempt to do the last step (2.3 Custom Recovery (TWRP) + SuperSU (root) + Kali Linux NetHunter), the transferring of files was ok but it seems like it's unable to finish the last two steps. 

Here's a section of what it says when I try to run the scrip twrpFlash.sh:

Booting into TWRP (20 secs dont worry)
downloading 'boot.img'...
OKAY [  0.357s]
booting...
OKAY [  0.028s]
finished. total time: 0.386s
Booting into TWRP DONE

Installing SuperSU
TWRP does not appear to be running. Waiting for TWRP to start . . .
Press CTRL + C to quit.
E:Unable to mount '/data'
Unable to locate zip file '/sdcard/supersu.zip'.
Installing '/sdcard/supersu.zip'...
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
E:Failed to sysMapFile '/sdcard/supersu.zip'
E:Error installing zip file '/sdcard/supersu.zip'
Done processing script file
Installing SuperSU DONE!

Installing Kali Linux Nethunter
E:Unable to mount '/data'
Unable to locate zip file '/sdcard/kaliNethunter.zip'.
Installing '/sdcard/kaliNethunter.zip'...
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
E:Failed to sysMapFile '/sdcard/kaliNethunter.zip'
E:Error installing zip file '/sdcard/kaliNethunter.zip'
Done processing script file
Installing Kali Linux Nethunter DONE!
Rebooting into Kali Linux Nethunter
Everything is installed. Phone should be booting up! Enjoy

I'm new to all of this, so if I'm missing something, please let me know. I will appreciate any help!

Also, I'm not sure if this has anything to do with it, but I have the Nexus using PTP instead of MTP.

Thanks

**Comment by alvarosaavedra** [comment]
You can fix it: remove the "-p" from the adb push command at line 50 & line 55 in the twrpFlash.sh and try it again.

https://forums.kali.org/showthread.php?29125-Problem-with-twrpFlash-sh-script

**Comment by jmingov** [comment]
https://github.com/offensive-security/nethunter-LRT/issues/2
