### ISSUE TITLE
(Nexus 6 Marshmallow) Keyboard input is not working in VNC mode

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#379]
I connected to the VNC and just wanted to type something, but it was like not able to sense my finger even it did pop up the keyboard panel to me, in other words, the popped up keyboard panel is "fake". And except for this, everything is fine. So, for now I need to use the send key command to input my words instead.

Do you guys have the same issue as me? or just me having this problem? Any ideas?

**Comment by jcadduono** [comment]
you have to switch main input method to Hacker's Keyboard.
this depth glitch happens with AOSP keyboard, Google keyboard, and CM keyboard.
also happens in USB Keyboard app.
