### ISSUE TITLE
Nexus 5 6.0.1 MMB29S - iw: command not found

### ISSUE THREAD

**Issue by IvoPereira** [offensive-security/kali-nethunter#380]
Device: Nexus 5
ROM: Stock rooted 6.0.1 (MMB29S)
Root: SuperSU v.2.67
ROM State: clean install + supersu + busybox

Hello,

After having installed kali-nethunter and trying to run wifite from Custom Commands, wifite shows up, but it returns the error: "airmon-ng requires the program iw".

If I try to run iw in the Kali Terminal the following message appears:
```
"bash: iw: command not found"
```

Even after running `apt-get update` I get the same results.

Any ideas?

Thanks

**Comment by vay3t** [comment]
the comand 'iw' exist. 
```
root@kali:~# iw
Usage:  iw [options] command
Options:
        --debug         enable netlink debugging
        --version       show version (3.17)
Commands:
        help [command]
        event [-t] [-r] [-f]...
```

i have Device: Nexus 5 6.0.1 (MMB29S), supersu free 2.64, kernel 3.4.0-gb7558f2 #2

**Comment by IvoPereira** [comment]
Hey. Strange then.

How may I install it without Aroma? And how can I check kernel?

Thanks!

**Comment by vay3t** [comment]
how to create zip nethunter without aroma: https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer
install nethunter in hammerhead: https://github.com/offensive-security/nethunter-LRT
if you have problems with ADB please visit #341 
recommendation: add your google email after installed nethunter in your nexus

**Comment by IvoPereira** [comment]
Kernel: 3.4.0-g7717f76

Yeap, I've noticed that either. That the installer does not have the option `--noaroma`` anymore.

And I've did add my google email after the installation.

Thanks

**Comment by binkybear** [comment]
iw is installed by default.

**Comment by IvoPereira** [comment]
@binkybear so what could be the reasons for it not being installed? How can I use the installer with noaroma?
