### ISSUE TITLE
Openvpn client: unable to redirect default gateway -- Cannot read current default gateway from system

### ISSUE THREAD

**Issue by nrgskill** [offensive-security/kali-nethunter#381]
Running Kali 3.0 on Oneplus One 12.1-YOG7DAS2K1
Openvpn version: OpenVPN 2.3.4

issue:
Openvpn connects but can't read (and set) routing:

Openvpn connection Log (sanitized):

> OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH]
> [IPv6] built on Dec  1 2014
> library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
> UDPv4 link local: [undef]
> UDPv4 link remote: [AF_INET]ip:port
> WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> VERIFY OK: bla bla bla
> VERIFY OK: nsCertType=SERVER
> VERIFY OK: bla bla bla
> Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
> Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
> Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
> Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
> Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
> [vpnsvc] Peer Connection Initiated with [AF_INET]ip:port
> TUN/TAP device tun0 opened
> do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> /sbin/ip link set dev tun0 up mtu 1500
> /sbin/ip addr add dev tun0 ip/sm broadcast ip
> **NOTE: unable to redirect default gateway -- Cannot read current default gateway from system**
> Initialization Sequence Completed

Openvpn config (sanitized)

> client
> dev tun 
> proto udp 
> ; Cert
> ns-cert-type server
> cipher BF-CBC
> ;Host
> resolv-retry infinite
> ;auth
> auth-user-pass
> keepalive 10 30
> sndbuf 0
> rcvbuf 0
> remote serveraddress port
> persist-key
> persist-tun
> nobind
> comp-lzo
> verb 2
> <ca>
> -----BEGIN CERTIFICATE-----
> bla bla bla
> -----END CERTIFICATE-----
> </ca>

**Comment by binkybear** [comment]
So openvpn is going to be use android networking and with lollipop that means routing tables so it might be a bit more complicated.

You can read a little more on vpn and routing tables on this [post](http://tinc_gui.poirsouille.org/).  Just search for "Android 5.0 / Lollipop."

IMO Using openvpn (https://f-droid.org/repository/browse/?fdid=de.blinkt.openvpn) for android is a much better client.  However, that doesn't really solve your question and may not even be what you are interested in.

But to answer your question, it may be an issue with routing tables.
