### ISSUE TITLE
 TAB word in DuckHunter HID

### ISSUE THREAD

**Issue by sramtam** [offensive-security/kali-nethunter#382]
How to type the word "testTABtest"  in DuckHunter HID? I have letters "T" "A" "B" in payload, but DuckHunter HID coverts to lowercase letters "T" "A" "B" resulting to "testtabtest". 
Code:
STRING testTABtest

P.S I am using OnePlus One and NetHunter 3.0

**Comment by binkybear** [comment]
I believe it may be associated with:

https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/duckhunter.py#L56

For now you could try removing that line from /sdcard/nh_files/modules/duckhunter.py.  I believe we might have to add some more some better checking.

**Comment by TheNain38** [comment]
@binkybear You would need to apply the replacement only when the word is at the begining of the line or only have spaces to its left
