### ISSUE TITLE
Does Not support Nexus 5X (bullhead)

### ISSUE THREAD

**Issue by judebzy** [offensive-security/kali-nethunter#383]
Does Not support Nexus 5X (bullhead) :(

**Comment by slick97477** [comment]
It is being worked on for future support, also you can build your own image
via the github source

On Thu, Feb 11, 2016 at 11:45 PM, judebzy <notifications@github.com> wrote:

> Does Not support Nexus 5X (bullhead) :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/kali-nethunter/issues/383>.
>



-- 
Malachi 3:8-9 <http://bible.knowing-jesus.com/Malachi/3/8>

"Will a man rob God? Yet you are robbing Me! But you say, 'How have we
robbed You?' In tithes and offerings. "You are cursed with a curse, for you
are robbing Me, the whole nation of you!

**Comment by jmingov** [comment]
https://github.com/offensive-security/kali-nethunter/issues/368#issuecomment-177820905
