### ISSUE TITLE
Nexus 5 6.0.1 MMB29S: Unable to detect wireless devices details

### ISSUE THREAD

**Issue by IvoPereira** [offensive-security/kali-nethunter#384]
Device: Nexus 5
ROM: Stock rooted 6.0.1 (MMB29S)
Root: SuperSU v.2.64
ROM State: clean install + supersu + busybox
Kernel: 3.4.0-g7558f2

Some days ago I've faced an issue that was mentioning that I didn't have iw installed. After installing another kernel I was able to get past that.

However, in the screen of choosing the device to put into monitor mode, I'm presented with p2p0 and wlan0 interfaces, however both of them show "??????" on driver column and "unable to detect for sdio 0x02d0:0x4335" on Chipset column.

Trying start wifite on any of them would just loop the prompt to choose any device. If I try to airmon-ng wlan0 I get:
`ERROR adding monitor mode interface: command failed: Operation not supported (-95)`

What could it be? Some drivers missing? If so, how can I fix that?

Thanks

**Comment by lanacif** [comment]
I have the same problem. I tried replacing the airmon-ng. But I get the error **"ERROR while getting interface flags: no such device"**

**Comment by vay3t** [comment]
wlan0 is not compatible monitor mode. please use a external usb wifi tplink tl-wn772n

check our wiki for more information https://github.com/offensive-security/kali-nethunter/wiki

**Comment by jmingov** [comment]
All right @vay3t.

Saludo!

**Comment by IvoPereira** [comment]
@vay3t however Nexus 5 shouldn't have a compatible monitor and inject modes?

Do I really need to always carry a wifi adapter to use wifite?

**Comment by vay3t** [comment]
yes it is. please you can ask me on twitter @vay3t
