### ISSUE TITLE
Terminal error "1) no title" on Nexus 9 running 6.0.1     

### ISSUE THREAD

**Issue by locustnigi** [offensive-security/kali-nethunter#386]
As title, I cannot use any nethunter app, nor using my kali terminal.
I have removed and reinstalled chroot as suggested in similar topics, but witith no success.

I made a wipe, i rooted the device with supersu, and installed nethunter. After, I turned on the device and I made my first login. During the installation I could not got rid of the error messages as in #329 even wiping.

**Comment by locustnigi** [comment]
Repeated the process of removing the chroot. when it comes to select the packages to install, I select kali-nethunter, but pressing install&update produces again the "1) no title" error.

**Comment by locustnigi** [comment]
Weird thing is that eachnrestart of the tablet erase the chroot, and I have to do all the download and installation from scratch.. :/

**Comment by kendallgreen** [comment]
similar problem with OnePlus One.  I installed nethunter 3.0 from TWRP 3.0 and don't have the menu. Just "select shell KALI ANDROID ANDROIDSU"  any choice leads to "1) no title"

**Comment by locustnigi** [comment]
@kendallgreen Did you started android before installing kali?

**Comment by kendallgreen** [comment]
No I upgraded TWRP to 3.0 and installed nethunter 3.0.  When that didn't work, I ran the scripts from the linux kit to get a clean image which also failed in the fastboot mode.

**Comment by locustnigi** [comment]
Same here but with windows..

**Comment by kendallgreen** [comment]
I repeated using the scripts with sudo since fastboot requires it.  I finally managed to get Nethunter 3.0 installed.

**Comment by locustnigi** [comment]
Could you please detail the experience? Which scripts are you talking about? I havent used adb, but the Nexus Root Toolkit.

**Comment by chrcoe** [comment]
I have also used the Nexus Root Toolkit and have the same problem.  However, I can load ANDROID and ANDROIDSU terminals but not KALI which appears to be the terminal that the NetHunter apps are trying to load and then I get the "1) no title" message and the terminal closes.  I was able to capture the attached screenshot as the terminal was flashing open before the no title message.

![screenshot_20160307-213510](https://cloud.githubusercontent.com/assets/770617/13610222/9e0f4e62-e52a-11e5-9828-e794173de3c9.png)

**Comment by binkybear** [comment]
@chrcoe - You do not appear to have kali chroot install, you may have to try to redownload chroot from within app.

**Comment by chrcoe** [comment]
@binkybear that's what I thought but when I go to my nethunter app under chroot manager the only option is to remove chroot or to add new metapackages and I think I am missing something.  I will remove chroot and reinstall it.

**Comment by chrcoe** [comment]
@binkybear that worked great, thanks!  When I installed nethunter I didn't see an option for full chroot access but it appeared to have been setup with limited capabilities.  When reinstalling it gave me the option of setting it up with full access.

**Comment by mehardeepsingh** [comment]
I am having the same issue also tried redownloading and reinstalling chroot and also tried reflashing nethunter. The same screenshot is seen on my terminal. I am running a one plus x with cm13 and 6.0.1 installed. Help will be appreciated. Thank you.

**Comment by mehardeepsingh** [comment]
Also only the Kali terminal crashes there is no issue with android and androidsu

**Comment by binkybear** [comment]
@mehardeepsingh - Go into androidsu and type bootkali.  If you get an error then either chroot isn't installed, busybox isn't installed, or nethunter app did not generate configuration file.

**Comment by Sujay45** [comment]
Guys Just give the all permissions of Nethunter app. In SETTING>>APPS>>NETHUNTER>permission // this app need to have all permission allowed

**Comment by fadihere** [comment]
@sujay45
How To Open permissions In Samsung Device's?

**Comment by bhavik9090** [comment]
I got an error Saying "Setenforce: not found".
