### ISSUE TITLE
Bettercap in NH APK

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#387]
I would suggest to include [The bettercap project](https://github.com/evilsocket/bettercap/) into nethunter [apk](https://github.com/offensive-security/nethunter-app)

**Comment by jmingov** [comment]
Yep, we tested it time ago, and worked fine with nethunter.

Will come in future releases.

Atm, you can manually install it following the webpage instructions, https://www.bettercap.org/docs/install/ (try to avoid beta version since it can have "problems").


Jaime

**Comment by vay3t** [comment]
All right @jmingov Thanks!

Saludos

**Comment by binkybear** [comment]
Yep, would love to add bettercap.  For now, manual dev version install worked for me in NH:
```bash
sudo apt-get update && apt-get install -y build-essential ruby-dev libpcap-dev
cd /opt
git clone https://github.com/evilsocket/bettercap
cd bettercap
gem install bundler
bundle install
gem build bettercap.gemspec
sudo gem install bettercap*.gem
```
Also, I believe: gem install bettercap would work as long as you have prereq's also for stable version.

I think it has a lot of the same functionality as MITMf but claims to be a better at ICMP redirects as well as much less options (which I like).

**Comment by vay3t** [comment]
I have installed using:
```
~# apt-get install build-essential ruby-dev libpcap-dev -y && gem install bettercap
```

And it work fine

**Comment by binkybear** [comment]
Updated to know that bettercap can be run from mana-toolkit menu in updated apk with updated nethunter-utils.  APK and changes will be pushed soon.

**Comment by vay3t** [comment]
Nice! I will wait for the update!
