### ISSUE TITLE
HID Attacks   open failed: ENOENT (No such file or directory) 

### ISSUE THREAD

**Issue by yo0x** [offensive-security/kali-nethunter#388]
OPO: Apk Version.3.0.5
when i press under: HID Attacks>Windows CMD>Save To SDCARD 
is unable to save the custom script and says:
_open failed: ENOENT (No such file or directory) _

any ideas why?

**Comment by xxkirbyy** [comment]
Could be silly, but is the SD card mounted?

**Comment by yo0x** [comment]
Ho no. As I wrote I got a oneplus one 64gb. No sdcard inside.

**Comment by JakTheRipper** [comment]
I'm stuck in the same boat. Nexus 7 and I cant save, same error. I talked to someone else running Net Hunter Version 2 and they also had the same problem.

**Comment by binkybear** [comment]
The code is located: https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/HidFragment.java#L522

It attempts to make a file:

new File(nh.APP_SD_FILES_PATH,loadFilePath);

The SD_FILES_PATH is located here:

https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/utils/NhPaths.java#L93

So it saves to:

/(storage_name)/nh_files/scripts/hid/

Can you confirm you have that folder?

**Comment by JakTheRipper** [comment]
Thanks, that helped. I can save now!
