### ISSUE TITLE
solution to Wifite can not capture handshake file

### ISSUE THREAD

**Issue by TomasAndersonvoid** [offensive-security/kali-nethunter#389]
Hi @binkybear , though the test of external wifi cracking I found that this verson of wifite can not work properly (can not get hand shake capture). Refer to darkr4y's work, I suggest change origional version to darkr4y's version ---- https://github.com/darkr4y/wifite-mod. It will fix the capture problem by my test.

**Comment by zuthroxius** [comment]
If you run it with the -aircrack option do you have the same problem?

**Comment by TomasAndersonvoid** [comment]
There is no problem with aircrack-ng if you look through the link. The problem is there are few mistakes in wifite.py script, it invokes aircrack function but can not check handshake file properly. If you only use aircrack-ng insted of wifite there won't be a problem

**Comment by tipoe** [comment]
ahh thanks  @TomasAndersonvoid it works :dancer:

**Comment by saran2017** [comment]
Error: Unable to capture handshake in time on wifite (is that my external WiFi adoptor fault) give any tips to resolve this issues thank you!!
