### ISSUE TITLE
SSLStrip+ on MITMf returns an error.

### ISSUE THREAD

**Issue by Yaldo425** [offensive-security/kali-nethunter#390]
SSLStrip+ will either not work getting stuck at "[SMBserver] Config file parsed" or some error regarding the --black-ips parameter.

This error is present on the Nexus 5 and OnePlus One. Those are the only two nethunter compatible devices I had to test it with.

**Comment by binkybear** [comment]
I am not getting this error with latest build.  Here is a new apk with small gateway space fix:

https://transfer.sh/2Jd4T/nethunter-app-release.apk

Have you tried running it manually to see if encounter same error?

**Comment by Yaldo425** [comment]
I tried installing that APK and the same thing occurs, even with manually entering commands. It gets stuck at "[SMBserver] Config file parsed"

**Comment by binkybear** [comment]
I believe your error may be related to something else (maybe configuration file?).  Just to confirm what I'm seeing, I made a video:

https://vimeo.com/156642232

I haven't modified any settings but I am on kali-rolling (if it makes a difference).
