### ISSUE TITLE
HID won't work

### ISSUE THREAD

**Issue by ShaharLahav** [offensive-security/kali-nethunter#392]
Hi,  have a nexus 4 running nethunter and the HID attacks won't work.
maybe it related to an errors during the installation?
```
E:error opening /data/local/nhsystem/kali-armhf/dev/ram12
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram14
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram16
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram10
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram13
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram15
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/loop6
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram4
.
.
.
```

thanks in advance...

**Comment by binkybear** [comment]
Those errors are related to TWRP check for symlinks that don't exists.  That's a known issue with TWRP.  As far as your HID not working, double check the kernel flashed in system > about and also check android terminal to see if you have /dev/hidg0.  If both look okay then it "should" work and its possible you might just have to play with your usb settings other.

**Comment by ShaharLahav** [comment]
Hi, tanks for the quick respond.... What will those errors affect ? 
And my kernel is 3.4.0-kali-g23ba62d  and i do have the hidg0..
Also, when i click on execute is says Attack launched and immediately Attack execution ended.

**Comment by binkybear** [comment]
So things I would try:

* Different usb cable
* Enable debugging
* Disalbe mtp/enable mtp

Also try the usb keyboard app and see if you can type manually.  Having hidg0 tells me it should work.

**Comment by ShaharLahav** [comment]
The debugging fixed it, thanks.
