### ISSUE TITLE
Nexus 5x Nethunter Version 3.0.5 not detecting external wifi TL-WN722N 

### ISSUE THREAD

**Issue by m2dragon** [offensive-security/kali-nethunter#396]
Everything seems to work fine except the usb external wifi. When I run Wlan1 Monitor UP i get the "No such device":
wlan1: ERROR while getting interface flags: No such device         root@kali:/# lsusb                                                 libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Function not implemented
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:/#

Here are my the specs:
Nethunter Version:3.0.5 Built by Kali at 2016-02-02 04:42:40 pm pst
Android version 6.0.1
Kernel Version: 3.10.73-gdb8d6ec root@kali #2 Fri Dec 25 19:26:19 UTC 2015
Build Number: MMB29Q

**Comment by IvoPereira** [comment]
Possibly related?

https://github.com/offensive-security/kali-nethunter/issues/385

**Comment by m2dragon** [comment]
How can I see if the wifi drivers are installed and the firmware correctly?

**Comment by m2dragon** [comment]
Got the external wifi working with AWUS036NEH adapter. I guess TL-WN722N doesn't like the Nexus 5X or maybe its a firmware version issue. But now I am happy everything is working!
