### ISSUE TITLE
wireless monitoring issue

### ISSUE THREAD

**Issue by Saudibyte** [offensive-security/kali-nethunter#397]
Hi,
I have installed nethunter on Nexus 10
kernal 3.4.67-00092-g7b02438
My external cards:
1-TL-WN721N
2-Panda PAUO5 Model PAU05

When I run wifite, I get six question marks in front of wlan1 no matter what card I use.

when I choose the interface (by choosing 3), the list of interfaces comes back again but the name of the interface changes to wlan1mon.

And thus, the list is continuously repeating itself and wifite doesn't work.

**Comment by 0E800** [comment]
What does airmon-ng give you?

**Comment by st213497** [comment]
@0E800 
it gives:
phy         interface      Driver          Chipset
....            ......            ......                 ......
phy7       wlan1          ??????        Ralink Technology, Corp. RT5372

**Comment by 0E800** [comment]
Do you have both WiFi devices plugged? I am pretty certain that the
TL-WN721N is an atheros based chipset.

**Comment by st213497** [comment]
@0E800 
Indeed, it is atheros.
but I keep changing them for troubleshooting but i don't plug them together.
My external cards:
1-TL-WN721N (Atheros)
2-Panda PAUO5 Model PAU05 (Ralink)

**Comment by 0E800** [comment]
What does airmon-ng show when only the TL-WN721N is plugged in?

**Comment by st213497** [comment]
@0E800 
It doesnt show any thing. It doesnt even blink.
![screenshot_2016-03-07-19-38-25](https://cloud.githubusercontent.com/assets/11574287/13576111/0aaf4416-e49d-11e5-955a-701c92c3d3ba.png)
![screenshot_2016-03-07-19-38-00](https://cloud.githubusercontent.com/assets/11574287/13576112/0ab01e86-e49d-11e5-8fe8-3a97ac9bff0a.png)
![screenshot_2016-03-07-19-37-36](https://cloud.githubusercontent.com/assets/11574287/13576114/0ab391c4-e49d-11e5-91be-f25047a63217.png)
![screenshot_2016-03-07-19-33-30](https://cloud.githubusercontent.com/assets/11574287/13576113/0ab185e6-e49d-11e5-917c-76990888a47a.png)

**Comment by st213497** [comment]
@0E800  i took the screen shots for dmesg, lsusb and iwconfig

**Comment by binkybear** [comment]
@st213497  - There is a failed to get firmware for htc_9271.fw in your picture.  You seem to be missing those in /system/etc/firmware.

**Comment by st213497** [comment]
@binkybear @0e800
I confirm that by copying the firmware to /system/etc/firmware the card shows with airmon-ng and it also works with airmon and airodump however:
1- wifite still shows question marks under the driver column
2- wifite still loops in the interface choice although the name of wlan1 changes to wlan1mon when I select it
3-when I set wlan1 to monitor mode using airmon-ng start wlan1, I get the attached message.

**Comment by st213497** [comment]
![screenshot_2016-03-08-13-07-19](https://cloud.githubusercontent.com/assets/11574287/13598464/f2c51712-e52e-11e5-9885-a9a9f9a63708.png)

**Comment by binkybear** [comment]
@st213497 - Try:
```bash
sudo ifconfig wlan1 down && sudo iwconfig wlan1 mode monitor && sudo ifconfig wlan1 up
```
There has been some issues with airmon-ng recently.

**Comment by st213497** [comment]
@binkybear 
I get the attached SET error

![screenshot_2016-03-09-11-07-47 2](https://cloud.githubusercontent.com/assets/11574287/13630190/1aa232fe-e5ef-11e5-92a8-58322157cc3d.png)

**Comment by VaanaParama** [comment]
I could fix this problem easily by setting the interface directly:

Wifite -i wlan1

it worked every time :)
