### ISSUE TITLE
nexus 7 2013 lolipop can't see contents of /sdcard/captures via MTP 

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#399]
Hi, so on my nexus 7 2013 kali nethunter whenever I write files to /sdcard/captures from the Nethunter FS  (via cp, rsync or the kalimenu script)  the files are not visable on the sdcard via MTP. The only thing that works is to boot into recovery and over ADB run `chmod -R 0777 /sdcard/kali-nh`  but that only makes files already in that directory visable new files are not accessible. I tried the solutions in https://github.com/offensive-security/kali-nethunter/issues/26 but none of the solutions work other then booting into recovery. Ideally you should not have to boot into recovery everytime you want to copy over captures from nethunter.

**Comment by binkybear** [comment]
@thesle3p - Are you on the latest version of NH?  I remember running into this issue a while ago but haven't run into it lately.   I'm probably thinking of the issue you linked.

**Comment by thesle3p** [comment]
This is NH 3

**Comment by thesle3p** [comment]
Any plans to fix/look into this?

**Comment by binkybear** [comment]
@thesle3p - I haven't been able to recreate with cp command.  It's likely its related to rsync but I am not using rsync at the moment.  My guess it's retaining root permissions when it copies over which is causing sdcard to have trouble access the files/folder.  I think if I were to implement a fix I change owner/group before copying to sdcard.  

I also abandoned working kalimenu a while ago when we removed it from app, so I think the rsync issue will be limited to probably errors with that script.  Unless it happens to you at other times?

**Comment by thesle3p** [comment]
The same thing happens after a fresh flash of nethunter to files cp'd to /sdcard as well........

-----Original Message-----

**Comment by binkybear** [comment]
Was the ownership of /captures changed?

**Comment by thesle3p** [comment]
No, on my host I don't run as root so that's most likely the issue.
