### ISSUE TITLE
build.py fail during apk download

### ISSUE THREAD

**Issue by ffaggiani** [offensive-security/kali-nethunter#403]
Hi,

Just to mention that if you run python build.py it will fail with error message: 

`$"URLError = [Errno 111] Connection refused"`

The problem on the line 151 of build.py when it tries to download cSploit-nigthly and it is no longer available.

I suggest to change this line to:
`https://github.com/cSploit/android/releases/download/v1.6.5/cSploit-release.apk`

Because for now cSploit its preparing their next version cSploit 2

Regards,
Fab

**Comment by binkybear** [comment]
Thanks for posting issue.  Moved to your recommended link.
