### ISSUE TITLE
BusyBox Auto Install

### ISSUE THREAD

**Issue by matrixfox** [offensive-security/kali-nethunter#405]
Why is there a installer for BusyBox Free version? You need BusyBox before TWRP is even ran... Not to mention, I have a Pro version already installed... Now I have two versions of BusyBox. Thanks!

https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/META-INF/com/google/android/update-binary#L165

**Comment by binkybear** [comment]
> Why is there a installer for BusyBox Free version?

First, the busybox that comes with Nethunter is custom built to support commands needed by Nethunter scripts.  As far as the difference between "free" and "pro" you are referring to the busybox app in Google Play store.  That makes no difference here.

> You need BusyBox before TWRP is even ran

No, you can install TWRP without busybox.  It's flashed as a recovery img.

>  Not to mention, I have a Pro version already installed

Like I said, there is no difference between pro and free except for "auto update" and a few features in app.

> Now I have two versions of BusyBox. Thanks!

You are always free to delete our version.  Ours is probably more up to date then the "pro" version as it's built from: https://github.com/jcadduono/nethunter-installer-tools.  Either way, it doesn't really matter does it, you offered nothing constructive.

**Comment by matrixfox** [comment]
Constructive or not. Last time I did that. I got this error, with your software.

https://github.com/offensive-security/kali-nethunter/issues/205

**Comment by offensive-security** [comment]
You are welcome to change the code to suit your needs, or write your own. The joys of open-source!

**Comment by matrixfox** [comment]
Why would I contribute. This rom can't even get flashed with a kernal patch on a Nexus 5. Hangs at 40%, 70% and 90%. You guys have larger problems. Besides the point,
I don't want to muck around with BusyBox! *CLOSED*

**Comment by offensive-security** [comment]
I somehow suspect that it's not us with the lager problems :)
