### ISSUE TITLE
Kexec hardboot is not detected

### ISSUE THREAD

**Issue by kdb424** [offensive-security/kali-nethunter#407]
I requested the kexec hardboot patch forl the oneplus one and you so graciously added it. I have however made a kernel installed for the oneplus one and it is not detected unfortunately when trying to boot another rom. Has this been tested at all? Can I provide any more useful information? Thanks for all of your time.

**Comment by binkybear** [comment]
@kdb424 - It appears kexec is broken in CM13 as well as ycable.  Stand by for updated patch (unless you can find one).

**Comment by kdb424** [comment]
http://forum.xda-developers.com/oneplus-one/development/kernel-resurrected-kernel-t3212301
Can't find the commit, but I have tried that kernel on my internal CM rom and it worked for booting a second CM13 with nethunter. Hopefully you'll have better luck with search. If needed, I'll contact the dev and see if I can sort it out.

**Comment by binkybear** [comment]
@kdb424 - I just switched to CAF and all the branches reverted.  I'll make a new build on main branch and modify resurrected tomorrow since you said it was working for you.

**Comment by binkybear** [comment]
Updated.  Build a zip from this repo and give it a try whenever you have a chance.
