### ISSUE TITLE
Save me from myself! Nexus 7 mobile (tilapia)

### ISSUE THREAD

**Issue by r0n1n47r3yu** [offensive-security/kali-nethunter#408]
Sooooooo I'm new at this (sorry,sorry) after reading all the things and trying for four days to install NetHunter to my Nexus 7 ( 2012 mobile, tilapia, w/ no sim card.) running 5.1.1 Lollipop using NetHunter Installer 1.2.7. fail everytime. I have the Nexus 7 2012 Lollipop ZIP (2342059e2de1d75065741743aa1072c39cdbf58a) from offensive-security.com/kali-linux-nethunter-download/ but here's the trick, during install it will not let me choose the lollipop build, it's grayed out and it will only let me install kitkat option. (I tried it anyways once didn't work out. I think it got stuck in bootloop but maybe I was just too impatient after 25mins with the Kali and dragon head flashing)
ANYWAYS! 
![nfcufxd](https://cloud.githubusercontent.com/assets/17817377/13931485/e6553f84-ef79-11e5-89d6-eba05cd40589.png) I know that pic isn't 1.2.7 installer, I just pulled it from the netz.. Help me, help you, help myself! Wtf am I doing wrong?
Before you ask, unlocked and rooted with WuGfresh Nexus Root Kit. (which is awesome!)
SU... TWRP.... blah blah blah got it, did it, still failed. Or maybe....maybe I'm just an id10t, which often times seems the case.

**Comment by jcadduono** [comment]
actually all you have to do is install twrp and flash:
https://idlekernel.com/nethunter/nightly/3.0.5-20160320-0041/kernel-only/kernel-nethunter-grouper-lollipop-3.0.5-20160320-0041.zip
followed by:
https://idlekernel.com/nethunter/nightly/3.0.5-20160320-0041/chroot-full/update-nethunter-generic-armhf-kalifs-full-rolling-3.0.5-20160320-0041.zip

the new installer should make it a good bit easier, once a release happens those zips should be combined into 1.
you can find the entire nightly index here: https://idlekernel.com/nethunter/nightly/
each file should have a sha256sum separate download below it for checking

let me know how it goes

**Comment by r0n1n47r3yu** [comment]
Copy that, will sitrep success or failure, thanks for the reply.

**Comment by r0n1n47r3yu** [comment]
Worked!

For anyone else this is what I did.
Opened wugfresh Nexus Root Toolkit
Clicked on Launch under Advanced Utilities
Over on the bottom right is a section Flash  Zips [Rom/Gapps...
![screenshot 2](https://cloud.githubusercontent.com/assets/17817377/13939700/c65807dc-efad-11e5-8cc3-350edb30ff85.png)

Just add one Zip at a time! I tried both the first time and it failed maybe it won't for you idk.
![screenshot 3](https://cloud.githubusercontent.com/assets/17817377/13939785/623f0696-efae-11e5-89bb-2c6b31e56dab.png)

If you need more than that I'll be happy to help you. 
Thank you @jcadduono for your help!
Fixed #408
