### ISSUE TITLE
Kali Nethunter 3.0 - Nexus 6 - Multirom - Aroma freezing on install

### ISSUE THREAD

**Issue by 3xpl01t** [offensive-security/kali-nethunter#409]
Motorola Nexus 6 - Latest 6.0.1
Rooted (SuperSU) - Busy Box (latest) - TWRP (Multirom edition-latest)  - Multirom (CM13 installed as secondary)

Unable to flash nethunter to secondary ROM being CM13.
Aroma launcher starts but freezes either in setup menu or during installation.
Never finishes.
Made 20+ attempts.
Also attempted to install via Aroma-Free installer - still no luck - does not install correctly.

Any suggestions?

**Comment by EricSB** [comment]
This is also happening using standard TWRP without multirom on the Nexus 6.  The installer simply freezes up at random times and never installs nethunter.  It's super annoying as I don't know of another way to install it.

**Comment by binkybear** [comment]
Have you tried building an installer from this repo.  There has been a lot of fixes since last official release.

**Comment by 3xpl01t** [comment]
Ended up getting it installed with the alternative installer.
Seems to be working fine.
Just google "kali nethunter alternative".

Any way to use the internal bluetooth rather than a usb bluetooth device??   

I heard kernals can be modified to allow this?  Any suggestions?

Many thanks
