### ISSUE TITLE
Y-cable Charging wont work in OPO android 6.0.1 CM13

### ISSUE THREAD

**Issue by 3lk3n1313** [offensive-security/kali-nethunter#414]
Hi, I installed Android 6.0.1 CM13 and nethunter nightly 3.0.5-20160326-0309 and when I want to use the service y-cable-charging, nothing happens. connect my wireless card TL-WN822N with my usb y-cable and external battery. I put on my terminal LSUSB and nothing comes on the screen, no load my opo and does not detect my wireless card. 
NetHunter is not recoigozing USB connected by OTG using external power supply through Y-cable.
What is my problem? is a kernel or driver error or service?
when I connect my wireless card with y-cable service disabled with my cable otg all goes well.

before when I was installed 5.1 cm12.1 everything worked well with my y-cable and external battery.

Any solutions, someone have the same issues?

**Comment by jcadduono** [comment]
something is up on marshmallow kernel with the y cable patch, not much i can do since i don't own the device, so waiting for someone else to come up with a fix :)

**Comment by binkybear** [comment]
Correct, 5.1 still works but ycable patch is not working in Marshmallow.  It appears to be across all devices and possibly related to firmware loading.  ATM I'm not sure what changed to cause issue, but if you need ycable I suggest sticking with CM12.1 for now.

**Comment by JamesHagerman** [comment]
Could you please point me in the direction of the original patch for this under 12.1? Maybe I can dig into this a bit...

**Comment by binkybear** [comment]
@JamesHagerman - Original ycable patch is here for lollipop (split across a few patches): https://github.com/binkybear/AK-OnePone/commits/cm-12.1

The 100% battery should be gone now.  I'm pretty sure I uploaded the fixed kernel.  (That was me testing ycable fix)

**Comment by yesimxev** [comment]
Got OPO, CM13 android 6.0.1, Nethunter 2017.10, kernel 3.4.110, y cable. Usb drive works in it but phone doesn't charge. Is it just because of random ebay otg cable? Also TL-WN722N doesn't work but all the firmware should be good
