### ISSUE TITLE
Kali nethunter won't boot

### ISSUE THREAD

**Issue by zoudrix** [offensive-security/kali-nethunter#415]
Hey all I have installed Kali nethunter on a stock firmware and duel boot ressuruction remix then I swapped them with multi ROM both Kali and ressuruction worked and I did couple of boot to check and it's OK then suddenly when I booted again to Kali it's stuck at the logo can't boot but the other one boots normally

**Comment by bkr32** [comment]
which device?

**Comment by pyc0de** [comment]
Similar issue with Nexus 7 2013 deb + CM13
I'm getting random bootloops.

**Comment by jcadduono** [comment]
if nethunter was in primary slot and you made resurrection remix your primary then maybe RR doesn't have the multirom patch and can't boot other roms

if it's the opposite, maybe there's something wrong with multirom patch on flocm...what slot is nethunter in?

**Comment by zoudrix** [comment]
I have fixed the problem by opening multirom recovery and using an option called restorecon

**Comment by bkr32** [comment]
Wow it must be purge night thanks for closing all the old issues though @Re4son
