### ISSUE TITLE
MacChanger Crashes

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#419]
In the NetHunter app when I try and use MacChanger the app crashes and doesn't change my address. However if I enter the terminal then I can enter the command macchanger -r wlan0 and it will successfully change the mac address and display the changed address in the NetHunter app. Any Ideas?

**Comment by jcadduono** [comment]
possibly an issue fixed by:
https://github.com/offensive-security/nethunter-app/commit/b99311f1a092af2ab6e03d9088a8bd9181634359
(requires a new app build, probably in 3.0.6)

**Comment by bkr32** [comment]
mac changer works if your device is in airplane mode
