### ISSUE TITLE
Nethunter Terminal crashing

### ISSUE THREAD

**Issue by ukdude13** [offensive-security/kali-nethunter#420]
I have just installed nethunter on my Nexus 5. It all seems to be working ok, however when I try and use the custom commands nethunter terminal opens and then crashes. When I go on the app itself if I select android it opens fine but if ibselect Kali it crashes.

Could anyone offer any suggestions on how to fix this.

Thanks

**Comment by binkybear** [comment]
Can you confirm that you have busybox installed and is in the path.  Also, that your chroot is in /data/local/nhsystem/kali-armhf (check if it has files).

**Comment by ukdude13** [comment]
Yes there are folders in the /data/local/nhsystem/kali-armhf folder.

Busybox is installed but how do I check it is in the path?

**Comment by binkybear** [comment]
Just type busybox in android terminal (also check which version you have).  Also check to make sure you have root by typing su in android terminal.

If you have adb installed you can try getting a logcat and capturing the error to see whats really happening.

**Comment by ukdude13** [comment]
Yes both of them work. Busybox is version 1.24.1

**Comment by binkybear** [comment]
Double check that you can boot into chroot.  From android terminal as root, type "bootkali".

If that works then you can also try reinstalling terminal apk:

https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/Term-nh.apk

**Comment by ukdude13** [comment]
It says "chroot: can't execute 'bin/bash': no such file or directory"

**Comment by binkybear** [comment]
So thats the issue that the app is encountering.  You appear to have a bad chroot install (or at least bash is missing from chroot).  

You can try deleting chroot from app in chroot manager, then redownload from app.  That would probably be the easiest thing.

**Comment by ukdude13** [comment]
The that worked, I'm new to this so it probably Lt seemed like stupid questions.  Thank you for your help!

**Comment by binkybear** [comment]
Not a stupid question, the error doesn't give you any information.  I just happened to have seen something similar once before.  Glad it worked!

**Comment by GabrielTK** [comment]
@binkybear Having the same issue, but bootkali isn't in the PATH. What should I do??

**Comment by binkybear** [comment]
I'm not reopening the issue as this issue was solved but latest nethunter and terminal app.  If you are having issues with terminal and nethunter app you can try downloaded latest versions and flashing those instead.

build.nethunter.com has the latest nightlies which might be a bit more stable for the Nexus 9 (marshmallow).

**Comment by tptarun** [comment]
Having same problem. I have rooted my phone edit KingRoot. what to do ??

**Comment by jmingov** [comment]
Solution was provided  time ago, open a new issue if you think there's really a problem.
