### ISSUE TITLE
The wiki instructions have gone a bit wonky.

### ISSUE THREAD

**Issue by lavanoid** [offensive-security/kali-nethunter#422]
The images/screenshots are missing in https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

**Comment by jcadduono** [comment]
GitHub has been throwing 404s out a lot lately, they will probably show up with F5 or so. They show for me right now.

**Comment by binkybear** [comment]
Appears to be working fine on my end.

**Comment by lavanoid** [comment]
Silly Github x3
