### ISSUE TITLE
error launching intent install android terminal 

### ISSUE THREAD

**Issue by missym-pt** [offensive-security/kali-nethunter#424]
HI
I get "error launching intent install android terminal" on Nexus 5 running 6.0.1.

Im using nethunter terminal and already tried updating (https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer/update/data/app) and removed resize from busybox. Nothing solves. Please help.

**Comment by binkybear** [comment]
Open up android su terminal.  Type bootkali.  If you get a missing anything reinstall chroot.

If you get a different error please post error here.

**Comment by missym-pt** [comment]
I had already tried that to and i've tested it again. I get no errors when i use the terminal. I even tried to let it open in background but nethunter doesn't detect it.

**Comment by binkybear** [comment]
So you can boot into chroot fine?

Since it is an intent error I would suggest removing Terminal app and Nethunter Terminal app again and reinstalling from the link you provided.  When Terminal-nh.apk is installed it registers an intent so Nethunter can pass commands to the terminal.  

So all I can recommend is reinstalling Nethunter app and Terminal-nh (maybe removing other terminal).  If you are familiar with adb maybe a logcat might help but I can't guarantee it will say more then what you already seeing.

**Comment by missym-pt** [comment]
I unistalled the app and rebooted the Phone with the intent of reinstalling, but when it rebooted the app was still there. Tested it and everything work fine.
Its solved.

Thank you

**Comment by cyba3r** [comment]
Same issue here. Booting into chroot works fine. Tried a couple of times to install/uninstall without success. Saw that there was an update of the Terms 10 days before, may be there is something broken?

**Comment by mAfnanm** [comment]
I was type bootkali command in nethunter but it's say /bin/bash permission denied...
What to do...

**Comment by badboyhacker** [comment]
No No No
You must when launch the terminal 
Frist: type "su" grant the terminal for root request
second you se the # instead $ in terminal
type "bootkali"

**Comment by ASHERH4X** [comment]
Little late to the party here.

Specs:
- Nexus 6P
- Android version 8.1.0
- LineageOS Version 15.1-20190419-NIGHTLY-angler
- ADB and App root access enabled (addonsu applied)
- Busybox 

screenrecord vid: (private link, not public):
https://youtu.be/N0SMoKJeEBA

Thinking this may just be a Lineage OS issue for me?  But I wanted to start here first....

Thanks.
