### ISSUE TITLE
nethunter + nova launcher

### ISSUE THREAD

**Issue by missym-pt** [offensive-security/kali-nethunter#425]
Hi

I wanted to install nova launcher to remove google now bar but Im concernd it may affect the system stability (nexus 5 6.0.1) i had some troubles and just got everything running on the 3rd time (battery stats at 4000% after installing nethunter - already solved). Can anyone tell me if its OK? Can i install nova launcher?
Thank you

**Comment by jcadduono** [comment]
Nova Launcher should not affect any of the NetHunter utilities in any way. There shouldn't be any issues, unless Nova Launcher has its own issues with your ROM's framework.
