### ISSUE TITLE
Nexus 5X, CM13, Nethunter, Camera not working

### ISSUE THREAD

**Issue by TAz00** [offensive-security/kali-nethunter#431]
Hi,
I'm just trying out the "latest" build of Nethunter on my 5X, everything besides the camera seems to work. Be it bluetooth, wifi or w/e.

The camera app opens, but screen stays completely black. I should mention that it works fine in CM13

Cm13 : https://download.cyanogenmod.org/get/jenkins/158071/cm-13.0-20160413-NIGHTLY-bullhead.zip
Kernel : https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/kernel-only/kernel-nethunter-bullhead-marshmallow-3.0.5-20160410-1617.zip
Chroot Full : https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/chroot-full/nethunter-generic-armhf-kalifs-full-rolling-3.0.5-20160410-1617.zip

Updated supersu to 2.71, no change.

Tried flashing vendor.img from the official rom, https://dl.google.com/dl/android/aosp/bullhead-mhc19q-factory-22ba5e5a.tgz camera is still black. 

Tried whiping the camera app cache and data, still black.

Any ideas? stable builds? I know bullhead support is rather experimental, but if anyone has any info they can share, that would be greatly appreciated.

**Comment by TAz00** [comment]
Got nethunter and camera to work.

Flashed to stock
Rooted
Flashed CM13 + Gapps
Booted and ran setup.
Boot to recovery and flashed Net Hunter Chroot Full.
Did not flash kernel.
Reboot

Camera + Nethunter \0/

**Comment by jcadduono** [comment]
Look at the version table on the wiki, bullhead builds are for stock 6.0.1 not CM 13.0. It is possible that updating the bullhead kernel to CyanogenMod's sources may result in it working on both I suppose, should we have the time...or if somebody else willing to do it! Community driven project and all. ;)

The chroot zips work on nearly all Android phones, but you will not have access to any of NetHunter's pentesting features without flashing a NetHunter kernel.

**Comment by TAz00** [comment]
Hi, you're entirely right, nothing actually works pentesting wise.

So now I've flashed to stock using NRT 'flash to stock' together with 6.0.1-mhc19q
https://dl.google.com/dl/android/aosp/bullhead-mhc19q-factory-22ba5e5a.tgz 

Flashed generic full chroot
https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/chroot-full/nethunter-generic-armhf-kalifs-full-rolling-3.0.5-20160410-1617.zip

Then rooted and flashed with supersu 2.67 and twrp-3.0.2.0-bullhead.

Flashed bullhead update
https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/update-nethunter-bullhead-marshmallow-3.0.5-20160410-1617.zip

Flashed Kernel
https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/kernel-only/kernel-nethunter-bullhead-marshmallow-3.0.5-20160410-1617.zip

And the camera is black again.

**Comment by jcadduono** [comment]
why are you flashing so many things lol

all it takes is kernel and chroot zip flashed from twrp for the entire installation!
(you don't even need root)

but ok, if you can find time to join #nethunter on freenode IRC i can look at updating bullhead for you

**Comment by binkybear** [comment]
Issue should now be fixed.  Tested and working on ASOP but unsure on CM (should work).
