### ISSUE TITLE
OnePone-cm-13.0 kernel

### ISSUE THREAD

**Issue by iangzy** [offensive-security/kali-nethunter#432]
This is how to return a responsibility ？ 

 HZFILE  kernel/hz.bc
  BC      kernel/timeconst.h
/bin/sh: 1: bc: not found
/root/arm-stuff/kali-nethunter/AK-OnePone-cm-13.0-caf/kernel/Makefile:137: recipe for target 'kernel/timeconst.h' failed
make[1]: *** [kernel/timeconst.h] Error 127
Makefile:950: recipe for target 'kernel' failed
make: *** [kernel] Error 2

**Comment by jcadduono** [comment]
if you need help building a kernel, talk to #cyanogenmod-dev or #android-root on webchat.freenode.net
