### ISSUE TITLE
Nexus 6P Marshmallow External Wifi Cards

### ISSUE THREAD

**Issue by prairie-guy** [offensive-security/kali-nethunter#435]
I have installed NetHunter (Angler 6.0.1, Marshmallow) on Nexux 6P. Most everything works as expected. (Super job!.Very impressive.)

The problem is with external wifi cards. I have tested multiple wifi cards (AWUA036H, WSB54GC, etc), which work as expected with Kail on other distributions. Unfortunately, none of these wifi cards works on Nexus 6P. When I review dmesg, the USB Adapter is recognized, but no new network interface is created.

 For example, with Linksys card the last output is:
Product: Compact wireless-G USB Adapter 
Manufacturer: Cisco-Linksys
(But no firmware, mac-address or network interface is mentioned.)

I am using an Apple USB-C to USB Adaptor. I suspect that the USB-C is the issue, perhaps related to power.

On the other hand, when I use a USB-C to Ethernet Adaptor, dmesg reports both a USB device and all of the expected network interfaces (eth0).

**Comment by prairie-guy** [comment]
I have installed NetHunter (Angler 6.0.1, Marshmallow) on Nexux 6P. Most everything works as expected. (Super job!.Very impressive.) 

The problem is with external wifi cards. I have tested multiple wifi cards (AWUA036H, WSB54GC, etc), which work as expected with Kail on other distributions. Unfortunately, none of these wifi cards works on Nexus 6P. When I review dmesg, the USB Adapter is recognized, but no new network interface is created. For example, with Linksys card the last output is:

Product: Compact wireless-G USB Adapter 
Manufacturer: Cisco-Linksys
(But no firmware, mac-address or network interface is mentioned.)
 
I am using an Apple USB-C to USB Adaptor. I suspect that the USB-C is the issue, perhaps related to power. 

On the other hand, when I use a USB-C to Ethernet Adaptor, dmesg reports both a USB device and all of the expected network interfaces (eth0).

**Comment by TomasAndersonvoid** [comment]
I am using the same device, no problem here. If you go through NetHunter-->Custom Commands at left menu. plug in your external wifi card and run Wlan1 Monitor Mode script, you may see the led on your wifi card on and off like crazy. Then do whatever you want, I suggest run Launch Wifite script to test if the external wifi card works or not.

**Comment by prairie-guy** [comment]
Thanks Tom! 

Just checking that you are using the 6P vs. 6.

Also, I am using the 'shamu' image. (I couldn't find one for 'angler') Not sure if this is a problem.

Can you confirm what image of NetHunter you are using on your Nexus 6P?

When I looked at Custom Commands, there was no 'Wlan1 Monitor Mode' script (with wifi card installed or not). I did see the Update script, which I tried. I ended up getting an error indicating related to 'ldconfig' not being found. Trying to fix that left we with 'postgresql-9.4' broken.

I am going to go back into Recovery Mode and Reinstall. . .

Can you confirm what image of NetHunter you are using on your Nexus 6P.

Many thanks.

**Comment by binkybear** [comment]
@prairie-guy - If you are using 6P and you flash "shamu" image its going to try to install the Nexus 6 kernel (which it probably didn't because it noticed the wrong version).  You need to use angler kernel.  It was not officially supported when 3.0 was released but test versions were made.

You should build it from this repo or download from @jcadduono:

https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/kernel-only/kernel-nethunter-angler-marshmallow-3.0.5-20160410-1617.zip

Otherwise, you will not get external wifi or hid.

**Comment by prairie-guy** [comment]
Thanks! I was thinking that might have been it. When I looked back at the image, I did notice it was 'shame', but couldn't find the 'angler' version. I will give this a try. Very helpful feedback.

**Comment by prairie-guy** [comment]
Ok, so I've been using Nethunter Rootlkit Installer. So should I reflash with 'nethunter-shamu-marshmallow-3.0.zip' and then flash 'kernel-nethunter-acgler-marshmallow-3.05' afterwards? (I couldn't find 'net hunter-angler-marshmallow-3.05.zip)

**Comment by jcadduono** [comment]
assuming you have twrp, all you have to do is flash kernel-nethunter-angler zip and boot up

**Comment by prairie-guy** [comment]
Ok, but I wiped out net hunter. . . So I was going to add that back (with 'samu'). And then flash the kernel-nethunter-angler afterwards.

**Comment by TomasAndersonvoid** [comment]
I am using nexus 6P. I believe it is kernel version's problem. I am using
angler version of nethunter.

**Comment by prairie-guy** [comment]
Do you have the image: nethunter-angler-marshmallow-3.0.zip?

**Comment by TomasAndersonvoid** [comment]
Yep

**Comment by prairie-guy** [comment]
I it available for me to download?

**Comment by TomasAndersonvoid** [comment]
Oh I deleted after install, you can create by using command shows on github

**Comment by TomasAndersonvoid** [comment]
No, I dont think so. I deleted it after install. if you git clone the repo
to local machine and cd in to nethunter-installer. Run command python
build.py -d angler --marshmallow then you will get the zip you need.

I it available for me to download?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/435#issuecomment-211076226>

**Comment by TomasAndersonvoid** [comment]
https://idlekernel.com/nethunter/nightly/3.0.5-20160410-1617/kernel-only/kernel-nethunter-angler-marshmallow-3.0.5-20160410-1617.zip
here is the link provided by binky it is same to the zip file you create
youself. Do not use shamu because it is for nexus6 not 6p. If you have twrp
just choose install the zip provided above. Try to play with it, its
midnight here need some sleep.

**Comment by prairie-guy** [comment]
Thanks Tom. I built it and need to try flashing it. Out of curiosity, what is the default size used for the chroot? Get some sleep. Bryan

**Comment by jcadduono** [comment]
The full (default) chroot should occupy about 2.3 GB when extracted.

**Comment by prairie-guy** [comment]
Many thanks to all! I have Nexus 6P with a working marshmallow kernel able to connect to an external wifi card. For the benefit of others, here is a summary of what I did:

I was able to build nethunter for Nexus 6P based on instructions found here:
https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter

root@kali:~# git clone https://github.com/offensive-security/kali-nethunter
root@kali:~# cd kali-nethunter/nethunter-installer
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d angler --marshmallow

I then transfered to Nexus 6P with: 
adb push -p update-nethunter-angler-marshmallow-20160417_153111.zip /sdcard/update-nethunter-angler-marshmallow-20160417_153111.zip 

Finally, I rebooted into recovery mode (twrp) and installed the angler-marshallow zip file.(Be sure to enter password if required. Otherwise, /sdcard mount is unavailable. 

Again, appreciate everyone's help.

**Comment by jcadduono** [comment]
You can probably save yourself an immense amount of space using --depth 1 if only using the git repo to build. We've got a lot of binary history... :)
(otherwise just download from my nightly mirror as mentioned earlier!)

Glad it's working out for you.

**Comment by anietie** [comment]
Thanks guys. Was able to get nethunter running on my Nexus 6p (Huawei) as suggested by prairie-guy.

**Comment by DarkBlueShark** [comment]
Hello guys sorry for asking this stupid question but if I follow prairie-guys instructions and flash the angler marshmallow zip file created or downloaded (~11mb) will nethunter be installed already? Or do I have to flash more zips?

**Comment by prairie-guy** [comment]
Yes, that should do it. You will want to do an 'apt-get update & apt-get upgrade'. Also, I have been wanting a larger chroot,  if you want the full size chroot, add '-fs full'  to the build script. See: https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter

**Comment by DarkBlueShark** [comment]
Thank you very much for the fast answer and for your help! I'll try it out today. Thx have a good day!

**Comment by gooldennn** [comment]
Hi guys.
I've fully installed nethunter on my Huawei Nexus 6p. But when I'm using usb-c to usb-c adapter and connecting my awus036h its not working. 
Could you tell me what kind of wireless adapter you got this working with?

**Comment by gooldennn** [comment]
Got it working now :)

**Comment by mikeman0120** [comment]
Hi.  I've tried using the command 'python build.py -d angler --marshmallow' and get the error, "Device angler not found in devices/devices.cfg".  Does anybody know what went wrong?  I have a nexus 6p mmb29m and the computer I ran this command on has a pre-sana version of Kali on it.

**Comment by mikeman0120** [comment]
Nevermind...I'm a dummy.  Didn't do './bootstrap'.  By the way, did anyone do the experimental device branch?

**Comment by jcadduono** [comment]
atm experimental branch is only devices i've been working on that are either very unstable or don't currently boot and need more work on patches to boot properly
it is rebased on top of master once in a while, and master should always contain the latest for already stable devices

**Comment by mikeman0120** [comment]
OK thanks

**Comment by mikeman0120** [comment]
After flashing nethunter over 6.0.1 build number mmb29m it forces closes when I try to open Kali from nethunter terminal.  Android and Android su both worked though.  I didn't have busy box or terminal emulator installed before flashing.  I looked under /system/xbin for the bootkali command but didn't see it.  I didn't notice any errors during flashing.  Am I missing something obvious?

**Comment by jcadduono** [comment]
Sounds like you didn't install a rootfs so just open the nethunter app and download it, alternatively make zip with --rootfs full

**Comment by mikeman0120** [comment]
Thanks for the quick replies.  It did say it found the kali chroot directory and that it was installed.  Just for the heck of it I restored my stock and tried again.  This time I let the nethunter zip install super su.  I don't think that made any difference, but when I opened the nethunter app, it kind of glitched out after giving it permissions.  I reopened it and everything works.  Maybe that's what it was doing the first time.

**Comment by Dr0me** [comment]
@prairie-guy @binkybear @jcadduono 
I am trying to install from windows, I followed the directions here 
 https://github.com/offensive-security/kali-nethunter/wiki/Windows-install

and when I flash angler 3.1.0 from here https://idlekernel.com/nethunter/nightly/3.1.0-20160816-0223/

I get some script running, and then nothing but what seems to be a normal startup.  I dont get the install screen and options like I have seen on tutorials.  After flashing nethunter and rebooting, I do, however, get an error with SuperSU that says update binary, and I cannot update it (binary was fine before).  It sent me into a boot loop when I went to TWRP and did a restore.  I have since performed a factory reset, rooted, rerooted, flashed, and still nothing, not even the install graphic for nethunter comes up.  Could it be that the file is bad?  I am beginner, so hand holding may be appreciated.

**Comment by h00die** [comment]
I've been trying the custom build 6p as well.
Following the directions, I can oemUnlock, stockFlash fine.  twrp loads fine, looks like superSU loads fine.
However, when I restart after nethunter, I don't have the nethunter app.
Logs:
```
root@k:/root/nethunter-LRT# ./twrpFlash.sh
NETHUNTER LINUX FLASH (TWRP, SuperSU and Kali Nethunter)

CHECKING PRE-REQUISITES

Checking if adb is installed
adb FOUND
Checking if adb is installed DONE

Checking if fastboot is installed
fastboot FOUND
Checking if fastboot is installed DONE

Adb connection check
ADB device detected.
Adb connection check DONE

Checking TWRP image existence
Dir twrpImage/ has files
Checking TWRP image existence DONE

Checking SuperSu existence
Dir superSu/ has files
Checking SuperSu existence DONE

Checking Kali Nethunter zip existence
Dir kaliNethunter/ has files
Checking Kali Nethunter zip existence DONE

CHECKING PRE-REQUISITES DONE

Sending Kali Nethunter zip to the device
Transferring: 81306506/81306506 (100%)
6653 KB/s (81306506 bytes in 11.934s)
Sending Kali Nethunter zip to the device DONE

Sending SuperSu zip to the device
Transferring: 4288330/4288330 (100%)
6275 KB/s (4288330 bytes in 0.667s)
Sending SuperSu zip to the device DONE

Rebooting into bootloader
Rebooting into bootloader DONE

Flashing TWRP image
target reported max download size of 494927872 bytes
sending 'recovery' (16932 KB)...
OKAY [  0.450s]
writing 'recovery'...
OKAY [  0.253s]
finished. total time: 0.703s
Flashing TWRP image DONE

Booting into TWRP (20 secs dont worry)
downloading 'boot.img'...
OKAY [  0.444s]
booting...
OKAY [  0.679s]
finished. total time: 1.124s
Booting into TWRP DONE

Installing SuperSU
Installing zip file '/sdcard/supersu.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found

*****************
SuperSU installer
*****************
- Mounting /system, /data and rootfs
- Extracting files
- Detecting system compatibility
- System-less mode, boot image support required
- Creating image
- Mounting image
- Creating paths
- Removing old files
- Placing files

******************
Boot image patcher
******************
- Finding boot image
--- Boot image: /dev/block/mmcblk0p34
- Extracting ramdisk
- Decompressing ramdisk
- Checking patch status
- Creating backup
- Patching sepolicy
- Patching daemon launcher
- Patching init.*.rc, fstabs, file_contexts, dm-verity
- Compressing ramdisk
- Creating boot image
- Flashing boot image

*************************
    IMPORTANT NOTICES
*************************
If TWRP offers to install
SuperSU, do *NOT* let it!
*************************
First reboot may take a
few minutes. It can also
loop a few times. Do not
interrupt the process!
*************************

- Unmounting /system
- Done !
Done processing script file
Installing SuperSU DONE!

Installing Kali Linux Nethunter
Installing zip file '/sdcard/kaliNethunter.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
####################################################                                                                                                                                                                                                           ####  88      a8P         db        88        88  ####  88                                                                                                                                                                 .88'         d88b       88        88  ####  88   88'          d8''8b      88                                                                                                                                                                     88  ####  88 d88           d8'  '8b     88        88  ####  8888'88.                                                                                                                                                                     d8YaaaaY8b    88        88  ####  88P   Y8b      d8''''''''8b   88        88  ##                                                                                                                                                             ##  88     '88.   d8'        '8b  88        88  ####  88       Y8b d8'                                                                                                                                                                       '8b 888888888 88  ####                                              ######  ####                                                                                                                                                             ######### NetHunter ####################@Unpacking the installer, this may take                                                                                                                                                              a while...@Starting the install process@Installing busybox applets to /sbin@Chec                                                                                                                                                             king for previous versions of NetHunterExtracting SuperSU zip...- Installing Sup                                                                                                                                                             erSU in automatic mode
*****************
SuperSU installer
*****************
- Mounting /system, /data and rootfs
- Extracting files
- Detecting system compatibility
- System-less mode, boot image support required
- Creating image
- Mounting image
- Creating paths
- Removing old files
- Placing files

******************
Boot image patcher
******************
- Finding boot image
--- Boot image: /dev/block/mmcblk0p34
- Extracting ramdisk
- Decompressing ramdisk
- Checking patch status
--- Already patched, attempting to find stock backup
--- Stock backup restored
- Extracting ramdisk
- Decompressing ramdisk
- Checking patch status
- Patching sepolicy
- Adding daemon launcher
- Adding init script
- Creating mount point
- Patching init.*.rc, fstabs, file_contexts, dm-verity
- Creating ramdisk backup
- Compressing ramdisk
- Creating boot image
- Flashing boot image

*************************
    IMPORTANT NOTICES
*************************
First reboot may take a
few minutes. It can also
loop a few times. Do not
interrupt the process!
*************************

- Unmounting /system
- Done !
@Installing AppsInstalling NetHunter AppInstalling NetHunter TerminalInstalling                                                                                                                                                              NetHunter VNCInstalling cSploitInstalling OpenVPNInstalling Hacker's KeyboardIns                                                                                                                                                             talling RF AnalyzerInstalling ShodanInstalling USB KeyboardInstalling Router Key                                                                                                                                                             genInstalling DriveDroidFreeing up some space on /system@Running busybox install                                                                                                                                                             er...- Installing busybox...- /system/xbin/busybox not found! Symlinking...@Inst                                                                                                                                                             alling NetHunter wallpaper- Found screen resolution: 1440x2560- No wallpaper fou                                                                                                                                                             nd for your screen resolution. Skipping...@Installing NetHunter boot animationCo                                                                                                                                                             pying nano highlights to /system/etc/nanoCopying terminfo files to /system/etc/t                                                                                                                                                             erminfoCopying 32-bit shared libraries to /system/libInstalling /system/bin bina                                                                                                                                                             riesInstalling init.d scripts@Symlinking Kali boot scripts@Running kernel instal                                                                                                                                                             ler...##################################################            NetHunter Ke                                                                                                                                                             rnel Installer   Kernel: NetHunter kernel  Version: 2.1   Author: Binkybear#####                                                                                                                                                             #############################################Checking device compatibility...Ins                                                                                                                                                             talling busybox applets to /sbinFreeing up some space on /systemCopying firmware                                                                                                                                                              to /system/etc/firmwareCopying 32-bit shared libraries to /system/libInstalling                                                                                                                                                              /system/xbin binariesRunning boot image patcher...- Found boot partition at: /d                                                                                                                                                             ev/block/mmcblk0p34- Dumping & unpacking original boot image...- Detected ramdis                                                                                                                                                             k compression format: gzip- Running ramdisk patching scripts...- Executing: 01-r                                                                                                                                                             amdisk-patch-- Patching the ramdisk for NetHunter & init.d...- Executing: 02-sup                                                                                                                                                             ersu-- Patching the sepolicy for SuperSU...- Executing: 03-no-verity-opt-encrypt                                                                                                                                                             -- Disabling dm-verity & forced encryption...-- Found fstab: fstab.angler- Build                                                                                                                                                             ing new ramdisk...- Found replacement kernel Image.gz!- Found replacement ramdis                                                                                                                                                             k image!- Found replacement device tree image!- Backing up original boot image t                                                                                                                                                             o /data/local/boot-backup.img...- Writing new boot image to memory...Boot image                                                                                                                                                              patching complete@Running Kali chroot installer...- No Kali rootfs archive found                                                                                                                                                             . Skipping...*************************************************       Kali NetHun                                                                                                                                                             ter is now installed!       **   Don't forget to start the NetHunter app    **                                                                                                                                                                    to finish setting everything up!       ************************************                                                                                                                                                             *************Done processing script file
Installing Kali Linux Nethunter DONE!
Rebooting into Kali Linux Nethunter
Everything is installed. Phone should be booting up! Enjoy
```
I tried `./build.py -d angler -m` as well as `--rootfs full` with the same results.  Any ideas on why the last step gives no errors that I can see, but doesn't actually work?

**Comment by rajeevnaik1** [comment]
Pls can say step by step to install nethunter on Nexus 6p and with link.kernel for nethunter and which is the best of cable to connect the wifi card with otg cable and wifi card pls help me. I tried and tried 15 time with different Android . But I am not able to get wifi like airmon-ng and wifie now I am using nougat 7.0.pls make step by step install and link download. Pls help.

**Comment by rajeevnaik1** [comment]
It should be new now the date is 17/10/2016.  Make a new 
Video  r make step by step process with download link pls.  Provide the otg cable which I need to buy.pls I am getting mad.

**Comment by h00die** [comment]
googled and found this, looks like everything you are asking for 6p on marshmallow w/ amazon links

**Comment by rajeevnaik1** [comment]
i tried to install nethunter on nexus 6p but i don't got install i am getting error and sum phone hang on force safe mode and sum time all tools work and wifi card problem  pls help. i have google search but i triend but now result.i am using  marshmallow MMB29Q image. pls help me any one . i need link r step by step installation. thank u.

**Comment by h00die** [comment]
Posting error messages or logs or the steps you followed would help more and get the answers you seek. 
You asked for a step by step with Amazon link to cable, I provided that.

**Comment by rajeevnaik1** [comment]
I installed nethunter on Android marshmallow 6.1 I have problem with wifi card pls help me.i flashed kernel 3.15.2 and update nethunter 3.15.2.thank what is the meaning of Amazon link

**Comment by rajeevnaik1** [comment]
I am using Android image MMB29Q

**Comment by stants225** [comment]
Hi, I know I'm late, but I was wondering if I would need anything elsefor nethunter to work: I have already rooted my Nexus 6p android 6, and built the nethunter repository for it. I am also getting a WiFi adapter soon. Do I just need to send myself the .zip then flash it with two, or do I have to adb push it? Also is there anything else I need to do?

**Comment by stants225** [comment]
*with twrp

**Comment by DarkBlueShark** [comment]
Hey stants225 no you just have to copy the .zip to your phone and then flash with twrp that's it. You don't need to push it.

**Comment by stants225** [comment]
Thanks darkblueshark, I've got it working now! One thing, what external wifi device would you personally recommend for the 6p?

**Comment by DarkBlueShark** [comment]
I have the Nexus 6p as well you probably know already cause I commented month ago. I use TL-WN722N it's from tp link and working with Linux and Kali very good for years now. This model is even recommended by many people but I think youve already seen it on the web. It's an old model like 5 years old but very good for packet capturing and injection got for that one:P

**Comment by DarkBlueShark** [comment]
go*

**Comment by stants225** [comment]
Thanks for the help!

**Comment by DarkBlueShark** [comment]
You're welcome have fun!(:

**Comment by anietie** [comment]
Guys I need your help. I downloaded this file nethunter-generic-armhf-kalifs-full-rolling-3.15.2-20161024-2241.zip from  the nightly builds and used TWRP to flash it on my Nexus 6p. The issue is this. My phone sees my WIFI card TL-WN722N when I run lsusb but the card never comes on. It doesn't blink when plugged it. 

What must I do to get it to work?

Any leads?

Anietie James

**Comment by Dr0me** [comment]
how did you get your kernel to recognize the usb as a potential wifi port?


________________________________

**Comment by stants225** [comment]
Does anyone mind telling me what adapter they used for the usb to usb c? I dont want to get the wrong one :/

**Comment by h00die** [comment]
I think my hot link before must not have come through. Googled and found http://rageweb.info/2016/09/10/kali-nethunter-nexus-6p-install/
Looks to have links to adapter and cable and I guess worked. Maybe your best bet

**Comment by rajeevnaik1** [comment]
Please make video on how to install net hunter on Nexus 6p r please give a reply .I have install net hunter on Nexus 6p.i rooted my Nexus 6p and I installed the net hunter zip 3.15.3 and kernel angler on marshmallow 6.0.1 image 
MTC20F. I am not able get wifite r airmon-ng.i use 4 wifi cards tplink227, Alfa awsu0360,.. but it is not working please help me . Can pls give me step by step process to install net hunter with neat steps and factory image also pls.thank for u email and please provided a link to buy a other cable correct.i buy 4 to otg cable to connect wifi card . please help me 

https://build.nethunter.com/nightly/3.15.3-20161221-0941/

**Comment by DarkBlueShark** [comment]
Hello rajeevnaik1 as you and many have requested i can make a youtube tutorial on how to install net hunter on the nexus 6p greetings DarkBlueShark

**Comment by rajeevnaik1** [comment]
good but do on nought 7.1.1

**Comment by rajeevnaik1** [comment]
I have install net hunter on Nexus 6p.i rooted my Nexus 6p and I installed the net hunter zip 3.15.4 and kernel angler on marshmallow 6.0.1 image
MTC20F. I am able to get wifite r airmon-ng.i use 4 wifi cards tplink227, Alfa awsu0360, working .Hope u enjoy by installing nethunter 3.15.4 on Nexus 6p. It is working all Kali tool on Nexus .Thank bye.
https://build.nethunter.com/nightly/. 
Can any one make pls make a kernal for nougat 3.15.4.

**Comment by EightieOG** [comment]
Hi guys, I am totally new to this and am in way over my head. I have what I believe is a Nexus 6 running Nethunter, android version 6.0.1 kernal version 3.10.40-g15269a3-dirty root@kali #3 Build number MMB29S.. Basesband version MDM9625_104662.22.05.32R. I bought a TP Link Tw722N wireless adapter and an edimax N150 7611 ULB I believe because it has wifi/bluetooth capabilities. So far I can't get either one to work on my device. I don't know if its my cable I have a OTG female usb to micro usb I cant figure out how to install the driver software. I have tried ifconfig and it won't show up. Please help!

**Comment by EightieOG** [comment]
Also I can't get the RF Analyzer to work. It says HackRF source not available. I bought a book on Kali and on Nethunter but everyone skips over this part. I just need some trouble shooting help. Thanks everyone.

**Comment by akrolla** [comment]
youre using the one downloaded from kalis website, if so that is deprecated. if you are using linux please refer to this https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter

if you are on windows 
instructions are here https://github.com/offensive-security/kali-nethunter/wiki

i just started using linux to build nethunter, because with windows it gets a bit tedious and you can make mistakes easily or install the wrong kernel, or wrong software.

**Comment by akrolla** [comment]
Got otg

**Comment by EightieOG** [comment]
For the nexus 6 what build do I use? How do I know?

**Comment by Laser89** [comment]
I got temporary fix for the issues of external wifi cards not being connected or recognized & and it will fix also the camera (because mine is not working or not connected error message showing)

Before anything else you should clean install compatible .img and or nethunter .zip on your device.

1. Before installing nethunter install flashify and backup current kernel, you can save on your google drive, dropbox or use otg thumbdrive to save.
2. Now Install nethunter.
3. If you want to use your external wifi don't flashed the kernel which I told you to backup. (As is)
4. If you want to use your camera just flash the kernel which I told you to backup ;)

Hope it works on you.. coz mine is ;) 

NOTE: this is just temporary fix.. so you can get going whatever you want to do ;)

**Comment by lweingart** [comment]
Hi everyone,
I made the same mistake as a few here, which was to install the shamu nethunter on the nexus 6P, making it impossible to use a wifi dongle.
I went on and tried to build the nethunter as prairie-guy went on, but the nethunter build does not seem to work anymore. This is what I get when I try:
`$ python build.py -d angler -m -fs full
Found Hackerskeyboard.apk at: update/data/app/Hackerskeyboard.apk
Error: ('Connection aborted.', error(54, 'Connection reset by peer'))`
It would seem that one or more resource is not available anymore.

So I thought I would just reinstall everything with a nightly build, but I'm somewhat confused by the explanations here: https://github.com/offensive-security/kali-nethunter/wiki#10-supported-devices-and-roms
At point 2.0 Downloading Nethunter it says that we can download a nightly build, and right after it mentions that the kernel-nethunter-[device]-[os]-*.zip. should be flashed last.
I cannot find the update-nethunter-angler-marshmallow-something in the nightly builds...
Is there a nightly build for angler marshmallow that can be used as kaliNethunter image for the nethunter-LRT installer ?

Could anyone re-route me (or enlighten me) in the right direction? I feel stuck with my kernel-angler-mashmallow image, lacking the remaining (or the full) image.
Or else, if anyone has a link to a full angler marshmallow nethunter image for me to download, I would gladly take it.

Thanks guys for your help

**Comment by lweingart** [comment]
Hi again, after re-reading carefully the few first comments between prairie-guy and jcadduono, as I still have nethunter installed on my device, flashing the angler kernel should do the trick.
I would just need a bit of advice to do just that part, if someone has the knowledge on how to do it.

Cheers
