### ISSUE TITLE
Nethunter terminal crashes

### ISSUE THREAD

**Issue by DeAdHaCkErZ** [offensive-security/kali-nethunter#436]
I have been used nethunter on nexus 6p and it's work will but today when I try to open terminal it's crash why ? 

Iam use cm13 

And when I try to flash chroot full it's give error but before it's work will

**Comment by jcadduono** [comment]
please post recovery.log of error when flashing chroot, to get that use:
`adb pull /tmp/recovery.log`
after seeing the error
alternatively, you can go to advanced -> copy log to sd, and copy recovery.log off your internal storage or microsd card depending on where it goes

if flashing the chroot gives you an error, then that is why your terminal cannot start as you would be missing parts of the chroot
