### ISSUE TITLE
{feature request} add Proxmark3 client to Nethunter Repo, proxdroid deprecated and nonfunctional

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#437]
Hi, so after several months of experimentation and sporadic conversation with the developer I can confirm that proxdroid is no longer supported and does not work with nethunter, A better way of allowing nethunter devices to utilize a proxmark is to add the proxmark client to the nethunter Repository, however research and experimentation shows that the make file for the proxmark client will require modification compile on nethunter (http://www.proxmark.org/forum/viewtopic.php?pid=16495#p16495).

**Comment by jcadduono** [comment]
I thought that's what this was:
https://github.com/offensive-security/kali-nethunter/commit/cefdbd492fb234876418414001febc056ad23fbf

Is proxmark3 not working? (run from Android SU terminal on NetHunter 3.0.5+)

**Comment by thesle3p** [comment]
The android client for the proxmark3, proxdroid is no longer developed
and can not talk to proxmark3s with modern firmware, it also is
extremely limited in features compared to the native linux client.
Running the proxmark3 client from the chroot would be much more
efficient and flexible.
