### ISSUE TITLE
(Reguest) Can someone build for me?

### ISSUE THREAD

**Issue by pahapoika** [offensive-security/kali-nethunter#438]
Hey. 
Can someone build nethunter for my Samsung Galaxy s4 mini?
I know how to build Nethunter but sadly my computers cpus were burned cause my cpus heated up too much when i was overclocking them.(fail)
And my laptop is MacBook so...

But if someone could be so nice and build Nethunter for me:
Rom cyanogenmod 13
Kernel: original 3.4.0
Device: Samsung Galaxy s4 mini (gt-I9195)

Thank you!

**Comment by jcadduono** [comment]
i don't have any plans to add support for old lower-mid range devices and it would be best to focus our work on newer devices that have the power to take advantage of all of nethunter's functions.
your device is very limited for space and memory.
you should still be able to follow the guide on porting nethunter to your device. while it's possible to compile the linux kernel on a mac, it's easier just to do it in a VM using virtualbox.

start here: https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter

**Comment by pahapoika** [comment]
I will just use it as 24/7 Wi-Fi cracker.
I have Samsung Galaxy s7 edge as my primary.

Oh u can run Linux on macbook. I didnt remember.
