### ISSUE TITLE
Social-Engineer Toolkit not included in Nethunter

### ISSUE THREAD

**Issue by m2dragon** [offensive-security/kali-nethunter#439]
I have a Nexus 5x running Nethunter, i noticed that it does not have the utility setoolkit pre installed. Any instructions on how to install it?

**Comment by TomasAndersonvoid** [comment]
go terminal apt-get update then apt-get install kali-linux-all the apt-get upgrade. you will have all you want

**Comment by binkybear** [comment]
Not reall an issue but it's pretty easy to do in kali terminal:
```bash
apt-get update
apt-get install set
setoolkit
```
