### ISSUE TITLE
Nexus 9 failed to get firmware htc_9271

### ISSUE THREAD

**Issue by locustnigi** [offensive-security/kali-nethunter#441]
Ola again :)
i have the cprrect cable but it seems i have the same problem of #327 

this is my dmesg

[ 1969.475637] usb 2-1: USB disconnect, device number 3
[ 1971.864993] usb 2-1: new high-speed USB device number 4 using tegra-ehci
[ 1972.039465] usb 2-1: New USB device found, idVendor=0cf3, idProduct=9271
[ 1972.039501] usb 2-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 1972.039527] usb 2-1: Product: USB2.0 WLAN
[ 1972.039548] usb 2-1: Manufacturer: ATHEROS
[ 1972.039567] usb 2-1: SerialNumber: 12345
[ 1972.041251] usb 2-1: ath9k_htc: Firmware htc_9271.fw requested
[ 1972.050118] usb 2-1: ath9k_htc: Failed to get firmware htc_9271.fw
[ 1972.051245] usb 2-1: ath9k_htc: USB layer deinitialized

tried to follow https://forums.kali.org/showthread.php?19025-Firmware-htc_9271-fw-download-failed-USB-Wireless-Adapter-Problems but nope...

**Comment by locustnigi** [comment]
File to download in the similar ticket has been removed

**Comment by binkybear** [comment]
You appear to be missing htc_9271.fw from /system/etc/firmware.  Download (https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/boot-patcher/system/etc/firmware/htc_9271.fw) the file to your sdcard and copy to folder. Using adb or androidsu in terminal:
```
su
mount -o rw,remount,rw /system
cp /sdcard/htc_9271.fw /system/etc/firmware
```

**Comment by locustnigi** [comment]
Nope ;/ cannot remount in rw nor with cmdline nor with total commander or other tools.  Wondering whats wrong ;(

**Comment by binkybear** [comment]
You should be able to also do it in recovery also (mount your system).  If not its possible its either a busybox or supersu issue.

**Comment by locustnigi** [comment]
done in recovery. Works! Tnx! :)
