### ISSUE TITLE
Can i install nethunter on LG Nexus or Motorola Nexus ? 

### ISSUE THREAD

**Issue by Hyp3r10n** [offensive-security/kali-nethunter#444]
I don't know can i install nethunter on LG-Motorola Nexus or just phone by Google make ? please help ! I'm searching on Google for an hours but i can't figure out

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/wiki read up!

**Comment by Hyp3r10n** [comment]
I read it. But i dont know nethunter support LG,Motorola or not ? Please tell me, sorry for my bad English. Thank You

**Comment by pahapoika** [comment]
Hey @Hyp3r10n 
Theres guide>https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/README.md

its not too difficult :+1:

**Comment by Hyp3r10n** [comment]
Thank you guys !!!
