### ISSUE TITLE
(HELP) Porting kernel.

### ISSUE THREAD

**Issue by pahapoika** [offensive-security/kali-nethunter#445]
Hey. 
Im modifying kernel to my phone. i did everything that is in https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter

But when i tried make clean (https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel) command with ubuntu it didnt do anything. Just  said no rule for make clean.

So can someone kindly help me?

**Comment by tsdorgut** [comment]
You should post your makefile for further (or any) help.

**Comment by pahapoika** [comment]
@tsdorgut my computer just missed libncurses5-dev package.
