### ISSUE TITLE
i386 device architecture support - missing Kali chroot

### ISSUE THREAD

**Issue by tsdorgut** [offensive-security/kali-nethunter#446]
Output of the build attached.

![screenshot_20160427-153929](https://cloud.githubusercontent.com/assets/7632644/14852479/38ad2dfa-0c8f-11e6-9d98-4d32903696e0.jpg)

**Comment by jcadduono** [comment]
We currently don't have full support for architectures other than armhf right now.
While the installer is perfectly capable of installing to other architectures, the NetHunter app still needs support and there currently aren't any chroots built for architectures other than armhf which is the cause of your 404 error.

**Comment by tsdorgut** [comment]
Can I build my own rootfs and push it to kali servers? I would gratefully support this project. And I will definitely inspect the nethunter app for support.

**Comment by binkybear** [comment]
tsdorgut - It's not possible to push a different arch to kali servers.  You could modify the build script and push the kalifs-full.tar.xz to your /sdcard and test it out that way. For i386 but I imagine other things would need to change also as I haven't looked at different archs.  But as @jcadduono said, it could be done with enough work.

**Comment by 0E800** [comment]
I have a Lenovo Thinkpad 8. It runs on Intel Bay Trail Atom Z3770 and has 2gb memory.
If I install Android-x86 5.1 or Android-x86 5.1 - Remix OS, I should be able to install the Nethunter APKs.
I could change the sources.list to pull packages from kali i386 repo?

Think it would be great to have a i386 port of Nethunter. I don't have much experience with dev, but I will beat my head against the keyboard enough times to make it work. 

Any pointers to get me on the right direction would be awesome. 

Best regards,
