### ISSUE TITLE
Upgrade mitmf from 0.9.7 to 0.9.8

### ISSUE THREAD

**Issue by prairie-guy** [offensive-security/kali-nethunter#447]
I would like to upgrade mitmf from 0.9.7 to 0.9.8. What is the best way to do this?

1) Change Nethunter to 'rolling' distribution. (Not sure what this may break.)
2) Download from git-hub, build and install.
3) Somehow find a apt-get package for 0.9.8
4) Other . . .

Any thoughts would be welcome.

**Comment by jcadduono** [comment]
if you don't mind losing everything in your chroot (replacing it with rolling chroot), you can simply flash the newest chroot through a complete nethunter upgrade:
(don't forget to back up first!)
https://idlekernel.com/nethunter/nightly/3.0.5-20160425-1720/nethunter-generic-armhf-kalifs-full-rolling-3.0.5-20160425-1720.zip
SHA256: 75987a512084e9be0cc995e13d967a2c2a45eacc14b59b5636af1037e3574d1b

alternatively, you can use the "nethunter-fs/build.sh -f" script to build your own rolling chroot which creates a tar.xz. You can place this on your sdcard and have the nethunter app install it for you after removing your current chroot.

If you only wish to upgrade mitmf, the best option would be to do option 2 and just build mitmf yourself using your current sana libraries.

I think it would be best to replace the chroot with the rolling one though if you want to keep your installation up to date and maintain full compatibility with new app releases.

**Comment by prairie-guy** [comment]
Thanks jcadduono. What I would like to do is build my own chroot and kernel appropriate for marshmallow with 'rolling' kali. I am using a Nexus 6P. How would I modify what I have done for a non-'rolling' kali? Here is what I did previously: 
                                                                                                                                                                   root@kali:~# git clone https://github.com/offensive-security/kali-nethunter                                                                                                        
root@kali:~# cd kali-nethunter/nethunter-installer                                                                                                                                 
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d angler --marshmallow

**Comment by jcadduono** [comment]
You have to go into the kali-nethunter/nethunter-fs folder and do:
./build.sh -f
This will take approx 40 mins to build a full rolling chroot tar.xz.
You can then place that in kali-nethunter/nethunter-installer/rootfs/armhf folder
Once it's there, just use the --rootfs full option tagged onto the end of your build.py command.

Understand that the build.sh -f script is only being tested on Kali, so it might not work on all Linux distros.

**Comment by prairie-guy** [comment]
Ok, to review.

In Kali:
./build.sh -f (to build full chroot)
cd [chroot.tar.xz] kali-nethunter/nethunter-installer/rootfs/armhf/.
python build.py -d angler --marshmallow --rootfs full

Then transfer to Nexus with adb. 

Do I then just execute an write over the original chroot, or do I need to delete the previous chroot?

Thanks.

**Comment by jcadduono** [comment]
close enough,
```
./build.sh -f
mv output/kalifs-full.tar.xz ../nethunter-installer/rootfs/armhf/
cd ../nethunter-installer
./build.py -d angler -m --rootfs full
```
should do it. then you can just flash that in twrp and it overwrites everything nethunter related, and automatically deletes the old chroot.

**Comment by prairie-guy** [comment]
I'm running Rolling. Thanks very much jcadduono.
