### ISSUE TITLE
Hfield wi-fire and oneplus one

### ISSUE THREAD

**Issue by mabusdogma** [offensive-security/kali-nethunter#448]
Hello everybody! I have a oneplus one with nethunter installed, and an old wireless card (hfield wi-fire) from 2008. I can use it on kali (plug and play, it says the driver is zd1211rw ) but I can't find a way to install the proper driver on my oneplus and use the USB wireless card with th OTG cable.
Any ideas?

**Comment by jcadduono** [comment]
https://github.com/binkybear/AK-OnePone/blob/marshmallow/arch/arm/configs/kali_defconfig#L1699
https://github.com/binkybear/AK-OnePone/blob/cm-12.1/arch/arm/configs/kali_defcofing#L1623

@binkybear caught in a bear trap

**Comment by mabusdogma** [comment]
How can I use the links? Sorry I just don't know how to use them. 
Copy/paste on the terminal doesn't work.

I see on the links you sent me this:
CONFIG_ZD1211RW is not set


What can I do?

**Comment by jcadduono** [comment]
wait for new kernel build for OPO is option 1
build your own kernel after changing that line to CONFIG_ZD1211RW=y in those sources is option 2

**Comment by mabusdogma** [comment]
I'm going to try building a new kernel (I have zero experience on it... But I just saw a tutorial with NDK.

In case that I decide to wait for a new kernel build...
How could I be sure that zd1211rw is included? Is there as way to ask for it somewhere?

**Comment by jcadduono** [comment]
i really did just give you that answer with my last message

**Comment by binkybear** [comment]
I have had to revert OPO after ycable changes.  I will create a new build in the next day or two.

**Comment by mabusdogma** [comment]
Thanks binkybear! I just couldn't make the wireless card work

**Comment by binkybear** [comment]
^^ Another day, another kernel.  Give it a try!
```
python build.py -d oneplus1 -m -k
```

**Comment by mabusdogma** [comment]
I'm lost, I downloaded both references and then I paste the command on the console... And an error appeared.
Is there a way to get the zip file for flash in recovery mode?

**Comment by jcadduono** [comment]
https://idlekernel.com/nethunter/nightly/3.1.0-20160504-2330/kernel-nethunter-oneplus1-marshmallow-3.1.0-20160504-2330.zip

feel free to browse the index @ https://idlekernel.com/nethunter/nightly/
should there be any change in the git, you can simply refer to the build time, and if it is older than the last git commit, join #nethunter on freenode irc and I'll be happy to rebuild.

**Comment by kendallgreen** [comment]
I am trying to install Nethunter on my OPO with Cm13-ZNH0EAS2JK.  TWRP 3.0.2 is installed but I get a boot loop when I try to install Nethunter oneplus lollipop 3.0 using the LRT scripts or manually with TWRP. I think the problem is SuperSU, I have tried BETA 2.71 and UPDATE 2.46.  Before I try something else, can someone give me some directions.

**Comment by bkr32** [comment]
@kendallgreen  you dont need to install superSu, i recommend installing the nethunter update from https://idlekernel.com/nethunter/nightly/ it will install superSU for you, all you have to do is run the app and install chroot in its entirety
