### ISSUE TITLE
When building Nethunter image, OnePlusX is not found.

### ISSUE THREAD

**Issue by Lucurus** [offensive-security/kali-nethunter#449]
Hi, 
I tried to build my own image, but when I put in `python build.py -d oneplusx --marshmallow` I get `Error: Device oneplusx not found devices.cfg`
I checked that document and the device is listed there, so I don't know if I did something wrong or if this is a bug.
Any help is appreciated
Thanks

**Comment by binkybear** [comment]
Use:
```bash
python build.py -d oneplusxcm  --marshmallow
```
I believe @jcadduono made the kernel so it may be CM only.
