### ISSUE TITLE
TP-Link TL-WN722N It works with nexus 5x ?

### ISSUE THREAD

**Issue by guillermo04** [offensive-security/kali-nethunter#450]

**Comment by h0r57** [comment]
Yes, it works.

**Comment by guillermo04** [comment]
Ok thanks for answering

**Comment by guillermo04** [comment]
Ok thanks for answering

**Comment by guillermo04** [comment]
I have another question Updating my nexus 5x is nutella ( 7.0 ) can be installed nethunter ?

**Comment by h0r57** [comment]
I think bullhead is better right now.

**Comment by guillermo04** [comment]
ok thanks
