### ISSUE TITLE
Size of full chroot

### ISSUE THREAD

**Issue by Z3r0byte** [offensive-security/kali-nethunter#452]
Hey everyone,

I was installing the full chroot on my device. However, the system started to warn that its memory was low, so I had to abort it. At that point, the chroot had already taken about 2 GB. How big is this chroot actually?

Thanks in advance,

Z3r0byte

**Comment by worsedoughnut** [comment]
A general approximation of the respective sizes of each chroot meta-package can be found here:

https://www.kali.org/news/kali-linux-metapackages/

**Comment by jcadduono** [comment]
```
root@hltecan:/data/local/nhsystem # busybox_nh du -md1
2813    ./kali-armhf
2813    .
root@hltecan:/data/local/nhsystem #
```
and so it would seem that 2813 MB is the answer for the current, updated state of the Kali Rolling 2016.1 armhf full chroot.
I don't currently have an estimate for the Sana one downloaded by the app should you choose that method of installation, but it should be fairly similar in size.

**Comment by Z3r0byte** [comment]
Thanks for all the answers!

**Comment by ibanezalvin** [comment]
guys can i install kali linux top 10 and wireless in extsd card or memory card?
