### ISSUE TITLE
Unusably slow Nexus 7 2013 (flo) when running Nethunter 3 on CM13

### ISSUE THREAD

**Issue by alexborisov** [offensive-security/kali-nethunter#455]
I've tried to install this manually via _TWRP_ and using the _nethunter-LRT_ script. On booting the animation is very slow (like 1FPS) and the OS boots and is pretty much unresponsive.

I've tried a full install (tick everything) and default.

**Comment by jcadduono** [comment]
use flocm not flo, different packages, build from git or download from https://idlekernel.com/nethunter/nightly/
