### ISSUE TITLE
no default gateway in kali

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#461]
no default gateway present in kali

root@kali:~# ip route
192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.101
root@kali:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 wlan0

Is something broken in kali config?

**Comment by n00shE** [comment]
Is 192.168.0.0 not your default gateway? Correct me if im wrong?

**Comment by pyc0de** [comment]
My default gateway is 102.168.0.1
if I run dhclient wlan0, default gw appears, but this is not convinient, and this wasnt the case in NH2.
Anyway is this a desired behavior or (likely) thisvis a bug?

**Comment by binkybear** [comment]
This is related to Android routing changes in lollipop and not a bug with Nethunter.
