### ISSUE TITLE
broken tshark output in nethunter terminal

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#462]
When running:
tshark -i wlan0
tshark output starts to overwrite itself from the top of the screen instead of scrolling down like all other apps.

This is triggered by tcp ack/rst packets, because when i run 
tshark - i wlan0 -Y http
packets are displayed fine.

Please look into it, because it is very annoyng bug.
Thanks!

**Comment by pyc0de** [comment]
am i the only one having this issue or nobody is using tshark on nethunter? i had this bug since nethunter 2.0.

**Comment by jcadduono** [comment]
can u try running "resize" command before tshark and let me know if that helps?

**Comment by pyc0de** [comment]
@jcadduono doesn't help( 
i run:
resize; tshark -i wlan0

**Comment by pyc0de** [comment]
Hi,
Any news on this annoying bug?

**Comment by pyc0de** [comment]
After latest updates the issue is gone now. Nice!

For some reason I see '?' instead of '→', weird.
