### ISSUE TITLE
Nexus 7 freezes at boot after Kali NetHunter 3.0 install

### ISSUE THREAD

**Issue by cybermapt** [offensive-security/kali-nethunter#463]
Hi,

I have installed Kali NetHunter (Lollipop) on Nexus 7 (2013) WiFi.
I followed and used NetHunter-LRT: https://github.com/offensive-security/nethunter-LRT.
All ok, system installed but when the tablet was rebooted it doesn't start. I see only the animated logo and no other.

Step 2. I tried to re-install and now I see a lot of error after installation:

Starting AROMA INSTALLER version 3.0
(c) 2013-2015 by amarullz.com
AROMA INSTALLER Finished...
Updating partition details...
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram12' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram14' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram16' (Not a directory)
...
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop1' (Not a directory)
...done

Please some fix?
Thanks

**Comment by pyc0de** [comment]
try to use file manager in recovery and manually delete this directory.

**Comment by pyc0de** [comment]
if you want to reinstall, first go to recovery and manually delete /data/loca/kali-armhf.
This worked for me.

**Comment by OluMMelegi** [comment]
I have the same problem and deleting /data/local/kali-armhf manually didn't work for me. Any updates on this issue?

**Comment by shishan** [comment]
facing the same question
