### ISSUE TITLE
Can Not find veil evasion in nethunter

### ISSUE THREAD

**Issue by xavkno** [offensive-security/kali-nethunter#464]
Is it even included in the packages
and a can't install it as the response i get from
"apt-get install veil-evasion"
is:

E: Unable to locate package veil-evasion

Thanks in advance.

**Comment by vay3t** [comment]
veil have problems in nh because using arch x86/x64 (nh not support). you also have the "hid" in nh. my suggestion: ussing a pc for create a payloads FUDs
