### ISSUE TITLE
Nexus 7(wifi 2012 version 4.4.4) boot loop 

### ISSUE THREAD

**Issue by kamron030702** [offensive-security/kali-nethunter#466]
I fallow all installation steps on the Kali website for installation,

**Comment by kamron030702** [comment]
Then and when I booted Kali net hunter with everything installed it was boot looping so I flash stocked it again and now that is boot looping someone suggested clearing/erasing my cache but I don't know how, could you tell me? I've googled and I could find anything helpful.

**Comment by n00shE** [comment]
Boot to recovery and click wipe

**Comment by akrolla** [comment]
Is the 4.4.4 deprecated? I wanted to tryto instal a nethunter instance inside of pwn phone...
