### ISSUE TITLE
Nethunter not working on official cm13 nightlies for OnePlus 2. 

### ISSUE THREAD

**Issue by yennefer1173** [offensive-security/kali-nethunter#471]
I tried flashing the latest nethunter over the latest cm13 nightly build and the phone did not want to boot at all. I guess it is because of the new kernel from Oxygen OS 3, which is used by the cm13 nightlies. Oneplus released the kernel sources, so it should be pretty easy to fix.

**Comment by jakuta-tech** [comment]
Confirmed same situation. Stuck at the OnePlus logo.

**Comment by binkybear** [comment]
Pulled from the latest CM repo.  Didn't see a lot of changes though but might be worth giving it another kernel flash.

**Comment by yennefer1173** [comment]
The new kernel does not fix the issue. I noticed that the cm13 nighlies requires a modified version of supersu, but nethunter uses the official supersu. So I flashed this one https://www.androidfilehost.com/?fid=24580943222145372 and all worked well. It would be great if it was packaged with the installer for OP2.

**Comment by jcadduono** [comment]
If additional modifications are necessary then we can add them to the patch.d folder in op2 kernel for M 
..will need to do a diff on official supersu zip and that one I guess.

**Comment by binkybear** [comment]
I compared both supersu's and it's just one small difference:

https://www.diffchecker.com/zvti0joz

@yennefer1173 - So the kernel worked after flashing that new supersu?

**Comment by yennefer1173** [comment]
Yes, it works like a charm for now. I found it in this thread https://forums.oneplus.net/threads/mirrors-for-official-oxygen-os-roms-and-ota-updates.387615/ . It is in the first post under the section with TWRP & SuperSU for Oxygen OS 3.

**Comment by jcadduono** [comment]
well that difference wouldn't make any difference since on M, SYSTEMLESS=detect would just turn into SYSTEMLESS=true ... maybe we just need to update SuperSU :S The way NetHunter installs it at the moment is SYSTEMLESS=false, then prevents SuperSU from modifying the boot image, but applies supolicy automatically during its own boot image modification process.

**Comment by jakuta-tech** [comment]
Hmmm, well the only way I seem to be able to get past the +1 logo for nightlies is to flash cm13, the modified SuperSU v2.74 TWRP flashable zip, Nethunter (--nosu) and then flashing modified SuperSU v2.74 again, but only in that combination.  Any other combination I tried failed.  I've tried official SuperSU v2.74 in those combinations and can't get past the +1 logo.
 
Once in Nethunter, dmesg registers an Alfa and a TL-WN722N when they are plugged in but neither of them show up in iwconfig.  All attempts are under 2802f71eeb92e08ec67983c0fc0440f2d659bcdc

**@yennefer1173** Do you see wlan1 ?

**Comment by yennefer1173** [comment]
No, I also can't see wlan1(I'm using tl-wn722n). It is shown as usb device in lsusb, but not as a network interface in ifconfig. It could be a driver issue. This bug has already been reported here https://github.com/offensive-security/kali-nethunter/issues/468.

**Comment by binkybear** [comment]
Are you both using a usb-c type adapter with otg or usb-c otg cable.  In my experience with OnePlus2 it only worked with a usb-c adapter and not the usb-c otg cable.

I know I enabled for atheros (tl-wn722n) so the driver should be OK.  But the OnePlus2 is not my favorite device to build for, it has some issues.

**Comment by yennefer1173** [comment]
I am using the official usb-c adapter from oneplus with usb 2.0 otg cable. My tl-wn722n worked perfectly on previous builds(unofficial cm13) and I can confirm that the otg feature of the official cm13 nightlies works, because I tried some flash drives and they work flawlessly, so the problem remains to be related with nethunter.

**Comment by jakuta-tech** [comment]
@binkybear I have both cable types which work fine on the unofficial rom's with Nethunter.

A single OTG cable from Alfa or TL-WN722N to the OP2 using the OnePlus2 Type-C adapter works fine on Seraph's or Graraks unofficial CM13 and CM13.01 ROM's and Nethunter.  

Also the OTG-Y cable with the OnePlus Type-C adapter and the Alfa or TP-LINK works fine on the unofficial ROM's with Nethunter.  

Nightlies don't work with either OTG or OTG-Y cables to bring up wlan1, but it is registered in lsusb and dmesg.

Also yes I have a usb-c OTG cable and it doesn't work with the OP2, only the Type-C adapter works.

**Comment by binkybear** [comment]
Thank you @jakuta-tech and @yennefer1173 for your detailed responses and help.  I'm using the same kernel so it appears the issues is related to some change in official builds.  It seems like its a matter of tracking down what the changes were.

**Comment by renjen-n00b** [comment]
aw looks like some other guys found the issue. thanks @yennefer1173 and @jakuta-tech

**Comment by renjen-n00b** [comment]
@jakuta-tech how did you manage to get past the bootloop or the +1 logo? i have already tried that combination... not working
i tried the --nosu.. also tried implementing the modified Supersu into the zip file i've built.. flash was successful but i'm still getting a bootloop.

**Comment by jcadduono** [comment]
you guys can probably just edit this file:
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/supersu/vars
remove both lines and add:
`SYSTEMLESS=true`
to the file, then save it and build your nethunter installer.
before flashing, you will need to go back to a bootable state though.

**Comment by jakuta-tech** [comment]
@jcadduono thanks.  I've got `SYSTEMLESS=true` which now just sets SuperSU to the same as modified SU.  The phone only boots when rootfs is built with the --nokernel option though so it's coming back to the kernel as the issue.

@renjen-n00b The other way of trying to install as above is to build without kernel and changing the SuperSU variable as @jcadduono says above;

`python build.py --device oneplus2cm --marshmallow --rootfs minimal --nokernel --release nightly-test1`
build the kernel separately
`python build.py --device oneplus2cm --marshmallow --kernel --release nightly-test1`

You can flash rootfs after setting up the bootable state and then reboot. Nethunter/chroot will be installed, but it won't have the kernel.  At least it gets you to a point where you can start to debug.

Reboot to recovery and flash the kernel file and you will go back to a "stuck at oneplus logo" again so it seems to be a kernel problem.

**Comment by jakuta-tech** [comment]
@binkybear 316a62ebd212c79ffef65190f7552fbd39270859 still doesn't work for me.  Flashing minimal with kernel hangs at OnePlus boot logo.  Build without kernel gets into the system, then flash kernel after and hangs at boot logo again.

**Comment by jakuta-tech** [comment]
492b9cb3f119ed3166b1bb51202c52af30cf71c2 unfortunately has the same result.  Fails to boot past the logo when the kernel is flashed.

**Comment by renjen-n00b** [comment]
yup stuck at the +1 logo

**Comment by Chris-Ar** [comment]
Can you pull a location during boot? To see what the heck is doing before hanging...if it reaches bootstage at al :/

**Comment by Chris-Ar** [comment]
Location = log cat for my t9 :D

**Comment by binkybear** [comment]
Okay I was able to test this one myself.  Dropped the dtb.img and it seems to be flashing okay.  Haven't had a chance to check wlan1 yet, but it seems to be back on track.

Give it a test and let me know.

**Comment by renjen-n00b** [comment]
it works like charm! .. @binkybear 
kernel seems to work **perfectly**
but i'm unable to get into the kali terminal shell..
i'm downloading the full chroot right now and will reply back asap

> Okay I was able to test this one myself. Dropped the dtb.img and it seems to be flashing okay. Haven't had a chance to check wlan1 yet, but it seems to be back on track.
Give it a test and let me know.

thanks!

**Comment by yennefer1173** [comment]
Everything is working well now. And wlan1 seems to be working too(tried with tl-wn722n) :). Thank you @binkybear !!!

**Comment by renjen-n00b** [comment]
**Update**
i have downloaded the full chroot and everything works perfectly but i'm unable to get
wlan1, tho i'm using [netsys](https://www.amazon.it/6800mW-Netsys-9000WN-Wireless-Antenna/dp/B00AERB7AQ)

**Comment by jakuta-tech** [comment]
@binkybear perfect :+1:   Everything is working great.
