### ISSUE TITLE
Build on Windows?

### ISSUE THREAD

**Issue by al3xv3gas** [offensive-security/kali-nethunter#472]
Title kinda says it. Can I build on windows?

**Comment by vay3t** [comment]
yes, but we like kali. you can use [Nexus Root Toolkit v2.1.5](http://www.wugfresh.com/nrt/)

**Comment by binkybear** [comment]
All you need is python and git to build a flashable zip.  See @vay3t comment for flashing.

**Comment by al3xv3gas** [comment]
ok
