### ISSUE TITLE
KALI NETHUNTER VIRUS AND BUILD ISSUES

### ISSUE THREAD

**Issue by al3xv3gas** [offensive-security/kali-nethunter#473]
While working with Kali Nethunter I'v feaced two issues on my OPO:

-) I downloaded the source with the help of <a href="https://github.com/termux">Termux</a> and built an uninstaller and Kali NetHunter distro for my PAC MAN 5.1 ROM. Downloading and Building was a success but after I flashing I encountered two issues/errors: 1) TWRP said it couldn't find certain partitions on my OPO. 2) After flasing iI rebooted and none of the Kali Linux NetHunter apps were there.

-) After downloading a stable distribution for the same ROM, I installed Kali NetHunter successfully on my device. When I rebooted, Malware Bytes, CM Security and Avast all said that CSploit is a virus. Is it really a virus or should I put it under the ignored threats list?

Swift reply please, I do not want my OPO to be damaged!!!!

**Comment by jcadduono** [comment]
Many virus scanners include tools that are used for network penetration / security testing as "HackTool" category when running scans, and can safely be ignored.

**Comment by binkybear** [comment]
cSploit is not a virus.  You can check out there repo and build it yourself.  See @jcadduono response.
