### ISSUE TITLE
What about the missing apps?

### ISSUE THREAD

**Issue by al3xv3gas** [offensive-security/kali-nethunter#474]
While working with Kali Nethunter I'v feaced two issues on my OPO:

-) I downloaded the source with the help of Termux and built an uninstaller and Kali NetHunter distro for my PAC MAN 5.1 ROM. Downloading and Building was a success but after I flashing I encountered two issues/errors: 1) TWRP said it couldn't find certain partitions on my OPO. 2) After flasing iI rebooted and none of the Kali Linux NetHunter apps were there.

-) After downloading a stable distribution for the same ROM, I installed Kali NetHunter successfully on my device. When I rebooted, Malware Bytes, CM Security and Avast all said that CSploit is a virus. Is it really a virus or should I put it under the ignored threats list?

Swift reply please, I do not want my OPO to be damaged!!!!

Edit: What about the missing apps and framwork after installing the self built kali distro?

**Comment by bkr32** [comment]
cSploit is seen as virus because of how it works, it sniffs traffic and can inject packets similar to a virus, but rest assured it is not a virus

**Comment by vay3t** [comment]
I recommend that you uninstall windows

**Comment by al3xv3gas** [comment]
Ok @vay3t, good one. Not gonna happen lol. My question is why did NetHunter not install properly when I built it from source on my phone running a CM 12.1 deri. After installing my custom-built distro of NetHunter I rebooted and couldn't find the NetHunter app.

**Comment by pyc0de** [comment]
have you trief --forcedown before building?

**Comment by al3xv3gas** [comment]
Nope @pyc0de will do and will get back here.

**Comment by al3xv3gas** [comment]
It worked! @pyc0de
