### ISSUE TITLE
Responder/Responder MITMf plugin seg faults on Nexus 7

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#477]
Hi, so it looks like when ever I run Responder on my Nexus 7 running nethunter it runs for a moment and then crashes giving a segmentation fault message, I tried this using the Responder MITMf plugin, the Version of Responder in the Repo as well as the Git version with both wlan0 and wlan1 same result each time, has any one else encountered this error?

**Comment by thesle3p** [comment]
Has anyone confirmed this? Does Responder work for anyone on Nethunter?

**Comment by pyc0de** [comment]
it works for me on Nexus 7 2013

**Comment by thesle3p** [comment]
is that after a apt-get update and upgrade on the chroot? I am trying to figure out if a update to kali broke it or if something I did messed it up.

**Comment by thesle3p** [comment]
It looks like Responder dies trying to load cffi:
'''Python -v ./Responder.py -I wlan0
--snip--
import cffi.vengine_cpy # precompiled from /usr/lib/python2.7/dist-packages/cffi/vengine_cpy.pyc
dlopen("/usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.arm-linux-gnueabihf.so", 2);
Segmentation fault
''"
Reinstalling cffi using aptitude did not seem to fix it nor did upgrading cffi using easy_install.

**Comment by thesle3p** [comment]
Looks like easy_install -U cryptography fixed it, weird.
-----Original Message-----
