### ISSUE TITLE
;60R (Possible resize issue)

### ISSUE THREAD

**Issue by binkybear** [offensive-security/kali-nethunter#478]
Error when launching commands sometimes brings up ;60R and command needs to be relaunched.

https://twitter.com/vay3t/status/740608472350330882

**Comment by jcadduono** [comment]
weird i can't figure out how to reproduce it

**Comment by binkybear** [comment]
It appears randomly.  I see it on OnePlus1 sometimes but not on Nexus 5x.  It could be related to busybox resize but unsure.

**Comment by vay3t** [comment]
* in the photo is a Nexus 5 2013

**Comment by jmingov** [comment]
Ill try to reproduce it.

 :+1:  ty @vay3t for the info.

**Comment by vay3t** [comment]
I remember now. When this error occurs WN722N had connected. could that be the reason?
I connected the antenna and did run custom commands. the error occurs

**Comment by jcadduono** [comment]
well i dont think resize could be the problem, but maybe the commands after it failing, so it still shows the output of resize?

**Comment by vay3t** [comment]
Sorry, I do not know that resize.
*** UPDATE: the error is when you use first time "custom commands" after turning on the device

**Comment by pyc0de** [comment]
I get same issue on Nexus 7 2013, seemingly random.

**Comment by n00shE** [comment]
I can confirm. I get this issue using any custom command after a reboot. Even after nethunter boots ALL OK

**Comment by renjen-n00b** [comment]
it appeared once, the first time i rebooted after flashing nethunter.... but it disappeared after that by just rebooting once.
