### ISSUE TITLE
Wifite doesn't work

### ISSUE THREAD

**Issue by Doveyang** [offensive-security/kali-nethunter#482]
![screenshot_20160611-204752](https://cloud.githubusercontent.com/assets/19889990/15991385/25926ca2-30e4-11e6-8f79-1f7e9ecd8136.png)

**Comment by renjen-n00b** [comment]
https://github.com/derv82/wifite#execution

**Comment by binkybear** [comment]
Error appears python related. You may want to check your python and wifite install.

**Comment by Doveyang** [comment]
@binkybear It indeed seems to be python. All python related tools, such as sqlmap, do not work. However, the problem is that I don't know how to re-install it.

**Comment by bkr32** [comment]
@Doveyang you could flash a new full nethunter build
