### ISSUE TITLE
whatweb unusable - constant Target::TimeoutError is deprecated

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#483]
Hi,
whatweb throws this warning and exits.

/usr/share/whatweb/lib/target.rb:188: warning: constant Target::TimeoutError is deprecated

do we need to update ruby?

**Comment by binkybear** [comment]
I have no issues running latest from github.

**Comment by pyc0de** [comment]
Thanks, latest whatweb works fine. Closing.

**Comment by panthi12** [comment]
I'm having the same problem, what do you did?

**Comment by pyc0de** [comment]
I just updated both nethunter & chroot and whatweb worked.
