### ISSUE TITLE
Nethunter VNC app unusable on Nexus 7 2013

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#484]
Hi,
I could connect to vnc server, see the desktop, but I cannot clck or move mouse pointer around, no matter which input method I select or what mouse do I use.

I have encounteted same issue in some other vnc clients, but others are working fine.

Server settings and client settings are Nethunter's defaults.

**Comment by Zahkc** [comment]
bump

**Comment by pyc0de** [comment]
What do you mean>

**Comment by Zahkc** [comment]
http://www.webopedia.com/TERM/T/thread_bump.html

**Comment by thehackcave** [comment]
I too face the same issue in Nethunter (Nexus 5x ,Nougat 7.0). Any fixes so far?
