### ISSUE TITLE
Battery stuck at 100% on OPO running 13.0, with nethunter 3.1

### ISSUE THREAD

**Issue by JamesHagerman** [offensive-security/kali-nethunter#485]
I know that this is a bug that's been around for a while but it seems to have fallen off the waggon to some extent. I figured tracking it here might be the best way to get eyes on it.

**Comment by bkr32** [comment]
yes this issue is related to Y cable charging seen in https://github.com/offensive-security/kali-nethunter/issues/414
best go for a kernel made before may to avoid the issue altogether

**Comment by JamesHagerman** [comment]
Alright cool. I'm trying `https://idlekernel.com/nethunter/nightly/3.1.0-20160524-0111/kernel-nethunter-oneplus1-marshmallow-3.1.0-20160524-0111.zip` now...

Thank you for the update!

**Comment by JamesHagerman** [comment]
@bkr32 Any chance you'd know where I could get an earlier nightly? The one you called out in another thread, 20160524 still seemed to have the battery issue... 

Or, if someone could point me to a githash of the last working version I'll just built it myself...

**Comment by bkr32** [comment]
i'll upload a GDrive link

**Comment by JamesHagerman** [comment]
AWESOME! Thank you so much! I'll try it now!

**Comment by bkr32** [comment]
it should work, just try it out or i'll upload the update as well

**Comment by JamesHagerman** [comment]
On it now. I'll let you know if it works.

**Comment by JamesHagerman** [comment]
That seems to have fixed the battery stuck at 100%!! Had to reboot a few times just to make sure everything was cleanly installed, but it works!

Now, I wonder what the actual change was so that maybe the next nightly can be fixed as well...

**Comment by bkr32** [comment]
Y cable patch issue

**Comment by bkr32** [comment]
Just to add on the issue, it seems that with some kernels like the last working nethunter kernel for Oneplus one, do not correctly interface with ADB, the issue i am having is that revoke usb authorization does not show up due to this @binkybear hope you can update the kernel

**Comment by jcadduono** [comment]
I'd just like to add for those who are looking to try previous kernel builds with the new repository layout (kernels moved into nethunter-devices repository instead!)
You can git clone the full history of this repository which is around 4.2 GB, then search through commits like so:
```sh
git log --oneline --all -- nethunter-installer/kernels/marshmallow/oneplus1
```
Once you've found a kernel revision you'd like to try, you can use (as an example):
```sh
git checkout a767ee9 nethunter-installer/kernels/marshmallow/oneplus1
```
You will then need to move that into the new devices folder. You can do this with:
```sh
rm -rf nethunter-installer/devices/marshmallow/oneplus1
mv nethunter-installer/kernels/marshmallow/oneplus1 nethunter-installer/devices/marshmallow/oneplus1
```
From here, you can use build.py to generate the kernel from that revision on the current installer branch.
```sh
cd nethunter-installer
./build.py -d oneplus1 -k -m -r "kernel-rev-a767ee9"
```

**Comment by JamesHagerman** [comment]
Hey @bkr32 and @binkybear,

This issue is still preset in the latest nightly: kernel-nethunter-oneplus1-marshmallow-3.1.0-20160802-0230.zip

Just wanted to throw it out there in case I've missed something that might have changed since a month or so ago.

**Comment by bkr32** [comment]
yes it still persists, i'd prefer if Y cable charging was left out altogether,i suppose i can try build a custom kernel

**Comment by binkybear** [comment]
@JamesHagerman & @bkr32  - I thought it was fixed/removed.  I'll try uploading a new kernel tonight.

**Comment by bkr32** [comment]
thanks @binkybear i'll provide feedback then

**Comment by binkybear** [comment]
New zImage was uploaded yesterday: https://github.com/offensive-security/nethunter-devices/commit/ba26e5f5174f36bb3b5b09e5abefa00de8f59b20

Will probably spend more time on it this weekend tweaking.

**Comment by bkr32** [comment]
waiting for a new build on idlekernel

**Comment by bkr32** [comment]
@JamesHagerman new build is up at idle-kernel 100% bug is gone 
@binkybear first boot after flashing the device was unresponsive needed a hard reboot, now it's generally slow and jittery

**Comment by bkr32** [comment]
new build brings back 100% issue and doesnt mount storage on pc's 
it is rather fast and snappy though

**Comment by binkybear** [comment]
k try this: https://transfer.sh/MnndC/kernel-nethunter-oneplus1-marshmallow-20160812-163937.zip

**Comment by JamesHagerman** [comment]
Trying this now. Hopefully it's less crashy than the last few August nightlys...

**Comment by binkybear** [comment]
I realized I didn't push HID patch.  It's now in nethunter-devices.

**Comment by bkr32** [comment]
Battery bug and screen lock bug aren't present, and HID attacks aren't working, still testing

**Comment by binkybear** [comment]
@bkr32 - Flash new kernel in nethunter-devices and HID attacks should be working again.  Tested on latest OxygenOS with OnePlus 1 and everything seemed much more stable to me.

**Comment by bkr32** [comment]
Sure will, I'm currently testing the one you just posted on transfer.sh, do you have any issue updating apps?

**Comment by binkybear** [comment]
No issues updating apps and no more freezing.

**Comment by bkr32** [comment]
the only issue i face is that revoke usb authorization goes missing it is present in stock kernel though

**Comment by JamesHagerman** [comment]
Thank you for all the work on this.

Is there something I can do to test that "revoke usb authorization" thing on my end?

**Comment by binkybear** [comment]
It may be related to: ro.adb.secure

I am also missing it.  I can remove the keys manually but it breaks adb.

https://github.com/CyanogenMod/android_packages_apps_Settings/blob/830a8464a067c022227344c95738bfe9e53fc526/src/com/android/settings/DevelopmentSettings.java#L362

**Comment by bkr32** [comment]
probably is i searched up the issue and some custom kernels experience it, it is present on stock kernel however

**Comment by bkr32** [comment]
i guess this issue can be closed since the 100% bug is solved @JamesHagerman @binkybear

**Comment by JamesHagerman** [comment]
Agreed!

**Comment by phr34k0** [comment]
Someone pls reupload that kernel for cm13. Power issue here due to https://build.nethunter.com/nightly/?C=M&O=D
