### ISSUE TITLE
Minimal build of KNH

### ISSUE THREAD

**Issue by al3xv3gas** [offensive-security/kali-nethunter#486]
Hi, everyone. So recently I installed NetHunter on my phone and I kinda realised that I'm not using most of the apps included in NetHunter anyway. So I was wondering the following: Is there a way to just have the NetHunter App, NetHunter Terminal and the KNH Chroot all in one flashable zip? If so, how do I go about making such a minimal image?

**Comment by jcadduono** [comment]
Just delete the apks from the zip the installer is designed to be very versatile. Pretty much everything can be removed from it 1 by 1 if you wanted. The installer checks for existence of stuff in zip before trying to install stuff, so you could add stuff to the minimal zip and it could become a full zip automagically and vice-versa.

**Comment by al3xv3gas** [comment]
Ok, but what about the updater script, wouldn't that be affected by me removing stuff?

**Comment by al3xv3gas** [comment]
And what about the kernel, what lurpose does it serve?

**Comment by jakuta-tech** [comment]
There's an awesome wiki here that will give you kernel purposes.

**Comment by jcadduono** [comment]
the updater-script should check for the existence of everything in the installer before trying to install that item...the only thing you should not remove is busybox/tools folder and META-INF i think...

**Comment by al3xv3gas** [comment]
No because I'm running a build of PA and I want to include the Radioactive kernel into my very own build specially for PA, what can I delete and what can I keep. And because this is not really an issue but more of a question why don't you guys make a chatrrom on Gitter for just such questions?;) Just a suggestion on the side.

**Comment by bkr32** [comment]
1.)delete unwanted apks
2.) flash your own zip after flashing updater

**Comment by jcadduono** [comment]
we have an irc channel which should be listed in the wiki for live discussion.

to use another kernel simply replace the kernel in the nethunter-installer/kernels/androidversion/yourdevice/ folder with the kernel you want to include...this will not apply any of the kernels ramdisk modifications and you would need to create something from the ramdisk-patch folder if you were going to do something like that.

./build.py -d yourdevice -m/-k builds the installer
open the zip and remove whatever you don't want, but keep tools, boot-patcher, and META-INF folder at least

**Comment by al3xv3gas** [comment]
About the Chroot...when I make a custom build the Chroot is not included and I have to download it after flashing KNH. What do I need to modify in the installer zip so that the Chroot is included "out of the box"?

**Comment by al3xv3gas** [comment]
@jcadduono

**Comment by jcadduono** [comment]
see the readme in nethunter-installer folder
