### ISSUE TITLE
After flash Nethunter Kernel in the Samsung Galaxy S5 CM 13, the camera not working

### ISSUE THREAD

**Issue by Giann23** [offensive-security/kali-nethunter#488]
Hello, Everyone,
I have this problem with my device, after flash kali nethunter kernel (3.1.0-20160616-2249)  for my s5, cm 13.0 Build cm-13.0-20160615-NIGHTLY-klte, the camera not working more,  and i see this message (" The application camera has stopped unexpectedly"), I already try restarting my device, and when I install CM13, the camera works again without the kernel

*Note, I only flash the kernel first

Sorry for my english,

help me please

**Comment by jcadduono** [comment]
yes there were some very big changes recently in cm13 nightlies and i have to redo much of the work, not sure when i'll have the time to get to it...hopefully within the week though

**Comment by Giann23** [comment]
oh thanks, I expect then, can recommend me some previous build, which if it worked the kernel? thanks!

**Comment by jcadduono** [comment]
https://github.com/CyanogenMod/android_kernel_samsung_klte/commit/67f19bfe81079abb9ca7f5d68f1990826e10576e looks like June 3rd so I would go for 20160602 or older if you can find it.

**Comment by Giann23** [comment]
Thank you, I try with this Kernel and an older cyanogenmod
