### ISSUE TITLE
add tunctl to nethunter kali repo

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#490]
hi
is it possible to add tunctl to nethunter kali repo, or is there other way to create tun/tap interface?
thanks.

**Comment by binkybear** [comment]
You can create tun:
```bash
mkdir /dev/net
ln -s /dev/tun /dev/net/tun
```
Android handles tun differently.  This was also added to latest app so it should be created automatically.

**Comment by pyc0de** [comment]
@binkybear,
I used this solution:

mknod /dev/tun c 10 200
chmod 600 /dev/tun
ln -s /dev/tun /dev/net/tun

however:

# cat /dev/tun
cat: /dev/tun: File descriptor in bad state

is something broken here?

initially I stumbled upon this issue when trying to run miredo:

Error: cannot open device file /dev/net/tun ()

However, after manually creating tun I get another error when trying to run miredo:

miredo[16008]: Starting...
miredo[16009]: Miredo setup failure: libteredo cannot be initialized
miredo[16008]: Child 16009 exited (code: 1)
miredo[16008]: Terminated with error(s).

Is this related to 'cat: /dev/tun: File descriptor in bad state' ? I can't find anything meaningful on 'libteredo cannot be initialized' issue.
Have you tested miredo on Nethunter + CM13?

Should I raise a separate issue for miredo or just use this thread?

Thanks.

**Comment by binkybear** [comment]
cat: /dev/tun: File descriptor in bad state <-- Means its working.

Your error shows libteredo cannot be initialized so I assume its related to that library file. 

I have never used miredo before but you could try building miredo from source (if you haven't).

**Comment by binkybear** [comment]
I think this was fixed in https://github.com/offensive-security/kali-nethunter/issues/503
