### ISSUE TITLE
Building for officially un-supported Android devices

### ISSUE THREAD

**Issue by Logmytech** [offensive-security/kali-nethunter#492]
I want to know if it is possible to build Nethunter for a device which is not supported officialy.

Say I want to build for a Samsung device.

Can the Python build script do that.

How would I go about doing this?

**Comment by darkdawn29** [comment]
Same here but i want build it for Xperia Z3

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/README.md

You only need to build a kernel image.
You can still flash the entire thing minus the kernel by doing:

`./build.py --generic armhf --rootfs full`
