### ISSUE TITLE
Nexus 10 doesn't recognize the driver of TL-WN722N's wireless card.

### ISSUE THREAD

**Issue by erfack** [offensive-security/kali-nethunter#494]
My Nexus 10  with NetHunter 3 (kernel version 3.4.67-00092-g7b02438) and Android Lollipop 5.1.1 (build LMY49J), doesn't recognize the TL-WN722N's driver.
I've already copied the chroot firmwares to /etc/firmware:
"root@manta:/ # ls /etc/firmware
ar9170-1.fw
ar9170-2.fw
carl9170-1.fw
htc_7010.fw
htc_9271.fw
rt2561.bin
rt2860.bin
rt2870.bin
rt3070.bin
rt73.bin
rtlwifi
zd1211"

But when I launch Wifite, shows the driver of TL-WN722N as ?????.
However lsusb recognize the chipset.

![screenshot_2016-06-29-23-39-56](https://cloud.githubusercontent.com/assets/20214090/16470234/4d1630fa-3e55-11e6-93d0-b14db437ff47.png)
![screenshot_2016-06-29-23-40-47](https://cloud.githubusercontent.com/assets/20214090/16470235/4d48281c-3e55-11e6-8bf9-404f7a3846a3.png)

**Comment by jcadduono** [comment]
looks to me like you don't have nethunter kernel installed, only the app/chroot components

you can build it with:
`./build.py -d manta -l -k`

or download prebuilt here:
https://idlekernel.com/nethunter/nightly/3.1.0-20160628-2308/kernel-nethunter-manta-lollipop-3.1.0-20160628-2308.zip
flash with twrp

**Comment by erfack** [comment]
Flashed just now the prebuilt but no changes.

**Comment by jcadduono** [comment]
output of:
```sh
cat /proc/version
ls /system/etc/firmware
```
please

**Comment by erfack** [comment]
![screenshot_2016-06-30-00-40-18](https://cloud.githubusercontent.com/assets/20214090/16471185/5d7ea30e-3e5b-11e6-90ae-4cc94ac16c47.png)

**Comment by jcadduono** [comment]
no idea then, all looks good to me

**Comment by erfack** [comment]
Tomorrow I will test the wireless card on a pc with Kali Linux. Thank you for the support however and sorry for my english! 
If you have suggestions, please tell me.

**Comment by erfack** [comment]
![screenshot_2016-06-30-01-02-10](https://cloud.githubusercontent.com/assets/20214090/16471664/7141a668-3e5e-11e6-99c1-f43cd65ede43.png)

**Comment by jcadduono** [comment]
looks good, open KALI terminal as root and do:
`ip link set wlan1 up`
it should work

**Comment by erfack** [comment]
Nothing ... the driver is still not recognized

**Comment by binkybear** [comment]
Only other thing I can think of is trying ifconfig wlan1 up instead.  The firmware is loaded and the device is recognized.  There's no reason why it shouldn't work.  Do you have ycable turned on?

**Comment by erfack** [comment]
Yes I have. I tried to build a new kernel but i had some errors. Now I will re-flash nethunter.

**Comment by n00shE** [comment]
The driver isn't recognized on my Nexus 5 either. But it's not a problem because the card still works.

**Comment by a7ent** [comment]
root# modprobe ath9k_htc
root# ifconfig -a (see if its listed)
root# ifconfig wlan0 up


if the ath9k_htc firmware file isnt in the directory i belive it is part of:
apt-get install firmware-atheros

as always update/upgrade/dist-install

as well as checking for my frequent spelling errors
