### ISSUE TITLE
Oneplus 3 support?

### ISSUE THREAD

**Issue by xDGameStudios** [offensive-security/kali-nethunter#497]
No really issue here sorry but also no forum on offensive security site either.
Is OnePlus 3 currently supported? I wanted to buy it but don't know if it will work or not (if not should I stick to OnePlus 2?) Another things can I run Kali Nethunter with MultiROM?

Thank you for your time and patience

**Comment by binkybear** [comment]
https://github.com/offensive-security/kali-nethunter/issues/489
