### ISSUE TITLE
Random Reboots when using Wlan1

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#498]
Flashed the latest full rolling nethunter update but now the device (oneplus one cos13.1) restarts randomly once the network device (external tp-link 722n) is put in/out of monitor mode this happens with the provided script as well as with wifite or any other package that utilizes monitor mode sometimes it works perfectly and other times reboots randomly

**Comment by dingu1963** [comment]
same issue better reflash kali nethunter
