### ISSUE TITLE
Installation fails on Nexus 5

### ISSUE THREAD

**Issue by byt3bl33d3r** [offensive-security/kali-nethunter#5]
Hi, 
after flashing my nexus 5, the phone doesn't boot past the Google logo... The phone is unlocked, has TWRP 2.8.0.1 installed and the zip files sha1sum checks out. It previously had cyanogenmod with encryption enabled

**Comment by Nethunterlover** [comment]
I had issue in my Nexus 5 with wifite when I start wifite then select the WiFi networks to attack it send few deauth packets and says an output
Airodump-ng exited with status 1
Any help 
@binkybear
Waiting for reply
