### ISSUE TITLE
OnePlus 3: Installer ERROR 1

### ISSUE THREAD

**Issue by shizonic** [offensive-security/kali-nethunter#500]
I just built a flashable zip installer for the OnePlus 3 and got an ERROR 1 while the install process on TWRP.

Recovery log attached.
[recovery.txt](https://github.com/offensive-security/kali-nethunter/files/349149/recovery.txt)

**Comment by jcadduono** [comment]
That doesn't make sense. The zip extract process shows env.sh being extracted... :S maybe something preventing `cd /tmp/nethunter` from working..

**Comment by shizonic** [comment]
What could I try to fix this?

**Comment by shizonic** [comment]
Okay it was a problem of the TWRP recovery... after flashing the version of Garak the installation process worked! 😂
