### ISSUE TITLE
Errors updating metapackages

### ISSUE THREAD

**Issue by n00shE** [offensive-security/kali-nethunter#503]
Seems to be an issue with Teredo/Miredo

![download8f0eaa3f_f0_2fpictures_2fscreenshots_2fscreenshot_2016-07-07-17-51-27](https://cloud.githubusercontent.com/assets/19400884/16674481/72b8dc2c-446d-11e6-8432-48e5aaac8888.png)

**Comment by pyc0de** [comment]
Please, try this and tell me the results

mknod /dev/tun c 10 200
chmod 600 /dev/tun
ln -s /dev/tun /dev/net/tun

**Comment by n00shE** [comment]
![download411f7234_f0_2fpictures_2fscreenshots_2fscreenshot_2016-07-08-08-37-01](https://cloud.githubusercontent.com/assets/19400884/16692876/8e876674-44e7-11e6-9840-6fee38f2bab3.png)
![downloadacdb0c59_f0_2fpictures_2fscreenshots_2fscreenshot_2016-07-08-08-38-29](https://cloud.githubusercontent.com/assets/19400884/16692879/9177c0ae-44e7-11e6-975c-1db8ed19f897.png)

**Comment by pyc0de** [comment]
First, delete /dev/run and rerun those commsp

**Comment by n00shE** [comment]
cannot remove /dev/run no such file or directory

**Comment by n00shE** [comment]
oh you meant tun i assume

**Comment by n00shE** [comment]
failed to create symbolic link ./tun file exists

**Comment by pyc0de** [comment]
OK you already have simlink to /dev/run
now try to update Kali.

**Comment by n00shE** [comment]
same error

**Comment by binkybear** [comment]
In terminal in kali
```bash
rm -f /dev/net/tun
mknod /dev/net/tun c 10 200
```
Try that (worked for me)

**Comment by n00shE** [comment]
Thanks first suggestion worked!
