### ISSUE TITLE
Where to download NetHunter image for oneplus2

### ISSUE THREAD

**Issue by duchengyao** [offensive-security/kali-nethunter#504]
The [wiki](https://github.com/offensive-security/kali-nethunter/wiki) shows Kali Nethunter supports oneplus2. But I can not find the download link in `https://www.offensive-security.com/kali-linux-nethunter-download/ `

How can I download the NetHunter image for oneplus2

Thanks.

**Comment by renjen-n00b** [comment]
if you just use your computer a little bit more for searching before asking you'd ended up [here](http://forum.xda-developers.com/oneplus-2/development/nethunter-oneplus2-t3301694)

**Comment by renjen-n00b** [comment]
@jcadduono i think you should close this, and thanks for EVERYTHING

**Comment by binkybear** [comment]
You can build it from this repo or @renjen-n00b has created his own post on XDA (see above).  It will be uploaded officially soon to nethunter.com.

**Comment by duchengyao** [comment]
Thanks so much.

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
