### ISSUE TITLE
Can't build for KitKat on Bacon

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#506]
I treid to build NetHunter for KitKat for Bacon and it didn't work. It said it couldn't find a kernel image.

**Comment by jcadduono** [comment]
right, only these devices have kitkat kernels and they are not going to be maintained anymore afaict.
https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer/kernels/kitkat

there's really no reason to stay on kitkat is there?

**Comment by al3xv3gas** [comment]
For me there is every reason.I need KK for my android development project at the moment. So could you please help me making a build for KK?

**Comment by al3xv3gas** [comment]
@jcadduono

**Comment by jcadduono** [comment]
Nay but there is a guide on porting your own kernel and if you're doing any serious development then it should be easy enough

**Comment by al3xv3gas** [comment]
Where can I find this guide? @jcadduono

**Comment by jcadduono** [comment]
if u can't put in the effort to find the guide then how will u put in the effort to figure out the many other issues that may arise during kernel compilations lol..the answers are out there. i mean all it really takes is 2 seconds of google
