### ISSUE TITLE
Bleeding Edge

### ISSUE THREAD

**Issue by n00shE** [offensive-security/kali-nethunter#507]
![image](https://cloud.githubusercontent.com/assets/19400884/16786614/f7915bdc-484a-11e6-9e5c-bb3bb71d3d29.jpg)
![image](https://cloud.githubusercontent.com/assets/19400884/16786619/fedaca9a-484a-11e6-8587-6e96ecccce72.jpg)
Bleeding edge not detected even though it was added to sources list.

**Comment by binkybear** [comment]
If you are on kali-rolling the bleeding edge check should be removed: https://github.com/trustedsec/social-engineer-toolkit/blob/2590e5eb1bb01cb6ff8f263e25d9145ad4c8bf83/readme/CHANGES#L13

But you appear to be on sana still.  You can try updating your chroot to kali rolling (downloading latest image or doing it manually).
