### ISSUE TITLE
Nexus 5X with stock android, Encryption and Google Fi?

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#508]
Is it possible to get nethunter working on a Nexus 5X with FDE and Stock android? Also would it work with google Fi? If so how would I go about doing that?

**Comment by binkybear** [comment]
Full disk encryption is enabled by default for all devices in marshmallow.  I have a Nexus 5X and Google Fi is installed/working on a stock android.  Just installed from app store.

(also nethunter works fine)
