### ISSUE TITLE
OnePlusOne - NetHunter 3.0 installation error

### ISSUE THREAD

**Issue by VanasriJithendar** [offensive-security/kali-nethunter#509]
nethunter 3 instalation not completing successfuly on OnePlusOne. I boot to TWRP to flash the zip and it appears to finish but I get errors afterwards in the TWRP console see below. I can not boot into my OnePlusOne. im using latest twrp 3.0.2 becon

Error opening: '/data/local/nhsystem/kali-armhf/dev/ram12' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram14' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram16' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram10' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram13' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram15' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop6' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram4' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram9' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop0' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram7' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop1' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram0' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram3' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram11' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram6' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop4' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram8' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram1' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop5' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop7' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram2' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop3' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram5' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop2' (Not a directory)
I:Data backup size is 1998MB, free: 53757MB.
...done
I:Set page: 'flash_done'
I:operation_end - status=0
I:Set page: 'confirm_action'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set overlay: 'slideout'
I:Set overlay: ''
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /usb_otg/recovery.log

**Comment by jcadduono** [comment]
Your install went fine, these warnings are no longer an issue with rolling chroot or using new 3.1.0 installer from git. They are harmless.

**Comment by jcadduono** [comment]
As for not booting, I believe you may need to use a newer build of NetHunter. Your OS may be too new for that kernel.

**Comment by VanasriJithendar** [comment]
do you meant this version twrp-3.0.1-0-bacon.img

**Comment by jcadduono** [comment]
I mean a newer version of NetHunter. You can find prebuilt zips at:
https://idlekernel.com/nethunter/nightly/
You will need a kernel-nethunter-yourdevice-youros zip, as well as a nethunter-generic-armhf zip (choose between minimal, full, or none in which you can download via the app)

**Comment by VanasriJithendar** [comment]
after installing kernel i want to flash with nethunter night??
