### ISSUE TITLE
Nexus 5 - An error during install and now the webserver doesn't start

### ISSUE THREAD

**Issue by Rumata888** [offensive-security/kali-nethunter#51]
I already had superuser and clockworkmod installed. While installing nethunter there was an error right after chroot was installed. Something not found in kernel, I think. Now the webserver is not starting. Superuser grants permissions, browser starts with "Google chrome's connection attempt to 127.0.0.1 was rejected". Pity

**Comment by RastaManKing** [comment]
Greetings!
Nexus 5 - installed NetHunter 3.0 with TWRP over a fresh install of marshmallow 6.0.1 and it got stuck at 70% at:
 installing kernel - freeing up system space. 
Tried this twice replicating the same error, the second time after sitting for over 20mins i performed a hard reset and let it boot to nethunter, booted up fine, wifite works,
Still i dont have peace of mind, could you elaborate on how to fix this problem??
thank you in advance!
