### ISSUE TITLE
Add rtl8192cu fix to support device id 0b05:17ba

### ISSUE THREAD

**Issue by TestWestWA** [offensive-security/kali-nethunter#511]
Spent a while trying to figure out why Asus nano wireless wasn't running on the realtek rtl8192cu,  then through investigation I noted that the device ids supported by the current driver does not have this device id in it.  It has 0b05:17ab,  not 0b05:17ab.  Not sure if that's a typo,  but a bit of goggle-fu later I found https://wikidevi.com/wiki/ASUS_USB-N10_Nano which shows a link to a modified driver - https://github.com/pvaret/rtl8192cu-fixes.git.  Any chance of having this driver in the next release,  or giving as a way to install this ourselves?  (my skills are very rusty,  years sitting in corporate cubicles has dulled my brain) 

I'm guessing there will be a few worldwide folks that have the same issue due to this device id...

**Comment by binkybear** [comment]
Which device is this for?

**Comment by TestWestWA** [comment]
External Asus N10 nano usb wireless adaptor.

**Comment by binkybear** [comment]
Which android device I mean.

**Comment by TestWestWA** [comment]
Apologies.

I was using  oneplus one,  cyanogen os 12.

**Comment by renjen-n00b** [comment]
use the following :
check `lsusb`
`apt-get update`
`apt-get install firmware-realtek`

it should work by now :+1:

**Comment by Hapor** [comment]
Im trying to make this adapter work in Samsung Galaxy S5 and so far no luck. To install nethunter i've used: 
kernel-nethunter-klte-touchwiz-marshmallow-2017.11-18-1618.zip 
nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip 
After that apt-get update and apt-get upgrade. Everything seems working good, but external wifi adapter is not recognized. Output of lsusb shows it is there, but no interface in ifconfig or anywhere else. 
dmesg output:
```
[ 6667.275538] reading MSM_THERM_CH [rc = 0] [adc_code = 32633]
[ 6667.609912] max77804k-muic max77804k-muic: func:max77804k_muic_show_usb_state info->cable_name:[USB-Host]
[ 6668.284303] [SSP]: ssp_sensorhub_list - 1, 1, 7, -1 (4)
[ 6668.284466] [SSP]: ssp_sensorhub_read - 1, 1, 7, -1 (4)
[ 6669.583787] [SSP]: MSG From MCU - AR-0,12257,-9670,-4151 20, 20
[ 6669.611796] max77804k-muic max77804k-muic: func:max77804k_muic_show_usb_state info->cable_name:[USB-Host]
[ 6670.456694] !@Sync 221 [01-10 19:58:13.961]
[ 6670.613550] msm_thermal:msm_therm_temp_log Debug Temp for Sensor: 
[ 6670.613652] msm_thermal:msm_therm_temp_log (0 --- 34)(1 --- 34)(2 --- 34)(3 --- 34)(4 --- 34)(5 --- 34)(6 --- 34)(7 --- 34)(8 --- 33)(9 --- 34)(10 --- 34)
[ 6671.613961] max77804k-muic max77804k-muic: func:max77804k_muic_show_usb_state info->cable_name:[USB-Host]
[ 6672.234836] [SSP]: ssp_sensorhub_list - 1, 1, 7, 1 (4)
[ 6672.235360] [SSP]: ssp_sensorhub_read - 1, 1, 7, 1 (4)
[ 6672.413813] [SSP]: ssp_sensorhub_list - 1, 1, 7, -1 (4)
[ 6672.413874] [SSP]: ssp_sensorhub_read - 1, 1, 7, -1 (4)
[ 6672.473187] usb 1-1: new high-speed USB device number 4 using xhci-hcd
[ 6672.494576] usb 1-1: New USB device found, idVendor=0b05, idProduct=17ba
[ 6672.494583] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6672.494588] usb 1-1: Product: 802.11n WLAN Adapter
[ 6672.494591] usb 1-1: Manufacturer: Realtek
[ 6672.494595] usb 1-1: SerialNumber: 00e04c000001
[ 6672.494950] usb 1-1: ep 0x81 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 6672.495040] usb 1-1: ep 0x2 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 6672.495122] usb 1-1: ep 0x3 - rounding interval to 32768 microframes, ep desc says 0 microframes
[ 6672.602897] synaptics_rmi4_i2c 2-0020: cmd_store: Command = boost_level,2
[ 6672.603710] synaptics_rmi4_i2c 2-0020: cmd_status_show: Command status = 0
[ 6672.604043] synaptics_rmi4_i2c 2-0020: cmd_result_show: Command result = boost_level,2:OK
[ 6672.803164] Governor: enter mode 0x1
[ 6672.938204] synaptics_rmi4_i2c 2-0020: cmd_store: Command = boost_level,1
[ 6672.939048] synaptics_rmi4_i2c 2-0020: cmd_status_show: Command status = 0
[ 6672.939412] synaptics_rmi4_i2c 2-0020: cmd_result_show: Command result = boost_level,1:OK
[ 6672.959556] max77804k_get_input_current: CHG_CNFG_09(0x12)
[ 6672.960576] max77804k_get_input_current: CHG_CNFG_09(0x12)
```
Tried many things and out of ideas right now. Maybe someone have any suggestion?
