### ISSUE TITLE
bullheaad build number?

### ISSUE THREAD

**Issue by Zahkc** [offensive-security/kali-nethunter#512]
Just asking a quick question about what build number i need for my bullhead.
I know that MHC19J works but i was wondering if a could go up to MTC19Z and if it was possible to go to any NPCXXX builds.

Thanks fam

**Comment by ham4kurdish** [comment]
i think there is no difference
all build numbers works
bullhead h790 and bullhead h791 are works

**Comment by binkybear** [comment]
You should be able to use the latest Marshmallow build.
