### ISSUE TITLE
The command "netstat" is broken?

### ISSUE THREAD

**Issue by zjq777007** [offensive-security/kali-nethunter#513]
my device is nexus6p, it has flash the nethunter and rootfs option is full when I build nethunter.
when I enter "netstat -an",It is shown as follows:
root@kali:~# netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State 
tcp 0 0 0.0.0.0:6001 0.0.0.0:\* LISTEN 
Segmentation fault
is "netstat" broken?help me! thx!

**Comment by binkybear** [comment]
I am seeing same error on Nexus 5X.  Will try to track this down.

**Comment by Physicist1616** [comment]
As a workaround, `ss -a` or `ss -l` works.
