### ISSUE TITLE
Kernel Bricks Nexus 5

### ISSUE THREAD

**Issue by DarrenRainey** [offensive-security/kali-nethunter#514]
so I have nethunter working in a chroot but I cant get hid to work because the kernel isnt installed so when I build a kernel for my nexus 5 kitkat it says there are no errors and then when I flash it with twrp 3.0.2-2 it causes the device to not boot and go into a boot loop anyone know how to build a working kernel for kitkat

**Comment by binkybear** [comment]
Are you building flashable kernel from this repo?  Also, why are you still using kitkat?  Lollipop is much more stable.

**Comment by n00shE** [comment]
i have a nexus 5 and got it working on lollipop

**Comment by akrolla** [comment]
I habe same problem on lollipop with hid not working and ducky not ableto opensaved scripts asthey are greyed out

**Comment by akrolla** [comment]
I updated and havent had a probelm yet..
