### ISSUE TITLE
Missing rootfs images

### ISSUE THREAD

**Issue by lorentzm** [offensive-security/kali-nethunter#516]
Getting HTTP 404s when trying to run the build.py with --rootfs full on architectures other than armhf:
https://images.offensive-security.com/arm64/kalifs-full.tar.xz
https://images.offensive-security.com/arm/kalifs-full.tar.xz

Not sure if the the urls built by the rootfs function in build.py line 176 are incorrect or if the images were accidentally removed from images.offensive-security.com.

**Comment by jcadduono** [comment]
They simply don't exist yet and never have. Use armhf on arm64 devices, it is fine as long as kernel supports it which most do. The android binaries are static compiled so have no dependencies to worry about due to arch differences.

**Comment by lorentzm** [comment]
Thanks James.
I swapped my arch setting to armhf in the devices.cfg file and successfully built zip.
I noticed that the first entry in devices.cfg [htc_pmewl] has it's arch set arm64. Is there some reason that it shouldn't be built rootfs full?

**Comment by jcadduono** [comment]
that was just a bad commit that wasnt looked at before merge still needs to be fixed

**Comment by lorentzm** [comment]
Looks like this is all fixed up in the new devices repo. Thanks @jcadduono!
