### ISSUE TITLE
NetHuntet 3.0 installation error on my OnePlus One 64gb

### ISSUE THREAD

**Issue by VanasriJithendar** [offensive-security/kali-nethunter#517]
When im trying install nethunter 3.0 on my OnePlus One 64gb, im getting errors, and im using 
Android 6.0.1
Cynogenmod 12.0-20160713-NIGHTLY-bacon
Kernel version 3.4.112-cynogenmod-gd7227f6
Twrp 3.0.2 becon
Please guide me how install and which rom i have to use??

Errors are listed below here:

Error opening: '/data/local/nhsystem/kali-armhf/dev/ram12' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram14' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram16' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram10' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram13' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram15' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop6' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram4' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram9' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop0' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram7' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop1' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram0' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram3' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram11' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram6' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop4' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram8' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram1' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop5' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop7' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram2' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop3' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/ram5' (Not a directory)
Error opening: '/data/local/nhsystem/kali-armhf/dev/loop2' (Not a directory)
I:Data backup size is 1998MB, free: 53757MB.
...done
I:Set page: 'flash_done'

![screenshot_20160717-210454](https://cloud.githubusercontent.com/assets/20453233/16901527/453e2eec-4c64-11e6-96e3-e8fe094e4194.png)

**Comment by jcadduono** [comment]
build new installer from git, hopefully new release soon...
you can also just flash these 2 files in twrp:
https://idlekernel.com/nethunter/nightly/3.1.0-20160714-1621/nethunter-generic-armhf-kalifs-full-rolling-3.1.0-20160714-1621.zip
https://idlekernel.com/nethunter/nightly/3.1.0-20160714-1621/kernel-nethunter-oneplus1-marshmallow-3.1.0-20160714-1621.zip

**Comment by VanasriJithendar** [comment]
Have to flash 1st kernel or nethunter

**Comment by jcadduono** [comment]
Doesn't mattet

**Comment by VanasriJithendar** [comment]
After flashing both zip files i have successfully installed nethunter and the problem is battery 100% bug plz give me solution @jcadduono

**Comment by lorentzm** [comment]
You might have a look here #485

**Comment by LiYaHX** [comment]
@jcadduono hello, I have the same problem, but when i follow your solution , the link is 404.

[https://idlekernel.com/nethunter/nightly/3.1.0-20160714-1621/nethunter-generic-armhf-kalifs-full-rolling-3.1.0-20160714-1621.zip](url)
[https://idlekernel.com/nethunter/nightly/3.1.0-20160714-1621/kernel-nethunter-oneplus1-marshmallow-3.1.0-20160714-1621.zip](url)

could you help me please?  thank you.

**Comment by LiYaHX** [comment]
@jcadduono I got it, but still thank you.  :)
