### ISSUE TITLE
Tp link tl-wn727n drivers for NetHuntet 3.0 on OnePlus One 64gb

### ISSUE THREAD

**Issue by VanasriJithendar** [offensive-security/kali-nethunter#518]
Im using nethuntet 3.0 and i have tplink tl-wn727n usb wifi adopter. My oneplus one not recognizing the device where to get drivers for my tp link tl-wn7227n drivers??

**Comment by renjen-n00b** [comment]
use this command to have its binary firmware installed,

`apt-get install firmware-misc-nonfree`

the above contains various drivers for the linux kernel.

**Comment by VanasriJithendar** [comment]
Is this device supports nethunter??

**Comment by bkr32** [comment]
Yes its supported and works out of the box you need no drivers and if you don't know how to use it simply google

**Comment by VanasriJithendar** [comment]
My ralink mt7601u detecting but not showing in iwcomfig or ipconfig @bkr32 @renjen-n00b @zaventh @jmingov  

![screenshot_20160722-192841](https://cloud.githubusercontent.com/assets/20453233/17065566/26ef3f08-5060-11e6-9d51-d5bc673ae4bd.png)

**Comment by renjen-n00b** [comment]
@VanasriJithendar there's no ipconfig, maybe you wanted to try ifconfig?
first you really need to know that your ralink is already supported by the nethunter's kernel and you need no drivers for that but maybe you've missed something so here's a hopeful workaround but first @jcadduono @binkybear should check if it'll work **< i'm not responsible of anything happens in a bad way >**

1-please check lsusb and see if its showing there.
2-unplug your ralink adapter from the phone.
3-download and install this :
`https://github.com/torvalds/linux/tree/master/drivers/net/wireless/mediatek`
or use "svn export" if you know how to use it.
4-
`cd mt7601/src`
`make`
`sudo make install`
`sudo mkdir -p /etc/Wireless/RT2870STA/`
`sudo cp RT2870STA.dat /etc/Wireless/RT2870STA/`
`sudo modprobe mt7601Usta`

source: [here](http://askubuntu.com/questions/457061/ralink-mt7601u-148f7601-wi-fi-adapter-installation)

**Comment by VanasriJithendar** [comment]
@renjen-n00b  
How to downlad https://github.com/torvalds/linux/tree/master/drivers/net/wireless/mediatek drivers
I tries git clone http://github.com/torvalds/linux.git
But its 4gb
And svn export not working on nethunter
Plz guide the detailed procedure

ThanQ

**Comment by bipul121** [comment]
I also have same problem
