### ISSUE TITLE
Ralink mt7601u drivers for NetHuntet 3.0 on OnePlus One 64gb

### ISSUE THREAD

**Issue by VanasriJithendar** [offensive-security/kali-nethunter#520]
Ralink mt7601u detecting but not showing in ifconfig or iwconfig

![screenshot_20160722-192841](https://cloud.githubusercontent.com/assets/20453233/17059911/11463c08-5045-11e6-9591-c57d8528d945.png)

**Comment by renjen-n00b** [comment]
#518 you really dont have to duplicate such stuff as its not a nethunter issue.

**Comment by VanasriJithendar** [comment]
@renjen-n00b 
How to downlad https://github.com/torvalds/linux/tree/master/drivers/net/wireless/mediatek drivers
I tries git clone http://github.com/torvalds/linux.git
But its 4gb

Plz guide the detailed procedure

ThanQ
