### ISSUE TITLE
oneplus3 can't boot after flash

### ISSUE THREAD

**Issue by 1807374010** [offensive-security/kali-nethunter#522]
I had flashed the image built by 'nethunter-installer' 

python ./build.py --device oneplus3 -m --rootfs full

But the phone boot such a long time after this.It didn't boot until the battery is low and shutdown.what's wrong?I have no idea about this.

**Comment by jcadduono** [comment]
lol 1-807-374-xxxx is a local phone number where i live

what version of oxygenos are you on?

**Comment by 1807374010** [comment]
OxygenOS 3.2.1.Actually 1807374010 is my QQ number.The oxygenOS had a new version 3.2.2 yesterday. Will it work well on this new version?

**Comment by jcadduono** [comment]
looks like it should work just the same, oneplus just released a kernel update in their OSS branch but it wasn't really much more than dash charging support

**Comment by 1807374010** [comment]
But why I can't boot the phone after flash?There just a logo of 'kali' shining all the time……

**Comment by anupritaisno1** [comment]
Maybe SuperSU kernel patch issue https://github.com/offensive-security/kali-nethunter/issues/525
Flash it and see if you get a similar result as me
