### ISSUE TITLE
OP3

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#523]
Just curious if the OP3 will become the "prefered" device?

**Comment by jcadduono** [comment]
preferred generally means it's something one of us have on hand for testing, not that it's the best device to buy.
i've looked at the OP3, not sure if binkybear has interest in owning one, but i'm probably going to end up with the note 7 soon.

**Comment by binkybear** [comment]
No plans as of yet but I've heard good reviews.  Maybe one day I'll get one so until then it is not the preferred device but I will continue to update kernel for it.
