### ISSUE TITLE
Tp link tl-wn722n drivers for NetHuntet 3.0 on OnePlus One 64gb

### ISSUE THREAD

**Issue by VanasriJithendar** [offensive-security/kali-nethunter#524]
### Device:
Oneplus one 64gb

### Version (Kitkat/Lollipop/Marshmallow/Nougat):
MarshMallow cynogenmod

## Issue:
My tplink wn722n detecting in nethunter using lsusb
But not recognized in ifconfig iwconfig
Pls give me a solution

**Comment by 1807374010** [comment]
Did you up it?
ifconfig wlan1 up

**Comment by VanasriJithendar** [comment]
Yes but no use @1807374010

**Comment by VanasriJithendar** [comment]
Yes but no use @1807374010

**Comment by vay3t** [comment]
ifconfig -a ;)

**Comment by VanasriJithendar** [comment]
@vay3t 
Did everything but no use
