### ISSUE TITLE
[oneplus2] SuperSU patch is ignored causing the ROM to be unable to boot on latest kernel build

### ISSUE THREAD

**Issue by anupritaisno1** [offensive-security/kali-nethunter#525]
### Device:
Oneplus 2 (one a2003)

### Version (Kitkat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo or downloaded from website:

Downloaded from website

## Issue:
The SuperSU patch is ignored by the installer
This is a huge issue because the ROM doesn't boot up without this patch

I downloaded Kali nethunter for cm 13 from the official site

**Comment by anupritaisno1** [comment]
![screenshot_2016-07-29-05-24-41](https://cloud.githubusercontent.com/assets/17122638/17246059/54fd8ec6-55a7-11e6-97de-f87b55d8be1c.png)
Screenshots attached

**Comment by anupritaisno1** [comment]
SuperSU not found in installer error.... If I flash an older build it works just fine. I am using latest official twrp

The problem is, if SuperSU is installed to /system without this patch, the ROM simply doesn't boot up at all

**Comment by anupritaisno1** [comment]
I found a workaround for now
Flash an old kernel build and flash the current bugged out build over it and the rom boots but flashingthe most recent nethunter build alone makes the ROM unbootable because of no sepolicy kernel patch for SuperSU

**Comment by 1807374010** [comment]
So,can I flash a nosu image on the newest cm13 rom?

**Comment by renjen-n00b** [comment]
[Check this](http://forum.xda-developers.com/showpost.php?p=67955319&postcount=235)

**Comment by anupritaisno1** [comment]
That would answer the question given that I built the rom but I'm just using the official cm nightlies
![screenshot_2016-07-29-08-45-25](https://cloud.githubusercontent.com/assets/17122638/17250450/0a903d8c-55c2-11e6-8485-f00341bf4000.png)
This is last week's official nethunter kernel build

![screenshot_2016-07-29-08-46-00](https://cloud.githubusercontent.com/assets/17122638/17250477/26ac687e-55c2-11e6-8360-fad2d7cae5f0.png)
And this is this week's official build. Here the supolicy patch fails but it succeeds if I use an older official kernel

Also, my PC is not that powerful for building stuff, everything used- from cm to the kernels was official and not compiled by me

**Comment by anupritaisno1** [comment]
Btw I could post recovery logs on pastebin, the issue isn't that a patch fails, the issue is that the ROM doesn't boot as the patch is missing. If I only flash the latest official nethunter build, the ROM doesn't boot

Official cm 13 latest nightly btw

Without flashing an older official kernel over the newer one, the ROM doesn't boot

**Comment by 1807374010** [comment]
I can boot by flashed latest official nethunter kernel then flashed supersu ,flashed the nethunter nokernel-nosu-image at last.

**Comment by anupritaisno1** [comment]
Let me check, if that's the case I'll close this issue

**Comment by anupritaisno1** [comment]
Well that's for the oneplus 3 and this issue has been opened for the oneplus 2😉

**Comment by 1807374010** [comment]
But you should reinstall kali-chroot-image after flash.

**Comment by anupritaisno1** [comment]
Why exactly?

**Comment by 1807374010** [comment]
I don't known~I had flashed my phone more than 30 times...

**Comment by jcadduono** [comment]
MY BAD GUYS

https://github.com/offensive-security/kali-nethunter/commit/6834a9fc33af0ac237c9043153437b5194c18313

fixed (i hope) - new builds up on my nightly mirror

**Comment by 1807374010** [comment]
Did the oneplus 3 fix too?

**Comment by anupritaisno1** [comment]
Problem has been solved in latest offi

**Comment by anupritaisno1** [comment]
cial build
