### ISSUE TITLE
Atheros AR9271 device support for nethunter

### ISSUE THREAD

**Issue by VanasriJithendar** [offensive-security/kali-nethunter#527]
### Device:
One plus one 64gb

### Version (Kitkat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.0.1

## Issue:
My tp-link wn722n device not supporting in net hunter
I installed firmware father is and updated Kali
And used ifconfig set wlan1 up but it showing no such device.

**Comment by bkr32** [comment]
really again?
for the last time this device is supported, go to custom commands and click "Wlan1 Monitor Mode"

**Comment by a7ent** [comment]
root#   modprobe ath9k_htc
root#    ifconfig -a     (see if its listed)
root#    ifconfig wlan0 up

**Comment by VanasriJithendar** [comment]
@a7ent @bkr32 
![screenshot_20160731-170758](https://cloud.githubusercontent.com/assets/20453233/17276262/73e6d59a-5741-11e6-8397-fa9a9e99d99c.png)

**Comment by jcadduono** [comment]
You're not going to be able to use any of nethunter USB/otg functions without installing a nethunter kernel for your device. You have CyanogenMod kernel.

**Comment by balveer231** [comment]
Bro in my case this is not showing wlan1 option in wifite attack

**Comment by bkr32** [comment]
Set wlan1 to monitor mode and then start wifite

**Comment by balveer231** [comment]
How to set wlan1 in monitor mode
