### ISSUE TITLE
MSFPC stopped working?

### ISSUE THREAD

**Issue by n00shE** [offensive-security/kali-nethunter#528]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from website.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
version 3.4.0-g12d78b6-dirty root@kali

## Issue:
![screenshot_2016-08-01-17-24-54](https://cloud.githubusercontent.com/assets/19400884/17313087/98c4d69c-580d-11e6-8d36-a9d66c03a3f8.png)

**Comment by binkybear** [comment]
There's a wonderful example in the help file:
```bash
Example: /usr/bin/msfpc windows 192.168.1.10        # Windows & manual IP.
```
That syntax works for me.  If you need more examples check out mpc page:
https://github.com/g0tmi1k/mpc

**Comment by n00shE** [comment]
![screenshot_2016-08-02-17-11-55](https://cloud.githubusercontent.com/assets/19400884/17349612/5236d924-58d4-11e6-9a35-4032d70caa02.png)
Still doesn't work... Even launching from nethunter app

**Comment by binkybear** [comment]
Try updating your msfpc.  Works fine for me on 1.4.2.
