### ISSUE TITLE
nethunter fails to load atheros firmware on nexus 5x marshmellow

### ISSUE THREAD

**Issue by thesle3p** [offensive-security/kali-nethunter#529]
So I just flashed Nethunter onto my Nexus 5x and everything but external wireless seems to be working, I apt-get installed  firmware-firmware and tried manually copying htc_9271.fw to /system/etc/firmware but I still can't get wlan1 to show up and when I run modprobe_ath9k_htc I get this error:

```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.173-g71e278e-dirty/modules.dep.bin' modprobe: FATAL Module ath9k_htc not found in directory /lib/modules/3.10.173-g71e278e-dirty
```

Here is what dmesg shows: 

```
[ 1248.217069] usb 1-1: new high-speed USB device number 55 using xhci-hcd
[ 1248.240692] usb 1-1: New USB device found, idVendor=0846, idProduct=9030
[ 1248.240793] usb 1-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[ 1248.240924] usb 1-1: Product: WNA1100
[ 1248.240993] usb 1-1: Manufacturer: NETGEAR WNA
[ 1248.241129] usb 1-1: SerialNumber: 12345
[ 1248.243783] usb 1-1: ath9k_htc: Firmware htc_9271.fw requested
[ 1248.320140] usb 1-1: ath9k_htc: Firmware - htc_9271.fw download failed
[ 1248.320247] usb 1-1: USB disconnect, device number 55
[ 1248.320714] usb 1-1: ath9k_htc: USB layer deinitialized
[ 1248.576975] usb 1-1: new high-speed USB device number 56 using xhci-hcd
[ 1248.577468] usb 1-1: Device not responding to set address.
[ 1248.780291] usb 1-1: Device not responding to set address.
[ 1248.983664] usb 1-1: device not accepting address 56, error -71
[ 1249.263292] usb 1-1: new high-speed USB device number 58 using xhci-hcd
[ 1249.263918] usb 1-1: Device not responding to set address.
[ 1249.466857] usb 1-1: Device not responding to set address.
[ 1249.670541] usb 1-1: device not accepting address 58, error -71
[ 1249.950395] usb 1-1: new high-speed USB device number 60 using xhci-hcd
[ 1249.950957] usb 1-1: Device not responding to set address.
[ 1250.153223] usb 1-1: Device not responding to set address.
[ 1250.356763] usb 1-1: device not accepting address 60, error -71
[ 1250.636985] usb 1-1: new high-speed USB device number 62 using xhci-hcd
[ 1250.637877] usb 1-1: Device not responding to set address.
[ 1250.840866] usb 1-1: Device not responding to set address.
[ 1251.043545] usb 1-1: device not accepting address 62, error -71
[ 1251.528391] usb 1-1: new high-speed USB device number 65 using xhci-hcd
[ 1251.529060] usb 1-1: Device not responding to set address.
[ 1251.733593] usb 1-1: Device not responding to set address.
[ 1251.936503] usb 1-1: device not accepting address 65, error -71
```

It looks like it can't find the firmware, the directory modprobe is looking in does not seem to exist in the chroot and dmesg makes it look like it can't find the .fw file in /system/, what should I do?

**Comment by binkybear** [comment]
Double check you flashed the kernel in settings > about.  You can try reflashing the kernel again, this will copy the firmware to /system/etc/firmware.  If you want to do it manually and believe you have the right kernel installed then you need to make sure you remount /system as rw.

If you need a kernel you can rebuild from this repo or download fromhttps://idlekernel.com/nethunter/nightly/

**Comment by thesle3p** [comment]
Flashed kernel twice no luck, same error message.

-----Original Message-----

**Comment by thesle3p** [comment]
Still not working, any advice?

**Comment by binkybear** [comment]
What kind of cable are you using?  Modprobe isn't going to work because it's not actually a module-it's baked into kernel.  The download failed so check the /system/etc/firmware manually (outside of kali) to make sure the firmware file is there AND correct size (you can compare with file in repo).  

I would check firmware file first though.

**Comment by thesle3p** [comment]
So when I run ls -l in /system/etc/firmware I get this:
```
-rw-r--r-- root     root        83968 2016-08-10 23:05 ar9170-1.fw
-rw-r--r-- root     root         3508 2016-08-10 23:05 ar9170-2.fw
-rw-r--r-- root     root        13424 2016-08-10 23:05 carl9170-1.fw
-rw-r--r-- root     root        72992 2016-08-10 23:05 htc_7010.fw
-rw-r--r-- root     root        51272 2016-08-10 23:05 htc_9271.fw
-rw-r--r-- root     root         8192 2016-08-10 23:05 rt2561.bin
-rw-r--r-- root     root         8192 2016-08-10 23:05 rt2860.bin
-rw-r--r-- root     root         8192 2016-08-10 23:05 rt2870.bin
-rw-r--r-- root     root         4096 2016-08-10 23:05 rt3070.bin
-rw-r--r-- root     root         2048 2016-08-10 23:05 rt73.bin
drwxr-xr-x root     root              2016-08-10 23:05 rtlwifi
drwxr-xr-x root     root              2009-01-01 03:00 wcd9320
drwxr-xr-x root     root              2009-01-01 03:00 wlan
drwxr-xr-x root     root              2016-08-10 23:05 zd1211
```

Does that Look right?

**Comment by thesle3p** [comment]
looks like kali is looking for htc_9271.fw which is not there, gunna try manually copying that over.

**Comment by thesle3p** [comment]
Still the same error message. I confirmed htc_9271.fw copied over to /system/etc/firmware but still get the firmware download failed error.

**Comment by thesle3p** [comment]
Ok, after flashing the cache and app data for Media and External storage in Android I can get the firmware to load but I then get a "Service Connection time out for: 256" error from usb 1-1 and a "ath9k_htc: Unable to initialize HTC services" error from ath9k_htc 1-1:1.0 in dmesg.

**Comment by binkybear** [comment]
I am runnig 5x with latest kernel (from repo) and atheros is working with usbc > otg cable.  What kind of cable are you using?  (Not saying that's issue)

**Comment by thesle3p** [comment]
A friend is in the exact same boat as us and is using this: https://www.amazon.com/gp/product/B017GNH5RO/ref=ox_sc_act_title_1?ie=UTF8&psc=1&smid=A14L9DIA3NK9B0 no problem, so I am trying that as well still no dice.

**Comment by binkybear** [comment]
So I did a test one with a usb-c adapter:

http://imgur.com/a/zjWyH

It appears to not work with usb-c adapter but usb-c otg cable works fine.  Which is the opposite of how it worked on OnePlus2.

**Comment by thesle3p** [comment]
I am not doubting that it works for you and others, I am just trying to figure out what I did wrong. Could it be a defective wireless card? When I get a chance I will confirm the card still works on my Nexus 7 2013.

**Comment by binkybear** [comment]
@thesle3p - I am suggesting not using the usb-c adapter and getting a usb-c otg cable instead (from picture).

**Comment by thesle3p** [comment]
Ok, I got a new cable and monitor mode and packet injection works but when ever I try and put my TP-link card into master mode using hostapd-wpe or Mana I get a ```Failed to initialize interface```` error message, I confirmed in the config files that wlan1 is specified not wlan0 but it still won't go into master mod.
