### ISSUE TITLE
[Nexus5x] PostgreSQL-Error: cannot create shared memory

### ISSUE THREAD

**Issue by NW1337** [offensive-security/kali-nethunter#530]
### Device:
Nexus5x
BuildNr MMB29K

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Android 6.0.1

KernelVersion:
3.10.73-g71e278e-dirty
root@ubuntu #8
Sun May 29 17:51 UTC 2016

### Built from repo (date and build command) or downloaded from website (links):
Built net hunter with help from here:
https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter

Then followed this:
https://github.com/offensive-security/nethunter-LRT

Used the correct FactoryImg from here:
https://developers.google.com/android/nexus/images?hl=en

used TWRP:
twrp-3.0.2-0-bullhead.img

used SuperSU:
I think it was v2.76, the neweset, not beta

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.73-g71e278e-dirty (root@ubuntu) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #8 SMP PREEMPT Sun May 29 17:51:44 UTC 2016

## Issue:
Whenever I try to "service postgresql start"    ###or "msfdb init" i get the following error:

root@kali:~# service postgresql start
[....] Starting PostgreSQL 9.5 database server: main
[....] The PostgreSQL server failed to start. Please check the log output: 2016-08-03 08:17:18 UTC [26538-1]
FATAL: could not create shared memory segment: Function not implemented 2016[FAIL3 08:17:18 UTC [26538-2] DETAIL: Failed system call was shmget(key=5432001, size=40, 03600). ... failed!
 failed!

This seems to have solved the problem for another person, but the download link of the kernel is no more valid:
https://github.com/offensive-security/kali-nethunter/issues/374

I already found out that there are no files like /proc/sys/kernel/shm* (shmmax, shmall and so on) so this might be really a kernel problem, as stated above in the linked issue 374

With kernels i am not familiar at all, so pls point me to a link where i can download the correct kernel and explain how to flash that thing...

Thanks in advance for any help!

**Comment by jmingov** [comment]
`Linux version 3.10.73-g71e278e-dirty (root@ubuntu)` <-- Looks like the nethunter kernel didnt flashed as you can see in the issue #374 it should be: `root@kali`

Which command you used to build nethunter? (python build.py [this part])

You should try to flash the kernel alone (you can also build it from repo or use this build from @jcadduono site).

[https://idlekernel.com/nethunter/nightly/3.1.0-20160802-0230/kernel-nethunter-bullhead-marshmallow-3.1.0-20160802-0230.zip](bullhead nethunter kernel)

Jaime

**Comment by NW1337** [comment]
Thanks for the quick answer!

The parameters used for build.py where: -d bullhead -m --rootfs full --release v3.0

After twrpFlash.sh from LRT my phone tried about an hour to boot, it should take some time it was said but i thought that was too long so i tunred it off & on again, then it booted into kali.
Did i maybe thereby cancel the kali kernel flashing? I also had "swipe pattern required for booting" on, could that have been a problem?

Anyways:
Downloaded now "kernel-nethunter-bullhead-marshmallow-3.1.0-20160802-0230"
How do i flash the kernel? cp kernel zip to phone & twrp, but what then?

**Comment by jcadduono** [comment]
if you have twrp installed already its probably easier to just copy the zips over mtp and flash them in twrp than to use LRT
you can install nethunter 3.0+ zips in any order over each other as much as you want

**Comment by NW1337** [comment]
Tried flashing only the kernel: copied the kernel zip with mtp to phone and started to twrp, then install and selected the zip. No error messages, but when i restart it still says in settings->about root@ubuntu

Any ideas why this doesnt work?

**Comment by jcadduono** [comment]
```
jc@sateda:~/build/kali-nethunter/nethunter-installer/devices/marshmallow/bullhead$ gzip -d < Image.gz-dtb | strings | grep '^Linux version'
Linux version 3.10.73-g71e278e-dirty (root@ubuntu) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #8 SMP PREEMPT Sun May 29 17:51:44 UTC 2016
```

looks like that **is** the nethunter kernel :)

**Comment by NW1337** [comment]
That confuses me even more...
Then why jmingov and this issue https://github.com/offensive-security/kali-nethunter/issues/374 say its supposed to be root@kali?

And more importantly why i still get the same error from my first post?

**Comment by jcadduono** [comment]
it should have been, but it must have been compiled in someone else's environment. most binkybear's kernels are root@kali, mine are all jc@gallifrey, maybe binkybear compiled it at work? :D

dunno, its missing a couple configs maybe, not many bullhead users running nethunter

**Comment by NW1337** [comment]
Hm and what can i do now to fix this? Dont know how to compile a kernel... :(

**Comment by binkybear** [comment]
root@ubuntu was correct (one of my other build boxes).  I think I ran into error with shmmax and didn't fix.  Will push an update to nethunter-devices tonight or tomorrow.

**Comment by NW1337** [comment]
Ok thanks.
And ty for the quick help.
Ill bookmark this, pls post when rdy.

**Comment by jcadduono** [comment]
keep an eye on https://github.com/offensive-security/nethunter-devices/commits/master

**Comment by jmingov** [comment]
My bad @NW1337, i was wrong mate.

> Then why jmingov and this issue #374 say its supposed to be root@kali?

We used to build always on a kali box.

br

**Comment by NW1337** [comment]
Do i have to flash Image.gz-dtb as is or unpack it first?

**Comment by binkybear** [comment]
You should be able to flash if you have the devices folder in your repo:
```bash
python build.py -d bullhead -m -k
```

**Comment by NW1337** [comment]
Okidoki, thank you!
I have to do git clone again, right?
Will flashing the kernel erase my user data?

**Comment by jcadduono** [comment]
It will not erase anything, you can cd to the devices folder and use
```sh
git fetch
git rebase
```
this should bring you up to the latest. if you encounter issues updating the repo, you can use (after fetch)
```sh
git reset --hard origin/master
git clean -xdf
```
this will also reset any changes you've made in there

then simply go back to the nethunter installer dir and do the command binkybear told ya in his last comment

**Comment by NW1337** [comment]
That worked like a charm.
The msfdb init problem is no more there, it just finishes now saying db already initialized.

With the new kernel my phone is now always in portrait mode, even though rotation is turned on... can be because of the new kernel?

**Comment by binkybear** [comment]
@NW1337 - Nothing was changed in kernel that I know of as far as locking screen rotation.  (Just posix/syscalls).  I am glad that the kernel did fix issue.  Double check the pull down for screen lock rotation and try restarting.  That's all I can think of.

**Comment by NW1337** [comment]
Did double check it & had restarts between tests. Still with the new kernel only portrait & the old one can both.

It definitely is somehow the new kernel: with the old one this scale app works:
https://play.google.com/store/apps/details?id=com.gamma.bubblelevel&hl=de

With the new kernel the bubbles dont move when i move/rotate the phone, which indicates that gyroscope isnt working and therefore the screen wont rotate because no movements are detected at all...

**Comment by NW1337** [comment]
Sorry for my late answer, forgot to check commits.
Postgresql still works, rotation still not.

**Comment by binkybear** [comment]
I had same issue but when to settings > display > when device is rotated -> Rotate contents of the screen.  Works now.

**Comment by NW1337** [comment]
Think i get what u mean but couldnt reproduce that:(
Went to settings>display rotated phone and then changed from stay in portrait mode to rotate screen contents, nothing happened...

**Comment by binkybear** [comment]
@NW1337 - Yes, I'm using a Nexus 5X for daily phone and rotation worked/works fine.
