### ISSUE TITLE
Wrong reference link in Wiki page

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#531]
@jcadduono @jmingov 
Hi guys, just let you know the there is a wrong reference link for the "Bluetooth" under point 8 in wiki page, it is referred back to the wiki page.

![123](https://cloud.githubusercontent.com/assets/16465163/17424164/d25ebe5c-5af3-11e6-916c-a3ae13fc6c8f.png)

Thanks.

**Comment by jcadduono** [comment]
I think we're just kinda hoping someone will come along and write a wiki page for it :$

Unfortunately I have no experience with BT/RFCOMM to write anything about it.
