### ISSUE TITLE
Hostapd-karma.conf errors

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#532]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Configuration file: /sdcard/nh_files/configs/hostapd-karma.conf
Line 39: unknown configuration item 'enable_karma'
Line 42: unknown configuration item 'enable_karma_loud'
2 errors found in configuration file '/sdcard/nh_files/configs/hostapd-karma.conf'
Failed to set up interface with /sdcard/nh_files/configs/hostapd-karma.conf
Failed to initialize interface

Apologies if this has been brought up previously

**Comment by ozsteyr** [comment]
From all Mana related tools.

**Comment by binkybear** [comment]
It appears this was a change with mana configuration files/mana that we missed:
https://github.com/sensepost/mana/commit/438d1fe8233b29b6a0cfdf38f0de97405f262270#diff-924fc5161937f4c80927e6c0667fddbdR54

Can you try changing in /sdcard/nh_files/configs/hostapd-karma.conf
enable_mana=1
mana_loud=0

**Comment by ozsteyr** [comment]
All good, thank you.
