### ISSUE TITLE
nexus5x

### ISSUE THREAD

**Issue by 877286291** [offensive-security/kali-nethunter#534]
### Device:

nexus5x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

bullhead
### issues: where can i download the netthunter for nexus5x ?? How can i install the iso to nexus5x

**Comment by binkybear** [comment]
Build yourself from repo or download from:
https://idlekernel.com/nethunter/nightly/3.1.0-20160806-1435/

You need bullhead zip file and https://idlekernel.com/nethunter/nightly/3.1.0-20160806-1435/nethunter-generic-armhf-kalifs-full-rolling-3.1.0-20160806-1435.zip.  Flash in TWRP.

**Comment by 877286291** [comment]
should i flash the two zip in TWRP

**Comment by binkybear** [comment]
Yes.

**Comment by 877286291** [comment]
Thank u
