### ISSUE TITLE
camera and sensor not working

### ISSUE THREAD

**Issue by hadihmh** [offensive-security/kali-nethunter#535]
### Device:

nexus 5x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

marshmallow

## Issue:
I install nethunter after that my phone sensor and camera not working.what I do?help me please

**Comment by binkybear** [comment]
Can you confirm you flashed kernel from repo?  I have it flashed on my phone and everythings working fine.

**Comment by hadihmh** [comment]
I'm so sorry I can't. I'm flashing my rom and I try to install by multirom and install on cm13 but after install dont working my rom.i don know what is reason .can you help me?what i do?sorry for my English

**Comment by binkybear** [comment]
I would first start by not using CM and using ASOP (not CM).  CM usually uses a different branch for kernel_msm so the kernel may be incompatible.  We usually don't support CM based ROMs.

**Comment by UnGast** [comment]
Hi. I don't use CM and have the same issue.

**Comment by vay3t** [comment]
@UnGast you have MultiROM?

**Comment by hadihmh** [comment]
I test many way to install this kernel but i can't. I install in my base nexus rom but my camera and sensor does not work

**Comment by UnGast** [comment]
@vay3t no I don't have MultiROM.

**Comment by vay3t** [comment]
try install again, clean ur device with https://github.com/offensive-security/nethunter-LRT and install factory image. (first test ur device without nethunter) last, use sure to clone the latest version of https://github.com/offensive-security/kali-nethunter .install without CM (i recommend exclusively AOSP)

**Comment by UnGast** [comment]
@vay3t thanks for your answer. Yesterday I already tried reinstalling the factory image (the sensors worked) and installing Nethunter again (sensors stopped working).

**Comment by UnGast** [comment]
With "the sensors worked" I mean that the camera and rotation worked. I did not test the other things.

**Comment by vay3t** [comment]
install last version of nethunter (remove the older clone and download the last) install kali-nethunter again. and create the new zip. using this command.

```
git clone https://github.com/offensive-security/kali-nethunter
cd kali-nethunter/nethutner-installer/ && ./bootstrap.sh
./build.py -d bullhead -m -f 
```

if you still have problems, please send dmesg. @jcadduono can help you

**Comment by binkybear** [comment]
I'm currently running latest kernel with now camera issues (sensors).  I can't reproduce this error.  If you could confirm you are using my latest kernel and latest ASOP.

**Comment by cocoy2814** [comment]
I also have this issue. Returning to stock android, the camera works. Recompiled a few minutes ago and issue persists.

Compiled: python build.py -d bullhead -m --rootfs full 

cat /proc/version ->>

Linux version 3.10.73-kali (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Sun Aug 7 12:51:54 CDT 2016

Any recommendation on how to fix would be welcome.

**Comment by UnGast** [comment]
@vay3t I tested it again with the stock image and all sensors worked. Back in Nethunter they stopped working again.

cat /proc/version

Linux version 3.10.73-kali (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Sun Aug 7 12:51:54 CDT 2016

**Comment by vay3t** [comment]
@UnGast @cocoy2814 please send dmesg

**Comment by cocoy2814** [comment]
@vay3t here you go. 

[dmesg-nexus5x-nethunter.txt](https://github.com/offensive-security/kali-nethunter/files/422343/dmesg-nexus5x-nethunter.txt)

**Comment by UnGast** [comment]
@vay3t here's mine.

[dmesg.txt](https://github.com/offensive-security/kali-nethunter/files/422689/dmesg.txt)

**Comment by UnGast** [comment]
Gret! Everything is working now!

**Comment by hadihmh** [comment]
What is happen?

**Comment by cocoy2814** [comment]
Confirming from my end that everything is working. Thanks!

**Comment by cocoy2814** [comment]
@hadihmh camera and sensors should be working after binkybear's latest patch.

**Comment by hadihmh** [comment]
@cocoy2814
Which is the latest patch do you mean ? Send it to me so I install ?

**Comment by UnGast** [comment]
@hadihmh Just call ./bootstrap.sh again and rebuild Nethunter.

**Comment by hadihmh** [comment]
Thank

**Comment by jcadduono** [comment]
@UnGast very inefficient to run bootstrap.sh again, you can simply cd to devices and type:
```sh
git fetch && git rebase
```
this will update you to the latest commit and apply any commits you have made on top of it

**Comment by Headstam** [comment]
I've the same problem, but I'm on an oneplus 2 my cam can't connect error help my. I've LineageOS 14.1 Nougat 7.1.2 and now saw my light can't work too :/
