### ISSUE TITLE
Getting the error ;67R whenever issued any Custom Command from Nethunter App.

### ISSUE THREAD

**Issue by paranoidninja** [offensive-security/kali-nethunter#538]
### Device:

Oneplus One

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow 6.0.1 CyanogenMod 13.0

### Built from repo (date and build command) or downloaded from website (links):

Just clicked App Update from the Nethunter App. It Showed new app v3.1 available. After installing the whole issue started.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.111-Phreya-2.6 (root@valhalla) (gcc version 4.9.4 20150629 (prerelease) (crosstool-NG 1.20.0 - Linaro GCC 2015.06 - Cortex-A15) ) #1 SMP PREEMPT Fri Apr 15 02:09:39 EDT 2016

## Issue:

Getting the error " ;67R syntax error near unexpected token `;' whenver issued any whatsoever command from the Nethunter App. Tried reinstalling busybox and all necessary stuff.. Still the same issue. If all else fails, can you please guide me towards a nethunter 3.0 apk?

**Comment by vay3t** [comment]
please view #478

**Comment by jcadduono** [comment]
i wonder if this is a sana chroot issue

**Comment by paranoidninja** [comment]
Nah...I uninstalled the nethunter 3.1, and installed 3.0.5 and the problem is gone now.....Thinking of decompiling and checking the apk build....Any help would be great

**Comment by paranoidninja** [comment]
The issue is with 3.1 Apk...

**Comment by binkybear** [comment]
@paranoidninja - You don't need to decompile.  You can view the source code: https://github.com/offensive-security/nethunter-app

You can also look at commits to see what has changed.

**Comment by paranoidninja** [comment]
From the commit, it only looks like the Mana toolkit is changed and Wardriving has been added, but one thing I can't understand is how can that break Terminal Custom commands. The 3.0.5 works flawlessly except the mitmf where there is always a black-ips issue, but that can be ignored since I use terminal for that. Tomorrow will try this new commit by replacing a few files with the older one...need to go to sleep..now its too late

**Comment by paranoidninja** [comment]
Nah...Still the same...Let me know if any update changes those things in the build.

**Comment by vay3t** [comment]
is not a serious issue only occurs on the first start of kali terminal after turning on the device. if you have any solution, I would appreciate you.

**Comment by paranoidninja** [comment]
Not exactly...And this dsnt happen when I start the kali terminal, this thing only occurs whenever I execute any custom command from the nethunter app. And I have tried every other fix except compiling them.

**Comment by vay3t** [comment]
try factory reset and install nethunter without cm

**Comment by paranoidninja** [comment]
Ok. But I still dont get one thing...
I install NH App 3.0.5, it works.
I install NH App 3.1 on above of 3.0.5, it doesnt work.
I install 3.0.5 on 3.1, it starts to work again. I dont think this is some rom issue. I may be wrong...Will try installing th whole thing with 3.1 and update it here...

**Comment by paranoidninja** [comment]
The issue still exists..Not yet fixed

**Comment by binkybear** [comment]
Could you double check that the resize was removed from your: bootkali_env in /data/app/com.off*/scripts/ folder.
