### ISSUE TITLE
oneplus one cyan 13 bootloop // battery issue with new kernel

### ISSUE THREAD

**Issue by merinoffff** [offensive-security/kali-nethunter#539]
### Device:

Oneplus One 64g

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Cyanogen 13 (https://cyngn.com/support)

### Built from repo (date and build command) or downloaded from website (links):

https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

N/A

## Issue:

Went to bootloop after installing fresh Cyan 13 from the link above (me not the best searcher, couldn't find the 12.1 version). I'm using Linux installer from VBox (the last steps were done manually as USB filters didn't catch the TWRP), otherwise everything went without errors, and there was the resulting bootloop.

Let me know if any information is needed, I can redo the drill 'al capo' if needed. I'm kind of new to android thingy, don't know where to gather logs in this situation and stuff.

**Comment by binkybear** [comment]
Can you try reflashing kernel?  I just flashed a couple days ago on a new CM build and didn't experience a bootloop. 

You can rebuild kernel:
python build.py -d oneplus1 -m -k

Go back into recovery (vol down+power) and flash the zip file.  Otherwise, you may need to try to reinstall again.

**Comment by merinoffff** [comment]
Rebuilt the kernel, now it boots, thanks. But now the battery stopped working: no metrics, no charging. Battery status is unknown, level is 0%. maybe some firmware is broken?

**Comment by merinoffff** [comment]
Ok, I accidentally wiped data when wiping caches :) so I decided to flash fresh marshmellow cyan, and the battery is working fine. I'm gonna try tomorrow once again, as I would like to have a phone today :smile: Meanwhile if you could tell me some knobs (or links about knobs) on the topic I can play with like logfiles and stuff, cause I'm really not yet into android.

So the flow was: flashing fresh cyan 13, flashing nethunter with twrpFlash script, flashing the new kernel @binkybear suggested.

**Comment by binkybear** [comment]
So NH is working fine for you now?

**Comment by binkybear** [comment]
I've flashed CyanogenOS 13 recently and everything appears to be fine.  No issues on my side.  Let me know if you are still having issues.
