### ISSUE TITLE
No WLAN1 with TL-WN722 and DISABLED Y-Cable

### ISSUE THREAD

**Issue by cyba3r** [offensive-security/kali-nethunter#540]
### Device:

OnePlus 1
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow
### Built from repo (date and build command) or downloaded from website (links):

Build 16.08.2016 

 git pull
./build.py -m -d oneplus1 -fs full
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.112-cyanogenmod-g8fbc62e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016
## Issue:

I'm using Kernel 3.1.0-20160816-0223, most of the issues are gone, no 100% bug and DuckHunter works very well. But there is a strange behaviour. My Tl-WN722 works only if I enable Y-Cable AND plug the USB Cable in my laptop. If I disconnect it, the wlan1 interface disappear instantly.

**Comment by cyba3r** [comment]
If I disable any bootservices at nh, I also need to connect a usb cable...

**Comment by bkr32** [comment]
y cable has a bug which resulted in incorrect battery stats 
https://github.com/offensive-security/kali-nethunter/issues/485

**Comment by cyba3r** [comment]
Thank for your replay. I'm using a MICRO USB hub (http://www.ebay.de/itm/like/131526067980?lpid=106&chn=ps&ul_noapp=true) and It works very well with the last kernels.

**Comment by bkr32** [comment]
i use the OTG adapter that comes with the s7 and have no issue which kernel are you currently running?
plug in the cable and 722n and launch wifite it should detect it

**Comment by cyba3r** [comment]
Nope: iwconfig wlan1 says that there is no device

**Comment by cyba3r** [comment]
The S7 has a different kernel ;-)

**Comment by bkr32** [comment]
i'm using a oneplus one with kernel built on 16th august and connecting 722n via a s7 OTG adapter

**Comment by cyba3r** [comment]
Sorry, miss understood s7 :-). The version works well with WiFi, but has problems with BadUsb and Ducky.
