### ISSUE TITLE
Inconsistent work of usb-otg

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#541]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 
Linux version 3.4.0-nethunter-flo-2.0 (jc@gallifrey) (gcc version 4.9.4 20151028 (prerelease) (Linaro GCC 4.9-2016.02) ) #1 SMP PREEMPT Mon Jun 27 18:28:36 EDT 2016

## Issue:
Most of the time, kernel fails to load usb device descriptor when plugin in wifi/ethernet adapter via usb-otg. As the result, adapter does not work. Sometimes it work but sudenly stops. 

If I run 'watch lsusb' for some time, I can see adapters appearing/disappearing from usb device list.

## dmesg:
device number 2 using msm_hsusb_host
[24406.553588] usb 2-1: device descriptor read/64, error -71
[24406.913330] usb 2-1: device descriptor read/64, error -71
[24407.143646] usb 2-1: new full-speed USB device number 3 using msm_hsusb_host
[24407.393280] usb 2-1: device descriptor read/64, error -71
[24407.713317] usb 2-1: device descriptor read/64, error -71
[24407.943298] usb 2-1: new full-speed USB device number 4 using msm_hsusb_host
[24408.424407] usb 2-1: device not accepting address 4, error -71
[24408.544769] usb 2-1: new full-speed USB device number 5 using msm_hsusb_host
[24409.034698] usb 2-1: device not accepting address 5, error -71

## Research done:
EPROTO 71 /* Protocol error */

"This error can be caused by clocking the on-chip USB device at the wrong frequency. Check your clock tree configuration. The frequency should be 48MHz. If it's slightly off, it's possible that enumeration would sometimes be successful and sometimes fail. If it's way off, enumeration will always fail. Various errors are possible including the ones you listed."

## Workarounds tried:
echo -1 >/sys/module/usbcore/parameters/autosuspend

echo Y > /sys/module/usbcore/parameters/old_scheme_first

No good.

**Comment by MelrondMcBong** [comment]
Hey i have the same device (Nexus 7 2013 Mobile) and i tried to flash the nightly release from idlekernel over a stock android 6.0.1 (MOB30X) and over CM13 with the same results. I dont know if it is the same issue because i am still new to searching and reporting bugs, but i wasnt able to get my TL-WN722N to work, iwconfig lists wlan1 but it is no wireless extension. On android stock 5.1.1 its working fine

**Comment by pyc0de** [comment]
Not sure about your case, post dmesg log when you connect tplink.

Been having this issue approx. for some weeks. Prior usb-otg worked fine.

Got my usb port examined - it is in good shape. All adapters work fine on another devices. Cables are fine. So I think its kernel misconfiguration.

**Comment by jcadduono** [comment]
i'll take a look

**Comment by jcadduono** [comment]
ok can you try https://idlekernel.com/nethunter/flocm/kernel-nethunter-flocm-marshmallow-k3.0-test1.zip

**Comment by pyc0de** [comment]
Now I cant see neither usb hub nor adapters.

[  516.012268] bq27541_get_psp status: Not charging ret= 0x0101
[  516.013946] bq27541_get_psp status: Not charging ret= 0x0101
[  516.015075] bq27541_get_psp voltage_now= 4082000 uV
[  516.016357] bq27541_get_capacity = 92% ret= 91
[  516.017456] bq27541_get_psp temperature= 291 (0.1\xffffffa2XC)
[  516.019470] bq27541_get_psp current = -326 mA
[  516.023864] bq27541_get_capacity = 92% ret= 91
[  516.026000] bq27541_get_psp voltage_now= 4082000 uV
[  516.027191] bq27541_get_psp temperature= 291 (0.1\xffffffa2XC)
[  516.028198] bq27541_get_psp status: Not charging ret= 0x0101
[  516.240112] aux operation failed 02
[  516.240295] aux read failed
[  516.262268]  AUX access error
[  516.540679] aux operation failed 02
[  516.541168] aux read failed
[  516.560729]  AUX access error
[  516.819763] slimport_cable_plug_proc:AUX ERR
[  516.821075] 3.3V output disabled
[  516.822357] sp_tx_power_down
[  516.823059] sp_tx_power_down
[  516.879730] sp_tx_hardware_powerdow

I didnt test it with latest CM13 nightly.

**Comment by jcadduono** [comment]
seems to be an issue with CM13 kernel source...maybe i can try replacing usb driver changes with google's latest

**Comment by pyc0de** [comment]
Thanks. Will it be possible to fall back to latest working kernel if you cant fix it?

**Comment by jcadduono** [comment]
If there is one let me know...sorry I'm having a really busy week with Note 7 release and S7 changes

**Comment by pyc0de** [comment]
update:
ethernet-2-usb and tplink 722n work flawlessly if use y-cable and powerbank. (Strangely, I do not enable y-cable patch in nethunter app!) The moment I unplug powerbank, adapter disappears from usb devices list.

Hope this helps.

**Comment by pyc0de** [comment]
update:
Apple usb-2-ethernet adapter doesnt work with y-cable (it worked previously with just otg cable), only tplink-722n works MOST of the time.
Hope this issue will be fixed, thanks.

**Comment by pyc0de** [comment]
After recent kernel update issue is fixed. Thanks!
