### ISSUE TITLE
Stopped In Chroot Installed 

### ISSUE THREAD

**Issue by sirmatrixpage** [offensive-security/kali-nethunter#543]
### Device:

Nexus 5 [ Hammerhead ] 

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow [ CM 13 ] 

### Built from repo (date and build command) or downloaded from website (links):

https://images.offensive-security.com/nethunter-release/nethunter-hammerhead-marshmallow-3.0.zip

## Issue:

Stopped In Chroot Installed

**Comment by jcadduono** [comment]
please either build from github or you can download a kernel and generic-armhf zip from idlekernel.com/nethunter/nightly
this is fixed since 3.0.5 or so

you can find instructions to build an installer yourself here: https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
