### ISSUE TITLE
When building Nethunter image ، Nexus 5 

### ISSUE THREAD

**Issue by sirmatrixpage** [offensive-security/kali-nethunter#544]
### Device:

Nexus 5 Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

## Issue:

How Can I Build Image By kali-nethunter Tool ?

**Comment by vay3t** [comment]
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/README.md

**Comment by binkybear** [comment]
Instructions are in README.md as @vay3t has pointed out.
