### ISSUE TITLE
Nexus 4 Nethunter 3.1.0 no OTG in Android (but OTG works in TWRP?!)

### ISSUE THREAD

**Issue by MinaTheLoli** [offensive-security/kali-nethunter#545]
### Device:

Nexus 4
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

CM Lollipop
## Issue:

I use a TP WN821N with an OTG Y Cable in Nethunter 3.1.0 under CM Lollipop. The thing is, my OTG doesnt seems to work, the Wifi Card also dont get any green power signal (like its deactivated). Same doesnt work on normal usb devices BUT they o work and i can mount them only in TWRP?! what could it be?

**Comment by jcadduono** [comment]
If you don't mind updating to cm13 I have been supporting it and it's up to date with no known issues

**Comment by MinaTheLoli** [comment]
i will try it out, btw nethunter 3.0 works. It detects my wifi card and im able to use it

**Comment by jcadduono** [comment]
I assume the problem you have right now is just that you haven't installed nethunter kernel though. This is why we have these questions in issue report that you left blank...

**Comment by MinaTheLoli** [comment]
i also used the 3.1.0 kernel

**Comment by jcadduono** [comment]
Don't know that till you give output of proper commands

**Comment by MinaTheLoli** [comment]
i will use cm13 and try it there, if not i will give u the needed infos cause im already on 3.0, thats why i know it works there

**Comment by MinaTheLoli** [comment]
i tryd to use your nethunter but it seems there is no kernel

Error: Unable to find kernel image at: devices/marshmallow/mako

**Comment by MinaTheLoli** [comment]
nvm forgot it was makocm lol

**Comment by MinaTheLoli** [comment]
the wlan card dont start/work on yours, same prob as bfore
