### ISSUE TITLE
Sending malicious exe from nethunter

### ISSUE THREAD

**Issue by gooldennn** [offensive-security/kali-nethunter#547]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
marshmallow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.10.94+ (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #4 SMP PREEMPT Fri Jan 8 19:14:10 UTC 2016
root@kali:~#

## Issue:
Is there a way to send the malicious exe / pdf (whatever files) you make straight from the nethunter? 
I can find the directory where the .exe files is in the terminal, but is it possible to move this file to the sd of the phone and send it as for example mail?

Example: setoolkit
                  adobe pdf embedded exe social engineering
                  How can i send this pdf file straight from my phone?

**Comment by bkr32** [comment]
you can always upload it or use apache2 or simple http
