### ISSUE TITLE
wardriving log

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#548]
### Device:

oneplus one
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow
## Issue:

where can i find the log for my warddriving session?

**Comment by binkybear** [comment]
Script is here: https://github.com/offensive-security/nethunter-utils/blob/master/usr/bin/start-kismet

Should be saved to /sdcard/captures:
https://github.com/offensive-security/nethunter-utils/blob/master/usr/bin/start-kismet#L88

**Comment by bkr32** [comment]
hmmm i  cant see any such folder in sdcard, is there a correct way to terminate warddriving?

**Comment by binkybear** [comment]
@bkr32 - Ctrl-c will launch the save/move portion.  Otherwise, I would check /captures/kismet folder or do a search for netxml inside chroot.

**Comment by bkr32** [comment]
keep getting `warning no gps data found for BSSID` yes location is enabled for nethunter app, and it stays on until you force stop it

**Comment by binkybear** [comment]
@bkr32 - I'm seeing the issue now in testing.  Looks like something is happening where gpsd isn't passing location along.  Will update.

**Comment by bkr32** [comment]
Thanks for the update @binkybear have you encountered any reboots when using wlan1?

**Comment by binkybear** [comment]
Are you using a recent kernel?  I haven't noticed any recently....but it's possible you are using a version I forgot to patch wlan1 fix.

**Comment by bkr32** [comment]
August 16th build its a rare issue that occurs very randomly sometimes with wifite other times with wash

**Comment by binkybear** [comment]
This is getting slightly off topic but if you could next time it freezes/reboots can you get me a: cat /proc/last_kmsg > /sdcard/oops.txt

**Comment by binkybear** [comment]
Alright, fix is up:

https://github.com/binkybear/nethunter-utils/blob/e6f226370bf6d396bc204f45976dfae84ac46f87/usr/bin/start-kismet

Replace start-kismet in /usr/bin with the one above.

Please test if you have a chance.  If it works I will push it to nethunter-utils.

**Comment by bkr32** [comment]
/usr/bin/start-kismet: line 49: syntax error near unexpected token `then'
/usr/bin/start-kismet: line 49: `if [ -z "$adaptor" ]; then'root@kali:/#

**Comment by binkybear** [comment]
I went and pulled the one working on my phone and updated it:

https://raw.githubusercontent.com/binkybear/nethunter-utils/master/usr/bin/start-kismet

Try again please when you have time.

**Comment by bkr32** [comment]
alright, i get `Dbus is running: 2199 /tmp/gps found!` and it pretty much stays stuck there

**Comment by binkybear** [comment]
@bkr32 - Did you run it from the phone or from adb/ssh?  You need to run it from the phone because of screen size issue.

**Comment by bkr32** [comment]
yes i ran it from kali terminal not ssh

**Comment by binkybear** [comment]
I just ran it right now from the same script above and it's working fine.  I'm not sure if I can reproduce your error.  It should check for wlan1 then it should start Kismet after it's found.  My only suggestion would be to make sure wlan1 is good or try restarting.

**Comment by bkr32** [comment]
started monitor mode manually and re ran the script but still stays stuck on /tmp/gps found
restarted the device as well

**Comment by bkr32** [comment]
seems it doesn't start wlan1 on its own, did a diff check just to make sure the scripts are the same, i noticed the second if then statement doesn't have a else, perhaps its finding gpsfileout ?

**Comment by binkybear** [comment]
We can remove the gpsfile_out check. The script now passes the /tmp/gps to netcat and then gpsd reads the stream.  So:
https://github.com/binkybear/nethunter-utils/blob/master/usr/bin/start-kismet#L32

Should really it should be checking for /tmp/gps instead (the loop can be moved up into the else above).

**Comment by bkr32** [comment]
We can give it a shot

**Comment by bkr32** [comment]
Moved   /usr/bin/tail -f $gpsfile | netcat -l -p 2001
  echo "netcat active"
  /usr/sbin/gpsd -n tcp://127.0.0.1:2001
echo "passing to nc" 
Into the else statement of gpsfile found and oddly enough it doesn't fire netcat active

**Comment by binkybear** [comment]
Latest update is working for me.

**Comment by bkr32** [comment]
alright it's finally working but sadly still throws the no gps data error :cry:

**Comment by bkr32** [comment]
flashed latest nethunter rolling full, issue still persists, a few other problems with the new build
nethunter app doesn't show up on launcher and cant be installed
openvpn also goes missing but can be installed
drivedroid update doesn't mount devices correctly

**Comment by hhpmgr** [comment]
Any luck with this one? I'm having the exact same issue... latest nethunter chroot built from source, latest stable cyanogenmod. Most things working well, but getting same GPS message as above.

Starting GPSD and netcat
/usr/bin/tail: cannot open '/tmp/gps' for reading: No such file or directory
/usr/bin/tail: no files remaining

**Comment by bkr32** [comment]
From new commits it seems a TCP server is being added to handle it so you'll have to wait for that

**Comment by hhpmgr** [comment]
Ah OK, thanks. Is that new commits to nethunter / gpsd / kismet ? Just wondering where to watch :-)

**Comment by binkybear** [comment]
Added TCP server:
https://github.com/offensive-security/nethunter-app/commit/aa54587c2bbfe50f972c58c1e54458a2ec1c865d
https://github.com/offensive-security/nethunter-app/commit/8b00461b6584f154260ec64b0061a46910667ea4

Script needs updating to point GPSD for testing now.

**Comment by bkr32** [comment]
updated to latest 3.15.2 build still get GPS not connected was the above script commited?

**Comment by binkybear** [comment]
The above script was not committed.   You would have to manually replace with script.  I need to make sure it works before committing.

**Comment by yesimxev** [comment]
Not sure if this solves the issue, but it can be done manually, I can't test if Nethunter app does any of these though:

Start BlueNMEA (playstore app)
Then terminal: 
`gpsd -N -n -D 5 tcp://localhost:4352`
Then another terminal: 
`kismet`
Then I use giskismet to convert the file to import into Earth: 
`giskismet -q "select * from wireless" -o aps.kml`
