### ISSUE TITLE
n7100/FATAL: kernel too old problem

### ISSUE THREAD

**Issue by thunderbirdtr** [offensive-security/kali-nethunter#549]
### Device:

tg03 / n7100
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.0.101-kali-nethunter (thunderbirdtr@localhost) (gcc version 6.0.0 20160401 (experimental) (UBERTC-6.0.0) ) 
## Issue:

I compiled nethunter supported kernel for N7100 but I'm getting kernel too old error and never see bash console and can't do much on nethunter app. Is there any way we can skip that part because It's actually working.

kali ~ # killkali 
kernel.shmmax = 134217728
Shutting down SSH Server
FATAL: kernel too old
Shutting down Postgresql
FATAL: kernel too old
Removing all Kali mounts
unmounted pts
unmounted dev
unmounted proc
unmounted sys
unmounted system
unmounted sdcard
unmounted external_sd
kali ~ # bootkali_login 
setenforce:  Could not set enforcing status:  Invalid argument
mount: mounting /storage/usbdisk on /data/local/nhsystem/kali-armhf/mnt/usbdisk failed: No such file or directory
kernel.shmmax = 268435456
net.ipv4.ip_forward = 1
The Kali chroot has been started.
FATAL: kernel too old
kali ~ #

**Comment by binkybear** [comment]
We had the same issue with N7 2012.  The problem here is "kernel too old" and the issue became know after the switch to kali-rolling.  

Your two options are: downgrade to earlier version of kali or find a ported/upgraded kernel.

**Comment by thunderbirdtr** [comment]
So basicly If I want to use latest v3.0 , I need at least 3.1.xxx kernel then ? Or when we return the old verison can we upgrade and still have it. or I mean It's must be script why can't we disable it ? Is it happen because kali-fs itself or because of script ?

**Comment by binkybear** [comment]
I would go higher (3.4) if possible, testing on 3.1 failed for grouper.

According to your log, the chroot is mostly loaded: https://github.com/offensive-security/nethunter-app/blob/master/assets/scripts/bootkali_init#L116.

From there we run bash: https://github.com/offensive-security/nethunter-app/blob/master/assets/scripts/bootkali_bash#L7 and set up the environment.  Those scripts exists in /data/data/com.offsec.nethunter/files/scripts/.

You are free to modify those.  I believe the error is occurring when you first step into chroot.

I would check these first:
/root/.bashrc
/root/.profile
/root/.bash

**Comment by thunderbirdtr** [comment]
Another problem I saw;

"
bootkali_login -> #!/system/bin/sh??export PATH=/sbin:/system/sbin:/system/bin
"

Also when I installed first time I saw also one more problem in bootkali_login because symbolic wasn't okey. and I had to "rw system" and fix then back to "ro system" and new symbolic was

"
/data/data/com.offsec.nethunter/files/scripts/bootkali_login
"

I'll check these too but modify and change kernel something else porting to higher level is something else do you know any guidelines for start because I never port it except adding feature or etc.

**Comment by binkybear** [comment]
#!/system/bin/sh should be okay.  That is what Android uses for it's shell script (bootkali_login).  I may not be understanding the issue though.  Are you missing a certain path?

The "kernel is too old" is a recent issue with Kali rolling but you are right.  I will add something to Wiki explaining older kernels/devices will not work in the future.

**Comment by thunderbirdtr** [comment]
That's the only problem I saw in symbolic links It was default when I installed I'm not sure about that path part.

**Comment by kaiof** [comment]
This disables Android;s Linux Deploy for kali-rolling, since the Android kernel is 2.x ... and Sana's gone so no Kali on Android. The error only appears at the end of a really long install; I've been trying to get something working since yesterday...and back I go to wipe and install again.
