### ISSUE TITLE
Aux problem with kernel.

### ISSUE THREAD

**Issue by A767** [offensive-security/kali-nethunter#550]
### Device:
Oneplus One

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

Latest nightly kernel and full chroot zip from:
https://idlekernel.com/nethunter/nightly/3.1.0-20160827-1810/

## Issue:
Aux audio does not work after flashing kernel. (Full generic zip does not flash it for some reason.)

**Comment by binkybear** [comment]
Audio from headphone jack works fine for me on August 12 build.  What is the date of kernel you are using?

**Comment by A767** [comment]
August 12 and using Cyanogen OS 13.1.1

**Comment by binkybear** [comment]
Same build as mine.  I would first try a different cable then maybe flash a different kernel to make sure.  I'm using the same set up as you and can't reproduce.

If others experience issue let me know please.

**Comment by A767** [comment]
Did a clean flash with COS 13.1.2, still same.

I think I'm missing a critical step during the flashing process or there is a conflict with something. 

May I ask how you did it?

**Comment by A767** [comment]
Tested some speakers and it's working but my FM-transmitter still does not work, might be related to low battery level of the transmitter. If it's possible, delete this issue.
