### ISSUE TITLE
Cant't connect to wifi

### ISSUE THREAD

**Issue by rylm** [offensive-security/kali-nethunter#552]
### Device:

Samsung Galaxy S4
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow
### Built from repo (date and build command) or downloaded from website (links):

Downloadeded Oneplus One CM 12.1 image and built Kali Chroot on my machine from this github repo
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.5 (alberto96@build2.dev.xda-developers.com) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Mon May 2 11:39:10 CEST 2016
## Issue:

I can't connect to wifi, it says "Authentication problem". Issue is similar to #186, but reboot doesn't help.

**Comment by majackov** [comment]
Was same trouble when I changed wifi mac address, reset him back and all works ..
