### ISSUE TITLE
USB didn't work on OnePlus 3

### ISSUE THREAD

**Issue by keviiin38** [offensive-security/kali-nethunter#553]
### Device:

OnePlus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow (OxygenOS 3.2.4)

### Built from repo (date and build command) or downloaded from website (links):

Kernel : https://idlekernel.com/nethunter/nightly/3.1.0-20160827-1810/kernel-nethunter-oneplus3-marshmallow-3.1.0-20160827-1810.zip.sha256

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

ADB did not work without USB..

## Issue:

No USB is detected, on the computer, nothing, on the device i did not see the notification that allow to change between MTP and other. Only charging process seem to work .. And it's not dash charging..

**Comment by binkybear** [comment]
Dash was added to OnePlus3.  Maybe try latest from github (it has "adb fix'): https://transfer.sh/X6q9j/kernel-nethunter-oneplus3-marshmallow-20160831-154658.zip

**Comment by keviiin38** [comment]
Thanks very much, i'll try it and tell you if it's working, where could i find all the latests from Github ? Because i can't build it from my computer..?

**Comment by keviiin38** [comment]
So @binkybear , the issue is the next one : 
 - OxygenOS 3.24 stock, I try to flash the kernel, seem to work, but in the settings there is still written "Oneplus .... Ubuntu" under the kernel version ... So i don't know if the kernel has not been flashed or it's normal
 - Second, when i flash the kernel and next this (https://idlekernel.com/nethunter/nightly/3.1.0-20160831-1936/kernel-nethunter-oneplus3-marshmallow-3.1.0-20160831-1936.zip) there the usb is no more supported and detected.. But in the settings is something like "Elemental X ..... root@" 

Hope you or someone else could help

Thanks in advance

**Comment by ozsteyr** [comment]
For me any kernel from idlekernel gives troubles.

The kernel from binkybear is good:

https://transfer.sh/X6q9j/kernel-nethunter-oneplus3-marshmallow-20160831-154658.zip

But i must turn off usb debugging in developer options in order for my pc to recognize my OP3.

**Comment by keviiin38** [comment]
Okay thanks @ozsteyr , I finally be able to build from the github repo, so i'll try it on a fresh install of OOS.
Is the kernel on the repo, bikinybear's ?
