### ISSUE TITLE
Error when installing angler on Nexus 6P

### ISSUE THREAD

**Issue by Dr0me** [offensive-security/kali-nethunter#554]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

kernel 3.10.94+ root@kali #4 , build MTC20F
## Issue:

 I have installed all in accordance with the windows installation page from the website.  My drivers check good.  I flash to stock, root, re-root with twrp, but when I flash angler version of nethunter it does not fully install.  It shows some code running but the gui for nethunter install never comes up.  I have tried with and without wiping cache/delvik.   It reboots to the normal stock screen, but the kernel says kernel 3.10.94+ root@kali #4 , build MTC20F.  There is also a new error with SuperSU binary needing updated that I cannot clear.  I tried flashing from twrp, redid this whole process, and then tried flashing from NRT.  There was also another weird error in which my original build was mmb29M and then it was switched to MTC20F along this process.  This could have been an error in NRT that directed me to the wrong build (yes I had named my device as a mmb29m build already).  Anyway, I am relatively new to this, Im a mechanical engineer transitioning to the cyber world (scary i know).  I've never done a manual build like I have seen people have success with.  Does it matter what folder I have the file in when I flash it from TWRP?  Also, I have windows 10.  Thanks to all for the help, I appologize for the bother, but I have spent literally over 12 hours trying to get nethunter working on my phone (those updates after flashing stock take forever!!).

**Comment by Jsitech** [comment]
I Had the exact same issue with my nexus 10. Turns out the problem was the latest TWRP Custom recovery, TWRP 3.0.2-0 .. I Downloaded twrp manager from the Play Store and flashed 2.8 .. Install finished succesfully.
