### ISSUE TITLE
Trouble with external Wifi adapter, Nexus 7 2013 Wifi

### ISSUE THREAD

**Issue by lordvejder** [offensive-security/kali-nethunter#555]
## Issue:

Everything is installed cause airmon-ng was showing wlan1, even somehow external WiFi was primary on connecting to networks. After reboot, airmon-ng dont show wlan1 anymore, OTG cable is ok, TpLink external is ok cause it works on laptop.

Also wifite is not working it canot get wlan in monitor mode, even if i get it manually it shows same: just ok and again to choose frem same numbers.

**Comment by lordvejder** [comment]
Looks like it has to be something with USB conections, my computer doesnt recognise it is connected when in Nethunter. Stock rom works fine.

**Comment by pyc0de** [comment]
Could you provide dmesg log?

**Comment by VaanaParama** [comment]
after several days working out with wifite on my nexus 5 i found a solution for me:
Try to set the interface directly in wifite like:
wifite -i wlan1
For me this worked fine.
greez

**Comment by lordvejder** [comment]
Sry for waiting.

So lsusb see that usb is connectec, and airmon see nothing. U have all in screenshot, tell me what to send if i did this wrong.

Thnx

![screenshot_20160910-194807](https://cloud.githubusercontent.com/assets/21681646/18412485/e84bff96-778f-11e6-863a-1359422cef7d.png)

**Comment by binkybear** [comment]
Try:
```bash
ifconfig wlan1 up
dmesg | grep ath
```
Also, try checking ycable option if that still doesn't work.  Double check correct kernel is installed.

**Comment by lordvejder** [comment]
When i wanted to try that, not even lsusb recognise it. I updated kernel to 10 sept ver for marshmallow. Still the same.
![screenshot_20160911-132623](https://cloud.githubusercontent.com/assets/21681646/18416958/c18fb282-7823-11e6-8e2f-276069849bc6.png)

**Comment by pyc0de** [comment]
Looks similar to my issue #541. Have you tried any other adaptrers like usb2ethernet and such?

**Comment by lordvejder** [comment]
Looks like im gonna need new USB OTG cable, maybe its broken. I tryed gamepad on both Nexus 7 and Nexus 5 and it sometimes work and sometimes dont. Ill update when itry with new cable.

**Comment by pyc0de** [comment]
I've tried several previously flawlessly working cables and result is exactly the same: sometimes it works. And this issue appeared after kernel update.
