### ISSUE TITLE
Auto-ENTER after each STRING and missing the "G"/"g" in DuckHunterHID for German Keyboard

### ISSUE THREAD

**Issue by BesoBerlin** [offensive-security/kali-nethunter#556]
### Device:
Nexus 5 

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.0.1

### Built from repo (date and build command) or downloaded from website (links):
Download from website

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gb7558f2 (root@kali) (gcc version 4.7 (GCC) )) #2 SMP PREEMPT Wed Oct 7 02:16:12 UTC 2015

## Issue:
When using DuckHunterHID with German KeyBoard Setting, it performs an ENTER after each STRING automatically. 
As well it doesn't type a "g" or "G". 
This issue only(!) appears when I use the German language in Nethunter. When I use American English it works well on the same device.
Somehow I do not have this issue on Linux Devices yet, but on OS X Windows.

**Comment by MattBarbier** [comment]
This happens with the Italian keyboard too (at least for me). Also the characters "{" and "}" are misconfigured (the print as "è" and "+", which are the base character on the key. The brackets are obtained with the ALT GR + key combo)

**Comment by D13man** [comment]
The auto-Enter occurs because the "STRING" command always hits enter when it finishes typing, you need to use "TEXT" as noted here: https://github.com/byt3bl33d3r/duckhunter.

And, the "G" or "g" can be fixed by modifying  "keyseed.py" in "nh_files/modules" by adding in "'de_bin' : {...}:" the following: `"\x47": "left-shift g", "\x67": "g",`

Hope that this fixes the issues that you are having. :)

credits to VectreUK for the fix of G and g.

**Comment by MattBarbier** [comment]
@D13man it worked for me, but I can't use the same method for { and }. Is it correct to write
`"\x7b": "right-alt left-shift lbracket"` (and rbracket for the other one)?

**Comment by BesoBerlin** [comment]
Thank You very much! Thats it! So I will play around a little bit with this file and see if I can add a german mac layout as well...

**Comment by BesoBerlin** [comment]
#742

**Comment by SupaSTO** [comment]
@D13man Hello, I properly modified the keyseed.py file but the g/G character still doesn't pop up. I use a Belgian keyboard. Do you have any hint on what else I could try to fix the issue ? Thanks

**Comment by BesoBerlin** [comment]
hmm... thats strange! what about other input languages? have you tried the german and/or the english ones? do they worl properly? maybe upload the keyseed.py file here to let us have a look into it ...

**Comment by SupaSTO** [comment]
The US layout works perfectly, but here's the fuke in a google drive : https://drive.google.com/open?id=0B6ZEFjDOhYWuR1lGMGd6eXY0dFE

I just modified the required field in the "be_bin" section, so I don't really see where the problem is

**Comment by BesoBerlin** [comment]
Hey SupaSTO... have you tried to add this line in be_bin as well? maybe try to replace the whole be_bin and be part with this:

> 'be_bin' : {
>         # Symbols
>         "\x20": "space",
>         "\x21": "8",                    # !
>         "\x22": "3",                    # "
>         "\x23": "right-alt 3",          # hashtag nethunter
>         "\x24": "rbracket",             # $
>         "\x25": "left-shift quote",     # %
>         "\x26": "1",                    # &
>         "\x27": "4",                    # '
>         "\x28": "5",                    # (
>         "\x29": "minus",                # )
>         "\x2a": "left-shift rbracket",  # *
>         "\x2b": "left-shift slash",     # +
>         "\x2c": "m",                    # ,
>         "\x2d": "equals",               # -
>         "\x2e": "left-shift comma",     # .
>         "\x2f": "left-shift period",    # /
>         # Numbers
>         "\x30": "left-shift 0",
>         "\x31": "left-shift 1",
>         "\x32": "left-shift 2",
>         "\x33": "left-shift 3",
>         "\x34": "left-shift 4",
>         "\x35": "left-shift 5",
>         "\x36": "left-shift 6",
>         "\x37": "left-shift 7",
>         "\x38": "left-shift 8",
>         "\x39": "left-shift 9",
>         # Symbols
>         "\x3a": "period",               # :
>         "\x3b": "comma",                # ;
>         #"\x3c": "\\x00\\x00\\x00\\x64\\x00\\x00\\x00\\x00", # <
>         "\x3d": "slash",               # =
>         #"\x3e": "\\x20\\x00\\x00\\x64\\x00\\x00\\x00\\x00", # >
>         "\x3f": "left-shift m",         # ?
>         "\x40": "right-alt 2",          # @
>         # Uppercase
>         "\x41": "left-shift q",
>         "\x42": "left-shift b",
>         "\x43": "left-shift c",
>         "\x44": "left-shift d",
>         "\x45": "left-shift e",
>         "\x46": "left-shift f",
>         "\x47": "left-shift g",
>         "\x48": "left-shift h",
>         "\x49": "left-shift i",
>         "\x4a": "left-shift j",
>         "\x4b": "left-shift k",
>         "\x4c": "left-shift l",
>         "\x4d": "left-shift semicolon",
>         "\x4e": "left-shift n",
>         "\x4f": "left-shift o",
>         "\x50": "left-shift p",
>         "\x51": "left-shift a",
>         "\x52": "left-shift r",
>         "\x53": "left-shift s",
>         "\x54": "left-shift t",
>         "\x55": "left-shift u",
>         "\x56": "left-shift v",
>         "\x57": "left-shift z",
>         "\x58": "left-shift x",
>         "\x59": "left-shift y",
>         "\x5a": "left-shift w",
>         # Symbols
>         "\x5b": "right-alt 5",           # [
>         #"\x5c": "right-alt backslash",  # \
>         "\x5d": "right-alt rbracket",    # ]
>         "\x5e": ["lbracket", "space"],   # ^
>         "\x5f": "left-shift equals",     # _
>         "\x60": "right-alt backslash",   # 
>         # Lowercase
>         "\x61": "q",
>         "\x62": "b",
>         "\x63": "c",
>         "\x64": "d",
>         "\x65": "e",
>         "\x66": "f",
>         "\x67": "g",
>         "\x68": "h",
>         "\x69": "i",
>         "\x6a": "j",
>         "\x6b": "k",
>         "\x6c": "l",
>         "\x6d": "semicolon",
>         "\x6e": "n",
>         "\x6f": "o",
>         "\x70": "p",
>         "\x71": "a",
>         "\x72": "r",
>         "\x73": "s",
>         "\x74": "t",
>         "\x75": "u",
>         "\x76": "v",
>         "\x77": "z",
>         "\x78": "x",
>         "\x79": "y",
>         "\x7a": "w",
>         #Shift chars
>         "\x7b": "right-alt 9",      # {
>         "\x7c": "right-alt 1",      # |
>         "\x7d": "right-alt 0",      # }
>         "\x7e": ["right-alt slash", "space"], # ~
>         "\x7f": "backspace",
>         #SDLK_RETURN,0x28
>         #"\x0a": "\\x00\\x00\\x00\\x28\\x00\\x00\\x00\\x00",
>         #"\x0d": "\\x00\\x00\\x00\\x28\\x00\\x00\\x00\\x00"
>     },
>     'be' : {
>         "\x20": "\\x00\\x00\\x00\\x2c\\x00\\x00\\x00\\x00",
>         "\x21": "\\x00\\x00\\x00\\x25\\x00\\x00\\x00\\x00",
>         "\x22": "\\x00\\x00\\x00\\x20\\x00\\x00\\x00\\x00",
>         "\x23": "\\x40\\x00\\x00\\x20\\x00\\x00\\x00\\x00",
>         "\x24": "\\x00\\x00\\x00\\x30\\x00\\x00\\x00\\x00",
>         "\x25": "\\x02\\x00\\x00\\x34\\x00\\x00\\x00\\x00",
>         "\x26": "\\x00\\x00\\x00\\x1e\\x00\\x00\\x00\\x00",
>         "\x27": "\\x00\\x00\\x00\\x21\\x00\\x00\\x00\\x00",
>         "\x28": "\\x00\\x00\\x00\\x22\\x00\\x00\\x00\\x00",
>         "\x29": "\\x00\\x00\\x00\\x2d\\x00\\x00\\x00\\x00",
>         "\x2A": "\\x02\\x00\\x00\\x30\\x00\\x00\\x00\\x00",
>         "\x2B": "\\x02\\x00\\x00\\x38\\x00\\x00\\x00\\x00",
>         "\x2C": "\\x00\\x00\\x00\\x10\\x00\\x00\\x00\\x00",
>         "\x2D": "\\x00\\x00\\x00\\x2e\\x00\\x00\\x00\\x00",
>         "\x2E": "\\x02\\x00\\x00\\x36\\x00\\x00\\x00\\x00",
>         "\x2F": "\\x02\\x00\\x00\\x37\\x00\\x00\\x00\\x00",
>         "\x30": "\\x02\\x00\\x00\\x27\\x00\\x00\\x00\\x00",
>         "\x31": "\\x02\\x00\\x00\\x1e\\x00\\x00\\x00\\x00",
>         "\x32": "\\x02\\x00\\x00\\x1f\\x00\\x00\\x00\\x00",
>         "\x33": "\\x02\\x00\\x00\\x20\\x00\\x00\\x00\\x00",
>         "\x34": "\\x02\\x00\\x00\\x21\\x00\\x00\\x00\\x00",
>         "\x35": "\\x02\\x00\\x00\\x22\\x00\\x00\\x00\\x00",
>         "\x36": "\\x00\\x00\\x00\\x23\\x00\\x00\\x00\\x00",
>         "\x37": "\\x02\\x00\\x00\\x24\\x00\\x00\\x00\\x00",
>         "\x38": "\\x02\\x00\\x00\\x25\\x00\\x00\\x00\\x00",
>         "\x39": "\\x02\\x00\\x00\\x26\\x00\\x00\\x00\\x00",
>         "\x3A": "\\x00\\x00\\x00\\x37\\x00\\x00\\x00\\x00",
>         "\x3B": "\\x00\\x00\\x00\\x36\\x00\\x00\\x00\\x00",
>         "\x3C": "\\x00\\x00\\x00\\x64\\x00\\x00\\x00\\x00",
>         "\x3D": "\\x00\\x00\\x00\\x38\\x00\\x00\\x00\\x00",
>         "\x3E": "\\x02\\x00\\x00\\x64\\x00\\x00\\x00\\x00",
>         "\x3F": "\\x02\\x00\\x00\\x10\\x00\\x00\\x00\\x00",
>         "\x40": "\\x40\\x00\\x00\\x1f\\x00\\x00\\x00\\x00",
>         "\x41": "\\x02\\x00\\x00\\x14\\x00\\x00\\x00\\x00",
>         "\x42": "\\x02\\x00\\x00\\x5\\x00\\x00\\x00\\x00",
>         "\x43": "\\x02\\x00\\x00\\x6\\x00\\x00\\x00\\x00",
>         "\x44": "\\x02\\x00\\x00\\x7\\x00\\x00\\x00\\x00",
>         "\x45": "\\x02\\x00\\x00\\x8\\x00\\x00\\x00\\x00",
>         "\x46": "\\x02\\x00\\x00\\x9\\x00\\x00\\x00\\x00",
>         "\x47": "\\x02\\x00\\x00\\xa\\x00\\x00\\x00\\x00",
>         "\x48": "\\x02\\x00\\x00\\xb\\x00\\x00\\x00\\x00",
>         "\x49": "\\x02\\x00\\x00\\xc\\x00\\x00\\x00\\x00",
>         "\x4A": "\\x02\\x00\\x00\\xd\\x00\\x00\\x00\\x00",
>         "\x4B": "\\x02\\x00\\x00\\xe\\x00\\x00\\x00\\x00",
>         "\x4C": "\\x02\\x00\\x00\\xf\\x00\\x00\\x00\\x00",
>         "\x4D": "\\x02\\x00\\x00\\x33\\x00\\x00\\x00\\x00",
>         "\x4E": "\\x02\\x00\\x00\\x11\\x00\\x00\\x00\\x00",
>         "\x4F": "\\x02\\x00\\x00\\x12\\x00\\x00\\x00\\x00",
>         "\x50": "\\x02\\x00\\x00\\x13\\x00\\x00\\x00\\x00",
>         "\x51": "\\x02\\x00\\x00\\x4\\x00\\x00\\x00\\x00",
>         "\x52": "\\x02\\x00\\x00\\x15\\x00\\x00\\x00\\x00",
>         "\x53": "\\x02\\x00\\x00\\x16\\x00\\x00\\x00\\x00",
>         "\x54": "\\x02\\x00\\x00\\x17\\x00\\x00\\x00\\x00",
>         "\x55": "\\x02\\x00\\x00\\x18\\x00\\x00\\x00\\x00",
>         "\x56": "\\x02\\x00\\x00\\x19\\x00\\x00\\x00\\x00",
>         "\x57": "\\x02\\x00\\x00\\x1d\\x00\\x00\\x00\\x00",
>         "\x58": "\\x02\\x00\\x00\\x1b\\x00\\x00\\x00\\x00",
>         "\x59": "\\x02\\x00\\x00\\x1c\\x00\\x00\\x00\\x00",
>         "\x5A": "\\x02\\x00\\x00\\x1a\\x00\\x00\\x00\\x00",
>         "\x5B": "\\x40\\x00\\x00\\x30\\x00\\x00\\x00\\x00",
>         "\x5C": "\\x40\\x00\\x00\\x64\\x00\\x00\\x00\\x00",
>         "\x5D": "\\x40\\x00\\x00\\x2f\\x00\\x00\\x00\\x00",
>         "\x5E": "\\x40\\x00\\x00\\x23\\x00\\x00\\x00\\x00",
>         "\x5F": "\\x02\\x00\\x00\\x2e\\x00\\x00\\x00\\x00",
>         "\x60": "\\x40\\x00\\x00\\x31\\x00\\x00\\x00\\x00",
>         "\x61": "\\x00\\x00\\x00\\x14\\x00\\x00\\x00\\x00",
>         "\x62": "\\x00\\x00\\x00\\x5\\x00\\x00\\x00\\x00",
>         "\x63": "\\x00\\x00\\x00\\x6\\x00\\x00\\x00\\x00",
>         "\x64": "\\x00\\x00\\x00\\x7\\x00\\x00\\x00\\x00",
>         "\x65": "\\x00\\x00\\x00\\x8\\x00\\x00\\x00\\x00",
>         "\x66": "\\x00\\x00\\x00\\x9\\x00\\x00\\x00\\x00",
>         "\x67": "\\x00\\x00\\x00\\xa\\x00\\x00\\x00\\x00",
>         "\x68": "\\x00\\x00\\x00\\xb\\x00\\x00\\x00\\x00",
>         "\x69": "\\x00\\x00\\x00\\xc\\x00\\x00\\x00\\x00",
>         "\x6A": "\\x00\\x00\\x00\\xd\\x00\\x00\\x00\\x00",
>         "\x6B": "\\x00\\x00\\x00\\xe\\x00\\x00\\x00\\x00",
>         "\x6C": "\\x00\\x00\\x00\\xf\\x00\\x00\\x00\\x00",
>         "\x6D": "\\x00\\x00\\x00\\x33\\x00\\x00\\x00\\x00",
>         "\x6E": "\\x00\\x00\\x00\\x11\\x00\\x00\\x00\\x00",
>         "\x6F": "\\x00\\x00\\x00\\x12\\x00\\x00\\x00\\x00",
>         "\x70": "\\x00\\x00\\x00\\x13\\x00\\x00\\x00\\x00",
>         "\x71": "\\x00\\x00\\x00\\x4\\x00\\x00\\x00\\x00",
>         "\x72": "\\x00\\x00\\x00\\x15\\x00\\x00\\x00\\x00",
>         "\x73": "\\x00\\x00\\x00\\x16\\x00\\x00\\x00\\x00",
>         "\x74": "\\x00\\x00\\x00\\x17\\x00\\x00\\x00\\x00",
>         "\x75": "\\x00\\x00\\x00\\x18\\x00\\x00\\x00\\x00",
>         "\x76": "\\x00\\x00\\x00\\x19\\x00\\x00\\x00\\x00",
>         "\x77": "\\x00\\x00\\x00\\x1d\\x00\\x00\\x00\\x00",
>         "\x78": "\\x00\\x00\\x00\\x1b\\x00\\x00\\x00\\x00",
>         "\x79": "\\x00\\x00\\x00\\x1c\\x00\\x00\\x00\\x00",
>         "\x7A": "\\x00\\x00\\x00\\x1a\\x00\\x00\\x00\\x00",
>         "\x7B": "\\x40\\x00\\x00\\x26\\x00\\x00\\x00\\x00",
>         "\x7C": "\\x40\\x00\\x00\\x1e\\x00\\x00\\x00\\x00",
>         "\x7D": "\\x40\\x00\\x00\\x27\\x00\\x00\\x00\\x00",
>         "\x7E": "\\x40\\x00\\x00\\x38\\x00\\x00\\x00\\x00",
>         "\x7F": "\\x00\\x00\\x00\\x2a\\x00\\x00\\x00\\x00",
>         "\xA0": "\\x00\\x00\\x00\\x2c\\x00\\x00\\x00\\x00",
>         "\xA3": "\\x02\\x00\\x00\\x31\\x00\\x00\\x00\\x00",
>         "\xA7": "\\x00\\x00\\x00\\x23\\x00\\x00\\x00\\x00",
>         "\xAC": "\\x40\\x00\\x00\\x8\\x00\\x00\\x00\\x00",
>         "\xB0": "\\x02\\x00\\x00\\x2d\\x00\\x00\\x00\\x00",
>         "\xB2": "\\x00\\x00\\x00\\x35\\x00\\x00\\x00\\x00",
>         "\xB3": "\\x02\\x00\\x00\\x35\\x00\\x00\\x00\\x00",
>         "\xB5": "\\x00\\x00\\x00\\x31\\x00\\x00\\x00\\x00",
>         "\xE0": "\\x00\\x00\\x00\\x27\\x00\\x00\\x00\\x00",
>         "\xE7": "\\x00\\x00\\x00\\x26\\x00\\x00\\x00\\x00",
>         "\xE8": "\\x00\\x00\\x00\\x24\\x00\\x00\\x00\\x00",
>         "\xE9": "\\x00\\x00\\x00\\x1f\\x00\\x00\\x00\\x00",
>         "\xF9": "\\x00\\x00\\x00\\x34\\x00\\x00\\x00\\x00",
>         "\x0a": "\\x00\\x00\\x00\\x28\\x00\\x00\\x00\\x00",
>         "\x0d": "\\x00\\x00\\x00\\x28\\x00\\x00\\x00\\x00",
>     },

**Comment by SupaSTO** [comment]
I was thinking about doing this, I will try it and give feedback tomorrow as I won't have access to my device today. Thanks a lot !

**Comment by BesoBerlin** [comment]
any news?
