### ISSUE TITLE
Root replace Kernel and Kernel replace Root

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#557]
### Device:

OnePlus 3
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

OxygenOS 3.2.4
### Built from repo (date and build command) or downloaded from website (links):

Build from repo with : "python build.py -d oneplus3 --marshmallow --nosu --rootfs full" [2016-09-03] & "python build.py -d oneplus3 --marshmallow --rootfs full" [2016-09-02]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Can't be executed because ADB didn't work on OP3... And the NetHunter Terminal crash when granting rights ...
## Issue:

I've tried both .zip, one with and the other without the SuperSU installer.
Similar issue that #551 ... 
- **With the SuperSU installer :** 
  When i launch for the first time it asks for an binary update that's fail every time.. still after reboot.. 
  I've flash differents version of SuperSU, then it was working, **BUT** it erased the kernel, so i've stock kernel again, **AND** when opening the terminal, it ask for "grant" when i click on it the terminal close and can't use it.. crash after each launch.. (like in  ##551)
- **Without the SuperSU installer :** ( [...] --nosu [...] )
  I flash OOS first, then the SuperSU .zip and when everything is configured i flash my NetHunter .zip
  There the problem is in the other side, the root works with stock OOS, but the kernel that's installing during NetHunter install modify the root because i've the same issue with this binary update..

So, it seems like the Kernel flash is modifying the root and reverse the SuperSU flash replace the kernel with the stock kernel...

**Comment by binkybear** [comment]
If you build from the repo there is a no supersu option.  I am without a OnePlus 3 so I cannot test this at the moment.

**Comment by akrolla** [comment]
Sounds to me like its replacing the kernel back to stock turning se linux
back on . Did u just use adb and try to sideload everything? Did u try any
other method for a properinstall? flash to stock, root, install twrp
busybox update su binary then. Boot to recovery  Once done copy
nethunter.zip from computer to downloads folder on ur sd card. U don't have
to but it helps. And install nethunter.zip using twrps install rom option.

**Comment by akrolla** [comment]
Is this still open? need any new help?
