### ISSUE TITLE
Dump Mifare

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#559]
### Device:
Oneplus One

### Built from repo (date and build command) or downloaded from website (links):
idlekernel 31 august

## Issue:
Does Dump Mifare require a external NFC reader?
it shows No NFC device found regardless of NFC state

**Comment by binkybear** [comment]
It does require an external reader.

**Comment by bkr32** [comment]
Could you please link the component

**Comment by binkybear** [comment]
I believe a Proxmark 3 is the most common one I hear about: https://store.ryscc.com/

**Comment by bkr32** [comment]
Thanks for that
