### ISSUE TITLE
mana wireless toolkit

### ISSUE THREAD

**Issue by gooldennn** [offensive-security/kali-nethunter#561]
### Device:

huawei nexus 6p
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

marshmallow
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

linux version 3.10.94+ (root@kali) (gcc version 4.9.xgoogle 20140827 (prerelease) (GCC) ) #4 SMP Fri jan 8 19:14:10 UTC 2016
## Issue:

https://goo.gl/photos/WttXgA94HVvbaZ57A

Cant mana to work, any ideas/solutions?

**Comment by ozsteyr** [comment]
This issue has been brought up and closed.

https://github.com/offensive-security/kali-nethunter/issues/532
