### ISSUE TITLE
Direct Chroot

### ISSUE THREAD

**Issue by seanwlk** [offensive-security/kali-nethunter#562]

**Comment by bkr32** [comment]
nethunter runs on more than one layer and its not possible to have it run from a iso directly

**Comment by seanwlk** [comment]
I understand, but I have issues to run it with MultiROM, and I don't want to run this ROM as my daily driver. I prefer using the current COS 13.1 available for the One, and the latest Kali ROM release is still running Lollipop

**Comment by bkr32** [comment]
Kali rom? nethunter installs as a add on i haven't used multi rom in some time but make sure primary rom has hexec driver, alternatively swap secondary and primary roms flash nethunter and then swap them back

**Comment by seanwlk** [comment]
Yeah this did the job actually, hexec is supported. I just swapped the primary with the secondary. Thanks.
