### ISSUE TITLE
alfa awus036h 

### ISSUE THREAD

**Issue by puba** [offensive-security/kali-nethunter#563]
### Device:

ONEPLUSONE
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow
### Built from repo (date and build command) or downloaded from website (links):

dfsfd
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.14.112-cyanogemod-g8fbc623(root@nhbuild-box)
## Issue:

alfa awus036h is not working with this build, tried with OTG, Y cables, external power source, no go. 
Is it even supported on nethunter?

**Comment by akrolla** [comment]
Cable y charging should be u haveyo activateit in kali services in
nethunter app

**Comment by puba** [comment]
@akrolla been there, done that...adapter cold and still, without any sign of life

**Comment by akrolla** [comment]
Hmmm bummer I had one on order I was going to try. Wonder if theres the
same problem with the pineapple connector.

On Sep 8, 2016 12:27 PM, "puba" <notifications@github.com> wrote:

> <https://github.com/akrolla>

> @akrolla <https://github.com/akrolla> been there, done that...adapter
cold and still, without any sign of life
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/563#issuecomment-245673885>,
or mute the thread

**Comment by benichmt1** [comment]
I had an interesting issue similar to this. My wireless card used to be able to work with just the Y cable without being connected to a power source. Now I need to be connected to USB power and the Y cable power enabled for it to actually work.

I have the Alfa AWUS036NHA and the TL-WN722N which both exhibited the same behavior.
