### ISSUE TITLE
NetHunter wallpaper & boot animation Nexus 6p (1440x2560)

### ISSUE THREAD

**Issue by h00die** [offensive-security/kali-nethunter#564]
Nexus 6p has a resolution of 1440x2560.  Can the author of the NetHunter wallpaper and boot animation create one at that size for 6p?

**Comment by jcadduono** [comment]
wallpaper done, i needed it for note 7 anyways

bootanimation...well, theres only 1080x1920 i think and no one has the original that i know of o.o

**Comment by binkybear** [comment]
Nobody has the original boot animation.  I'm going to close issue for now.
