### ISSUE TITLE
System reboot when activate hotspot

### ISSUE THREAD

**Issue by jslon** [offensive-security/kali-nethunter#565]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Android 6.0.1 (Marshmallow)
OxygenOS 3.0.2
### Built from repo (date and build command) or downloaded from website (links):

nethunter-oos3-6.0.1-20160811-full
https://www.androidfilehost.com/?fid=24591000424954117
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux Version 3.10.84kali+ (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #4 SMP PREEMPT Sat Aug 6 16:51:16 CDT 2016
## Issue:

The system reboots when start a hotspot or when trying to execute airmon-ng start wlan0 or using Wifite.

**Comment by seanwlk** [comment]
Do you actually have an external Wireless adaptor connected through OTG or you're trying to use the built-in card?

**Comment by jslon** [comment]
For the moment I'm using the built-in card. I know it doesn't support monitor mode so I shouldn't use airmon-ng but I'm not able to create a hotspot without the system crashing.

**Comment by seanwlk** [comment]
Actually you can't use the integrated one at all AFAIK. You shluld use a dongle via OTG.

**Comment by jslon** [comment]
It doesn't make sense, is an OS common option, with the normal OS I'm able to do it. The system is also crashing when I'm using the "Bad USB MITM Attack" of the Nethunter app. At the moment I start the attack and plug the USB, the system crashes. Any idea why?

**Comment by akrolla** [comment]
Incomplete installation maybe ? Did u verify sha1sums once the install
completed?

**Comment by jslon** [comment]
No I didn't. I verified the SHA1sums after downloading it but not after the installation. How should I verify them?

**Comment by akrolla** [comment]
Sorry I mispoke I meant after download.  Hm so file integriry was fine. I
believe there is a similar issue with  the kernel for the OP3 open at this
very moment from the other day that was causing almost the same problem..
@binkybear I think its issue #489 its quite similar?

**Comment by akrolla** [comment]
they were having issues with the OP3 kernel crashing yesterday due to an
update to how the usb was picked up and had to revert the kernel to before
the update @binkybear perhaps the problems lies elsewhere and perhaps
bothissues are correlated.

**Comment by akrolla** [comment]
Ahh roger that I have the nexus I'm thinking of upgrading to OP3 do you
guys recommend that over the nexus ?

**Comment by jslon** [comment]
@binkybear Sorry about my ignorance, but where can I download that update?

**Comment by binkybear** [comment]
@jslon - You can build it from this repo.  I've uploaded one for you:

https://transfer.sh/nfQj4/kernel-nethunter-oneplus2oos-marshmallow-20160912-003744.zip

**Comment by jslon** [comment]
I'll try it, thank you very much!

**Comment by jslon** [comment]
Just have to install it with TWRP or first I have to wipe the phone?

**Comment by binkybear** [comment]
If you have TWRP and latest oxygen os just flash.  If you don't have latest, you may want to start fresh.

**Comment by jslon** [comment]
ok thanks!

**Comment by akrolla** [comment]
On the link on the main page is to the main app apk which is here
https://images.offensive-security.com/latest.apk all the links are
available in the documentation section also.

**Comment by jslon** [comment]
@binkybear I'm sorry for bothering you but I'm a beginner at the Android world and don't really understand much about how this works. There is an update for the OxygenOS, so I'm trying to install it before flashing the NetHunter, but when I download it and press install the system reboots and boot on TWRP directly, I don't know if this is supposed to happen. Actually I have OxygenOS 3.0.2. How can I update the system before flashing NH? Once updated, for flashing it I just have to move the NH image to my phone and press install on TWRP, am I right?

**Comment by akrolla** [comment]
Boot into twrp and then install kernel

**Comment by akrolla** [comment]
My bad misread that, once installed it boots into multirom and u choose
which kernel to run. Which tour oxygen kernel shpuld be the internal kernel

**Comment by akrolla** [comment]
Its alright we are all noobs at one point:) once I got the phone rooted and
twrp and the kernelinstalled I saved the nethunter zip file onto my sd card
and installed it through twro. I installed kernel separately. To help
relieve stress on the aroma installer included as it tends to lock up
installing both the kernel and chroot.

**Comment by akrolla** [comment]
My typos are terrible.  Sorry **  installed it through twrp.

**Comment by jslon** [comment]
I tried  flashing the new NetHunter image @binkybear gave to me but the problem wasn't resolved, in fact, the terminal is crashing when i select "kali" and all the NetHunter options (from the NetHunter app) are disabled. I also tried building a new OnePlus2 image and flashing it but the problem persists. I'm not able to update my Oxygen version to 3.1 because after downloading it and pressing install the phone reboots into TWRP instead of installing the update. Right now I'm trapped. I was wondering if you can guide me how to wipe everything off and start fresh again. Thank you very much.

**Comment by binkybear** [comment]
- Go into TWRP.  
- Wipe > System/data.  
- Install Oxygen OS factory zip file (latest) from sdcard.  
- Reboot (make sure it works).  
- Reboot into TWRP.  
- Install:  https://transfer.sh/JEe79/nethunter-oneplus2oos-marshmallow-kalifs-full-20160911-011114.zip

**Comment by jslon** [comment]
Ok, I did it. Now the NetHunter app is working fine, as well the terminal. But now LTE is having issues (have the ! sign) and the rear camera is not focusing, and again, the system crashes when trying to create a hotspot. :/

**Comment by binkybear** [comment]
I see error now also.

**Comment by binkybear** [comment]
So it appears I need to include modules with kernel:

https://transfer.sh/ewYh5/kernel-nethunter-oneplus2oos-marshmallow-20160915-155247.zip

I tested on mine, please test on yours.

**Comment by jslon** [comment]
I flashed it and now is working! If I found any issue I'll let you know. Thank you very much!

**Comment by jslon** [comment]
Hello @binkybear, I just realized that after flashing the last image you gave me the front camera is not being detected.

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
