### ISSUE TITLE
Wifite doesn't allow selection selection of interface on first start just loops

### ISSUE THREAD

**Issue by kevinnz** [offensive-security/kali-nethunter#566]
### Device:

OnePlus 3
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oxygen OS 3.2.4
### Built from repo (date and build command) or downloaded from website (links):

`python build.py -d oneplus3 --marshmallow --rootfs full` and 
https://transfer.sh/Jpvrm/kernel-nethunter-oneplus3-marshmallow-20160909-014754.zip from @binkybear 
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-ElementalX-OP3-0.15 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #7 SMP PREEMPT Thu Sep 8 20:38:30 CDT 2016
## Issue:

Wifite doesn't allow selection selection of interface on first start, just keeps going around in a loop. Work around is to put wlan1 into monitor mode via NetHunter app.

**Comment by VaanaParama** [comment]
Try to Set the Interface in wifite directly:
Wifite -i wlan1

**Comment by TermiGR** [comment]
I do have exactly the same problem with my Nexus 7 2013 (Marshmallow latest) and the TL-WN722N Card.

**Comment by TermiGR** [comment]
Update: It seems like wlan0 and wlan1 are switched somehow. So i had to modify the wifite and the monitor mode scripts from wlan1 to wlan0 - strange

**Comment by jcadduono** [comment]
If you start your phone with a wifi adapter plugged in its completely normal for USB to become wlan0, you should not plug your adapter in until OS has fully booted.

**Comment by tehpenguin** [comment]
Same issue here. Bump.

**Comment by Drosos2000** [comment]
Enable monitor mode to your adapter and then set the Interface in wifite directly:
airmon-ng start MONITOR_INTERFACE
wifite --mon-iface MONITOR_INTERFACE

For example:
airmon-ng start wlan1
wifite --mon-iface wlan1mon
