### ISSUE TITLE
Metaspoit doesn't work right

### ISSUE THREAD

**Issue by piratestatic** [offensive-security/kali-nethunter#569]
### Device:
Nexus 7 (2013)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmellow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gcc51ee3-dirty(root@kali)(gcc version 4.7(GCC)) #4 SMP PREEMPT Sat Dec 12 00:29:55 UTC 2015

## Issue:
I enter service postgresgl start and that works fine
then I type service metasploit start and I get metasploit unrecongnized service

I can get msfconsole to work but it doesn't recognize msfpayload.

Can someone help me fix what I am missing

**Comment by akrolla** [comment]
In the apps of the nerhunter interface is the payload generator scripts,
also check to start metasploit in kali services and start it.

**Comment by binkybear** [comment]
https://www.kali.org/releases/kali-linux-20-released/

> specifically, there is no longer a metasploit service

Use msfvenom instead of msfpayload.

**Comment by piratestatic** [comment]
@binkybear thanks for the msfvenom, @akrolla  didn't know that tool existed thanks for pointing that out
One more question, I am running Kali version 3.0.5 (release keys) Built by Kali at 2016-02-02, I have been seeing there is a 3.15? When I go to update it I get please uninstall previous versions before installing this one...can someone give me the slow kids guide on how to do this? I have been trying to update with no success.

**Comment by binkybear** [comment]
Uninstall the app?  Downloaded the latest.apk first.  Then just hold down icon and put it in trash.  Use a file manager to install latest apk (something like es explorer or free CM file manager).  You could do it more easily with adb (adb install latest.apk).

**Comment by akrolla** [comment]
Yea it wont install new apk until the prior one is deleted.

**Comment by piratestatic** [comment]
@akrolla  Some how I feel like you are giving me information I already knew but had to hear it from someone else for it to click. @binkybear  I got a little worried when I deleted it and nothing worked... I downloaded es explorer and I am better now. Thanks guys really.

**Comment by akrolla** [comment]
Probably, lmao. I'm mr obvious stater. It helps cement it in for me when I
have knowledge of something and someone else explains it . It helps cement
it into your long term memory. Im pretty passionate about this project and
try to help with as much as I can with what i know so binky and the others
can work on some more great features for It  . I am still in school
learning my languages And hope one day I can contribute more.

**Comment by 2EASY4HACK** [comment]
msfpc not working :(

**Comment by bozwald** [comment]
Try running apt-get install metasploit-framework

**Comment by amzker** [comment]
Yes This Error
Is Not Solved By Devs
