### ISSUE TITLE
Fails to install downloaded apk update.

### ISSUE THREAD

**Issue by webkodex** [offensive-security/kali-nethunter#571]
### Device:
Motorola Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

https://www.offensive-security.com/kali-linux-nethunter-download/nethunter-shamu-marshmallow-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.40-g15269a3-dirty (root@kali) (gcc version 4.7 (GCC) )#3

## Issue:

Cannot update to version 3.15, after downloading apk & when i try to install it says app not installed.

**Comment by vay3t** [comment]
first, u need unintall the old apk

**Comment by webkodex** [comment]
uninstall old apk ? you mean uninstall  nethunter app from device ?

**Comment by vay3t** [comment]
yes

**Comment by webkodex** [comment]
Thanks i did exactly. uninstalled old apk & installed latest, rebooted now everything works fine.

**Comment by marxenegls** [comment]
i'm confused , if i uninstall the old app how will be able to launch the nethunter app to update or can  i download the update,  uninstall the old first before installing the newer one? 
... it does have the remind me later option , so it is possible it would work that way. 
of coarse trying either option could cost me a lot of time 
.. It ought to be made clearer, 
and where is the apk at play store or @ offensive-sec
