### ISSUE TITLE
Nethunter can't find BusyBox

### ISSUE THREAD

**Issue by seanwlk** [offensive-security/kali-nethunter#572]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.110-cyanogenmod-gdb51504 (build02@cyanogen) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Jun 16 21:53:08 PDT 2016
## Issue:
After a busybox binary update "Nethunter can't find busybox" I'm currently using version 1.24.2 Stericson.
I'm not completely sure if it's actually busybox related, can someone confirm that while using that version Nethunter still works?

**Comment by binkybear** [comment]
I made an app that might help: https://github.com/binkybear/busybox/releases/download/1.24.3/busybox.apk

**Comment by seanwlk** [comment]
Indeed, this version of busybox fixed the issue, so it was actually Stericson's version the issue.

**Comment by asihu** [comment]
Binky...its works.thanks
