### ISSUE TITLE
Knowing your limits

### ISSUE THREAD

**Issue by piratestatic** [offensive-security/kali-nethunter#573]
***this may or may not be in the wrong spot***
So what are major/hard limits to a device not being able to support Nethunter/Kali Linux mobile? At first I thought it was the Snapdragon 800 series processor but it seems that isn't the case.

I was also looking at the Pwn Phone by Pwnie Express (https://www.pwnieexpress.com/build-pwn-phone) and their builds aren't as expansive as the Nethunters but they are working on releasing the exact same ones. That may be due to taking the easy route out and not re-inventing the wheel.

I am just curious from the developers side why certain phones are able to and others that seem to be running the same operation system and can be unlocked, can't run Nethunter.

**Comment by binkybear** [comment]
Answered in other repo.
