### ISSUE TITLE
Error: Terminal app not found

### ISSUE THREAD

**Issue by Neto** [offensive-security/kali-nethunter#574]
I have Nethunter running on a Nexus 6 but I keep getting the error Terminal app not found, can't continue.

Nethunter Terminal run, but chroot on Nethunter app can't identify it

Please help!

**Comment by BeNeDeLuX** [comment]
*WORKAROUND* 
Please open your kalifs-full-rolling....zip file on your Nexus device and install the Term-nh.apk from the data/app/ Folder.

**Comment by cyba3r** [comment]
Not working in my case...

**Comment by binkybear** [comment]
You could always download it from this repo: 
https://github.com/offensive-security/kali-nethunter/raw/master/nethunter-installer/update/data/app/Term-nh.apk

I've also uploaded a new one for testing: https://transfer.sh/9F34P/term-release.apk

**Comment by jcadduono** [comment]
hehe i ended up in their boat, i can't seem to get the terminal app to install either <.> i don't know much about the android app system but yeah, it just says "Failed to install" for both of those

**Comment by binkybear** [comment]
@jcadduono and I talked a bit about this on IRC.  

I believe issue is because the app is signed now for release and earlier version are not uninstalling completely.  Possibly related to below:

http://stackoverflow.com/questions/32737714/can-not-install-my-own-generated-apk/33911634#33911634

**Comment by jcadduono** [comment]
so it seems you can install the one i just linked, then uninstall that, and then installing signed release ones from now on should work

**Comment by Rinilyn** [comment]
yea i installed the one you linked,it still gives App not installed. The one in the full rolling rar fails too. i should mention that i jumped from version 3.15 to the latest nightly build (2017-10-12).
the nethunter app wasnt installed too but it didnt fail to install

**Comment by amzker** [comment]
Reinstall Chroot


Flash New Zip


Check package name
Need com.offsec etc
