### ISSUE TITLE
Nexus 5 No Title ERROR

### ISSUE THREAD

**Issue by luma420** [offensive-security/kali-nethunter#575]
### Device:

Nexus 5
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Mashmallow
### Built from repo (date and build command) or downloaded from website (links):

Downloaded nethutner from the official page. 
## Issue:

No Title as soon as i open the terminal with the kali option. Tried to reinstall chroots via nethunter app without sucsess

**Comment by vay3t** [comment]
u need build nethunter from github
