### ISSUE TITLE
Successful Build of Nethunter for Nougat Nexus 9 (Flounder)

### ISSUE THREAD

**Issue by hackdefendr** [offensive-security/kali-nethunter#576]
### Device: 
Nexus 9 (Volantis/Flounder)

### OS version (KitKat/Lollipop/Marshmallow/Nougat): 
Nougat

### Built from repo (date and build command) or downloaded from website (links): 
Built from repo today 09/16/2016.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 
N/A

## Issue:

Successful built Nougat supported version of Nethunter for my Nexus 9 (Flounder). 

* 11 minute total install.
* 1 loop during boot
* No errors
* Android 7.0 (Latest patches)
* Kali Linux FULL

Should I or can I make this available so others can test it?

Later,
J

**Comment by jcadduono** [comment]
By all means, do so! 
Just make sure you're providing sources to your kernel on GitHub publicly with your full modifications.

You may also submit a pull request on the nethunter-devices repository. It's awesome when users with devices can maintain nethunter for their devices, so go for it! 

Don't forget to read the README.md in the nethunter-devices repository for instructions on adding your own device.

:)

**Comment by hackdefendr** [comment]
Well that is easy, this first go at it I used everything as-is. No changes made.

However, when I started to test the applications I hit some auto-close issues and timeouts. So I may just need to fork it and see whats up with the old debugger.

Not unexpected, but still when the install goes as clean and fast as it did, you really want everything to work. No fun in that... :)

**Comment by hackdefendr** [comment]
The ROM is here: https://www.hackdefendr.com/?page_id=195

If anyone else with a Nexus 9 wants to give it a go.

**Comment by hackdefendr** [comment]
Closing this to open a new one for actual help.
