### ISSUE TITLE
Request to get milestones/contribution guides to get more contribution from the community.

### ISSUE THREAD

**Issue by thel3l** [offensive-security/kali-nethunter#579]
### Device:
-Na-

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

-Na-

### Built from repo (date and build command) or downloaded from website (links):

-Na-

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

-Na-

## Issue:

Can we please get a development roadmap or milestones on Github to allow easier contribution from the community? Right now, other than the main devs (who are doing a spectacular job :)), none of us know *what* to contribute to the project - the wiki has guides to actually setting up the project, and basic instructions, but we don't know **the long term objectives or goals**. This would really be helpful - even if a full-fledged guide isn't possible, at least a list of objectives that is regularly updated. Example:

* Improve stability of _
* Fix permission error with _
*  Update kernel versions for all devices _

Thanks!

**Comment by binkybear** [comment]
That's a good idea.  Do you have any examples or ideas which tracks that kind of roadmap?  Maybe something that integrates with github?

**Comment by thel3l** [comment]
Yep. How about just using Github Projects? You can set details of each pane, and have several panes under every release of NetHunter.

Example: 

https://github.com/thel3l/exampleNH/projects

I just made that repo for an example. I think that would help get more people onboard, working towards an aim.

**Comment by thel3l** [comment]
Got a couple of examples of this:

**Comment by thel3l** [comment]
A good site to help with this seems to be Unito:

https://unito.io/

**Comment by akrolla** [comment]
Yea and perhaps a section for each type of phone so as to seperate issues a
little better also that would be a long list but only include known working
or recommended devices. The only place I see the issues is when they get
emailed and in the news section so it becomes confusing when tracking a
particular issue.

**Comment by binkybear** [comment]
Github projects sounds like an easy enough.  I looked at unito and it's kind of hacky to get it working with public repo.  Figure it would be easier to just keep things on github.

**Comment by jcadduono** [comment]
Just throwing it out there, my dream request from someone would be to add:
https://github.com/phhusson/sepolicy-inject (v1 and v2)
to the project, and create permissive policy injections that apply to the our busybox and entire nhsystem domain :)
this way nethunter can run happily on selinux enforcing kernels!

**Comment by binkybear** [comment]
@jcadduono - You can actually do it with supersu:

https://su.chainfire.eu/#selinux-policies-supolicy

example
```bash
supolicy --live "allow sdcardd unlabeled dir { getattr read }"
```
I've only looked at selinux briefly.  I believe otherwise we would have to create a policy and inject into all ramdisks...I think.

**Comment by akrolla** [comment]
Can you run SET from the phones terminal?

**Comment by akrolla** [comment]
Nevermind running wrong command-_-

**Comment by thel3l** [comment]
All right! Looking forward to it!
