### ISSUE TITLE
Pineapple Connector / Unable to change IP´s / Wrong IP-Range ?

### ISSUE THREAD

**Issue by BeNeDeLuX** [offensive-security/kali-nethunter#580]
### Device:
OnePlus One

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow (CM 13 / 2016-08-19))

### Built from repo (date and build command) or downloaded from website (links):
https://idlekernel.com/nethunter/nightly/3.15-20160914-1734/
Lastet NetHunter App Build 3.15 (2016-06-04).

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.112-cyanogenmod-g8fbc62e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016

## Issue:
I´m unable to change any IP-Address in the Pineapple Connector menu because i can´t add a dot to the input fields. The default IP-Range if you connect the Pineapple Nano via OTG is 192.168.42.x /24 instead of 172.16.42.x/24. The IP-Range 172.16.42.x/24 is only used for the WiFi connection - not for the OTG Connection. So i´m a but confused about the default settings.

What´s about the "No upstream" option ? Is it only a connection to the pineapple for management without routing the traffic?

**Comment by binkybear** [comment]
Decimal problem is an easy fix...just wish I had noticed it sooner.  Here's an apk:

https://transfer.sh/jn1Tm/nethunter-app-debug.apk

I'm not sure about 192.168.42.x/24 range.  If you want to connect to the pineapple gateway/webserver its usually on the 172.16.42.1:1471.  So this sets up an ethernet interface with the nano in the same subnet as that range.

By default the script allows "upstream" so that your pineapple will access the wlan0 for internet.  If you just want to connect to pineapple web interface but don't need the internet then you would check it.

**Comment by BeNeDeLuX** [comment]
The new decimal fix works just fine. Thanks!
I will check the the Pineapple Connector now and give you a feedback. 

More info´s about the IP-Ranges via Ethernet and USB-OTG --> http://wiki.wifipineapple.com/#!connectivity.md

Ethernet:
> By default the WiFi Pineapple is expecting an Internet connection from 172.16.42.42 on its LAN. Connect the WiFi Pineapple LAN port to the Linux PC host. On the NANO this is the male USB A plug.

USB Tethering:

> If USB Tethering is supported by the Android device, when enabled it will enumerate on the WiFi Pineapple as a new network interface, usb0, and the WiFi Pineapple will automatically adjust its kernel routing table to use this interface for its Internet access, as well as Internet access for any clients connected to the WiFi Pineapple. Via DHCP, the WiFi Pineapple will receive an IP address on the Android devices internal network (typically 192.168.x.x).

**Comment by binkybear** [comment]
I see now thanks.  That's because the pineapple connector app uses the usb0 tethering interface to assign an IP with DHCP where our script just connects as a client.

**Comment by BeNeDeLuX** [comment]
The Pineapple Connector doesn´t work in my test. But i´m sure you know it already because of your last post and the the usb interface (rndis0). I just changed the IP Ranges inside the App to the correct one for a test, but nothing happen.

The URL that the App open after you start the "Setup Connection" is wrong. There is always the string"null" directly behind the port. For Example: "http://192.168.42.129:1471null"

**Comment by BeNeDeLuX** [comment]
Yes this is the original app from Hak5. This App works fine but has absolute no options like upstream or special port forwarding. If the basic pineapple connector module works inside the nethunter app, some more options could be added in the future.

**Comment by binkybear** [comment]
@BeNeDeLuX -You can try running it manually to see where error is:

https://github.com/offensive-security/nethunter-app/blob/master/assets/scripts/pine-nano

I've tested it on OnePlus1 and it works without issue.  It should be run on the androidsu side (from /data/local)

**Comment by BeNeDeLuX** [comment]
@binkybear - shame on me! This was my fault, i´m sorry!

There are two ways to connect the Pineapple Nano. 
Here is the default Hak5 way **(USB Tethering)**
![cameringo_20160919_201729 - kopie](https://cloud.githubusercontent.com/assets/1895086/18643931/8f104864-7ea7-11e6-9048-a932ef5bf7bf.jpg)

And here is the connection the Nethunter Pineapple Connector uses **(Ethernet)** 
![cameringo_20160919_201223 - kopie](https://cloud.githubusercontent.com/assets/1895086/18643930/8f0f051c-7ea7-11e6-82fd-3a42614608b4.jpg)

I use the wrong connection during my Nethunter tests.

So only the URL needs to be corrected. (remove the "null" behind)
