### ISSUE TITLE
[Request] Wake-lock

### ISSUE THREAD

**Issue by lavanoid** [offensive-security/kali-nethunter#582]
## Issue:

The Kali NH app should have a wake-lock when installing the CHROOT, as when the device goes into sleep mode the CPU drops into a powersave mode depending on what governor the user has set.

I currently have to change my screen timeout to prevent this but a wake-lock would definitely make sense.

**Comment by binkybear** [comment]
I have added wakelock ^^.  Needs testing if anyone has time.
