### ISSUE TITLE
Stuck at oneplus logo with included kernel

### ISSUE THREAD

**Issue by larsveelaert** [offensive-security/kali-nethunter#583]
## Issue:

When flashed nethunter trough TWRP, after reboot to system, the android logo dissapears and the oneplus logo stays. The device is stuck at this point

The version from Nethunter I flashed is built by myself with the python scripts.
When I built a boot.img from CM13 and flash it the devices boots fine with everything installed ( but no modified kernel )
Clearly a problem with the kernel.

What can I do to fix this?
Is this a known problem?

**Comment by polarsbear** [comment]
New developement. Found a compiled kernel from March (Onyx, Nethunter, 20160516) (link: https://www.androidfilehost.com/?fid=24533103863139802)
Then flashed a SuperSU image v 2.74 over it modified for oxygenOS for the onplus 3.

Device boots a couple of times, but ends up fully booted, everything working.
Still a bug on the normal way of installing, also I notice the root management program has changed. (not the standard CM root manager, but SuperSU app)

**Comment by polarsbear** [comment]
UPDATE: HID and Wlan0 not working (only things I tested)

**Comment by jcadduono** [comment]
Yeah it needs a major update its a bit out of date at the moment I'll get to it when I have the time unless someone else wishes to volunteer as I don't have the device

**Comment by polarsbear** [comment]
I want to get into this, can you give me some guides? a way to debug? (get logs out the device)
I am working on it now and it seems the SuperSU fix is just rewriting the backup boot.img (kernel), so that is were the Wlan1 and HID problem comes from.

**Comment by binkybear** [comment]
I don't have device either.  It's a been a while since it's been updated.

**Comment by polarsbear** [comment]
I was thinking of starting all over from the official CM13 kernel for onyx and applying the patches. Or is there a better way to go about it.
In other words, are the most changes made in de network drivers stack and other kernel config options?
Thanks

**Comment by jcadduono** [comment]
It's on my GitHub nethunter_kernel_onyx I think, you could probably get away with clone, add remote cm13, and then git rebase it

**Comment by polarsbear** [comment]
Ok, thanks, working on it now. I'll keep you posted

**Comment by polarsbear** [comment]
UPDATE: got it working for HID attacks, just need to configure the OTG USB drives for wifi and sdr
the repo: https://github.com/polarsbear/nethunter_kernel_oneplusx_cm
