### ISSUE TITLE
where is kali 2016.2 vmware box version for download?

### ISSUE THREAD

**Issue by Maple-Wang** [offensive-security/kali-nethunter#585]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

where is kali 2016.2 vmware box version for download?

### Built from repo (date and build command) or downloaded from website (links):

where is kali 2016.2 vmware box version for download?

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
where is kali 2016.2 vmware box version for download?

## Issue:
where is kali 2016.2 vmware box version for download?

**Comment by binkybear** [comment]
This is not related to Nethunter.  Please use google.
