### ISSUE TITLE
TP-LINK TL-WN722N not working with Nexus6 and Nethunter

### ISSUE THREAD

**Issue by Neto** [offensive-security/kali-nethunter#586]
Nexus 6

Linux kali 3.10.40-g27906c4 #1 SMP PREEMPT Tue Aug 9 18:53:52 UTC 2016 armv7l GNU/Linux

Please help! I just can't make TP-LINK TL-WN722N work with nethunter on my Nexus6.

**lsusb:**
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 05c6:90a4 Qualcomm, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**root@kali:~# iwconfig**
r_rmnet_data7  no wireless extensions.
r_rmnet_data4  no wireless extensions.
wlan0     no wireless extensions.
r_rmnet_data1  no wireless extensions.
sit0      no wireless extensions.
dummy0    no wireless extensions.
r_rmnet_data6  no wireless extensions.
r_rmnet_data3  no wireless extensions.
lo        no wireless extensions.
rmnet_usb0  no wireless extensions.
rmnet_data7  no wireless extensions.
rmnet_data6  no wireless extensions.
rmnet_data5  no wireless extensions.
rmnet_data4  no wireless extensions.
rmnet_data3  no wireless extensions.
rmnet_data2  no wireless extensions.
rmnet_data1  no wireless extensions.
rmnet_data0  no wireless extensions.
r_rmnet_data8  no wireless extensions.
r_rmnet_data0  no wireless extensions.
r_rmnet_data5  no wireless extensions.
usb0      no wireless extensions.
r_rmnet_data2  no wireless extensions.

**modprobe ath9k_htc:**
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.40-g27906c4/modules.dep.bin'
modprobe: FATAL: Module ath9k_htc not found in directory /lib/modules/3.10.40-g27906c4

**Comment by jcadduono** [comment]
The Shamu kernel isn't using modules, we ask for /proc/version output so we can see the user who built the kernel, this will tell us if the kernel was installed successfully.

**Comment by Neto** [comment]
root@kali:~# cat /proc/version
Linux version 3.10.40-g27906c4 (android-build@kpfi9.cbf.corp.google.com) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Tue Aug 9 18:53:52 UTC 2016

Thanks for your answer.
This means anything to you?
I thought TL-WN722N had native nethunter support.
Tottaly lost on how to make it work.

**Comment by jcadduono** [comment]
Yes that means you don't have the nethunter kernel installed (that is built by Google)
You can try installing by building a zip from git or download the kernel installer prebuilt from idlekernel.com/nethunter/nightly

**Comment by Neto** [comment]
Jcadduono
I tried to twrp install kernelnethunter.zip now I'm stuck on recovery mode.
Sorry so many questions...I'm a noob on android. I have a rapiPi3 working perfectly with Kali

**Comment by jcadduono** [comment]
Which zip did you install specifically?
It might need to be updated for newer OS

**Comment by Neto** [comment]
Well...I'm starting all over again.
Flashing shamu-mob31e-factory-051e2d25.zip now.
Then I have this options to flash nethunter. Don't know which I should use.
Should I use the newest one?
kernel-nethunter-hltekor-lollipop-3.1.0-20160910-2236.zip  
kernel-nethunter-shamu-lollipop-3.1.0-20160831-1936.zip  
kernel-nethunter-shamu-lollipop-3.15-20160914-1734.zip 
kernel-nethunter-shamu-lollipop-3.15.2-20160922-0014.zip

**Comment by Neto** [comment]
Sorry to bother you guys.
Here's what I did step  by step:

Flash shamu-mob31e-factory-051e2d25.zip worked fine.
Installation of SuperSU worked fine.
Flash kernel-nethunter-shamu-lollipop-3.15.2-20160922-0014.zip
Install run ok
After reboot, I'm sucked on TWRP.
I'm probably doing something stupid.

**Comment by jcadduono** [comment]
MOB31E the M stands for Marshmallow and you're flashing a Lollipop kernel :P

**Comment by Neto** [comment]
man
I'm flashing lollypop for DAYS. :(

**Comment by Neto** [comment]
jcadduono
Thank you! Everything working great!
(Although ssh is crashing constantly)

**Comment by Neto** [comment]
hi @jcadduono

Can you help again?

I used TWRP to install
 kernel-nethunter-shamu-marshmallow-3.15.2-20161014-0038.zip

But instead of 3.15.2 version is still 3.10.40
what am I doing wrong?

root@kali:~# cat /proc/version
Linux version 3.10.40-g819dcd6 (root@nh-buildbox)

**Comment by jcadduono** [comment]
Lol this is why we should get out of the 3.x.x naming scheme :p you have the right kernel... That's the Linux version!

**Comment by Neto** [comment]
Is there a tool to notify each new kernel?



On October 15, 2016 at 2:46:54 PM, James Christopher Adduono (notifications@github.com<mailto:notifications@github.com>) wrote:

Lol this is why we should get out of the 3.x.x naming scheme :p you have the right kernel... That's the Linux version!

**Comment by jcadduono** [comment]
just watch https://github.com/offensive-security/nethunter-devices/commits/master

**Comment by manuelhz** [comment]
Hi,
I have the Nexus 6 Runing NH 3.1, I wanted use the TP-LINK TL-WN722N, and i had the same isue that Neto, so I have flashed kernel-nethunter-shamu-marshmallow-3.15.2-20161014-0038.zip, using NRT V2.1.9. The process works ok, but now my internal wifi doesn't work (It doesn't show any wi-fi network)  and the TP-LINK TL-WN722N seem working, but cannot be on monitor mode.

root@kali:~# cat /proc/version
Linux version 3.10.40-g819dcd6 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Sep 23 23:12:26 UTC 2016

root@kali:~# iwconfig
wlan0     IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=31 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          
wlan1     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=0 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

root@kali:~#lspci
00:00.0 PCI bridge: Qualcomm Device 0101
01:00.0 Network controller: Broadcom Limited BCM4356 802.11ac Wireless Network Adapter (rev 02)

root@kali:~#lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 05c6:90a4 Qualcomm, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@kali:~#dmesg
[dmesg.txt](https://github.com/offensive-security/kali-nethunter/files/742932/dmesg.txt)

Please help me.

Thank you ...

**Comment by manuelhz** [comment]
I flash my phone with factory image MOB30I compilation, and then flash the kernel. After that, the internal wifi doesn't work, so I mean the kernel kernel-nethunter-shamu-marshmallow-3.15.2-20161014-0038.zip is not compatible. How can I find the compatible with Net Hunter kernel for my device ?

**Comment by jcadduono** [comment]
the first thing you should do before posting about an issue is try the latest version, read the wiki

**Comment by manuelhz** [comment]
Jcadduono, thanks for your answer.
It was my steps:
Install Nexus Root Toolkit 
Restore device from factory
Unlock the bootloader
Root the device
Flash the next files:
nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170202-1604.zip
kernel-nethunter-shamu-marshmallow-3.15.4-20170202-1604.zip
Now I have wlan0 and wlan1, and I can make wlan1 works fine (it include packet injection), but I can’t use the internal wifi. I have the same vehaviour that with previous installation.
Mae be I’m doind something wrong?

**Comment by manuelhz** [comment]
I don't know why,  but the Kernel file: 
kernel-nethunter-shamu-marshmallow-3.15.4-20170202-1604.zip
 doesn't work properly, more especifically Internal Wifi doesn't work after flashing this kernel,
May be the Android Compilation or the device (Nexus 6 shamu marshmallow MOB30I compilation).
I solve my problem using PwnKernel by Dragonhunt3r.
It's the download link:
https://forum.xda-developers.com/devdb/project/dl/?id=16683&task=get
Now I have my NetHunter Running with my TP-LINK TL-WN722N. Monitor mode, Packet Injection and Aircrack-ng Runing.

**Comment by farouk25** [comment]
manuelhz 
commented 3 months ago
I don't know why, but the Kernel file:
kernel-nethunter-shamu-marshmallow-3.15.4-20170202-1604.zip
doesn't work properly, more especifically Internal Wifi doesn't work after flashing this kernel,
May be the Android Compilation or the device (Nexus 6 shamu marshmallow MOB30I compilation).
I solve my problem using PwnKernel by Dragonhunt3r.
It's the download link:
https://forum.xda-developers.com/devdb/project/dl/?id=16683&task=get
Now I have my NetHunter Running with my TP-LINK TL-WN722N. Monitor mode, Packet Injection and Aircrack-ng Runing

Please i have have problèmes withe m'y nethunter  on one plus one wlan1 dont up

**Comment by Gabrigawr** [comment]
Has your issue been resolved?
