### ISSUE TITLE
Nexus 5x android 7 nougat support ?

### ISSUE THREAD

**Issue by majackov** [offensive-security/kali-nethunter#589]
### Device:
nexus 5x
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat
## Issue:
Nexus 5x with android 7 (nougat) support nethunter?

**Comment by jmingov** [comment]
Not at this moment. There are big changes, and the first tests dindt worked.

We will upodate the wiki information when it is ready to go.

**Comment by Physicist1616** [comment]
So at least for not crashing things in nougat, I found that I needed to have another terminal emulator to do su and bootkali before I could use csploit, the Kali terminal, and the VNC.  I haven't done full functionality tests other than getting those crashes to stop.

**Comment by dopetik** [comment]
Hi!
I managed to install nethunter on my Nexus 5x (bullhead) with stock nougat (android 7)
major pb is the new app permissions system...
1_ make a backup of all important data
2_ download and flash factory image from google > https://dl.google.com/dl/android/aosp/bullhead-nrd90s-factory-d6bf1f56.zip
3_restart phone and complete the android setup wizard
4_download and flash latest nethunter kernel for bullhead from https://idlekernel.com/nethunter/nightly/3.15.2-20160922-0014/kernel-nethunter-bullhead-nougat-3.15.2-20160922-0014.zip
5_ reboot (not sure this is really needed)
6_ download and flash latest nethunter > https://idlekernel.com/nethunter/nightly/3.15.2-20160922-0014/update-nethunter-generic-armhf-3.15.2-20160922-0014.zip
7_ on a computer or with a app, extract all apk from update-nethunter-generic-armhf-3.15.2-20160922-0014.zip
8_ uninstall / reinstal all app (specially nethunterapp and terminal_nh)
9_ launch nethunter and allow all permissions
10_ reboot and start netunter app
11_ use nethunter app to down and install kali chroot
Done ;)

(monitoring mode ok, some bugs with terminal emulator)

**Comment by AgeOfMarcus** [comment]
Hey @dopetik, can you upload the kernel from idelkernel.com as the site seems to be down. Can you also upload the nethunter file from idlekernel? Thanks.

**Comment by jcadduono** [comment]
@AgeOfMarcus search build.nethunter.com/nightly for a similarly named file.
my site idlekernel.com was moved to build.nethunter.com (they are essentially the same, however old builds may have been purged)

**Comment by AgeOfMarcus** [comment]
@dopetik does it need to be exactly the same or just one of the 3.15.2 ones?
