### ISSUE TITLE
Clean install crashing

### ISSUE THREAD

**Issue by Neto** [offensive-security/kali-nethunter#590]
Nexus 6
Marshmallow
nethunter-shamu-marshmallow-3.0
kernel-nethunter-shamucm-marshmallow-3.15.2-20160922-0014
...
Linux version 3.10.102-nethunter-g79824c9-03314-g0757761 (root@kali) (gcc version 4.9.4 20160726 (optimized) (UBERTC-4.9.4) ) #1 SMP PREEMPT Sat Aug 27 18:13:31 CEST 2016
...

After two attempts of cleaning install (flash factory etc), Nexus 6 is crashing constantly.
Seems to be related to the use of the USB port.
Crashes when connected to a Mac during an SSH session or to the TPLink WN722N
NetHunter app is 3.15
Any tips?

**Comment by binkybear** [comment]
After it crashes can you run a:
```bash
cat /proc/last_kmesg > /sdcard/crash.txt
```

**Comment by Neto** [comment]
Hope this is what you want. 
I don't have a last_kmesg only a ksmg.
Here it goes:

http://ncpm.me/hZL9

**Comment by binkybear** [comment]
I've updated kernel up to latest.  It was a bit behind...not sure if this will help you or not:

https://transfer.sh/qgUFa/kernel-nethunter-shamu-marshmallow-20160923-192921.zip

**Comment by Neto** [comment]
Coll. I'll try it and let you know.
Thank you

**Comment by Neto** [comment]
Maybe it is too soon to say, but no crash with the new kernel for while.
And yesterday, every time I ssh-copy-id from mac to nexus it crashed.
Today worked flawless.
Keep you posted.
