### ISSUE TITLE
Nexus 9 Kali Boot Animation and reset loop

### ISSUE THREAD

**Issue by RS-Influential** [offensive-security/kali-nethunter#591]
Nexus 9
Marshmallow 6.0.1
Nethunter-flounder-marshmallow-3.0.zip

Hello all,

Just installed Nethunter for the second time and it just keeps on opening at a reduced screen, getting to the point where it shows the Kali graphic, it flashes for a bit then restarts and continues along that loop.

**Comment by binkybear** [comment]
Are you getting a boot loop?  It won't run at all??

**Comment by RS-Influential** [comment]
Just a boot loop. It will not run at all. I ran a clean install of Marshmallow and retried and still have the same results.

**Comment by binkybear** [comment]
Try flashing the latest kernel from this repo or from:
https://idlekernel.com/nethunter/nightly/3.15.2-20160922-0014/kernel-nethunter-flounder-marshmallow-3.15.2-20160922-0014.zip

**Comment by RS-Influential** [comment]
So I discovered that TWRP 3.0.2-1 was looping so I added TWRP 3.0.2-0 and now it just hangs on the TWRP boot animation. Should I go with a lower version in order to try and flash the kernel? Sorry for being such a drag, just learning most of this right now.

**Comment by binkybear** [comment]
TWRP takes about 5-10 minutes to boot on the Nexus 9 (not sure why).  I would suggest first just try waiting it out.

**Comment by RS-Influential** [comment]
Waiting it out worked. I flashed the new kernel and still have the same issue. In the log I have at lot of lines pointing to "Error opening: /data/local/nhsystem/kali-armhf/dev/ (Not a directory)"

**Comment by carterhuangfu** [comment]
anybody could fix it up since I have encountered with the same issue, 
 "Error opening: /data/local/nhsystem/kali-armhf/dev/ (Not a directory)"
