### ISSUE TITLE
apt-get update Err 404

### ISSUE THREAD

**Issue by Neto** [offensive-security/kali-nethunter#592]
Nexus 6
Marshmallow
nethunter-shamu-marshmallow-3.0
Linux version 3.10.40-g819dcd6 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Sep 23 23:12:26 UTC 2016

apt-get update reports packages not found.
My source.list is the original:
deb http://http.kali.org/kali sana main non-free contrib
#deb-src http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/ sana/updates main contrib non-free
#deb-src http://security.kali.org/ sana/updates main contrib non-free

Any clues?

------------

root@kali:/# apt-get update
Ign http://security.kali.org sana/updates InRelease
Ign http://security.kali.org sana/updates Release.gpg
Ign http://security.kali.org sana/updates Release
Hit http://http.kali.org sana InRelease
Get:1 http://http.kali.org sana/non-free armhf Packages [118 kB]            
Get:2 http://http.kali.org sana/main armhf Packages [12.5 MB]                               
Get:3 http://http.kali.org sana/contrib armhf Packages [65.3 kB]                            
Ign http://http.kali.org sana/contrib Translation-en_US                                                            
Ign http://http.kali.org sana/contrib Translation-en                                                               
Ign http://http.kali.org sana/main Translation-en_US                                                               
Err http://security.kali.org sana/updates/main armhf Packages                                                      
  404  Not Found
Ign http://http.kali.org sana/main Translation-en                                                                  
Err http://security.kali.org sana/updates/contrib armhf Packages                                                   
  404  Not Found
Ign http://http.kali.org sana/non-free Translation-en_US                                                           
Err http://security.kali.org sana/updates/non-free armhf Packages                                                  
  404  Not Found
Ign http://http.kali.org sana/non-free Translation-en                                                              
Ign http://security.kali.org sana/updates/contrib Translation-en_US                                                
Ign http://security.kali.org sana/updates/contrib Translation-en                                                   
Ign http://security.kali.org sana/updates/main Translation-en_US                                                   
Ign http://security.kali.org sana/updates/main Translation-en                                                      
Ign http://security.kali.org sana/updates/non-free Translation-en_US                                               
Ign http://security.kali.org sana/updates/non-free Translation-en                                                  
W: Failed to fetch http://security.kali.org/dists/sana/updates/main/binary-armhf/Packages  404  Not Found          

W: Failed to fetch http://security.kali.org/dists/sana/updates/contrib/binary-armhf/Packages  404  Not Found

W: Failed to fetch http://security.kali.org/dists/sana/updates/non-free/binary-armhf/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by binkybear** [comment]
@Neto - That is an older chroot (sana).  The new chroot is for kali-rolling and doesn't need that.  Read the README:

http://security.kali.org/README

You can use an old deb if you want to continue to use sana (see above link).  If you plan on upgrading you will need to download latest nethunter app and redownload chroot.

**Comment by Neto** [comment]
Understood.
How I can make sure I have the latest nethunter app?
Just downloaded the one from the link at the bottom of this page: 
https://github.com/offensive-security/kali-nethunter/wiki
Installing chroot right now. 
Hope is the correct one...

**Comment by pindonga1234** [comment]
Understood.
How can I make sure I have the latest nethunter app?
Just downloaded the one from the link at the bottom of this page:
https://github.com/offensive-security/kali-nethunter/wiki
Installing chroot right now.
Hope is the correct one...
Thank you for the help!
-------------------------------------------
Hi Im a lammer can you help me to install the new chroot, not even I cant find it in https://github.com/offensive-security/kali-nethunter/wiki Is it in https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer? Do I have to download update.zip and installed it with TWRP?

**Comment by Neto** [comment]
@pindonga1234
1. Download the most recent app from the botton of the page you linked on your message.
2. On your current nethunter app, remove your chroot, reboot, remove the app
3. Connect to a computer and "adb install <new nethunter app>
4. After installing, reinstall new chroot from inside new nethunter app

**Comment by Neto** [comment]
@binkybear 
All good.
New version, new chroot with kali rooling
Thanks!!!!

**Comment by RobinJesba** [comment]
Help me with 404 error kali linux

**Comment by RobinJesba** [comment]
Help me with lateat source.list

**Comment by anonymus2727** [comment]
Hi! Guys I downloaded the latest app and my sourcelist is new but I have the 404 issue.Help will be appreciated
