### ISSUE TITLE
Bettercap

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#593]
### Device:
Nex 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

downloaded from kali.org Apk and chroot up to date to today.

### Output of `cat   /proc/version` in adb shell or NetHunter Terminal:

linux version 3.4.0-gb7558f2    Gcc 4.7 #2 preempt WED Oct 7 02:16:12 utc 2015
## Issue:

Bettercap errors As seen in photos below. How do I rectify?

https://goo.gl/photos/F5stpx7KBh4HSxzT6

**Comment by binkybear** [comment]
Can you tell me what command/args you are running.  I know some people had issues where it required them to set the gateway in order to get it running.

**Comment by akrolla** [comment]
Just bettercap

**Comment by akrolla** [comment]
I probably have to set the gateway I don't believe I did that. I thought
maybe I called the wrong command like I did with SET the other day.

**Comment by akrolla** [comment]
I shouldve added this one also
https://goo.gl/photos/nJSzPyYmMPbVNpQ9A

**Comment by binkybear** [comment]
Try setting more arguments: https://www.bettercap.org/docs/main.html#examples

Are you trying to run it on rmnet0?

**Comment by akrolla** [comment]
attempting to. Then I just remembered the nexus 5 can't inject as it is
right? Id have to get nexmon I believe .

**Comment by vay3t** [comment]
I would like to help but I cant see links of google

**Comment by akrolla** [comment]
Anybody with link can see

**Comment by akrolla** [comment]
here's a consolidated link

https://goo.gl/photos/o34v7wX4jmSqUjdj7

I'm going to read into it @binkybear ill let you know.

**Comment by akrolla** [comment]
I dont think it'll work with rmnet0 because of the antennae in the nexus
without that nexmon patch.What do u think

**Comment by akrolla** [comment]
Yea @binkybear I ran some arguments  and get the same error

**Comment by akrolla** [comment]
there's also a new csploit apk out

On Sep 24, 2016 7:29 PM, "cody webb" <cody.l.webb@gmail.com> wrote:

Yea @binkybear I ran some arguments  and get the same error

**Comment by akrolla** [comment]
I need to download the boot.img for that nexmon (nexus monitoring mod) and
apply it via adb @binkybear is this going to cause any problems with NH?
Could perhaps this be included in future updates for the nexus 5. I doubt u
really ness with it anymore aince its an old phone but it would be nice. it
would add a lot of functionality to the nexus that otherwise id have to
carry other tools and attach them to phone

**Comment by vay3t** [comment]
u cant sniffing with bettercap if u not connected in access point. because bettercap spoofing the arp and icmp protocol. the gsm 3g and lte dont have that protocol. if u need sniffing the mobile signal u need build a fake BTS with bladerf: https://www.evilsocket.net/2016/03/31/how-to-build-your-own-rogue-gsm-bts-for-fun-and-profit/

**Comment by akrolla** [comment]
I tried it on my wifi still got errors

**Comment by akrolla** [comment]
Ima try that rogue bts that's pretty neat I have the android imsi catcher
apk I think that's be cool to set up some rogue bts see if that app is
actually effective at picking them up.

**Comment by akrolla** [comment]
Could Not detect gateway address to the AP is the error I get trying to sniff

**Comment by akrolla** [comment]
_          _   _
| |__   ___| |_| |_ ___ _ __ ___ __ _ _ __
| '_ \ / _ \ __| __/ _ \ '__/ __/ _` | '_ \
| |_) |  __/ |_| ||  __/ | | (_| (_| | |_) |
|_.__/ \___|\__|\__\___|_|  \___\__,_| .__/
                             

[E] Could not detect the gateway address for interface -X, make sure you've specified the correct network interface to use and to have the correct network configuration, this could also happen if bettercap is launched from a virtual environment.
[I] Found NetBIOS name 'HPF7F87E' for address 192.168.1.69
root@kali:~#

**Comment by akrolla** [comment]
I run bettercap -I wlan0 -g [gateway address]
and I get xouldnt determin router mac error
 that's the arguments to set interface and dictate gateway address to it

**Comment by akrolla** [comment]
I resolved it thanks guys you have to run bettercap -I wlan0 -G [gateway address] I had a typo inn my gateway you can find that by running netstat -r -n 

But as for default gate way of router for the mac addreas error I got it from csploit how can I find it in. Terminal? Or else it kept spitting the cannot fins router mac address error?

Closed #593

**Comment by vay3t** [comment]
bettercap -I wlan0 -G <gateway>

it is a issue already reported. you'll have to contrive to find the mac gateway manually. apparently the problem is bettercap and not nethunter.https://github.com/evilsocket/bettercap

**Comment by akrolla** [comment]
Yea I documented how i found it before I closed. You cannot find the
routers gateway using NH I had to use csploit to find it which is
maintained by the bettercap team.

**Comment by akrolla** [comment]
It must not be showing up in the emails, I posted the solution on the
GitHub app so it doesn't show in the emails for some reason.

**Comment by akrolla** [comment]
Thank you for looking into it also tho . Thats why I love thiS community!
I don't know a lot but I learn a lot just by reading The code and learning
from other people's issues. I haven't been doing this too long i have an
electrical engineering background and decided to go and get my computer
science degree which im working towards. and I want to start on the OSCP in
the next few months so im trying to soak up as much as possible. But I'm
still pretty new but thanks to all you guys I'm learning alot more
everyday. So thanks to @binkybear @jcadduono @bkr32 and @vay3t . so thank
you guys ! Hopefully one day I can contribute to the code !

**Comment by BeNeDeLuX** [comment]
rmnet0 has no mac-addres. That´s the problem if you want to arp spoof with bettercap.
In that case add "--no-spoofing --no-discovery" and as @vay3t said - you NEED to add the Gateway on your own with the -"G" argument. Use the "route" command inside kali to get your current gateway. so you can write a small script with an $IP variable for "-G"

Bettercap 1.5.8 works so far for me.
Hope that helps ;)

**Comment by akrolla** [comment]
Route gaveme the devicesgateway addressi hadto use csploit which is
maintaoned by bettercap to getthe router gateway

**Comment by BeNeDeLuX** [comment]
Or try it inside a ANDROIDSU Shell with
`getprop net.rmnet0.gw`

However - you know how to get your correct gateway ;) 
Is the main problem with bettercap fixed for you ? Or is there still an error ?

**Comment by akrolla** [comment]
I haven't tried in android su , I closedthis issuein the github app ... are
you guys not seeing it? I get notifications via email but it seems what I
post in the app is not seen by everybody or something. For instance in this
thread wheniget the email that you have posted to it, it isn't showing my
solution and the closure of the issue unless I open the app.. or go onto
github.com via browser

On Sep 26, 2016 2:15 PM, "BeNeDeLuX" <notifications@github.com> wrote:

Or try it inside a ANDROIDSU Shell with
getprop net.rmnet0.gw

However - you know how to get your correct gateway ;)
Is the main problem with bettercap fixed for you ? Or is there still an
error ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/593#issuecomment-249668496>,
or mute the thread

**Comment by akrolla** [comment]
I digress i figured it out and closed it but thank u because I wanted to
figure out howto do it all in terminal and not rely on csploit for a
littlepiece of info like that
When iget home I will try the command in android su.
