### ISSUE TITLE
nethunter installer for nexus 6p

### ISSUE THREAD

**Issue by anewbee** [offensive-security/kali-nethunter#594]
### Device:

nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

marshmallow

## Issue:
I can't find the download link for nethunter ROM for nexus 6p(only for nexus 6)
Can anyone send a download link for me?

**Comment by MatthewHKnight** [comment]
You have to build it yourself for angler that's why I'm gonna release a video trying to explain how to build a custom nethunter but right now I'm trying to find out a few things.
But you're gonna need to build your own nethunter.
