### ISSUE TITLE
Internal WIFI doesn't work on Oneplus3

### ISSUE THREAD

**Issue by ya0guang** [offensive-security/kali-nethunter#596]
### Device:

Oneplus3
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

OxygeOS 3.2.6
### Built from repo (date and build command) or downloaded from website (links):

Build zip file by myself on 26, Sep.
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

adb shell doesn't work. 
## Issue:

The internal WIFI doesn't work.
I tried this NetHunter3.10 OP3 kernal
https://idlekernel.com/nethunter/nightly/3.1.0-20160831-1936/kernel-nethunter-oneplus3-marshmallow-3.1.0-20160831-1936.zip
it worked well with WiFi but adb found no device.

Then I build NH by building process in Wiki using
./build.py -d oneplus3 -m -fs full
and Install ZIP via TWRP 3.0.2-1 on OOS3.2.6
Then when I firest boot it rebooted after several seconds. And then when I come into NH, I found it couldn't open wlan.

Could you please tell me how to fix it? Or if I want to fix it by myself, what should I learn? Thanks a lot!!!

**Comment by binkybear** [comment]
This appears to be an issue with OOS 3.2.6.  Most likely because the kernel sources haven't been released yet for this update (so I've read).  When it's updated I will push out another kernel to test.

**Comment by ya0guang** [comment]
@binkybear Thanks a lot! So which version of OOS is available for NH? I'll do my test after you release a new version for NH!

**Comment by binkybear** [comment]
An update for OnePlus3 users.  There was changes to the latest OnePlus3 for OOS that requires a wifi module to built now.  However, the module seems to be interfering with bringing up external wireless devices, maybe similar to the OnePlus1.

**Comment by ozsteyr** [comment]
How are things progressing on the internal wifi not working issue?
I updated without researching first and now have no internal or external wifi on OOS 3.2.7

**Comment by binkybear** [comment]
Should be okay now that ramdisk is included.  If you build from repo it should work.

**Comment by ozsteyr** [comment]
So start fresh and use from repo only? Also I hate to ask but i dont have much free space on my phone, would it be possible to download the files?

**Comment by ozsteyr** [comment]
I updated from 3.2.4 to 3.2.7 then installed from idlekernel and lost all wifi. So i then decided to restore from recent backup and now the phone is stuck on the oneplus logo.

**Comment by binkybear** [comment]
Yes as long as you have git and python you can build a zip pretty easily.  Just have to run bootstrap.sh to get kernel then:
```bash
python build.py -d oneplus3 -m
```

**Comment by ozsteyr** [comment]
So i managed to build from the repo with kali live usb. I did install git and pythin on win 8.1 but couldnt get ./bootstrap.sh working. i know nothing is this area. So i just want to make sure that by flashing the kernel from the repo that the issue of no internal wifi should be fine, cause the kernel is what caused the issue before. I had flashed both the nh app and the rootfs full first and wifi was working then after flashing the kernel it broke. Where i live my download speed is around 200 kbs and has taken me all day to clone NH repo and have had lots of troubles using my twrp backups. i just dont want to start over if possible.

**Comment by ozsteyr** [comment]
Flashed kernel from repo and no wifi.

**Comment by jcadduono** [comment]
try moving wlan.ko from ramdisk-patch/sbin to modules in kernel zip and flash zip and see what happens i guess

**Comment by ozsteyr** [comment]
There doesnt seem to be a modules folder or file in the zip. Should i create one? Would taking wlan.ko from the zip and just copy it to the directory manually after zipping work?

**Comment by jcadduono** [comment]
You can create the modules folder in the zip or in the device folder before creating the zip

**Comment by ozsteyr** [comment]
I unzipped, created folder with wlan.ko, zipped and flashed. Wifi is working fine. Thankyou both for the assistance.

**Comment by ozsteyr** [comment]
But now GPS has stopped. Icon in settings responds unlike with the wifi issue.

**Comment by ozsteyr** [comment]
GPS was a permission issue. It took multiple reboots for it to ask. All good now.
