### ISSUE TITLE
Armitage does not work. Throws floating point exception.

### ISSUE THREAD

**Issue by ultron0** [offensive-security/kali-nethunter#600]
### Device:
OnePlus 2

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Latest CM 13 Marshmallow nightly build for OP2(cm-13.0-20160924)

### Built from repo (date and build command) or downloaded from website (links):
Built from repo today(26th September)

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.84-perf+ (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Tue Jun 14 19:32:04 CDT 2016

## Issue:
Armitage does not work on the latest chroot. I have fully updated its packages. When I try to open Armitage from the console, the only output is "Floating point exception" and nothing else. I guess it is some kind of a package bug, but I was not sure whether to submit a bug report here or on the Kali Linux bug tracker. I hope that I am not the only one who can reproduce this bug, so that this issue can easily be resolved.

**Comment by bkr32** [comment]
armitage should ideally not work at all, its based on java and has its own GUI which dont import or use any native android UI elements

**Comment by ultron0** [comment]
It does not work within the chroot desktop environment, which we access via the nethunter VNC viewer. It was working some time ago. I don't know what really happened. I don't think the cause for this error is the GUI. If a floating point exception occurs, it is most definitely a serious crash in the code execution. Maybe I need to write a bug report on the Kali Linux bug tracker. It could be a bug in all ARM-based Kali Rolling builds, but I don't have anything else to test with, other than my phone.

**Comment by bkr32** [comment]
Can you please list the steps you used to install it, I can try it out

**Comment by ultron0** [comment]
I believe Armitage is preinstalled with the latest full chroot, which can be downloaded with the Kali Chroot Manager in the Nethunter android app (I believe it is included in the kali-linux-nethunter metapackage). If not included, then doing apt-get install armitage should do the same. I then open a VNC session with the chroot desktop, and from a XFCE terminal I open Armitage, but the only error output is "Floating point exception". Starting it from the kali menu in XFCE does nothing at all, so it might be quite hard to track the origin of this issue. Fully upgrading the chroot packages seems to not fix a thing. I usually upgrade my packages with apt-get clean && rm -rf /var/lib/apt/lists/ && apt-get update && apt-get dist-upgrade.

**Comment by bkr32** [comment]
Tried it and get the same error, so it should be something in previous chroot updates that broke it, I'd check previous java updates

**Comment by ultron0** [comment]
I found a workaround. Removing -XX:+UseParallelGC from /usr/share/armitage/armitage seems to fix the problem. So it looks like a java bug, rather than anything else.

**Comment by fanntom** [comment]
Same problem. I did try removing -XX:UseParallelGC but I still get the floating point exception.
I tried clean installing on my Nexus 6 Marshmellow 6.0.1 as well as my Nexus 4 but still same results came put.

**Comment by ultron0** [comment]
Sorry, @fanntom . My bad XD. I meant remove -XX:AgressiveHeap . -XX:UseParallelGC should be left there, as it does not affect this issue. I've edited my original post, so that someone else does not get confused.

**Comment by fanntom** [comment]
@ultron0 no prob :)
