### ISSUE TITLE
Installing NetHunter on Nexus 10 - error opening...

### ISSUE THREAD

**Issue by JayKey** [offensive-security/kali-nethunter#601]
Hi, I'm trying to install NetHunter on my Nexus10. I'm using Linux Root Toolkit to install it, but I also tried installing manually from TWRP. Every time I get errors below during my install, and after the reboot Nethunter isnt installed (not properly at least). I have some new apps with stock android icons. One is androidVNC other are com.offsec.n... (two of them), when I try to use them they only get me prompt "Unfortunately, androidVNC has stopped" or with the other two "Nethunter has stopped" . I also tried installing Nethunter on the top of other Nethunter, but with no effect, even the wallpaper isn't changing. I'm using most up to date ROM image (5.1.1), Netunter 3.0, TWRP 3.0.2.0, SuperSU 2.67

Updating partition details...
E:error opening /data/local/nhsystem/kali-armhf/dev/ram12
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram14
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram16
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram10
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram13
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram15
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/loop6
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram4
E:error: Not a directory
...

**Comment by Holmeren99** [comment]
Unless you have found a solution [here](http://www.idevelopcode.com/kali-linux-nethunter-for-google-nexus-10-from-ubuntu-14-04/) I haven't tried this yet, but it seems promising.
And if you already have found a solution please be so kind to share it
