### ISSUE TITLE
Commands Ignoring Linux Routing Tables

### ISSUE THREAD

**Issue by Physicist1616** [offensive-security/kali-nethunter#602]
### Device:

Nexus 5x Bullhead
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat (I know, not officially working yet, but this doesn't seem to my newbly eyes like something this version switch would break; it seems more like it's caused by Android's handling of Wifi and Data hand-offs superseding the Linux routing table.)

I discovered this by getting no results from nmap; it turns out _I had Syn scanned a private range through my data connection_.  I'm guessing my provider isn't too happy with me, but really, the routes look fine, so I can't figure out why it didn't work.
### Built from repo (date and build command) or downloaded from website (links):

Originally downloaded from OffSec git Sep 2nd(-ish), built with `-f` flag on the 22nd(-ish).
`./build.py -f -n -d bullhead -fs full`
NetHunter-LRT for installation
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016
## Issue:

The Kali and Android terminals aren't using the right route for the network.  Connected to LTE and a WAP that has no WAN connection simultaneously, I cannot ping or scan into the network despite having an IP and a route; the packets go to rmnet_data0 device instead of wlan0.

The results are the same whether I am in the chroot, androidsu, vnc'd to the kali desktop, or using Jack Palevich's terminal emulator from the Play store.

Specifying `-I wlan0` on the ping command works correctly, but I'm pretty sure most commands and tools don't have such an interface flag, relying instead on the routing table.  Why would the routing table not work here, and can I make it work?  Is there some preferred method for retaining a working data connection while on wifi? (I noticed cSploit doesn't like this scenario either).

![screenshot_20160926-145122](https://cloud.githubusercontent.com/assets/6197004/18856997/e065ae62-83fb-11e6-8068-52a5486b35c0.png)

**Comment by binkybear** [comment]
What I think you are asking about is routing in Android, which is something that got a lot more complicated in Lollipop.  Here is the technical file:

http://androidxref.com/5.0.0_r2/xref/system/netd/server/RouteController.cpp

The routing tables were created to manage network switch better but has made it a lot more difficult to specify when you want to use one interface over another.  While I can't give you the definite answer to your problem, here is a script we use for tethering wifi to give you an idea:

https://github.com/offensive-security/nethunter-utils/blob/master/usr/share/mana-toolkit/run-mana/start-nat-simple-lollipop.sh#L26

It's also possible to set a certain device to have a higher routing table by making it the first routing table.  I think this might be what you are asking for (giving a higher precedence to a routing table)?

**Comment by Physicist1616** [comment]
That's useful, but it shows me that Linux isn't driving here at all, and it only updates itself to reflect what Android is doing.  It seems, then, that adjusting routes by using the Linux command `ip route add` will make no difference to what my device will actually do.  (Right?)

My use case is this:  The targeted wifi network does not have a gateway **or** I don't want to use it because of a firewall, NMS, or no port forwarding.

Typically, my wifi connection would bounce in this case, but I managed to make it stay up by turning the gateway and dns fields to 0.0.0.0.  Subsequently, setting `ip route default dev rmnet_data0` still causes `ping 8.8.8.8` to return unreachable.

How can I tell my device to use the default route for internet stuff or ssh/vnc servers and the closed wifi for any interaction with private address space if `ip route add` doesn't work?  I see you're using it in that script you linked; is the `scope link table $table` portion actually important to setting the route, or am I doing something else wrong, or is this just a nougat bug?

**Comment by mathitam** [comment]
looks like Android does not add the main route table to its filesystem..

ref : **https://superuser.com/questions/701956/android-devices-dont-know-route-to-a-host-located-in-the-same-network**

It helped me fix this issue
