### ISSUE TITLE
rc.local autorun

### ISSUE THREAD

**Issue by Neto** [offensive-security/kali-nethunter#603]
Nexus 6
Marshmallow
Linux version 3.10.40-g819dcd6 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Sep 23 23:12:26 UTC 2016

Is it possible to run rc.local or other autorun script after booting nexus 6 on nethunter?

**Comment by binkybear** [comment]
Under custom commands in Nethunter and you can add your own script.  Just check off the run at boot.

Systemd is not compatible with chroot so we use android service to launch commands at start.
