### ISSUE TITLE
Nethunter Terminal Could not find: /system/bin/bootkail_login

### ISSUE THREAD

**Issue by Zahkc** [offensive-security/kali-nethunter#604]
**Device:** Bullhead (nexus 5)
**OS version:** Nougat
**Built from:** Github
**Output of `cat /proc/version`:** Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 smP PREEMPT Wed Aug 24 20:47:30 CDT 2016
**Issue:**
Pretty simple i think but whenn i open NH terminal i get the error 
Could not find:
/system/bin/bootkali_login:
Please run Nethunter Application to
generate!

When I run bootkali or bootkali_login in the android su terminal everything loads fine, it is just the terminal shortcut that isn't working. I'm certain that bootkail_login is in /system/bin/

**Temp fix for others with issue:**
open androidsu terminal instead
`bootkail`
followed by
`resize`

**Comment by binkybear** [comment]
Are you running latest nethunter app from this repo?  It will generate those files if they are missing.  

Also, you can do a ls -la /system/bin/bootkali* to determine if they are indeed there.

**Comment by Zahkc** [comment]
Newest version of app, downloaded it today.

bullhead:/ # ls -ls /system/bin/bootkali*
0 lrwxrwxrwx 1 root root 54 2016-09-29 09:35 /system/bin/bootkali -> /data/data/com.offsec.nethunter/files/scripts/bootkali
0 lrwxrwxrwx 1 root root 59 2016-09-29 09:35 /system/bin/bootkali_bash -> /data/data/com.offsec.nethunter/files/scripts/bootkali_bash 0 lrwxrwxrwx 1 root root 59 2016-09-29 09:35 /system/bin/bootkali_init -> /data/data/com.offsec.nethunter/files/scripts/bootkali_init 8 lrwxrwxrwx 1 root root 60 2016-09-29 09:35 /system/bin/bootkali_login -> /data/data/com.offsec.nethunter/files/scripts/bootkali_login

Definatly there

**Comment by binkybear** [comment]
Thank you, I'll check code and look into this.

**Comment by binkybear** [comment]
Created new apk with changes in above commit.  Please test before I upload to main repo:

https://transfer.sh/10GjJL/term-release.apk

I hardcoded path to check since we only check for one file.

**Comment by majackov** [comment]
Thank you, it works!

**Comment by Zahkc** [comment]
Didn't fix for me. Soz man

**Comment by binkybear** [comment]
@Zahkc - I need a little more details on why it didn't work for you.  You installed new apk and get same error? 

The commit above checks the symlink to see if it leads back to /data/data/com.offsec.nethunter/files/scripts/bootkali_login.  If that's the case you are probably missing bootkali_login or the symlink and need to run the nethunter-app to generate.

**Comment by OctAg0nO** [comment]
Same problem here

Installing on Nexus 6 Shamu Nougat, Nethunter 3.0 ( Custom Build - Latest Release )

Could not find:
/system/bin/bootkali_login
Please run Nethunter Application to generate!


root@kali:~# ls -la /system/bin/bootkali*
lrwxrwxrwx. 1 root root 54 Oct  4 18:45 /system/bin/bootkali -> /data/data/com.offsec.nethunter/files/scripts/bootkali
lrwxrwxrwx. 1 root root 59 Oct  4 18:45 /system/bin/bootkali_bash -> /data/data/com.offsec.nethunter/files/scripts/bootkali_bash
lrwxrwxrwx. 1 root root 59 Oct  4 18:45 /system/bin/bootkali_init -> /data/data/com.offsec.nethunter/files/scripts/bootkali_init
lrwxrwxrwx. 1 root root 60 Oct  4 18:45 /system/bin/bootkali_login -> /data/data/com.offsec.nethunter/files/scripts/bootkali_login

**Comment by binkybear** [comment]
@OctAg0nO - Can you verify that you are using terminal APK from this thread?  Could you also give me a logcat when you run the terminal (any errors)?

**Comment by OctAg0nO** [comment]
Yes, im using the APK from this thread, i found the application works when i run a custom commands from the nethunter app, but, if i try to open other terminal it close..

in logcat i get this error:

E/InputDispatcher(924): channel '73e059a com.offsec.nhterm/com.offsec.nhterm.Term (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by Fuse8499** [comment]
Make sure you uninstall the original Nethunter terminal that was install when you flashed Nethunter. THEN flash the apk. It won't work otherwise. The apk will reinstall the modified version of the terminal. Hope this helps.

**Comment by isclayton** [comment]
Launching term from outside nethunter app still produces the issue. I did the following: 

uninstall old nh term> install apk posted above> reboot > let nethunter boot finish. 

Running commands from NH works as expected, androidSU bootkali workaround also works. Launching from Android launcher does not. 

Nexus5x NBD90W

**Comment by binkybear** [comment]
I still think its related to signature keys.  Can you uninstall old apps using this method:
```
su
pm uninstall com.offsec.nethunter
pm uninstall com.offsec.nhterm
```
Then install ones from this repo:
https://github.com/offensive-security/kali-nethunter/raw/master/nethunter-installer/update/data/app/Term-nh.apk
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/nethunter.apk

They are the mostly updated and check for Su before looking for files.

**Comment by Zahkc** [comment]
Did what you asked but the KALI shortcut still isnt working. Using command bootkali in ANDROIDSU still works thou. I even added it as a system app but no luck.

**Comment by binkybear** [comment]
@Zahkc - I'm going to go under the assumption this is a Nougat issue since I've only tested on Marshmallow and @OctAg0nO is having same issue on Nougat.  I'll flash Nougat on a device soon and test on that.  Thanks for the quick feedback.

**Comment by binkybear** [comment]
Could users on Android N and anyone else having issues try latest:
https://transfer.sh/uupSV/term-release.apk

Includes:
https://github.com/binkybear/Android-Terminal-Emulator/commit/477a9e907379221e253849184ab65b81f718d185
https://github.com/binkybear/Android-Terminal-Emulator/commit/914551b4e7b42625261ce57d944c0c6aec5835f6

**Comment by Zahkc** [comment]
Still no good man. soz

**Comment by binkybear** [comment]
Alright slight tweak:
https://transfer.sh/uupSV/term-release.apk

Can you also run a logcat when you start app with adb?  There should be a msg about SYMLINK real file path.

**Comment by Zahkc** [comment]
Still not working. Attached is a 'logcat' of system boot and opening app and a 'logcat | grep symlink' doing same.
[logcat.txt](https://github.com/offensive-security/kali-nethunter/files/518685/logcat.txt)
[logcatgrepsymlink.txt](https://github.com/offensive-security/kali-nethunter/files/518684/logcatgrepsymlink.txt)

**Comment by binkybear** [comment]
Changes marked above.  Thank you for the logcat, it helped out.  Hopefully this fixes issue.

Here is new APK: https://transfer.sh/13WZF7/term-release.apk

**Comment by Zahkc** [comment]
New Error at least.
`Could not find:
/data/local/nhsystem/kali-armhf:
Missing chroot. You need to install from
Chroot Manager`
[logcat.txt](https://github.com/offensive-security/kali-nethunter/files/520424/logcat.txt)
[Logcat Symlink.txt](https://github.com/offensive-security/kali-nethunter/files/520425/Logcat.Symlink.txt)

**Comment by binkybear** [comment]
Added fix: https://github.com/binkybear/Android-Terminal-Emulator/commit/37d093582738cef6395a7222508ef4bcc05f613b

Here is latest.  I think this should do it now: https://transfer.sh/vLUkM/term-release.apk

So a quick run down on the problem.  For whatever reason Nougat? isn't seeing the folders unless we run the command as "su."  This doesn't seem to be an issue on Marshmallow.

**Comment by Zahkc** [comment]
Works a charm mate, cheers!

**Comment by OctAg0nO** [comment]
working !!!
:)

**Comment by isclayton** [comment]
Works. Thanks for the efforts!

**Comment by C4rl0r0ss1** [comment]
Hi, can you please fix the apk link https://transfer.sh/vLUkM/term-release.apk.
Thanks
Best regards

**Comment by jmingov** [comment]
Hi C4rl0r0ss1 , you can download the same file from the nethunter repo, we always update the apps after fixing a bug.

You can download the apk here:

https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/Term-nh.apk

(This is a closed issue from 4 months ago, if after trying the apk, you still have problems, open a new issue plz.)

Br

J

**Comment by C4rl0r0ss1** [comment]
Thank you for the fast reply, but i still have the same problem...I'll try to open a new issue.

**Comment by leandrosoares6** [comment]
I was able to solve it like this:
1 - Delete the "kali-armhf" directory located in "/data /local/nhsystem" and open the app "nethunter -> Kali Chroot Manager -> install chroot", I discovered that the app looks for the file "kalifs-full.tar.xz "in sdcard;
2 - In the nethunter installation zip I extracted the file "kalifs-armhf-full.tar.xz" and renamed "kalifs-full.tar.xz" inside the sdcard;
3 - I entered the terminal that comes preinstalled in my ROM and uninstalled the nethunter and nhTerm app with "su pm uninstall com.offsec.nethunter" and "su pm uninstall com.offsec.nhterm";
And finally, still in the terminal of my ROM I went in the apk's directory of nethunter and nhterm and gave "su pm install ..." in both apk's.
I finally opened the nethunter and granted all permissions and root access ...
Kind of complicated but it worked for me :)
