### ISSUE TITLE
Nexus 5X - Nougat, missing NetHunter.Apk

### ISSUE THREAD

**Issue by TAz00** [offensive-security/kali-nethunter#605]
### Device:
Nexus 5X - 32GB

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.0.0 (NRD90S) - bullhead-nrd90s-factory-d6bf1f56.zip

### Built from repo (date and build command) or downloaded from website (links):
https://idlekernel.com/nethunter/nightly/3.15.2-20160928-1441/kernel-nethunter-bullhead-nougat-3.15.2-20160928-1441.zip
https://idlekernel.com/nethunter/nightly/3.15.2-20160928-1441/nethunter-generic-arm64-kalifs-full-rolling-3.15.2-20160928-1441.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Only have access to normal Terminal Emulator at the moment
~~bullhead:/ $ cat /proc/version
Linux version 3.10.73-g9d3a4ad (android-build@wpiw9.hot.corp.google.com) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Tue Aug 9 18:08:52 UTC 2016
bullhead:/ $~~

Flashed Kernel again standalone, no force reboot, wiped dalvik
bullhead:/ $ cat /proc/version
Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016
bullhead:/ $

## Issue:
There is no NetHunter App in my apps list, trying to reinstall NetHunter.Apk from github gives me an error saying its already installed. But the only nethunter app visible is the VNC app.

## Possible related info:
Reset to factory with Nexus Root Toolkit
Rooted
Flashed both nethunter zips with TWRP (kernel first, but no reboot inbetween)
BusyBox is version v1.24.2-Stericson after flash

**Comment by binkybear** [comment]
This is probably related to the application being signed now.  Solution would be to run from computer:
```
adb uninstall com.offsec.nethunter
```
Or if you want to run on android itself from androidsu terminal:
```
su -c pm uninstall com.offsec.nethunter
```
Then reinstall apk.

Related to: https://github.com/offensive-security/kali-nethunter/issues/574

**Comment by TAz00** [comment]
Thanks, that coupled with

`adb uninstall com.offsec.nhterm`

And reinstalling both did the trick.
