### ISSUE TITLE
Nexus 7 build.py troubles

### ISSUE THREAD

**Issue by pindonga1234** [offensive-security/kali-nethunter#606]
## Issue:I have the next issue, I dont know my device name when i put

python build.py --device grouper --lollipop
Error: Device grouper not found in devices/devices.cfg
after I put
python build.py --device grouper tilapia --lollipop
build.py: error: unrecognized arguments: tilapia

How is the correct devices name for my Nexus 7 version 2012?

**Comment by MelrondMcBong** [comment]
grouper is correct but they dropped support for it, you can use the 3.0 release instead
