### ISSUE TITLE
Nexus 9 apt-get update 404 errors

### ISSUE THREAD

**Issue by ChrisCooney** [offensive-security/kali-nethunter#607]
### Device:

Nexus 9
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Lollipop
### Built from repo (date and build command) or downloaded from website (links):

Downloaded from Kali website - https://www.offensive-security.com/kali-linux-nethunter-download/ 

Nexus 9 lollipop image downloaded. Installed using the nethunter LRT yesterday.
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.40-g108581f-dirty (root@kali) (gcc version 4.9 20140514 (prerelease) (GCC) ) #1 SMP PREEMPT Tue Aug 11 12:19:33 UTC 2015
## Issue:

Attempting to plug in [Alpha Wireless Card](https://www.alfa.com.tw/products_show.php?pc=34&ps=92) into Nexus 9 via OTG cable. Nothing is registered.

Output of dmesg indicates it was unable to obtain the htc_1971.fw drivers. It detects that it is an Atheros wireless card, but doesn't load up.

I attempted to run apt-get update && apt-get install firmware-atheros, however I get 404 errors:

```
W: Failed to fetch http://security.kali.org/dists/sana/updates/main/binary-armhf/Packages  404 Not Found

W: Failed to fetch http://security.kali.org/dists/sana/updates/contrib/binary-armhf/Packages  404 Not Found

W: Failed to fetch http://security.kali.org/dists/sana/updates/non-free/binary-armhf/Packages  404 Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I've found some promising solutions, but to get ahold of the I first need to update and install the atheros firmware! Such is life.

I've seen some similar problems but none with this exact combination. Do you think I should move to Marshmellow instead?

**Comment by binkybear** [comment]
Well theres two issues occurring here.  One is the missing firmware and the other is that our old official release is still using sana.

Adding firmware-atheros will not fix.  In android the firmware exists in /system/etc/firmware and needs to be placed there manually.

The 404 is because of sana.  Expect an official update hopefully this weekend.  Otherwise, you can upgrade chroot from app.  Fixing the firmware issue is a bit more work.

**Comment by lcfut** [comment]
I also have a Nexus 9 Running NetHunter 3.0 on 6.0.1 and receive similar 404 errors.
I noticed my sources.list file had an incorrect entry and changed it accordingly, but its still using sana as mentioned above.
When I am in NetHunter and choose to Check App Update, I can pull 'latest.apk' but it fails to install.  I also get 404 errors when in chroot manager and attempt to add metapackages.

Thoughts?

**Comment by GabrielTK** [comment]
Getting lots of 404 too. Any updates?

**Comment by jcadduono** [comment]
use build.nethunter.com builds until new release
