### ISSUE TITLE
We need to make a new official release

### ISSUE THREAD

**Issue by jcadduono** [offensive-security/kali-nethunter#608]
### Device:

All of them
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Seeya KitKat
## Issue:

We're getting increasingly more and more duplicate tickets related to the v3.0 release and especially the deprecation of the Sana repos. It's often hard to separate these issues when people leave out versioning information.

We may not have fixed all the bugs so far that we'd have hoped to, and while it is nice to make a completely stable release, we are in much more of a stable state than the actual 3.0 release.

I think it would be advantageous the the project & development to push out an official release as soon as possible

 It would really help to keep the open issues down and maintainable and give us good issue reports on bugs that are actually current so that we can solve them sooner.

To add to that, I'm nearing my 10 TB per month bandwidth limit per month due to hosting the prebuilt git-current zips on my server. :P It'd be nice to throw that load onto the offensive security servers instead.

I've opened this issue in a publicly replyable area since this is a community powered project, and it would be nice to get everyone's input on this, even if they're not actively submitting/developing patches/commits.
## Things we need to discuss before a new release can happen
- Version scheme - Should we move to the Kali versioning format of rolling (_2016.10_ for example)
  I think the rolling version format is a good choice, but it might not work in our favor when it comes to individual app updates. For those however, single revision numbers could work? (similar to how LZ4/ZSTD versioning works), ex. _r316_  
  @binkybear your choice to go from 3.1.0 to 3.15 was the weirdest thing, lol  
  If we are sticking with the current incrementing version number, should we next have say...  
  3.27? I like the number 27
- Which devices are ready for or deserve a stable release?
- Should we drop grouper (k3.1)? Do we know if the new 3.4 kernel is actually working?
- What major issues do we have that _must_ be solved?
- Is anyone else not so secretly in love with Maisie Williams? (I need to add more items to this list)

**Comment by binkybear** [comment]
@jcadduono - We can talk about throwing the files on offsec servers privately in chat.

* Version Scheme - Dates is probably a good idea to keep track of.  I still think major releases should have a version number associated with it...ideally I should be updating the version # every time I push an update. 
* I'll have to get back to you on whats "stable."  Most of the marshmallow builds are stable.
* Grouper should be dropped for two reasons: 1) You can't actually run installer in TWRP (says "low memory) 2) 3.4 kernel doesn't actually work...and when it does the display is all screwed up.
* Major issues we are current experiencing are the switch to the signed apps and a few users reporting HID isn't working.
* Hodor

**Comment by jcadduono** [comment]
I'll see if I can take a look in the pm app source to see how uninstall works and see if I can replicate it in the installer to make the switch of signatures go smoother.

I can also take a peek at gadget drivers and see what's up if you want to point me to the kernels with reported hid issues

**Comment by binkybear** [comment]
The HID issues are within the app.  I haven't run into it myself, HID button still works in app for me.  Others said there were issues but I have a feeling it was a change in permission due to app signing.

**Comment by jmingov** [comment]
+1 for dropping Grouper support.

**Comment by jmingov** [comment]
Let try to split all this into issues and adding them to the "3.27" Milestone will help a lot with the progress tracking.

**Comment by akrolla** [comment]
I got the 3.4 grouper kernel that I posted in my issue and ita been stable sincce install I had one bug report captured.. .. on another not do you have a link to the nethunter apk

**Comment by akrolla** [comment]
I haven't placed nethunter on it yet I wanted to see how stable the kernel itself is
