### ISSUE TITLE
Nethunter not working on OnePlus 2 OOS 3.

### ISSUE THREAD

**Issue by 1nt3rnal3rr0r** [offensive-security/kali-nethunter#609]
### Device:

OnePlus 2
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

OOS 3.1.0 Marshmallow
### Built from repo (date and build command) or downloaded from website (links):

Repo build from 1 October(today)
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.84-perf+ (jenkins@build) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Sun Jul 3 19:13:59 EDT 2016
## Issue:

The OOS nethunter build for OnePlus 2 seems to be completely broken. After flashing the zip, the system hangs on the splash screen. I don't know if the kernel is broken, because I've tried a zip file without the custom nethunter kernel and the result is still the same. I have no idea where to look for the cause of this issue.

**Comment by binkybear** [comment]
I just installed one OnePlus2 OOS and it appears to be working fine.  Are you flashing correct device?  Newest kernel appears to work.

**Comment by ultron0** [comment]
Sorry for the late reply, @binkybear . I've had a very busy week.
Today I tried flashing a build from a clean clone of the repo, and the result it still the same. My guess is that we are not using the same build of OOS. I downloaded mine from here: https://s3.amazonaws.com/oxygenos.oneplus.net/OnePlus2Oxygen_14_OTA_020_all_1608262242_44a55e674a2b4bf6.zip . This is a link from the oneplus support page and it is the most recent zip. If you want, you could try flashing this version of Oxygen OS and see for yourself.

**Comment by PurvC** [comment]
Follow this steps to build your Nethunter zip for Oneplus 2 for Oxygen OS -

Pre-requisites - Unlocked Bootloader, TWRP.

You need to flash this SuperSu modified for Oneplus 2 OxygenOS before following the below given steps - https://www.androidfilehost.com/?fid=24591000424961865

1 - git clone --depth 1 https://github.com/offensive-security/kali-nethunter
2 -  cd kali-nethunter/nethunter-installer
3 - ./bootstrap.sh ( Type N for Experimental Devices and Type N again when prompted to download full Download History)
4 - python build.py -d oneplus2 -m -nosu -fs full
5 - Flash the zip built with the script.

**Comment by jcadduono** [comment]
You can also just download the latest zips: nethunter-generic-arm64 (open it and remove supersu.zip, this is the key to fixing boot issue I think), and kernel-nethunter-oneplus2oos from https://build.nethunter.com/nightly

When using bootstrap.sh, you can just keep pressing enter as the default options when leaving it empty are to download master and minimal history.

**Comment by ultron0** [comment]
Thank you for the instructions. Installing the modified supersu did the trick. I think a possible fix for this would be for the build.py script to include the modified supersu in the oneplus2oos nethunter zip, instead of the current one. Though the code in build.py might get a bit dirty after such a change :D.
