### ISSUE TITLE
suggestion: login protocol & ssh port forward

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#610]
[>] It would be convenient to have available in the apk: choose a protocol, user and address. to connect so quickly without having to access direct the terminal.
for example: [FTP] localhost 21
the idea is to have available a list of the most common protocols such as:
ftp, ssh, sftp, telnet, netcat (?).

[>] Another suggestion is to have available fast configurations port forward with ssh from the apk.
I imagine design like the nmap module

**Comment by jmingov** [comment]
Althoght you can do this fron custon commands (or you should be able to), it can be a good addition.

**Comment by vay3t** [comment]
so it is, but edit each time becomes somewhat annoying. also could be stored connections to avoid having to write all the time ip. like ConnectBot
