### ISSUE TITLE
Drop Grouper & KitKat

### ISSUE THREAD

**Issue by jmingov** [offensive-security/kali-nethunter#611]
This is for the "v3.27" Milestone

See: https://github.com/offensive-security/kali-nethunter/issues/608

Drop Grouper: I think we all agree here.

Drop kitkat builds: ??

**Comment by jmingov** [comment]
+1 Remove kitkat builds and support.

**Comment by jmingov** [comment]
@jcadduono saw you edited the wiki a few hours ago, is grouper already removed? And kitkat?

**Comment by jcadduono** [comment]
yeah I removed grouper from the wiki, I don't remember if kitkat was even on the wiki in the first place :P

**Comment by jmingov** [comment]
hehe, atm at least we have a number/name for the milestone, saw you liked that number so why not?
