### ISSUE TITLE
Does nethutner support internal wifi?

### ISSUE THREAD

**Issue by majackov** [offensive-security/kali-nethunter#612]
### Device:
Nexus 5x
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat
## Issue:
airmon-ng start wlan0 (internal wifi)
ERROR adding monitor mode interface: command failed: Operation not supported (-95)

**Comment by jmingov** [comment]
Nop, at the moment is only viable for the nexus 5.

Take a look here: https://github.com/offensive-security/kali-nethunter/issues/567
