### ISSUE TITLE
jfltexx - no sound after kernel update

### ISSUE THREAD

**Issue by marcusguita** [offensive-security/kali-nethunter#614]
### Device:

Galaxy S4 (Intl) jfltexx
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

cm-13.0-20160820-SNAPSHOT-ZNH5YAO0J3-jfltexx
### Built from repo (date and build command) or downloaded from website (links):

https://idlekernel.com/nethunter/nightly/3.15.2-20161002-0200/
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.107-nethunter-jfltexx-g5a41f24-dirty (semsevens@Dark) (gcc version 4.9.4 20150629 (prerelease) (crosstool-NG 1.20.0 - Linaro GCC 2015.06 - Cortex-A15) ) #1 SMP PREEMPT Sat Jun 4 22:05:33 CST 2016
## Issue:

No sound after update kernel: kernel-nethunter-jfltexx-marshmallow-3.15.2-20161002-0200

**Comment by DeStilleGast** [comment]
I had this problem too, and got it solved. I looked in the kernel that I downloaded and saw a file called media_profiles.xml I thougt this was this problem and I was correct.

What I did was:
- restoring to a backup I made.
- Copy the file media_profiles.xml from /system/ect to my SD card
- then apply the kernel and reboot
- once back in the system replace the media_profiles.xml from your sdcard and reboot your phone again.
- Now your music should work again.

So for I haven't encounterd any other bugs while doing this, the HID-gadget still works (the only thing i tested)

Hope I have helped you.

**Comment by marcusguita** [comment]
Hi DeStilleGast,

I did the procedures but in my case it did not work. I compared the files and the content is the same. Also compared the other files in /system/etc, but after applying the kernel, there was no change.

What is OS version you installed?

Thanks!

**Comment by DeStilleGast** [comment]
OS: Resurrection Remix Marsmallow v5.7.4 with Android 6.0.1

if you got the same or not you can try to reflash your rom (if custom) to get your sound back.
try then the steps I have mentiont

if you would like to have mine media_profiles.xml you can just ask :)

**Comment by marcusguita** [comment]
Hello, I went back a previous backup to compare the files and follow the steps mentioned. 

I will install the rom who commented and run the tests. I will return soon.

**Comment by DeStilleGast** [comment]
Oke, first off all, I am apologizing. I still don't have sound (I noticed it when my bluethooth was of and atemped to play music throu the speakers) BUT. I am able to call. you can still play/hear music throu bluethooth. And I was testing with bluethooth on :/. Yesterday when I first tested this kernel there was spam in the catlog with invalig argument (or something like that). Now I dont have this anymore. But I will also still try to get my sound back throu the phone speakers. I will accept if you angry at me with giving a bit of false hope.

**Comment by DeStilleGast** [comment]
So far I have tried, combining, installing other drivers (viper4android) nothing is working well for my. Sinds this is my only phone I have, I need my phone 24/7 I can't help finding a solution. But I hope that I helped you a bit.

**Comment by marcusguita** [comment]
Hi DeStilleGast, no problem.

I installed Resurrection OS, but, no sound after kernel update. Thanks!!

**Comment by jcadduono** [comment]
hey guys, for now, just open the zip file in like 7-zip or something and delete the "sbin" folder inside ramdisk-patch folder. it has some things that just shouldn't be installed on your device.
after removing the sbin folder from zip it should be safe to flash without losing your audio, but if you already lost it you need to restore or reflash your rom before installing the new modified zip.

**Comment by DeStilleGast** [comment]
I have quickly tested from what you said, twice to be sure but my speak still doesn't work :/

what I have done:
- Flash original rom
- Flash kernel
- Restart

**Comment by marcusguita** [comment]
I tested flashing kernel without /ramdisk-path/sbin folder, but no soud yet. :(

**Comment by jcadduono** [comment]
did you flash your original rom and have sound working before flashing the modified nethunter zip with sbin removed?

**Comment by marcusguita** [comment]
Yes jcadduono.

1. Wipe FULL
2. Install cm-13.0-20160820-SNAPSHOT-ZNH5YAO0J3-jfltexx or Resurrection Remix Marsmallow v5.7.4 with Android 6.0.1
3. [Sounds good] - Backup full
4. Install kernel-nethunter-jfltexx-marshmallow-3.15.2-20161012-0401_no_sbin.zip (without /ramdisk-path/sbin folder)
5. [ no sound ]
6. Restore backup full
7. Sounds OK

**Comment by jcadduono** [comment]
Does sound return after only restoring Boot?

**Comment by marcusguita** [comment]
no... need to restore boot and system partition.

If I restore only boot, cellphone wont start.

**Comment by jcadduono** [comment]
that doesn't make sense, are you sure you're restoring the original boot that matches the rom?

**Comment by DeStilleGast** [comment]
Currently testing, flashed the modified kernel and then restored the boot. My phone does start up

**Comment by DeStilleGast** [comment]
Sound does work, HID does not work, it tells me to flash a custom kernel

**Comment by jcadduono** [comment]
ok so it is a kernel binary issue, whoever is maintaining this device should look to fix it, you can find maintainer in kernels.txt and tag them here

**Comment by DeStilleGast** [comment]
@semsevens You should look here too, we got problems with sounds.

**Comment by krystian530** [comment]
If u want sound - flash boot.img from cm13.zip.
If u want kali tools working - restore nethunter kernel from recovery :)

**Comment by DeStilleGast** [comment]
> If u want sound - flash boot.img from cm13.zip.
If u want kali tools working - restore nethunter kernel from recovery :)

I got a cm13 rom (resurection remix) it has sound. I made backup of the boot image. I flashed the kernel and restored my boot.img back. Got sound, but no kernel support.

Are you trying to tell me if I want sound I have to restore it and if I want to use the kernel I need to reflash it. That is a horrible idea.

Still haven't heard anything of @semsevens

**Comment by semsevens** [comment]
Hey, there. Sorry for coming late.
I just rebuild the kernel and fix  it.
@jcadduono  I have sent a PR.

**Comment by DeStilleGast** [comment]
I can confirm that kernel-nethunter-jfltexx-marshmallow-3.15.3.20161126-1805.zip works with Resurection Remix latest version

**Comment by Nihal7899** [comment]
Guys anyone please help me 
I am using Kali nethunter my repository is
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
When I run apt-get install 4.9.0-kali3-amd64 it's says unable to locate package 
E: couldn't find any package glob
E: couldn't find any package regex

**Comment by shahrukhulla** [comment]
I have flash sm j530f using odin and update 8.1 oreo since update no sound in external speaker. I think its a bug in stock rom downloaded from sammobile this bug has every 8.1 oreo firmwares i have updated my bootloader so i can't downgrade 7.0 please help me.
