### ISSUE TITLE
Error connection after install fluxion tools

### ISSUE THREAD

**Issue by xdarknet** [offensive-security/kali-nethunter#618]
### Device:

Xiaomi redmi 3x using generic amr64
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marsmallow
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

root@kali:~# cat /proc/version                              Linux version 3.18.20-g76f906f (builder@c3-miui-ota-bd09) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Sep 22 18:58:53 CST 2016
## Issue:

Cannot ping. Wget or anything acces to internet using kali terminal or vnc server. This happen after me install fluxion tools. Maybe error on dhcpd or interfaces. Please helpme to resolve the problem im not want to redownload kali-chroot-full.tar.xz
After typing ping google.com in terminal give error like this
root@kali:~# ping google.com                                ping: google.com: Temporary failure in name resolution      root@kali:~#

**Comment by binkybear** [comment]
``bash
Temporary failure in name resolution
```
Your error appears to be related to DNS.  I would check your resolv.conf to make sure you actually have dns entried.  Try running:
```bash
su
ping 8.8.8.8
```

**Comment by SkyHacker143** [comment]
I have same error
Su ping 8.8.8.8 
Works fine
How to resolve this
