### ISSUE TITLE
OnePlus One CM 12.1, TP-Link WN722N not working.

### ISSUE THREAD

**Issue by jeretc** [offensive-security/kali-nethunter#619]
### Built from repo (date and build command) or downloaded from website (links): 
OnePlus One CM 12.1 
https://www.offensive-security.com/kali-linux-nethunter-download/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux Version 3.4.39-5983550 (dpi@SWHC3516) (gcc version 4.8 (GCC) #1 SMP PREEMPT Fri Oct 23 12:12:46 KST 22015

## Issue:
Hi i canot seem to get the Wireless TP-link WN722N to work. When i do "lsusb" i can see the wireless adapter listed as :  
Bus 002 Device 005: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n

when i do "iwconfig / ifconfig" device not showing. Even "ifconfig wlan1 up"  also does not help.

Any solution for this?

**Comment by binkybear** [comment]
Your title said its for the OnePlus One but your device is showing as Samsung Tab in your issue.  

I don't recognize that kernel either.  I have no idea who built that but I imagine thats probably where your problem is.

**Comment by jeretc** [comment]
Hi i downloaded the firmware from the official website.  I flashed the
firmware on my Samsung tab.  Nethunter successfully installed without
errors.  Only the wireless adapter is not working even though it is
detected in nethunter.

So i figure it could be some other issue.

Thanks.

**Comment by binkybear** [comment]
If the installer doesn't recognize the device it skips flashing the kernel.  Essentially you flashed a "generic" version. So if your device is a Samsung Tab then you need to flash a Samsung Tab kernel with firmware/devices enabled that Nethunter uses. 

I don't believe we support this device.

**Comment by jcadduono** [comment]
dpi is Samsung's official build user, there is no NetHunter for Tab S, you should not flash NetHunter for other devices on your device. Of course it's not going to work. If you wanted to get it working, you'd need to compile your own NetHunter kernel for the Tab S and you can install it with the generic 3.15.2 installer if you want.

**Comment by jeretc** [comment]
Hi,  i have flashed my rom to cynogenmod 12.1. And installed the generic
3.15.2 nethunter.

Installation was fine no errors but same issue with the wireless adapter
even though it is detected in kali.

Thanks.

**Comment by jcadduono** [comment]
once again, you cannot use adapters at all on a purely generic install, you must use a nethunter kernel as well

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
