### ISSUE TITLE
ADB and Fastboot need to be updated

### ISSUE THREAD

**Issue by photonicgeek** [offensive-security/kali-nethunter#62]
After having installed google-nexus-tools, I found out that the ADB binary is version 1.0.26, but in order to invoke the RSA authorization prompt, it requires 1.0.31. I have tried multiple times to compile the binary myself with no luck. It just needs to recompiled from source for ARM.

**Comment by thesle3p** [comment]
Just curious, but is there a time table as to when this will be done? I may learn how to package software for debian just to get this to work.......

**Comment by jmingov** [comment]
https://github.com/offensive-security/kali-nethunter/wiki#installing-brt-nrt-and-google--android-windows-drivers
