### ISSUE TITLE
NetHunter Terminal: Could not find /system/bin/bootkali_login

### ISSUE THREAD

**Issue by BruceZhang1993** [offensive-security/kali-nethunter#620]
### Device:
OnePlus 2

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat / CM14

### Built from repo (date and build command) or downloaded from website (links):
Built from repo using kernel extract from cm14 unofficial

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.84-perf+ (david@Seraph08) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Sun Oct 2 03:31:24 EDT 2016

## Issue:
NetHunter Terminal start kali failed with error: could not find bootkali_login and file permissions below

> oneplus2:/ # ls -l /system/bin/boot*
> -rwxr-xr-x 1 root shell 51472 2009-01-01 13:00 /system/bin/bootanimation
> lrwxrwxrwx 1 root root     54 2016-10-09 00:35 /system/bin/bootkali -> /data/data/com.offsec.nethunter/files/scripts/bootkali
> lrwxrwxrwx 1 root root     59 2016-10-09 00:35 /system/bin/bootkali_bash -> /data/data/com.offsec.nethunter/files/scripts/bootkali_bash
> lrwxrwxrwx 1 root root     59 2016-10-09 00:35 /system/bin/bootkali_init -> /data/data/com.offsec.nethunter/files/scripts/bootkali_init
> lrwxrwxrwx 1 root root     60 2016-10-09 00:35 /system/bin/bootkali_login -> /data/data/com.offsec.nethunter/files/scripts/bootkali_login
> -rwxr-xr-x 1 root shell 39176 2009-01-01 13:00 /system/bin/bootstat

when i start kali from android terminal:

> oneplus2:/ $ /system/bin/bootkali_login
> sush: /system/bin/bootkali_login: not found

but when i start kali from android su, everything works.

**Comment by jcadduono** [comment]
`su -c bootkali_login` or just `bootkali_login` if from # root terminal

your terminal $ means non root...regular user can't see /data/data folder, so bootkali won't exist. you need to be root.

**Comment by BruceZhang1993** [comment]
I just wonder why nethunter terminal cannot start kali, I can manually enter kali chroot.

**Comment by binkybear** [comment]
https://github.com/offensive-security/kali-nethunter/issues/604#issuecomment-252458353

**Comment by BruceZhang1993** [comment]
@binkybear thanks i'll try this workaround.

**Comment by ChiranjeevMazumdar** [comment]
Hi, i am using termux to install kali nethunter. After installing it says you can now start Kali nethunter using ./startkali.sh but on doing so i am getting the following error...
proot error: execve("/usr/bin/env"): No such file or directory
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp//proot-1041-tKAJIk': No such file or directory
proot error: can't chdir to '': No such file or directory
Please help.
