### ISSUE TITLE
OnePlus 3 - Kernel flashing but not showing up.

### ISSUE THREAD

**Issue by shonenx333** [offensive-security/kali-nethunter#621]
### Device:
OnePlus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Oxygen 3.2.7

### Built from repo (date and build command) or downloaded from website (links):

Kernel : [here](http://build.nethunter.com/nightly/3.15.2-20161008-1854/kernel-nethunter-oneplus3-marshmallow-3.15.2-20161008-1854.zip) 
Fs: [here](http://build.nethunter.com/nightly/3.15.2-20161008-1854/nethunter-generic-armhf-kalifs-full-rolling-3.15.2-20161008-1854.zip) 

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux Version 3.18.20-perf+ (OnePlus@ubuntu-21) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) )

## Issue:

As you've already seen the nethunter kernel is not working.
I tried flashing every kernel/kali-fs in the nightly build. Kali itself works fine (except the modules which need the kernel).
I have no idea what i did wrong.

I just downloaded the zips. Got into TWRP and installed the kernel and then the kali-fs (without reboot)

Do i need to wipe the cache or sth?

**Comment by jcadduono** [comment]
recovery.log of kernel flash

`adb pull /tmp/recovery.log` in twrp after flashing

you should have provided link to the download in your issue report, please do link the exact zips you are flashing, preferably latest

**Comment by shonenx333** [comment]
I edited the issue report with the exact links. 

Recovery log : [here](https://drive.google.com/file/d/0B0YP_lttWghncl9DdkE3ZEFhYXM/view?usp=drivesdk)

**Comment by jcadduono** [comment]
Looks fine to me, definitely flashed the kernel. cat /proc/version again after that?

**Comment by shonenx333** [comment]
u0_a96@OnePlus3:/ $ cat /proc/version
Linux version 3.18.20-perf+ (OnePlus@ubuntu-21) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Sep 30 14:06:43 CST 2016

Same as before no matter which user su kali or normal

**Comment by jcadduono** [comment]
You must have flashed something else after NetHunter kernel...this doesn't make sense ...unless it's somehow replacing recovery instead of boot lol

**Comment by jcadduono** [comment]
Well that's why...when you flash full generic, SuperSU sees the already SuperSU modified kernel and restores your stock kernel ....flash kernel-nethunter last!!!

As for wifi not working ...I think wlan.ko should be in modules folder not sbin, I guess @binkybear trying to go about it without replacing system wlan.ko

**Comment by shonenx333** [comment]
Thank you :) so i might have to life without WiFi I guess :D it works now

**Comment by jcadduono** [comment]
Try as root:

find /system -name wlan.ko

then

mount -o remount,rw /system
cat /sbin/wlan.ko > (location from find command)
mount -o remount,ro /system
sync
reboot

this will replace your wlan kernel module with the one from NetHunter instead of trying to use that loader script thing

**Comment by shonenx333** [comment]
i flashed the new kernel ([here](http://build.nethunter.com/nightly/3.15.2-20161010-0317/kernel-nethunter-oneplus3-marshmallow-3.15.2-20161010-0317.zip)

cat /proc/version is:
Linux version 3.18.20-ElementalX-OP3-0.22 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) )

(does this look right?).

i tried your solution with the wifi. but /sbin/wlan.ko does not exist so cat /sbin/wlan.ko... fails.

**Comment by jcadduono** [comment]
When you cat'd to wlan.ko it made it 0 bytes when it failed...it doesn't make any sense at all for it to fail unless you're on stock kernel, because that is where it is placed by the NetHunter kernel installer.

**Comment by shonenx333** [comment]
So i might try it again later that day.
So i will flash the latest op3 kernel.
and run your commands regarding wlan. But as you've seen i was not on stock kernel and /sbin/wlan.ko does not exists... but i will try it again and report in 1 hour. 

thanks again :)

**Comment by shonenx333** [comment]
So tried it again with the newest kernel ( [this one](http://build.nethunter.com/nightly/3.15.2-20161010-0317/kernel-nethunter-oneplus3-marshmallow-3.15.2-20161010-0317.zip)
/proc/version is: Linux version 3.18.20-ElementalX-OP3-0.22 (root@nh-buildbox..) so same as before. (and if i'm right this is the nethuner kernel so no stock kernel.)

cat /sbin/wlan.ko says file not found so cat'ing that content so /system/lib/modules/wlan.ko wont work.
maybe the other way around? content of /system/lib/.../wlan.ko to /sbin/wlan.ko ?

**Comment by askasmani** [comment]
I have the same problem as wifi not working after kali install, @shonenx333. After I install the OP 3.2.7, and reboot the wifi is working fine. After I install the kernel-nethunter-oneplus3-marshmallow-3.15.2-20161010-0317.zip, wifi stops working.

**Comment by shonenx333** [comment]
@askasmani did u tried the solution @jcadduono brought up? If so does the file /sbin/wlan.ko exists on your device (when on nethunter kernel) because strangely it does not on mine, even though the kernel should have placed it there.

**Comment by askasmani** [comment]
i found the wlan.ko file, but when i run the cat command it says cat: /sbin/wlan.ko: no such file or directory.

**Comment by shonenx333** [comment]
Yep that's what I thought maybe @jcadduono can help us with that but I doubt that since the file should exist in sbin as he said...

**Comment by shonenx333** [comment]
I can say with the new [kernel](http://build.nethunter.com/nightly/3.15.2-20161012-0401/kernel-nethunter-oneplus3-marshmallow-3.15.2-20161012-0401.zip) you just have to execute the commands given by @jcadduono and wifi works :)

Thanks guys i will close here.
