### ISSUE TITLE
Wi-fi problems mac:02:00:00:00:00

### ISSUE THREAD

**Issue by andriydzy** [offensive-security/kali-nethunter#622]
### Device:

Nexus 5
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

6.0.1
## Issue:

My wi-fi isn`t working, mac address: 02:00:00:00:00, tried to change in console, but there are no wlan0, NetHunter doesn`t see wlan too. What can I do?

**Comment by lightpencil** [comment]
same problem after flashing kernel

**Comment by majackov** [comment]
same problem :(

**Comment by redwards510** [comment]
I have this problem on Oneplus3, CM 13 (10/31 nightly). No wifi, Mac set to the 02:00:00:00:00:00

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/issues/635
