### ISSUE TITLE
dictionaries-common and postgresql* fail to upgrade

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [offensive-security/kali-nethunter#623]
## Issue: dictionaries-common and postgresql* fail to upgrade as they should.

Both of these packages attempt to reach directories /data/local/tmp (outside of chroot).

### Workaround:

    mkdir /data
    ln -s / /data/local

Quick and cheap workaround, but it shouldn't need it. Is this also happening on supported devices?

**Comment by binkybear** [comment]
These packages are usually installed already in chroot.  I cannot recreate this issue.  Are you using the minimal chroot and installing the packages?

**Comment by VTCAKAVSMoACE** [comment]
It is a full chroot (downloaded through the app), but it occurred during the first update. I'm not sure if it would be worth mentioning, but it was through ssh to the Android and then using `su -c bootkali` to get into the kali chroot.

**Comment by VTCAKAVSMoACE** [comment]
I did a full wipe and used the metapackage `kali-linux-all` and `kali-nethunter` instead of just `kali-nethunter`, seems to have fixed itself. I can't replicate it again, might be a one-off thing. I'll close this for now and reopen if I have any updates.
