### ISSUE TITLE
nethunter not working on nexus 6 (android version : 7.0 Nougat)

### ISSUE THREAD

**Issue by dannyrock** [offensive-security/kali-nethunter#625]

**Comment by vay3t** [comment]
try to install from github. those on the official website are bad (aroma have problems), be sure to install the correct version compatible with android 7. @offensive-security could to update them for last versions.

**Comment by dannyrock** [comment]
Seems like nethunter is not yet released for android version 7.0 any aspected release date?

**Comment by jcadduono** [comment]
It might not even be in next official release if people don't try it out and report with success or reasons of failure and logs
build.nethunter.com

Need flash nethunter-generic-armhf-kalifs-full-rolling and kernel-nethunter-shamu-nougat zip for full install

**Comment by MatthewHKnight** [comment]
My biggest issue I'm having is I did python build.py -d shamu --nougat
came out 79.0mb I place the zip on my Nexus 6 boot into TWRP installs on my phone reboots, I install the busybox files to the right path give SuperSU permissions to the NetHunter app install chroot files when I open NetHunter Terminal click Kali it gives me a blank error and tells me something needs to be install from chroot manager but when I go to chroot it says the directory exists so not sure what is missing or whats wrong however the ZIP on the nethunter website works just fine I just don't wanna be running a vulnerable Android and getting my phone infected or hacked.

**Comment by DimaSemchuk** [comment]
I'll be very happy if @offensive-security would make it for nexus 6 nougat

**Comment by akrolla** [comment]
It takes time friend. Have patience the devs are working as hard as
possible to rectify the problem, we have a lack of testers in the platform
so that places a bottleneck on development

**Comment by DimaSemchuk** [comment]
Can I give any help with testing? Got a nexus 6 in my office for playing with stuff.
If there's any tutorial on installation...

**Comment by akrolla** [comment]
@jcadduono

**Comment by jcadduono** [comment]
not mine

**Comment by BesoBerlin** [comment]
https://github.com/offensive-security/kali-nethunter/issues/709

Should be already working when in actually builds...

For me it works well on my Nexus 6 with Nougat 7.0... with smaller known issues...
(Terminal crashes - fix with manually bootkali via an other terminal ulator, duckhunter doesn't load or save payloads - "fix" with copy paste from elsewhere, etc)

**Comment by DimaSemchuk** [comment]
ok, I'll try to install also.
If me and my team can give a hand with testing something specific - shoot me with a message

**Comment by carlosdajackal** [comment]
Downgrade to lollipop and then to nethunter

**Comment by BesoBerlin** [comment]
Well at the moment I am running Nethunter on Nexus 6 Android 7.1.1 which runs perfect, except the issue with duckhunter, which is not able to load or save a payload from storage.

**Comment by carlosdajackal** [comment]
@BesoBerlin so you just installed it on top of nougat and it worked?

**Comment by BesoBerlin** [comment]
Yes... I've built it via Nethunter Installer with build.py -d Shamu -n and then installed via Nethunter-LRT... Some issues as reported but most of the tools work like a charm...

**Comment by edwinsusta** [comment]
@BesoBerlin 
Which Android image are you using?

**Comment by ravensec** [comment]
@BesoBerlin 
Which Android image were you using with Nethunter-LRT

**Comment by BesoBerlin** [comment]
I've used 7.0 meanwhile I am using the 6P with Nethunter OS ROM, so my Nexus 6 is still running on Android 7.0 and Nethunter on top. Not shure if it works with 7.1*...
Best regards
