### ISSUE TITLE
error in build the nethunter for nexus 6p 

### ISSUE THREAD

**Issue by anewbee** [offensive-security/kali-nethunter#626]
### Device:

nexus 6p(angler)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

nougat(NBD90X release in 2016 Oct)

## Issue:
When I built the nethunter for nexus 6p, it worked well until when finished download all apps
the error is : Unable to find kernel image at: devices/nougat/angler
that means nethunter does not support nexus 6p in nougat?

**Comment by jcadduono** [comment]
https://github.com/offensive-security/nethunter-devices/tree/master/nougat

correct. someone with a 6P will have to build it and contribute it. :)
