### ISSUE TITLE
Duckhunter HID keyboard attack doesn't work, but the standard HID keyboard attack does.

### ISSUE THREAD

**Issue by AFriendlyTrashcan** [offensive-security/kali-nethunter#627]
### Device:
Nexus 6p

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from idle kernel nightly repo https://build.nethunter.com/nightly/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.94+ (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #4 SMP PREEMPT Fri Jan 8 19:14:10 UTC 2016

## Issue:

When I try to run the Duckhunter HID keyboard attack it doesn't work, if i try to run it from /opt/duckout.sh i get a bunch of errors saying "/system/xbin/hid-keyboard: Accessing a corrupted shared library". Despite this, when I try to run the standard HID keyboard attack, it works fine.

**Comment by binkybear** [comment]
Can you tell me what happens if you run /system/xbin/hid-keyboard by itself?

**Comment by jcadduono** [comment]
I'm also running into this with the arm64 hid-keyboard binary, I will rebuild them with proper android tool chain and sysv hash style tomorrow I guess

**Comment by AFriendlyTrashcan** [comment]
@binkybear it just says -bash: ./hid-keyboard: Accessing a corrupted shared library

**Comment by jcadduono** [comment]
fixed, uploading new binaries soon

**Comment by jcadduono** [comment]
should be fixed with https://github.com/offensive-security/kali-nethunter/commit/134662fce0792b942eff3ff180ffb0b08319476a

:)

**Comment by AFriendlyTrashcan** [comment]
@jcadduono <3

**Comment by AFriendlyTrashcan** [comment]
@jcadduono I just got around to flashing it, it works great, thank you.
