### ISSUE TITLE
Bad Usb Reboots Phone

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#628]
### Device:

Oneplus 3
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow  OOS 3.2.7 + 3.2.4
### Built from repo (date and build command) or downloaded from website (links):

Repo
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-ElementalX-OP3-0.22 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #3 SMP PREEMPT Wed Sep 28 00:02:55 UTC 2016
## Issue:

When i start badusb my phone Reboots.
There seems to be no rndis0. If i use usb tether in settings, rndis0 appears but disapears when stopping the tether. Phone still restarts when i use badusb with rndis0 interface up, just wanted to mention it. 
On my OP2 rndis0 shows under NH app network interfaces upon phone start without need of other input.

**Comment by ozsteyr** [comment]
Not sure if this helps but, i tried a non - NH, ElementalX kernel and BadUSB works as it should.

**Comment by majackov** [comment]
Yes, I have too this trouble, but I dont use badusb yet

**Comment by ozsteyr** [comment]
By choosing rndis0 as a usb config in dev options and using ifconfig, i can get rndis0 up without using usb tether switch, but badusb in NH app still restarts phone.

**Comment by ozsteyr** [comment]
I admit I know next to nothing about kernels and such but, because BADUSB worked with one kernel and not the other, could someone explain how to compare the two and maybe i could try and find the issue?

Thanks

**Comment by PaElodar** [comment]
I too have this problem.
Its good to see the devs actively trying to help (NOT)
I get that there busy and no doubt doing this for free but come on 20 days without so much as a reply?
It looks as though at least one user wants to try and get it fixed but is not even given pointers to do it themselves.
There are now three reported users with the same issue, could someone please look into this.

**Comment by binkybear** [comment]
@PaElodar - You are welcome to provide a logcat or last_kmsg when it's rebooting.  I don't have a OnePlus3, which I've stated before.  I can't recreate this issue, therefore I can only guess at solutions to fix this issue.

The OnePlus3 is a new device and each device has it's own kernel and it's own problems.  None of the devs own the OnePlus3.  So please, provide some type of log or offer a fix because I know as much as everyone else here in regards to the problem.

**Comment by PaElodar** [comment]
Thank you very much for the reply.
cat /proc/last_kmsg no such file or directory.
cat /proc/kmsg, is ok, just not sure what im looking for.

**Comment by binkybear** [comment]
A /proc/last_kmsg will generate after a "kernel oops." After the phone reboots you would have to check.  Also, a logcat running when error occurs might help if its software related.

**Comment by PaElodar** [comment]
last_kmsg still says no such file or directory.
So i took a kmsg before and after the BADUSB reboot. I hope this is somewhat helpful.

BEFORE
http://pastebin.com/E4u7ivQr

AFTER
http://pastebin.com/DtWNiSn9

**Comment by ozsteyr** [comment]
So if last_kmsg is no such file or directory does this mean its not a kernel oops?
Also i tried mubix lock and this too reboots my phone, are they related in some way?
What other logs would be helpful?
Thanks.

**Comment by binkybear** [comment]
@ozsteyr - The mubixlock and badusb use the same type of script to set the usb device to rndis.  Is possible to try parts of the script manually to see where it might lock up for you.  My guess would be it might lock when trying to set rndis0.

**Comment by ozsteyr** [comment]
Thanks for the help. I did as you sugested and When i navigated to /sys/devices/virtual/android_usb/android0/functions the phone rebooted.

**Comment by binkybear** [comment]
Looking through the source code it appears that I need to set an option in OnePlus 3 defconfig:

https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/blob/5ac8dc344aa5242cadae5f8010497e6b2869575c/drivers/usb/gadget/configfs.c#L1700

I believe option is located here in defconfig:

https://github.com/binkybear/android_kernel_oneplus_msm8996/blob/ElementalX/arch/arm64/configs/kali_defconfig#L3362

Will post updated kernel

**Comment by ozsteyr** [comment]
Cheers Binky

**Comment by binkybear** [comment]
Did not mean to close this. Pushed updated kernel.  Please test when you have time.

**Comment by ozsteyr** [comment]
Built new kernel using, python build.py -d oneplus3 -k which produced, kernel-nethunter-oneplus3-marshmallow-20161119_000557.zip. Problem still persists.

**Comment by binkybear** [comment]
@ozsteyr - Can you also do a
```
ls /sys/devices/virtual/android_usb/android0/
```

**Comment by ozsteyr** [comment]
And post it?

**Comment by binkybear** [comment]
@ozsteyr - Yes please. Also a
```
cat /sys/devices/virtual/android_usb/android0/functions 
```

**Comment by ozsteyr** [comment]
cat /sys/devices/virtual/android_usb/android0/functions reboots the phone

**Comment by binkybear** [comment]
Was there anything from ls?

**Comment by ozsteyr** [comment]
Posted it

**Comment by binkybear** [comment]
Implemented jcad's suggested fix.  Uploaded to nethunter-devices.  Please try again when you have time.

**Comment by ozsteyr** [comment]
Now were getting somewhere!
Phone no longer reboots when using BADUSB or mubix-lock. Although neither seem to work.

**Comment by ozsteyr** [comment]
Thankyou both so much for your help and time

**Comment by binkybear** [comment]
So rndis0 still isn't working?  HID is ok?

**Comment by ozsteyr** [comment]
HID is fine, havnt had trouble with it yet. Using  BADUSB and mubix-lock both start without errors that i can see but
Badusb using tcpdump -vv there is no traffic and mubix lock says type screen -r but there are none.

**Comment by binkybear** [comment]
@ozsteyr - Do you see an rndis0 interface with ip? (ifconfig)

**Comment by ozsteyr** [comment]
Yes, and there is now traffic via tcpdump, not sure about before. Rndis0 seems good

**Comment by binkybear** [comment]
I've updated kernel with jcad's full HID patch and possible Drivedroid patch.  I've uploaded here for now but it should be on build.nethunter eventually:

https://transfer.sh/oqTJE/kernel-nethunter-oneplus3-marshmallow-20161121-234857.zip

**Comment by ozsteyr** [comment]
Wasnt sure about drivedroid. It wasnt working a few months ago but now drivedroid free that is included in NH works as cdrom but nothing with drivedroid paid.

**Comment by jcadduono** [comment]
join drivedroid beta program and then you will get a beta page on play store where you can download drivedroid paid newer versions...i don't know why he is doing it that way, but yeah the drivedroid paid on the play store (non-beta) currently is ancient

**Comment by ozsteyr** [comment]
@jcad Thanks, had no idea.

**Comment by droidsec-cn** [comment]
oneplus2 has same problem,can you share a patch?
