### ISSUE TITLE
S7 Edge gets laggy after flashing kernel

### ISSUE THREAD

**Issue by h4x00r8** [offensive-security/kali-nethunter#629]
Hello everyone!
## Issue:

When installed nethunter-generic-arm64-kalifs-full-rolling-3.15.2-20161016-0305.zip it seems the kernel doesn't changed. (Kernel Version - 3.18.14-8252943 dpi@SWDD6821 #1)  in addition, i could not load supported wlan1 drivers.

I tried to flash the kernel only (via TWRP) - IT WORKS (i can load wlan1 drivers), but with the new kernel the device is very slow and laggy.

The steps i took to install Nethunter:
1. flash STOCK Rom via Odin
2. flash TWRP (Last Version) via Odin
3. Format Data (twrp)
4. reboot device and setup
5. installed - nethunter-generic-arm64-kalifs-full-rolling-3.15.2-20161016-0305.zip from - https://build.nethunter.com/nightly/

*\* 6. After noticing the stock kernel didn't changed, i flashed the kernel only for hero2lte devices - kernel-nethunter-hero2lte-marshmallow-3.15.2-20161016-0305.zip

From this step, the device is very slow and laggy.

do you have any recommendations for this issue?
### Device:

**S7 Edge SM-935FD**
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

**Marshmallow**

**Comment by jcadduono** [comment]
I think this might be due to extra column in heap stats I will look at it soon

**Comment by h4x00r8** [comment]
Waiting for your update!

thanks for the great work.

**Comment by jcadduono** [comment]
this turned out to be a little more complicated than I had planned. I'm going to separate Note 7 and S7/S7 edge kernel sources for now until Samsung finds the time to merge them properly

**Comment by h4x00r8** [comment]
So is there any solution for this issue or we have to wait samsung to merge the s7 edge and note 7 kernel sources? :/

**Comment by jcadduono** [comment]
i made another kernel tree from s7 edge sources instead and am in the process of cherry-picking my note 7 commits onto it

**Comment by h4x00r8** [comment]
Great news! :)

**Comment by jcadduono** [comment]
can u let me know if https://build.nethunter.com/test-builds/kernel-nethunter-hero2lte-marshmallow-rebase-s7-b1.zip works for u

**Comment by h4x00r8** [comment]
Please let me know on any update regarding this, when the S7E kernel will be ready just let me know - i will test it.

**Comment by h4x00r8** [comment]
downloading.. i will update you shortly!

many thanks!

**Comment by h4x00r8** [comment]
Flashed kernel-nethunter-hero2lte-marshmallow-rebase-s7-b1.zip , the device is stuck on lock screen, after 4 min - cant get the keyboard working (samsung and hacker keyboard)

**Comment by h4x00r8** [comment]
Although you dont have the device on hand, if i can help - use me.

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/kernel-nethunter-hero2lte-marshmallow-rebase-s7-b2.zip how about this?

**Comment by h4x00r8** [comment]
with the b2 version the device is booting slow (without freezing) but still very slow and laggy.
(very same as kernel-nethunter-hero2lte-marshmallow-3.15.2-20161016-0305.zip)

if you want me to extract logs or anything else - just tell me what you need.

thanks!!

**Comment by jcadduono** [comment]
huh interesting ok i'll try a stock build from each

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/kernel-nethunter-hero2lte-marshmallow-rebase-s7-b3-stock.zip

no nethunter stuff just stock kernel (built from source) by itself, is this laggy too?

**Comment by h4x00r8** [comment]
ok, so i flashed b3 kernel, same problems like the b1 / b2. 
what kernel version did you used for this package? 
after reverting to my working stock kernel i noticed the version is 3.18.14-8252943

**Comment by jcadduono** [comment]
Hmm I just used the stock source of G935FXXU1BPHJ :(

**Comment by jcadduono** [comment]
Can you grab logs please then adb logcat and adb shell dmesg
You need USB debugging enabled

**Comment by h4x00r8** [comment]
##############
Logcat log
##############

--------- beginning of main
W/SELinux (26739): SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.jtb.alogcat 
D/TimaKeyStoreProvider(26739): TimaSignature is unavailable
D/ActivityThread(26739): Added TimaKeyStore provider
I/InjectionManager(26739): Inside getClassLibPath caller 
W/System  (26739): ClassLoader referenced unknown path: /data/app/org.jtb.alogcat-1/lib/arm64
W/XPrivacy(26739): Hooking package=org.jtb.alogcat
W/XPrivacy(26739): Get client 10260/SERIAL(null;null) identification=!restricted 5112 ms
D/RelationGraph(26739): garbageCollect()
--------- beginning of system
D/ContextRelationManager(26739): ContextRelationManager() : FEATURE_ENABLED=true
W/ResourcesManager(26739): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package org.jtb.alogcat
I/InjectionManager(26739): Inside getClassLibPath + mLibMap{0=, 1=}
D/ResourcesManager(26739): For user 0 new overlays fetched Null
D/InjectionManager(26739): InjectionManager
D/InjectionManager(26739): fillFeatureStoreMap org.jtb.alogcat
I/InjectionManager(26739): Constructor org.jtb.alogcat, Feature store :{}
I/InjectionManager(26739): featureStore :{}
D/RelationGraph(26739): garbageCollect()
W/ResourcesManager(26739): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package org.jtb.alogcat
W/ResourcesManager(26739): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package org.jtb.alogcat
D/AbsListView(26739): Get MotionRecognitionManager
E/MotionRecognitionManager(26739): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@e5aec77
E/MotionRecognitionManager(26739): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@bcd20e4
E/MotionRecognitionManager(26739): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@bcd20e4
D/Activity(26739): performCreate Call Injection manager
I/InjectionManager(26739): dispatchOnViewCreated > Target : org.jtb.alogcat.LogActivity isFragment :false
D/SecWifiDisplayUtil(26739): Metadata value : SecSettings2
D/ViewRootImpl(26739): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{8a4c95a I.E...... R.....ID 0,0-0,0}
D/ViewRootImpl(26739): #1 mView = android.widget.LinearLayout{d562126 V.E...... ......I. 0,0-0,0}
I/InjectionManager(26739): dispatchCreateOptionsMenu :org.jtb.alogcat.LogActivity
I/InjectionManager(26739): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/ViewRootImpl(26739): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
D/ViewRootImpl(26739): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(26739): Timeline: Activity_idle id: android.os.BinderProxy@8a6ded8 time:3800590
D/ViewRootImpl(26739): #3 mView = null
W/XPrivacy/XRuntime(26739): Get client 10260/exec(logcat -v brief *:V;null) shell=!restricted 10402 ms
W/XPrivacy/XRuntime(26739): exec 10403 ms
D/ViewRootImpl(26739): ViewPostImeInputStage processPointer 0

**Comment by h4x00r8** [comment]
The dmesg log is too long how can i send it to you?

**Comment by h4x00r8** [comment]
*** logcat and dmesg logs are extracted with my WORKING stock kernel **

**Comment by h4x00r8** [comment]
OK i uploaded the 2 logs to zippyshare:

http://www49.zippyshare.com/v/Q08rCLXj/file.html

**Comment by Star3161** [comment]
Hey I just want to jump in here. I too have the same problem but on the S7 (G930FD) I ran some Geekbench tests and I recieved the following scores: **621** Single-Core, **575** Multi-Core and **317** RenderScript Score, whereas on the stock ROM (FXXU1BPI) the scores are normal. I know this is far from the normal scores but I believe that the kernel is somewhat limiting the CPU.

**Comment by jcadduono** [comment]
dmesg/logs from working kernel will not help/be useful, and i can't download from zippyshare, it just redirects me to virus infested sites, consider making a google drive account or something

**Comment by h4x00r8** [comment]
Which kernel do you want me to install and extract the logs?

**Comment by h4x00r8** [comment]
I will install kernel-nethunter-hero2lte-marshmallow-3.15.2-20161016-0305.zip and extract the logs.
 The other kernels (b1 b2 b3) is very unstable.

**Comment by h4x00r8** [comment]
Uploaded the Log files to drive - 
https://drive.google.com/drive/folders/0B58D78rosDd4aDhNWU96YXZkTzg?usp=sharing

**Comment by jcadduono** [comment]
hmm, dmesg was run too late to get any startup info (needs to be run as soon as you start your device), and logcat is invalid/empty (maybe try `adb shell logcat` instead?)

**Comment by h4x00r8** [comment]
OK i uploaded the logs again - this time from boot stage.
https://drive.google.com/drive/folders/0B58D78rosDd4aDhNWU96YXZkTzg?usp=sharing

** in dmesg logs folder there is 9 dmesg logs, dmesg9.txt is the last one taken

thanks!!

**Comment by Star3161** [comment]
I can confirm that both (kernel-nethunter-herolte-marshmallow-3.15.2-20161019-0333) and (kernel-nethunter-herolte-marshmallow-rebase-s7-b1) are also lagging. Here the the logs including a geekbench screenshot. https://drive.google.com/open?id=0B9VfwWEOHA1cWUpUN3hhMFNlU3M - feel free to ask me for testing S7 kernels. Thanks!

**Comment by h4x00r8** [comment]
Any update with this issue? :/

**Comment by jcadduono** [comment]
sorry guys I'm stumped, I can't find anything that points to the cause of the issue. I'll need to ask a kernel dev who's experienced with S7 to help me solve it.

**Comment by Star3161** [comment]
No problem! Thank you for your hard work and dedication! Hope this gets solved :)

**Comment by Star3161** [comment]
Hi, just a quick update. I have flashed both of the lastest kernels (kernel-nethunter-herolte-marshmallow-3.15.2-20161024-2241) and (kernel-nethunter-herolte-marshmallow-3.15.2-20161023-0148) but they are still laggy and are having the same poor CPU performance in geekbench tests. Just a heads up!

**Comment by h4x00r8** [comment]
Hey..
any update regarding this issue?

=\

**Comment by jcadduono** [comment]
nope

**Comment by Star3161** [comment]
@jcadduono which note 7 ports rom do you recommend that are confirmed working?

**Comment by jcadduono** [comment]
No confirmation, try them all and report back!

**Comment by h4x00r8** [comment]
Hey jcadduono

I have a Working S7 Edge Kernel thats Working with Nethunter.

I am using this kernel about 2 month.
there are no performance issues,
but i experiencing system reboots from time to time.

if i will send you the working s7  Edge kernel it can help in the process?

thanks

**Comment by jcadduono** [comment]
no

**Comment by Star3161** [comment]
@h4x00r8 would you mind sharing the ROM? I would be able to test it on my S7 (Flat) Thanks!

**Comment by h4x00r8** [comment]
this is a kernel only, and for S7 Edge version.

if it helps, i can share it with you.

**Comment by kalqaatri** [comment]
hi @h4x00r8 would you mind sharing the kernel please ?

thanks

**Comment by zcyang668** [comment]
Works well with Superman rom v1.18.1
