### ISSUE TITLE
Android 5.0 Support

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#63]
I'm getting a Nexus 7 2013 Wi-Fi edition soon. Is Android 5.0 supported, or should I wait with Kitkat?

**Comment by chrisbdaemon** [comment]
Bump..

Can this issue be reopened?

**Comment by DrDinosaur** [comment]
Yes, it has been some time. I can't imagine too many people have not
upgraded to Lollipop by now.

**Comment by magichand** [comment]
If you follow the guide to compile it on your own you should be able to get flashable zip. 

Works for me on oneplus one device. Works fine with CM12.

**Comment by DrDinosaur** [comment]
Hopefully a simpler solution is in the works.

**Comment by magichand** [comment]
Which device you have? I can try to compile it for you.

**Comment by DrDinosaur** [comment]
Nexus 7 2013 32GB Wi-Fi.

**Comment by magichand** [comment]
Looks like your device is not in the menu for Lollipop. Only the following:-

 ---- NEXUS 10 (2012) - MANTA --------------------------------------------------------
  [1] Build for Nexus 10 Kernel with wireless USB support (Android 4.4+)

 ---- NEXUS 7  (2012) - GROUPER/NAKASI -----------------------------------------------
  [2] Build for Nexus 7 (2012) with wireless USB support (Android 4.4+)

 ---- NEXUS 7  (2013) - DEB/FLO ------------------------------------------------------
  [3] Build for Nexus 7 (2013) with wireless USB support (Android 4.4+)

 ---- NEXUS 4  (2012) - MAKO ---------------------------------------------------------
  [4] Build for Nexus 4 with wireless USB support (Android 4.4+)

 ---- NEXUS 5  (2013) - HAMMERHEAD ---------------------------------------------------
  [5] Build for Nexus 5 with wireless USB support (Android 4.4+)

 ---- NEXUS 6  (2014) - SHAMU --------------------------------------------------------
  [6] Build for Nexus 6 with wireless USB support (Android 5)

 ---- NEXUS 9 (2014) - VOLANTIS ------------------------------------------------------
  [7] Build for Nexus 9 with wireless USB support (Android 5)

  [0] Exit to Main Menu

**Comment by DrDinosaur** [comment]
3 looks like a match, no?

**Comment by magichand** [comment]
That says for kitkat.

**Comment by unknownpwn** [comment]
@magichand no it says for 4.4+ (which means 4.4 and above)

**Comment by magichand** [comment]
Ok then.  I'll compile it.

**Comment by millzee2000** [comment]
Where will it be once you do? I've got this device and I really want to try nethunter

**Comment by magichand** [comment]
I'll post a Mega link for you guys. Still compiling at the moment. Hopefully no error turns up.

**Comment by offensive-security** [comment]
We'll announce public lollipop builds on http://nethunter.com when we're ready.

**Comment by millzee2000** [comment]
Ok thanks a lot :)

**Comment by magichand** [comment]
Sorry for being a bit late. Here is the link.

https://mega.co.nz/#F!aZEj1ZYA!P_N1FxVlQOyUc3KwZ19iKg

Any bug, raise it to the official maintainer. I'm just helping to compile base on the official repo.

**Comment by millzee2000** [comment]
That's awesome. Which should I flash first? I'm guessing the kernel but I wasn't sure.

**Comment by magichand** [comment]
Just flash the biggest file. bear in mind, you need to flash this on top of any AOSP/Stock ROM. Any OTA update will wipe out your installation as well. I am not sure how to recover it after an OTA flash.
