### ISSUE TITLE
Nexus5 nethunter3.15.2 HID ATTACK problem 

### ISSUE THREAD

**Issue by SuzumiyaXZ** [offensive-security/kali-nethunter#632]
### Device:

Nexus5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

lollipop

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.2-20161012-2207/nethunter-generic-armhf-kalifs-full-rolling-3.15.2-20161012-2207.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-g8a80a0e (android-build@vpbs1.mtv.corp.google.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Thu Feb 5 04:14:26 UTC 2015

## Issue:
I have a Nexus5 running kali nethunter 3.15.2 
TWRP：2.8.6.1
OS：Android5.0
I use this rom
https://build.nethunter.com/nightly/3.15.2-20161012-2207/nethunter-generic-armhf-kalifs-full-rolling-3.15.2-20161012-2207.zip
The nethunter home hava the
HID Interfaces
/dev/hidg0
but when i hit execute attack and my nexus 5 connect my Computer Nothing happened. and I open the USB keyborad APP display Only support Nexus 7 
i tried these methods. https://github.com/pelya/android-keyboard-gadget
But they are useless 
but the BAD USB MITM can work。
THANKS。

**Comment by jcadduono** [comment]
you need to install a kernel, you can't just use generic by itself with kernel required features...

**Comment by SuzumiyaXZ** [comment]
Ok，I'm trying. Thanks.

**Comment by akrolla** [comment]
Anykernel for nexus 5 is a good one google it u can find it. It is also in
the nethunter zip . I've found that including the kernel in the nethunter
install bogs the nexus 5 down significantly and leads to incomplete
installs.

**Comment by jcadduono** [comment]
As of NetHunter 3.1 there are no remnants of AnyKernel in the installer code and the boot image patching code was redone based on the LazyFlasher project, which is an attempt to make a universally supported patcher similar to AnyKernel but with much more error handling, compatibility, and developer friendliness. :D

As for issues with NetHunter kernel for Nexus 5 slowing down the device, I have not heard of this?

**Comment by akrolla** [comment]
Locks up aroma installer and doesn't complete the install in multirom will
stay stuck at a stated percentage saying installing apps or at other steps
involved like it will stick at 90% one time and then try again it gets
stuck at 60 etc etc.. the only successful way to install it in my luck has
been to load anykernel seperately but I will try that kernel also. I am on
3.15 and did that for 3.0 and this one. I have slow internet so I have to
predownload everything and can't clone a git on a fly I'm getting faster
internet this week so i will give it a try. As for now I'm like whatever
works.

**Comment by akrolla** [comment]
That is really great news Im glad to see the nexus 5 still getting as much
support as it does.remarkable. is it lazykernel or a derivative?
