### ISSUE TITLE
Nethunter not working on OnePlus 2 CM13. Stuck at oneplus logo.

### ISSUE THREAD

**Issue by 1nt3rnal3rr0r** [offensive-security/kali-nethunter#634]
### Device:

OnePlus 2
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

CM13 Marshmallow
### Built from repo (date and build command) or downloaded from website (links):

Built from repo(today 20-th of October). I am sure that I have built the right zip because the output file is named "update-nethunter-oneplus2cm-marshmallow-20161019_234735.zip".
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Can't get to the terminal.
## Issue:

Nethunter does not work with the most recent CM13(cm-13.0-20161015) nightly build for OP2. I seem to get stuck at the oneplus logo. This is probably a kernel issue. Nethunter does not work with OOS as well.

**Comment by ultron0** [comment]
The kernel is bugged for sure. Installing nethunter without the custom kernel does work, but as soon as I install the kernel, the device does not boot at all.
