### ISSUE TITLE
Oneplus3 WIFI not working showing MAC address as 02:00:00:00:00:00 after flashing kernel

### ISSUE THREAD

**Issue by lightpencil** [offensive-security/kali-nethunter#635]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow OOS_16_1609301402
### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.2-20161019-0333/kernel-nethunter-oneplus3-marshmallow-3.15.2-20161019-0333.zip
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-perf+ (OnePlus@ubuntu-21) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Sep 30 14:06:43 CST 2016    
## Issue:

The problem is very intreresting. Firstly i flashed the kernel in builds previously released, same problem, wifi not working showing MAC address as 02:00:00:00:00:00, so i skiped to flash the kernel and derectly flashed full nethunter build (nethunter-generic-arm64-kalifs-full-rolling-3.15.2-2016xxxx-xxxx.zip) i can't remember. It worked. And today I tried again to flash the kernel _https://build.nethunter.com/nightly/3.15.2-20161019-0333/kernel-nethunter-oneplus3-marshmallow-3.15.2-20161019-0333.zip_ it's still the problem. At this time the kernel changed. However, I accidently flashed the update one which is **update-nethunter-generic-arm64-3.15.2-20161019-0333.zip,** after boot into the system I found that the kernel version changed to _Linux version 3.18.20-perf+ (OnePlus@ubuntu-21) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Sep 30 14:06:43 CST 2016_  and the wifi is woking. it seems that the flashed kernel disappeared...
So what should i do now??

**Comment by majackov** [comment]
I have too this problem (oneplus3)

**Comment by lightpencil** [comment]
@majackov many thanks, I'll try it.
Thats why i open the issue, to find a permanent solution.

**Comment by shonenx333** [comment]
I dont know if you tried @jcadduono solution for a earlier kernel:

> Try
> 
>  as root:
> 
> find /system -name wlan.ko
> 
> then
> 
> mount -o remount,rw /system
> cat /sbin/wlan.ko > (location from find command)
> mount -o remount,ro /system
> sync
> reboot
> 
> this will replace your wlan kernel module with the one from NetHunter instead of trying to use that loader script thing

i had to do this with my kernel build(maybe 2 weeks ago - also OP3). 
I dont know if they have fixed that. But it maybe worth a try.

**Comment by lightpencil** [comment]
@shonenx333 WOW thank you, it works perfectly well, it sovled the problem at the latest kernel!!

**Comment by majackov** [comment]
Yeah, it works, thx too

**Comment by nielz010** [comment]
Hey,
I have the same problem, but when I run the find /system -name wlan.ko command in the androidsu terminal it finds nothing. Can someone help me?

**Comment by test2556** [comment]
@shonenx333
My OP2 Wifi does not work and the mac adress is 02:00:00:00:00:00
all the commands work except this command: cat /sbin/wlan.ko > (location from find command)
it says no such file or directory.
can u please help because i need my wifi working.
tnx already

**Comment by lightpencil** [comment]
@test2556 replace '(location from find command)' to the output you find in the command 'find /system -name wlan.ko', it should be a path, not derectly run 'cat /sbin/wlan.ko > (location from find command)'.

**Comment by test2556** [comment]
@lightpencil yeah i did replace it to the location but it said no such file or directory.
but i removed linux nethunter because the wifi didnt work and the phone lagged a lot.
went back to the normal oxygen tnx for your answer.

**Comment by prime-i346** [comment]
Currently I'm having the same issue , I'm using op3 running cm13 and I need a terminal screenshot of it . somebody please.
