### ISSUE TITLE
DriveDroid Rebooting the Device! ( Oneplus 2 on Oxygen OS 3 )

### ISSUE THREAD

**Issue by PurvC** [offensive-security/kali-nethunter#637]
### Built from repo (date and build command) or downloaded from website (links):Built from repo -

python build.py -d oneplus2 -m -nosu - fs full ( Flashed SuperSu before flashing nethunter zip ).
Built on 20-Oct-2016
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.84-perf+ (root@nh-buildbox) (gcc version
4.9.x-google 20140827 (prerelease) (GCC) #3 SMP PREEMT We
d Oct 5 02:47:29 UTC 2016
## Issue: When the device hosted with the image is connected to the PC via USB, the device reboots.

@binkybear @jcadduono @jmingov

**Comment by binkybear** [comment]
Can you get the kernel debug info
```
su
cat /proc/last_kmesg > /sdcard/oops.txt
```

**Comment by PurvC** [comment]
cat: /proc/last_kmesg: No such file or directory

@binkybear

**Comment by jcadduono** [comment]
last_kmsg

**Comment by PurvC** [comment]
cat: /proc/last_kmsg: No such file or directory

@binkybear @jcadduono

**Comment by lightpencil** [comment]
same problem
