### ISSUE TITLE
Nexus 7

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#639]
### Device:

Nexus 7
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Cm 21.1
### Built from repo (date and build command) or downloaded from website (links):

Kali.org
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

linux version 3.1 10-00131-g477a94d (tassader@tyene) gcc 4.8
## Issue:

It still has the sana repos..I changed them but the HID keyboard and hid iterfaces aremissing .. do you know a better kernel to use that is accepted by the hid keyboard or how to add the hid interfaces? Hidkeyboard has you download a firmware and has you reboot . When done it boot loops.

**Comment by akrolla** [comment]
CM 12.1 typo

**Comment by jcadduono** [comment]
1. you have to use the sana chroot on your device, rolling requires a 3.2 kernel or newer
change your sources.list to point to old.kali.org

2. that's not the nethunter kernel for grouper so that's why things are missing (you can download it from build.nethunter.com if you like)
unsure if it works in its current status...don't think so

3. grouper is being discontinued as it is too old to run much

**Comment by akrolla** [comment]
It givesme 404s when I try to use sana it is also running on kali 3.1 and someof theupgrades state that the kernel must be upgraded to 3.2

**Comment by akrolla** [comment]
Yeaim tryingto frankenstein it with cm 12.1

**Comment by akrolla** [comment]
I have actively been trying to find a new kernel ill keep looking and keep my hopes up ...

**Comment by akrolla** [comment]
It works with cm12.1 but the hid function doesn't but then again I figured I have a ducky and my phone so there's a purpose for everything

**Comment by akrolla** [comment]
And I think on the usb github tueres instructions to compile a kernel so I might try that later and see if I can compile it with 12.1 ..

**Comment by akrolla** [comment]
@binkybear what is that nethunteros you just posted?

**Comment by akrolla** [comment]
@binkybear is that unlegacy grouper kernel pretty stable does NH and hid functions proper on it?

**Comment by akrolla** [comment]
Ps @jcadduono is the awesomest:-P

**Comment by akrolla** [comment]
y'all don't have the build on there anymore I bought this because I figured it'd have the great supprt the nexus 5 shares

**Comment by akrolla** [comment]
The anykernel was not the right kernel for it. that's why I used cm ... when I went to install in twrp and it tried tocinstall anylernel it said it was the wrong kernel

**Comment by jcadduono** [comment]
You can try one of the older kernels by building from the git. It's still possible.

You would have to clone this repository on a Linux box.
Then check out the **full** history when using nethunter-installer/bootstrap.sh.
Enter the `devices` folder after `./bootstrap.sh` and use the command:
```sh
git log --follow -- lollipop/grouper
```
To see history of where grouper existed. As you'll notice, there's a commit where grouper is deleted, and there's a commit where it's upgraded to 3.4, and there's a commit where it was initially added to the repository.
You will want to checkout the devices repository just before it was upgraded to 3.4 (it was very unreliable)
The commit hash for 3.4 update is `30f37892e2a5414b` so to grab grouper just before that happened, run:
```sh
git checkout 30f37892e2a5414b~
```
(the ~ tells git to grab just before that commit)

You can now go back to the nethunter-installer folder and build for it!
```sh
./build.py -d grouper --lollipop -k
```
I think this revision is for the latest Nexus factory image of Lollipop.

You should now have a kernel-nethunter-grouper zip file that can be installed in TWRP.

Have fun!

**Comment by akrolla** [comment]
I found a anykernel kma try it out and then imcgoing to do what you said... I've. Never rewally donw it that way before still a noob to softwaare how do I set up that environment in python

**Comment by akrolla** [comment]
Heres a link 
https://github.com/koukaipan/anykernel-updater-grouper

**Comment by akrolla** [comment]
or ima try this one http://forum.xda-developers.com/nexus-7/orig-development/wip-linux-tegra-nv-3-4-bringup-t3128195 that has whole kernel

**Comment by jcadduono** [comment]
You can use https://github.com/jcadduono/lazyflasher/tree/kernel-flasher instead of you're going that route.
Download https://github.com/offensive-security/nethunter-devices/raw/952ae9e20d82850144c41e80fd5de35680722d70/lollipop/grouper/zImage (last available NetHunter grouper kernel at Linux 3.1) and place it in the lazyflasher folder, then type make or just manually zip the folder.

**Comment by akrolla** [comment]
Well for future ref. How do I do it that way

**Comment by akrolla** [comment]
thanks for all ur he'll jcadduono you're pretty sharp.

**Comment by akrolla** [comment]
Help not he'll

**Comment by akrolla** [comment]
IMA keep this open as a reference I know there's still a lot of people using grouper if that's alright

**Comment by v-mos** [comment]
hi @akrolla you have any luck running NH 3.0 in the Nexus 7, any help would be really apreciate

**Comment by v-mos** [comment]
Thanks ! I recently flash the aosp rom with android n 7.1 with kernel 3.4 after I installed a generic minimal rolling of NH the installer go well no boot issues but when I try to setup the chroot with the nethunter app, the app doesn't detect the busy box that is already installed I'm not able to found a fix or information for this 

The room is fully functional maybe that can help you in the other project

**Comment by bayp1p0** [comment]
@v-mos pls help us how can ı upgrade my kernel 3.1 to 3.4...
android 5.1 and nexus 7  2012 ı have that.
ı do that https://forum.xda-developers.com/nexus-7/orig-development/wip-linux-tegra-nv-3-4-bringup-t3128195 but my android became trash ı mean ı can do that :)
https://github.com/jcadduono/lazyflasher/tree/kernel-flasher is it work for me and last question;
when I use kernel flasher ? before or after  nethunter install ?

**Comment by saxesn** [comment]
i get it running with CM14 and kernel 3.4


1. Flash the [Image ](https://forum.xda-developers.com/nexus-7/development/rom-cm14-1-nexus-7-2012-t3507001)

2. Boot the Image and finish the Setup Wizard 

3. Flash Nethunter [nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-****](https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-20170211-0304.zip) -> some errors with Chroot install

4. Sideload BusyBoxFree APK

5 Reinstall BusyBox -> Video

6 Install Chroot from SD Card or Download

**Comment by saxesn** [comment]
i get it running with CM14 and kernel 3.4


1. Flash the [Image ](https://forum.xda-developers.com/nexus-7/development/rom-cm14-1-nexus-7-2012-t3507001)

2. Boot the Image and finish the Setup Wizard 

3. Flash Nethunter [nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-****](https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-20170211-0304.zip) -> some errors with Chroot install

4. Reinstall Terminal and Nethunter App (permission issue)

5. Sideload BusyBoxFree APK

6. Reinstall BusyBox -> tricky :see_no_evil: -> [Video](https://youtu.be/m1q6iGHUDMw)



7. Install Chroot from SD Card or Download 

but i cant Flash Nethunter and Gapps together -> system partition full... :-1:

**Comment by crypt0b0y** [comment]
@saxesn, i'm did it. And install chroot from last image for Nexus 7 2012. But how can i upgrade kernel for using OTG with wi-fi adapter? any help?

**Comment by thedp** [comment]
@crypt0b0y Were you able to resolve it?

**Comment by gtg472b** [comment]
@saxesn thanks so much! How the eff did that work for installing Busybox? I kept following along and didn't believe it would work but then all the sudden it did...??

Major question for you though...bcmon and other programs are old compiles, and they don't support PIE (position independent execution). That leaves me with two options...use Android 4.4.4 with everything working, but an old copy of Kali, or go with your method for Android 7.1 and no bcmon or other apps that have been discontinued. Have you found a way around this? All the old ways of hacking the linker file for Android 5 don't seem to work for Android 7, it just bootloops when I patch the file (or maybe my assembly is too rusty to do it properly). I just started looking into how to recompile bcmon, but there aren't any instructions and thus way beyond my comfort level. Any help is appreciated.

**Comment by SimenDeath** [comment]
@saxesn 
Hi, guys
I installed ua_grouper with 3.4 kernel on my Nexus 7 grouper .. also i used nethunter generic minimal arm64. Everythink looks fine. Right now i am really not able to get over tricky part of installing busy box .. when i am uinstalling (in app busybox) it will freeze the app. I need to close and restart. Installation of busybox (into su/xbin or system/xbin) looks also right - in upper bar i got info which is installed or if none is installed. ....
Still got problem with nethunter and not detection of busybox in nethunter :( any tips please ?

**Comment by gtg472b** [comment]
@simendeath I literally just followed the video that @saxesn posted to YouTube. It feels dumb doing things you know don't work, but then it magically worked at the end. I have no idea why. Play his video and do exactly the same stuff he did.

**Comment by SimenDeath** [comment]
@gtg472b Can i ask you what rom did u have? :) CM14 or AOSP ?

**Comment by louisgv** [comment]
I'm having the same problem but not on grouper but tilapia. I'm using https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-20170211-0304.zip 

with AOSP ROM for K3.4 at https://forum.xda-developers.com/nexus-7/orig-development/wip-linux-tegra-nv-3-4-bringup-t3128195

BusyBox installed successfully for me, and older version of NetHunter recognized it! (md5sum == aeabeff3c0238c4921a3cdd72a23e372 )

However, opening latest version of NetHunter from the flashed zip will show the BusyBox not found error. I'm very stuck....

@SimenDeath which version of NetHunter image are you using? (The date number if you could please provide it)

**Comment by jcadduono** [comment]
Be sure to delete /system/xbin/busybox_nh if it won't run properly on your device, NetHunter will only see that if it exists

**Comment by louisgv** [comment]
That was it! @jcadduono You are the awesomest!

To folk who ran into the same problem: Boot into recovery, then mount system, then use TWRP's file manager to delete busybox_nh.

You can do so in adb too but you will need to mount /system as read/write.

**Comment by SimenDeath** [comment]
@louisgv Hello my friend,
Here is for all people here what i used :)

1. twrp-3.0.2-0-grouper-k3.4-20160822 TWRP for Nexus 7 grouper
2. ua_grouper-7.1.2-20170718215606 ROM for Nexus 7 grouper
3. open_gapps-arm-7.1-pico-20170715 Gapps Pico version - smallest as possible
4. nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-20170211-0304  Nethunter for arm64

**Comment by gtg472b** [comment]
FYI I have this semi successfully working via multirom. The new kernel, 3.4, isn't kexec and so it causes some issues. It can't be the internal ROM, so I installed stock to internal, copied it to a secondary ROM, then wiped internal. Installed UA7.x into internal. Then moved it from internal to secondary. Copied stock back to internal. Now multiboot works. However, UA+Kali won't boot. So when I want to boot Kali, I have to copy it into internal slot. Kali boots directly, but doesn't give the option to multiboot. PITA. I think I've tried injecting boot into Kali while it's in internal slot, but it says the boot partition isn't big enough or something.

Now my main problem is that old programs and apps don't work because they weren't compiled with PIE support. Anyone figured out how to bypass that yet? Eg, bcmon.

**Comment by gtg472b** [comment]
To fix the PIE issue (hacking linker just froze boot for me), read Koorosh's response, answer #2

https://stackoverflow.com/questions/30498776/position-independent-executables-and-android-lollipop

"I know this is an old topic but this hacky way may save some people's time with a Hex-Editor , find the 17th byte, change the value 02 to 03, and that’s it!"

Programs like iwconfig work no problem, and enable_bcmon no longer gives a PIE error, but I still can't get the bcmon app to work. I'm currently running down issues with it not being able to find libraries, so I'll probably just move them to different folders.

**Comment by 0E800** [comment]
2018 and both deb flo grouper and tilapia have decent 3.4 kernels making marshmellow , nougat, and even oreo roms possible.  

Dont give up on the original device that inspired KaliPWN and paved the way for affordable portable devices before Nethunter was even a glint in the eyes of the offsec crew.  

N7 deserves some attention again.

**Comment by kfxtech** [comment]
@0E800 its been a few months but did you build the alpha nethunter for oreo nexus 2013? I have the LTE model deb if you need tester.

**Comment by 0E800** [comment]
Apologies .Life drama got me side tracked . Had to focus on keeping a roof over head .

I'll revisit and see where I left off. Im pretty sure I got Nougat working . I also was attempting to create and all in one single zip to flash and somehow couldn't get WiFi injection working. 

Thank you for the reply .

**Comment by dsingler** [comment]
I have a N7 grouper I've messing with if you need testing still. I'm willing to loaded it another 60+ times to get what I want. I've been down just about every path.

**Comment by 0E800** [comment]
Awesome . I'll try to have something for you to test shortly .

I have 3 N7 Groupers and 1 tilapia. The problem I have mostly with the N7 
is the janky microusb port that gets lose and makes it very difficult 
troubleshoot .
≪0E8⊘⊘≫
   🅼🅸🅽🅳 ᵃˢ ⲱⲉⲁⲣⲟⲛ

**Comment by 0E800** [comment]
Better late than never...

If anyone wants to beta test:

Android Pie Nethunter for Nexus 2013 Wifi (Flo) (have not tested Deb)

https://github.com/0E800/Nexus-7-2013-Flo-Experimental/releases/tag/RR_PIE_Flo_Kali

**Comment by emprise1976** [comment]
@0E800 
Does NMAP work now?

**Comment by 0E800** [comment]
Not yet. Need to get the kernel right before I can break off to explore
specific issues.
Nmap is either causing problems because of some lack of kernel driver
module or its because nmap needs to be compiled with patches related to the
issue and link I posted on the other thread.

Would be helpful if other users could report if its working or not and if
they are on a recent kernel.
