### ISSUE TITLE
Can't install nh terminal app

### ISSUE THREAD

**Issue by nik012003** [offensive-security/kali-nethunter#641]
### Device:

OnePlus One /Bacon

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow cm13 10/22/2016 Nightly

### Built from repo (date and build command) or downloaded from website (links):

Downloaded from : 
build.nethunter.com

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.112-cyanogenmod-g8fbc62e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016

## Issue:
After I did the generic armhf update and updated the kernel the Nethunter App and the Terminal App were removed.So I reinstalled the Nethunter  app and it works just fine but the nh-terminal app doesn't install.

**Comment by binkybear** [comment]
https://github.com/offensive-security/kali-nethunter/issues/605

Issue is related to new signing key.  Try to uninstall using adb or commandline on device:
```bash
adb uninstall com.offsec.nhterm
```
or on device
```
su -c pm uninstall com.offsec.nhterm
```

**Comment by nik012003** [comment]
Thank you ,now it works!
