### ISSUE TITLE
external wlan1 connact

### ISSUE THREAD

**Issue by h4x00r8** [offensive-security/kali-nethunter#642]
Someone know how to connect external wifi (wlan1) to secured wpa network?
i could not find the wpa_supplicant.conf and cant install gui version of network-manager 

thanks
### Device:

Galaxy S7 edge
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

KitKat

**Comment by daedroza** [comment]
```
ifconfig wlan0 down
ifconfig wlan1 down
ifconfig wlan1 up
iwconfig wlan1 mode managed
```
The access point should already be saved, only then your external WiFi adapter will automatically connect to the saved access point.

**Comment by h4x00r8** [comment]
Where i configure the wpa settings? The wpa_supplicant.conf cannot be modified.

**Comment by daedroza** [comment]
First configure your access point through Settings > WiFi, then do what I said above.
