### ISSUE TITLE
WHY BadUSB blocks HID attacks?

### ISSUE THREAD

**Issue by Chessito** [offensive-security/kali-nethunter#643]
I connect my Nexus 5 to my computer and start BadUSB using the rndis0 interfaz but while BadUSB is running i want to run some cmd commands using HID attack but it doesn't works while badUSB is running... I can use HID attack successfully every time but if i'm running badUSB at the same time HID doesn't works. can someone help me?

**Comment by bkr32** [comment]
your device can only be recognized once as a HID device if you choose to use BadUSB it will be recognized as such and attack cannot be chosen since BadUSB is used a networking usb device whereas other attacks recognize HID attacks as a usb keyboard
