### ISSUE TITLE
bootkali login file could not be found

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#644]
### Device:
Oneplus One

### Built from repo (date and build command) or downloaded from website (links):
nethunter generic full 3.15.2 20161010

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
linux version 3.4.112

## Issue:
when accessing the nethunter terminal i get the error

```
could not find: 
system/bin/bootkali_login:
please run Nethunter App to generate

```

bootkali login file is however present and running any command including custom commands from the app takes me to the root@kali terminal 
also running bootkali from androidsu takes me to it, i did use this build on cm13 and it worked without a problem

**Comment by binkybear** [comment]
Are you running the latest terminal app?  This should have been fixed in:
https://github.com/offensive-security/kali-nethunter/issues/604#issuecomment-252458353
https://github.com/offensive-security/kali-nethunter/issues/620

**Comment by bkr32** [comment]
thanks updated and its working fine
