### ISSUE TITLE
Nexus 6 DuckHunter Problem

### ISSUE THREAD

**Issue by raxmanis3333** [offensive-security/kali-nethunter#647]
### Device:

Nexus 6
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Android Nougat 7 
### Built from repo (date and build command) or downloaded from website (links):

Custom Build for nougat android..
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.40kali-g1d7b23e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #4 SMP PREEMPT Thu Aug 25 18:56:08 CDT 2016
## Issue:

I Try to attack windows 10 with DuckHunter HId attack but in my phone i see launched attack but nothing on victim pc...where is the problem??

thank for your help...

**Comment by CLCyber** [comment]
Check the app: USB Keyboard.

If it says: You need custom kernel.. You need to flash the custom kerel.

Just an Idea. I am not an Nethunter expert.

**Comment by BesoBerlin** [comment]
did you solve the issue?
by the way... how did you install the kernel succesfully? I am hardly trying to get it, but just get the error: "error: script failed 01-ramdisk-patch!" ... did you solve this somehow or did it work directly for you?
