### ISSUE TITLE
google keyboard + terminal

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#648]
### Device:

oneplus one
## Issue:

when trying to send commands to terminal such us volume down + c to stop a command, the google keyboard does not send that command rather it simply types C however when using aosp keyboard it works fine, this includes the on screen shortcuts
could it be a issue with the keyboard or the terminal app?

**Comment by binkybear** [comment]
https://github.com/binkybear/Android-Terminal-Emulator/issues/4

**Comment by mastermind860** [comment]
Hackers keyboard works well

**Comment by jcadduono** [comment]
hmmm, google keyboard is the only keyboard i use, no wonder i could never use this lol

**Comment by bkr32** [comment]
this issue taught me the importance of aosp keyboard
