### ISSUE TITLE
Will Google Pixel support nethunter in the future?

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#650]
Hi, everyone, I just wonder if anyone is already working on it. Now I am considering to buy a pixel phone but if the phone is confirmed not supported then I will go for one plus 3. Thanks guys.

**Comment by bkr32** [comment]
if one of the developers can get a hold of a pixel its entirely possible,
i'd suggest going for it as most of what makes nethunter work besides the framework which already exists for arm64 devices is the kernel

**Comment by PurvC** [comment]
Even if the Devs don't get hold of Pixel, you can always get help from the Wiki and help yourself with compiling and patching the kernel for Pixel.

**Comment by simonpunk** [comment]
Thanks guys, but I think I should wait and see as the price is still quite expensive. 
And I know there is a wiki guidelines teach you how to compile the kernel by yourself, and I did once before as well, but those pre-works are just like nightmare to me, I remember I couldn't always get the right version of the build-tool to build the kernel properly and each time the error message just frustrated me so mcuh. Also, I am just concerning the kernel of android 7.1 has changed too much that things can easily go wrong during compiling. And These concerns make me hang back.

**Comment by jcadduono** [comment]
when TWRP is working on it might be able to get something done, but not till then. Pixel has a lot of issues to get past as Google needlessly changed a lot to make it harder for custom FW to be installed. Pixel is NOT Nexus.

**Comment by GabrielTK** [comment]
+1

**Comment by jcadduono** [comment]
Pixel devices can in theory be supported now, needs a kernel build and 2 scripts

`patch.d/00-system-root`:
```sh
#!/sbin/sh
. "$env"
mv "$ramdisk" "$ramdisk-boot"
ln -s /system "$ramdisk"
```
`patch.d/99-system-root`:
```sh
#!/sbin/sh
. "$env"
rm "$ramdisk"
mv "$ramdisk-boot" "$ramdisk"
```

This will effectively make NetHunter patch the system root which Pixel devices use instead of the ramdisk root, allowing the installation to proceed as normal.

**Comment by eam9891** [comment]
anyone solve this yet?

**Comment by Klocko** [comment]
Any update? I'd love to not have to bring a second phone with me.

**Comment by akrolla** [comment]
we need testers for the pixel to bring forth development efforts, if you'd
like to be the guinea pig we provide as much support as we can to arrive to
a finished project as soon as we can!

**Comment by eam9891** [comment]
I would be willing to be a tester. Also would be willing to help in development. Not too experienced in this type of thing but have a decent background in programming. Will definitely be looking into how the porting process works and what is needed.

**Comment by GabrielTK** [comment]
Me too (testing and development) :D

On Feb 9, 2017 12:56 PM, "Ethan Morris" <notifications@github.com<mailto:notifications@github.com>> wrote:

I would be willing to be a tester. Also would be willing to help in development. Not too experienced in this type of thing but have a decent background in programming. Will definitely be looking into how the porting process works and what is needed.

**Comment by akrolla** [comment]
@jcadduono u got ur testers :). its cool giys it's a learning game for all
of us!:)

**Comment by jcadduono** [comment]
i am not interested in supporting these devices, you will have to wait for someone else to step up

**Comment by akrolla** [comment]
weren't u just asking for pixel testers a little bit ago?
https://github.com/offensive-security/kali-nethunter/issues/743

**Comment by Klocko** [comment]
That's Pixel C, but why? Most people use it on phones, not tablets.

**Comment by Klocko** [comment]
Any updates?

**Comment by GabrielTK** [comment]
I don't understand... So you need testers or not?? Also, why are we talking about Pixel C??

**Comment by GabrielTK** [comment]
Also, does it work with Magisk??

**Comment by Klocko** [comment]
No idea if it works with Magisk, and he wanted testers for Pixel C instead of Pixel phones, which is a strange choice.

**Comment by Klocko** [comment]
@simonpunk Been 4 months, it should be easier now.

**Comment by ChrisFernandez** [comment]
Any news on this for the pixel XL?
