### ISSUE TITLE
DuckHunter HID Spanish keyboard output is wrong!

### ISSUE THREAD

**Issue by DiegoSepu95** [offensive-security/kali-nethunter#652]
### Device:
Oneplus 1

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.110-nethunter-bacon-+ (root@nhbuild-box) (gcc version 4.7 (GCC) ) #2 SMP PREEMPT Sun Apr 10 08:48:30 CDT 2016

## Issue:
When I send an attack to my MacBook Pro computer, the letter g, G and almost all symbols are wrong. I tried fixing the es_bin file but I don't know what does the second string means for example "\x47": "\\x20\\x00\\x00\\x0a\\x00\\x00\\x00\\x00", I know \x47 is for the letter g, but I don't know what does \\x20\\x00\\x00\\x0a\\x00\\x00\\x00\\x00 means. Any help appreciated, thanks.

**Comment by DiegoSepu95** [comment]
Okay I fixed it, I just copy and pasted the \x47 and \x67, that are from G and g, from the us_bin and pasted them into es_bin.

**Comment by DiegoSepu95** [comment]
Any one that has mapped correctly the Spanish (Mexico) key output? I fixed some keys but the symbols are hard to fix.

**Comment by marasvensson** [comment]
I have same problem as you but do you know how to fix this on swedish keyboard
