### ISSUE TITLE
No sdcard and no wifi on OnePlus 3

### ISSUE THREAD

**Issue by shezack** [offensive-security/kali-nethunter#653]
## Issue: No sdcard showing after flashing this kernel. If I just flash the full nethunter pack stock kernel comes back and everything is fine. Even there is no wifi after flashing this kernel.
Plz help

**Comment by nielz010** [comment]
Same here, only SD card worm fine by me. Only wifi isn't working. Also the mac adress is: 02:00:00:00:00:00 Can someone tell ho tot Fix this?

**Comment by nielz010** [comment]
For some people this works:
Try

as root:

find /system -name wlan.ko

then

mount -o remount,rw /system
cat /sbin/wlan.ko > (location from find command)
mount -o remount,ro /system
sync
reboot

this will replace your wlan kernel module with the one from NetHunter instead of trying to use that loader script thing

But I cant find wlan.ko

**Comment by shezack** [comment]
I got my wifi working both internal and external, even I can put my wifi in monitor mode also,but the SD card issue still remains. In order to get the wifi working with the method you should flash the kernel from the build.nethunter.com as per your device. And in the about page you will see kernel version something like this..... Linux version 3.18.20-ElementalX-OP3-0.22 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #3 SMP PREEMPT Wed Sep 28 00:02:55 UTC 201640827 (prerelease) (GCC) ) #3 SMP PR.

**Comment by nielz010** [comment]
Linux version 3.18.20-ElementalX-OP3-0.22 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #3 SMP PREEMPT Wed Sep 28 00:02:55 UTC 2016

This is what i have, but still my wifi is nog working😥

**Comment by rob070511** [comment]
This should fix, worked for me.
[nethunter:patch.zip](https://github.com/offensive-security/kali-nethunter/files/570218/nethunter.patch.zip)

**Comment by jcadduono** [comment]
new build coming up soon...

**Comment by jcadduono** [comment]
how about todays build https://build.nethunter.com/nightly/3.15.2-20161104-0105/
wifi working?

**Comment by ozsteyr** [comment]
#596 may help with wifi, it did for me.

**Comment by shezack** [comment]
Everything nice and working.
Just one thing to ask, can we install fluxion in nethunter. Wifite doesn't seem to work for me, i tried on mutiple access points but it doesn't crack wpa2.

**Comment by shezack** [comment]
One more thing i forget to mention, the sdcard issue was due to Oxygen Community build 3.5.5, there is no issue with OOS 3.2.7

**Comment by ozsteyr** [comment]
Fluxion works through VNC. I have wireless, top 10 and password tools meta-packages installed and have no dependency issues with Fluxion.

**Comment by shezack** [comment]
Thanks for your support.
Closing

**Comment by pExeen** [comment]
hi shezack just a question : is everything working now ?

**Comment by shezack** [comment]
Yes I am using this build without any issues.
https://build.nethunter.com/nightly/3.15.2-20161104-0105/

**Comment by pExeen** [comment]
thanks :+1:

**Comment by mastermind860** [comment]
@shezack I have downloaded this kernel for OP3 https://build.nethunter.com/nightly/3.15.2-20161104-0105/
So. I have to unlock the bootloader first, install twrp, root the device, flash kernel and flash nethunter ? Is this process correct? If not please guide me through this.
