### ISSUE TITLE
Can't boot after flashing zip with CM13 based

### ISSUE THREAD

**Issue by sino1641** [offensive-security/kali-nethunter#655]
### Device:
Oneplus One

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

https://www.offensive-security.com/kali-linux-nethunter-download/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

No logs.

## Issue:
Can't boot after flashing zip with CM13 based.

**Comment by jcadduono** [comment]
you can either install a newer build from build.nethunter.com/nightly or wait for a new release to happen

**Comment by sino1641** [comment]
@jcadduono Thanks,dev.
Can't find the website above in wiki.
It needs to flash generic and kernel zips,right?

**Comment by sino1641** [comment]
@jcadduono 
Tried to flash kernel and generic zips into OPO but return error 1 when flashing generic zip.
/data and /cache are mounted as F2FS.

**Comment by seanwlk** [comment]
@sino1641 flash a stable rooted ROM and then install nethu term through the Nethunter app, it will do the job. I own a OnePlus One and I run COS 13.1.2 rooted (SuperSU 2.65 for compatibility with file manager ). The Nethunter app will install everything for you.

**Comment by jcadduono** [comment]
@sino1641 nothing i can do if you don't provide recovery log

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1

**Comment by sino1641** [comment]
It should be the problem about f2fs on /data and /system.
And it is totally OK now.
