### ISSUE TITLE
Missing NetHunter Terminal

### ISSUE THREAD

**Issue by cscholes982** [offensive-security/kali-nethunter#656]
### Device:
Samsung Galaxy S5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
CM13 Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
Built from repo on 5 Nov. 
sudo ./build.sh - m
sudo ./bootstrap.sh
sudo python build.py -d klte -m -roots minimal 

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@klte:/ # cat /proc/version
Linux version 3.4.0-nethunter-klte-eur-2.0 (jc@gallifrey) (gcc version 4.9.4 20151028 (prerelease) (Linaro GCC 4.9-2016.02) ) #1 SMP PREEMPT Sun Jul 17 14:21:48 EDT 2016
root@klte:/ #

## Issue:
The nethunter terminal doesn't install. It is in the zip file

**Comment by shezack** [comment]
Try downloading from 

https://build.nethunter.com/nightly/3.15.2-20161104-0105/nethunter-generic-armhf-kalifs-full-rolling-3.15.2-20161104-0105.zip

https://build.nethunter.com/nightly/3.15.2-20161104-0105/kernel-nethunter-klte-marshmallow-3.15.2-20161104-0105.zip

**Comment by cscholes982** [comment]
still dont have nethunter terminal

**Comment by jcadduono** [comment]
open adb, su, pm uninstall com.offsec.nhterm

flash update-nethunter zip (remove supersu.zip from it) again

this is due to signature changes
