### ISSUE TITLE
Camera not working.

### ISSUE THREAD

**Issue by shartlord** [offensive-security/kali-nethunter#657]
### Device:
Sprint Samsung Galaxy S5 (kltespr)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
CM13 latest nightly (marshmallow)

### Built from repo (date and build command) or downloaded from website (links):
kernel - 11/7/2016

## Issue:
Camera appears to be broken on all recent builds. Error displayed is:

Camera error
Can't connect to the camera.

Any idea how to fix/work around this? The camera works on the regular CM13 kernel.

**Comment by jcadduono** [comment]
i think i had an updated kernel somewhere but couldn't find anyone to test it at #nethunter on freenode irc

**Comment by shartlord** [comment]
I can give it a whirl if you need a test dummy.
