### ISSUE TITLE
Is SAMSUNG GALAXY NOTE 3 NEO(hl3g) supported for NEt Hunter

### ISSUE THREAD

**Issue by balramrexwal** [offensive-security/kali-nethunter#661]
### Device:
SAMSUNG Galaxy note 3 neo
SM-N750
hl3g
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
5.1.1

### Built from repo (date and build command) or downloaded from website (links):
stock rom

## Issue:
this device is Supportable or not.. with Exynos processer.

**Comment by bkr32** [comment]
no

**Comment by jcadduono** [comment]
it's supported if you add support for it ;)
