### ISSUE TITLE
Issue with DuckHunter HID and HID attacks (dont work) app usb keyboard work (Nexus 5X)

### ISSUE THREAD

**Issue by AkoibonHunter** [offensive-security/kali-nethunter#664]
### Device:

Nexus 5X (Bullhead)

### OS version (Marshmallow):

Return to factory kernel with last : https://developers.google.com/android/images?hl=en#bullhead
6.0.1 (MTC20K)  	4a950470af6c1e0111cfa8efbd77422928b88d01800dd2fadc6f8eeeae1b97a9
https://dl.google.com/dl/android/aosp/bullhead-mtc20k-factory-4a950470.zip

Command to return factory setti
with nethunter-LRT
**cp android/aosp/bullhead-mtc20k-factory-4a950470.zip ./nethunter-LRT-master/stockImage**
**./twrpFlash.sh**

### Downloaded from website (https://build.nethunter.com/nightly/3.15.2-20161110-0008/ ):

nethunter-generic-arm64-kalifs-minimal-rolling-3.15.2-20161110-0008.zip 
kernel-nethunter-bullhead-marshmallow-3.15.2-20161110-0008.zip

Command 
**fastboot flash recovery twrp-3.0.2-2-bullhead.img**
-> go recovery boot
**adb push nethunter-generic-arm64-kalifs-minimal-rolling-3.15.2-20161110-0008.zip  /sdcard**
-> reboot in normal boot
-> go reboot to revovery
**adb push kernel-nethunter-bullhead-marshmallow-3.15.2-20161110-0008.zip  /sdcard**
->  reboot in normal boot
-> nethunter app launch for first initialization

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.73-ElementalX-N5X-1.16 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #4 SMP PREEMPT Wed Aug 17 18:57:56 CDT 2016

## Issue:

The DuckHunter HID and HID attacks dont work.
When Run with button  |> say Launching Attack but no attack are performed.
Preview Panel say Loading wait 1second and show an empty page.

Debug info

The app usb keyboard work against Linux (Parrot) and Windows 8.1

root@kali:~# ls /dev/hi*
/dev/hidg0  /dev/hidg1

which hid-keyboard
/system/xbin/hid-keyboard
(in PATH)

root@kali:~# hid-keyboard | head
Usage: hid-keyboard devname mouse|keyboard|joystick
	keyboard options:
		hold
		left-ctrl
		right-ctrl
		left-shift
		right-shift
		left-alt
		right-alt
		left-meta
		right-meta

perform some request in dmesg

Additionaly Apache and SSH daemon dont work (no open port/no process with ps aux)

**Comment by jcadduono** [comment]
what is output of `echo h | hid-keyboard /dev/hidg0 keyboard`

**Comment by AkoibonHunter** [comment]
h

(this write h just here) but no output in terminal.

**Comment by AkoibonHunter** [comment]
hid-keyboard seems to work

**Comment by AkoibonHunter** [comment]
i copy the dmesg and syslog 
http://breizh-entropy.org/~akoibon/dmesg_android
http://breizh-entropy.org/~akoibon/syslog_android

**Comment by jcadduono** [comment]
if hid-keyboard works then it's an issue with your app, what nethunter app version?

**Comment by AkoibonHunter** [comment]
BusyBox Version ?
v1.25.0-Nethunter

**Comment by AkoibonHunter** [comment]
Version: 3.15.3

**Comment by AkoibonHunter** [comment]
where is the log of this app ?

**Comment by jcadduono** [comment]
use adb logcat while running hid attack

**Comment by AkoibonHunter** [comment]
There is no output when running DuckHunter HID or HID Attack

┌─[root@parrot]─[~]
└──╼ #adb logcat
- waiting for device -

In the HID Attack the Panel when i try Edit Source there is nothing here

**Comment by AkoibonHunter** [comment]
And when i press Update (just after Edit source) nethunter crash
with nethunter log perhaps we can see whats wrong here

**Comment by AkoibonHunter** [comment]
There is a lot of **avc: denied** for SELinux, its normal ?

**Comment by jcadduono** [comment]
you should be in selinux permissive so the avc denied should not mean anything to you (it should end with permissive=1)

also waiting for device means adb usb debugging isnt enabled on your phone

**Comment by AkoibonHunter** [comment]
i Run the attack twice and save last flood from adb XD 

ocket permissive=0
11-12 12:49:29.352  3271  3271 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{1779bbe V.ED..... ......ID 0,0-1080,628 #7f0e000a app:id/LatinkeyboardBaseView}
11-12 12:49:29.487   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
11-12 12:49:29.488   587  2791 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-12 12:49:29.503   587  2791 D audio_hw_primary: disable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:29.503   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
11-12 12:49:29.505   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0
11-12 12:49:31.916   587  2791 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-12 12:49:31.930   587  2791 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
11-12 12:49:31.931   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(101)
11-12 12:49:31.931   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1
11-12 12:49:31.937   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(71) acdb_id(102)
11-12 12:49:31.937   587  2791 D audio_hw_primary: enable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:31.938   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: spkr-vi-record
11-12 12:49:31.962   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(28) acdb_id(4)
11-12 12:49:31.963   587  2791 I ACDB-LOADER: ACDB AFE returned = -19
11-12 12:49:31.963   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
11-12 12:49:32.326  3401  3401 W Binder_6: type=1400 audit(0.0:3656): avc: denied { ioctl } for path="socket:[406426]" dev="sockfs" ino=406426 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:32.326  3401  3401 W Binder_6: type=1400 audit(0.0:3657): avc: denied { ioctl } for path="socket:[406426]" dev="sockfs" ino=406426 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:32.329  3271  3271 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{1779bbe V.ED..... ......ID 0,0-1080,628 #7f0e000a app:id/LatinkeyboardBaseView}
11-12 12:49:32.483   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
11-12 12:49:32.485   587  2791 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-12 12:49:32.504   587  2791 D audio_hw_primary: disable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:32.505   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
11-12 12:49:32.507   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0
11-12 12:49:36.800  2708  2708 W Binder_3: type=1400 audit(0.0:3658): avc: denied { ioctl } for path="socket:[408343]" dev="sockfs" ino=408343 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:36.800  2708  2708 W Binder_3: type=1400 audit(0.0:3659): avc: denied { ioctl } for path="socket:[408343]" dev="sockfs" ino=408343 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:37.940   587  2791 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-12 12:49:37.954   587  2791 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
11-12 12:49:37.955   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(101)
11-12 12:49:37.955   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1
11-12 12:49:37.958  3271  3271 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{1779bbe V.ED..... ......ID 0,0-1080,628 #7f0e000a app:id/LatinkeyboardBaseView}
11-12 12:49:37.953  3402  3402 W Binder_7: type=1400 audit(0.0:3660): avc: denied { ioctl } for path="socket:[406426]" dev="sockfs" ino=406426 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:37.953  3402  3402 W Binder_7: type=1400 audit(0.0:3661): avc: denied { ioctl } for path="socket:[406426]" dev="sockfs" ino=406426 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:37.961   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(71) acdb_id(102)
11-12 12:49:37.962   587  2791 D audio_hw_primary: enable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:37.962   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: spkr-vi-record
11-12 12:49:37.970  6588  6588 W Binder_C: type=1400 audit(0.0:3662): avc: denied { ioctl } for path="socket:[406426]" dev="sockfs" ino=406426 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:37.970  6588  6588 W Binder_C: type=1400 audit(0.0:3663): avc: denied { ioctl } for path="socket:[406426]" dev="sockfs" ino=406426 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:37.972  3271  3271 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{1779bbe V.ED..... ......ID 0,0-1080,628 #7f0e000a app:id/LatinkeyboardBaseView}
11-12 12:49:37.991   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(28) acdb_id(4)
11-12 12:49:37.991   587  2791 I ACDB-LOADER: ACDB AFE returned = -19
11-12 12:49:37.992   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
11-12 12:49:38.284 17193 17220 D OpenGLRenderer: endAllStagingAnimators on 0x7f84d55000 (ListPopupWindow$DropDownListView) with handle 0x7f9650dbe0
11-12 12:49:38.513   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
11-12 12:49:38.514   587  2791 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-12 12:49:38.530   587  2791 D audio_hw_primary: disable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:38.530   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
11-12 12:49:38.533   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0
11-12 12:49:45.462   996  2766 D WifiStateMachine: starting scan for "Bbox-745BE883"WPA_PSK with 2412
11-12 12:49:46.753   587  2791 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-12 12:49:46.767 17193 17285 D LANGGG  : us
11-12 12:49:46.768   587  2791 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
11-12 12:49:46.769   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(101)
11-12 12:49:46.770   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1
11-12 12:49:46.777   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(71) acdb_id(102)
11-12 12:49:46.777   587  2791 D audio_hw_primary: enable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:46.778   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: spkr-vi-record
11-12 12:49:46.783  3402  3402 W Binder_7: type=1400 audit(0.0:3664): avc: denied { ioctl } for path="socket:[406501]" dev="sockfs" ino=406501 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:46.783  3402  3402 W Binder_7: type=1400 audit(0.0:3665): avc: denied { ioctl } for path="socket:[406501]" dev="sockfs" ino=406501 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:46.804   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(28) acdb_id(4)
11-12 12:49:46.805   587  2791 I ACDB-LOADER: ACDB AFE returned = -19
11-12 12:49:46.805   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
11-12 12:49:46.820 17193 17220 V RenderScript: 0x7f84cbd000 Launching thread(s), CPUs 6
11-12 12:49:47.178 17299 17299 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-12 12:49:47.182 17299 17299 D AndroidRuntime: CheckJNI is OFF
11-12 12:49:47.183 17299 17299 W app_process: type=1400 audit(0.0:3666): avc: denied { write } for name="system@framework@boot.art" dev="dm-0" ino=32711 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
11-12 12:49:47.209 17299 17299 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-12 12:49:47.213 17299 17299 W main    : type=1400 audit(0.0:3667): avc: denied { write } for name="arm64" dev="dm-0" ino=32710 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
11-12 12:49:47.236 17299 17299 I Radio-JNI: register_android_hardware_Radio DONE
11-12 12:49:47.252 17299 17299 D AndroidRuntime: Calling main entry com.android.commands.am.Am
11-12 12:49:47.250 17329 17329 W main    : type=1400 audit(0.0:3668): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:49:47.250 17329 17329 W main    : type=1400 audit(0.0:3669): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:49:47.250 17329 17329 W main    : type=1400 audit(0.0:3670): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:49:47.270 17299 17299 D AndroidRuntime: Shutting down VM
11-12 12:49:47.318   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
11-12 12:49:47.319   587  2791 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-12 12:49:47.333   587  2791 D audio_hw_primary: disable_snd_device: snd_device(71: vi-feedback)
11-12 12:49:47.333   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
11-12 12:49:47.339   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0
11-12 12:49:48.793 17193 17285 D DuckHunterFragment: su -c '/data/data/com.offsec.nethunter/files/scripts/bootkali duck-hunt-run /opt/duckout.sh'
11-12 12:49:48.846  1007  1007 W Binder_2: type=1400 audit(0.0:3671): avc: denied { ioctl } for path="socket:[407280]" dev="sockfs" ino=407280 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:48.846  1007  1007 W Binder_2: type=1400 audit(0.0:3672): avc: denied { ioctl } for path="socket:[407280]" dev="sockfs" ino=407280 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:49:49.230 17339 17339 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-12 12:49:49.234 17339 17339 D AndroidRuntime: CheckJNI is OFF
11-12 12:49:49.233 17339 17339 W app_process: type=1400 audit(0.0:3673): avc: denied { write } for name="system@framework@boot.art" dev="dm-0" ino=32711 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
11-12 12:49:49.259 17339 17339 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-12 12:49:49.263 17339 17339 W main    : type=1400 audit(0.0:3674): avc: denied { write } for name="arm64" dev="dm-0" ino=32710 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
11-12 12:49:49.286 17339 17339 I Radio-JNI: register_android_hardware_Radio DONE
11-12 12:49:49.303 17339 17339 D AndroidRuntime: Calling main entry com.android.commands.am.Am
11-12 12:49:49.300 17368 17368 W main    : type=1400 audit(0.0:3675): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:49:49.300 17368 17368 W main    : type=1400 audit(0.0:3676): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:49:49.300 17368 17368 W main    : type=1400 audit(0.0:3677): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:49:49.335 17339 17339 D AndroidRuntime: Shutting down VM
11-12 12:50:01.278   587  2791 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-12 12:50:01.287 17193 17379 D LANGGG  : us
11-12 12:50:01.292   587  2791 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
11-12 12:50:01.292   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(101)
11-12 12:50:01.293   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1
11-12 12:50:01.299   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(71) acdb_id(102)
11-12 12:50:01.300   587  2791 D audio_hw_primary: enable_snd_device: snd_device(71: vi-feedback)
11-12 12:50:01.300   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: spkr-vi-record
11-12 12:50:01.310  3401  3401 W Binder_6: type=1400 audit(0.0:3678): avc: denied { ioctl } for path="socket:[409938]" dev="sockfs" ino=409938 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:50:01.310  3401  3401 W Binder_6: type=1400 audit(0.0:3679): avc: denied { ioctl } for path="socket:[409938]" dev="sockfs" ino=409938 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:50:01.326   587  2791 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(28) acdb_id(4)
11-12 12:50:01.327   587  2791 I ACDB-LOADER: ACDB AFE returned = -19
11-12 12:50:01.327   587  2791 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
11-12 12:50:01.712 17387 17387 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-12 12:50:01.715 17387 17387 D AndroidRuntime: CheckJNI is OFF
11-12 12:50:01.716 17387 17387 W app_process: type=1400 audit(0.0:3680): avc: denied { write } for name="system@framework@boot.art" dev="dm-0" ino=32711 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
11-12 12:50:01.742 17387 17387 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-12 12:50:01.746 17387 17387 W main    : type=1400 audit(0.0:3681): avc: denied { write } for name="arm64" dev="dm-0" ino=32710 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
11-12 12:50:01.771 17387 17387 I Radio-JNI: register_android_hardware_Radio DONE
11-12 12:50:01.788 17387 17387 D AndroidRuntime: Calling main entry com.android.commands.am.Am
11-12 12:50:01.786 17417 17417 W main    : type=1400 audit(0.0:3682): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:50:01.786 17417 17417 W main    : type=1400 audit(0.0:3683): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:50:01.786 17417 17417 W main    : type=1400 audit(0.0:3684): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:50:01.801 17387 17387 D AndroidRuntime: Shutting down VM
11-12 12:50:01.856   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
11-12 12:50:01.857   587  2791 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-12 12:50:01.873   587  2791 D audio_hw_primary: disable_snd_device: snd_device(71: vi-feedback)
11-12 12:50:01.874   587  2791 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
11-12 12:50:01.876   587  2791 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0
11-12 12:50:03.300  3402  3402 W Binder_7: type=1400 audit(0.0:3685): avc: denied { ioctl } for path="socket:[408848]" dev="sockfs" ino=408848 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:50:03.303  3402  3402 W Binder_7: type=1400 audit(0.0:3686): avc: denied { ioctl } for path="socket:[408848]" dev="sockfs" ino=408848 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:50:03.317 17193 17379 D DuckHunterFragment: su -c '/data/data/com.offsec.nethunter/files/scripts/bootkali duck-hunt-run /opt/duckout.sh'
11-12 12:50:03.706 17426 17426 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-12 12:50:03.710 17426 17426 D AndroidRuntime: CheckJNI is OFF
11-12 12:50:03.710 17426 17426 W app_process: type=1400 audit(0.0:3687): avc: denied { write } for name="system@framework@boot.art" dev="dm-0" ino=32711 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
11-12 12:50:03.736 17426 17426 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-12 12:50:03.740 17426 17426 W main    : type=1400 audit(0.0:3688): avc: denied { write } for name="arm64" dev="dm-0" ino=32710 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
11-12 12:50:03.762 17426 17426 I Radio-JNI: register_android_hardware_Radio DONE
11-12 12:50:03.778 17426 17426 D AndroidRuntime: Calling main entry com.android.commands.am.Am
11-12 12:50:03.776 17455 17455 W main    : type=1400 audit(0.0:3689): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:50:03.776 17455 17455 W main    : type=1400 audit(0.0:3690): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:50:03.776 17455 17455 W main    : type=1400 audit(0.0:3691): avc: denied { dac_override } for capability=1 scontext=u:r:shell:s0 tcontext=u:r:shell:s0 tclass=capability permissive=0
11-12 12:50:03.801 17426 17426 D AndroidRuntime: Shutting down VM
11-12 12:50:05.296  6588  6588 W Binder_C: type=1400 audit(0.0:3692): avc: denied { ioctl } for path="socket:[408892]" dev="sockfs" ino=408892 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
11-12 12:50:05.296  6588  6588 W Binder_C: type=1400 audit(0.0:3693): avc: denied { ioctl } for path="socket:[408892]" dev="sockfs" ino=408892 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

**Comment by jcadduono** [comment]
okay yeah you're in selinux enforcing that's why it's not working, no policies in effect for /dev/hidg* writes

you need to set selinux to permissive first

**Comment by AkoibonHunter** [comment]
hey 
I try to have the permissive mode but i fail, i try from ANDROID SU terminal:
setenforce 0
setenforce permissive
echo 0 > /sys/fs/selinux/enforce

but **getenforce** say always -> Enforcing
cat /sys/fs/selinux/enforce -> is always 1

And with KALI terminal there is not the binary find with find (when i try to use the /system/bin/getenforce) -> No suche file or directory.

Do you know some tricks to disable SElinux ?

**Comment by AkoibonHunter** [comment]
I try also 
$ adb shell su root setenforce 0
but with no effect

**Comment by jcadduono** [comment]
yes there might have been policy adjustments in ur android version where only init can set enforce value.... might need to add a patch.d file to write on boot setenforce 0 to init.nethunter.rc

**Comment by AkoibonHunter** [comment]
i didnt see your reply. i try that. i dont know actually whats is init.nethunter.rc but i will discover that :)

**Comment by AkoibonHunter** [comment]
hey, i dont succeed to modify the init.nethunter.rc (the original come back after a reboot)
I will follow this tutorial  next  try - http://stackoverflow.com/questions/9768103/make-persistent-changes-to-init-rc

i do that
the / rootfs was readonly, so i do
**adb shell su root mount -o remount,rw /**

do that for !safety!
**adb shell su root cp init.nethunter.rc init.nethunter.rc.old**

and replace with a text editor
```
# Execute files in /system/etc/init.d near the end of the boot sequence
on boot
    start run-parts
```
by this ->
```
# Execute files in /system/etc/init.d near the end of the boot sequence
on boot
    start run-parts
    setenforce 0
```

**Comment by jcadduono** [comment]
i meant add a file to patch.d in device folder, ex.
`devices/marshmallow/bullhead/patch.d/05-permissive`:
```
#!/sbin/sh

. "$env"

cat << EOF >> init.nethunter.rc

on boot
    setenforce 0
EOF

exit 0
```

that would do er

**Comment by AkoibonHunter** [comment]
hello,
i dont succeed at all   :-1: 

I follow this tutorial - https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter
I do that : 
**root@kali:~# git clone https://github.com/offensive-security/kali-nethunter
root@kali:~# cd kali-nethunter/nethunter-installer
./bootstrap.sh (with all version and exotic)**

i create the folder **patch.d** and edit a **05-permissive** file
_./devices/marshmallow/bullhead/patch.d
./devices/marshmallow/bullhead/patch.d/05-permissive_

┌─[✗]─[root@parrot]─[~/Documents/android/nethunter/kali-nethunter/nethunter-installer]
└──╼ #cat ./devices/marshmallow/bullhead/patch.d/05-permissive
```
#!/sbin/sh

. "$env"

cat << EOF >> init.nethunter.rc

on boot
    setenforce 0
EOF

exit 0
```

**BUILD nethunter-installer**
└──╼ #python build.py --device bullhead --marshmallow --rootfs minimal

**Reboot** in recovery mode, push that with **adb push**  and **install** it with twrp

Im still in Enforcing mode so i decide to change the kernel

**BUILD kernel**
└──╼ #python build.py --device bullhead --marshmallow --rootfs minimal --kernel

**Reboot** in recovery mode, push that with **adb push**  and **install** it with twrp

And i restart boot loader, and **Reboot** in recovery mode, push that with **adb push**  and **install** it with twrp

getenforce is Enforcing and the android envirronment is the same, i have the app run just before still alive in same state.

When you say _"flash"_ its something with fastboot flash boot xxxxxx ??

by+
```
                                                     ___ 
                                                  ,o88888 
                                               ,o8888888' 
                         ,:o:o:oooo.        ,8O88Pd8888" 
                     ,.::.::o:ooooOoOoO. ,oO8O8Pd888'" 
                   ,.:.::o:ooOoOoOO8O8OOo.8OOPd8O8O" 
                  , ..:.::o:ooOoOOOO8OOOOo.FdO8O8" 
                 , ..:.::o:ooOoOO8O888O8O,COCOO" 
                , . ..:.::o:ooOoOOOO8OOOOCOCO" 
                 . ..:.::o:ooOoOoOO8O8OCCCC"o 
                    . ..:.::o:ooooOoCoCCC"o:o 
                    . ..:.::o:o:,cooooCo"oo:o: 
                 `   . . ..:.:cocoooo"'o:o:::' 
                 .`   . ..::ccccoc"'o:o:o:::' 
                :.:.    ,c:cccc"':.:.:.:.:.' 
              ..:.:"'`::::c:"'..:.:.:.:.:.' 
            ...:.'.:.::::"'    . . . . .' 
           .. . ....:."' `   .  . . '' 
         . . . ...."' 
         .. . ."'           
```
        .

**Comment by AkoibonHunter** [comment]
i succeed to apply patch. i see init.nethunter.rc modify with my line (on boot setenforce 0)
but im still in enforcing.

**Comment by AkoibonHunter** [comment]
Well done !
THe HID attack works now, i use full-rooling instead of the minimal ...
The new build enabled that (no use of ram to unzip the 895M)

So bug is defeated by this :: 
https://build.nethunter.com/nightly/3.15.2-20161116-1730/
nethunter-generic-arm64-kalifs-full-rolling-3.15.2-20161116-1730.zip    +   kernel-nethunter-bullhead-marshmallow-3.15.2-20161116-1730.zip

Thk jcadduono
