### ISSUE TITLE
Wireless adapter not being recognized

### ISSUE THREAD

**Issue by Star3161** [offensive-security/kali-nethunter#666]
### Device:
Galaxy S7 (G930FD)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
kernel-nethunter-herolte-marshmallow-3.15.2-20161110-0008

## Issue:
When I plug in my wireless adapter (Panda PAU05) it does not show up in 'iwconfig' and 'ifconfig wlan1' but I know it is detected as whenever i plug it in the screen turns on.

**Comment by jcadduono** [comment]
you're not using nethunter kernel
