### ISSUE TITLE
Possible implementation / Poisontap

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#669]
Just a thought, maybe worth adding to Nethunter.

Siphons cookies, exposes internal router & installs web backdoor on locked computers

https://samy.pl/poisontap

https://github.com/samyk/poisontap

**Comment by simonpunk** [comment]
I was about to open the same issue too but your one step ahead of me..

Anyway, seems the first issue would be how to make our nethunter device recognised by Mac OS, as the script only works on window, and I have tried to modify by myself but no luck.

**Comment by bkr32** [comment]
we have a similar implementation called mubix-lock already

**Comment by simonpunk** [comment]
But what device should we enum if the target Mac OS doesn't have the rndis driver installed as mentioned by this website: http://joshuawise.com/horndis, "Mac OS X supports only CDC Ethernet devices out of the box."

so is there any way we can enum a CDC Ethernet device?
seems we would need to use usb0 function instead of rndis.

**Comment by bkr32** [comment]
I don't have a Mac so I can't really comment

**Comment by akrolla** [comment]
I think we would need to use a usb to ethernet adapter to do this, I may be wrong, but it seems to work like the LAN turtle which is an ethernet adapter. It also rewuires one on the pi board.

**Comment by simonpunk** [comment]
any news, guys?? I just get back to try find out which usb state I should enum, and luckily I tried it out, its ncm function, when I turn my usb state into ncm&hid, my mac book air finally recognized, as long as I do "ifconfig ncm0 up" and configure the dhcp stuff, My mac start requesting ip from my device. But!! it never gets a working ip address, it always gets a ip like 169.254.xxx.xxx with netmask 255.255.0.0 no matter how I tried to configure the dhcp options, so is there anyone wants to sort it out?? I actually writing a simple script to perform the all the usb attack as the bashbunny does against both Win and Mac, but what is left now is how to assign a ip address to a Mac machine. @jcadduono @binkybear
