### ISSUE TITLE
Hardware Compatibility Request

### ISSUE THREAD

**Issue by lcfut** [offensive-security/kali-nethunter#671]
### Device:

Samsung Galaxy S6 Edge +
Model SM-G9287

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow and/or Nougat

### Built from repo (date and build command) or downloaded from website (links):

Request for additional hardware compatibility

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

N/A

## Issue:
Hardware compatibility request

**Comment by jcadduono** [comment]
i tried to support this device at one point but the universal7420 devices have a very small boot partition and even with most options set to kernel module it's hard to fit the kernel image in the partition.
it might be easier now though if someone wants to give it a try. by supporting S6e+ it's very similar to S6, S6e, and Note 5 so you'd likely be able to support all of them with slight kernel config tweaks, although that would be a ton of builds.
