### ISSUE TITLE
Nexus 9 and OTG USB adapter compatibility

### ISSUE THREAD

**Issue by lcfut** [offensive-security/kali-nethunter#672]
### Device:

Nexus 9 (flounder)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow 6.0.1

### Built from repo (date and build command) or downloaded from website (links):

Downloaded from https://www.offensive-security.com/kali-linux-nethunter-download/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40-g6857980-dirty (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Sat Nov 28 06:32:48 UTC 2015

## Issue:
Nexus 9 running NetHunter 3.0 and having an issue with OTG wireless adapters.  When I run 'lsusb' I can see the RTL8187 Alpha adapter as well as the RTL8188CUS Edimax adapter.  However, the only adapter that will work with 'kismet' or 'wifite' is the Alpha adapter

**Comment by jcadduono** [comment]
no lsusb output, no way for us to know your hardware/vendor id and fix kernel

**Comment by lcfut** [comment]
Lsusb output
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by jcadduono** [comment]
is it showing in iwconfig ?

remember, you need to use the enable monitor mode command in nethunter app to turn cards on for that app

**Comment by lcfut** [comment]
So here is what I have done which is the confusing part.

1. Insert OTG adapter with Edimax Wifi
2. Boot Nexus 9
3. Launch Nethunter app
4. Launch kali terminal
5. Run ifconfig and iwconfig - wlan1 does not appear in either list
6. Run lsusb - Edimax adapter appears in the list
7. Run wifite command and only wlan0 is identifed - kill wifite command and return to terminal
8. Unplug OTG adapter and Edimax removed
9. Attach Alfa AWUS036H adapter to OTG adapter and attach to Nexus 9
10. Run ifconfig and iwconfig - wlan1 does not appear in either list
11. Run wifite command - prompted to select either wlan0 or wlan1 (alpha) in monitor mode

Why does the Alpha adapter work simply by attaching it to the Nexus 9 tablet, and the Edimax adapter does not?  I am not running any special commands to extra clicks anywhere on the Nexus 9.  Simply plug it in and it works.
![screenshot_20161215-133114](https://cloud.githubusercontent.com/assets/95530/21237204/f96be944-c2cb-11e6-94fa-17c2c208c47d.png)

**Comment by maetreya** [comment]
before plugging in my wireless adapter i like to use the command 

iw wlan0 del 

then once i plug in my wireless adapter i only have the wlan0 interface of my alfa adapter so that when i put into monitor mode with airmon-ng and start wifite i have no problems

**Comment by 0E800** [comment]
@svdvmxwl 

Possibly related, from: https://www.raspberrypi.org/forums/viewtopic.php?t=61665

````
MrEngman wrote:
Try this. Make a file 8192cu.conf in directory /etc/modprobe.d/ with the command

Code: Select all

sudo nano /etc/modprobe.d/8192cu.conf

and add the following lines

Code: Select all

# Disable power management
options 8192cu rtw_power_mgnt=0 rtw_enusbss=0

I'm assuming you are using the Edimax EW-7811Un


MrEngman
````

**Comment by 0E800** [comment]
@svdvmxwl 

These links might also be useful to review:

https://askubuntu.com/questions/509498/is-there-a-standard-wifi-driver-for-the-edimax-ew-7811un/612662

https://forum.odroid.com/viewtopic.php?f=117&t=9359

**Comment by svdvmxwl** [comment]
@0E800 hi, I tried this power msnagement option  change.  it didn't work.
