### ISSUE TITLE
mubix nexus 5

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#674]
### Device:

nexus5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

lollipop

### Built from repo (date and build command) or downloaded from website (links):

kali.org

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

linux 3.4.0-g12d78b6-dirty

## Issue:

how to add the mubix.sh and how to get it to appear in the nethunter APK?

**Comment by akrolla** [comment]
i retract my last question..

**Comment by bkr32** [comment]
you have to run it via terminal or make a custom command to launch it from the app

**Comment by akrolla** [comment]
How

**Comment by akrolla** [comment]
How do I setup the script its not included on nwxus 5

**Comment by akrolla** [comment]
More importanly where?

**Comment by pyc0de** [comment]
Nethunter App > Custom Commands > Add Command

**Comment by akrolla** [comment]
what  is the bash script? Its not located on thenexus 5 variant

**Comment by akrolla** [comment]
I know I need tto do that I just sont know where they posted the code on
here

**Comment by akrolla** [comment]
I have the 3.4 kernel isn't there a new apk for the 3.4 kernel or something. Like that?
