### ISSUE TITLE
Anyone wants to port this over to nethunter?

### ISSUE THREAD

**Issue by phr34k0** [offensive-security/kali-nethunter#676]
Looks pretty sweet https://samy.pl/poisontap/

**Comment by bkr32** [comment]
https://github.com/offensive-security/kali-nethunter/issues/669
https://github.com/offensive-security/kali-nethunter/issues/649

**Comment by binkybear** [comment]
Already a few issues open (bkr32) and I'm working on it.

**Comment by akrolla** [comment]
Trendnet ethernet adapters work well with kali
