### ISSUE TITLE
Use Remix OS

### ISSUE THREAD

**Issue by GabrielTK** [offensive-security/kali-nethunter#678]
### Device:
Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

## Issue:
Well, this is Just a suggestion. Why don't you guys use Remix OS in devices such as Nexus 9?? It would allow a better experience with multitasking, and it can be fully rooted with the latest Magisk

**Comment by bkr32** [comment]
RemixOS is as the title suggests a OS right now nethunter is a collection of tools that allow you to pentest on top of your existing ROM,
nOS is in development but will most likely be based on aosp or cm

**Comment by akrolla** [comment]
More than likely cm based upon the flexibility and usability and the large support base

**Comment by Zarkopafilis** [comment]
Remix OS is based on CM and other ROMs. It's just the same thing with extra customizability. This is pentest tools, not how to make your status bar change rainbow colors...

lineageOS is probably going to be supported next, now that CM broke down

**Comment by Zarkopafilis** [comment]
Well, looks like that they updated their website and will be continuing the updates in the next week https://status.lineageos.org/ . It's just CM after it's abandonment; I guess only some handles need to change and nethunter is good to go.
