### ISSUE TITLE
Nethunter 3 + Nexus 5 + TL-WN722N = no device & modprobe problems 

### ISSUE THREAD

**Issue by MrBlackMagic** [offensive-security/kali-nethunter#679]
Hello

Android Version= 6.0.0 MRA58K
Installed = nethunter-hammerhead-marshmallow-3.0
(with twrp stucked at 90%, after a lot of time i forced a reboot but it seemed to be installed even if it never compleats 100%; I had to add "http://old.kali.org/kali" in /etc/apt/sources.list to get update&upgrade run)

Updated to Nethunter 3.15

I tried plug & and play with the TP-LINK TL-WN722N (used two different OTG cables no Y):
Could not find it with "iwconfig" and could not start it with "ifconfig wlan1 up":
"No such device"

It is shown in lsusb:
https://postimg.org/image/kw5j3xwrp/

dmesg:
https://postimg.org/image/98g2n4x0l/

i tried "apt-get install firmware-atheros" which runned without errors but did not fix anything.

i tried to load driver manually but something seems to be wrong with modprobe:
https://postimg.org/image/9z8sswzdx/

Also lsmod failed:
https://postimg.org/image/mf5imnspx/

Any ideas ?

**Comment by jcadduono** [comment]
there is a good reason we have an issue template

this is hammerhead marshmallow kernel:
`Linux version 3.4.0-g5e6aa13 (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Sat Apr 2 20:23:25 CDT 2016`

this is you: https://postimg.org/image/9z8sswzdx/
