### ISSUE TITLE
Duckhunter HID blocked by endpoint security

### ISSUE THREAD

**Issue by marcdjay** [offensive-security/kali-nethunter#680]
Hi all,

More a question than an issue / bug report. I've confirmed that Duckhunter HID and the HID Keyboard are working, however when trying to run a Duckhunter attack against a computer with endpoint security that blocks mass storage devices (but not HID) then the phone is blocked as soon as it is plugged in.

Is there a way to make the software believe that the phone is a USB HID rather than a mobile phone / mass storage device when it is connected to the target?

**Comment by jcadduono** [comment]
depends on the device, on some with my patch you're able to run in terminal
`setprop sys.usb.config hid`
but with the vanilla hid patch you could run into null pointer deref on config which could crash your phone

if it succeeds though it will set your vendor/product ids to usb keyboard only
on some devices you may need to reboot to change vendor/product ids back though

**Comment by marcdjay** [comment]
Thanks, I'll give that a go tonight when I have time to debug, or rebuild my phone if needed.

I'm using the 3.15.3 20161126-1805 (I think or the one before it) on a Galaxy S5 on CM13 so I'll keep you posted with it

**Comment by marcdjay** [comment]
Update: entering setprop sys.usb.config hid worked and I was able to bypass the endpoint protection and launch an attack. Is it possible to change to the vendor/product ID's back without rebooting, and do you know off hand where/how I can find them?

Thank you

**Comment by jcadduono** [comment]
In most devices just use `setprop sys.usb.config mtp,adb`
That will put it in mtp with adb mode and return to your manufacturer vendor/prod ids
If your device doesnt use id switching though you would have to set sys.usb.config to none and manually echo ids to the USB vendor and product id sys fs nodes... See /init.usb.rc

**Comment by jmingov** [comment]
This could be very handy in the app... a screen to change the system props...
