### ISSUE TITLE
Terminal app crashes when I click kali

### ISSUE THREAD

**Issue by GabrielTK** [offensive-security/kali-nethunter#681]
### Device:

Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

[Website](https://images.offensive-security.com/nethunter-release/nethunter-flounder-marshmallow-3.0.zip)
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

10081@flounder:/ $ cat /proc/version
Linux version 3.10.40-g6857980-dirty (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Sat Nov 28 06:32:48 UTC 2015

## Issue:
When I click Kali in the terminal app, it crashes.
Also, bootkali isn't in the path, and, after install, I had to manually install BusyBox. I think my /system was not modified during install. Also, I got some weired errors after install was finished:

![img_20161128_013257](https://cloud.githubusercontent.com/assets/11809449/20685788/03b972d6-b59d-11e6-92ec-7e40b8efe4e9.jpg)

**Comment by GabrielTK** [comment]
Note: The strange error also happens when I try to decrypt storage from TWRP. Also, the boot Animation remains the Marshmallow one.

**Comment by binkybear** [comment]
The error (screenshot) above is unrelated to any issue you are having with terminal.  It was a known TWRP issue.

As far as the terminal crashing its possible that your chroot didn't install all the way.  From the NH app try removing chroot and dowloading new one through app then running it again.

**Comment by GabrielTK** [comment]
Oops, I flashed stock firmware and now I'm flashing Nethunter again. It's booting. If I still get the problem, I'm going to try this. Thank you  @binkybear

Em 28 de nov de 2016 9:10 PM, "binkybear" <notifications@github.com<mailto:notifications@github.com>> escreveu:

The error (screenshot) above is unrelated to any issue you are having with terminal. It was a known TWRP issue.

As far as the terminal crashing its possible that your chroot didn't install all the way. From the NH app try removing chroot and dowloading new one through app then running it again.

**Comment by GabrielTK** [comment]
Just a little question: Can I put a password and ask for it on boot after installation succeeded?? Also, Is there anyway to restore the standard boot animation??

**Comment by bkr32** [comment]
you can always reflash bootanimation as for the password you can set it in security settings like all android phones

**Comment by Silur** [comment]
I've got the same error, the terminal app (and also adb `bootkali` command) output is: `Missing a required folder. Something isn't right`. There is no java exception, the trace dives right into ARM assembly.

**Comment by tequillasun** [comment]
Try using busybox paid ver and install into system/bin not xbin

**Comment by clavodestiriouso** [comment]
same Missing a required folder. Something isn't right
