### ISSUE TITLE
How to install this in OP3

### ISSUE THREAD

**Issue by mastermind860** [offensive-security/kali-nethunter#683]
### Device:
Oneplus 3

Hello, im new into android rooting and stuffs like this. I have a oneplus 3 and i want to know how to install nethunter in op3. Many are saying that i have to install a kernel and the links for the kernels are outdated(idlekernal website is not even opening). Please guide me through the installation.

**Comment by rob070511** [comment]
If your phone is rooted, find the kernel and rom for your device and flash
them from this URL https://build.nethunter.com/nightly/3.15.3-20161129-1413/

Then go on setting about device and check the kernel has been installed. If
not flash again and then open the nethunter app to finish installation. If
your phone is not rooted follow the steps on Xda to achieve this for your
device.  Then follow above steps.

**Comment by mastermind860** [comment]
When should we root our device? Before flashing kernel or after flashing kernel? I have got a latest version of kenel from this url https://build.nethunter.com/nightly/3.15.2-20161104-0105/. Which one should i flash. Did you got any bootloop while doing this?

**Comment by rob070511** [comment]
Get the Kernel and arm64 generic version off of the link I supplied it's
more up to date.  Also root your device before you flash them both, and no
you shouldn't experience any bootloop.

**Comment by jcadduono** [comment]
don't root your device before flashing them, nethunter-generic zip roots your device for you, if you double root you will probably lose the kernel and have to flash that again too

**Comment by mastermind860** [comment]
There are 4 files for arm64. Could you please mention which one i should download? My os version is Oxygen Os 3.2.7. please dont think that im questioning your knowledge, i'm a noob that why im asking these questions. I saw one other thread where one guy told people to install https://build.nethunter.com/nightly/3.15.2-20161104-0105/ this version. he also mentioned that all the problems are resolved in this version also. So what are the main difference between these two? Is it okay if i install 1104-0105 ?

**Comment by mastermind860** [comment]
https://github.com/offensive-security/kali-nethunter/issues/653#issuecomment-263695065

This is the comment that i have mentioned above

**Comment by mastermind860** [comment]
@jcadduono so, are you saying that first we need to install twrp then kernel and then generic arm64 ?

**Comment by rob070511** [comment]
The post you are mentioning is 18 days old, as such there's a newer version
of the software available which I've linked to you.  Although it's really
up to you what one you install.  The other one should work fine. The
correct Arm64 version also depends on you,  I'd recommend this one.

https://build.nethunter.com/nightly/3.15.3-20161129-1413/nethunter-generic-arm64-kalifs-full-rolling-3.15.3-20161129-1413.zip

**Comment by mastermind860** [comment]
So aftwr installing this generic arm 64, do i need to download and install kali nethunter zip and flash again?? Or till flashing generic arm 64 is enough?

**Comment by mastermind860** [comment]
Have to tested this in OP3 ? all the options are working or not working??

**Comment by jcadduono** [comment]
read the wiki, if you can't, then chances are you won't be able to figure out anything and this isn't the kind of thing you want to install

**Comment by mastermind860** [comment]
@jcadduono @rob070511 
Hello guys. Thank you so much for your help. Now i got kali nethunter installed on my oneplus 3 with out any issue and all the attacks are working fine.No system lagging.
