### ISSUE TITLE
Bugs In Oneplus 3

### ISSUE THREAD

**Issue by mastermind860** [offensive-security/kali-nethunter#686]
### Device:
Oneplus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.18.20-ElementalX-OP3-0.15 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #5 SMP PREEMPT Mon Nov 21 17:40:25 CST 2016                    root@kali:~#

## Issue:
1) Ztether wont work when using Zanti
2) Wifi & Hostspot wont work sometime (a reboot will fix this)
3) Wireshark showing "Error while receiving by ADB for<000Ehost:devices-l>

Please suggest me a working otg y cabel to use with my OP3. I have Tp Link TL-WN823N which i believe that it will work with my OP3. This TL-WN823N is a small device, so should i use otg y cable or simply an OTG cable?

**Comment by mastermind860** [comment]
https://github.com/pelya/android-keyboard-gadget
Can i use this kernel to make usb keyboard work? Bcoz whenever i open usb keyboard, it is promoting me to install this kernel. Is it safe to install??

**Comment by mastermind860** [comment]
Usb keyboard application which is pre installed with nethunter is asking me to compile and install a kernel from www.github.com/pelya/android-keyboard-gadget.

**Comment by Zarkopafilis** [comment]
I can verify that zAnti works with a proper wifi card, unless you try to use it over https.
Also, wifi and hotspot works unless you mess around with wlanN interfaces in a wrong way, and not safely plugging out wlan1 (e.g. without ifconfig wlan1 down).

**Comment by mastermind860** [comment]
@Zarkopafillis
I tried ztether with the inbuilt wifi adapter of my phone. That might be the case. Which android veraion are u using now?

**Comment by Zarkopafilis** [comment]
@mastermind860 I use cm 12.1 , it's more stable imo

**Comment by qintian19880103** [comment]
hi:
 My cell phone is plus one 3t. After I replaced nethunter system，external network card and usb device can't be identified.  it shows unable to initialize libusb: - 99 after performing lsusb.  wireless network card is TL - WN722N 
USB cable is type - c to otg
