### ISSUE TITLE
DuckHunter: ENTER always sent following STRING

### ISSUE THREAD

**Issue by strixdio** [offensive-security/kali-nethunter#687]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Stock Marshmallow 6.0.1

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.3-20161121-2039/
kernel-nethunter-hammerhead-marshmallow-3.15.3-20161121-2039.zip
update-nethunter-generic-armhf-3.15.3-20161121-2039.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-g5e6aa13 (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Sat Apr 2 20:23:25 CDT 2016

## Issue:
Every "STRING" command automatically sends "ENTER" after the string is sent. I'm not sure if this is expected behavior as I am new to DuckHunter, but I don't see why this would be as it may not always be desirable.

**Comment by nethunteros** [comment]
https://github.com/offensive-security/nethunter-app/blob/master/assets/nh_files/modules/duckhunter.py#L210 <-- Use TEXT instead

**Comment by strixdio** [comment]
Ah, thank you very much!
