### ISSUE TITLE
screen off gestures does not work on oneplus 3T

### ISSUE THREAD

**Issue by mytts** [offensive-security/kali-nethunter#688]
### Device:

oneplus 3T

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

6.0.1

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.3-20161129-1413/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

root@OnePlus3T:/ # cat /proc/version
Linux version 3.18.20-nethunter-3T-1.2 (jc@westerley) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Tue Nov 29 13:57:37 EST 2016

## Issue:

screen off gestures does not work on oneplus 3T

**Comment by jcadduono** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/issues/21

oneplus's fault lol

they keep releasing partially updated kernel sources, not the full thing

**Comment by maddalakum** [comment]
For me also not working :(
