### ISSUE TITLE
broken kali app after using phone for one day or two

### ISSUE THREAD

**Issue by mytts** [offensive-security/kali-nethunter#691]
### Device:

oneplus 3T

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

6.0.1

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.3-20161129-1413/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

root@OnePlus3T:/ # cat /proc/version
Linux version 3.18.20-nethunter-3T-1.2 (jc@westerley) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Tue Nov 29 13:57:37 EST 2016

## Issue:

using one day or two ,i open kali app get error, same when open supersu or terminal
![image](https://cloud.githubusercontent.com/assets/5030198/20875339/e20c8224-baf4-11e6-8549-03a4e2074851.png)

![image](https://cloud.githubusercontent.com/assets/5030198/20875361/04285fc2-baf5-11e6-9605-fed16a22bc35.png)

after reboot will be ok

**Comment by bkr32** [comment]
reflash the package?

**Comment by jcadduono** [comment]
sounds like a supersu bug

**Comment by mytts** [comment]
flashed new kernel and waiting

**Comment by tequillasun** [comment]
Try putting kaliboot and kalilogin into system/bin again

**Comment by mytts** [comment]
I flashed kernel-nethunter-oneplus3t-marshmallow-3.15.3-20161205-0246.zip ,and it is ok for now

**Comment by jmingov** [comment]
@jcadduono, since @mytts solved the issue with a kernel reflash, we can close this by now.

Reopen it if you feel like mate.
