### ISSUE TITLE
Can we get minimum Chroot downloads off of a website

### ISSUE THREAD

**Issue by tequillasun** [offensive-security/kali-nethunter#692]
### Device:
LGL33l

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Lollipop

### Built from repo (date and build command) or downloaded from website (links):
Website

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

3.0

## Issue:

Nhterminal cannot connect to the outside world.. and nmap is not there. 

I was told that 3.0 chroot would fix this

**Comment by bkr32** [comment]
isn't nmap available to use in the nethunter app?

**Comment by tequillasun** [comment]
It's supposed to be but batch: nmap not found

**Comment by tequillasun** [comment]
I tried changing repository but get error cannot connect to kali.org

**Comment by bkr32** [comment]
seems you flashed the minimal build which is missing some components,
and you will get that error if a firewall is in place
you can always side load it
[follow this](https://nmap.org/download.html)

**Comment by tequillasun** [comment]
Yeah the phone has minimal space but it would be nice if I could download the chroot from my pc

**Comment by tequillasun** [comment]
Pc

**Comment by bkr32** [comment]
https://build.nethunter.com/nightly

**Comment by tequillasun** [comment]
I think those .sh scripts worked.  I am now 3.15 seems to be one step closer to working

**Comment by bkr32** [comment]
....3.15 is working

**Comment by tequillasun** [comment]
I still cannot apt-get install nmap and it doesn't work from nh menu.  The update meta packages seemed like it updated.

**Comment by jcadduono** [comment]
use triple ` around copy/paste of console output, it's the only way you can explain your issue
