### ISSUE TITLE
terminal kali: none of my commands work??

### ISSUE THREAD

**Issue by tequillasun** [offensive-security/kali-nethunter#694]
### Device:
LGL33L

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nethunter 3.15 oneplus one lollipop

### Built from repo (date and build command) or downloaded from website (links):

web and repo

## Issue:
I can finally get into the terminal but when i ls nothing shows up... and none of my commands work, example nmap, msf, ext.

**Comment by tequillasun** [comment]
i have minimum chroot installed

**Comment by jcadduono** [comment]
`i have minimum chroot installed`

minimum is minimum, that is why, it is a barebones base for installing specific packages, use apt-get
