### ISSUE TITLE
I wanna buy a nexus 4 advices

### ISSUE THREAD

**Issue by pindonga1234** [offensive-security/kali-nethunter#696]

**Comment by jcadduono** [comment]
Nexus 4 is getting close to Nexus 7 2012 status, even OnePlus One is starting to show its age but you can find them for ~$150-$180 on swappa and ebay.

Nexus 4 has a lot of issues currently just as grouper is (but not as bad), and you will have a hard time trying to get things working reliably, especially with limited OTG power (although Y cable might work sort of on CyanogenMod 13 kernel)
