### ISSUE TITLE
Models advices (I dont know if Im asking in the right place) If Im, sorry

### ISSUE THREAD

**Issue by pindonga1234** [offensive-security/kali-nethunter#698]

**Comment by vay3t** [comment]
nexus 5x ;)

**Comment by pindonga1234** [comment]
Thank for answer vay3t. Do you have this cellular phone?. I was watching between the one plus and the nexus 5x, the nexus 6 is very expensive for me, in fact I saw a nexus 5x in a very good price. But the question is the battery, the nexus 5x have 2700mha and the oneplus have 3100 mha, considering that both are going use the external wifi card, in performance is better the oneplus isnt?. And for me the RAM is the same beetwen 2GB or 3GB, I only wanna it for nethunter neither extra app or use
