### ISSUE TITLE
surviving OTA's

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#704]
### Device:
oneplus one

## Issue:

so lately i switched over to cm weeklies and found that after every flash i had to reflash nethuntenter rolling or i'd get a `busy-box was not found` error when launching terminal,
turns out cm over writes busybox and now uses a stock implementation known as toy-box
https://github.com/landley/toybox
https://github.com/CyanogenMod/android_external_toybox
http://www.landley.net/toybox/about.html
http://forum.xda-developers.com/android/software-hacking/tool-official-toybox-android-t3290884

is it possible to switch over to toybox from busybox to help nethunter survive OTA's
it can take up to half an hour when flashing update + nethunter rolling

thanks

**Comment by jcadduono** [comment]
no

why are you flashing the full installer

all you need is the 50 MB update after OS updates

**Comment by bkr32** [comment]
Referring to this
https://build.nethunter.com/nightly/3.15.3-20161205-0246/update-nethunter-generic-armhf-3.15.3-20161205-0246.zip
?

**Comment by jcadduono** [comment]
ya

**Comment by bkr32** [comment]
well it works, although it would be ideal to flash less zips
