### ISSUE TITLE
Will support Android 7 on oneplus3? 

### ISSUE THREAD

**Issue by majackov** [offensive-security/kali-nethunter#705]
### Device:
Oneplus3 
### OS version
Nougat
## Issue:
Will support Android 7 on oneplus3?

**Comment by jcadduono** [comment]
isnt that a question for oneplus, and oneplus has already answered it

as for nethunter, yes, essentially the oneplus 3 will be supported from the same base as oneplus 3t

**Comment by majackov** [comment]
I know about android 7 on oneplus3 (they released it a few weeks ago), I'm waiting nethunter :)

**Comment by bkr32** [comment]
@majackov hope you can build kernels then :)

**Comment by jcadduono** [comment]
they haven't released nougat on either oneplus devices yet...it's still in beta with no sources available...
