### ISSUE TITLE
[WISHLIST] Porting NetHunter to Huawei Nexus 6P - Nougat (7.1.1)

### ISSUE THREAD

**Issue by eliasps** [offensive-security/kali-nethunter#706]
## Issue: Porting NetHunter to Huawei Nexus 6P - Nougat (7.1.1)

This is a "feature request", more like a wishlist item to consider once more important issues have been resolved. It's about making an official image of NetHunter for Nougat 7.1.1 on Huawei Nexus 6P (angler) to install and work out of the box.

Thank you.

**Comment by anietie** [comment]
true.

**Comment by AutinDroid** [comment]
@eliasps I'll try to build a 7.1.1 image, but I don't have a 6P so I will need someone to test the kernel.

**Comment by eliasps** [comment]
@AutinDroid I can test the kernel on my 6P. Contact me when you want to to get it started! Thank you!

**Comment by thnkyle** [comment]
I can test as well and looking forward to getting it working.

**Comment by slick97477** [comment]
I will also be happy to test it

**Comment by JakTheRipper** [comment]
I'd love to test it too!

**Comment by jcadduono** [comment]
and now YOU TOO can have elementalx 4.04 with NetHunter support for 5 easy payments of $19.95

ok, it's coming

**Comment by jcadduono** [comment]
wish granted: https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-test1.zip

let me know how it goes

if it doesn't boot, hopefully you can do adb pull /sys/fs/pstore in TWRP and upload the logs for me to gdrive or email (jc@add_ono.com, fill in the blank)

**Comment by dchrostowski** [comment]
Thank you, sir.  Here's my TWRP log, cut down to begin at the sideload:

http://streetscrape.com/nethunter_flash.log

Haven't booted yet, will report back with results.

**Comment by dchrostowski** [comment]
Appears I got a bootloop/soft brick.

**Comment by jcadduono** [comment]
and logs?

**Comment by thnkyle** [comment]
I also got the bootlop and getting logs for you. I'll upload soon and try the test2 kernel

**Comment by thnkyle** [comment]
test2 kernel booted. Testing now.

**Comment by jcadduono** [comment]
test2 is just stock configuration making sure it boots with no changes

although it does have HID patch in it so go ahead and test that

**Comment by dchrostowski** [comment]
Logs were included in my first post.  See above.  Gonna try out the second one now and I'll post the logs at http://streetscrape.com/nethunter_flash2.log

**Comment by jcadduono** [comment]
i don't see the logs, all i see is a recovery log

**Comment by dchrostowski** [comment]
Oh I though you only wanted the flash logs.  I'll reflash #1.  You just want boot logs or should I dump the my entire logcat to a file?

**Comment by jcadduono** [comment]
logcat doesn't help, i only want kernel log (dmesg if it boots far enough to get adb, /sys/fs/pstore/console-ramoops from twrp directly after boot fail if it doesn't get far enough)

**Comment by dchrostowski** [comment]
Hope this helps.  I'll move on to number 2 and update the page.  https://streetscrape.com/nhkt/

**Comment by jcadduono** [comment]
hmm ok im going to enable debug features so the console-ramoops has more info to go on

**Comment by dchrostowski** [comment]
Logs for test 2 are up.

**Comment by jcadduono** [comment]
ok need console-ramoops for https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-test3.zip (same as test1, but with debug enabled to i can see trace)

**Comment by dchrostowski** [comment]
Flashing test3 now.

**Comment by dchrostowski** [comment]
logs are up.

**Comment by jcadduono** [comment]
Weird...Something broken in tracer

**Comment by dchrostowski** [comment]
I'm gonna re-check I put everything in the right place.  I was being very careful, but doesn't hurt to triple check.

**Comment by dchrostowski** [comment]
I exported dmesg and console-ramoops again, diffed them against what's been uploaded.  console-ramoops files are identical,  dmesg files are identical except most recent export has a few more lines tacked on to the end. I'd say that's expected.  BTW I'm in California right now, nasty storm outside, trees are falling, roads are flooding, mudslides are happening, power is flickering.  I may abruptly stop responding.

**Comment by AutinDroid** [comment]
@dchrostowski I too have created a test kernel. Will be uploading soon. TIP: In that storm of yours, remember that wifi is the meaning of life... (hopefully not)

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-test4.zip k console-ramoops from this, this time i think i have fixed function tracer so should get useful output...

**Comment by AutinDroid** [comment]
I'll try to make a nexon version of the kernel, so just a bit longer.

**Comment by dchrostowski** [comment]
As soon as I said it, boom - power goes out.  I'm back on the grid and thankfully didn't drown in the "atmospheric river".  Test 4 logs are up.  https://streetscrape.com/nhkt/

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-test5.zip

**Comment by jcadduono** [comment]
*poke* any news on this guy

**Comment by JakTheRipper** [comment]
I Flashed it over to my Device this morning, booted fine, but this doesn't
have net-hunter rolled in it does it?

**Comment by jcadduono** [comment]
you have to install https://build.nethunter.com/nightly/3.15.4-20170107-1635/nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170107-1635.zip as well for the rest of nethunter

**Comment by JakTheRipper** [comment]
perfect will do, thanks. Ill let ya know how it goes.

**Comment by thnkyle** [comment]
I flash both the kernel and the new rolling linked to it and booted up so
far so good.

On Mon, Jan 9, 2017, 1:05 PM Jak, <notifications@github.com> wrote:

perfect will do, thanks. Ill let ya know how it goes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/706#issuecomment-271392510>,
or mute the thread

**Comment by JakTheRipper** [comment]
working for me so far

**Comment by thnkyle** [comment]
I've tested a HID attack with it against a computer and seems to be working
good so far. I will try and test some of the other features later but so
far, looks good.

**Comment by dchrostowski** [comment]
Flashing test5.

**Comment by dchrostowski** [comment]
test5 logs are up: https://streetscrape.com/nhkt/

**Comment by thnkyle** [comment]
If you want logs I can provide them. So far every test attack has worked,
the Kernel has been working good. All tests appear to be working so far.
Will continue to work through.

**Comment by jcadduono** [comment]
a lot of work i suppose but it would be nice to know if f2fs data works with it :)

**Comment by dchrostowski** [comment]
I can test f2fs.  I refurbish and sell 6Ps on Amazon so I have a few spares laying around which might as well be utilized as guniea pigs for the time being.  It's also my personal everyday phone so I have a stake in this.

**Comment by dchrostowski** [comment]
Any logs or anything needed for f2fs testing, or should I just say whether or not it works?  I can definitely stress test it by rapid firing storage reads and writes if that's even helpful.  I'm not really much of a embedded/OS dev (I'd like to be), so I apologize for my ignorance.

**Comment by jcadduono** [comment]
I guess just knowing it boots would be OK, the driver should be quite stable by now.

**Comment by jcadduono** [comment]
consider it officially supported and good to go, have fun!

**Comment by D13man** [comment]
Aw, I'm late to the party, oh well. 
So, is it fully supported then? Even DriveDroid and everything? o.o

**Comment by jcadduono** [comment]
i believe so, first build is up @ https://build.nethunter.com/nightly/3.15.4-20170110-0950/

**Comment by anietie** [comment]
I just updated my nexus 6p from 6.1 to 7.1.1, installed the above kernel after installing nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170110-0950.zip. When I plug in my otg cable the phone hangs. Whenever I plug the OTG my phone hangs until it is pulled out then it reboots.

I don't think nougat is completely supported yet.

**Comment by anietie** [comment]
When I plug in the OTG without any wifi adapter plugged (I have TL-WN722N and EDIMAX EW-7811Un) it works but when I plug in any of the wifi adapters the phone reboots and gets into a boot loop until I remove the wifi adapter. When a usb to ethernet adapter is plugged in the phone works as it should and doesn't reboot.

The wifi sub system of the nougat build isn't functioning well.

**Comment by jcadduono** [comment]
6P is arm64 not armhf

**Comment by AutinDroid** [comment]
@jcadduono Cause the 6P doesn't require any kernel patches for nexmon, can you just make a nexmon kernel with the current kernel?

**Comment by dchrostowski** [comment]
I could not get F2FS working with the kernel.  Will post logs soon - it's been a busy week.

**Comment by anietie** [comment]
@jcadduono I downloaded and flashed nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170110-1420.zip and the same thing happened. I also flashed nethunter-generic-arm64-kalifs-minimal-rolling-3.15.4-20170110-1420.zip to no avail. I noticed that inside the above zip files there is an archive file: kalifs-armhf-full.tar.xz and kalifs-armhf-minimal.tar.xz respectively. I wonder why an armhf file is inside a file that is supposedly for arm64. What logs do you need @jcadduono for you to investigate further. Thanks.

**Comment by jcadduono** [comment]
`dmesg` from OS / `/sys/fs/pstore/console-ramoops` from TWRP after crash/reboot happens

**Comment by anietie** [comment]
I have sent an email with the logs attached to jc@add_ono.com (your correct email).

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-debug-test1.zip
use this build for gathering log, i have a feeling i know where the real issue is but would like better traces

**Comment by anietie** [comment]
OK. 
--------------------------------------------
On Fri, 13/1/17, James Christopher Adduono <notifications@github.com> wrote:

 Subject: Re: [offensive-security/kali-nethunter] [WISHLIST] Porting NetHunter to Huawei Nexus 6P - Nougat (7.1.1) (#706)
 To: "offensive-security/kali-nethunter" <kali-nethunter@noreply.github.com>
 Cc: "anietie" <anietiejohnjAMES@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Friday, 13 January, 2017, 14:03
 
 https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-debug-test1.zip
 use this build for gathering log, i have a feeling i know
 where the real issue is but would like better traces

**Comment by anietie** [comment]
I have attached the logs for the test kernel below as instructed.

**Comment by jcadduono** [comment]
please upload the logs somewhere, you can't just post a full log like that on github issue comments it will get cut and provide no useful information

**Comment by anietie** [comment]
So sorry about that. I didn't know sending it to your email would also copy it here. I have uploaded them to google drive. Thanks. 

https://drive.google.com/drive/folders/0B5sZJlCToe6QRFVfLTFLN2dyR0E?usp=sharing

**Comment by jcadduono** [comment]
thanks, i'll go through that trace and add null checks!

**Comment by jcadduono** [comment]
ok @anietie how about logs from this one now:
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-debug-test2.zip

i added some additional mac80211 fixes and rearranged some bad checks in bcmdhd driver (stupid oem drivers)

**Comment by anietie** [comment]
Logs have been uploaded to google drive 
https://drive.google.com/drive/folders/0B5sZJlCToe6QRFVfLTFLN2dyR0E
1. I copied twrp recovery log immediately after installing kernel with twrp
2. Copied dmesg after reboot
3. Also copied /sys/fs/pstore

**Comment by jcadduono** [comment]
i wonder what the negative effects of just removing the notifier call entirely from bcmdhd would be, because i fixed any possible null pointer deref in that function and that doesn't make any sense at all

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-debug-test3.zip
@anietie alright, see what happens with this build. might lose internal wifi, might not, not sure lol

**Comment by anietie** [comment]
@jcadduono thanks for all the effort. My phone no longer freezes when the wifi is plugged in. I have uploaded the logs

1. I copied twrp recovery log immediately after installing kernel with twrp
2. Copied dmesg after reboot but before wifi is plugged in
3. Copied dmesg after reboot and after wifi is plugged in
4. Also copied console-ramoops-b4-reboot-after-kernel-install
5.  Also copied console-ramoops-after-reboot-wifi-plugged-in 

I appreciate the effort sir.
Please can you point me to a guide on how to recompile the kernel so I can install the driver for my EDIMAX EW-7811Un usb adapter. And again why doesn't lsmod 

Much appreciated.

**Comment by jcadduono** [comment]
looks fine to me, appears to be working just fine according to logs

lsmod is the wrong command, you want lsusb
lsmod is for listing modules, and all wifi drivers are built into the kernel

`ip link set wlan1 up` brings your device online
you need to set monitor mode before doing that command if you want to use monitor mode

otherwise, just use the enable monitor mode command from nethunter app

**Comment by eliasps** [comment]
Seems to be working fine on my end too. Created a thread about it on XDA, in case more people want to help with this: https://forum.xda-developers.com/nexus-6p/general/kernel-kali-nethunter-huawei-nexus-6p-t3539084

Thanks!

**Comment by jcadduono** [comment]
uploading 1.1 will be in next nightly thanks

**Comment by SUbconsciousNcrytptions** [comment]
I have a LG Aristo two MSM board arm7 V processing chip and I was just wondering which kernel or which nethunter I would need to run on my 7.1.2 LG Aristo 2

**Comment by 0E800** [comment]
Try to find the source for the kernel of your device.
It needs to be modified and you can't modify something if you don't have the source .

Try to find the source for your ROM build as well.

**Comment by Muslim90** [comment]
Help bro build a Nethunter core for the Redmi note 6 pro model
