### ISSUE TITLE
Screen Recording Request

### ISSUE THREAD

**Issue by lcfut** [offensive-security/kali-nethunter#708]
Not really an "issue" per-say, but looking for capability to screen record in Nethunter similar to the desktop version of Kali.
Not sure if this is on the radar, or I am missing the option somewhere.

**Comment by jmingov** [comment]
Is part of GNOME wm, well a extension for it.

Check https://extensions.gnome.org/extension/690/easyscreencast/

At the moment is not a preference, well really is not even an idea, you have a lot of diff ways to record the screen.


Check this apps
http://www.androidauthority.com/best-screen-recording-apps-600838/

Or you can also do it with `adb shell screenrecord –bit-rate 12000000 /sdcard/screen.mp4`

BR

J
