### ISSUE TITLE
Error: Script failed: 01-ramdisk-patch!

### ISSUE THREAD

**Issue by BesoBerlin** [offensive-security/kali-nethunter#709]
### Device:

Nexus 6 shamu

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

7.0 Nougat

### Built from repo (date and build command) or downloaded from website (links):
15.12.2016
./build.py -d shamu -n 

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.40-g60e3696 (android-build@kpfj13.cbf.corp.google.com) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Sat Oct 22 03:37:25 UTC 2016

## Issue:

I just cant get the kernel installed... 
I am continuesly getting the "error: script failed 01-ramdisk-patch!" ... 
the log doesnt really give me any further information:

[recovery.log](https://github.com/offensive-security/kali-nethunter/files/655939/recovery.log.txt)

> - Detected ramdisk compression format: gzip/sbin/gzip
> /sbin/gzip
> 6055 blocks
> 
> - Running ramdisk patching scripts...
> - Executing: 01-ramdisk-patch
> -- Patching the ramdisk for NetHunter & init.d...
> 
> - Error: Script failed: 01-ramdisk-patch!- Aborting...
> Failed to patch boot image!Running Kali chroot installer...

but maybe one: 

> Installing busybox applets to /sbin
> Freeing up some space on /systemsh: 
> 63%: bad number

is there anybody who had the same issue and maybe already fixed that?
If not...any suggestions?

thnx a lot in advance for reply!

**Comment by jcadduono** [comment]
fixed, will be in next nightly

**Comment by BesoBerlin** [comment]
Hooray!! Thank you jcadduono!! now the kernel installed succesfully! 
not even 24 hours... WOW... 
At the moment there are some smaller issues, but i'll report them seperately when documented correctly...

Well done! ...close...

**Comment by joeisgood99** [comment]
I’m porting this to Sony z5c, so far it works over stock rom but have exactly same issue. @jcadduono Is this fix in Master branch? or just in the nightly. If so can you please point me to the commit?

At this stage I have to to patch kernel on my pc then flash it.

**Comment by jcadduono** [comment]
@joeisgood99 master branch same thing as nightly, post your recovery.log can't know anything without it

**Comment by joeisgood99** [comment]
Ok. I prob should start a new issue but here is the recovery.log
https://mega.nz/#!Qo5THDIQ!_u27Iri_NqWGZmA5IRsXOprpE1BIheMgu6vQ9vEWHjg

```
Running boot image patcher...

- Found boot partition at: /dev/block/mmcblk0p29- Dumping & unpacking original boot image...boot-patcher.sh: line 278: /tmp/nethunter/boot-patcher/tools/bootimg: not found


- Error: Unpacking boot image failed!- Aborting...
Failed to patch boot image!
Running Kali chroot installer...
```

**Comment by jcadduono** [comment]
your TWRP build is severely broken and the whoever is maintaining it has no idea what they are doing

**Comment by joeisgood99** [comment]
I agree. There is a 1000 unofficial versions of TWRP for Sony kitakami
platform . No official ones. The version used to produce recovery.log has
haad no problem installing other .zip files before.  Are you suggesting
that I try another version of TWRP?

**Comment by jcadduono** [comment]
that's embarrassing, well, i can just make an official TWRP for your device if you're willing to work with me on it

**Comment by joeisgood99** [comment]
Too easy. Sony has a recovery  inside kernel set up.  Iv built my own
version  so can upload device trees etc. Also when I get home from work I
can re test with my version of TWRP.  I'm very happy to work with you.

**Comment by joeisgood99** [comment]
Hi @jcadduono 
Apologies. I was at work when I read your reply. For some reason gmail only showed the first half sentence of each post you sent so I never saw the invite to #twrp on freenode IRC. Please let me know when your free and Ill meet you there. I have the next 3 weeks off annual leave so whenever suits you. I’m uploading a copy stock boot.img now.... Also can only find the #twrpdev channel not #twrp.

**Comment by Log1c1** [comment]
When I start the installation, the phone says "kali nethunter Error: unpacking boot image failed" and everything stops (Version from 2017-11-18) Help
