### ISSUE TITLE
mana wireless toolkit - nethunter error

### ISSUE THREAD

**Issue by jeretc** [offensive-security/kali-nethunter#710]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gb7558f2  gcc version 4.7 smp preempt wed oct 7 02:16:12 utc 2015

## Issue:
![screenshot_20161216-124329](https://cloud.githubusercontent.com/assets/20941239/21252050/a5375fb6-c38e-11e6-8ecc-345b4653b833.png)

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
