### ISSUE TITLE
VNC of Kali GUI feezes upon start

### ISSUE THREAD

**Issue by AutinMitra** [offensive-security/kali-nethunter#711]
### Device:

Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.3-20161216-0523/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-g15ae70a (root@nh-buildbox) (gcc version 4.8 (GCC) ) #3 SMP PREEMPT Tue Dec 6 11:50:40 CST 2016

## Issue:

VNC for the Kali GUI freezes at desktop, unable to move mouse.

**Comment by binkybear** [comment]
Could you provide a logcat of error (just the error related to vnc app) when running app?  Does it freeze on connect or on open?

**Comment by AutinDroid** [comment]
It freezes right after displaying my desktop
Logcat:
12-17 12:43:00.548 D/VNCFragment(13164): 
12-17 12:43:00.586 D/RUN_SCRIPT_NH: CMD(13747): vncserver :1 -geometry 1776x1080 && echo "Closing terminal in 5 secs" && sleep 5 && exit
12-17 12:43:00.586 D/initialCommand(13747): vncserver :1 -geometry 1776x1080 && echo "Closing terminal in 5 secs" && sleep 5 && exit
12-17 12:43:00.587 D/MM createTermSession(13747): /su/bin/su -c /system/bin/bootkalicmd: vncserver :1 -geometry 1776x1080 && echo "Closing terminal in 5 secs" && sleep 5 && exit
12-17 12:43:00.598 D/STS: ^^ (13747): /su/bin/su -c /system/bin/bootkali cmd: vncserver :1 -geometry 1776x1080 && echo "Closing terminal in 5 secs" && sleep 5 && exit
12-17 12:43:00.815 D/CS: InitialCmd(13747): vncserver :1 -geometry 1776x1080 && echo "Closing terminal in 5 secs" && sleep 5 && exit
12-17 12:43:03.404 I/Xtightvnc(20507): type=1400 audit(0.0:946): avc: denied { getattr associate } for key=0 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=shm permissive=1
12-17 12:43:16.557 I/ActivityManager(1167): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x18000000 pkg=com.offsec.nhvnc cmp=com.offsec.nhvnc/android.androidVNC.androidVNC (has extras)} from uid 10092 on display 0
12-17 12:43:16.584 I/ActivityManager(1167): Start proc 20851:com.offsec.nhvnc/u0a134 for activity com.offsec.nhvnc/android.androidVNC.androidVNC
12-17 12:43:16.917 W/System  (20851): ClassLoader referenced unknown path: /data/app/com.offsec.nhvnc-1/lib/arm
12-17 12:43:17.165 D/VncConstants(20851): FOLLOWPAN=0 DOUBLE_TAP_ACTION=null ADDRESS=127.0.0.1 USERNAME=root USELOCALCURSOR=0 PORT=5901 LAST_META_KEY_ID=0 PASSWORD=Tintin1! USEREPEATER=0 INPUTMODE=TOUCH_ZOOM_MODE FOLLOWMOUSE=0 NICKNAME=LOCAL CONNECTION COLORMODEL=C24bit SECURECONNECTIONTYPE=null SHOWZOOMBUTTONS=0 FORCEFULL=0 METALISTID=1 _id=2 SCALEMODE=MATRIX KEEPPASSWORD=1 REPEATERID=
12-17 12:43:17.167 I/ActivityManager(1167): START u0 {cmp=com.offsec.nhvnc/android.androidVNC.VncCanvasActivity (has extras)} from uid 10134 on display 0
12-17 12:43:17.191 I/WindowManager(1167): Destroying surface Surface(name=Starting com.offsec.nhvnc) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.destroyOrSaveSurface:2095 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3066 com.android.server.wm.WindowManagerService.relayoutWindow:2932 com.android.server.wm.Session.relayout:215 android.view.ViewRootImpl.relayoutWindow:5688 android.view.ViewRootImpl.performTraversals:1758 
12-17 12:43:17.319 I/VncCanvas(20851): Connecting to 127.0.0.1, port 5901...
12-17 12:43:17.322 V/VncCanvas(20851): Connected to server
12-17 12:43:17.322 I/VncCanvas(20851): RFB server supports protocol version 3.8
12-17 12:43:17.325 I/VncCanvas(20851): Using RFB protocol version 3.8
12-17 12:43:17.328 I/VncCanvas(20851): VNC authentication needed
12-17 12:43:17.331 I/System.out(20851): VNC authentication: success
12-17 12:43:17.335 I/VncCanvas(20851): Desktop name is root's X desktop (kali:1)
12-17 12:43:17.335 I/VncCanvas(20851): Desktop size is 1776 x 1080
12-17 12:43:17.506 I/ActivityManager(1167): Displayed com.offsec.nhvnc/android.androidVNC.VncCanvasActivity: +326ms (total +16s958ms)
12-17 12:43:20.614 W/System.err(20851): 	at android.androidVNC.RfbProto.writePointerEvent(RfbProto.java:1093)
12-17 12:43:20.614 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1158)
12-17 12:43:20.614 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1144)
12-17 12:43:20.615 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1126)
12-17 12:43:20.615 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1114)
12-17 12:43:20.615 W/System.err(20851): 	at android.androidVNC.VncCanvasActivity$ZoomInputHandler.onSingleTapConfirmed(VncCanvasActivity.java:245)
12-17 12:43:20.616 W/System.err(20851): 	at android.androidVNC.RfbProto.writePointerEvent(RfbProto.java:1093)
12-17 12:43:20.616 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1158)
12-17 12:43:20.616 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1144)
12-17 12:43:20.616 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1126)
12-17 12:43:20.616 W/System.err(20851): 	at android.androidVNC.VncCanvas.processPointerEvent(VncCanvas.java:1114)
12-17 12:43:20.616 W/System.err(20851): 	at android.androidVNC.VncCanvasActivity$ZoomInputHandler.onSingleTapConfirmed(VncCanvasActivity.java:247)
