### ISSUE TITLE
Mana bettercap, unable to start bettercap

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#714]
### Device:
Oneplus one

## Issue:
Upon launching mana-net-bettercap, the following error is encountered by bettercap 
'The specified gateway -I is not a valid ipv4 address'
Using the default settings

**Comment by vay3t** [comment]
That problem has bettercap in nethunter. I have not tried if it was corrected in the last versions of apk, but the solution is very simple. Manually specify the gateway with -G

try update the apk. I'll test it later. Currently occupied 3.15.3v

**Comment by vay3t** [comment]
lul, I have problems with mana in hammerhead. My phone reboot when i take the mana menu

```
root@kali:~# cat /proc/version
Linux version 3.4.0-g5e6aa13 (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Sat Apr 2 20:23:25 CDT 2016
```

**Comment by bkr32** [comment]
running 3.15.3, i'll test out the manual method as soon as my phone charges up

**Comment by vay3t** [comment]
I confirm hammerhead works nice mana-bettercap. I have had no problems actually

**Comment by bkr32** [comment]
any recommended irc client?

**Comment by vay3t** [comment]
https://www.offensive-security.com/offsec-irc-guide/
https://irssi.org/
https://play.google.com/store/apps/details?id=org.yaaic

**Comment by bkr32** [comment]
thanks i'll ask if anyone has a similar issue on it
happy holidays
