### ISSUE TITLE
Deleting system apps during flash

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#715]
### Device:
Oneplus One

## Issue:
so lately i noticed a strange issue, i clean flashed my rom and applied a LWP which worked fine, but after flashing nethunter the LWP picker was gone from system/app has anyone else encountered this or am i simply a one of case

**Comment by jcadduono** [comment]
if you don't have room for nethunter it moves apps from /system/app to /data/app until it has 50 MB free space on /system

see https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/common/tools/freespace.sh
looks like i got a typo i need to fix there too

**Comment by bkr32** [comment]
thanks i'll reflash once new builds are up and let you know if the issue persists
