### ISSUE TITLE
could be a useful tool on the platform to automate ettercap

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#717]
https://github.com/r00t-3xp10it/morpheus

@binkybear

**Comment by akrolla** [comment]
Can this be installed in chroot?  . Kali is supported

**Comment by akrolla** [comment]
Or added to metapackages

**Comment by vay3t** [comment]
u can try run in ur nethunter:

```bash
apt-get install -y ettercap nmap apache2 zenity
git clone https://github.com/r00t-3xp10it/morpheus
./morpheus
```

if u have questions u can ask your creator: https://twitter.com/pedro31851511

**Comment by akrolla** [comment]
Have you tried it yet I'm gonna go ahead and check it out ? Could be useful
for people who don't know ettercap that well.

**Comment by akrolla** [comment]
It ask for textual ettercap or visual ettercap, go the textual route
correct?


On Dec 22, 2016 12:25 PM, "cody webb" <cody.l.webb@gmail.com> wrote:

Have you tried it yet I'm gonna go ahead and check it out ? Could be useful
for people who don't know ettercap that well.

**Comment by vay3t** [comment]
Ettercap is deprecated if u can information for sniffing u can read this doc:
https://www.bettercap.org/docs/

**Comment by akrolla** [comment]
Yea I use better cap I was unaware ettercap is deprecated but I'd bet in
the near future this will be used with better cap

**Comment by vay3t** [comment]
In comfort for nethunter, use "mitmf" https://github.com/byt3bl33d3r/MITMf (you can find it in the apk), it has functions similar to morpheus. You could test it. 

note: In my opinion i think bettercap does better bypass hsts, but mitmf has better plugins

**Comment by akrolla** [comment]
Yea I like mitmf I just believe more then 1 type of tool should be used as
to provide a clearere picture, there's stuff burp will pick up that nmap or
nessus dont.
