### ISSUE TITLE
Unable to import DuckyScripts to Duckhunter

### ISSUE THREAD

**Issue by BesoBerlin** [offensive-security/kali-nethunter#718]
### Device:

Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

7.0 Nougat

### Built from repo (date and build command) or downloaded from website (links):

from repo 15.12.2016
./build.py -d shamu -n

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.40kali-g1d7b23e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #4 SMP PREEMPT Thu Aug 25 18:56:08 CDT 2016 (thanx @jcadduono again)

## Issue:

somehow duckhunter does not import scripts from sdcard, it is only possible to paste it from clipboard, but even if I do this, it is not possible to open it again... 
![screenshot_20161220-225542](https://cloud.githubusercontent.com/assets/12254933/21369503/91a2a844-c707-11e6-88e7-7aea1ae0053f.png)

**Comment by akrolla** [comment]
were you unable to find the ducky.txt ? I had to use a filemanager with
rootaccess to locate the ducky script that was only in my download folder,
it wouldn't show with the stock filemamager , for me, when you load from sd
card, it doesn't load the script and when you execute the attack after
loading from sd card it does the does the demo and never loads thw script
from the sd card.

**Comment by BesoBerlin** [comment]
No... In previous versions I was even able to import it from Dropbox, so I know it should work... 
but whatever I do, it is not possible... Even when manuallly copy it to the preset scripts, it is not available...

**Comment by akrolla** [comment]
You know come to think of it, it wont execute even after copy and paste and
conversion either , and actually I just checked and my nexus 5 can't find
the file either. weirD last week I did a ducky attack and it was able to
locate but not convert.. odd.

**Comment by BesoBerlin** [comment]
Now I got it... Well that's strange and I hope there will be a fix for this... Under marshmallow it worked fine for me....

**Comment by jcadduono** [comment]
probably supersu related

**Comment by BesoBerlin** [comment]
No but Ive tried again and when I paste or insert a duckyscript manually, it works well! For me it is only the issue of loading/saving to/from sdcard...

**Comment by malicewizard** [comment]
question. how do you get your nexus 6 7.0 nougat to work? from my research. it says it won't work. NBD90Z

**Comment by BesoBerlin** [comment]
Any news or workarounds for this issue? 
Have the same issue on any newer build for my Nexus 5 (cm14) as well...
