### ISSUE TITLE
some more enhancement ideas.

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#720]
I know every body is busy but there are some knowledgeable people in this community (IMA noob but progressively learning how mobile development works.,) maybe it would be a good idea to task people from the community to different areas, to help alleviate some burden from the main developers ,areas that binkybear and jcadduono are too busy to deal with .their love of the platform is bringing it forward at a very nice pace and to keep that pace and possibly increase the pace and capabilities 
we need to let them continue their wonderful work, but they definitely need help on other parts of the battlefront persay. The website would help with those duties and it would take some more commitment from the community but I think we are all gung ho about this I see the same names daily finding new issues which is great. Open source is a beautiful thing. Perhaps someone could assist in keep  more up to date with the status of certain projects and such we all love this thing I can tell its going to go far I feel if there were defined task given maybe the project could move at a faster rate, who knows fixing every little thing wrong on all the platforms takes all their time . I think it would help with productivity. And would incorporate the community more into the project I dunno.

**Comment by akrolla** [comment]
Or would it be possible to add the bcmon/nexmon to the kernel for grouper which was dropped but its still accessible to be built @autindroid as that could make it functional and useful again and I'd imagine they have the same WiFi radio as the nexus could probably port it to flo and deb also

**Comment by akrolla** [comment]
I'll look into if they used the same broadcom chip. I don't know but I think it could be done what do you think @jcadduono , I'm just trying to get as much compatible hardware out there for us it increases presence we don't need to have time constraints on issues for older devices as they are no longer supported and could take a little longer to respond because of that.

**Comment by AutinDroid** [comment]
@akrolla I'll try, but I don't own a nexus 7, I only on the pixel c, Nexus 5, and a Kindle fire (I'll make the pixel c compatible with nethunter, but the Kindle fire is way too slow). I can build it, but I need a tester.

**Comment by akrolla** [comment]
Aparantley it has the same chipset as the S3 
https://encrypted.google.com/search?source=android-browser&ei=ji5bWPLnI5TejwP-0oWoBA&q=bcmsdh_sdmmc+monitor+mode&oq=bcmsdh_sdmmc+mo&gs_l=mobile-gws-serp.1.0.0i22i30k1l2.3026.3961.0.5305.3.3.0.1.1.0.298.753.0j1j2.3.0....0...1c.1.64.mobile-gws-serp..0.3.506...0i30k1j0i10i30k1.S7T7W2hBrTM

And can perform monitoring mode

**Comment by akrolla** [comment]
I'll keep looking for active projects to make this chipset have monitoring mode capabilities

**Comment by AutinDroid** [comment]
@akrolla I'll try to port these devices when i'm free :) I don't how how bcmon works in chroot, but I will do my research.

**Comment by akrolla** [comment]
hey man no rush dude just enjoy ya vacay i got to 3v3n see if mon mod3 is possiblr on the chip set
im just really excited about the hammerheadcafmon im giddyvlike a schoolgirl

**Comment by AutinDroid** [comment]
@akrolla I can't wait till I create the hammerheadcafmon kernel. I am using a caf ROM as my daily driver (probably a bad idea, but meh...) and I miss nexmon capabilities in chroot.

**Comment by akrolla** [comment]
http://bcmon.blogspot.com/2012/09/working-monitor-mode-on-nexus-one.htmlindeed it seems my friend we are in the same boat

i think it maybe possible to do

i was reading their blog and there forum and it seems as they have had a alot of ssuccess

**Comment by AutinDroid** [comment]
@akrolla I don't know if it will work on newer time because it was discontinued a while back, probably requiring modification. I'll try to learn more :)

**Comment by akrolla** [comment]
go into op3n issu3s i hqve one titled nexus 7 jcaduono breaks it down how t0 build the kernel or find a new 3.4 kernel with packet injection capabilities for grouper

**Comment by AutinDroid** [comment]
@akrolla Nexmon is available for the S2, which has the BCM4330 chipset, the same one as the Nexus 7. I also found a kernel for aosp 7.1 for the grouper: http://forum.xda-developers.com/nexus-7/orig-development/wip-linux-tegra-nv-3-4-bringup-t3128195
I will try to build it with nexmon.
It would be nice if you could test your Nexus 7 with the nexmon app, and install the firmware for the S2.

**Comment by akrolla** [comment]
i have my groups as a pwn pad right n9w, and it fools the grouper into thinking its tilapia and the  bcmon apk along with the rfa.apk reaver app actually work and airodump-ng and a few tools come with bcmons apk

**Comment by akrolla** [comment]
pwnpads img works on both tilapia and grouper. so i think we can incorporate it somehow its not buggy at all running tilapia...

**Comment by akrolla** [comment]
just gott a make sure the kernel supports packet injection

@pingdonga1234

any luck on the front yet

**Comment by akrolla** [comment]
I have nexus 5 and grouper which are both out the door but there are a lot of grouper users out there still so it would be cool to add a Monmode before retirement, I have no bugs with the tilapia ROM I currently run on it so I really think it can be done if pwnie tricked grouper into tilapia we can do it also

**Comment by akrolla** [comment]
I'm running g a 3.2 kernel so we would def need a 3.4 kernel with packet injection capabilities it would probably be easier to find a tilapia one.

**Comment by akrolla** [comment]
Since it...obviously works..only bugg is it shows a signal strength but that's because tilapia has a gsm radio

**Comment by akrolla** [comment]
The only provle. With the reaver apk and bcmon apk the bcmon apk is limited to just monitoring and thegui for reaver isn't  really good

**Comment by akrolla** [comment]
Problem

**Comment by AutinDroid** [comment]
@akrolla here's a solution: https://github.com/chrisk44/Hijacker

**Comment by akrolla** [comment]
For the grouper?

**Comment by AutinDroid** [comment]
@akrolla no for the GUI issues. Nexmon is better

**Comment by akrolla** [comment]
problem parsing the package error

**Comment by akrolla** [comment]
its only for armv71 devices

**Comment by akrolla** [comment]
nexon dowantsupport grouperbut on their github they tell u how to compile it into a r0m same thing as bcmon

**Comment by AutinDroid** [comment]
@akrolla we don't want to compile a ROM with nexmon, a kernel would be better. All we need is the correct firmware, patches for the kernel, and the correct scripts to activate monitor mode, if we want chroot nexmon to work. For example, all the Nexus 5 needed was two patches, a few scripts, and the nexmon firmware.

**Comment by akrolla** [comment]
Oh I understand well now I know what parts to look for insteadcof entire
prjects

**Comment by AutinDroid** [comment]
Take a look at this:
https://github.com/seemoo-lab/nexmon/issues/9
Remember to backup your firmware!!!

**Comment by akrolla** [comment]
B e a utiful

**Comment by akrolla** [comment]
@pindonga1234

**Comment by akrolla** [comment]
Nexmon apk doesn't ** right off the shelf support...I don't have a PC ATM that's why I want to do it all on the phone... And in the field  you are only gonna have a cell and Maybe a laptop

**Comment by akrolla** [comment]
I don't know show to cp the finished ROM from git in chroot to sdcard in tilapia I can probably compile the whole thing unless you need adb ....

**Comment by akrolla** [comment]
how not show***

**Comment by akrolla** [comment]
Kernel not ROM**

**Comment by akrolla** [comment]
I don't know if that will play nice with my setup with the pwnpad that's why I keep saying ROM I have a feeling to get this done we are going to have to compile a tilapia ROM with nexmon not just a kernel I think that's going to brick the pwnpad hold on a sec and I'll give u the output of cat /process/version of the tilapia kernel.. And what other logs u might need just let me know

**Comment by akrolla** [comment]
https://drive.google.com/folderview?id=0B_18XYZB0AOyblplQ1VDbWFZN2s

**Comment by vay3t** [comment]
@akrolla My recommendation for you is: try to be as easy as possible in github and try not to use it as a chat. For that is the irc. If you have more general questions or want to talk for a while you can ask for twitter.

**Comment by akrolla** [comment]
A couple of this show that its indeed a tilapia ROM running successfully on a grouper

**Comment by AutinDroid** [comment]
You can tweet me @AutinDroid

**Comment by akrolla** [comment]
how are we supposed to develop without communication

**Comment by akrolla** [comment]
i dont havee a twitter..

**Comment by akrolla** [comment]
autin just hit me up on my github page we can talk there freely. sorry guys for the chit chat but trust me communication is the key to successful projects

**Comment by vay3t** [comment]
@akrolla It's easy to create a twitter account. What you say is true, but sometimes lots of information can generate noise

**Comment by akrolla** [comment]
yea well... im banned from irc for some reason...i have trwitter i gotta recover it...

**Comment by akrolla** [comment]
i understand vay3t

**Comment by akrolla** [comment]
@codyweb2

**Comment by akrolla** [comment]
yea most the time im on mobile so i cant edit comments or else i would post a single comment not to mention more ideaspopup in myheax after i wrote commwnt

**Comment by vay3t** [comment]
github is comfortable for mobiles, look https://github.com/akrolla

**Comment by akrolla** [comment]
But you can't edit comments in mobile I have to open desktop version that's
why I always have to correct misspells

On Dec 22, 2016 12:25 PM, "Vay3t" <notifications@github.com> wrote:

github is comfortable for mobiles, look https://github.com/akrolla

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/720#issuecomment-268860089>,
or mute the thread

**Comment by akrolla** [comment]
Don't have a twitter and nobody's ever in irc.. I'm not trying to chitchat I'm just trying to provide enough info as possible and ask questions. I know this platform is for code only but then how are issues ever addressed if we can't talk through them that's what development is about communication and testing. I try to provide enough evidence and even ask what evidence people need to develop a solution.

**Comment by akrolla** [comment]
Speaking of .. @binkybear am I banned from irc...

**Comment by akrolla** [comment]
Still no edit button in mobile

**Comment by vay3t** [comment]
binky and jc always on twitter

**Comment by akrolla** [comment]
Awesome well we shall converse there. I just don't trust twitter I've seen
what the je5t3r can do with twitter API tokens...

On Dec 22, 2016 12:49 PM, "Vay3t" <notifications@github.com> wrote:

binky and jc always on twitter

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/720#issuecomment-268864661>,
or mute the thread

**Comment by akrolla** [comment]
@binkybear with recent improvements i think we could bring grouper bqck from the dead with monitoring modei run pwnpad which is a tilapia rom.. on my grouper withno bugs and bcmon apk does exactly as it is suppssed to, perhaps tilapia rom with mon in chroot would do the trick or evn just a kernel

**Comment by mastermind860** [comment]
Guys, i have a doubt. When i use crunch to make a worklist, where exactly is it saving in nethunter. Im using nethunter in my One Plus 3. Whenever i create wordlist, the wordlists are created but i cant find it anywhere

**Comment by akrolla** [comment]
Crunch on your phone is probably a bad bad idea... Id imagine it would
populate your storage rather quickly and perhaps cause it to fail

**Comment by akrolla** [comment]
If you use pyrit u can do a pass through attack with crunch

**Comment by vay3t** [comment]
# crunch [args] > dict.txt

**Comment by akrolla** [comment]
Does nh have rainbow tables on it??

**Comment by mastermind860** [comment]
Thanks for your replies guys. I have found a way to use crunch in nethunter without any problem. The only problem which i had was crunch is saving all the created password list to an unknown folder. So wat i did is, i just created a folder inside /usr/share/passwords and gave the crunch output, that is crunch 5 6 12345 -o /usr/share/passwords/pass.txt and it saves the files in this location.

**Comment by 0E800** [comment]
There is a group/entity purposefully,  however gentle and patient in approach, deleting with intent to remove completely from  the internet; certain records, small unknown at the time or miss-interpreted facts recorded in personal blogs or tweets, but mostly anything that is evidence that can only be acquired from an online archive or website. 
Its important to be vigilant and to protect what you hustle for.


Don't let threads die.
History, for the sake of history; is why we archive.
