### ISSUE TITLE
Im a lammer. What does mean invalid issue report (not filled out)

### ISSUE THREAD

**Issue by pindonga1234** [offensive-security/kali-nethunter#722]
### Built from repo (date and build command) or downloaded from website (links): I need to know something, Im a lammer and always was for me a real issues to post in a forum. I dont see the necessary rules for do it, and so my question is what means 
invalid issue report (not filled out). I described what was my issue, so what must I filled out?

**Comment by BesoBerlin** [comment]
well...
Device:Oneplus One --> ok...

OS version (KitKat/Lollipop/Marshmallow/Nougat):CM12 CM13 ---> which of those? 12 or 13? well ok... youve tried both... 

Built from repo (date and build command) or downloaded from website (links): --> so youve built one from build.nethunter.com... which date and with which command?

Output of cat /proc/version in adb shell or NetHunter Terminal: --> youve left this blank (you did not fill out) so nobody knows ... please take at least the time to post this, as it would be helpfull...

by the way: what do you mean with they were not detected? not detected by wifite, by airmon-ng or by ifconfig?? please give more details when reporting an issue...

**Comment by pindonga1234** [comment]
Thank for the advice I will have it for future post, not detected in wifite neither in airmon-ng neither in ifconfig. But TL-WN722N works very well

**Comment by akrolla** [comment]
the reason they aask for the output of logcat /proc/version is to make sure you have a kernel built by them or a proper kernel that allows for packet injection it helps them to narrow down the issue. also btw, as for grouper, ive a tilapia rom on it and itworks fine. and BCMON works well on it also. so if you put the bcmon apk on the proper kernel that allows for injections , it unlocks the injection capabilities of the wifi radio inside the grouper
