### ISSUE TITLE
What is the default directory of nethunter

### ISSUE THREAD

**Issue by mastermind860** [offensive-security/kali-nethunter#724]
### Device:
Oneplus 3

## Issue:
 First of all this is not an issue. Kali nethunter is working good on my OP3. I just want to know the default directory of nethunter where the files are stored in android. Because i have created wordlist using crunch and it is not accessible by the wordlist name. When doing that it is showing file or directory not found. Please help

**Comment by mpkosewski** [comment]
I've only been able to access it via "Fx File Explorer" app with the root addon app. This is from the default home screen. You gotta enable root in the app and view hidden files first tho. 

System (root)  "/data/local/nhsystem/kali-armhf"

**Comment by jmingov** [comment]
Yo are right @mpkosewski, thats the path.
