### ISSUE TITLE
Will pay for a updated version of NetHunter for nexus 6 7.0 nougat NBD90Z.

### ISSUE THREAD

**Issue by malicewizard** [offensive-security/kali-nethunter#725]
## Issue: Top says all. or if their is a version that i can down grade to. that would be greatly appreciated.

**Comment by SecurityAddicted** [comment]
That's what I've done on my Nexus 9 with Nougat to have a (mostly) working Nethunter installation (links are for your device btw):
1. Start from a clean base (no old Nethunter install on the device)
2. Go to recovery
3. Flash [THIS](https://build.nethunter.com/nightly/3.15.3-20161222-1600/nethunter-generic-armhf-kalifs-full-rolling-3.15.3-20161222-1600.zip) if you want a full install of Kali, [THIS](https://build.nethunter.com/nightly/3.15.3-20161222-1600/nethunter-generic-armhf-kalifs-minimal-rolling-3.15.3-20161222-1600.zip) for a minimal one
4. Flash [THIS](https://build.nethunter.com/nightly/3.15.3-20161222-1600/kernel-nethunter-shamu-nougat-3.15.3-20161222-1600.zip) kernel
5. Clean cache/dalvik
6. Reboot
That worked for me, hope it will be for you as well :)

**Comment by malicewizard** [comment]
Well from research it would soft brick it. You know of this?

**Comment by SecurityAddicted** [comment]
Well my Nexus 9 with Nougat and Nethunter is working ok.
I guess you can just try that and, eventually, going back to a clean state by attaching it to a pc and flashing a factory image :)

**Comment by malicewizard** [comment]
Just a question. What's the difference between your 9 nougat and my 6
nougat.

**Comment by SecurityAddicted** [comment]
I don't know, I don't own a Nexus 6.
Anyway, [HERE](https://github.com/offensive-security/kali-nethunter/issues/718) there is a guy running Nethunter with Nougat on Nexus 6, so you can try safely I guess :)

**Comment by malicewizard** [comment]
Thank you for the link and your. I appreciated your help

**Comment by BesoBerlin** [comment]
Have a look at this... https://github.com/offensive-security/kali-nethunter/issues/709 for me this worked well.. I do now have an (almost) fully functional Nethunter on my Nexus 6 running Android 7.0 .... Just follow this issue up to where I closed it and you should get it working as well..

**Comment by AutinDroid** [comment]
@malicewizard Hey... A kernel is needed to add support. You don't need to pay me, I'll create it during my free time.

**Comment by malicewizard** [comment]
I appreciated it. BTW once it's done. How would I add it. I'm a noob. But I
learner.

**Comment by BesoBerlin** [comment]
Just flash the --kernel--.zip with TWRP like the installer does it...

**Comment by malicewizard** [comment]
ok. now that i figure that out. i'll be waiting over here for the updated kernel.

**Comment by AutinDroid** [comment]
Creating the kernel now... Give me a few hours (takes time to compile and internet upload speeds are slow for me ):)

**Comment by AutinDroid** [comment]
BTW plz don't flash that nexus 9 kernel, that'll hurt your phone. Nexus 9 and the Nexus 6 are completely different.

**Comment by malicewizard** [comment]
Wow thanks. I've been learning how to do it. But yeah. Internet speed has
stopped me. Like I said before I greatly appreciat what your doing. BTW I
got it install. But extremely buggy. So I uninstall. Did some research on
how to update the kernel. Think I got it. :)

**Comment by malicewizard** [comment]
I don't have 9. Didn't think I did that. If you're talking with me

**Comment by malicewizard** [comment]
well i'm getting impatient. guess it's my time to learn how to do this stuff.

**Comment by AutinDroid** [comment]
@malicewizard Err... There is already a Shamu nougat kernel

**Comment by malicewizard** [comment]
thought you making me one. i've been waiting for a good 5 days lmao

**Comment by AutinDroid** [comment]
@malicewizard already one in build.nethunter.com/nightly

**Comment by malicewizard** [comment]
How would i add this? is there a link i could read or? i appreciate it

**Comment by AutinDroid** [comment]
@malicewizard https://build.nethunter.com/nightly/3.15.4-20170110-1420/kernel-nethunter-shamu-nougat-3.15.4-20170110-1420.zip flash the file via twrp

**Comment by malicewizard** [comment]
ok. Last question. is it before or after i install nethunter. like when it's booting up. i load up twrp. click flash with the zip and i should be good.

**Comment by akrolla** [comment]
Check again @autindroid just replied 5 minutes ago

**Comment by AutinDroid** [comment]
@malicewizard any time is ok; before or after is fine.

**Comment by malicewizard** [comment]
well for some unknown reason. i can't get kail to install now. it stop at 90% waited 10 minutes. so i turned it off. Now keep in mind. this isn't the first time i got an error. the second time it install, it said complete. so i  restarted, then it said no command. so i did the. Soft-bricked/bootloop. got it back to stock. now this time it stop at 90% Now the first time install nethunter it stop at 70%  i waited 10 minutes. nothing happen. so i turned it off. turn it back on and Net hunter work!!. but for some reason i thought i did it wrong. because it wasn't working the way i thought it was supposed to. so i wipe it. tryed to install it again and got the install complete! this time. restarted and got the No command when it booted.  

So that leave me to where i am now. i'm going to try again. but not install everything when it says. would you like to install these with it.

**Comment by AutinDroid** [comment]
@malicewizard Err... Never use the official package, use the nightly zip I gave you and this nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170110-1420.zip

**Comment by malicewizard** [comment]
well how am i going to install nethunter i'm i'm using the 8.38 mb. when i should be using the 655 mb one from the main site. isn't that what the website said to do. install that one. once it's done. then use nexus root toolkit. look for advance utilities. click custom recovery. it loads up. then flash the zip you gave me. 

that's what i'm getting at. or do you want me to do it before then install nethunter.

**Comment by AutinDroid** [comment]
https://github.com/offensive-security/kali-nethunter/wiki#40-installing-nethunter-on-your-android
Sigh... Flash the two zips above via TWRP and your done. As simple as that. Order does not matter. The official site's installer is old and deprecated, nightlies work.

**Comment by malicewizard** [comment]
well from several hours from getting the download to be stable. got it downloaded. flash the kernel. install kali and it worked! Now to properly configure it. never got this far before. Thank you AutinDrioid. if there was a way to give a Thumbs up i would. appreciate it.

**Comment by malicewizard** [comment]
one question. should i buy the recommended card that is posted on the website. or would you have another in mind. Thank you. that's the last question. i swear :)

**Comment by jcadduono** [comment]
awus036neh
