### ISSUE TITLE
TP-LINK TL-WN722N not working with hammerheadmon Nougat

### ISSUE THREAD

**Issue by malokoum** [offensive-security/kali-nethunter#728]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
CM14 Nougat

### Built from repo (date and build command) or downloaded from website (links):
https://github.com/offensive-security/kali-nethunter
2016-12-21
python2 build.py -d hammerheadmon -n --rootfs full

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-g1262232-dirty (autintech@autintech) (gcc version 4.7 (GCC) ) #2 SMP PREEMPT Sun Dec 11 16:08:30 EST 2016

## Issue:
Hi,
ar9271 not working...

kali root terminal:
```
root@kali:~# apt-get install firmware-atheros 
root@kali:~# cp -r /lib/firmware /sdcard
```

android su terminal:
```
root:/# mount -o remount,rw /system
root:/# cp -r /sdcard/firmware /system/etc
```
reboot device and replug my wifi...

![screenshot_20161230-211910](https://cloud.githubusercontent.com/assets/24650954/21572223/2ab820c8-ced7-11e6-9f09-964be95f94e7.png)

Help me please :(

**Comment by jcadduono** [comment]
we build all of our kernels with wifi modules staticly built in, so you don't ever need to load them, and the firmware comes with the kernel installer so you don't need to install that either (the kernel does not load firmware from chroot!)

use the set wlan1 monitor mode custom command from nethunter app to bring your device up

also, provide dmesg of unplug/replug (pastebin, surround with ``` on here, or google drive) - logs tell us if your device is being recognized or if the driver is just missing

**Comment by malokoum** [comment]
thx @jcadduono :+1: 
it work with hammerheadcm kernel
