### ISSUE TITLE
ChromeOS kernel patching support (Pixel C)

### ISSUE THREAD

**Issue by AutinDroid** [offensive-security/kali-nethunter#733]
### Device: Pixel C (dragon)
 If you haven't heard, the Pixel C was meant to be running ChromeOS, but it was later changed to android. It still has a ChromeOS kernel, which cannot be patched by the NetHunter kernel patcher. I have compiled a kernel for the Pixel C, but the only problem is... I can't test if it fully works with NetHunter. Can you devs please add ChromeOS boot image support (make this my late Christmas gift).
Did I mention... Happy New Year!!!

**Comment by AutinDroid** [comment]
No one :(

**Comment by nethunteros** [comment]
I think we were holding off until TWRP support.  Looks like someone built an unofficial image today: https://forum.xda-developers.com/pixel-c/orig-development/unofficial-twrp-2-8-7-0-pixel-c-dragon-t3288243

**Comment by jcadduono** [comment]
@nethunteros  exactly a year from today ;)

**Comment by nethunteros** [comment]
Oh wow. I am still living in 2016!

**Comment by jcadduono** [comment]
here you go: https://github.com/jcadduono/android_external_libbootimg/commit/35e012599b3a4f0141a33f4e33e6563732d2c8a8

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/commit/c89049d8c068ebe3535af5db6bb290f757ccc35d

part 1 is complete, now all we need to do is add a check for the chromeos file created by bootimg, then trigger futility sign tool before flashing

**Comment by AutinDroid** [comment]
Actually there is a pixel c TWRP 3.0.2-0 support (unnoficial). It works OK. I am fine with using my Pixel C as a test dummy (although, if my tablet had a voice, it would be screaming at me to stop). Just tell me if you need something and I'll be there.

**Comment by jcadduono** [comment]
ima take a nap right now and work on the 2nd part tomorrow, have a kernel image ready eh

**Comment by jcadduono** [comment]
@AutinDroid do you mind joining IRC? I have a test ready.

**Comment by jcadduono** [comment]
https://build.nethunter.com/test-builds/kernel-nethunter-generic-arm64-chromeos-test-1.zip

i really need a recovery log from flashing this, and if it does succeed in flashing, let me know if it still boots!

**Comment by AutinDroid** [comment]
@jcadduono Will test... When my nap is over

**Comment by jcadduono** [comment]
wakey wakey eggs n bakey @AutinDroid

**Comment by AutinDroid** [comment]
@jcadduono Awake... At least half awake. Time to go to work :(

**Comment by jcadduono** [comment]
ur shillin me bro

**Comment by jcadduono** [comment]
https://forum.xda-developers.com/pixel-c/help/unpack-repack-boot-img-info-to-build-t3367835#post70487326

confirmed, it works, have fun, i'll say this is resolved!

**Comment by AutinDroid** [comment]
@jcadduono I tried the script. Pixel C kernel source only compiles into a image.gz, image.fit, and image.lzma and image. After installing the script (chromeOS), the Pixel C will be stuck at the google logo. I have tried with two kernels (Dirty Unicorns, no modification, and google's stock sources, with NetHunter config), and both kernels built wihtout problem. Tried to contact you via freenode nethunter chat, but no response :( (Naptime.... Again?, or am I just a noob at irc?).

**Comment by jcadduono** [comment]
i've very unpredictable when it comes to sleeping, anyways, try booting mine?
https://github.com/jcadduono/android_kernel_google_chromeos/commits/nethunter-7.1

```sh
sudo apt-get update
sudo apt-get install liblz4-tool git-core diffutils colordiff libncurses5-dev

mkdir -p ~/build/toolchain
cd ~/build/toolchain
wget https://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
tar xf *.tar.xz

cd ~/build
git clone git@github.com:jcadduono/android_kernel_google_chromeos google_chromeos
cd google_chromeos
./build.sh
```

**Comment by AutinDroid** [comment]
@jcadduono As your sleep schedule is unpredictable, so is my work schedule :) Will test when I get home

**Comment by jcadduono** [comment]
seems predictable to me, you go to work every time i wake up

**Comment by AutinDroid** [comment]
@jcadduono True...

**Comment by r-nation** [comment]
I went ahead and flashed purenexus rom 7.1.1 and flashed this kernel, https://build.nethunter.com/test-builds/kernel-nethunter-generic-arm64-chromeos-test-1.zip it boots..whats the difference with this kernel and one at the top of this page?

**Comment by r-nation** [comment]
ooops this was meant for other thread.
