### ISSUE TITLE
No NFC device found

### ISSUE THREAD

**Issue by BKDOnions** [offensive-security/kali-nethunter#734]
### Device:
Nexus 7 2013

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:No NFC device found.
root@kali:/# cat /proc/version
Linux version 3.4.0-gcc51ee3-dirty (root@kali) (gcc version 4.7 (GCC) ) #4 SMP PREEMPT Sat Dec 12 00:29:55 UTC 2015
root@kali:/#

**Comment by HazmirulZ** [comment]
Hello @BKDOnions please try this and see if it works.
Download the latest nethunter kernel from this link [https://build.nethunter.com/nightly/](https://build.nethunter.com/nightly/). Select the latest release, download the nethunter kernel base on your device and ROM. And flash it via recovery (TWRP).

**Comment by bkr32** [comment]
dump mifare requires a external NFC adapter from proxmark 
its not a issue with your device or kernel

**Comment by tirailleurdd** [comment]
Hi!
Does anybody find a way to use mfoc/mfcuk tools directly with embeded nfc device?
