### ISSUE TITLE
Cant install FruityWifi alongside nethunter 

### ISSUE THREAD

**Issue by ThatGuy626** [offensive-security/kali-nethunter#736]
### Device:
Nexus 5 Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

https://forums.kali.org/showthread.php?30413-How-to-install-FruityWiFi-v2-4
Nethunter downloaded official marshmallow zip from site

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
nginx Failed to start

## Issue:
Installing nethunter and fruitywifi

**Comment by AutinDroid** [comment]
You, like, got the zip from the official website? Get the kernel package here: https://build.nethunter.com/nightly/ (hammerheadcm-marshmallow) and flash the generic armhf full/minimal. Official builds (official website) is outdated
