### ISSUE TITLE
adapter not working

### ISSUE THREAD

**Issue by bimubuceru** [offensive-security/kali-nethunter#737]
OS version : Marshmallow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.84-perf-g4b39ed7 (builder@c3-miui-ota-bd75.bj) (gcc ve
[dmesg.txt](https://github.com/offensive-security/kali-nethunter/files/685668/dmesg.txt)
rsion 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Dec 2 19:59:39 CST 2016

## Issue:

**LSUSB is showing my adapter but ifconfig or wifite is not detecting it 
so i am not able to use it for wifi pentesting** 

![fgf](https://cloud.githubusercontent.com/assets/24922561/21655954/e1482134-d270-11e6-9ab9-938b15f2c80e.png)

i am also attaching dmesg output 
[dmesg.txt](https://github.com/offensive-security/kali-nethunter/files/685670/dmesg.txt)

**Comment by nethunteros** [comment]
I don't believe that you're using a kernel with atheros support.  What device is this?  I don't recognize the build string as one of ours.

**Comment by bimubuceru** [comment]
i am sorry 
my device is Xiaomi Redmi note 3 (Snapdragon) 
i know this device is not officially supported 
but someone ported nethunter for it 
http://en.miui.com/thread-301258-1-1.html
https://forum.xda-developers.com/redmi-note-3/how-to/guide-kali-nethunter-3-0-android-6-0-x-t3456920


will you please confirm that it is a kernel issue ? 
actually i am confused about its a power supply issue & i should buy a Y cable or its a kernel issue 

& is there any way to fix it 
please help me in fixing this if you want we can use my device for all testing purpose

**Comment by jcadduono** [comment]
no they did not port it they simply posted the hammerhead installer, yes you are running the stock kernel. tell the OP of that thread to take it down or send people to the generic zips and make sure they know they are NOT getting NetHunter OTG capabilities unless someone specifically ports for that device!

**Comment by bimubuceru** [comment]
i tried to contact OP he didnt replied till now 

anyway 
can you help me in porting ? 
if you want we can use my device for debugging.. 

& i flash all those files in my device 
all scripts are working fine.. 
even when i tried to launch wifite,airmon-ng,reaver
didnt gave me any error (their scripts are being executed properly)
its just it is not showing my adapter.. its only showing internal wifi

& in my country a lot of people use this device & want to use nethunter.. 
i will be thankfull to you if you help me in get it working properly

**Comment by chinna123123** [comment]
Same problem tl wn722n and pau05 and tl wn822n not work in redmi note 4 nethunter os
Somebody help me how to fix this problem
