### ISSUE TITLE
Terminal Emulator (com.offsec.nhterm) bug

### ISSUE THREAD

**Issue by P1ut0n** [offensive-security/kali-nethunter#738]
### Device:

Google Nexus 5 Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

LineageOS 14.0 (android 7.1)

### Built from repo (date and build command) or downloaded from website (links):

LineageOS 14.0-20170102-UNOFFICIAL ( NethunterOS )
https://build.nethunter.com/nethunteros/CM14_1/hammerhead/LOS-hammerhead-14.1-20170102-nethunteros.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-gfd77543 (root@nh-buildbox) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Mon Jan 2 12:49:19 CST 2017

## Issue:

When launching the Terminal Emulator app (com.offsec.nhterm) after flashing and after every reboot of my Nexus 5, the app first show : 

![screenshot_20170107-145313](https://cloud.githubusercontent.com/assets/24975404/21742199/d8acbe74-d4e9-11e6-9144-86a6dba89a54.png)

When I click on one of the 3 possibilities the app just crashes. It happen also if I launch the NetHunter app before.
Furthermore, when i open up the NetHunter app and launch any of the Custom Commands, i.e. Update Kali Metapackages, it won't do anything.

Here's how I managed to solve the problem to get the terminal app running and giving me a kali shell : 

 - I open the NetHunter app and start any Kali Services (i.e. SSH). After that I launch the Terminal Emulator app, and it will work until I reboot my phone again.

 - I open another Terminal Emulator app like the jackpal.androiterm one and : 
       hammerhead:/ $ su
       hammerhead:/ # bash /data/data/com.offsec.nethunter/files/scripts/bootkali
       root@kali:~# exit
       hammerhead:/ # exit
       hammerhead:/ $ exit
  Then if I launch the Terminal Emulator (com.offsec.nhterm) it will work until I reboot my phone again.

Any idea on where this problem comes from?
If you need the logcat or else just ask.

**Comment by nethunteros** [comment]
I was experienced same issue on OnePlus1.  I fixed issue by going to settings > app > nethunter > force stop > clear cache.  Then relaunching nethunter app.  I'm  a bit unsure whats causing this issue at the moment and need to spend more time on it.

**Comment by SecurityAddicted** [comment]
It's a problem with SELinux. See #726

**Comment by akrolla** [comment]
any idea for a startup script to run this at startup? in android background in nh custom commands?

**Comment by akrolla** [comment]
nvm

**Comment by akrolla** [comment]
su
bash " \data\data\com.offsec.nethunter/files/scripts/bootkali"

**Comment by akrolla** [comment]
until the sym link issue would it be possible to add a startup script doing this to circumvent the problem for the time being?

**Comment by akrolla** [comment]
i can only run one kali terminal at a time for the custom command

**Comment by akrolla** [comment]
anybody know how i could launch wifite or something with an addition to the script?

**Comment by jcadduono** [comment]
@akrolla this is not your issue, this is the selinux issue, you will have symlinks if you install nethunter properly

**Comment by akrolla** [comment]
I Installed it how it was written in the gist. I was suggesting it as a
custom command for hin if itvwasntvfixed

**Comment by akrolla** [comment]
Binkybears fix worked on nexus 5

**Comment by marcusguita** [comment]
Hi all,

I have same issue in OnePlus 2, and after installed "termux apk", I do this steps and after its working:

`su`
`pm uninstall com.offsec.nethunter`
`pm uninstall com.offsec.nhterm`

Then install ones from this repo:
https://github.com/offensive-security/kali-nethunter/raw/master/nethunter-installer/update/data/app/Term-nh.apk
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/nethunter.apk

This mentioned in issue 604 by @binkybear 
https://github.com/offensive-security/kali-nethunter/issues/604#issuecomment-252459410
