### ISSUE TITLE
HID Interfaces: no HID Interfaces detected. 

### ISSUE THREAD

**Issue by BZBaXraM** [offensive-security/kali-nethunter#741]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.112-cyanogenmod-g8fbc62e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016

## Issue:
Hi. What's problem? HID Interfaces no detected. I use from build.nethunter.com.  Please help me!!!

**Comment by jcadduono** [comment]
app probably didn't have root to see them, theyre probably there, open a kali terminal and do:
`ls /dev/hidg*`
see them?

**Comment by BZBaXraM** [comment]
I see root@bacon:/ # ls /dev/hidg*
/dev/hidg0 /dev/hidg1
root@bacon:/ #

**Comment by jcadduono** [comment]
then yup just the app not looking under root privileges it should still work

**Comment by SuzumiyaXZ** [comment]
hi，
Do you hava flush the kernel?
