### ISSUE TITLE
Duckhunter - Letter "g" or "G" not send to Windows 7 (DE)

### ISSUE THREAD

**Issue by r1b3y3** [offensive-security/kali-nethunter#742]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Mashmallow (CM 13.1)

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.4-20170107-1635/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-g5e6aa13 (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Sat Apr 2 20:23:25 CDT 2016

## Issue:
Hi @all,

I try to get HID attacks working. My first attempt was to use the example script "Hello World". If i trigger it attached to a linux box  i see the whole output:

Hello world!
Example of typing to computer. Nethunter is awesome!
I slept for 5 seconds, now I'm awake!
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
1234567890-=!#$%*()_+
\;',./:"<>?

on the windows boxes (german language):

Hello world!
Example of typin to computer. Nethunter is awesome!
I slept for 5 seconds, now I'm awake!
abcdefhijklmnopqrstuvwxyz
ABCDEFHIJKLMNOPQRSTUVWXYZ
1234567890-=!#$%*()_+
\;',./:"<>?

The letter g is missing. So i cannot use "wmic volume get" or mimikatz "logonPasswords". Weired...

Greets and thank u for your awesome work!
R1b3y3

**Comment by BesoBerlin** [comment]
Hi!!!
Hier die Lösung... 
https://github.com/offensive-security/kali-nethunter/issues/556

**Comment by BesoBerlin** [comment]
#556
