### ISSUE TITLE
Pixel C support - NEED TESTERS

### ISSUE THREAD

**Issue by jcadduono** [offensive-security/kali-nethunter#743]
### Device:
Google Pixel C (dragon / ryu)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
7.1.1 Nougat

## Issue:
We need testers who can provide logs, you can obtain these using in TWRP:
`adb pull /sys/fs/pstore`
then upload the pstore folder somewhere.

If the kernel does boot, you can provide a dmesg instead.
`adb exec-out dmesg > dmesg.log` (done in Android OS)

I suggest grabbing a recovery.log immediately after flashing (before booting) in TWRP:
`adb pull /tmp/recovery.log`

### Download:
Test `#1`: https://build.nethunter.com/test-builds/google/kernel-nethunter-dragon-nougat-test1.zip

NetHunter apps/rootfs: https://build.nethunter.com/nightly/3.15.4-20170110-1420/nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170110-1420.zip
(do not flash until after kernel confirmed to boot)

Kernel sources: https://github.com/jcadduono/android_kernel_google_chromeos (if interested)

### Items to check:
`[ ]` Does it even boot?
`[ ]` HID gadget (Duckhunter)
`[ ]` WiFi OTG (Monitor mode enable, Wifite)
`[ ]` OTG NFC devices?
`[ ]` RTL-SDR (Bluetooth)
`[ ]` NetHunter Terminal -> Kali boots?
`[ ]` F2FS - do f2fs data partitions boot? (backup data, internal storage to pc, format data as f2fs, enable use rm -rf mode in options, restore data, boot)
`[ ]` exFAT - does exFAT formatted storage mount? (unlikely, using OTG flash drive/sd reader, should mount manually in Kali though)

Please post the output of `cat /proc/version` with your reports.

## Have fun!

**Comment by AutinDroid** [comment]
Sorry, I forgot to check NetHunter issues :p Will be testing now

**Comment by r-nation** [comment]
Hello..
I'm on a rooted pixel c on 6.0.1 marshmallow w/3.18.0-xceed kernel. I could push the nethunter app to pixel but wouldn't be able to use the kali-rolling repositories since the kernel wouldn't be 3.4, i could send you money if you could compile your kernel for 6.0.1. I tried 7.1 but flashed back as it broke xposed and other apps and i really really dont wanna use 7.1, thanks in advance.

**Comment by r-nation** [comment]
I went ahead and flashed purenexus rom 7.1.1 and flashed this kernel, https://build.nethunter.com/test-builds/kernel-nethunter-generic-arm64-chromeos-test-1.zip it boots..whats the difference with this kernel and one at the top of this page?

**Comment by r-nation** [comment]
I stand corrected the kernel version dosen't change and the dragon kernel in nethunter nightlies absolutely refuses to flash. I've literally tried everything, whether its stock firmware 7.1.1 or purenexus7.1.1, I am systemless root but system only supersu results in bootloop on stock and purenexus roms. I even temporarily disable selinux before flashing just in case..nothing but bootloops and system isn't responding..frustrating

**Comment by miLstipple** [comment]
well im new to linux but trying to learn it. Have Pixel C running 7.1.2...... safe to try and flash it? im running elemental 1.09 Kernal
