### ISSUE TITLE
USB keyboard crashes on start on nexus 6

### ISSUE THREAD

**Issue by fantoro** [offensive-security/kali-nethunter#745]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

**Comment by jcadduono** [comment]
open a androidsu shell and do "setenforce 0"
then try again

**Comment by fantoro** [comment]
Thanks, I got also another weird problem, when I reboot and turn on terminal and choose any shell, terminal will crash and I have to turn on any kali service.
