### ISSUE TITLE
Terminal Emulator crashes on every shell.

### ISSUE THREAD

**Issue by BerndGrillt** [offensive-security/kali-nethunter#747]
### Device:
Nexus 6P

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170110-1420/nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170110-1420.zip
https://build.nethunter.com/nightly/3.15.4-20170110-1420/kernel-nethunter-angler-nougat-3.15.4-20170110-1420.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Well ... XD

## Issue:
Terminal Emulator crashes on every option. Even when i select android.

**Comment by jcadduono** [comment]
no helpful information

**Comment by BerndGrillt** [comment]
"no helpful information" ... Can you at least say, what kind of information you need ... I cant open any terminal

**Comment by jcadduono** [comment]
ever heard of adb?

**Comment by BerndGrillt** [comment]
No. Do you want me to get the Version over adb?
