### ISSUE TITLE
vdc ecryption not working 

### ISSUE THREAD

**Issue by gregstula-autoreleasepool** [offensive-security/kali-nethunter#748]
### Built from repo (date and build command) or downloaded from website (links):

downloaded from nightly build repo 
https://build.nethunter.com/nightly/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

u0_a114@ailsa_ii:/ $ cat /proc/version
Linux version 3.18.46-nethunter-ailsa_ii-3.0 (jc@westerley) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Sat Jan 7 13:51:16 EST 2017
u0_a114@ailsa_ii:/ $

## Issue: Encryption not working

Encryption is disabled by default when Kali is installed. Also, you need to format end erase encryption in order to install it. Axon 7 UI provides no enable encryption button in Settings -> Security.

So I did `mv /user/local/userinit.sh /user/local/userinit.sh.old` 

then

`vdc cryptfs enablecrypto inplace password [my password]`

that just resulted in a reboot with Encryption still disabled

I also tried the vdc command with the wipe option and it did nothing.

 Is there any way to encrypt this phone with Kali installed?

**Comment by jcadduono** [comment]
there actually isn't!

ZTE broke encryption, not me

it doesn't even work on stock!

**Comment by gregstula-autoreleasepool** [comment]
I actually solved it! 

First wipe and install CM13. Then setup password to start system in settings. Then wipe and install stock rom. Encyrption will remain and you will need a password to mount on boot.

**Comment by jcadduono** [comment]
i'm not supporting CM13 though so the kernel will probably not work

**Comment by gregstula-autoreleasepool** [comment]
Yes, I only used CM13 (kernal works but no wifi btw I tested it this morning) to enable encryption. I'm running stock rom with CM13's leftover encryption now
