### ISSUE TITLE
Nethunter App does not have permission to send to Nethunter Terminal

### ISSUE THREAD

**Issue by K3EPZ** [offensive-security/kali-nethunter#749]
### Device:
OnePlus 3T

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marsh 6.0.1

### Built from repo (date and build command) or downloaded from website (links):
https://pa2.androidfilehost.com/dl/uUSAvaKb8usfrBvHNIyaVQ/1484651631/457084094631642134/nethunter-cm13-6.0.1-20160925-full.zip?

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux 3.18.20
GGC 4.9.X

## Issue:
I can´t use anything because it doesn´t allow to use the terminal? Before was no terminal but somehow fixed it
I´ve downloaded Termux & the terminal from the repo

**Comment by jcadduono** [comment]
random unknown zip, not supported
