### ISSUE TITLE
Nethunter size (question more than issue) 

### ISSUE THREAD

**Issue by mpkosewski** [offensive-security/kali-nethunter#751]
### Device:
Nexus 7 2013

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 

### Built from repo (date and build command) or downloaded from website (links):
Nethunter 3.15

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gae95f7e-dirty (root@nhbuild-box) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Jul 29 23:09:11 CDT 2016

## Issue:
Mostly curious about the install size of nethunter. On my nexus 7 after install,  my storage space is 9.14gb used of 12.2gb. Is that a normal install size? 

Thanks in advance

**Comment by jmingov** [comment]
Hi @mpkosewski, last time i checked the kalifs w decompressed was a bit more than 2GB, the rest are meta-packages installed after the kalifs via apt-get, a full install of the meta-packages should be ~20GB almost like a normal kali install.

**Comment by mpkosewski** [comment]
Damn. I didn't know all the metapackages took up that much. I figure just doing the nethunter chroot would be enough for nexus

**Comment by akrolla** [comment]
it will be and its significantly smaller
