### ISSUE TITLE
Speaker not functioned in Nexus 6 (Nougat 7.1.1)

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#752]
### Device:
Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.1.1 (latest build from official factory image)

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.4-20170116-1311/kernel-nethunter-shamu-nougat-3.15.4-20170116-1311.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40kali-g1d7b23e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #4 SMP PREEMPT Thu Aug 25 18:56:08 CDT 2016

## Issue:
No sound present in speaker, but works fine with headphone, it still can record sounds, just not able to output sound. I think maybe this kernel was not built with latest source code???
Except for this, anything seems work fine here. 

I also tried to do `dmesg | grep "audio"` to see if it gives me useful info for you guys, it may not be useful tho.
[https://drive.google.com/open?id=0B-cBdArdvHDxU0lyUVhodGFwM0k](https://drive.google.com/open?id=0B-cBdArdvHDxU0lyUVhodGFwM0k)

**Comment by jcadduono** [comment]
@binkybear

**Comment by simonpunk** [comment]
@binkybear Hi, any ideas?

**Comment by binkybear** [comment]
I'll give kernel a pull & update.

**Comment by simonpunk** [comment]
@binkybear Thank you very much!! and sorry for taking your time!!

**Comment by mendozadelsur** [comment]
same problem here

**Comment by simonpunk** [comment]
@binkybear Thank you very much!  Sound issue fixed, and the rest are working fine as well, I think it's back to normal now. Thank you!

**Comment by styky** [comment]
I am having the exact same problem except I am on Android 7.0,  I updated my kernel to;
Linux version 3.10.40kali-g90f4f12 (root@nhbuild-box) Wed Jan 25 18:18:56 CST 2017 but the problem persists, any help appreciated.

**Comment by lewixlabs** [comment]
Hi,
i have same device & issue (audio not working on speakers).
Hi built today a kalihunter image with kalihunter-installer (python script build.py).
How can i get your kernel image updated?

Thank you for any help.
Lewix

**Comment by dimpol** [comment]
Is there a nougat nexus 6 kernel in the nightly web page that is known to have sound working as expected?
