### ISSUE TITLE
GUI Enhancement

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#753]
### Device:

all

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

all

## Issue:

in the process of making a GUI outside the NH for for the total environment and the OS...would like some feedback of some tools you would like to see added to this project. nothing that is already provided by nh app. i know this is available in the app but i believe making a gui would make the tools easier to access, and also could cut down on confusion about how to use that wonderful function inside, essentially, the guis are just pictures relating to the shellscript that will be preconfigured and run whatever tool is clicked on. also tools you would like to see added to the kalifs that could benefit the environment are welcome also.

**Comment by akrolla** [comment]
also anybody with experience is awesome too! i'm just learning to do this! As i believe it is very possible to make a whole nethunter ecosystem and this would further us up the path, also, a list of apps that you may want to download if say ...an app store was made

**Comment by akrolla** [comment]
unless of course everyone comes to the determination this is useless, and/or redundant

**Comment by vay3t** [comment]
I long ago suggested sqlmap in the apk

**Comment by akrolla** [comment]
roger that.

**Comment by akrolla** [comment]
keep coming up with a decent sized list ima try my best to churn some of thes out but i think im going to still need help as i am learning android studio for this project, and could def use outside criticism / help

**Comment by vay3t** [comment]
try view: mitm code https://github.com/offensive-security/nethunter-app/blob/master/src/com/offsec/nethunter/MITMfFragment.java

**Comment by akrolla** [comment]
isnt MItMf offered inside the nh app?

**Comment by akrolla** [comment]
sqlmap , wifite are potential candidates,  perhaps pyrit, t shark,

**Comment by akrolla** [comment]
poison tap

**Comment by akrolla** [comment]
id like to gear this more twards the nexmon supported devices, so when we write the scripts we can configure them to automatically configure and use wlan0mon at startup, also a app store to download diff tools.

**Comment by akrolla** [comment]
the airmon-g suite
