### ISSUE TITLE
tried to do a symlink for bootkali and etc. on Nexus 5

### ISSUE THREAD

**Issue by akrolla** [offensive-security/kali-nethunter#754]
### Device:

nexus 5 
### OS version (KitKat/Lollipop/Marshmallow/Nougat):

cm 14 nethunterOS 7.11 

### Built from repo (date and build command) or downloaded from website (links):
from the Gist

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

 Linux 3.4.0-g15ae70a (root@nh-buildbox)

## Issue:

i tried doing a symlink using

su
# ln -s /system/bin /data/data/com.offsec.nethunter/files/scripts

**Comment by akrolla** [comment]
it accepted the symlink but didnt work

**Comment by akrolla** [comment]
@jcadduono @binkybear

**Comment by jcadduono** [comment]
not 100% sure but you might be able to just flash the 60 mb generic zip on it

**Comment by akrolla** [comment]
I got the terminal working through the shell script but id like to make an
edition to it to open more than one terminal. This way only opens one and
closes it eveytime u rerun

On Jan 19, 2017 10:59 PM, "James Christopher Adduono" <
notifications@github.com> wrote:

not 100% sure but you might be able to just flash the 60 mb generic zip on
it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/754#issuecomment-273977983>,
or mute the thread

**Comment by akrolla** [comment]
I don't want to risk breaking it agn nexmon works great.

**Comment by BZBaXraM** [comment]
What is nexmon?

**Comment by akrolla** [comment]
some firmware that enables the broadcom chip inside the phone to sniff and
inject packets.
