### ISSUE TITLE
No service, but SIM card detected, Kali-nethunter rooting and installing problems

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#755]
### Built from repo (date and build command) or downloaded from website (links):
Offical documentation for kali linux, rooting it from the kali linux OS

## Issue:

Hi guys,

I was installing Nethunter via Kali-linux and I followed the main documentation step by step, then I came across a problem because I was using USB 3.0 (I'm guilty because I did not use USB 3.0 or else I know everything would have ran perfectly).

The following commands worked ./oemUnlock.sh, ./stockOpoFlash.sh 64gb. The last command which was ./twrpFlash.sh after running it for while it came up with an error which something like "No device emulator found". So I ran the command ./stockOpoFlash.sh 64gb and then Hard bricked my phone somehow, the phone kept connecting and disconnecting when plugged into my laptop. When I tried turning it on it wouldn't turn on and it was just a black screen.

I have a Oneplus One 64gb. After realizing I had hard bricked the phone, I manged to fix it after following instructions from:
https://www.reddit.com/r/oneplus/comments/3izejg/so_youve_just_bricked_your_oneplus/
Thanks to this guy or guys ^^^^^^^^ respect fo real.

Now after installing Cm 13.2.1 Bacon it says no service, I cant, call or text, but it sure detects my sim card. I have followed all instructions from forums and goggled it, finally I came to ask who can help me.
Help would be much appreciated. Story of my life <----- Lesson learn't. oh well at least I learnt how to unbrick a phone.

Main question is

After a successful kali nethunter install, can we use the phone normally? Like call, text etc....
Please help me, I want to make sure that I can call/text before I can start kali-nethunter install again using usb 2.0 this time.

**Comment by jcadduono** [comment]
kali nethunter only adds features, it does not remove them

**Comment by mpkosewski** [comment]
Yeah your phone should work with kali nethunter no problem. If you're having issues with that, then it's probably something with your Android OS. I'd reflash stock firmware first, check if it works then install nethunter.

**Comment by akrolla** [comment]
You probably have to change access point name of your network

**Comment by akrolla** [comment]
as for the other stuff , it sounds as if a incomplete install

**Comment by mpkosewski** [comment]
If you need help setting up your apn settings, just Google your carrier + "apn settings". Like for Att, Google "Att apn settings" and it'll tell you how to set it up. Though with stock flashing, it should be setup automatically

**Comment by marshalsahu** [comment]
I am facing the similar problem. What did you do to overcome?
