### ISSUE TITLE
NetHunter Installer Won't Download SuperSU

### ISSUE THREAD

**Issue by thejtshow** [offensive-security/kali-nethunter#758]
### Device:
Nexus 10

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

### Built from repo (date and build command) or downloaded from website (links):
Repo on 1/19/2017; `python build.py -d manta -l`; python version 2

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Can't get installed

## Issue:
Trying to build a nightly release for my Nexus 10 fails due to a certificate error when trying to download SuperSU. Was able to work around this by changing the script from `https` to `http` on the superSU getdlpage function, but the install failed completely. TWRP won't even open the zip. Not sure if related, but prevented me from testing this workaround.

**Comment by thejtshow** [comment]
Error Output:
```bash
Connection error: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Error: Could not retrieve download URL for SuperSU
```

**Comment by jcadduono** [comment]
i'm unable to reproduce either of your problems

**Comment by thejtshow** [comment]
I think I found my problem -- ID10T error. Was trying to run this in bash on ubuntu on windows. Will confirm but I'm willing to bet that is what caused this.

**Comment by thejtshow** [comment]
Confirmed. Was able to download everything fine on a full OS. I always forget bash on ubuntu on windows has networking problems.

**Comment by rubencabrera** [comment]
I didn't find this issue anywhere else, when trying to build with 
$ python build.py -d shamu -n
I get:
Finished downloading all apps
Connection error: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Error: Could not retrieve download URL for SuperSU

**Comment by rubencabrera** [comment]
In case someone has the same issue I had:
Run the build with
python build.py -d shamu -n -f -ns
The -ns flag avoids trying to download SuperSU, so you have to find it on your own, place it in the SuperSU folder of nethunter-LRT and follow installation procedure as documentation leads.

**Comment by NorvegianGoat** [comment]
`Connection error: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
Error: Could not retrieve download URL for SuperSU`
While I'm trying to download supersu I've this error, I'm going to try not to download it by using @rubencabrera 's solution.
