### ISSUE TITLE
Drivedroid error

### ISSUE THREAD

**Issue by majackov** [offensive-security/kali-nethunter#762]
### Device:
Oneplus3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Built from nh repo

## Issue:
Drivedroive doesnt work. Video http://rgho.st/private/7pvy8jZ8c/e73805d960e3c1254f565337c99c08be

**Comment by jcadduono** [comment]
no useful info or logs

**Comment by majackov** [comment]
Output of cat /proc/version in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-3.0 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Sun Jan 22 21:50:48 EST 2017

**Comment by jcadduono** [comment]
need logcat of drivedroid crashing

**Comment by majackov** [comment]
Drivedroid didnt crash (look video). Logcat http://rgho.st/8bxCqKWFt (when I try to select an usb system)

**Comment by majackov** [comment]
And adb bugreport log http://rgho.st/private/8htX6LGVc/7e294ea464f46c52e315b550f82868c3

**Comment by jcadduono** [comment]
can you please use another site / upload in non-rar

**Comment by majackov** [comment]
Non-rar http://rgho.st/private/7qPRQ6PPS/12f1bda5a859e42ac0c4cc1b52c59960

**Comment by jcadduono** [comment]
the log doesn't make sense, audits are showing permissive=0 yet the nethunter kernel is forced permissive, are you sure the kernel was installed while getting that log?

**Comment by majackov** [comment]
Yes. 
Because I have working nethunter on phone.
And output of cat /proc/version in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-3.0 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Sun Jan 22 21:50:48 EST 2017
A month ago drive droid was working (on Android 6)

**Comment by jcadduono** [comment]
get full dmesg from boot up

**Comment by majackov** [comment]
http://rgho.st/6hBy6fCpZ
There 2 files (readme):
dmesg1.txt - output of "adb shell dmesg" after boot up
dmesg2.txt - output of "adb shell dmesg" after boot up and opening drive droid

**Comment by majackov** [comment]
Downloaded beta version (and maybe enabled OEM unlock in dev options) and all are working!
