### ISSUE TITLE
Manual Chroot removal

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#763]
### Device:

Oneplus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

Latest Repo 
27/01/17
python build.py -d oneplus3 --marshmallow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-ElementalX-OP3-0.15 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #5 SMP PREEMPT Mon Nov 21 17:40:25 CST 2016

## Issue:

Current chroot removal method no longer funtional. Would like to know correct way to remove chroot for a fresh install.

**Comment by jcadduono** [comment]
if you are just updating from nightlies, selecting a kalifs zip will remove old chroot and put new one in.
otherwise, all you need to do is open androidsu terminal and `rm -rf /data/local/nhsystem/kali-*`

**Comment by ozsteyr** [comment]
Tried installing kalifs.zip, no errors, but nothing changed either.
Anyway, are there any other issues with nougat on the OO3?

**Comment by jcadduono** [comment]
don't know, only issue reported to me other than that is mac changer doesn't work.
i don't imagine it works on OOS3 either.

**Comment by ozsteyr** [comment]
Sorry I meant my OP3. Will try nougat now. CHEERS

**Comment by mcklyren16** [comment]
is this safe ?

**Comment by 3xpl01ts** [comment]
@mcklyren16 if you get a single symbol in that command wrong, you could brick the hell out of your device. I'd suggest deleting the chroot with some kind of root file manager like ES File Explorer.

**Comment by jcadduono** [comment]
Use the File Manager in TWRP to select /data/local/nhsystem and delete it.
That should be sufficient if you don't plan on reinstalling.
If you are just reinstalling a newer nethunter you don't need to delete it at all. The installer will safely remove an old chroot before installing the new one.

Do not delete it while booted into the device as it could be mounted and you risk deleting all your data along with it.

**Comment by mcklyren16** [comment]
the problem is cant remove the chroot using nethunter apk. i need to
manually remove it

**Comment by 2014rafael2014** [comment]
@jcadduno I try with File Manager in TWRP but I dont know why my phone shutdown. What is the other whay to remove this files/folders?

**Comment by 2014rafael2014** [comment]
@jcadduno I remove rm -rf /data/local/nhsystem/kali-* but occours another error when I will install a ROM
![20170614_172619](https://user-images.githubusercontent.com/8702456/27153208-e8fb7ca2-5126-11e7-895c-2ded36f29aa8.jpg)

**Comment by jcadduono** [comment]
that's not a recovery install zip, that is a fastboot install zip, google how to install factory nexus roms
