### ISSUE TITLE
LG -D821 Nexus 5  Unable to fetch updates at all  

### ISSUE THREAD

**Issue by mayday77** [offensive-security/kali-nethunter#764]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.0.1

### Built from repo (date and build command) or downloaded from website (links):
nethunter-hammerhead-marshmallow-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gcf10b7e ( android-build@wpiv.hot.corp.google.com) gcc version 4.8 (GCC) #1 SMP PREEMT Mon sep 19 22:14:08 UTC 2016

## Issue:
Not updating , at all ! apt-get not working , Unable to fetch

**Comment by mayday77** [comment]
Sorry,can't figure out, how to fix it ?

**Comment by jcadduono** [comment]
see the wiki on github on how to install nethunter (use nightly mirror)

**Comment by akrolla** [comment]
https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e
