### ISSUE TITLE
Camera doesnt work

### ISSUE THREAD

**Issue by majackov** [offensive-security/kali-nethunter#765]
### Device:
Oneplus3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Date build: 2017-01-23
build.py -d oneplus3 -n -fs full

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-3.0 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Sun Jan 22 21:50:48 EST 2017

## Issue:
Camera doesnt work after flashing nethunter kernel. Error message - "Unknow error"
Short video (10 secs) - http://rgho.st/private/7JZLQnQX9/78c25e13a218bc276ca08c43cbfebef7
Adb logcat - http://rgho.st/private/8Mcwbjqsm/9bb5742d7ef54e29ef6ceacbdcc07a7d

**Comment by jcadduono** [comment]
Fixed yesterday

**Comment by ozsteyr** [comment]
@majackov
Just curious, I can't flash OOS 4.0.2 / Error 7.
Googled fixes with zero luck, did you have any problems?

**Comment by majackov** [comment]
@ozsteyr, no.
Try to install last TWRP and wipe data (before backup it). 
Proof http://rgho.st/8By7C4XwZ
But I think after nethunter kernel gestures doesn't work (I didn't check them before flashing NH kernel)
