### ISSUE TITLE
Is Oxygen OS 3.5.6 supported in the latest Nethunter Nightly build for OnePlus 2

### ISSUE THREAD

**Issue by shivsah** [offensive-security/kali-nethunter#766]

**Comment by graybot666** [comment]
Installed perfectly... but some errors come up when running terminal commands... probably did something wrong on my end..

**Comment by shivsah** [comment]
So there are no issues like last time in Oxygen OS 3.1 where after using Duckhunter HID the phone wouldn't connect in Mass Storage mode and we had disable and re-enable USB Debugging to get it to work

**Comment by graybot666** [comment]
Still havent tested everything... but i tried hello world in usb charging mode.. worked fine.. and it is going back to mtp... so i think it's good.. was facing some problems with chroot removal but I fixed now..

**Comment by shivsah** [comment]
Can you provide me with your build as I don't have my Linux system with me right now... Its would be really helpful... Thanks



On Sat, Jan 28, 2017 at 12:35 PM +0530, "graybot666" <notifications@github.com<mailto:notifications@github.com>> wrote:


Still havent tested everything... but i tried hello world in usb charging mode.. worked fine.. and it is going back to mtp... so i think it's good.. was facing some problems with chroot removal but I fixed now..

**Comment by graybot666** [comment]
Sure.. should i mail it to you? I built using build.py script but for some reason when i installed it didnt   install the actual nhunter app and nhunter terminal.. had to download seperately..

**Comment by shivsah** [comment]
Sure just mail me the link... And let me know in the future if you are building one....



On Sat, Jan 28, 2017 at 12:45 PM +0530, "graybot666" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure.. should i mail it to you? I built using build.py script but for some reason when i installed it didnt install the actual nhunter app and nhunter terminal.. had to download seperately..

**Comment by shivsah** [comment]
@graybot666 still waiting for the link... E-mail id:- sahshivam@outlook.com.  Thanks

**Comment by edlovesiraq** [comment]
Oneplus2 , I can't get a terminal after I updated to Oxygen 3.5.6 or I would give you the info. Kali menu is still there, when I check update, it says it's the latest version. Says it has root, but custom commands all fail, and getting a kali terminal fails. When I try to start a kali terminal i just get 1)No Title.

Going to try re-downloading the zip and re-installing, if that fails I'll roll oxygen back.. I miss my nexus 5 and the OP2 has not been the upgrade i had hoped for. Drive droid doesn't work and now this =/   
nexus 5 worked like a champ!

**Comment by graybot666** [comment]
im facing the same ussue with drivedroid as it doesnt work.. dont know
why.. but about the other issues do you have proper kali-chroot installed?
@ed
Im using oos3.5.6 and kali terminal seems to work fine.. tested all the
ducky scripts and they worked too..

**Comment by edlovesiraq** [comment]
@graybot666 Kali-Chroot is the current but I upgraded from OOS2.1 over OTA. I'm sure thats what did it. I'm going to back up everything start from stock kernal and do a fresh install after I'm up to OOS 3.5.6. I'll let you know how that goes.  
Does anyone know of Boeffla kernal on OP2 enables Drivedroid (USBmassstorage?) or has anyone cracked the OP2-Drivedroid?  I have a good copy of KONBOOT that has been great in the past when I was using nethunter on a nexus5, so i'm gutted that I can't get it up on my oneplus2.

**Comment by shivsah** [comment]
Did you tried setting your SELINUX Mode to Permissive

**Comment by graybot666** [comment]
@graybot666 <https://github.com/graybot666> Kali-Chroot is the current but
I upgraded from OOS2.1 over OTA. I'm sure thats what did it. I'm going to
back up everything start from stock kernal and do a fresh install after I'm
up to OOS 3.5.6. I'll let you know how that goes.
Does anyone know of Boeffla kernal on OP2 enables Drivedroid
(USBmassstorage?) or has anyone cracked the OP2-Drivedroid? I have a good
copy of KONBOOT that has been great in the past when I was using nethunter
on a nexus5, so i'm gutted that I can't get it up on my oneplus2.


Yes thats gotta be the problem. I flashed the full signed OTA. Then when ur
phone is stock again go to oos updates.. update &install oos 3.5.6 (i think
this also clear my recovery so i flashed TWRP again) then i flashed the
nethunter zip built for oos rom.
As for drivedroid mine is working now... i didnt make any kernal changes..
all apps seem fully functional..

**Comment by shivsah** [comment]
@graybot666 @edlovesiraq You can use Termux as an alternative until Nethunter Terminal is fixed... just enable SSH in Nethunter app's Services Section... and login with Termux by using 

> **ssh root@localhost**

and when it asks for password enter 
> **toor**

and as for VNC you can start it by logging into Kali Terminal using ssh


and for further Discussion's and Support join the Telegram Group 
 https://t.me/joinchat/AAAAAEIBjTNzgnFiCG531g

**Comment by jcadduono** [comment]
There is no need to enable SSH unless you are connecting remotely to the device.
`su 0 bootkali_login` is sufficient in any terminal app.
If there's any issues it is very likely related to selinux, and you should either install a permissive nethunter kernel or run:
`su 0 setenforce 0` from a terminal to disable enforcing mode.

**Comment by edlovesiraq** [comment]
Sorry guys, was out for work.
I reflashed but haven gone beyond 3.1 yet. I regained Kali-Chroot but still
don't have drivedroid working, so now this weekend I'll try a fresh, ota to
3.5.6 then install kali. I'll hit back with how that works. Thank you for
the help guys!
