### ISSUE TITLE
Kexec-hardboot patch for Nethunter Kernel 

### ISSUE THREAD

**Issue by BZBaXraM** [offensive-security/kali-nethunter#767]
### Built from repo (date and build command) or downloaded from website (links):
build.nethunter.com 

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux localhost 3.4.112-cyanogenmod-g8fbc62e #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016 armv7l

## Issue:
Nethunter kernel supports Kexec-hardboot patch for MultiRom?

**Comment by jcadduono** [comment]
yes, you don't have it installed though

**Comment by BZBaXraM** [comment]
How?
