### ISSUE TITLE
Buggy almost non useable

### ISSUE THREAD

**Issue by bytedeez** [offensive-security/kali-nethunter#770]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmellow

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from official nethunter page

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Said not a file or directory.
In NetHunter terminal tried all 3 settings I.E.: Android, AndroidSU and Kali. 

## Issue:

Fresh installed using newly downloaded images 3 times.
After each install continuously received settings has stopped, Android system stopped  and network stopped. Says nethunter update is available however when I try to install it says storage is full and cannot install. However when I check my storage using es file explorer it says storage is at 50%. Cannot access setting to verify.
Cannot access settings period fails on every attempt.
Any advice? About to uninstall if problems persist.

Edit: cannot install any metapackages receive 404 errors. Check internet connection and I do have a connection and can ping 8.8.8.8

Due to settings not working cannot use HackersKeyboard for terminal use.

**Comment by jcadduono** [comment]
see the wiki, try out the nightly build images
