### ISSUE TITLE
Apache start failed "Use 'systemctl status apache2' for more info. Running in chroot, ignoring request."

### ISSUE THREAD

**Issue by theoneandonly-vector** [offensive-security/kali-nethunter#771]
### Device:
oneplus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
android 6.0.1
oxygen 3.2.7

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.18.20-ElementalX-OP3-0.22 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #3 SMP PREEMPT Wed Sep 28 00:02:55 UTC 2016

## Issue:
root@kali:~# service apache2 start
[....] Starting Apache httpd web server: apache2Invoking 'systemctl start apache2'.
Use 'systemctl status apache2' for more info.
Running in chroot, ignoring request.

 failed!
[....] The apache2 instance did not start within 20 seconds.[warnse read the log files to discover problems ... (warning).
root@kali:~#

the logs:
/var/apache2
are empty

i purged & reinstalled apache2 -> did not help.

**Comment by akrolla** [comment]
did u try starting it with the kali services button in the NH app?

**Comment by theoneandonly-vector** [comment]
yes
and I updated to Android N and also re-flashed the latest Kali-zip.. so I
don't have the problem anymore.

Am 13.02.2017 1:48 vorm. schrieb "akrolla" <notifications@github.com>:

did u try starting it with the kali services button in the NH app?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/771#issuecomment-279270438>,
or mute the thread
