### ISSUE TITLE
Signalking8000N doesn't work on it

### ISSUE THREAD

**Issue by BKDOnions** [offensive-security/kali-nethunter#773]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.4.0-gad29d11 (android-build@vpea2.mtv.corp.google.com) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Sat Jul 2 00:00:53 UTC 2016

**Comment by BKDOnions** [comment]
SK-8000N has a Ralink3070 chipset and is supported on Kali Linux,my otg cable is OK because I tested the cable by using my udisk and mouse

**Comment by jcadduono** [comment]
You don't have a nethunter kernel installed

**Comment by BKDOnions** [comment]
I've installed the latest one 20170202,but it still doesn't work,https://build.nethunter.com/nightly/3.15.4-20170202-1604/
Wasn't this URL?

**Comment by jcadduono** [comment]
edit your issue report with new information (cat /proc/version, etc)

**Comment by BKDOnions** [comment]
@jcadduono I flashed kernel-nethunter-flo-marshmallow-3.15.4-20170202-1604.zip

**Comment by BKDOnions** [comment]
I've updated it, have any solution?

**Comment by InsaneChef** [comment]
I have had same issue. Many hours of research and trial/error to no avail.  My next step is to add kernel headers so my USB dongle will work (RTL8811AU).  But first, I need to know how to get kernel to flash properly.  Is there even a place that shows examples?
