### ISSUE TITLE
Hostapd-wpe

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#774]
### Device:

Op3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

Nightly build 01.02.17

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-ElementalX-OP3-0.15 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #5 SMP PREEMPT Mon Nov 21 17:40:25 CST 2016

## Issue:

When running hostapd-wpe fron nh app and run certs fir the first time it states no such directory.
I have moved a long way in installing myself but am now stuck with incorrect config file configuration. As far as I can tell hostapd-wpe had no installation at all but I'm regularly wrong.

**Comment by ozsteyr** [comment]
Have now installed via apt and changed directories to get it working. But would still be helpful to have it done by someone in the NH team who knows what their doing.

**Comment by themakerman** [comment]
@ozsteyr Can you tell me how did you managed it to pull off. I am facing the same problem on OP3

**Comment by ozsteyr** [comment]
Create /usr/share/hostapd-wpe/certs
Git clone hostapd-wpe
Move contents to  /usr/share/hostapd-wpe/certs
Then run hostapd-wpe certs from nethunter.
Move hostapd-wpe script from usr/sbin to usr/bin
Then set hostapd-wpe.conf as needed.
This itself is no doubt not the correct way but it works

**Comment by ozsteyr** [comment]
Sorry, first apt-get install hostapd-wpe

**Comment by themakerman** [comment]
Got it

**Comment by initstring** [comment]
I had the same issue, with a slightly easier fix. Simply download all the files in the "certs" folder from this repo to /etc/hostapd-wpe/certs/ on the phone.
