### ISSUE TITLE
airterm terminal emulator for nethunter

### ISSUE THREAD

**Issue by HaxorGaruda** [offensive-security/kali-nethunter#777]
hello... 
i want to use use airterm as terminal emulator on nethunter.. because full feature like floating ... anyone know how to setup to integrate with nethunter ? thanks ...

**Comment by ozsteyr** [comment]
I agree it seems good.

**Comment by jmingov** [comment]
Unless the app dev collaborate with us / shares the app code, we can not do the integration with nethunter.

(This app looks closed source)


Br

J
