### ISSUE TITLE
Factory Fruity Wifi service not loading...

### ISSUE THREAD

**Issue by bytedeez** [offensive-security/kali-nethunter#778]
### Device:
Nexus 7 Flo

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmellow

### Built from repo (date and build command) or downloaded from website (links):
Nightly from 02-02-17 @1604
Kernal and Generic armhf
https://build.nethunter.com/nightly/3.15.4-20170202-1604/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gae95f7e-dirty

## Issue:
fruity wifi service does not open and start fruity wifi.
When starting service browser automatically opens to localhost:8000 (also tried port 8443) however it says page can not be found,
Tried starting apache. However Frutiy wifi page did not load,
I was able to work around the issue by manually install fruity wifi using apt-get and adding custom command to start and stop it. but the issue remains,
I was going to try to trouble shoot but i could not find the files that coincide with the preloaded service option. 
Also I was worried that manually installing fruitywifi would cause error with preloaded services. Not sure if it matters or not.

**Comment by ozsteyr** [comment]
On the fruity boards there is the issue with php5 running.
Need to stop it and start php7.0-fpm.

**Comment by bytedeez** [comment]
Right. The issue isn't that I can't use fruityWifi and get it running. The issue is the built in feature to do so is not working.

**Comment by ozsteyr** [comment]
Apologies, the modules or nothing is working?
Because I can change the configurations but I can't do anything with the modules.

**Comment by bytedeez** [comment]
I haven't tested that the modules yet.
I am waiting on a replacement otg to arrive.
Nothing is working when I enable the built in service. However I manually installed it and was able to setup customs commands in order to launch fruity wifi, load the page and loggin. I can enable the modules but that does not mean they are working.
