### ISSUE TITLE
HID interfaces disappear - Nexus 6p

### ISSUE THREAD

**Issue by patkszen** [offensive-security/kali-nethunter#779]
### OS version (KitKat/Lollipop/Marshmallow/Nougat): 

Nougat 7.1.1, build number N4F26J

### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 

Linux version 3.10.73-nethunter-angler-1.1 (jc@westerley) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Mon Jan 16 12:30:18 EST 2017

## Issue: 

HID interfaces initially work fine. I lose them after using HID Duckhunter or DriveDroid a few times, usually I have to switch USB modes from file transfer to PTP to make some of the features work. Rebooting the phone resolves the problem.

**Comment by jcadduono** [comment]
see if `setprop sys.usb.config hid` helps to bring them back, you can use `setprop sys.usb.config reset` to reset to boot up usb config

**Comment by patkszen** [comment]
it doesn't like setprop

"command not found"

**Comment by jcadduono** [comment]
you need to be root...

**Comment by patkszen** [comment]
I am root

**Comment by patkszen** [comment]
Right now I just realised you weren't referring to Kali CMD, the command indeed works in android CMD. I will fully test it later on, once my hid starts acting up

**Comment by jcadduono** [comment]
it should also work in kali since system is mounted and in the path

**Comment by patkszen** [comment]
For some reason it doesn't work in Kali cmd but it does the job in android cmd

I want to add a custom command to nethunter so don't have to type it in each time when it breaks  but not quite sure how to refer to android cmd from Kali with bash
