### ISSUE TITLE
Nexus 5X - Y cable charging

### ISSUE THREAD

**Issue by Anty0** [offensive-security/kali-nethunter#780]
### Built from repo: `20170207_144814`
`./build.py --device bullhead --nougat --uninstaller --nightly --rootfs full --nosu --nobrand`

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
`Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016`

## Issue:
I tried enable Y cable charging service, but without success. My phone is still only charging or only connects to device connected to otg. I know about bug in nethunter-app in service state detecting in version that I have installed (3.15.4). So I tried to find files specified [here](https://github.com/offensive-security/nethunter-app/blob/master/assets/scripts/check-ycable), but I didn't find any of them. So I suppose, that my device doesn't support y cable charging.
Am I right? Is there reason why y cable charging is not supported on my device? (It is due to USB Type-C? I thought that USB Type-C should be an advantage for charging phone when some other devices is connected...)

I know, that my English is not very good sometimes, so sorry for that.
Thank you in advance for your reply.

**Comment by yesimxev** [comment]
I had the same issue on Oneplus1 with CM13. Turned out that the kernel needed the CM12.1 dwc3_otg.c and .h driver instead of CM13, and it works flawlessly now. So I built the cm13 kernel with usual stuff, plus replaced the corresponding .c and .h files

**Comment by Anty0** [comment]
Wow, I didn't expect to get an response two years later...
Unfortunately I no longer have that device (bullhead), so I can't test your solution...
But anyway, thank you. Maybe somebody will find this useful. 🙂
