### ISSUE TITLE
Safety Net

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#781]
### Device:

OP3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

MM

Just curious if it's possible to add safteynet and CTS patches in the kernel or is this a stupid question? 
I  may be silly and childish but I do like pokemon go. I have had NH for a long time and gone without android pay and some games but now I would like to have both and from all my research and trial and error patching seems my only option, but if anyone knows some other possibilities I would be greatful.

**Comment by bkr32** [comment]
well  if you can run nh with a kernel enforcing selinux then sure
