### ISSUE TITLE
configuring wire shark common

### ISSUE THREAD

**Issue by Shaheenf88** [offensive-security/kali-nethunter#782]
## Issue:after nethunter install&update metapackage while installing the package downloaded a message came in the terminal asking configuring Wireshark common and details then yes or no I can't tap yes or no from there I tried many ways enter is not working,tried connecting mouse and doesn't work can anyone help I am confused

**Comment by akrolla** [comment]
Are u using the one from the site that install package is deprecated the
new terminal has a set of arrows added that were added to facilitate moving
around in yhose interminal popups. Could also try the tab key and hit enter
once the selection u want is selected.

**Comment by jdmcwhinnie** [comment]
Hi,
Was this issue ever solved?  I am having the same issue.  It is stuck on the terminal and tab on the hackers keyboard and Enter etc. doesn't work.  Any ideas?  I have to figure this out before my battery dies.

**Comment by Shaheenf88** [comment]
My nh-terminal version is 1.0.0 I have tried hitting tab and enter and also arrows button in therminal(←↑→) it is not working nothing is happening I am stucked at this prompt do you any other solution

**Comment by rachidb13** [comment]
i have the same problem i cant pass this step
after apt-get update 
the kali rolling was updatet perfectly 
then apt-get dist-upgrade 
![22835450_1742427802456419_284478982_n](https://user-images.githubusercontent.com/33155307/32107110-f07eb9e6-bb2d-11e7-8551-e715a040d044.png)

i cant shose yes in this etap 
i put a usb keyboard and its the same problem 
when u click att the arrow buton its show a bunsh of code like this photo
![22883227_1742450649120801_845103606_n](https://user-images.githubusercontent.com/33155307/32107347-999ffac6-bb2e-11e7-85b0-fc1af306453a.png)

pleas help !!

**Comment by bozwald** [comment]
I press enter for that or are you unable

**Comment by jdmcwhinnie** [comment]
all you need to do is ssh into your nethunter and use your pc....

**Comment by aarogita** [comment]
Use arrow keys, it will help you to select yes and then after that press enter.

**Comment by jcadduono** [comment]
Hey guys, try using JuiceSSH local terminal mode. Use `su -c bootkali_login` to bring up a Kali session and run wireshark and whatnot from there.
The NetHunter terminal has some bugs that need to be worked out regarding keyboard hotkeys and ncurses display.

**Comment by aarogita** [comment]
Thanks brother... It's fixed now..
