### ISSUE TITLE
Not detecting external wifi adapter

### ISSUE THREAD

**Issue by judeferolous** [offensive-security/kali-nethunter#784]

**Comment by akrolla** [comment]
Where are you downloading from

**Comment by akrolla** [comment]
can u provide the output to cat /proc/version to verified you have correct
kernel installed, I think you have stock android installed. You have to
root , install multirom and then if ugo to wiki there are links there to
the latest builds . I think u have an incomplete install.

**Comment by VFMA83** [comment]
Thank you for your help!

Here is what I have:

Linux version 3.4.67-00092-g7b02438 (root@kali) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT The Sep 24 01:04:17 UTC 2015

**Comment by akrolla** [comment]
I believe tou may have downoaded a dwprecated version plase vist the wiki
for more upto date downloads, alsoumd dlintfoget to check the nightly
builds. There should be a link in the wiki also

**Comment by VFMA83** [comment]
I appreciate the help.  

I know you guys get tons of stupid questions so I always try to fix the problems before asking for help.

Thank you again,

Best

**Comment by judeferolous** [comment]
which kernel and rom should i install @akrolla

**Comment by akrolla** [comment]
https://build.nethunter.com/nightly/

Those are for the nightlys most are pretty stable

**Comment by akrolla** [comment]
https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e

**Comment by akrolla** [comment]
Try this kernel after u follow those instructions in the gist

https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-hammerheadcm-nougat-3.15.4-20170211-0304.zip

**Comment by akrolla** [comment]
I that kernel doesn't work @autindroid has a more upto date lineage kernel
it hasn't been added yet

**Comment by judeferolous** [comment]
@akrolla so should i use multirom or install as normal on my primary os

**Comment by AutinDroid** [comment]
@akrolla @judeferolous the hammerheadmon-nougat package has been updated to stable (1.5). I advise against multirom, another user had issues with it. Try getting a nougat as primary (TIP: Euclidean OS is great!!!). Flash hammerheadmon-nougat and install the nexmon app and firmware (in app) for wlan0 monitor mode.

**Comment by akrolla** [comment]
Yea I use it as a primary I just install thru multirom just for ease of use
