### ISSUE TITLE
Alfa Networks AWUS036NEH (Still no Go)

### ISSUE THREAD

**Issue by VFMA83** [offensive-security/kali-nethunter#785]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 

3.4.67-00092-g7b02438
root@kali#1

## Issue:

I installed Nethunter on my Nexus 10 and everything is working well except I cannot get the external wifi card to work. I am using an Alfa Networks AWUS036NEH wireless card with a new OTG cable.  (The internal wireless works but not the external.)
 
When I go to the terminal and do a iwconfig it sees wlan0 with an IP, etc,  but the Wlan1  says  “No wireless extension found?”  I am assuming it is a driver issues but I bought the card that was supported out of the box. 

Any help would be greatly appreciated

**Comment by jcadduono** [comment]
Need to install nethunter kernel

**Comment by mpkosewski** [comment]
i have this exact same issue on my nexus 7 (2013 wifi). I did a brand new install of it to check if it was something wrong with it's current install. I'll post some screens and logs in a few min. "iwconfig" doesn't show any 1 of 3 Alfa devices connected; AWUS036NEH, AWUS036NHA, AWUS036NH. 

After some more tests, I found that airmon-ng still shows these devices and technically works so therefore I can run airodump-ng as normal. But putting the device in monitor mode with iwconfig does not work. 

However, my nexus 5(hammerhead) running virtually the same setup, works with "iwconfig" without issue on all devices.

**Comment by mpkosewski** [comment]
Just saw this too with AWUS036NHA, "vbus_otg IS NULL". Not sure what that means if that has anything to do with it. Otg should work,  I can plug in an external USB drive and use it. 

Hope the above info helps figure this out lol

**Comment by j0nnyf1v3** [comment]
I have the same issue with the same card, but on OPO

**Comment by mpkosewski** [comment]
I haven't had time to hope back on the device irc channels sadly but yeah I'm still not seeing anything although technically "airmon-ng" does technically work even if you don't see the device under "iwconfig" or "ifconfig"

**Comment by mpkosewski** [comment]
The atheros chipset if I remember correctly, showed up and worked like normal. But did not perform as well as the realtek's

**Comment by j0nnyf1v3** [comment]
What was weird for me was for brief moments of glory,after flashing the generic kernel, a boefella kernel and then the NH provided kernel for my device, I got a blinking blue signifying success. Unfortunatlly at the time I was dicking with trying to setup a multi-boot platform base,and would blow away anything I had done before a nand was possible.
