### ISSUE TITLE
Nethunter isn't working although it says, that the installation was successfull

### ISSUE THREAD

**Issue by MarkusKastner** [offensive-security/kali-nethunter#787]
### Device:
Nexus 10

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

### Built from repo (date and build command) or downloaded from website (links):
https://www.offensive-security.com/kali-linux-nethunter-download/

## Issue:
I try flushing Nethunter since Christmas, but it just doesn't work.

When choose all the optional things to install, it just freezes instantly, when i select just the required things, the intstallation process seems to work, but Nethunter isn't present at all, or can't start.

Well, i now it's free, but that level of frustration is too much, even in the Linux world.

**Comment by SuzumiyaXZ** [comment]
you need to download in https://build.nethunter.com/nightly/
and download the kernel can also hid attack whit use the OTG wirless devic

**Comment by SuzumiyaXZ** [comment]
https://www.offensive-security.com/kali-linux-nethunter-download/ is the old kali

**Comment by mpkosewski** [comment]
So is it better to flash the "generic armhf rolling" from the nightly than flash the image fro mthe offensive security site and then flash the nightly kernel on top?

**Comment by MarkusKastner** [comment]
Well well... flushing  nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip worked like a charm, but nmap isn't there and I think, it isn't working like it should be.
What kernel do I nedd to install?

**Comment by SuzumiyaXZ** [comment]
you can try nmap 127.0.0.1 in terminal

**Comment by MarkusKastner** [comment]
Problem solved. BusyBox was installed in ../binx, switched it to ../bin, now it works. And the other apps too. The only thing I didn't figured out was the right kernel to install.
