### ISSUE TITLE
Nightly feedback 

### ISSUE THREAD

**Issue by lcfut** [offensive-security/kali-nethunter#788]
### Device:

Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):

Nightly latest release

## Issue:
Once applied I can no longer apply Android system updates. 
Nethunter Terminal crashes upon launch
Where can I submit feedback for issues related to nightly builds?

**Comment by jcadduono** [comment]
Open Android terminal (nonsu) and do `su 0 setenforce 0` and it should stop crashing.
System updates failing is to be expected. No way around this. You have to use full OTA/fastboot zips to upgrade.
You are in the right place, but make sure your issue doesn't already exist before opening a new one. (Both yours exist already)
