### ISSUE TITLE
Nougat support for  Nvidia shield tablet k1

### ISSUE THREAD

**Issue by JuicySword** [offensive-security/kali-nethunter#789]
### Device:
Nvidia shield tablet k1

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

## Issue:
Need Nougat support for  Nvidia shield tablet k1

**Comment by AutinDroid** [comment]
I'll look into it

**Comment by salim133** [comment]
Any progress?

**Comment by AutinDroid** [comment]
@salim133 haven't have much free time recently, but I'll be starting kernel builds for numerous devices this weekend :)

**Comment by salim133** [comment]
Ah okay thank you for the update anyway ;)

**Comment by elmo315** [comment]
I am wondering too. I really want to take the nougat update, but kali nethunter is not available for nougat on the Nvidia shield K1 yet.

**Comment by JuicySword** [comment]
I upgraded to Nuget and a lot of things aren't working. Like can't access
Kali terminals...

**Comment by elmo315** [comment]
Any progress yet?

**Comment by AutinDroid** [comment]
@elmo315 reinstalling kubuntu.... Hard drive corrupted after absence of use.

**Comment by elmo315** [comment]
how is your computer coming along?

**Comment by AutinDroid** [comment]
@elmo315  Switched to macbook, gonna purchase a ssd for desktop soon. The nougat release for tegra is ota-5, right?

**Comment by elmo315** [comment]
was 5.0. they just rolled out a 5.1 update. here is a link https://shield.nvidia.com/support/shield-tablet-k1/release-notes

**Comment by elmo315** [comment]
btw if you need someone to test a beta build before publicly releasing  it i can do it.

**Comment by AutinDroid** [comment]
@elmo315 I don't see the source for 5.1 on the website, so I am using the kernel from Lineage. It would be great if you would get it tested for me! I will be able to create a working kernel hopefully by the end of the day, with only a few tiny missing features.

**Comment by elmo315** [comment]
the only problem i have is that i am grounded until the 23rd of march cuz my grades were bad. My report card is coming in on that date, and i made sure to bring them up (ive been grounded since last October). I can surely "sneak" my tablet for now, but finding the right time to sneak it will be difficult since i still need to update to 5.1, re-root and install twrp, then flash the test build. So, i cant be TOO involved in beta testing until the march 23rd if thats alright.

**Comment by elmo315** [comment]
just out of curiosity, can that Lineage kernel work on the shield k1 tablet?

**Comment by AutinDroid** [comment]
@elmo315 yes, it should. Lineage kernel is based on source of device (in this case, official source of Shield)

**Comment by AutinDroid** [comment]
made a test kernel here https://github.com/AutinDroid/NetHunter-Testing

**Comment by elmo315** [comment]
great! unfortunately, i wont be able to test right now as i do not have access to my testing computer (LCD finally gave out cuz my sister kept dropping it, so im using my dads). 

so, i cant flash the factory recovery to update from the ota (TWRP does not support OTAs as far as i know)

btw im a noob to flashing since this is the first device i did not screw up since its so developer friendly.
i know i have to flash the stock recovery.img from the nvidia open source firmware 1.5 zip, but do i need to flash everything else? (blob, boot.img, system.img, and if i have to will it wipe my data cuz i have an adopted sd card that only works with that device)
![screenshot_2017-03-11-22-59-31](https://cloud.githubusercontent.com/assets/26314048/23828917/e386c898-06ae-11e7-9998-9a0c4c8d23f7.png)

**Comment by AutinDroid** [comment]
I believe everything has to be installed (upgrading from marshmallow to nougat also involves changes in system) but data will remain (all info saved) you also need to flash boot.img

**Comment by AutinDroid** [comment]
Unless u receive ota

**Comment by elmo315** [comment]
i receive the OTA, but i have twrp, which does not update OTAs. (Im still on marshmallow)

So, if i flash all the files in the 1.5 zip, i wont lose any of my data, still be able to access my adopted sd card, and update to 5.1, re-root and test?

also do i flash this https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-shieldtablet-marshmallow-3.15.4-20170211-0304.zip

**Comment by AutinDroid** [comment]
Flash everything in the folder u showed. Flash the kernel in here https://github.com/AutinDroid/NetHunter-Testing

**Comment by AutinDroid** [comment]
The zip is TWRP flashable

**Comment by elmo315** [comment]
Thanks for clearing that up.

And my bad. I meant to give you this link. https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip

I flash that with your kernel correct?

**Comment by AutinDroid** [comment]
@elmo315 I forgot if shield is arm64 or armhf

**Comment by elmo315** [comment]
Thanx for putting up with my noobish questions. Im just real paranoid with bricking my device because just about every other device ive had has been bricked, or put in a bootloop, or something stupid. I just need re-asurement in the steps i take.

**Comment by elmo315** [comment]
Its a 32 bit cpu (armhf)

**Comment by elmo315** [comment]
Btw my parents kicked me off the computer fot the night. (eastern time, im in Florida) so i wont be able to flash anything tonight.

**Comment by AutinDroid** [comment]
@elmo315 than install Kali armhf

**Comment by elmo315** [comment]
Thanks. Its getting late. I need rest. I really appreciate your dedication to this thread. I will follow up when i have some time alone with the tablet so i can get rolling with the OTA update (hopefully wednesday. If not i will get back to you by next weekend. My parents will be out of town).

**Comment by JuicySword** [comment]
@AutinDroid Hey I can test this on my shield k1. Will it delete my data like apps etc...

**Comment by AutinDroid** [comment]
@juicysword just flash https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip and the kernel in here: https://github.com/AutinDroid/NetHunter-Testing
Flash via twrp. Install nougat before flashing

**Comment by elmo315** [comment]
@JuicySword have you tested yet

**Comment by JuicySword** [comment]
Not yet. but very soon. next few hours


2017-03-12 12:44 GMT-07:00 elmo315 <notifications@github.com>:

**Comment by salim133** [comment]
I keep getting **Could not find 'META-INF/com/google/android/update-binary' in the zip file.** When trying to flash the kernal

**Comment by JuicySword** [comment]
@AutinDroid Same  Could not find 'META-INF/com/google/android/update-binary' in the zip file

**Comment by AutinDroid** [comment]
@juicysword whoops I'll fix it when I'm home

**Comment by JuicySword** [comment]
are there ways to install Nethunter on SD card ?

**Comment by salim133** [comment]
Have you been able to fix the kernel?

**Comment by elmo315** [comment]
@AutinDroid how is it coming. Im in the process of updating to 5.1 nougat.

**Comment by elmo315** [comment]
Hello...

**Comment by californiajunkie** [comment]
this is the only thing stopping me from updating my tablet is nougat support for nethunter I  Appreciate you trying! I'll gladly test if you need hope you can get it soon

**Comment by AutinDroid** [comment]
https://github.com/AutinDroid/NetHunter-Testing

**Comment by californiajunkie** [comment]
Awesome will be testing asap just have do full backup flash 7.1 ROM and nethunter and then this

**Comment by californiajunkie** [comment]
Doesn't wanna boot gets stuck on nvidia logo I've tried on Tesla and aicp maybe I'll try stock ROM next I think?

**Comment by AutinDroid** [comment]
the kernel was built for cyanogenmod 14
it should work for most roms, so maybe problem with kernel
Ill try to check later after work

**Comment by californiajunkie** [comment]
OK thanks much appreciated

**Comment by californiajunkie** [comment]
Any word?

**Comment by AutinDroid** [comment]
@californiajunkie I doubt I'll find the time to make a working kernel today, but I'll do my best.

**Comment by hightechstl** [comment]
I have 7.0 on my k1, looking forward to testing!

**Comment by elmo315** [comment]
Any word yet?

**Comment by californiajunkie** [comment]
do we still have a chance at nougat?

**Comment by Patryk1024** [comment]
Something new?

**Comment by elmo315** [comment]
Umm...... is the kernel ready yet

**Comment by elmo315** [comment]
If anyone can guide me on how to pull kernal stuff out of the tablet i can do it. (If u can even do that)

**Comment by SecurityAddicted** [comment]
I've just built a Nougat-compatible kernel for the Shield Tablet: offensive-security/nethunter-devices#125
I'm running it since a few days without issues (LineageOS 14.1 with Nethunter). Please let me know of any issue :)

**Comment by elmo315** [comment]
Ayyyy about to test.
