### ISSUE TITLE
rom and kernel

### ISSUE THREAD

**Issue by judeferolous** [offensive-security/kali-nethunter#790]

**Comment by AutinDroid** [comment]
@judeferolous I personally would take Euclidan OS and install the hammerheadmon-nougat package.

**Comment by judeferolous** [comment]
but i nethunter not nexmon. @AutinDroid

**Comment by judeferolous** [comment]
after flashing euclidan os i should falsh kali nh right so which package should i use? @AutinDroid

**Comment by AutinDroid** [comment]
@judeferolous Flash euclidean os first. Then flash the armhf kalifs from build.nethunter.com/nightly and flash the hammerheadmon-nougat. Hammerheadmon-nougat is a kernel optimized for nethunter, allowing use of external devices and wlan0 monitor mode (via nexmon app).

**Comment by judeferolous** [comment]
so just flash the kalifs after euclidan installation..? or via nethunter app @AutinDroid

**Comment by AutinDroid** [comment]
Flash euclidean and then flash the rest
The kalifs in the link already has the standard Kali install.

**Comment by judeferolous** [comment]
so no need to installnethunter app after installing euclidan.. @AutinDroid

**Comment by AutinDroid** [comment]
Just flash everything I told you, and everything will be installed :)

**Comment by judeferolous** [comment]
ok tnx.. :D @AutinDroid

**Comment by akrolla** [comment]
Nh app is part of install package

**Comment by judeferolous** [comment]
kali fs is tar file there is mo option to flash it in recovery..
@AutinDroid

**Comment by AutinDroid** [comment]
@judeferolous I mean this https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip

**Comment by judeferolous** [comment]
armhf or i386 @AutinDroid

**Comment by AutinDroid** [comment]
Armhf

**Comment by judeferolous** [comment]
kk thanx will try and post results.. :D @AutinDroid

**Comment by judeferolous** [comment]
i have flashed euclidan and kalifs.zip installed kalinhmon kernel .also installed nexmon and update firmaware. When i start terminal wifite detects wlan0, but after searching for devices im unable to enter in to selection screen by pressing ctrl+c. @AutinDroid

**Comment by judeferolous** [comment]
yeah it works.. it detects but wifi cracking procedure seems not working..any suggestions for best tools for wifi penetration testing... @AutinDroid

**Comment by AutinDroid** [comment]
@judeferolous Do "source monstart-nh" to start wlan0 monitor mode.

**Comment by judeferolous** [comment]
did alll fine now.
but wifite seems not cracking wps @AutinDroid
