### ISSUE TITLE
How to generate /system/bin/bootkali_login ?

### ISSUE THREAD

**Issue by majackov** [offensive-security/kali-nethunter#791]
### Device:
Oneplus 3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.4-20170211-0304/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-3.1 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Thu Jan 26 22:15:43 EST 2017

## Issue:
I updated phone to 4.0.3, TWRP to v3.0.4-1 and flashed SuperSU-v2.79. After this I flashed .zip from https://build.nethunter.com/nightly/3.15.4-20170211-0304/ (for op3). cSploit and DriveDroid works correct, except terminal 
ps nethunter was installed before updating
![screenshot_20170217-172447](https://cloud.githubusercontent.com/assets/15738425/23069058/0673dbe0-f537-11e6-9179-c90a131fd0e3.png)
![screenshot_20170217-173014](https://cloud.githubusercontent.com/assets/15738425/23069059/09be4894-f537-11e6-8cb2-db8dfb13c460.png)

**Comment by akrolla** [comment]
su
bash " /data/data/com.offsec.nethunter/files/scripts/bootkali"

you have to run it as android interactive evey boot, in nethunter custom commands, it didnt work with a background boot at start settting

**Comment by akrolla** [comment]
Make a custom command in nh app with that script set it to interactive don't run at boot and every time u want a Shell just hit the run button to run the script

**Comment by majackov** [comment]
bash: can't open ' /data/data/com.offsec.nethunter/files/scripts/bootkali' :(

**Comment by bkr32** [comment]
@majackov clear nethunter app data and re-open the app

**Comment by majackov** [comment]
@bkr32, didn't help :(

**Comment by akrolla** [comment]
u might have to try reinstalling

**Comment by akrolla** [comment]
Make sure to wipe system data cach. Before install if u don't wipe sd card it leaves traces of chroot and that can mess it up to.. personally whenever I install nethunter I always wipe everything and install all factory stuff gwt it back to the condition it was in thhe box new, then I proceed to root. install multirpm, load into twrp place the rom and kernel, wipe system data cache and install, amd then I usually just sownload chroot

**Comment by akrolla** [comment]
if you do it that way 90%of the time it works perfectly I'm just anal and a perfectionist so if it messes up I just start all over
