### ISSUE TITLE
VPN Setup for Nethunter 

### ISSUE THREAD

**Issue by BZBaXraM** [offensive-security/kali-nethunter#794]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.112-lineageos (Boeffla-Kernel-6.0-beta10-Lineage14.1-nethunter-V2-bacon-u541-20170213@ZaneZam) (gcc version 5.4.1 20170113 (UBERTC-5.x.x) ) #1 SMP PREEMPT Mon Feb 13 13:05:21 CET 2017

## Issue:
How to setup and use OpenVPN?

**Comment by akrolla** [comment]
You have to find a good vpn and download and import the certificates

**Comment by BZBaXraM** [comment]
Can you help me?

**Comment by akrolla** [comment]
fins a good one like PIA and download the certificate bundles and import them

**Comment by akrolla** [comment]
Or freevpn.me but they're slow

**Comment by akrolla** [comment]
Or u could download hotspot shield app in google store

**Comment by vay3t** [comment]
u canuse vpnbook and download certs and imports in openvpn for android
