### ISSUE TITLE
Nexus 7 Grouper apt issue

### ISSUE THREAD

**Issue by micdot** [offensive-security/kali-nethunter#796]
### Device:
nexus 7 2012 grouper

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
5.1.1

### Built from repo (date and build command) or downloaded from website (links):
https://images.offensive-security.com/nethunter-release/nethunter-grouper-lollipop-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.1.10-Bricked-v0.591-g0a2e5f6 (root@kali) (gcc version 4.7 (GCC) ) #2 SMP PREEMPT Tue Oct 27 23:53:13 UTC 2015

## Issue:
Reading package lists... Done
Building dependency tree
Reading state information... Done
kali-linux-nethunter is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libc-dev-bin : Depends: libc6 (> 2.24) but 2.19-18 is to be installed
 libc6-dev : Depends: libc6 (= 2.24-8) but 2.19-18 is to be installed
 locales : Depends: libc-bin (> 2.24) but 2.19-18 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

I have over 400 upgrades pending because of this, Im not sure what i need in my sources.list either and just want to keep everything up to date. From what I know the sana repo has been discontinued and I read I should be using the old.kali.org repo but not sure what to add to sources.list. I can't find any inforrmation on any of this, any documentatation or advice on this would be apprciated.

**Comment by akrolla** [comment]
You probably have to use sana repos as grouper was discontinued:(

**Comment by micdot** [comment]
So what should my sources look like? This currently does not work for me, just get a bunch of errors.

deb http://kali.org/kali-rolling main contrib non-free
deb-src http://kali.org/kali-rolling main contrib non-free

deb http://old.kail.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib
