### ISSUE TITLE
Kali Nethunter NEXUS 10 ERROR PLS HELP

### ISSUE THREAD

**Issue by velazguez** [offensive-security/kali-nethunter#798]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):Lollipop
1>>>http://prnt.sc/eaiahr
2>>>http://prnt.sc/eaiaqo
3>>>http://prnt.sc/eaiauu
4>>>http://prnt.sc/eaib3s
5>>>http://prnt.sc/eaibbt

E:error opening /data/local/nhsystem/kali-armhf/dev/ram12
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram14
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram16
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram10
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram13
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram15
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/loop6
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram4
E:error: Not a directory
...

Pls help me

Android version:Nexus 10 (manta)	5.1.1
Twrp version:TWRP 3.0.2-0 Released

**Comment by AutinDroid** [comment]
@velazguez Are you using the official installer? That thing is deprecated.

**Comment by velazguez** [comment]
Yes official installer

**Comment by AutinDroid** [comment]
@velazguez The official installer is deprecated. Get inewer builds from build.nethunter.com/nightly

**Comment by velazguez** [comment]
link pls nexus 10

**Comment by velazguez** [comment]
Nexus 10 how to install helm me pls @AutinDroid

**Comment by velazguez** [comment]
@AutinDroid

**Comment by velazguez** [comment]
HELP ME

**Comment by VFMA83** [comment]
I am having the same issue.  I have followed three or four different install methods and none seem to work. Kali installs but the external network card does not work nor do the updates.   Is their a definitive guide that we can follow?  Mac - Linux - PC it doesn't matter.

**Comment by numaphlex** [comment]
I find that allowing TWRP to modify system could help before flashing supersu and nethunter.
