### ISSUE TITLE
Wifite looping and built in custom cimmand for wlan1 monitor mode not working.

### ISSUE THREAD

**Issue by bytedeez** [offensive-security/kali-nethunter#801]
### Device:

Nexus 7 2013

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marmashmello

### Built from repo (date and build command) or downloaded from website (links):

Nightly kernal and generic armhf update from 02/11/17.
Last complete nightly install was 02/02/17
Full rolling generic armhf.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gae95f7e-dirty (root@nh-build-box) gcc version 4.7. SMP PREEMEPT fri jul 29....

## Issue:
Wifite loop during monitor mode setup with 722n adapter.
Have tried manually setting adapter in monitor mode using airmon-ng start wlan1. Then choosing the interface in wifite.
Wifite still loops but show wlan1mon as interface.
Custom command in NH app will not put wlan1 in monitor mode.
Also tried ifconfig wlan1 down. iwconfig wlan1 mode monitor and then ifconfig wlan1 up.
Wifite still loops at monitor mode / interface selection.

I have had it working before. nightly build imstalled from 02/02 andthen used generic update and kernal build from 02/11 to update to lastest build. Still nol luck.
I have confirmed the drivers are installed via /system/etc/firmware/.
However wifite shows "?????" As driver.

Any ideas?

**Comment by vay3t** [comment]
try `airmon-ng start wlan1 && wifite` in terminal

**Comment by bytedeez** [comment]
Still get the same result.
Wifite shows wlan1mon.
I select wlan1mon interface and wifite loops back to interface selection.

**Comment by erickrm** [comment]
Device:
OnePlus 2

OS: Marsh mellow Cyanogen 13

Built From:
test armhf 3.15.4 (test-keys)

Output:
Linux version 3.10.84-perf+ (root@kali) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Sat Feb 25 20:12:42 EST 2017

The other issue i have and not sure if its linked, is that my terminal keeps force closing.  I can start the SSH service and get in that way though.

**Comment by bytedeez** [comment]
Try reflashing with the latest nightly.
Back up any data first. Then do a fresh install of ROM. Then install nethunter image and last install kernel. Took me a few tries but it corrected my issues.

**Comment by erickrm** [comment]
Hey Bytedeez, 

Thanks for info bud,  I actually ended up compiling my own kernel and now have everything working over Oxygen OS 3.5.6.  Although I have not tried wifite since my last compile, but i did get it working with the following switch wifite -i interfeacename it did the rest for me.

Thanks for the info though, greatly appreciated.

**Comment by tehpenguin** [comment]
Do you have a link to that kernel? Same loop issue here with nexus 7 2013 marshmellow
