### ISSUE TITLE
Support for the Google Pixel, and XL

### ISSUE THREAD

**Issue by Khodyn** [offensive-security/kali-nethunter#802]
It's been a while since the Google Pixel phones were released and TWRP works on it, is it feasible to bring Kali Nethunter to the Pixel now?

**Comment by AutinDroid** [comment]
@Klocko  I dont see y not. I'll be compiling some kernels during my free time

**Comment by AutinDroid** [comment]
@Klocko builds are coming soon

**Comment by Klocko** [comment]
Awesome, can't wait

On 12 Mar. 2017 2:40 pm, AutinDroid <notifications@github.com> wrote:

@Klocko<https://github.com/Klocko> builds are coming soon

**Comment by Klocko** [comment]
@AuDesign Any update?

**Comment by kimocoder** [comment]
+1 comment or?

**Comment by mjoudrey** [comment]
+1

**Comment by VizariMarek** [comment]
Has a pixel XL nethunter been released?

**Comment by kimocoder** [comment]
Take a look around NetHunter wiki [here](https://github.com/offensive-security/kali-nethunter/wiki) on howto:

* Porting to new devices [here](https://github.com/offensive-security/kali-nethunter/wiki#70-porting-nethunter-to-new-devices)

* Compile a kernel which is needed, read [here](https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

Also, take a look around this GitHub repo, eg other issue reports around Pixel support

**Comment by VizariMarek** [comment]
@AuDesign did you finish the kernels?

**Comment by edlovesiraq** [comment]
+1

**Comment by atombombzero** [comment]
Any news?
