### ISSUE TITLE
DuckHunter Oneplus One 'G' not recognized ?

### ISSUE THREAD

**Issue by SupaSTO** [offensive-security/kali-nethunter#804]
Hi all,

I've been messing around with DuckHunter HID since yesterday and I just realized that the 'g' character didn't have any output on target machines when it's clearly present in the script. I tested it on multiple computers with no results, but switching keyboard layout worked. 

I normally use the Belgian layout and this is what I would need to perform test attacks. Does anyone know if there's a way to fix this issue ?

Thanks in advance !

**Comment by BesoBerlin** [comment]
#556

**Comment by SupaSTO** [comment]
Thanks a lot !
