### ISSUE TITLE
How to empty the trash in Nethunter using terminal (console)

### ISSUE THREAD

**Issue by serpunja** [offensive-security/kali-nethunter#808]
Tell me please.
In Netnunter have basket (trash) ?

Then how to clean it ?

**Comment by zszszsz** [comment]
what trash?

**Comment by jcadduono** [comment]
apt-get install trash-cli
trash-empty

**Comment by serpunja** [comment]
@zszszsz 
![kalidesktop](https://cloud.githubusercontent.com/assets/24878620/23339795/e2b66cf8-fc3a-11e6-8649-f3f248b05afe.png)

**Comment by serpunja** [comment]
Thanks jcadduono .
