### ISSUE TITLE
suggestion：replace "amd64" with "x86-64"

### ISSUE THREAD

**Issue by zszszsz** [offensive-security/kali-nethunter#809]
I have to admit that I was trying to download kalifs for arm64 device, but I downloaded the amd64 version by mistake.

I mean, the two words "amd64" and "arm64" are too like to each other.

It will help many people to avoid that kind of mistakes if you change the word "amd64" to "x86-64".

**Comment by jcadduono** [comment]
Names are based on Kali repos
