### ISSUE TITLE
New Hardware Request

### ISSUE THREAD

**Issue by lcfut** [offensive-security/kali-nethunter#815]
Yes i know it hasn't been released yet, but this design would be the perfect fit for this project.  If this is something being considered I plan on getting one.

Thank you

**Comment by jmingov** [comment]
@lcfut mmm maybe im missing something, but, which device/hardware are you talking about?

**Comment by lcfut** [comment]
@jmingov 
Perhaps I should have pasted in the URL before hitting the button.

https://www.indiegogo.com/projects/gemini-pda-android-linux-keyboard-mobile-device-phone/x/7881296#/

**Comment by AutinDroid** [comment]
@jmingov will be possible if there it is open source and a TWRP build is created
