### ISSUE TITLE
nethunter builder devices not found

### ISSUE THREAD

**Issue by xTheCrow** [offensive-security/kali-nethunter#816]
Hi guys, when i try to build nethunter for nexus 5x nougat with the builder.py i get this error:

Error: device bullhead not found in devices/devices.cfg.

i ran this command:
python build.py -d bullhead --nougat

any help?

**Comment by xTheCrow** [comment]
fixxed, can close his post.

**Comment by nrrpinto** [comment]
@xTheCrow it would be helpful if you tell how did you solve this! I am having the same issue, I don't find the file "devices.cfg" anywhere except in "https://github.com/offensive-security/nethunter-devices/blob/master/devices.cfg", i wonder if i have to clone that git project and change the "build.py"!

Anyone to help about this topic?

**Comment by jcadduono** [comment]
Readme!!!!
