### ISSUE TITLE
NetHunter terminal crash

### ISSUE THREAD

**Issue by mikroskeem** [offensive-security/kali-nethunter#817]
### Device:

Google Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

LineageOS 14.1 (20170228, Android 7.7.1 to save you from searching)

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170211-0304/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

`Linux version 3.4.0-g0436925 (chris@LinuxVirt) (gcc version 4.6.x-google 20120106 (prerelease) (GCC) ) #3 SMP PREEMPT Sun Dec 11 20:19:29 EET 2016`

## Issue:

Terminal crashes when I try to open it. Logcat dump: https://paste.nightsnack.cf/raw/avamusiyaw

**Comment by mikroskeem** [comment]
If I manually reinstalled Term-nh.apk from `nethunter-generic-armhf-kalifs-minimal-rolling-3.15.4-20170211-0304.zip`, then I got it working.

**Comment by montvid** [comment]
> nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip 
This one has the same problem, terminal not working. Installed a working terminal from nethunter-flo-marshmallow-3.0.zip
Fix the terminal in nighty!
