### ISSUE TITLE
Installing php5-fpm, FruitWifi ? No package found...

### ISSUE THREAD

**Issue by jfxmedia** [offensive-security/kali-nethunter#819]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:  
Linux version 3.18.47-nethunter-3.1 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Thu Jan 26 22:15:43 EST 2017

## Issue: 
I have searched high,and then high on that high, and lower than low for several days on how to get FruityWifi working on nethunter. I am able to use "/etc/init.d/fruitywifi restart" and that works, but then trying to start or restart or apt-get or install "php5-fpm" it is nowhere to be found. I have found info on php5 and php7 and just php for different linux distros running on a PC, but for nethunter I am unable to figure out where the package is. When trying to install in terminal it says "no such file or directory"

I would appreciate GREATLY any help or advice, maybe alternatives to fruitywifi ? I'm VERY new to the world of hacking/coding/python.. Thank you

**Comment by jfxmedia** [comment]
I have solved this issue..

**Comment by miguelebf** [comment]
How did you solve it? I have the same problem @jfxmedia

**Comment by iart76** [comment]
yes how, i have some problem...
