### ISSUE TITLE
terminal crashes

### ISSUE THREAD

**Issue by PythonDream** [offensive-security/kali-nethunter#820]
### Device:
Samsung galaxy s6 edge plus

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow 6.01

### Built from repo (date and build command) or downloaded from website (links):
https://forum.xda-developers.com/galaxy-s6/development/kali-nethunter-s6-s6edge-stock-rom-t3559710

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.61-7080791 (dpi@SWDD5709) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Oct 28 14:48:54 KST 2016

## Issue:
Terminal-nh.app crashes when ever started and i choose between kali, android, and androidSU
no error message
if i try to install meta packages with nethunter.app it crashes because of the terminal
and so on every time i request an app to use the terminal

however i can do the following:
su -c bootkali
a kali session starts

busybox returns: 
BusyBox v1.26.2-Stericson (2017-01-14 16:15:58 PST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.

when i try to uninstall chroot with nethunter.app the phone restarts but chroot is still there untouched is that my issue?? and if so what to do???

is there anything else i need to check for?

**Comment by elitedevx** [comment]
I'm having the exact same issue.

**Comment by BesoBerlin** [comment]
try to manually bootkali by open any other terminal emulator, downloaded from appstore and enter
```
su
bootkali
```
afterwards nh-terminal should work as well...

**Comment by m3linial-GDrobz** [comment]
i have tried both and not working...
when i download and open an other terminal app im able to fire up a kali session with 
```
su
bootkali
```
as suggested by BesoBerlin however the nethunter.app and nh-terminal.app still crashes as explain at the top post

in regard to #817 i've tried manually removing vnc, nh-terminal, and nethunter.app and reinstall them from git in the propor order explained in an other issue thread i dont remember which one but that also left me with the same issue :(

**Comment by elitedevx** [comment]
Can you start SSH from the Kali Services menu in NetHunter app and then try again?

**Comment by m3linial-GDrobz** [comment]
After enabling ssh the apps still crash :-/

**Comment by loogol** [comment]
I'm having the exact same issue.
in android terminal:
`su bootkali`
kali started, busybox is active. how can i fix issue with NH terminal drop?

**Comment by californiajunkie** [comment]
Ya me too can boot from android termial with bootkali but  nh-term crashes every time it's opened

**Comment by loogol** [comment]
Hmm.. that issue was on the android mm.
For test, i flash cm12.1. After that i flash nethunter builded for cm12.1 without chroot. and it's works.
New problem with monitor mode.. can not compile wifi driver ..

Sory for my bad english

**Comment by leeech** [comment]
Work around... Open built in android terminal app .. type su     then type setenforce0          after that close the terminal app and open kalinethunther terminal app... all should be good now .... Issue is with selinux.

**Comment by leeech** [comment]
Let me know if this helps.. I'm using HTC m8 nougat

**Comment by rubencabrera** [comment]
From another terminal emulator:
su
bootkali
Has worked for me. Shame nougat built without SU

**Comment by montvid** [comment]
> nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip 
This one has the same problem, terminal not working. Installed a working terminal from nethunter-flo-marshmallow-3.0.zip

**Comment by GreysonJ** [comment]
Su
Bootkali 

also worked for me.
