### ISSUE TITLE
vncmanager

### ISSUE THREAD

**Issue by computer777** [offensive-security/kali-nethunter#821]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:root@kali:/# vncserver :1 -geometry 2392x1440 && echo "Closing terminal in 5 secs" && sleep 5 && exit
/usr/bin/xauth:  file /root/.Xauthority does not exist

New 'localhost:1 (root)' desktop at :1 on machine localhost

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/localhost:1.log

Use xtigervncviewer -SecurityTypes VncAuth -passwd /root/.vnc/passwd :1 to connect to the VNC server.

vncserver: Failed command '/etc/X11/Xvnc-session': 256!

=================== tail -15 /root/.vnc/localhost:1.log ===================

Xvnc TigerVNC 1.7.0 - built Feb  9 2017 22:51:56
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11901000, The X.Org Foundation

Tue Mar  7 13:22:07 2017
vncext:      VNC extension running!
vncext:      Listening for VNC connections on local interface(s), port 5901
vncext:      created VNC server for screen 0
/etc/X11/Xvnc-session: 7: /etc/X11/Xvnc-session: /su/bin/sush: not found
vncconfig: unable to open display ":1"
Killing Xtigervnc process ID 6511... which seems to be deadlocked. Using SIGKILL!

===========================================================================

Starting applications specified in /etc/X11/Xvnc-session has failed.Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
root@kali:/# tigervncserver -xstartup

New 'localhost:1 (root)' desktop at :1 on machine localhost

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/localhost:1.log

Use xtigervncviewer -SecurityTypes VncAuth -passwd /root/.vnc/passwd :1 to connect to the VNC server.

tigervncserver: Failed command '/etc/X11/Xvnc-session': 256!

=================== tail -15 /root/.vnc/localhost:1.log ===================

Xvnc TigerVNC 1.7.0 - built Feb  9 2017 22:51:56
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11901000, The X.Org Foundation

Tue Mar  7 13:23:07 2017
vncext:      VNC extension running!
vncext:      Listening for VNC connections on local interface(s), port 5901
vncext:      created VNC server for screen 0
/etc/X11/Xvnc-session: 7: /etc/X11/Xvnc-session: /su/bin/sush: not found
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 173 requests (172 known processed) with 0 events remaining.
Killing Xtigervnc process ID 6840... which seems to be deadlocked. Using SIGKILL!

===========================================================================

Starting applications specified in /etc/X11/Xvnc-session has failed.Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
root@kali:/#

## Issue: vnc server will not start as it did in previous builds. -where it loads the kali desktop. I tried to use      tigervncserver -xstartup /usr/bin/xterm and that worked fine.

**Comment by themakerman** [comment]
I am dealing with the same problem.
Device: One plus 3
OS: Android N

**Comment by themakerman** [comment]
Found the issue.... Run the command by adding sudo.... Or run su before running the server

**Comment by svdvmxwl** [comment]
Can anyone tell me the solution to this problem?
Anybody could run it? What are the corresponding measures to get it to work?
I hope sine one helps here..

**Comment by Sam-Antil** [comment]
simplu run: vncserver -localhost
