### ISSUE TITLE
Not detecting device and No wlan1, but showing device with "lsusb".

### ISSUE THREAD

**Issue by mmimarsinann** [offensive-security/kali-nethunter#822]
Device: Xiaomi Redmi Note 4 (nikel)
OS version: Marshmallow

Built from repo (date and build command) or downloaded from website (links): https://forum.xda-developers.com/android/software-hacking/kali-nethunter-mediatek-device-t3547416

root@kali:~# cat /proc/version
Linux version 3.18.22+ (jenkins@ubuntu) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Tue Aug 16 12:09:32 CST 2016

Issue:

Hi, not showing wlan1 and not detecting my USB wifi dongle.

Last login: Tue Mar  7 15:08:07 UTC 2017 on pts/18

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0bda:8187 Realtek Semiconductor Corp. RTL8187 Wireless Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:~# iwconfig
Warning: Driver for device ccmni5 has been compiled with an ancient version
of Wireless Extension, while this program support version 11 and later.
Some things may be broken...

ccmni5      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: 00:00:06:00:00:00   Bit Rate=0.005 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

ccmni0      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

ccmni6      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

ccmni1      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

ifb0      no wireless extensions.

ccmni7      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1048.45 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

ccmni2      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

ip6tnl0   no wireless extensions.

ifb1      no wireless extensions.

ccmni3      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1048.45 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni7     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni6     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni5     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni4     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni3     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni2     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni1     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

cc3mni0     ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1031.39 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

sit0      no wireless extensions.

lo        no wireless extensions.

ccmni4      ESSID:off/any  Nickname:""
          NWID:0  Mode:Unknown/bug  Channel:0
          Access Point: F0:FF:22:00:00:00   Bit Rate=-1048.5 kb/s   Sensitivity=-1031392 dBm
          RTS thr=-1031392 B   Fragment thr=-1031392 B
          Encryption key:0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000-0000
          Power Management:on

tunl0     no wireless extensions.

root@kali:~# ifconfig
ccmni0: flags=193<UP,RUNNING,NOARP>  mtu 1500
        inet 10.201.252.107  netmask 255.0.0.0
        ether aa:12:b1:c7:82:10  txqueuelen 1000  (Ethernet)        RX packets 21139  bytes 15930556 (15.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20563  bytes 3125706 (2.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 1378  bytes 81857 (79.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1378  bytes 81857 (79.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@kali:~# iw reg get
global
country 00: DFS-UNSET
        (2402 - 2472 @ 40), (6, 20), (N/A)
        (2457 - 2482 @ 40), (6, 20), (N/A), PASSIVE-SCAN
        (2474 - 2494 @ 20), (6, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5170 - 5250 @ 160), (6, 20), (N/A), PASSIVE-SCAN
        (5250 - 5330 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN
        (5490 - 5730 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN

root@kali:~# apt-get install firmware-realtek
Reading package lists... Done
Building dependency tree
Reading state information... Done
firmware-realtek is already the newest version (20161130-2).The following packages were automatically installed and are no longer required:
  libicu55 libjson-c3 libmysqlclient18 libpoppler61 libschroedinger-1.0-0
  lua-lpeg python-brotli python-ndg-httpsclient zlib1g-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 58 not upgraded.
root@kali:~# airmon-ng

Found phy0 with no interfaces assigned, would you like to assign one to it? [y/n] y

 ERROR adding monitor mode interface: command failed: Operation not supported (-95)

Found phy1 with no interfaces assigned, would you like to assign one to it? [y/n] y

 ERROR adding monitor mode interface: command failed: Operation not supported (-95)

PHY     Interface       Driver          Chipset

ethtool failed...
Only mac80211 devices on kernel 2.6.33 or higher are officially supported by airmon-ng.

Error installing on twrp:
Nethunter kernel installer
Checking device compatibility...
Error : unsupported device.
Aborted.
Failed to patch boot image.
http://i.imgur.com/3O2HxFO.jpg

**Comment by MimarSinanT** [comment]
@binkybear

**Comment by Sinns** [comment]
same issue here with my red mi note 4 nikel

**Comment by mackhossain** [comment]
i am facing the same problem.any 1 find any solutions?

**Comment by RootPwnage** [comment]
May want to copy the wlan0 part of airmon-ng and add all those interface names and add it to the script so the program knows to recognize them just a thought
