### ISSUE TITLE
no download link for galaxy s5 in the official website 

### ISSUE THREAD

**Issue by beav0team** [offensive-security/kali-nethunter#823]

**Comment by MimarSinanT** [comment]
CyanogenMod 12.1 or any Android 5.x based AOSP ROM: lollipop
CyanogenMod 13.0 or any Android 6.x based AOSP ROM: marshmallow
TouchWiz 5.1: touchwiz-lollipop
TouchWiz 6.0: touchwiz-marshmallow

Download here: https://idlekernel.com/nethunter/nightly
Your device is: klte

**Comment by AutinDroid** [comment]
Actually build.nethunter.com/nightly
