### ISSUE TITLE
bootimg patch fail

### ISSUE THREAD

**Issue by Ankris** [offensive-security/kali-nethunter#824]
## Issue: "Error: Unable to find archiever for gzip!"

**Comment by Ankris** [comment]
It was the TWRP fault. Using 3.1.0.0 fixed it.

**Comment by dhanush-raj** [comment]
@Ankris can I get the link to kernel sources..
Or the pelya patch file

Or else how did you patch the kernel I was not able to do it..
Help me...

_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
