### ISSUE TITLE
Is nethunter compatible with lineage  os 14.1 on the Oneplus one?

### ISSUE THREAD

**Issue by xavkno** [offensive-security/kali-nethunter#825]
## Issue: Is nethunter compatible with lineage  os 14.1 on the Oneplus one?

Thanks in advance.

**Comment by xavkno** [comment]
And then just use the generic arm zip right?

**Comment by BZBaXraM** [comment]
Yes

**Comment by H4dr1en** [comment]
Hi, is nethunter also compatible with lineage os 14.1 on the one plus 3 (7.0)?

**Comment by Nairod785** [comment]
@BZBaXraM The link is dead, can you resend it please?
I can't find the kernel here https://build.nethunter.com/nightly/3.15.4-20170211-0304/

**Comment by TheGroundZero** [comment]
I found this (older) version: https://www.androidfilehost.com/?fid=457095661767132824

I'm also looking for a more recent version of Kali NetHunter for OnePlus One (bacon) running LineageOS 14.1 (Android 7.1.1)

**Comment by flatounet** [comment]
TheGroundZero : I found this (older) version, I think: https://www.androidfilehost.com/?fid=457095661767132824

i have 1+1 bacon ,
installed : lineage-14.1-20170410-nightly-bacon-signed.zip
flashed zip in TWRP : update-nethunter-bacon-lineageos-14.1-20170126.zip

look fine ,updated chroot ok

but crash when a shell is open , "terminal emulator as been stoped ....." in white box ...
i have TL-WN722N wirlesscard.

my only way to get nethunter working ,is flashing : 12.1-YOG4PAS3JL + nethunter-oneplus1-lollipop-3.0.zip
like this all work fine.
but no update possible ....

can you drive me for fix my probleme ??? 
thank's

**Comment by reubadoob** [comment]
Having the same issue in choosing which version of Nethunter to install on my OnePlus One running 

- **Lineage OS:** 14.1-20170821-NIGHTLY-bacon 
- **Android Version** 7.1.2

**Comment by kellrobinson** [comment]
I have a Oneplus One phone with TWRP recovery and running 
lineageos 14.1-20180108-NIGHTLY-bacon
I am not using multirom.
I was able to flash kali on my OPO, using
update-nethunter-bacon-lineageos-14.1-20170126.zip
downloaded from
https://androidfilehost.com/?fid=457095661767132824
after flashing, I wiped dalvik/cache.
The phone booted just fine.
