### ISSUE TITLE
Nexus 10 kali wont run

### ISSUE THREAD

**Issue by danielbublil** [offensive-security/kali-nethunter#827]
### Built from repo (date and build command) or downloaded from website (links):
nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip
Then i flashed 

kernel-nethunter-manta-lollipop-3.15.4-20170211-0304.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.67-00092-g7b02438 (root@kali) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Thu Sep 24 01:04:17 UTC 2015

## Issue:
Nethunter app no interface are listed
When i am opeing kali terminal, android terminal is open instead.

Chroot full installed..
Busybox installed..
Tnx for helping!

**Comment by danielbublil** [comment]
![screenshot_2017-03-11-14-40-43](https://cloud.githubusercontent.com/assets/11839918/23823332/d549a912-0668-11e7-8bbd-d38309162aa7.png)
![screenshot_2017-03-11-14-40-14](https://cloud.githubusercontent.com/assets/11839918/23823333/d54a0146-0668-11e7-884d-2f8a8dad0588.png)

**Comment by cr1p70** [comment]
This cr1p70 have a look here hope it helps.

https://forums.kali.org/showthread.php?24474-Nexus-10-Nethunter-freezeing
