### ISSUE TITLE
Kali terminal crashes

### ISSUE THREAD

**Issue by Bexian** [offensive-security/kali-nethunter#828]
### Device:

Samsung galaxy S3 GT-I9300

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Android Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170211-0304/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.0.101-lineage-gd8fd4d5 (@lineageos-build) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Wed Mar 8 08:06:53 UTC 2017

## Issue:

Terminal-nh.app closes when i choose kali option with the error. "FATAL: kernel too old"
If i choose android or androidSU it works fine.

chroot is installed but when i try to install meta packages with nethunter.app it closes because of the terminal error.

busybox output:
BusyBox v.1.26.2-Stericson (2017-01-14 16:15:58 PST) multi-call binary.

when i do:
"su -c bootkali" or "su bootkali"
it says "FATAL: kernel too old"

**Comment by BZBaXraM** [comment]
This kernel old! Nethunter version not supported it kernel!

**Comment by Bexian** [comment]
which version does it support?

**Comment by mpkosewski** [comment]
Download kali generic full chroot from nightly builds along with the appropriate kernel for your device. 

Do clean Android OS image,;
Root device;
Install kali generic full chroot from twrp recovery ;
Then install the kernel after in twrp recovery.

**Comment by Bexian** [comment]
> Download kali generic full chroot from nightly builds along with the appropriate kernel for your device.

Downloaded from https://build.nethunter.com/nightly/3.15.4-20170211-0304/
1. kernel-nethunter-generic-armhf-3.15.4-20170211-0304.zip
2. nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip

> Do clean Android OS image,;
Root device;
Install kali generic full chroot from twrp recovery ;
Then install the kernel after in twrp recovery.

Installed twrp, wiped everything then installed lineageOS
Device rooted
installed 1. then 2. and cache cleared.
i open therminal and it crashes. it has root permission.
so from the 2. i extracted /data/app/Term-nh.apk and installed it. now it works but it have the same "FATAL: kernel too old" if i use Kali or bootkali option. i've tried to reinstall chroot full but nothing change. busybox is installed. What can i try now?

**Comment by marxenegls** [comment]
exact same issue , i build it the same way using the python build.py and although i tweaked the device list copied the mako folder from lollipop into the marshmallow dir . It built fine made an uninstaller.zip too . My cm13 marshmallow .
$ cat /proc/version
 Linux version 3.4.0_IthebChiKali0-Gee (ubuntu desktop (gcc version 4.8) 1 SMP PREE MTP 2016 )

**Comment by mpkosewski** [comment]
All I can say from my experience, device type aside, using any Android OS other than stock image from Google I can't guarantee to work. Although there are still lots of bugs to work out even with the stock OS, everything is technically functional like terminal not crashing etc. Although a common fix for that is to remove the kali chroot from the kali nethunter menu and reinstall it via the same menu

**Comment by mpkosewski** [comment]
Woops, my reply was a bit late to previous comment sry lol
