### ISSUE TITLE
Magisk Support request

### ISSUE THREAD

**Issue by xavkno** [offensive-security/kali-nethunter#829]
## Issue: could you please add support for magisksu instead of SuperSU as it is has more functions and it can hide itself from safetynet out of the box.

I know it may not be high on the priority list but I also worry a bit about the new closed sourceness of the new SuperSU and it being developed by an previously unknown Team.

**Comment by BZBaXraM** [comment]
You can uninstall magisksu, and flash SuperSU.

**Comment by xavkno** [comment]
Please read the whole issue.

**Comment by BZBaXraM** [comment]
I'm read

**Comment by asomyhz** [comment]
Hi 
Iwant run nethunter in my sony xperia core s 
pleeeez help ...
and thanks

**Comment by Z3brahStripe** [comment]
What if you replaced SuperSU.zip with magisk.zip, inside the nethunter(devicename).zip?

**Comment by keeganjk** [comment]
@Z3brahStripe Results in "Error 1"...

**Comment by blackzafiqz** [comment]
@keeganjk The error appeared because your modified zip is unsigned. Sign it first before flashing

**Comment by keeganjk** [comment]
I think error 1 is from not using the default boot image

**Comment by keeganjk** [comment]
@Z3brahStripe Should I name magisk.zip supersu.zip?
