### ISSUE TITLE
Samsung j-700HXXU

### ISSUE THREAD

**Issue by Crow-1** [offensive-security/kali-nethunter#830]
Most of people in Egypt and Other countries use this phone (Samsung j-700HXXU) please Make #NetHunter for this mobile

**Comment by AutinDroid** [comment]
@Crow-1 is there a TWRP build for this device?

**Comment by Crow-1** [comment]
yes and i had install the chroot and its work but i want official rom from #offensive-security becouse kernel doesn't work hid attack or bad-usb
and i had bought Tl- WN722N but it's don't work for kernel
only we want kernel for samsung j7h v1 becouse most off pentest in our country use it

**Comment by Crow-1** [comment]
that is the phone http://www.gsmarena.com/samsung_galaxy_j7-7185.php 
it's for very price that's why most of people bought it please support this phone with rom and kernel 
thanks to God then you .

**Comment by AutinDroid** [comment]
@Crow-1 Sure! Ill look into the build of this kernel. I have to build kernels for a few other devices, and after those are done, I'll try to build the kernel.

**Comment by Crow-1** [comment]
thank you so much .but make sure to make the kernel for the first version of samsung j7h not j7f .how much time you want to finish .and thank you again Egyptians love you ;D

**Comment by Crow-1** [comment]
you promised me @AutinDroid

**Comment by AutinDroid** [comment]
@Crow-1 sry school is taking up a lot of time, but I have spring break. I'm still doing work,but meanwhile if you can find kernel sources would be helpful

**Comment by Crow-1** [comment]
please help me ,it's very important me ,you can record video to learn me
how to make the kernel with c++ ,or make it in your free time please please

**Comment by Crow-1** [comment]
Now I have HTC One M9 can you build kernel for it please
