### ISSUE TITLE
Boot compression broken

### ISSUE THREAD

**Issue by Ankris** [offensive-security/kali-nethunter#832]
## Issue: After compiling the kernel with the patch applied, the boot compression (xz) gets broken for some reason. I can boot with no issues the non-compressed kernel Image from fastboot.

Ideas, ples?

**Comment by gerardo-junior** [comment]
Up

**Comment by dhanush-raj** [comment]
@Ankris can I know how did you apply the patch by pelya..


_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jcadduono** [comment]
we don't have an xz compressor built into the installer so it uses gzip as a backup compression format assuming it to be universally supported. be sure to enable gzip support for ramdisks in your kernel config.
