### ISSUE TITLE
OnePlus One DuckHunterHid not working!

### ISSUE THREAD

**Issue by JordiWD** [offensive-security/kali-nethunter#834]
### Device:
Oneplus One

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat ,  kernel-nethunter-bullhead version 3.15,4

## Issue: 
DuckHunterHID is not doing anything, HID Attacks work
Also some Kali services i start dont stay ON. Please help

**Comment by forid786** [comment]
Have you changed the language to the one used by the machine you're targeting? It's on American English by default.
