### ISSUE TITLE
When net hunter will be released for Nexus 6 (androud 7.1.1) , flashing the Marshmallow build bricks the phone.

### ISSUE THREAD

**Issue by dannyrock** [offensive-security/kali-nethunter#836]
### Device:

nexus 6 (shamu)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

android version 7.1.1

## Issue:
NEED a version which works with nexus 6 shamu (android 7.1.1 )

**Comment by hightechstl** [comment]
You might take a look at 
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-test1.zip

**Comment by hightechstl** [comment]
Disregard that one. 
https://build.nethunter.com/nightly/3.15.4-20170110-0950/

**Comment by dannyrock** [comment]
@hightechstl  
https://build.nethunter.com/test-builds/huawei/kernel-nethunter-angler-nougat-test1.zip
does this work with nexus 6(7.1.1) ?

**Comment by simonpunk** [comment]
@dannyrock, I am running nethunter on my nexus6 7.1.1 already..just download the right one, https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-shamu-nougat-3.15.4-20170211-0304.zip

**Comment by dannyrock** [comment]
@simonpunk  i installed this one but now my audio is not working

**Comment by simonpunk** [comment]
@dannyrock
update your rom to the latest offical room first, then flash my built zip: https://drive.google.com/file/d/0B-cBdArdvHDxOVcxWmxic2tIeE0/view?usp=drivesdk

**Comment by dannyrock** [comment]
@simonpunk 
from where can i download the generic full kali rolling 
https://build.nethunter.com/nightly/3.15.4-20170211-0304/ 
from here right ? can  u specify by link which one cuz there are couple of em? 
SO steps i should follow now are ::
1)Flash the latest stock rom ( from here::https://developers.google.com/android/images)
2)Flash twrp 
3)Flash super SU
4) flash the generic full kali rolling (via twrp) (Which you will specify)
5)Flash your kernal via twrp (This one ::https://drive.google.com/file/d/0B-cBdArdvHDxOVcxWmxic2tIeE0/view?usp=drivesdk)

here is the issue i opened if you want to see any more details about device  https://github.com/offensive-security/kali-nethunter/issues/873
Thanks

**Comment by simonpunk** [comment]
@dannyrock , the full kali rolling is this one: https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip

the steps you list is correct, but I am not sure if my kernel still works on the N6F27C, you may try, or I will compile the  kernel again once I get time.

**Comment by dannyrock** [comment]
@simonpunk kernel not working good , im having alot of reboots , please inform me when u compile new one , btw how do you compile .
im using official method 
ie
python build.py -d shamu --nougat --rootfs full --release v3.1
the build generated by it have sound issues

**Comment by simonpunk** [comment]
@dannyrock because your kernel zImage-dtb is not updated.

this command `python build.py -d shamu --nougat --rootfs full --release v3.1` can only build the flashable zip but not the kernel itself.

To do that, you have to compile the kernel source code to build the zImage-dtb first, then copy the zImage-dtb to /nethunter-installer/devices/nougat/shamu/, when you specify the "-d shamu", the build script will refer to shamu's kernel folder which is "/nethunter-installer/devices/nougat/shamu/" and pack it up.

I have uploaded the kernel zip file, you may extract the zImage-dtb from it and replace the zImage with the old one in that directory I just mentioned, then use that command to build again. Or after flashing the generic full kali rolling zip, then flash my kernel zip.

here are my new build kernel zip file:
[Kernel zip for Nexus 6](https://drive.google.com/open?id=0B-cBdArdvHDxRU9MX1RpMVB0Y2M)

I haven't try yet, because my nexus 6 is not up to date, but it should work.

P.S. remember to install the latest twrp recovery first.

**Comment by dannyrock** [comment]
@simonpunk ok got you so actual problem is with compiled kernel "zImage-dtb" which is pre present in  "/nethunter-installer/devices/nougat/shamu/" ...if yes .. it would be great if you report them so they can update the official zImage-dtb

**Comment by simonpunk** [comment]
they haven't been updating anything since 22nd Feb. thats why most of the recent issues were regarding to non-updated kernel, especially for nexus6, there are always some changes with the sound on each update, thats why the old kernel always fails on each update rom.

Btw, I have tagged binkybear and jcadduono, but got no response, so I decided to do it myself, just never knew there are so many nexus6 users here.

**Comment by BearChavez** [comment]
I've seen people still comment on this so I figured I'd ask on here, but how would I install the firmware-ralink package on my NetHunter device?

**Comment by simonpunk** [comment]
Do you mean the firmwares for ralink wireless dongle? I know there are some firmwares already included in the kernel zip files, but I dont know if they work for your ralink dongle.

**Comment by BearChavez** [comment]
I know the chipset driver is in this package: https://packages.debian.org/wheezy/firmware-ralink 
I just don't know how I'd add the repository it is in to the repo list. I've done this on PC, but not on this before

**Comment by dannyrock** [comment]
@simonpunk i see , btw i have installed your kernel every thing is working fine , hid attacks were not working but i eddied some configurations and they also started to work the only problem now is that usb keyboard is not working this one
https://github.com/pelya/android-keyboard-gadget
it says i need custom kernel..
it would be great if you build kernel with this .. thanks .. btw if you also can write a guide to build kernel that would be more appreciated, so i can build my own , cuz android versions are updating every day ..and i dont want to open issue every day..
i did some research and found the source code of kernel and found a way to compile it 
https://source.android.com/source/building-kernels
from here i can build a "zImage-dtb"
So my questions are 
Q1) So if i compile my kernel from there and replace the ""zImage-dtb" in https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-shamu-nougat-3.15.4-20170211-0304.zip
is that all i have to do? if not can u please explain :)
Q2)To run usb keyboard what else i have to do? build kernel and then ? how can i apply this patch 
https://github.com/pelya/android-keyboard-gadget/blob/master/kernel-3.10-nexus6.patch
Q3)how can i make a original compiled kernel a custom one.
by editing kernel source code? 
or the bunch of patch files in "https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-shamu-nougat-3.15.4-20170211-0304.zip" do the work
i know i asked for too much but please gimme a reply cuz i wanna learn some thing here

**Comment by BearChavez** [comment]
My dongle is a Ralink 5370 chipset

**Comment by simonpunk** [comment]
@dannyrock , the hid function is actullay working, I just set it to NOT always enabled just for the flexibility of usb attack, the author mentioned we can disable it , thats why you need to switch the usb state to "hid" first, to do that you can simply type this command in androidsu terminal: `setprop sys.usb.config hid`
but also you can see how it does in the file "init.nethunter.rc" which located at the root directory of your device.

for compiling the kernel, take a look at these articals:
1: set up the build environment first: https://forum.xda-developers.com/chef-central/android/guide-how-to-setup-ubuntu-16-04-lts-t3363669
But make sure you choose the right branch to repo sync when doing "repo init xxxxxxxxxxxxx -b xxxxxxxxx" step
2: download the kernel source code: https://forum.xda-developers.com/android/general/guide-building-android-kernel-osx-t3431794
Just dont mind even if it says for MAC OS.
3. Modify and compile the kernel, https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

You may come across alot of problems like I do before, but google is the only way and friend to help us solve them.

**Comment by simonpunk** [comment]
@dannyrock, forget to answer you Qs.
Q1. You can do that, or after replacing the your zImage-dtb, then type "python build.py -d shamu --nougat -k".

Q2. Apply the patch first before "make" command, but there is one line you have to muanlly add to code by youself after using the patch command. 

Q3. Yes, edit the source code which are all c code files, you can patch it as well, when you are done with the code, you may use "make menuconfig" to select the items you want, you can just follow the Wiki guide I listed above.
If you patch the code right, it should not have any problems when building the zImage-dbt using "make" command.

**Comment by BearChavez** [comment]
@simonpunk The chipset is a Ralink 5370

**Comment by dannyrock** [comment]
@simonpunk thanks man great help ... Respect (Y)

**Comment by thcabq** [comment]
Wondering if I can get that kernel. Simonpunk  the kernel file is no longer supported by drive
 Thank you

**Comment by arshiay** [comment]
please help me to install nethunter3 on nexus6 Nougat

**Comment by bpartin2009** [comment]
@simonpunk What do you do if you have twrp flashed the kernal....zip file before the generic*arm*rolling*full*.zip has been flashed? The wiki says to flash the full zip first then the kernal zip. Do I / can I undo this kernal flash? Then go back and do the full zip first? Also is the Nexus 9 and 6 both a armhf architechture? Where can I find this out?

**Comment by bozwald** [comment]
They changed the build.py to include the kernel it's likely you are
installing two kernels and breaking the build, try installing twrp then
just the zip build for your device it should have the kernel inside
already, obvious as with anything backup first.

**Comment by bpartin2009** [comment]
reading the build.py.... it looks like if use option "--rootfs full" then it will construst the file name and path to include the full chroot along with the kernal zip for the specific device. If not then it assumes you are just building an update kernal zip file. I will go back and rebuild with the --rootfs full option and see if I don't make a > 600MB zip file. That being said, is there any harm in the fact that I already falshed a 9MB device kernal zip file? Or can I just flash again with the full zip and be OK? Alternatively, I can flash the https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip first and then after reboot, go back into twrp and flash https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-flounder-nougat-2017.11-18-1618.zip right? As opposed to rebuilding my own one shot full zip with "python build.py -d flounder --nougat --rootfs full"? Any Pros or Cons to doing one way or another? FYI, so far I have only twrp flashed nightly/2017.11-18-1618/kernel-nethunter-flounder-nougat-2017.11-18-1618.zip by mistake.... no full kali, just this 9.6MB file.
