### ISSUE TITLE
Oneplus 3T terminal crash and close

### ISSUE THREAD

**Issue by dmoulden** [offensive-security/kali-nethunter#837]
### Device:
Oneplus 3T running OxygenOS 4.0.3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170211-0304.zip

https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-oneplus3-nougat-3.15.4-20170211-0304.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.31-perf+ (OnePlus@ubuntu-21) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Feb 8 18:26:20 CST 2017

## Issue:
Every time I open the nethunter terminal and select Kali it crashes and closes immediately

**Comment by dmoulden** [comment]
The nethunter app also closes when I try to run anything that spawns a terminal.

**Comment by jcadduono** [comment]
This is to be expected when you only install half of NetHunter.
A permissive nethunter kernel is necessary for things to work properly.

**Comment by dmoulden** [comment]
Thanks for this jcadduono.

Can you elaborate on how to do install a permissive nethunter kernel on the 3T?

As far as I'm aware I followed the install guide correctly.

**Comment by dmoulden** [comment]
Never mind. Thanks for your help and sorry to bother you. All is working.

**Comment by chhc007** [comment]
@dmoulden  
All is working? Try the VPN client.It will powers off your phone and my phone shutdown itself sometimes.
