### ISSUE TITLE
type password to decrypt storage on nexus 7

### ISSUE THREAD

**Issue by xi3** [offensive-security/kali-nethunter#84]
After install on nexus 7 using nethunter windows installer v1.0.9

"type password to decrypt storage" but I never set any password during installing.

**Comment by iLoveTux** [comment]
I ran into this exact same problem (seems to be a problem with the windows installer), These are the steps I took:

1. run windows installer (got exact same output as the original poster)
2. stuck (pulled hair out)
3. got factory image from here: https://developers.google.com/android/nexus/images
4. unzip that file
5. go into directory that was created by unzipping
6. run "sudo ./flash-all.sh" (yes I switched to linux) - This put it back to factory (you may want to stop here it's safer)
7. try windows auto-installer again (I liked the idea of an automated installer)
8. same problem (grrrrr...)
9. back on my linux machine repeat steps 3-6
10. download nethunter image from here: http://images.kali.org/kali_linux_nethunter_1.10_nakasi_kitkat.zip
11. run "adb push kali_linux_nethunter_1.10_nakasi_kitkat.zip /sdcard/"
12. wait....this takes forever
13. run "adb reboot recovery"
14. didn't work (android with a red caution sign) (frustrated)
15. gave up and wondered why nethunter won't come like the factory images so I can just run "adb flashall"

If you could give me some help from here I would appreciate it.

**Comment by iLoveTux** [comment]
This seems likely related to these discussions:

http://forum.xda-developers.com/showthread.php?t=2573015
http://forum.xda-developers.com/showthread.php?t=2417097

can anyone confirm?

also, can anyone confirm that NetHunter uses a custom bootloader, or is it possible that we can replace the downloaded bootloader image with a stock one of the same version.

**Comment by iLoveTux** [comment]
Ok, so I replaced the bootloader-grouper-4.23.img in C:\program files (x86)\nethunter_install\data\Factory_images\nakasi-ktu84p-factory-76acdbe9 with the one from the second link above, and the error went away, but I still get the type password to decrypt storage prompt, so I am assuming that this is a custom bootloader. 

Could someone please point me in the right direction for customizing the bootloader-grouper-4.23.img in order to resolve this?

**Comment by binkybear** [comment]
@iLoveTux - Nethunter does not use custom bootloader, it uses custom kernel but bootloader is not changed.

**Comment by iLoveTux** [comment]
OK, so I got this working by simply skipping step 6 in the windows installer (flash stock image), will this cause problems with nethunter? 

It successfully rooted my device and installed the nethunter tools which seem to be working, but I haven't had time to test extensively, and probably won't until tomorrow.

**Comment by Zaxscdvf** [comment]
@iLoveTux you can just root your nexus with the nexus rootkit and  download the nethunter image and install it manually, and to answer your question no everything should work fine.

**Comment by iLoveTux** [comment]
I'm not sure why I had so many issues getting this done, but I'm sure it's something I was doing.

Anyway, all my issues are solved. Thank you very much for your help.
