### ISSUE TITLE
VPN client powers off the Oneplus 3T when connecting

### ISSUE THREAD

**Issue by f3l1x30** [offensive-security/kali-nethunter#840]
### Device: 
Oneplus 3T

### OS version (KitKat/Lollipop/Marshmallow/Nougat): 
Nougat

### Built from repo (date and build command) or downloaded from website (links): 
nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170211-0304

### Output of `cat /proc/version` in adb shell or NetHunter Terminal: 
Linux version 3.18.47-nethunter-3.1 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Thu Jan 26 22:15:43 EST 2017

## Issue:
VPN client powers off device when I try to connect to my VPN. I've even tried bypassing apps and using the nethunter terminal to connect but as soon as I hit that "enter" key it freezes then powers off. I'll be surprised if I'm the only person to notice this but it's one of the main ingredients for a few concepts I want to test.

Many thanks

**Comment by chhc007** [comment]
Yes ! 
Same problem!

**Comment by chhc007** [comment]
Are you using the kernel built for oneplus 3 on 2017.2.11?
That kernel causes camera app crash .
I use the kernel built for oneplus 3  on 2017-6-29,camera app is working.
BUT my phone always crash now.  VPN client powers off device and some time the phone crash itself just like when using the VPN client.

I see some new kernels for op3t. I flashed but the wifi adapter can't work.

Did you try  new kernels?
