### ISSUE TITLE
VNC not working locally. 

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#842]
### Device:

Nexus 5x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat & Marshmallow tried...

### Built from repo (date and build command) or downloaded from website (links):

Followed instructions and downloaded things via this guide:

http://www.hackcave.net/2017/02/kali-nethunter-for-nexus-5xbullhead-nougat-marshmallow-tutorial.html

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140807 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016

## Issue:

Everything seems to work with the exception of the VNC app.  I can start and view the kali desktop, but mouse doesn't work and can't use keyboard shortcuts on the nexus itself.  Haven't tried VNC'ing from another device just yet.

**Comment by hightechstl** [comment]
I had this same problem on my NVIDIA Shield. It worked perfectly when I used my laptop to connect in though. Also if you want to do it locally, I have a bluetooth keyboard with a touchpad that worked Perfect for local VNC. That might be another option

**Comment by MbrooGit** [comment]
Had same problem. Do this:
1. Change password for vnc (vncpasswd)
2. Launch vnc manulally (vncserver :1 -geometry "your resolution without quotes")
That's it.
