### ISSUE TITLE
build.nethunter.com certificate overdue

### ISSUE THREAD

**Issue by FlameSky-S** [offensive-security/kali-nethunter#844]
build.nethunter.com  certificate has overdued since April 4th. 
Been waiting for 2 days to get a secure download.
Not a big problem but may raise security concerns. 
Don't know if it's ok to post it here, sorry if it's not.

**Comment by jmingov** [comment]
@FlameSky-S, thanks for the warning, we are working on it. Ill update the issue when we are done.

**Comment by jcadduono** [comment]
I have been very busy with life lately and did not notice. For anyone with access to the build.nethunter.com server, you can become root (binky/jmingov I suppose you'll need to give me a ssh pubkey) then do:
```
req-build.nethunter.com-crt
```
that should request a new cert from letsencrypt and install it and reload nginx with the new cert.

(done for now)
