### ISSUE TITLE
terminal nethunter does not work/oneplus one

### ISSUE THREAD

**Issue by vort3xx** [offensive-security/kali-nethunter#847]
When I open Terminal Nethunter, it tells me: unfortunately, terminal has stopped but, I have downloaded the Terminal Emulator from the Play Store and I have entered the bootkali , and it works. But if I open the application nethunter and update it redirects to terminal nethunter and crash again.

I have oneplus one with build marshmallow (6.0.1) update nethunter created on a terminal.
kernel version: 3.4.112-cyanogenmod-g8fbc62e root@nhbuild-box #3 Fri Aug 19:57:27 CET 2016
busybox verision: 1.26.2
![screenshot_20170409-144946](https://cloud.githubusercontent.com/assets/27137381/24837467/31649684-1d35-11e7-94e6-fa78bd625fef.png)
![screenshot-20170400145840-499x668](https://cloud.githubusercontent.com/assets/27137381/24837469/396f11b0-1d35-11e7-9f11-a0e4fafb4de9.png)

**Comment by MbrooGit** [comment]
#848

**Comment by vort3xx** [comment]
I I've tried it but the application still does not work

**Comment by MbrooGit** [comment]
Not sure that it will help but maybe you need to reinstall kali busybox?

**Comment by simonpunk** [comment]
May be you can try the following steps.
1. download another terminal app from play store
2. Open terminal and type the following:

> su
setenforce 0

3. try open nethunter terminal again and see if it works for you, if it does work, just redo above step everytime you reboot your device. At least works for me.

**Comment by vort3xx** [comment]
Omg the problem continues. I have reinstalled android marshmallow again from scratch. The version of cm is: cm-13.0-20161220-SNAPSHOT-ZNH5YAO3XH-bacon.zip and the build: update-nethunter-oneplus1-marshmallow-20170404_015106.zip , also i wipe: data system data cache dalvik/ART cache

**Comment by mattewfarel** [comment]
I have also OnePlus one with Marshmallow 6.0.1 with same kernel version and same busybox version , i am using the "cm-13.1.2-ZNH2KAS3P0-bacon-signed-fastboot_64GB" rom , i've build nethunter to "update-nethunter-oneplus1-marshmallow-20170427_203910.zip" and install it , rebooted , installed chroot , but the same problem as you , nethunter terminal is still crashing , i've even reinstalled the Android stock image , and redo all the previos work but nothing have been changed , The terminal is still not working

**Comment by MbrooGit** [comment]
flash 'generic kalifs', not 'update'

**Comment by vort3xx** [comment]
Nothing, again i have reinstalled from scratch but in this time i installed just cm13 and the kernel 3.15.4-20170211-0304,not the "update-build" and then the apps(Terminal-nethunter, openvpn... ) but terminal-nethunter continue without working

**Comment by j0nnyf1v3** [comment]
I have had this same issue on this same phone. Or I would get an error that nethunter cannot communicate with the terminal. Or that term was not installed when it was clearly right next to the app in my drawer.. Or just a blank screen on the term with no words... I need to start noting these bugs....

**Comment by rohitereddy** [comment]
> May be you can try the following steps.
> 
> 1. download another terminal app from play store
> 2. Open terminal and type the following:
> 
> > su
> > setenforce 0
> 
> 1. try open nethunter terminal again and see if it works for you, if it does work, just redo above step everytime you reboot your device. At least works for me.


this worked, thank you !!
