### ISSUE TITLE
Is it possible to install NetHunter from the SD Card?

### ISSUE THREAD

**Issue by nicko1111** [offensive-security/kali-nethunter#851]
My device Nexus 5, Lollipop!
When I will install the "chroot" it needs "kalifs-full.tar.xz" in the internal memory. But my internal memory is not able to store "kalifs-full.tar.xz", very full..
But I have a 64GB memory card (SD CARD), how do I install it from the memory card?

**Comment by Kirball** [comment]
Well the nexus 5 has no sd card slot so I don't think you can.

**Comment by nicko1111** [comment]
I use this to read the memory card: http://image.prntscr.com/image/b5873bf8feb740e7a05e096ce01a60b1.jpg
But my question was another, is it possible to do this? Is it possible to install NetHunter from the SD Card? That is my question.

**Comment by Kirball** [comment]
I don't think you should have a problem installing it that way.  Give it a try what's the worst that could happen?

**Comment by RAJD7** [comment]
I have a question.Nethunter app detects  kalifs-full.tar.xz file only from internal storage.So how can we make it detect file from external storage and install nethunter on android.Hope you guys reply.

**Comment by nicko1111** [comment]
Kirball
The NetHunter installer does not recognize the SD. It does not detect kalifs-full.tar.xz for installation. I might as well format my device and perform the installation, but I do not want to remove my files, let alone backup. Understood?

**Comment by mynamekrs17** [comment]
Watxch this and you'll know : https://m.youtube.com/watch?v=uNrT3sjbLFg

**Comment by mynamekrs17** [comment]
Install nethunter on SD CARD MEMORY : https://m.youtube.com/watch?v=uNrT3sjbLFg

**Comment by RAJD7** [comment]
Hey mynamekrs17,Thanx for the reply but he actually installs kali nethunter in the internal memory firsts and moves it to the new ext created.I actually need a way to install it directly to SD card(External stoarage) coz my phone dont have enough internal.Btw thanx again for reply.

**Comment by mynamekrs17** [comment]
It' s same bro. You just need to mount the nh data to the sd card. And then u just need to install it like usual.

**Comment by Kirball** [comment]
I think running it from an SD card would be possible but could cause you limited functionality because you need to be able to plug in a wifi or Bluetooth dongle/adapter.  But I think it's possible and with a y cable you might be able to do it.  I am pretty sure nethunter would have to install on the internal memory though so installing it using an SD card seems possible but running it from the SD card doesn't seem entirely possible or very plausible to me.

**Comment by mynamekrs17** [comment]
I have an idea :
F1RST. Install nethunter with this tut = https://youtu.be/Uq-2svXv3_E < This tut tell you how to install nethunter with only 5 mb .
Second. Mount it like this tutorial video : https://youtu.be/uNrT3sjbLFg

+ Hope this can help you +

**Comment by j0nnyf1v3** [comment]
Use Phoenix SD Formatter... That is a knarly(in a good way) piece of software for anything booting from sd cards.
