### ISSUE TITLE
Oneplus 3 crashes while using nethunter terminal

### ISSUE THREAD

**Issue by Lulz-Sec** [offensive-security/kali-nethunter#854]

**Comment by TheDarthMole** [comment]
Im having the same problems too, i open or use the terminal and then a couple of minutes later when i have closed the the app, apps start crashing and eventually the system ui crashes. It litterally leaves the last opened app open and doesn't allow me to interact with the screen at all. Pressing the power button turns off the screen but doesn't turn it back on. Holding the power button is the only way to restart it.

**Comment by franga2000** [comment]
I've just encountered the same issue. I think it could be related to #843. 
If you want to use Nethunter, I suggest you downgrade to OOS 4.0.3 (requires full wipe) or if you don't need Nethunter and just want to fix your phone, dirty flash the latest stock OOS image (no need to wipe).

**Comment by grese** [comment]
I’m seeing the same behavior with the OnePlus3t.  I’m running OOS 4.0.3 with the latest NetHunter.  I open the terminal, and a couple of minutes everything on the phone slows to a crawl.  Eventually, Android’s UI locks up and the phone crashes.

Kinda smells like a memory leak, but I haven’t tried debugging it yet.
