### ISSUE TITLE
the nethunter can support FlymeOS?

### ISSUE THREAD

**Issue by 1729831470** [offensive-security/kali-nethunter#855]
### Device:
MEIZU m2 note (Telecom version)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

### Built from repo (date and build command) or downloaded from website (links):
https://github.com/offensive-secutiry/kali-nethunter

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
not

## Issue:
the Kali Nethunter can support FlymeOS?

**Comment by BearChavez** [comment]
I need more details about Flyme to answer your question.
Does it support SeLinux? Do you have a way to set SeLinux to permissive? And do you have a custom recovery ready?

**Comment by jmingov** [comment]
But as @BearChavez says, does Flyme support Nethunter?

**Comment by 1729831470** [comment]
@BearChavez My Phone have TWRP Recovery,and SELinux

**Comment by BearChavez** [comment]
@1729831470 Is SELinux set to permissive?

**Comment by 1729831470** [comment]
@BearChavez yes.I unlock the oem lock

**Comment by BearChavez** [comment]
You need to check the SELinux status. OEM unlocked doesn't relate to the SELinux status. I need to know what state it is in to provide you with the correct setup instructions

**Comment by 1729831470** [comment]
@BearChavez My Device SELinux status is normal

**Comment by BearChavez** [comment]
@1729831470 In your settings, go to About Phone and look for SELinux status and tell me what it says
