### ISSUE TITLE
problem with download drivedroid

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#856]
## Issue:
```
~/kali-nethunter/nethunter-installer# ./build.py -d flo -m -f -fs full
Force redownloading all apps
Downloading: Hackerskeyboard.apk (1303164 bytes)
    1303164  [100.00%]
SHA512: 8c861c7540e6eeb006070d0f2d80134e75637066591d705b987e164c3fe87521ed694ac844c945eb74449aff8723ff039f793b2e3743aac73865f74bb248edf5
Expect: 8c861c7540e6eeb006070d0f2d80134e75637066591d705b987e164c3fe87521ed694ac844c945eb74449aff8723ff039f793b2e3743aac73865f74bb248edf5
Hash matches: OK
Download OK: update/data/app/Hackerskeyboard.apk
Error: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

**Comment by 3xpl01ts** [comment]
The softwarebakery website, from which drivedroid is being downloaded, has an expired ssl certificate. A workaround for this is to change https to http in line 148 in build.py .

**Comment by rubencabrera** [comment]
I had a different error message but the same solution worked, thanks @3xpl01ts 

This was my error, in case someone is looking for it:

```
Download OK: update/data/app/Hackerskeyboard.apk
Error: hostname 'softwarebakery.com' doesn't match 'dev.softwarebakery.com
```

**Comment by kimocoder** [comment]
Anyone still encountering problems? I've updated the DriveDroid app in NetHunter recently, but please REPORT BACK here if you're encountering problems.

**Comment by technwarrior** [comment]
Hi,

the problem still exists though it's due to the expired SSL certificate of bakerysoftware.com. The work-around provided by @3xpl01ts did the trick for me.

**Comment by kimocoder** [comment]
I will make a commit in some hours, thanks for reporting back sir
