### ISSUE TITLE
 Nexus 10 install i only get green icons that dont run

### ISSUE THREAD

**Issue by Kirball** [offensive-security/kali-nethunter#858]
## Issue: I have rooted my device then I installed nethunter but I cant open any apps1.  I dont have the nethunter wallpaper either.  The apps dont have the right names either they appear to have file types and creator names.  I will include screenshots.
![screenshot_2017-04-18-11-48-12](https://cloud.githubusercontent.com/assets/9312917/25140029/f37f59c2-242c-11e7-9f8d-419ee9bf2b87.png)
![screenshot_2017-04-18-11-48-17](https://cloud.githubusercontent.com/assets/9312917/25140033/f6b44008-242c-11e7-942c-4d7b4cae67cb.png)

**Comment by a7ent** [comment]
try going into security and checking allowed apps from unknown sourses. also, try reinstalling the apks from the generic linux package. /data/apps

**Comment by Kirball** [comment]
I fixed it by installing the nightly build.

**Comment by velazguez** [comment]
@Kirball Pls how to install link??

**Comment by Kirball** [comment]
https://build.nethunter.com/nightly/

**Comment by velazguez** [comment]
Which  to i download pls links

**Comment by Kirball** [comment]
It depends on the device you are installing it to.  Pick the most recent date then pick your device then download and install.

**Comment by velazguez** [comment]
My device Nexus 10 Manta

**Comment by Kirball** [comment]
https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-manta-lollipop-3.15.4-20170211-0304.zip
Sorry for the late reply but that's the nightly build you would use for the latest version

**Comment by numaphlex** [comment]
Sorry to hijack this, i also have manta, just a question, why does the rooting process makes youtube app disappear? also have hammerhead and it doest happen, not even when nethunter is installed and it says that its moving lots of apps to /somewhere/else... thanks.
