### ISSUE TITLE
SELinux issues on latest build of LineageOS Nougat

### ISSUE THREAD

**Issue by 3xpl01ts** [offensive-security/kali-nethunter#859]
### Device:

Probably all devices which use the latest build of Lineage OS. Mine is OnePlus 2.

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat

### Built from repo (date and build command) or downloaded from website (links):

Built from repo (python build.py --generic arm64)

## Issue:

I have noticed that many people have reported that the terminal crashes on startup on Nougat. The problem seems to be in SELinux like in this bug report #578 . I know that I am not using a kernel from the nethunter-devices repo, but none of them work on Lineage 14.1 for OP2, so at the moment I am using the stock kernel. Busybox, supersu, and bootkali work, but the terminal still crashes. Maybe building a kernel which runs in permissive mode all the time could solve this, but I don't know how to do it.

I only built a custom kernel, which is based on the stock Lineage kernel: https://github.com/3xpl01ts/android_kernel_oneplus_msm8994-los . It has all the standard patches, but is useless, since it doesn't fix anything. I don't use it right now, so this is a bit irrelevant.

The only workaround for this issue is to run su && setenforce 0 in another terminal app, but this is a bit uncomfortable.

It would be great if someone wishes to help.

**Comment by bkr32** [comment]
try running a HID attack from the NH app, it should work fine after that, at least in my trials

**Comment by 3xpl01ts** [comment]
Well this workaround just sets the kernel to run in permissive mode. Looks like I have to make a custom kernel that runs always in permissive mode. But the problem is that I don't know exactly how to configure this.

**Comment by simonpunk** [comment]
maybe try to edit the init.nethunter.rc inside the flashable kernel zip? I haven't try it, but seems a way to achieve it. 
Edit that file, add "setenforce 0" under the line where contains "on boot", and flash the zip again, see if works or not, but it's just my thought, never try it before.

**Comment by 3xpl01ts** [comment]
Thanks for the idea, @simonpunk . But that did not work. After I booted the device, the kernel was still enforcing. I am starting to think that Lineage OS is putting the kernel in enforcing on startup, which is happening after the kernel loads. A couple of months ago, on older Lineage builds, I had no such problem. It's got to do something with the ROM.

**Comment by simonpunk** [comment]
@3xpl01ts May I know if you have followed the steps below? just want to be clear what exactly you have done so that I wont do it next time.

1. extract that file from the flashable zip.
2. add the command to the line and save it.
3. replace that one from the zip with the edited one.
4. flash the zip again.

or you just edited that file in the root directory?

**Comment by 3xpl01ts** [comment]
Yep, I followed the exact same steps. The file I edited was /boot-patcher/ramdisk-patch/init.nethunter.rc . I added setenforce 0 just below the on boot section.

**Comment by simonpunk** [comment]
Thanks, and I just found this article.
https://wiki.gentoo.org/wiki/SELinux/Tutorials/Permissive_versus_enforcing#Disabling_through_the_boot_parameter
But I dont have that mentioned path in my /etc directory.
So maybe I will try to compile my kernel with that SECURITY_SELINUX_BOOTPARAM_VALUE set to 0 and see if it works or not.

https://android.googlesource.com/kernel/common/+/android-3.10/security/selinux/Kconfig

**Comment by 3xpl01ts** [comment]
Lineage OS is getting on my nerves now. I tried the SECURITY_SELINUX_BOOTPARAM_VALUE and after reboot the kernel was still enforcing. Then I edited the /system/etc/init.d/90userinit file and added setenforce 0 to it - STILL ENFORCING AFTER REBOOT. I don't know what the hell did they do with this ROM, but it is trying to be secure as hell. In dmesg I can see that SELinux starts in permissive and finishes initialization in enforcing. I have no idea why this is happening.

**Comment by simonpunk** [comment]
@3xpl01ts Hi, I have tried to config the SECURITY_SELINUX_BOOTPARAM_VALUE but it gives me a recovery boot loop, so I googled again, and found this artical, http://www.mobilearmy.net/en/set-selinux-permissive-boot/

So I just downloaded the app "universal init.d" and add the line "setenforce 0" to my "90userinit"(depends on your device), toggle on the button, then reboot. now It working like a charm for me.
But I don't know if it works for you, you may give a try.

**Comment by 3xpl01ts** [comment]
I am glad that you solved your problem, @simonpunk . But sadly, it did not work for me. My ROM is still running in enforcing mode after reboot. It looks like selinux is blocking init.d, see here: https://jira.lineageos.org/browse/BUGBASH-406 and I don't see any workaround for this other than to rebuild the whole Lineage OS ROM with selinux disabled, but that is not a very good solution. I will try to find a better solution for this.

**Comment by 3xpl01ts** [comment]
I found the best workaround for this. Instead of supersu, I installed [Magisk](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445) and installed this [module](https://forum.xda-developers.com/apps/magisk/module-magisk-selinux-permissive-script-t3577549) . I don't have any selinux issues any more and it works perfectly because now I don't have to wait any applications to run on boot. Maybe this could get integrated in the nethunter installer. I personally think that Magisk is better than supersu because it is open source and it has more features.

**Comment by simonpunk** [comment]
@3xpl01ts Thanks, that works for me too. However, I still can't get the safetynet bypassed, but it's not a big for me. 
Now, I have spent a whole week to just google how to turn the android device into cdc ethernet network adapter, but seems no one ever interests on this, there is no article talking about this. 
I just want nethunter to be like bashbunny which does all the same usb attacks without extra usb device and money, we now just can't simulate a cdc ethernet based network adapter which works for MAC OS.

**Comment by 3xpl01ts** [comment]
@simonpunk you can pass the safetynet test by enabling "Magisk Hide" in the settings of the Magisk Manager app. It hides everything, even the permissive mode, so you won't have any problems. Some apps tend to crash when they detect a rooted device and Magisk hides all the "nasty" stuff you have made to your device :D, and everything works just fine.

As for the ethernet usb attacks, I think that your kernel needs a special module like the g_ether module for the raspberry pi. I found some stuff here http://linux-sunxi.org/USB_Gadget/Ethernet .

**Comment by simonpunk** [comment]
@3xpl01ts , I tried "Magisk Hide" but still nothing works, it says I don't have supersu installed something like that, but never mind, not really a matter to me.

but for the ethernet usb attacks, not like raspberry pi, android cannot load the those usb module independently, because it is designed to use android composite gadget in default setting. I have tried to compiled the usb gadget to module, but it gave me so many errors. 

also, when I turn my usb functions into ecm_qc, it does show up a new network interface called "ecm0", and my Mac does detect it as a ethernet adapter device, but it never gets a valid ip address even I have dhcp the ip to ecm0. From the dmesg log in my android says it failed with my dwc3 usb controller, so I really don't know what to do, I think we must need someone to make patch for this.
So right now still we cannot conduct a badusb attack against mac OS..

**Comment by 3xpl01ts** [comment]
Well, you can open a separate issue for this. Someone could help :). About Magisk, I think that you only installed the app from google play. You need to flash the zip which includes an open source su. It should be flashed on stock, unrooted ROM. Here is a [link](https://redirect.viglink.com/?format=go&jsonp=vglnk_149415248725316&key=f0a7f91912ae2b52e0700f73990eb321&libId=j2ejrktl01000n4o000DL2u37bhib&loc=https%3A%2F%2Fforum.xda-developers.com%2Fapps%2Fmagisk%2Fofficial-magisk-v7-universal-systemless-t3473445&v=1&out=http%3A%2F%2Ftiny.cc%2Flatestmagisk&ref=https%3A%2F%2Fgithub.com%2Foffensive-security%2Fkali-nethunter%2Fissues%2F859&title=%5B2017.4.26%5D%20Magisk%20v12.0%20-%20Root%20%26%20Universal%20Systemless%20Interface%20%5BAndroid%205.0%2B%5D&txt=Latest%20Magisk) for it. I might integrate it in the nethunter installer when I have the time.

**Comment by simonpunk** [comment]
thanks anyway, I think this post can be closed now, and also, I saw there is still a new build for nexus 6, I remember google said they have stopped nexus6's update support, but I will try to compile the kernel again once I get time.
