### ISSUE TITLE
development stopped?

### ISSUE THREAD

**Issue by buttha** [offensive-security/kali-nethunter#860]
is it a my impression?
Last git's commits months ago, no new nougat devices in nethunter-devices repository, there are issues with lineageOS 14 (for example, with my oneplus one gestures are not working, connection tethering too), I see various opened issues here.
It's a pitty, I can't use nethunter anymore :-(

**Comment by BesoBerlin** [comment]
it looks like.. @jcadduono @binkybear ... a short information would be nice... is there a reason for this? such engaged guys as you are, wouldn't "stop" developement for no reason and without any information, would you?

**Comment by 3xpl01ts** [comment]
I think that they are focused on developing this https://github.com/nethunteros .
