### ISSUE TITLE
Terminal crash and wireless card freezes when used. 

### ISSUE THREAD

**Issue by michael86** [offensive-security/kali-nethunter#863]
### Device:

HTC one m7 

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Both Marshmallow and Nougat

### Built from repo (date and build command) or downloaded from website (links):

repo: 

Marshallow: python build.py -d m7cm --marshmallow -fs full

Nougat: python build.py -d m7cm -nougat -fs full

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.111 (michael8t6@ubunutu) (gcc version 4.8 (gcc) ) #1 SMP PREEMPT Mon Apr 24 14:49:29 PDT 2917

## Issue:
Nethunter terminal crashes after selecting any of the three terminal options (kali, android and androidsu)

I've filled out the device.cnf and added my patched zImage to the relevant device directory, flashed the rom, flashed the nethunter build.zip. Everything seems to have installed okay, I have all the apps installed, nethunter opens okay and detects the chroot. Tested the rubber duck hello world script and that worked perfectly. However, when I try to open any terminal it just crashes. 

I've built the kernel for both marshmallow and nougat and both do the exact same thing. 

Also when I plug my wireless card (Alfa AWUS051NH v.2)  in via a otg cable, nethunter detects it but as soon as I try to do anything with it like changing the mac, the card lights up and then becomes unresponsive and is no longer detected by nethunter. Again, this happens with both the marshmallow and nougat builds. When building the kernel, I made sure the drivers for this card (rt2800usb) were included in the config. According to the wiki, the predessor (v.1) is confirmed as working so am I wrong in assuming the V.2 should work as well? Works fine in a vm runing Kali.

**Comment by michael86** [comment]
Just discovered, if I open another terminal app and run

`su
bootkali`

I can get into nethunter terminal that way.

**Comment by 3xpl01ts** [comment]
See [here](https://github.com/offensive-security/kali-nethunter/issues/859) for possible workarounds. This is a common problem when selinux is in enforcing mode.

**Comment by MattBarbier** [comment]
I recompiled the terminal app (cloning [source](https://github.com/binkybear/Android-Terminal-Emulator) from github) changing just a couple lines of code in the gradle.build file from module "term":

`targetSdkVersion 25`

to:
`targetSdkVersion 23`

and
`dependencies {
    compile project(':emulatorview')
    compile project(':libtermexec')
    compile 'com.android.support:support-v4:24.2.1'
}`

to:
`dependencies {
    compile project(':emulatorview')
    compile project(':libtermexec')
    compile 'com.android.support:support-v4:25.2.0'
}`

tested on Nexus 5X 6.0.1 and Nexus 5X 7.0.0, never crashed again
