### ISSUE TITLE
Boot animation not made specifically for Nexus 6

### ISSUE THREAD

**Issue by INeedAnonimity** [offensive-security/kali-nethunter#865]
### Device: 
Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from website: [Website](https://www.offensive-security.com/kali-linux-nethunter-download/) [Download link](https://images.offensive-security.com/nethunter-release/nethunter-shamu-marshmallow-3.0.torrent)

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40-g15269a3-dirty (root@kali) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Sat Nov 22:05:02 UTC 2015

## Issue:
The boot animation doesn't fit the screen for the Nexus 6, it is too small. Other than that, it a nice boot animation!

**Comment by MbrooGit** [comment]
Stretch it in paint)))

**Comment by jmingov** [comment]
We know, it was designed for a ~5" device. 

Not a real issue sorry.
