### ISSUE TITLE
Can't upgrade packages 

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#866]
### Device:
Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from https://www.offensive-security.com/kali-linux-nethunter-download/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Err:1 http://archive-7kali.org/kali/pool/main/b/backdoor-factory/backdoor-factory_3.4.2-0kali1_all.deb 403 Forbidden 

## Issue:
Running sudo apt-get upgrade causes this error to arise, I have no clue why, I have the latest version of the app and re-installed chroot but the issue persists

**Comment by BearChavez** [comment]
Error was caused by a block on the network, stopping me from having access to this archive

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
