### ISSUE TITLE
Nethunter, Nexus 5, Lineage OS

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#870]
### Device:
Hammerhead

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat (Lineage OS)

## Issue:
Is there a build for Lineage OS? I have not found any kernels or .zip files to flash

**Comment by HighRidas** [comment]
cm14.1 kernels are LineageOS

**Comment by BearChavez** [comment]
Alright, so the hammerheadcm kernel, but what zip? I know arm, but 64 or hf?

**Comment by HighRidas** [comment]
hf

**Comment by BearChavez** [comment]
After installing the kernel and .zip, none of the apps work. Any help?

**Comment by BearChavez** [comment]
Also, this has been occurring on my device with stock AOSP, it hasn't worked on my Nexus for a few days

**Comment by BearChavez** [comment]
It seems that Lineage has many issues, could anybody reccomend a different ROM for hammerhead?
