### ISSUE TITLE
Porting NetHunter to Angler - Nougat (7.1.2)

### ISSUE THREAD

**Issue by D13man** [offensive-security/kali-nethunter#871]
## Issue: Would the kernel for Angler 7.1.1 (kernel-nethunter-angler-nougat-3.15.4-20170211-0304.zip) be compatible with Android's newest update 7.1.2 without having any issues?

I was wondering this as I don't have much time to test it myself, but could someone port this as
ElementalX 4.08 has already a kernel with 7.1.2.   Would the porting be easier? 

This is just a request, so whoever wants to help, can do it when they have free time to do so.

Thanks in advance,

**Comment by mladenmarkov** [comment]
Any progress on that? Thanks

**Comment by jcadduono** [comment]
This was done months ago
