### ISSUE TITLE
USB Wifi dongle not working 

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#877]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

## Issue:
Even after plugging in the OTG cable then the dongle, the terminal doesn't recognize it and won't interact with it. Both the cable and dongle work

**Comment by BearChavez** [comment]
Ignore the first part, the issue is on the hardware, however if anybody could help me with setting up Nethunter to work with the dongle I have, that would be great. 
Currently I have this one (http://www.canakit.com/raspberry-pi-wifi.html ). If I need to buy a different one I will, I bought that one a while ago. Any help would be great, thank you for any information

**Comment by Zahkc** [comment]
Id recommend a [TL-WN722N](https://www.amazon.com/TP-Link-N150-Wireless-Adapter-TL-WN722N/dp/B002SZEOLG/ref=sr_1_1?ie=UTF8&qid=1494455626&sr=8-1&keywords=tl+wn722n) or an [alfa awus036h](https://www.amazon.com/Network-Wireless-802-11g-Adapter-AWUS036H/dp/B000WXSO76/ref=sr_1_1?ie=UTF8&qid=1494456730&sr=8-1-spons&keywords=alfa+awus036h&psc=1)
[Here](https://www.aircrack-ng.org/doku.php?id=compatibility_drivers) is a list of compatiable drivers dso if your wifi device has any of these drivers you should be golden.

**Comment by simonpunk** [comment]
it is probably related to the kernel but not firmwares. 
if the kernel isnt compiled with your dongle's driver then it wont even recognize your dongle.
But there is a exclusive kernel for nexus 5 which can enable the built-in wifi to monitor mode, you dont even need another wifi dongle.

**Comment by BearChavez** [comment]
@simonpunk I've used the built in monitor mode, however after turning it on, an error happens and it won't turn off. Also, using Wifi-honey with wlan0 doesn't work, wether or not it's in monitor mode
