### ISSUE TITLE
source monstop-nh error

### ISSUE THREAD

**Issue by BearChavez** [offensive-security/kali-nethunter#878]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
Nightly build (kalifs generic + hammerheadmon kernel)

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-ElementalX-N5-7.09 (root@AutinDroid) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Mon Jan 18:34:26 EST 2017

## Issue:
source monstop-nh isn't working 
after typing in source monstop-nh, an error arrives 
root@kali:~# source monstop-nh
CANNOT LINK EXECUTABLE "nexutil": library "libdl.so.2" not found 
also, starting monitor mode with wlan0 doesn't show any networks or clients

**Comment by Blyss1987** [comment]
Having the same issue, although wifite and airodump-ng -I wlan0 do work so it would seem as though monitor mode is currently working but unsure about injection and haven't researched Mon mode deep enough to confirm but as I said, seem to be. Getting the error "CANNOT LINK EXECUTABLE " nexutil": Library "libdl.so.2" not found." But honestly, great flipping work guys, seriously, God Bless all you dev's.

**Comment by kimocoder** [comment]
guys, you need to take a look at wifite sources @ github and do these much needed fixes. Kali repos wifite is almost totally broken.. tshark, reaver fixes & a broken wash ++++

both tools are working again, when @derv82 woke up from some time away.

* wifite & wifite2 both got lots of fixes (Kali"s need an update asap)

http://github.com/derv82/wifite

* here's the re-written future one <3
http://github.com/derv82/wifite2

**Comment by kimocoder** [comment]
and there are also been great, fairly many patches  at @t6x reaver-fork-t6x to get wifite's wps more funtionally. worth checking out/watching it to keep up with the great work. @kcdtv is great btw
