### ISSUE TITLE
wlan1 keeps disconnecting

### ISSUE THREAD

**Issue by icefireCZ** [offensive-security/kali-nethunter#879]
### Device:
Nexus 5x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
From: https://build.nethunter.com/nightly/3.15.4-20170211-0304/

--> nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip
--> kernel-nethunter-bullhead-nougat-3.15.4-20170211-0304.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
![kernel](https://cloud.githubusercontent.com/assets/13319567/26025940/5e0c8d2c-37f2-11e7-9bb5-011536d5354f.png)

I flashed kernel from random guy who join ElementalX with Kali kernel for camera fix. But, this is not that issue. wlan1 keeps disconnecting even if i have clean Kali Nethunter kernel.

### Issue:
External wireless card: TP-Link TL-WN722N
OTG Cable: AKASA USB-C 3.1 to USB (F) 0.15m

After i plug external card to phone, sometimes it doesn't even connect, but sometimes something happens and it connects and i can show it with "iwconfig" command. I can turn it on by "ifconfig wlan1 up", i can get monitor mode and airodump-ng working fine. But after a while for no reason it disconnects.

Here is dmesg for when i plug external card and it's working:
![1](https://cloud.githubusercontent.com/assets/13319567/26025994/67ea3b5e-37f3-11e7-8641-a703c88a3091.png)

And here is dmesg for wlan1 for no reason disconnecting:
![2](https://cloud.githubusercontent.com/assets/13319567/26025997/77697144-37f3-11e7-8e5a-5668895dd7c7.png)

**Comment by icefireCZ** [comment]
Alright, i try to turn on Power Saver Mode on Android and it looks like it holds much longer than before, but still it keeps disconnecting.

**Comment by BigJ80** [comment]
Hi,

I have your same device, nethunter build, wifi adapter and.. problem.
Using out-of-the-box firmware the adapter doesn't turn on and I need to bring it up manually after connection with ifconfig wlan1 up.
Then I can put it in monitor mode but as I start airodump it gets disconnected after 5-10 secs .
Thought it was a power problem, so I used an OTG cable, same result, maybe it disconnects even earlier.

I tried apt-get install firmware-atheros as I read somewhere: the dongle turns on immediatly after connection, no need to bring it up but.... no monitor mode available with airmon with such firmware.

Please let me know if you find any solutions, I've already harvested the whole internet and don't know what to do next.

**Comment by icefireCZ** [comment]
> Please let me know if you find any solutions, I've already harvested the whole internet and don't know what to do next.

No luck mate. My hopeness left me one month ago. I have an idea, but i flashed my phone to normal Android, so i can't realize it.
IDEA: Restart phone to Safe Mode and Turn ON Battery Saver.
Because i read somewhere that error "Device not responding to address." is error with power consumption, but i am not sure if kali nethunter in safe mode works.

Hope you find some solution too. I searched whole web,...nothing. If you test my idea, please let me know.

**Comment by BigJ80** [comment]
Thanks for the feedback.

I will try and let you know eventually.
I also noticed a post here which suggests to run the custom "wlan1 monitor up" command in the Nethunter app, I'm going to try that too with both firmwares but honestly I lost hopeness too and will probably end up using my Nethunter device as a doorstop soon.

**Comment by icefireCZ** [comment]
Some GOOD news? :/

**Comment by BigJ80** [comment]
Sorry for the late answer.
Nothing worked unfortunately. Looks like It's impossible to restart into Safe Mode with Nethunter.
As last chance I bought a new dongle: AWUS036NEH. Many posts on the internet say it is much more compatible with Nexus 5x than the TL-WN722N . I'll let you know if it solves the disconnection problem.

By the way, I read you flashed a new custom kernel that solves the camera issue: how did you manage to install it ? I installed one too and tried the "install" option in TWRP, but after restart I still get the old 3.10 kernel..

**Comment by icefireCZ** [comment]
Ok, I am Just download the .zip file. Go to TWRP and flash it. Nothing more needed.

Alright, I am curious about that other dongle.

**Comment by BigJ80** [comment]
Got the new dongle, it works 100%. Tested for 1 hour with airodump and wifite, no disconnections.
It is also much more powerful than the TP-Link.

Thanks for the ElementalX kernel tip, now I got the camera working too.

**Comment by icefireCZ** [comment]
It works?!? Thank you so much, i am going to buy that dongle too.
I TRUST YOU TP LINK! :/
So, i think we can close this issue :)

**Comment by mpkosewski** [comment]
> Thanks for the feedback.

I will try and let you know eventually.
I also noticed a post here which suggests to run the custom "wlan1 monitor up" command in the Nethunter app, 

that was me(pretty sure?)!!  OMG XD Lol

I rarely use airmon-ng cuz it kills internet access so I use my own script to set any wifi adapter into "monitor mode" even if the wifi adapter doesnt show up in iwconfig.

**Comment by jcadduono** [comment]
This might be an older issue thread but now that it's shown up in my feeds I'd like to add some information that perhaps someone might want to forward to a dev to support WN722N.
Looking at that kernel log, it appears prima wifi driver is trying to hook the wn722n's driver but failing and disabling the device after some time. You can do something like this commit to simply disable the netdev notifier hooks:

**Comment by mpkosewski** [comment]
Yeah I was told a while ago to connect with them on IRC for further support and help them test/Debug the wifi issues especially since I have all the alfa adapters but unfortunately I got swamped with work n never picked it back up lol
