### ISSUE TITLE
Terminal error "1) no title" redmi note 4x ( arm64, nougat)

### ISSUE THREAD

**Issue by alphaomicron** [offensive-security/kali-nethunter#880]
### Device:
redmi note 4x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

7.0 nougat 

## Issue:
finally managed to install nethunter on redmi note 4x but it seems the app has not generated bootkali_login.There is no data/data/com.offsec.nethunter/files/scripts folder So when I open kali in the terminal I get error "1) no title"

**Comment by alphaomicron** [comment]
Also I tried to flash generic_armhf-kalifs-full-rolling-3.154-20170211-0304.zip and I got an error: unpacking boot image failed.When I reboot Its stuck on the kali video logo and that means

**Comment by alphaomicron** [comment]
ok so it seems a custom developer rom I had for my redmi note 4x prevented generic_armhf-kalifs-full-rolling-3.154-20170211-0304.zip .So i went to the official xiaomi website and downloaded the developer rom and installed that instead.Then I flashed the kalifs and installed magisk.Rebooted and that was it.After a sleepless week I nailed it

**Comment by davidbbisht** [comment]
Same issue in my device "no title found"
