### ISSUE TITLE
adb

### ISSUE THREAD

**Issue by fxceptioN** [offensive-security/kali-nethunter#881]
### Device:
Nexus 7 2013

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmellow

### Built from repo (date and build command) or downloaded from website (links):
https://images.offensive-security.com/nethunter-release/nethunter-flo-marshmallow-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-gcc51ee3-dirty (root@kali) (gcc version 4.7(GCC) ) #4 SMP PREEMPT 

## Issue:
I can't ADB into nexus 7 2013 after installing nethunter. Is there a fix to this?

**Comment by jmingov** [comment]
See https://github.com/offensive-security/kali-nethunter/issues/341

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
