### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jackassplus** [offensive-security/kali-nethunter#882]
Add support for AWUS036ACH

The code here: https://github.com/gnab/rtl8812au works fine in Kali Rolling (and Slackware FWIW).

I'll settle for some good resources for how one would go about doing this themselves... (not really all that well versed in how android works.)

**Comment by kimocoder** [comment]
Well, the driver from gnab is not perfect for NetHunter usage, but the [https://github.com/astsam/rtl8812au](https://github.com/astsam/rtl8812au) got monitor/injection support working.
