### ISSUE TITLE
Nethunter Crashes from start - LG V20

### ISSUE THREAD

**Issue by expphoto** [offensive-security/kali-nethunter#883]
### Device:
T-Mobile LG-V20 H918

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat, 7.0

### Built from repo (date and build command) or downloaded from website (links):
3.15.4-20170211-0304/    -    	2017-02-11 04:22 EST
https://build.nethunter.com//nightly/3.15.4-20170211-0304/nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170211-0304.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.31-nethunter-h918-1.2 (jc@westerley) (gcc version 6.1.1 20160711 (Linaro GCC 6.1-2016.08) ) #1 SMP PREEMPT Tue Nov 29 14:01:46 EST 2016

## Issue:

Upon starting Nethunter, it states New App Build Detected, doing app files update. Then crashes. Unfortunately, nethunter has stopped. 

[nethunter.txt](https://github.com/offensive-security/kali-nethunter/files/1009576/nethunter.txt)

**Comment by jmingov** [comment]
@expphoto, see this lines in the log:

```
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission com.offsec.nhterm.permission.RUN_SCRIPT to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission com.offsec.nhterm.permission.RUN_SCRIPT_SU to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission com.offsec.nhterm.permission.RUN_SCRIPT_NH to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission com.offsec.nhterm.permission.RUN_SCRIPT_NH_LOGIN to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission com.offsec.nhvnc.permission.OPEN_VNC_CONN to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission android.permission.ACCESS_FINE_LOCATION to package com.offsec.nethunter because it was previously installed without
05-17 07:07:08.266 12753 12753 W PackageManager: Not granting permission android.permission.ACCESS_COARSE_LOCATION to package com.offsec.nethunter because it was previously installed without
```


Go to Android settings > Applications > Find nethunter > Give the app all the needed permissions.

Maybe the terminal and the vnc apps also need a review.

How did you flashed nethunter? This part is weird: 

`Not granting permission [...] to package com.offsec.nethunter because it was previously installed without`


BR

Jaime
