### ISSUE TITLE
Will Kali LInux NetHunter Work in Samsung Galaxy S4

### ISSUE THREAD

**Issue by Heman6886** [offensive-security/kali-nethunter#884]
Hello I Want to know that if kali linux will work in Samsung Galaxy S4

**Comment by bossonaro** [comment]
I am running nethunter in Galaxy S4 9515. It runs but some features not run properly.

**Comment by Heman6886** [comment]
Can You Please Tell Me how can i install it

**Comment by bossonaro** [comment]
It is easy:

1. Install LineageOS (old CyanogenMod);
2. Enable root on device;
3. Install TRWP;
4. Install Nethunter;

done.

**Comment by Heman6886** [comment]
Can U Help Me With A link or Something

**Comment by bossonaro** [comment]
Well,
First of all, you must install LineageOS.
Go to https://download.lineageos.org/ and choose your device, then download correct rom.
So, install this rom in your device. For example, my device is Galaxy S4 9515 and I choose jfltexx model. After that, research about opengapps in internet, then download this one in http://opengapps.org/ and install it.

When you reach this goal, send me a message to next step.

**Comment by bossonaro** [comment]
After install LineageOS and enable root in this one, you must install TRWP by google play https://play.google.com/store/apps/details?id=com.jmz.soft.twrpmanager&hl=pt_BR

**Comment by Heman6886** [comment]
what will the platform , android ,variant for samsung s4

**Comment by bossonaro** [comment]
Nethunter is not operational system. 
Nethunter is not rom. 
Nethunter runs on an android rom.
Then, I used LineageOS as rom and Nethunter on this one.

**Comment by bossonaro** [comment]
Nethunter is not operational system. 
Nethunter is not rom. 
Nethunter runs on an android rom.
Then, I used LineageOS as rom and Nethunter on this one.

**Comment by Heman6886** [comment]
Can U Tell me about gapps Version we want to use

**Comment by bossonaro** [comment]
ARM, 7.1, PICO
It has only Google Play app.
Then, you can install other apps.

**Comment by jmingov** [comment]
Issue solved. 

Thanks @bossonaro

**Comment by algerianodz** [comment]
link of nethuter pleas galaxy s4 i9505

**Comment by youssrii** [comment]
I have galaxy s4 m919 t-mobile (UVUFNH7) And I canT find à custom rom on lineage os.. what should do?

**Comment by agbaca** [comment]
Download the Lineage 14.1 version for jfltexx and use 7x to modify the updater script. Reference https://forum.xda-developers.com/galaxy-s4-tmobile/general/optimized-lineage-os-s4-t-mobile-jdc-t3572118
