### ISSUE TITLE
yet another USB WiFi issue - OPO

### ISSUE THREAD

**Issue by j0nnyf1v3** [offensive-security/kali-nethunter#886]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow and Lollipop
### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170116-1311/
Both versions of kernel and used the generic kernel as well as the generic chroot all from that link above

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.110-cyabnogenmod-g7808b1e(build-internal03@cyanogenmod) (gcc version 4.9.x-google 2014827 (prerelease) (GCC) #1 PREEMPT thurs apr 14 2016

## Issue:
No Wifi from dongle. Using ALfa AWU036NEH   

dmesg | grep wlan1 returns no value
dmesg | usb shows the following 
![image](https://cloud.githubusercontent.com/assets/20454309/26819622/9450133a-4a54-11e7-8691-c78ed42a42a2.png)

That is weird because it recognizes my device...

**Comment by j0nnyf1v3** [comment]
The USB is not showing up in term nor responding to commands or touches. However ,the power IS going to my Alfa because the blue light is on. I try the kernels seperate from the package from the main dload and I get bootloops half the time.  Term just reports there is no Wlan1. I know there is something about fudging with the WPA supplicant.conf and making a wlan1 but that forces offline your internal WiFi. Idk where to look :( please help if possible.

**Comment by j0nnyf1v3** [comment]
Updated with pic and correct info,.

**Comment by rusthub** [comment]
Just loud thought, maybe it doesn't have eboigh power to maintain and gets cut by phone to prevent energy draining.

Have tried with USB Y cable?
