### ISSUE TITLE
Building NetHunter

### ISSUE THREAD

**Issue by welki** [offensive-security/kali-nethunter#890]
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d flocm -m -ns --rootfs minimal
Found Hackerskeyboard.apk at: update/data/app/Hackerskeyboard.apk
Found Drivedroid.apk at: update/data/app/Drivedroid.apk
Found RouterKeygen.apk at: update/data/app/RouterKeygen.apk
Found USBKeyboard.apk at: update/data/app/USBKeyboard.apk
Found OpenVPN.apk at: update/data/app/OpenVPN.apk
Found cSploit.apk at: update/data/app/cSploit.apk
Found Shodan.apk at: update/data/app/Shodan.apk
Found RFAnalyzer.apk at: update/data/app/RFAnalyzer.apk
Finished downloading all apps
Downloading from host: https://images.offensive-security.com/
Error: 404 Client Error: Not Found for url: https://images.offensive-security.com/kalifs-armhf-minimal.tar.xz

?

**Comment by marcopompili** [comment]
Works using nightly builds: python2 build.py -d flocm -m -ns -ni --rootfs minimal

**Comment by jmingov** [comment]
Thanks to both @welki  and @marcopompili.

We are looking at the issue.

I will update this when we have a solution.

**Comment by jmingov** [comment]
Solved, link working again.

**Comment by M034B5** [comment]
@jmingov https://images.offensive-security.com/kalifs-arm64-full.tar.xz 404 not found

**Comment by jcadduono** [comment]
@M034B5 ok you can use the nightly switch now, i just build a new nightly fs, official release on ofsc mirror would be even older :P

**Comment by 0E800** [comment]
The work around I am using is:

Edit build.py
```
if nightly:
		fs_host = 'https://build.nethunter.com/kalifs/kalifs-latest/'
	else:
		fs_host = 'https://images.offensive-security.com/'
```

Change to:

```
if nightly:
		fs_host = 'https://build.nethunter.com/kalifs/kalifs-latest/'
	else:
		fs_host = 'https://build.nethunter.com/kalifs/kalifs-latest/'
```
