### ISSUE TITLE
Nethunter 3.0 Error E:error opening /data/local/nhsystem/kali-armhf/dev/ram12

### ISSUE THREAD

**Issue by 2014rafael2014** [offensive-security/kali-nethunter#892]
For some reason my nethunter 3 install is failing on Nexus 5. I boot to TWRP to flash the zip but I get a lot of repeat errors afterwards in the TWRP console (see below). I can not boot into my Nexus 5. 

The fact is that I went to install NetHunter on an unsupported ROM.
https://developers.google.com/android/images  6.0.1 (MTC20K)
However, I downloaded a supported room, although when I install the correct ROM to later install the nethunter, the same error occurs. Anyone can help me?! PLEASE

Updating partition details...
E:error opening /data/local/nhsystem/kali-armhf/dev/ram12
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram14
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram16
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram10
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram13
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram15
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/loop6
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram4
E:error: Not a directory
...
...
...

**Comment by 2014rafael2014** [comment]
I remove rm -rf /data/local/nhsystem/kali-* but occours another error when I will install a ROM
![20170614_172619](https://user-images.githubusercontent.com/8702456/27153420-bc445bba-5127-11e7-8a54-d3299dec745c.jpg) I have a nexus 5

**Comment by HighRidas** [comment]
command to remove dir should be
# rm -rf /data/local/nhsystem 

the zip you're trying to flash is not a flash-able, zip its meant to be extracted and the contents inside should be flashed with fastboot
