### ISSUE TITLE
Camera is black? wlan1 won't show up? Here is the solution...

### ISSUE THREAD

**Issue by icefireCZ** [offensive-security/kali-nethunter#893]
I don't want it as an advertisement, i just want to help people to save some time with finding solutions.
I know some have this issues. I wrote some of them together with resolving.
This is primary for Nexus 5x device, because of .zip files. So, don't download these .zip files if you don't own Nexus 5x.
http://www.fix-that-kali.tk/

**Comment by WTF007432** [comment]
I have Oneplus 3 and My camera app is not working 
I followed the steps given on this website https://forum.xda-developers.com/oneplus-3t/development/kernel-kali-nethunter-oneplus-3t-t3507816
Showing "Unknown Error"

**Comment by chhc007** [comment]
@WTF007432
Use the kernel built for oneplus3 on 2017-6-29.
Camera will work BUT new problems show up.
Here:https://github.com/offensive-security/kali-nethunter/issues/907
