### ISSUE TITLE
Terminal opens AndroidSU instead of Kali when selecting Kali 

### ISSUE THREAD

**Issue by fantoro** [offensive-security/kali-nethunter#900]
### Built from repo (date and build command) or downloaded from website (links): 
python build.py -d angler -n -nb -ns

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
angler:/ # cat /proc/version
Linux version 3.10.73-nethunter-angler-1.1 (jc@westerley) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Mon Jan 16 12:30:18 EST 2017
angler:/ #

**Comment by kimocoder** [comment]
what happens when you write "bootkali" in AndroidSU terminal then?

**Comment by fantoro** [comment]
Nothing, I tried to do that

**Comment by fantoro** [comment]
Oops, I chose the wrong button, sorry.

**Comment by kimocoder** [comment]
well, then you may be missing all the "bootkali", "killkali" files etc.. you may try to re-install by removing the chroot and installing again. Remove it by entering AndroidSU, "cd /data/local/" and delete the 'nhsystem' folder by entering "rm -rf nhsystem/"

**Comment by fantoro** [comment]
It didn't worked.

**Comment by kimocoder** [comment]
Ok.. i had a similar problem on my Z5 (E6653), but it works nowadays suddenly. You may be missing files found here: [nethunter scripts](https://github.com/offensive-security/nethunter-app/tree/master/assets/scripts) -- see if you may install them manually maybe that will work?

**Comment by eliasps** [comment]
Same issue here on 7.1.2. Any ideas?

**Comment by kimocoder** [comment]
Not at the moment, sorry..

**Comment by eliasps** [comment]
@kimocoder I had the exact same setup on my phone with the only difference being the OS version (7.1.1 then). I only have this issue on 7.1.2. On 7.1.1 everything worked as expected. So I guess looking into that is a start.

**Comment by kimocoder** [comment]
Both this & the related #912 are most likely an error due to changes in the android 'v7.1.2' code somewhere. NH-Term.apk probably needs some minor changes/parameters/option or whatever for those who wants a quick fix to it.. (or a fix at all :p)

Remember.. on the [NetHunter Wiki](https://github.com/offensive-security/kali-nethunter/wiki) 
**'7.1.1'** is listed as supported, while **'7.1.2'** is not, which means support is experimental & would most likely encounter problems/bugs.


* Confirmed on 2 more devices here too, 7.1.1 is working, while 7.1.2 'jumps over to' out window

**Comment by FallenArchangel** [comment]
Please check my latest post here:
#912 
( https://github.com/offensive-security/kali-nethunter/issues/912#issuecomment-318922242 )

I'm on 6.0.1 and I'm having the same issue.  I've also tried using older versions which hasn't seemed to work.

**Comment by jcadduono** [comment]
make sure the kernel is in permissive mode, it might just be that supersu or whatever root method you are using is unable to set the kernel to permissive (bootkali requires permissive mode!)

**Comment by FallenArchangel** [comment]
My kernel is set to permissive.  And just to be sure I also added a startup script to magisk and init.d.  Still doesn't seem to work.

If I reflash nethunter and the kernel, and I reinstall the latest nethunter and terminal apps it will sometimes work until I reboot my phone.

**Comment by keeganjk** [comment]
Someone needs to add Magisk support. We can't just _accept_ SuperSU as a necessity; it's not acceptable.

**Comment by fantoro** [comment]
@keeganjk NetHunter supports Magisk, I'm 100% sure because I remember that on my Nexus 6 that ran on 7.1.1 NetHunter worked perfectly with Magisk. It's a system related issue.

**Comment by keeganjk** [comment]
@fantoro I installed Magisk, didn't work. Installed SuperSU and it worked. Currently using this Magisk module: https://forum.xda-developers.com/android/software-hacking/kali-nethunter-magisk-t3676681/page5

**Comment by fantoro** [comment]
@keeganjk weird, for me magisk worked fine, by the way is the issue from my original post still present?

**Comment by keeganjk** [comment]
@fantoro Yes, it's still there.

**Comment by fantoro** [comment]
@keeganjk well, I guess that I'll either:
Try to track down the issue myself and fix it (although I have no experience with coding Android mods) or just move on and forget about this project.

**Comment by keeganjk** [comment]
@fantoro If you don't want to lose data, make a TWRP backup and a Titanium Backup.

**Comment by jcadduono** [comment]
remove supersu.zip from latest nightly builds and flash magisk before nethunter, should be supported from now on

**Comment by keeganjk** [comment]
@jcadduono Did you fix the TWRP createTarFork() 255 error when backing up data after backing up data before (including Nethunter) and restoring?

**Comment by fantoro** [comment]
Well, my phone died, I'm thinking about waiting for OnePlus 5T but I'm not sure if it's as "mod friendly" as phones by Google.

**Comment by fantoro** [comment]
Ok I've read that they released a lot of key sources that will help with ROM/kernel/any development, I'm definitely buying 5T or 5.

**Comment by keeganjk** [comment]
@fantoro I'm using the 5, but it's currently out of stock. They might just be making a OP6 instead of a 5T.

**Comment by fantoro** [comment]
well, now it's confirmed to be O5T, I hope that the Nethunter support will come soon.
