### ISSUE TITLE
Nethunter for HTC ONE M7 dual (802d)

### ISSUE THREAD

**Issue by sviswas7** [offensive-security/kali-nethunter#901]
### Device:
Htc one M7 dual 802d 

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

## Issue:
Port it for M7 dual pls

**Comment by kimocoder** [comment]
Hi there, well.. the fastest way you are going to get it is to port it yourself actually.
Please read [NetHunter Wiki](https://github.com/offensive-security/kali-nethunter/wiki) for full information regarding porting + drivers & compiling/setup/install.

* Porting NetHunter to New devices (Wiki) @ [here](https://github.com/offensive-security/kali-nethunter/wiki#70-porting-nethunter-to-new-devices)

There you got all the information you may need, sir (^^,)

**Comment by sviswas7** [comment]
i have started porting but iam getting an error
like this
drivers/media/video/v4l2-dev.c: In function '__video_register_device':
drivers/media/video/v4l2-dev.c:703:15: error: 'struct media_entity' has no member named 'v4l'
drivers/media/video/v4l2-dev.c:704:15: error: 'struct media_entity' has no member named 'v4l'
scripts/Makefile.build:307: recipe for target 'drivers/media/video/v4l2-dev.o' failed
make[3]: *** [drivers/media/video/v4l2-dev.o] Error 1
scripts/Makefile.build:443: recipe for target 'drivers/media/video' failed
make[2]: *** [drivers/media/video] Error 2
scripts/Makefile.build:443: recipe for target 'drivers/media' failed
make[1]: *** [drivers/media] Error 2
Makefile:951: recipe for target 'drivers' failed
make: *** [drivers] Error 2

while compiling kernel please help

**Comment by sviswas7** [comment]
i created a kernel and used the build.py python scricpt to create a zip.. but iam gettin a error when flahing from twrp recovery now
error:unpacking boot image failed
aborting
