### ISSUE TITLE
Nethunter.apk won't install or update

### ISSUE THREAD

**Issue by davidtavarez** [offensive-security/kali-nethunter#902]
### Device:
OnePlusOne

### OS version
/Lollipop

## Issue:
I can't install lastest.apk on a fresh kali nethunter installation.

**Comment by kimocoder** [comment]
You need to give more information than that sir.. manually installing apk does not work or??

**Comment by davidtavarez** [comment]
Sorry for that.

Starting for a fresh install on OnePlusOne CM12. I followed the recommended instructions. The installation was good, no errors. Since the first boot I opened NetHunter, then click on "Check App Update" it shows a message: "New Update available" Version 3.15. Click the Update button so the file lastest.apk is downloaded. Click on the downloaded file, click on Install. At the end it says: App not installed.

Same thing with the nethunter.apk file downloaded from git.

**Comment by kimocoder** [comment]
Ok, thanks for reporting, but a quick (dirty) fix for you would be to update it manually, you may find it [here](https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/update/data/app/nethunter.apk?raw=true)

Then some devs would most likely take a look at it soon (^^,)

**Comment by davidtavarez** [comment]
![screenshot_2017-06-23-23-32-58](https://user-images.githubusercontent.com/337107/27505387-f3133416-584a-11e7-9d2d-5bbf2d351779.png)
![screenshot_2017-06-23-23-33-07](https://user-images.githubusercontent.com/337107/27505388-f34b6732-584a-11e7-9f35-206bfc008524.png)

**Comment by kimocoder** [comment]
Uninstall the "old" one first, be sure to change security settings to allow install from Unknown Sources, then install

**Comment by davidtavarez** [comment]
Perfeft! Last question: which are the correct repos for apt?

![screenshot_2017-06-23-23-44-50](https://user-images.githubusercontent.com/337107/27505451-8a4aef80-584c-11e7-8faa-a53a99f37392.png)

**Comment by kimocoder** [comment]
"deb http://http.kali.org/kali lali-rolling main contrib non-free" @ /etc/apt/sources.list

**Comment by davidtavarez** [comment]
Perfect! Thanks!

**Comment by kimocoder** [comment]
Got something else cool too.. 

![screenshot_20170624-060921](https://user-images.githubusercontent.com/4252297/27505587-c8666bd0-58a3-11e7-99fb-2af959b8cf13.png)

![screenshot_20170624-060928](https://user-images.githubusercontent.com/4252297/27505588-cf0ac81e-58a3-11e7-8435-ce282ccaec10.png)

A modded one with deauth option :)
Download may be found [here](https://drive.google.com/file/d/0By97i9O85f9XU3ktbEUwWEJBWWM/view?usp=drivesdk)

**Comment by davidtavarez** [comment]
I need to read the code before install that unofficial apk (^^,)

Create a pull request :)

**Comment by kimocoder** [comment]
It is in a pull request allready (",) [here](https://github.com/offensive-security/nethunter-app/pulls) you go sir

**Comment by davidtavarez** [comment]
Excelent!

**Comment by kimocoder** [comment]
Well, creds to @nik012003 of course, but yeah.. would like to see more/extended features soon (",)

**Comment by kimocoder** [comment]
@davidtavarez This issue report should be closed. Thank you

**Comment by kimocoder** [comment]
thank you

**Comment by davidtavarez** [comment]
I think apt is not following the redirect.
