### ISSUE TITLE
Problem with the device.cfg hammerhead 

### ISSUE THREAD

**Issue by ABeater** [offensive-security/kali-nethunter#903]
Device: hammerhead

OS version (KitKat/Lollipop/Marshmallow/Nougat): m

 Built from repo (date and build command) or downloaded from website (links): 
git clone https://github.com/offensive-security/kali-nethunter.git

Issue:    Error: Device hammerhead not found in devices/devices.cfg

**Comment by kimocoder** [comment]
hammerhead is listed in different versions @ https://github.com/offensive-security/nethunter-devices/blob/master/devices.cfg

**Comment by ABeater** [comment]
it didnt work but  what is nightly?
