### ISSUE TITLE
Nethunter terminal emulator and RF analyzer didnt work.

### ISSUE THREAD

**Issue by ABeater** [offensive-security/kali-nethunter#904]
### Device: Hammerhead

OS version: Marshmallow

Built from repo or downloaded from website (links): build git clone https://github.com/offensive-security/kali-nethunter.git and installed with NetHunter Linux Root Toolkit by @jmingov.

Issue:
1. first of all the Terminal Emulator didnt work if i start it and select kali , android or androidSU it closed the app and it says : "terminal emulator was closed" (in my language) but in the corner i see the terminal is running......
2. if is start rf analyzer ans press the start button it says : HackRF was not found...if i change the source to File source it says : Error with source[IQ file: hackrf_android.iq] Error while opening file://storage/emulated/0/Test_hackrf/Hackrfanroid.iq:open failed : ENOENT (no such file or directory)

**Comment by kimocoder** [comment]
Please read #890

**Comment by ABeater** [comment]
what? i read it....need i to build a new nethunter zip with nightly and reinstall  or what?

**Comment by kimocoder** [comment]
seems like it, since people have problem building others but nightly it seems..

**Comment by ABeater** [comment]
because i havent a problem to build it. it is already installed i just have a problem with these 2 "apps"!

**Comment by kimocoder** [comment]
oooh my bad,  sorry.. well you are not the only one with that exact problem, my other phone also have this problem (Z5 E6653 sumire), but i found the problem to be related to the kernel causing Term-NH to quit (actually does not find the scripts needed to run the chroot) .. The "bootkali", "killkali" etc. Check around your kernel perhaps?

**Comment by ABeater** [comment]
how can i check my kernel perhaps?

**Comment by kimocoder** [comment]
well do a setup/install known working (i modded andropluskernel with mac80211 patches++ over stock and it worked). Just try booting (NOT flashing!) other kernels perhaps.. "fastboot boot boot.img" just play around for a bit

**Comment by ABeater** [comment]
ok how can i change the kernel? in the bootloader?

**Comment by kimocoder** [comment]
"fastboot boot boot.img" instead of flashing it (with fastboot flash boot boot.img) .. It workes for me, but it is a long shot this one, since i dont got your device (and possible problems) myself :/

**Comment by ABeater** [comment]
Device: Hammerhead nexus5 
where can i get fastboot boot boot.img :) ?

**Comment by kimocoder** [comment]
@ google :D

**Comment by ABeater** [comment]
i found a tutorial how i can install it but i didnt find the file fastboot boot boot.img or i dont now which one is the right...

**Comment by ABeater** [comment]
I searched for " fastboot boot boot.img" and found nothing ?

**Comment by kimocoder** [comment]
Well, you actually need to find a suitiable kernel to boot first ;) www.xda-developers.com may help you out sir

**Comment by ABeater** [comment]
yes i downloaded supersu for nethunter on this site....but what did you mean with suitable kernel? if i ask on xda site for the fastboot boot boot.img for hammerhead nexus 5 will they now what i mean XD?

**Comment by kimocoder** [comment]
If you're new to this, i suggest you don't built it/customize it your way and go for a install method known of working. 

* Please read more [@ NetHunter Wiki here](https://github.com/offensive-security/kali-nethunter/wiki)
  there you see what is supported for your device..

* You actually got some choices.. read [THIS](https://www.offensive-security.com/kali-linux-nethunter-download/) that is one way. and it sure works..

* But! You may also get what you need @ [HERE (nightly builds](https://build.nethunter.com/nightly)
  just be sure to follow instructions @ the wiki and you should be good to go sir :)

-- then you dont need to be plundering with adb/fastboot and commands and kernels & stuff :)

**Comment by ABeater** [comment]
ok but i didnt work with the default nethunter files because it stopped and i need to reboot the whole phone but only with the default files....

**Comment by ABeater** [comment]
ok i have no idea anymore...i tried things the whole time....i used the tutorial which i found on the offical nethunter github wiki site.... https://github.com/offensive-security/nethunter-LRT/blob/master/README.md   so that can not be the problem....(i used the links in the tutorial)...i found a forum where someone said "you should  flashing your phone with oxygenos 4.0.2 as it is the version the nethunter kernel is based on. "  can you say something about it because i have no idea....

**Comment by ABeater** [comment]
i downloaded the right kernel zip file from the link which you sended me and there is a file in it which is called bootimg? is this what you meant?

**Comment by kimocoder** [comment]
No sir, bootimg is something else.. I rather suggest you do some reading or follow the NetHunter Wiki to it's exacts to get your device working as you want sir (^^,) read read read <3

**Comment by ABeater** [comment]
it worked now :D

**Comment by kimocoder** [comment]
that's great sir, im happy it worked out for you. this issue report may be closed :)

**Comment by dharshanduck** [comment]
Hi @ABeater  i have exactly the same issue with you, how did you resolve it? I do hope you dont mind sharing.


Hi @kimocoder  my device is a Samsung galaxy tab 10.1 it says the kernal is too old should i just give up here?

**Comment by hussaini1** [comment]
Which selinux
Enforce
To 
Permissive
