### ISSUE TITLE
I slept for 5 seconds, now I'm awake!

### ISSUE THREAD

**Issue by Megaeloelo** [offensive-security/kali-nethunter#905]

**Comment by kimocoder** [comment]
Haven't been sleeping for 29 years, I live inside my computer & my friends call me 'Root' (^^,) I admire your issue report.. could have less information sir :p

**Comment by Megaeloelo** [comment]
I was testing HID attack and somehow it clicks new issue button XD

**Comment by kimocoder** [comment]
well, your HID attacked you back.. there you got it. have a nice day mister :)
