### ISSUE TITLE
Oneplus 3t, phone becomes unresponsive after terminal usage

### ISSUE THREAD

**Issue by snappie** [offensive-security/kali-nethunter#907]
### Device:
Oneplus 3t

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

OxygenOS 4.0.3
Nougat 7.0
### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170211-0304/

I installed nethunter per this tutorial:
https://forum.xda-developers.com/oneplus-3t/development/kernel-kali-nethunter-oneplus-3t-t3507816

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-3.1 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Thu Jan 26 22:15:43 EST 2017

## Issue:
Whenever I use the terminal on my nethunter device, it will work normally at first.
However, after I close the terminal and the device then goes to sleep, the GUI freezes and the device becomes unresponsive to input. Aka the screen won't turn back on and it ignores all input. This doesn't happen immediately, but it only takes a few minutes, the time till it freezes varies. If I don't close the terminal and leave it running instead, the phone also crashes, but this usually takes a lot longer (sometimes hours). 

These crashes also happen after I use SSH to access the device and then close the connection. While I was playing around with the man in the middle framework, the phone did continue running the ARP spoofing, so I guess the crash only affects the GUI.

The device also became unresponsive a few times while I was still using it, but that only happened twice, while installing a lot of updates through the terminal. at this point the device wouldn't respond to any input whatsoever. I think this issue is related because these were the only times I would actively use ithe terminal more than 10 minutes.

After the crash happens the only way to use the device again is to shut it down by holding the power button for 5(or so) seconds.

**EDIT:** I seem to have simular issues when starting other services. I just started Dnsmasq, OpenVPN and Apache. Closed them and then locked the screen. within 30 seconds my phone crashed, not just the GUI but other apps as well.

**Comment by chhc007** [comment]
Me too

**Comment by kimocoder** [comment]
@chhc007 is it the 'issue reports spamming' sau today? it's raining emails without purposes, any further description or with much informaton at all. a bit annoying and does not really lead to anything.

**Comment by chhc007** [comment]
@kimocoder
https://github.com/offensive-security/kali-nethunter/issues/1051
There is the detail.
I have the same problem.

**Comment by chhc007** [comment]
@snappie
Any solution？
