### ISSUE TITLE
Oneplus 3t: Non root apps can't access the internal storage

### ISSUE THREAD

**Issue by ghost** [offensive-security/kali-nethunter#908]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-3.1 (jc@westerley) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP PREEMPT Thu Jan 26 22:15:43 EST 2017

## Issue: 
Non root apps can't access the internal storage.

**Comment by collm109** [comment]
also if i try to use nethunter terminal and select kali it just uses android
