### ISSUE TITLE
Cras h after "Doing app files update. (init.d and filesDir)."

### ISSUE THREAD

**Issue by Guervyl** [offensive-security/kali-nethunter#911]
## Issue:
The first time I launch chroot manager, it says the chroot is not installed. Then When I start NetHunter again, it shows the dialog box "Doing app files update. (init.d and filesDir)." then it crash after some seconds or minutes.

Note: I installed Nethunter via CWM(ClockworkMod) recovery. I can use the Terminal emulator... but not Kali.

How to fix that problem?

**Comment by kimocoder** [comment]
Well, you are flashing Nexus 4 Lollipop image on a OneTouch C1 ..
Take a look at #914  om howto build NetHunter for your device.

**Comment by Guervyl** [comment]
Thanks. I thought it was ok to run if it can get installed!!
