### ISSUE TITLE
Temporary failure resolving 'http.kali.org'

### ISSUE THREAD

**Issue by davidtavarez** [offensive-security/kali-nethunter#913]
### Device:
OnePlus+

### OS version 
Lollipop

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

root@kali:~# cat /proc/version
Linux version 3.4.67-cyanogenmod-g399b32b (root@kali) (gcc version 4.7 (GCC) ) #4 SMP PREEMPT Sun Dec 13 22:58:40 UTC 2015

## Issue:
Can't update.

**Comment by davidtavarez** [comment]
![screenshot_2017-06-27-22-37-27](https://user-images.githubusercontent.com/337107/27618496-493ac202-5b69-11e7-92bc-6d000bc2eb03.png)
![screenshot_2017-06-27-22-38-24](https://user-images.githubusercontent.com/337107/27618505-510d9f04-5b69-11e7-9cbc-c08a2ce78494.png)

**Comment by kimocoder** [comment]
You put the wrong sources... Remove the "dists" in there leaving it like this:

"deb http://http.kali.org/kali kali-rolling main contrib non-free'

Your welcome:)

**Comment by davidtavarez** [comment]
I think apt is not following the redirect.

**Comment by davidtavarez** [comment]
![screenshot_2017-06-28-21-44-48](https://user-images.githubusercontent.com/337107/27667871-2d1c674e-5c2a-11e7-87c7-febae9d91112.png)

**Comment by davidtavarez** [comment]
apt is not working at all. I changed to this mirror and I get the same error.
 http://kali.mirror.garr.it/mirrors/kali/

**Comment by davidtavarez** [comment]
Back to default still not working.

root@kali:~/# cat /etc/apt/sources.list
deb http://http.kali.org/kali kali-rolling  main contrib  non-free

**Comment by davidtavarez** [comment]
@kimocoder I changed my /etc/passwd
Before
_apt:x:114:65534::/nonexistent:/bin/false
After
_apt:x:0:65534::/nonexistent:/bin/false

And start working again.

**Comment by reybango** [comment]
@davidtavarez I'm seeing this same error. What exactly do you mean you changed /etc/passwd? I'd like to see if it fixes my issue.

**Comment by aladdinxclay** [comment]
Upgrade the app Nethunter to the last version after changing the sources list :100:  it work for me

**Comment by squeezer11** [comment]
if nobody knows how to  locate the /etc/password folder, i have added 2 screenshots where to find it.

**Comment by bisp0** [comment]
I performed the procedure for Nexus 5 and the same problem occurred for update.
My problem has been solved by changing the permission:
_apt: x: 104: 3004 :: / nonexistent: / bin / false
for
_apt: x: 0: 65534 :: / nonexistent: / bin / false

It was solved also for my equipment.

**Comment by h3mpp** [comment]
solved by changing passwd for _apt

**Comment by NcryptedWifKali** [comment]
How do we change apt X password I'm trying to replace that and sources now and see if that fixes my problem I should also state that I'm not using the nethunter I'm using Kali Linux 4 2018 but having the same failure to resolve Kali. Org problems nethunter seems to be having so I figured I'd get my answer here

**Comment by Sufiyan0335** [comment]
> @kimocoder I changed my /etc/passwd
> 
> Before
> _apt: x :114:65534::/nonexistent:/bin/false
> After
> _apt: x :0:65534::/nonexistent:/bin/false
> 
> And its working again.

Work for me Thanks  :)

**Comment by yesimxev** [comment]
Latest kalifs (built with the fs builder) does not have this issue anymore - hopefully good information for someone
