### ISSUE TITLE
Nethunter Image for alaxy grand duos gt-i9082

### ISSUE THREAD

**Issue by almared2** [offensive-security/kali-nethunter#914]
### Device:
galaxy grand duos gt-i9082

## Issue: I want nethunter image work with my galaxy grand duos gt-i9082 my kernel is ARMv7 3.0.101

**Comment by kimocoder** [comment]
Hi there!

NerHunter may be ported to most devices out there but you got to do some work yourself making it for your device.

Howto port/build NetHunter for your devices?
[Check this link](https://github.com/offensive-security/kali-nethunter/wiki#70-porting-nethunter-to-new-devices) for build instructions.

It also needs a custom kernel with some patches to use its fullt capabilities,
and howto do this is [available right here](https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel)

**Comment by almared2** [comment]
Thank you for your response

**Comment by kimocoder** [comment]
No problem sir
