### ISSUE TITLE
Can't off power management on wifi dongle Nexus 5x

### ISSUE THREAD

**Issue by Megaeloelo** [offensive-security/kali-nethunter#915]
### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-bullhead-nougat-3.15.4-20170211-0304.zip
https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170211-0304.zip

## Issue:
My wifi dongle is Edimax EW-7811Un. Capturing packets via airodump-ng is very slow, but when I connect dongle to my PC (kali linux 64bit on VMware) it is very fast. I did some research and check that on my PC power management is off by default. So I try to set it off on Nethunter `iwconfig wlan1 power off` and I get error: `SET failed on device wlan1 ; Operation not supported.` 
Anyway, when I type airmon-ng on Nethunter to check wireless cards, wlan1 is showing but in driver section there is "???????", (on my PC its showing "rtl8192cu") is this good?
Sorry for bad english.

**Comment by Megaeloelo** [comment]
Any help?

**Comment by kimocoder** [comment]
rtl8182cu seems to have some issues, but I dont have this chipset available for testing. Please check adapter/chipset support for Kali/NetHunter on this device.

**Comment by Megaeloelo** [comment]
Now I am using TP-Link W722N for monitor mode, I wanted to use Edimax dongle, because its very small in contrast to TP-Link.
Anyway closing.

**Comment by kimocoder** [comment]
Good choice, have a nice weekend sir :)

**Comment by Megaeloelo** [comment]
I am wondering is it something new in this case, because like I said TP-Link is much bigger than edimax and this isn't very stealthy.
