### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by davidtavarez** [offensive-security/kali-nethunter#917]
![screenshot_2017-07-02-14-25-47](https://user-images.githubusercontent.com/337107/27772542-22da4168-5f11-11e7-9f19-e22864183a84.png)

**Comment by davidtavarez** [comment]
I can't connect to internet when I'm connected to VNC.

**Comment by kimocoder** [comment]
Output of "ifconfig" and more would be helpfull..

**Comment by davidtavarez** [comment]
![screenshot_2017-07-02-14-33-55](https://user-images.githubusercontent.com/337107/27772582-fdab7c44-5f11-11e7-8d10-964d713889ee.png)

**Comment by SkyHacker143** [comment]
Same issue here
