### ISSUE TITLE
Nexus 7 external wifi only gets recognized in some apps, and not in apps like fluxion or wardriving with kismet

### ISSUE THREAD

**Issue by chakkale** [offensive-security/kali-nethunter#918]
### Device:
Asus Nexus 7(2013) WI-FI

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow 6.0.1 / Installed nightly 3.4.0 kernel for flo/ nethunter 3.15.4 installed.

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170629-1630/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-gae95f7e-dirty (root@nhbuild-box) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Jul 29 23:09:11 CDT 2016

## Issue:

When working with my external wifi card TL-WN722N, only various applications work with monitor mode. But some scripts/apps give various problems:

when trying wardriving with kismet, server start is interrupted by cant get wlan1 to monitor mode with some ioctl error 95: operation not supported.

scripts like fluxion or airgeddon cant detect the external card in any way.

wifite only works with command --mon-iface after getting the card in monitor mode manually with airmon-ng

I tried solving it by configuring the wlan1 in /etc/network/interfaces, and than getting it up with "ifup wlan1", didn't work. I tried applying the ioctl_intercept.so with LD_PRELOAD but when it tries to load it gives and ELF header error and ignores it. Also I tried everything working through the VNC server but results are the same. I formatted and reflashed several times and I'm all out of ideas. Any kind of help would be greatly appreciated. Especially from @binkybear . Thanks in advance.

**Comment by chakkale** [comment]
If anyone would have this problem again, there is clearly a bug in flashing Nethunter over Stock rom on Nexus 7 2013. I finally fixed this problem by switching to CM 13 rom and building a fresh nethunter installer from scratch for CM. All the issues are gone now and everything is working perfectly. Except if @binkybear is interested, there was a terminal issue which was causing it to crash fresh out of installation. I fixed that issue by uninstalling it and installing a custom term-nh.apk from xda developers.

**Comment by XRay437** [comment]
Which ROM are you using now? Previously i've used the ResurrectionRemix with kernel ElementalX (based on CM13).
Now i'm trying to use NH on my N7 with Nougat (crDroid 3.4 7.1.2 LOS-based) and ElementalX 6.10 but i'm not able to make my AWUS036NH working.

**Comment by chakkale** [comment]
Im using the latest nightly cyanogen 13 rom which was out for Nexus 7 2013 like 2016.06 i dont remember exactly. And i flashed it with the nethunter full kalifs installer that i built in kali for flocm.

**Comment by chakkale** [comment]
You should try the nightly kernels for flo on build.nethunter.com

**Comment by XRay437** [comment]
Do you know where I can download the latest CM based on 6.0.1? Or something based on CM but on 6.0.1, because I don't find any RR 5.8.2 (the last v. based on CM13.1 that I was using with NH).

**Comment by XRay437** [comment]
Also, it would be useful if you post the terminal nh apk because I've experienced some issue with the termnh. Thank you!

**Comment by chakkale** [comment]
here is the latest cyanogen 13 for flo : https://www.androidfilehost.com/?fid=24588212152304703
here is the terminal apk im using: https://www.androidfilehost.com/?fid=817550096634767507

**Comment by chakkale** [comment]
@binkybear @jcadduono After this threat I remember that i tried flashing it on lineage 14.1. Just wanted to ask, do you have any plans to compile a kernel that supports flo devices on lineage 14.1?

**Comment by XRay437** [comment]
Now i've flashed the CM13 as suggested, rebooted, installed nethunter and then kernel (last nightly) for flocm but now the N7 is very laggy, since the system boot, i see the boot animation very slow (1fps)...

**Comment by chakkale** [comment]
that must be the wrong kernel, that happens to me when I was trying other kernels. Now I'm gonna link all the files I used. I compiled the fullchroot kalifs zip myself but the one in the link should work as well too.

Kernel:  https://build.nethunter.com/nightly/3.15.4-20170629-1630/kernel-nethunter-flocm-marshmallow-3.15.4-20170629-1630.zip
Nethunter:  https://build.nethunter.com/nightly/3.15.4-20170629-1630/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip
CM file: https://www.androidfilehost.com/?fid=24588212152304703

**Comment by XRay437** [comment]
Idk what happened but now everything is working. Yesterday i made a clean install (again) of the CM13, gapps, i've configured my Google Account, then i've installed nethunter (last nightly), the last kernel (again!) and this time my N7 booted fine! Everything worked at "full speed", no slow OS, no slow boot animation. I've configured chroot and then, replaced the terminal, launched wifite and then "airmon-ng requires iw".
iw was correctly installed, but idk, i've tried a apt-get update & upgrade, i've rebooted several times and voilà, i've launched wifite via NetHunter app and it recognized also my otg wifi adaptor!!!

**Comment by chakkale** [comment]
Glad its working fine now. Also @binkybear ,not expecting an answer, but I just find this on the build page: 
https://build.nethunter.com/nethunteros/CM14_1/flo/

I want to try it but I'm kinda afraid. Any infos about this one ?

**Comment by chakkale** [comment]
Yep I tried it and it doesn't boot as I feared. Stuck at google log. restored from backup.

**Comment by sezusatish** [comment]
hi admin
i am using Device : Nexus 7 2013 (flo) WIFI
Android 6.0.1 (marshmallow)
Nethunter: nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip
Kernel: kernel-nethunter-flo-marshmallow-2017.11-18-1618.zip
i download the file from this links and install them using TWRP and using Y cable to connect tp link wn722n v1 but its not even led on Tp-link not blinking in lsusb able to see but i use wiconfig not able to see or detect sir kindly asst me

**Comment by chakkale** [comment]
it doesn't work properly on stock android os, as i linked above try it with CyanogenMod OS and the flash the kernel for the "flocm" one not the "flo" one.

**Comment by sezusatish** [comment]
thank you sir for your assistance i did the same as you seed it work for me for for couple minutes only after that if
i connect external wifi card it not shown in in lsusb or iwconfig  
even i try to building own nethunter base on this linke 
https://github.com/offensive-security/kali-nethunter/wiki/Building-Nethunter
including the  kernel full 
using this commend  :
root@kali:~/kali-nethunter/nethunter-installer# python build.py -d flocm -m -su  --rootfs full
able to make zip file and installed and all is working only external WiFi  
rom is installed cm 13
my device nexus 7 2013 wifi(flo)
can assist to find any solutions is it kernel issues or this nexus device is not support

**Comment by chakkale** [comment]
you should try checking another usb device such as a flash drive etc since nexus 7 usb port is unreliable and gets broken easily, also you can try another usb adapter for wifi card too. This way you can figure out if its a hardware problem or software...

**Comment by sezusatish** [comment]
sorry to disturb you but i am using the same card  in kali os and i working
good even i try with alfa card also after the zip file installed it working
for couple for minutes like 120 min even i tryed to use otg pen driver and
mouse also if possible can you asst me as i seed i tryed  to check in lsusb
it now shown or iwconfig
once again  thank you for you reply
