### ISSUE TITLE
OTG wifi interface not recognized

### ISSUE THREAD

**Issue by XRay437** [offensive-security/kali-nethunter#920]
### Device:

Nexus 7 2013 (flo/flocm)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat (LOS 7.1.2)

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170629-1630/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-ElementalX-N7-6.10 (aaron@bella) (gcc version 4.9.4 20150629 (prerelease) (crosstool-NG 1.20.0 - Linaro GCC 2015.06 - Cortex-A15) ) #1 SMP PREEMPT Mon Jul 3 10:59:57 EDT 2017

## Issue:

I'm trying to get working the AWUS036NH with an Y-OTG cable.
Kali doesn't recognize the interface, but if i run lsusb i see the device attached.
Previously, using CM 6.0.1 and ElementalX kernel i was able to use the interface without particular anomalies.
Since there's no pre-builted kernel for flocm 7.X (only Marshmallow and below), i'm using the ElementalX kernel (it should support NetHunter without anomalies).
Anyway, now i'll try to build the original NH kernel for my device and to try.
There's something that i can do? I've enabled also the Y-cable charge service through the app.
With this ROM/kernel config, i'm not experiencing any troubles.
Since from lsusb i see the wireless interface, it could be related to a kernel misconfig or to something else?

Any help is much appreciated.

Some logs:

```
root@kali:/system/etc/firmware# ls
ar9170-1.fw    htc_9271.fw  rt3070.bin     vidc.b00  vidcfw.elf
ar9170-2.fw    rt2561.bin   rt73.bin       vidc.b01  vidc.mdt
carl9170-1.fw  rt2860.bin   rtlwifi        vidc.b02  zd1211
htc_7010.fw    rt2870.bin   vidc_1080p.fw  vidc.b03

root@kali:/system/etc/firmware# lsusb
Bus 002 Device 002: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05c6:9048 Qualcomm, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```
Dmesg logs after usb unplug replug:

`[  122.969970] usb 2-1: USB disconnect, device number 2
[  122.974029] B_CONN clear
[  122.979339] a_host work
[  122.979370] !b_conn
[  122.979400] deleting a_wait_vrise timer. remaining -120122 msec
[  122.991058] smb345_charger: [smb345_inok_isr] VBUS_DET = H
[  123.188171] SELinux: initialized (dev fuse, type fuse), uses mountpoint labeling
[  123.492370] wlan: [942:E :HDD] hdd_tx_rx_pkt_cnt_stat_timer_handler: Disable split scan
[  123.637634] notifying plugin
[  125.139251] smb345_charger: [smb345_inok_isr] VBUS_DET = L
[  125.322357] portsc = 88001205
[  125.376464] usb 2-1: new high-speed USB device number 3 using msm_hsusb_host
[  125.435974] portsc = 88001205
[  125.535614] usb 2-1: New USB device found, idVendor=148f, idProduct=3070
[  125.535858] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  125.536193] usb 2-1: Product: 802.11 n WLAN
[  125.536407] usb 2-1: Manufacturer: Ralink
[  125.536743] usb 2-1: SerialNumber: 1.0
[  125.552612] B_CONN set
[  125.552642] deleting a_wait_vrise timer. remaining -122695 msec
[  125.769165] notifying plugin
`

**Comment by alphaomicron** [comment]
I've tested it as well but it wont work. Would recommend use the tp link  TL WN722n
It seems to work natively
