### ISSUE TITLE
wifi dongle wont reconzie!

### ISSUE THREAD

**Issue by neogenik** [offensive-security/kali-nethunter#921]
### Device:
nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):

website

## Issue:
i have tryed multipule otg cables with no luck. for a split 2nd the wifi adapter lit up for a split secon and that was that no more. i have a tp-link tl-wn722n. any help would be great. im running nethunter of kali linux. any help?

**Comment by icefireCZ** [comment]
Hey, it looks like you have same problem like me, but with different phone.
Check this:
https://github.com/offensive-security/kali-nethunter/issues/879

**Comment by alphaomicron** [comment]
try downgrading to android 6.0 and test it.See if it works.Hope this helps
https://www.youtube.com/watch?v=Tb_0nOGnTUI
