### ISSUE TITLE
slow duckhunter hid attack>?#!

### ISSUE THREAD

**Issue by huzaifa-007** [offensive-security/kali-nethunter#925]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
umm''(custom kernel) ;)
## Issue:
i came across this project called droidducky (https://github.com/anbud/DroidDucky)
it worked on my phone and then i tried nethunter's duckhunter hid ...
the result of nethunter's hid was way much more slower than the droidducky idk if it even is an issue for other guys .. so it's more of a confirmation ..
if other people also encounter the same issue ;
i suggest you should implement (droidducky) in the nethunter app
otherwise the issue can be closed(if no one gets slow hid attack)
i was attacking windows 10 btw and script generated from rubberducky's site and it worked without problem

**Comment by simonpunk** [comment]
the speed was actually not that slow before they changed to anther output method

**Comment by huzaifa-007** [comment]
I used your duckhunter.py file and the speed is too much faster 
But some problems.
As far i could check.
1.it executes ENTER after a STRING statement
2. doesn't  print the letter 'g' in any layout.
3.MOUSE statement not working 
The problem persist even after replacing all my files with yours.

**Comment by simonpunk** [comment]
hi, for your question:
1. I didnt notice that before, maybe I give it a look tonght.
2. actually you will need to modify the 'bootkali' file in located at system/bin/, search the string `$busybox chroot $mnt /bin/bash $2`, comment out that string, and then add this string `sh /sdcard/nh_files/modules/duckout.sh` , then save it. it should solve the letter 'g' problem.
3. I dont even konw there is such statement exist, but I will take look later.

**Comment by huzaifa-007** [comment]
I did as you said . But i remember for almost every script i have to replace /sdcard with the full path i.e "/storage/emulated/0/" but that's  a whole other issue 
Other than that your suggestion worked now its all good ..
but sometimes if there's  something wrong with the script  i cant stop it from sending keystrokes 
You should also add something like a ctrl-c to stop the script.. plugging out the usb doesnt work it just resumes executing the script after i plug it in....


And just another unrelated to this issue  question.. In the nethunter app .. "hid attack" section. can i change the hid keystrokes. Where is the file in which the ducky script is stored?
Thanks for your help (y)

**Comment by huzaifa-007** [comment]
It helped resolve the letter 'g' error but now it doesn't use the file at /opt/duckout.sh which is generated by the "duck-hunt-convert" bootkali script arg used by the nethunter app.. 
So changing $your-suggestion to "sh /data/local/nhsystem/kali-armhf/opt/duckout.sh" 
Worked for me :D ..
So i think i should close the issue if the "enter key " after STRING statement isn't  an error 👍
