### ISSUE TITLE
NetHunter Keeps Stopping

### ISSUE THREAD

**Issue by GVoid27** [offensive-security/kali-nethunter#926]
### Device:
Samsung S7 SM-G930F

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170629-1630.zip

https://build.nethunter.com/nightly/3.15.4-20170629-1630/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Closes without providing output, Samsung error "NetHunter Terminal has stopped"

## Issue:
When ever I open NetHunter and select any shell, the terminal crashes with the error "NetHunter Terminal has stopped". I am relatively new to this, any help would be greatly appreciated.

I saw in "Nethunter Terminal crashing #420" that binkybear asked if /data/local/nhsystem/kali-armhf has files, I don't see any files there. Is this perhaps my issue? And if so how do I go about resolving it. Thank you!

**Comment by BearChavez** [comment]
You should flash armhf, not arm64

**Comment by jcadduono** [comment]
arm64 is correct for his device, he is missing a kernel obviously because he flashed generic, which means he is still in enforcing selinux mode (normally i ship nh kernels in permissive mode to make things work)

the arm64 installer still installs the armhf kali fs, so you should provide logs from install from recovery if you do not see the kali-armhf folder

**Comment by GVoid27** [comment]
I don't see the kali-armhf folder at all, I've attached the recovery log (hope its the correct log).

Note I also tried flashing generic alongside with: kernel-nethunter-generic-arm64-3.15.4-20170629-1630 , but still having the same issue. I'm feeling like a proper noob with this issue, I really appreciate your help.
