### ISSUE TITLE
Bug in Kernel Oneplus 3. Camera doesnt work

### ISSUE THREAD

**Issue by pindonga1234** [offensive-security/kali-nethunter#927]
### Built from repo (date and build command) or downloaded from website (links):
Lastest nethunter downloaded from nethunter.build.com
Lastest Oxygen downloaded from the official site

**Comment by Malmik** [comment]
You can always modify kernel at your own.
Here are links to tutorials:
1 https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter
2 https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

Ps. When I come back home I can do this kernel if you can't. Just write to me

**Comment by majackov** [comment]
I have this trouble too with last open beta. And wifi doesnt work too :(

**Comment by pindonga1234** [comment]
Thank Malmik for your help. I dont know how send a private message, I wanted send you for ask for you mail for helping I dont have the most minimal idea hoy modific the kernel. I was reading some about it but I saw very difficult and I gave up. Thank for your help
