### ISSUE TITLE
Nexmon on Nexus 5x Bullhead with nethunter

### ISSUE THREAD

**Issue by LinuxPentesting** [offensive-security/kali-nethunter#928]
### Device:

Does anyone know if there is a build for Nexus 5x  (nougat) bullhead with nethunter that would allow for monitor mode with wlan0 for packet injection? Ive read the posts about hammerhead and it being applicable on android 6.0, but nothing about bullhead or nougat. Would love to hear from binkybear and other devs

**Comment by h3xcmd** [comment]
The 5x bullhead unfortunately does not support packet injection,  you will have to use an Alfa AWUS036AC USB wlan1 dongle. When it comes to pwn phones you will need dongle's unless its the one+plus(number) or the 5 hammerhead. Most will support monitor mode though that's like a normal scan for wifi networks.

**Comment by BearChavez** [comment]
@h3xcmd What USB-C otg cable works? I'm looking at an Aukey adapter plus the Panda PAU05 for my 5X

**Comment by bozwald** [comment]
Nexmon doesnt work on the 5x as its a qualcomm chip, a USB-C to female USB
A (f) works for me, it powers a couple of devices perfectly but required a
powered USB hub for a wifi card Alfa AWUS036H, getting the NEH soon so will
try that without hub, im also looking for a powered USB HuB that works with
a power pack @jcadduono suggested one but i misplaced the name of it.

I had to remove supersu and then reinstalled the kali bullhead rom and it
works on mon mode too, i was installing two supersus and a mount request
was failing.

Wifite worked but seemed not to capture a handshake.

Bluetooth dongle isnt found by hciconfig at all a var/bus error
