### ISSUE TITLE
Searchsploit platform crashes and Nethunter Terminal Instability

### ISSUE THREAD

**Issue by TheRealEliteOwl** [offensive-security/kali-nethunter#929]
### 
https://build.nethunter.com/nightly/3.15.4-20170629-1630/kernel-nethunter-shamu-nougat-3.15.4-20170629-1630.zip

https://build.nethunter.com/nightly/3.15.4-20170629-1630/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40-ged17190 (android-build@wpix2.hot.corp.google.com) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Thu Jan 19 06:01:31 UTC 2017

## Issue:

Crash on Searchsploit during switch of platforms. "Nethunter keeps stopping"

Been able to get around this by leaving it on Searchsploit for a few seconds before moving to another platform. Seems to be specific to platforms mostly. 

Another issue - Nethunter terminal crashes regardless of Kali Android or Su. 
Fix - Download Android Terminal Editor
Input 1 - SU
Input 2 - Bootkali
This should restore functionality for both Nethunter Terminal and Android Terminal Editor.

**Comment by jcadduono** [comment]
nethunter kernel not installed, your issue is to be expected in selinux enforcing mode

**Comment by TheRealEliteOwl** [comment]
I noticed that and thought it was strange, I reflashed and it is working.
