### ISSUE TITLE
firefox and iceweasel

### ISSUE THREAD

**Issue by maxygas** [offensive-security/kali-nethunter#930]
### Device:
Shamu

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Cm 13

### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40-g819dcd6 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Sep 23 23:12:26 UTC 2016

## Issue:
Firefox is showing only blank page and iceweasel the same . I can open any site but i see nothing just blank pages. Can you help me maybe ?

**Comment by maxygas** [comment]
[GFX1-] : Failed 2 buffer db=0 dw=0 for 0,0,1268,50

**Comment by maxygas** [comment]
Solved thanks !
about:config 
browser.tabs.remote.autostart2 set to false

**Comment by vespirah** [comment]
Hey maxygas i have the same problem could please give a more detailed information on the steps you used please and thank you

**Comment by maxygas** [comment]
Hi ! Open up firefox , write in adress bar about:config  and
Scroll to line browser.tabs.remote.autostart2
And set it to false hope this works you too

BlueMail<http://www.bluemail.me/r?b=10066> -el küldve
2017. júl. 23.-n, 23:21-kor, vespirah <notifications@github.com<mailto:notifications@github.com>> ezt írta:

Hey maxygas i have the same problem could please give a more detailed information on the steps you used please and thank you

**Comment by sikklegend** [comment]
I get a black screen not a blank but black and i cant fix it

**Comment by yesimxev** [comment]
`mkdir /dev/shm`
