### ISSUE TITLE
No Sound - kernel-nethunter-shamu-nougat-3.15.4-20170629-1630

### ISSUE THREAD

**Issue by TheRealEliteOwl** [offensive-security/kali-nethunter#931]
### Device:

Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat 7.1.1

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.15.4-20170629-1630/kernel-nethunter-shamu-nougat-3.15.4-20170629-1630.zip
https://build.nethunter.com/nightly/3.15.4-20170629-1630/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Happens as soon as the kernel is flashed. 

## Issue:
No sound

**Comment by rubencabrera** [comment]
Same issue reported here: 
https://github.com/offensive-security/kali-nethunter/issues/873
