### ISSUE TITLE
No HID interface detected nexus 7 6.0.1 marshmellow

### ISSUE THREAD

**Issue by tehpenguin** [offensive-security/kali-nethunter#933]
### Device:
Nexus 7

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

nethunter-flo-marshmellow-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.0-gad29d11

## Issue:
No HID interfaces are detected. /dev/hidg0 and /dev/hidg1 are not present.

**Comment by tehpenguin** [comment]
So it looks like I need to flash version 3.15. I am just confused how to flash the correct kernel afterwords. If anyone can explain this process it would be awesome!

**Comment by BearChavez** [comment]
https://build.nethunter.com/nightly/3.15.4-20170629-1630/kernel-nethunter-flo-marshmallow-3.15.4-20170629-1630.zip

That should be the correct kernel, flash it through TWRP

**Comment by tehpenguin** [comment]
I cant seem to get into twrp

**Comment by BearChavez** [comment]
@tehpenguin Try re-flashing your recovery, I have had to do this before when re-installing ROMs and using custom kernels

**Comment by tehpenguin** [comment]
So i was able to flash the kernal but its still not showing any hid and now kali terminal crashes

**Comment by BearChavez** [comment]
@tehpenguin Is it the "No Title" crash? It's been discussed before if that's the issue

**Comment by tehpenguin** [comment]
Well, I think the kernel never actually flashed. I must be doing it wrong. Uname -a shows kernel 3.4 and it should be 3.15.4

**Comment by BearChavez** [comment]
@tehpenguin Run the command 
cat /proc/version
The output of that is what you need to know if it's installed correctly, if you get the terminal running of course

**Comment by tehpenguin** [comment]
When I su in Terminal emulator and cat /proctversion it shows 3.4 still in android and bootkali

**Comment by tehpenguin** [comment]
Solved with updating to 3.15 kernel on 3.0.
