### ISSUE TITLE
DuckHunter HID key error

### ISSUE THREAD

**Issue by huzaifa-007** [offensive-security/kali-nethunter#939]
### Device:
LG G2 -VS980

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
nougat

### Built from repo (date and build command) or downloaded from website (links):
[CUSTOM built ] no problem with the kernel for sure

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
[CUSTOM built ] no problem with the kernel for sure

## Issue:
something is wrong with the duck-hunt-convert bootkali arg,
it includes an {enter } key after a STRING ends in the duckout.sh script

**Comment by jcadduono** [comment]
I think there is a different command like TEXT to not produce enter key

**Comment by huzaifa-007** [comment]
Yeah ! Sorry my BAD 😅
