### ISSUE TITLE
Nexus 5 Nexmon with OTG devices 

### ISSUE THREAD

**Issue by PeaCarChoo** [offensive-security/kali-nethunter#940]
### Device:
Nexus 5

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 

### Built from repo (date and build command) or downloaded from website (links):
NethunterOS
https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e
Nethunter App & Kalifs-full updated from nightlys 
kernel-nethunter-hammerheadmon-nougat-3.15.4-20170629-1630.zip
nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-ElementalX-N5-7.09 (root@AutinDroid) (gcc version 4.8 (GCC) ) \1 SWP PREEMPT Mon Jan 23 18:34:26 EST 2017

## Issue:
I have NethunterOS installed and the Nexmon part works well. I'm able to run airodump-ng with the internal wifi card, its awesome. However, I'm having issues with OTG, I'd like to add another external wifi card and use a USB memory stick too (not necessarily at the same time). 

I can connect an OTG cable and a mouse and that works fine.

If I connect an OTG cable with a Wifi USB (PiHut Ralink RT5370) then do lsusb it shows only the two default Linux Foundation root hubs. Dmesg indicates USB "device not accepting address 2, error -62" and "cannot disable port 1 (err=19)".

If I use a Y-Cable and connect the mouse that works fine.

If I use a Y-cable and connect the Wifi USB then I get a similar error again "device not accepting address 4", "unable to enmerate USB device on port 1" but I also spotted these errors "bq24192_set_input_i_limit: bad mA=0 asked to set", "bq24192_therm_mitigation_work: failed to set input current limit as 0". Not sure if the last two are relevant to the USB or just the charging part (which works). 

I've tried changing the y-cable charging service setting in Nethunter app but it makes no difference.

I've tried a few devices such as USB memory sticks and other wifi cards and only the mouse works, or is even listed by lsusb.

But now for the confusing bit, I've also tried a three different USB hubs and found one that works. My desktop USB hub works. I.e. I've connected the OTG cable to a 4-port USB hub and connected the Wifi USB into the hub and it works perfectly everytime. All the devices that didn't get listed by lsusb when connected directly also work via the hub.

I assumed it was a power issue but that doesn't explain why the hub works but the Y-cable doesn't. I don't think it can be software\firmware because the Wifi card works perfectly via the hub. So I'm stumped!

As a last resort I have ordered a TL-WN722 which I'm hoping will work directly.

**Comment by jcadduono** [comment]
If the desktop hub has power from AC adapter then the desktop hub has a built in controller that is negotiating and providing its own power with the connected devices. Using the Y cable it's possible that the phone is refusing to negotiate any higher power than it is able to safely put out, and the power provider connected to the power split in the Y cable can't communicate to negotiate power so it provides none.

**Comment by PeaCarChoo** [comment]
The fault turned out to be a hardware issue with the usb on the phone. I made an image of the phone and copied it to another phone and it worked perfectly. Annoying that the usb partially worked and hence why the fault was so difficult to find. Still I got there in the end!
