### ISSUE TITLE
404 updates? Checked sources.list...

### ISSUE THREAD

**Issue by frankj22** [offensive-security/kali-nethunter#943]
## Issue:I'm trying to update kali after installing nethunter and getting a bunch of 404's
I've checked sources.list and it only has the  2 recommended sources. I checked sources.d and its empty.
Where is it finding these extra sources.
Any help very much appreciated thanx

**Comment by BesoBerlin** [comment]
Are these two sources still Kali sana?
If so, change them to kali-rolling and do apt-get update && apt-get dist-upgrade

**Comment by frankj22** [comment]
Thank you very much, I'll try as soon as it charges and post...

**Comment by frankj22** [comment]
So I changed the sources.lst file to just 
deb http://http.kali.org/kali kali-rolling main contrib non-free
Still getting errors
I found a reference to another location where sources were stored and found some files with the names of the failing sources but now I cant find them.
Is there anything else you can recommend?
I've been at this for a week and feel so close!

Any help greatly appreciated...

Maybe someone could make a working chroot for samsund d710

**Comment by jcadduono** [comment]
If on a kernel 3.2 or older device you must use old.kali.org sana repos not http.kali.org
Otherwise, why not just use nightly build generic for your device which has a prebuilt rolling chroot :/
