### ISSUE TITLE
Installation enquiry

### ISSUE THREAD

**Issue by vs17673704** [offensive-security/kali-nethunter#946]
If someone can tell me whether I can install Kali Linux in Lenovo K4 note.

**Comment by ricky0178** [comment]
You can download a general device nethunter zip at https://images.offensive-security.com/nethunter-release/nethunter-hammerhead-marshmallow-3.0.zip this link flash it with a custom recovery, and hope it will work

**Comment by jcadduono** [comment]
Do not flash hammerhead NetHunter on non hammerhead devices!!!! Use generic NetHunter from build.nethunter.com as described in the NetHunter wiki! You won't have any kernel support on unsupported devices, so they will not work with OTG or HID features (wifi monitoring, packet injection, ducky) until someone ports a NH kernel for your specific device

**Comment by kimocoder** [comment]
For devices that are NOT supported, it is possible to build an image by compiling a supported kernel. 
Read more on howto compile/build & adding device support on the NetHunter wiki [here](https://github.com/offensive-security/kali-nethunter/wiki)

**Comment by suzainkhan** [comment]
You can get blue tick from here 
https://junaidmugloo.blogspot.in/p/settings.html?m=1
