### ISSUE TITLE
Missing /dev/hidg1

### ISSUE THREAD

**Issue by ricky0178** [offensive-security/kali-nethunter#948]
### Device:

Samsung Galaxxy S5 mini (sm-g800f)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Ansrois 7.1.1 nougat LineageOS

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.39+ (ayke@android) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Mar 24 16:03:33 CET 2017
kminilte:/ #

## Issue:

/dev/hidg1 missing. I've tried to execute the command ls /dev/hidg* and the output is /dev/hidg0. Duckhunter HID in fact won't work

Update: 
I reinstalled nethunter, but now every hid interface has disappeared

**Comment by ricky0178** [comment]
Update: 
I reinstalled nethunter, but now every hid interface has disappeared

**Comment by jcadduono** [comment]
You will want to tag the developer of the kernel for your device. (ayke@android) and mention unstable or missing hid kernel drivers.
