### ISSUE TITLE
boot animation

### ISSUE THREAD

**Issue by hxrofo** [offensive-security/kali-nethunter#951]
### Device:

Samsung Galaxy Note N9005

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Lollipop 5.0

Does anyone of you know a way to get the boot animation in nethunter to work in galaxy note 3? I installed the generic kalifs full rolling [https://build.nethunter.com/nightly/3.15.4-20170629-1630/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip](url) and kernel-nethunter-hlteeur-lollipop-3.15.4-20170629-1630.zip and everything works fine except the boot animation, which i'd like very much to have...i think it's sexy LOL. thanks

**Comment by jcadduono** [comment]
There used to be a zip you could install on Samsung devices to make Android use the Android boot animation format again but it stopped working after KitKat. Need someone to convert NH Android pngzip container format to Samsung QMG bootanim format I guess.

**Comment by hxrofo** [comment]
It works on CM. Earlier this morning, I was testing different roms, so I flashed this CM rom [cm-14.1-20161029-UNOFFICIAL-trader418-hlte-v0.7B](http://download.highonandroid.com/file/CM14.1/GalaxyNote3/cm-14.1-20161029-UNOFFICIAL-trader418-hlte-v0.7B.zip) then installed armhf kalifs full rolling, and the boot animation worked great.
