### ISSUE TITLE
Wifi adapter not detected

### ISSUE THREAD

**Issue by itsme2417** [offensive-security/kali-nethunter#953]
### Device:

Nexus 5x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat

### Built from repo (date and build command) or downloaded from website (links):

Downloaded from https://forum.xda-developers.com/nexus-5x/development/kali-nethunter-nexus-5x-bullhead-t3453134 
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016

## Issue:
My wifi adapter (TP-LINK TL-WN722N) isn't recognized by Kali I'm pretty sure it's receiving enough power and other devices such as my rtl sdr are detected fine

**Comment by jcadduono** [comment]
dmesg

**Comment by itsme2417** [comment]
https://pastebin.com/pKt6b0Db
This was after I plugged in and unplugged my antenna multiple times also a device does show up in lsusb but only if I'm using a 4 port hub (which is not the device since when I unplug the antenna it goes away)

**Comment by itsme2417** [comment]
I found out it works if i plug it in my otg cable just a bit in and in a VERY specific position....guess it's my otg cable
