### ISSUE TITLE
Kernel make error

### ISSUE THREAD

**Issue by TheImpulse** [offensive-security/kali-nethunter#955]
### Device:
Asus Zenfone 2 Laser (Z00L)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat

### Built from repo (date and build command) or downloaded from website (links):
August  13, 22:54

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017

## Issue: 955

I am using CM sources to make kernel. I follow exact steps as told on Modifying kernel page and everything goes fine untill I make. It always ends with following error. I tried by changing sources to offical kernel source files but I am still getting same error. Help me solve it. A point though my device is unoffical and I am trying to make it offical. My device is having offical Lineage OS 14.1 that I am using as base.

arch/arm64/mm/fault.c: In function '__do_kernel_fault':
arch/arm64/mm/fault.c💯2: error: implicit declaration of function 'cpr_regulator_print_corner_voltage' [-Werror=implicit-function-declaration]
  cpr_regulator_print_corner_voltage(); //<asus-wx20150730+>
  ^
In file included from include/linux/jump_label.h:70:0,
                 from include/linux/static_key.h:1,
                 from include/linux/tracepoint.h:20,
                 from include/linux/module.h:18,
                 from arch/arm64/mm/fault.c:21:
/home/aayushgupta219/nethunter/android_kernel_asus_msm8916/arch/arm64/include/asm/jump_label.h: In function 'do_page_fault':
/home/aayushgupta219/nethunter/android_kernel_asus_msm8916/arch/arm64/include/asm/jump_label.h:30:2: warning: asm operand 0 probably doesn't match constraints
error, forbidden warning: jump_label.h:30
scripts/Makefile.build:308: recipe for target 'arch/arm64/mm/fault.o' failed
make[1]: * [arch/arm64/mm/fault.o] Error 1
Makefile:828: recipe for target 'arch/arm64/mm' failed
make: * [arch/arm64/mm] Error 2

**Comment by jcadduono** [comment]
what toolchain are you using? for most aarch64 kernels i would recommend https://releases.linaro.org/components/toolchain/binaries/latest-5/aarch64-linux-gnu/gcc-linaro-5.4.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz

**Comment by TheImpulse** [comment]
This toolchain is not working. I am using toolchain mentioned in kali guilde i.,e. 4.9. which is causing errors too. The toolchain you recommended is giving error gcc5 not found.

**Comment by Malmik** [comment]
Do you surely use 64 bit version of linux to compile?
