### ISSUE TITLE
Nethunter Terminal won't connect to Kali without additional step

### ISSUE THREAD

**Issue by lvdisturbed1** [offensive-security/kali-nethunter#958]

**Comment by lvdisturbed1** [comment]
Did a little testing with previous known-working builds.  Seems like the problem I am having is related to Magisk.  When using SuperSU, it works as intended.

Not sure what the issue is, SELinux is permissive.  Thoughts?  Anyone out there get Nethunter working with Magisk 13.3?

**Comment by atarii** [comment]
I've added a fix for this here: https://github.com/offensive-security/nethunter-app/pull/173
