### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Malmik** [offensive-security/kali-nethunter#960]
Hi. Two questions (as in title):
1.When will be armel version of chroot released?
2.I have 2.6.x.x kernel source code for Samsung Callisto. How to update it to minimum of 3.2, or modify 3.2 kernel source of other samsung device to work on it?
(I know that this is not directly related to Kali, but I am working on a port of it, and this wilk be usefull info)

**Comment by jcadduono** [comment]
lol
why would you put like 500 hours of work into making an incredibly obsolete device with a very low resolution that can't even run the nethunter app run nethunter when you can just buy something cheap like Moto E4 (USA Snapdragon 625) for $129 or Moto E4 Plus (Snapdragon 627) for $199 that will run nethunter with ease

you would need extremely indepth kernel knowledge to port an ancient chipset like that to kernel 3.2 or newer and like i said at least 500 hours of work
and the best part is....you'd have to port the operating system too!
it will never happen

**Comment by Malmik** [comment]
Just wanted to have pchisical keyboard :D

**Comment by Malmik** [comment]
Thanx. By the way, I want to develop NetHunter. I have soo much free time, I learn very fast and I am determined. How can I help?
