### ISSUE TITLE
Nethuntet terminal "no title error"

### ISSUE THREAD

**Issue by davidbbisht** [offensive-security/kali-nethunter#964]
Kali nethunter is successfully installed with chroot. But in terminal show "no title" error and couldn't be open terminal.

**Comment by davidbbisht** [comment]
Pls Anyone do help me...

**Comment by BearChavez** [comment]
This issue has already been discussed, please check the closed issues section

**Comment by somnath003** [comment]
@BearChavez  there is no solution I found for this issue I readed many closed issues can you help me??
