### ISSUE TITLE
Hammerheadmon kernel: no HID interfaces

### ISSUE THREAD

**Issue by hxrofo** [offensive-security/kali-nethunter#965]
### OS version: Nougat
===> **Euclidean ROM version 7.1.2-20170511-hammerhead-NIGHTLY**
### Nightly build: https://build.nethunter.com/nightly/3.15.4-20170629-1630/
**Kernel:** https://build.nethunter.com/nightly/3.15.4-20170629-1630/kernel-nethunter-hammerheadmon-nougat-3.15.4-20170629-1630.zip
**FS:** https://build.nethunter.com/nightly/3.15.4-20170629-1630/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170629-1630.zip
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.0-ElementalX-N5-7.09 (root@AutinDroid) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Mon Jan 23 18:34:26 EST 2017

## Issue:
Actually, there are **TWO** issues:
1) the first one is there are no HID interfaces at all. ls /dev/hidg* returns "no such file or directory"
2) the second one, and maybe that's what's causing the first, is that the kernel never gets flashed, even with different official TWRP versions: **2.8.7-0** / **3.0.0-0** / **3.0.1-0** / **3.0.3-0** / **3.1.0-0** and **3.1.1-0**
Whenever I issue the command **cat /proc/version** , it returns version 3.4.0

**Recovery Log** link: https://pastebin.com/aukAdEeJ
Thanks for helping
 
EDIT: solved by typing the command "setprop sys.usb.config hid" in androidsu terminal, which brings the hidg* interfaces up

**Comment by jcadduono** [comment]
according to your `cat /proc/version` and twrp log it flashed just fine
maybe hid patch needs fixing

**Comment by hxrofo** [comment]
@jcadduono How can I get it patched? thnx

**Comment by awerqo** [comment]
Hello! I have same problem on same device.
Output of cat /proc/version in adb shell or NetHunter Terminal are the same.

OS Version: Nougat (Linage 14.1)
Nightly build: 2017.11-18-1618 https://build.nethunter.com/nightly/2017.11-18-1618/nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip

With hammerheadcm kernel https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-hammerheadcm-nougat-2017.11-18-1618.zip hid works perfectly

With hammerheadmon kernel https://build.nethunter.com/nightly/2017.11-18-1618/kernel-nethunter-hammerheadmon-nougat-2017.11-18-1618.zip   i must typing "setprop sys.usb.config hid" in androidsu terminal" always after i connected phone to computer and select MIDI connection.

Somebody found how solve this problem?
Thanks for helping.

**Comment by awerqo** [comment]
I dont't remember but after connection phone to computer and selecting "MIDI connection" you can get the HID interfaces by typing:

 "setprop sys.usb.config hid"
And HID Attack will be work.

But after reconnect phone or reboot you must do it again.
