### ISSUE TITLE
Add simpler wallpaper

### ISSUE THREAD

**Issue by keeganjk** [offensive-security/kali-nethunter#966]
In 1999, Google had an ugly logo that had too much detail:
![Google Logo, 1999](http://i2.cdn.turner.com/money/dam/assets/150831165121-google-05-31-1999-to-05-05-2010-780x439.png)
Now, it's much more simple and looks much better:
![Google Logo, Now](https://cdn.vox-cdn.com/uploads/chorus_asset/file/6466217/fixed-google-logo-font.png)

The Kali Nethunter wallpaper has too much detail, like the text with shadows, ugly lines, (too much) fire and blue lines in the background, and lines and stuff on the dragon logo. Could you add a simpler, better-looking wallpaper or choices of wallpapers?

**Comment by pingo-power** [comment]
Same here

**Comment by Truestark** [comment]
I can make a new set of wallpapers if you want

**Comment by Truestark** [comment]
![16 - 1](https://user-images.githubusercontent.com/7072398/29863876-95e1fd62-8d8e-11e7-82b3-3136daebe6dd.jpg) I made this one when I was using nethunter, it looks super minimal on AMOLEDs.

**Comment by keeganjk** [comment]
@Truestark It's good, but it uses the Kali Linux logo instead of the Kali Nethunter logo. I still might use it, though.

**Comment by keeganjk** [comment]
@Truestark Yes, a new set of wallpapers would be great!

**Comment by Truestark** [comment]
![prop1](https://user-images.githubusercontent.com/7072398/29912682-21760f00-8e50-11e7-98f1-d1cfd96be110.jpg)

how about this?

**Comment by kimocoder** [comment]
This ia actually VERY nice sir! Great work!

**Comment by kimocoder** [comment]
These are the sizes needed, if you fix the sizes matching these ones needed, just email them to me at [christiian@nesl.no](mailto://christian@nesl.no) and I'll pust the commit.

![screenshot_20170831-105341](https://user-images.githubusercontent.com/4252297/29914998-b84ca2f6-8e3a-11e7-8d94-633ed22c6889.png)

**Comment by keeganjk** [comment]
Maybe you could add both of these, and if anyone else has any ideas, they can try to add some as well.

**Comment by keeganjk** [comment]
I tried some new colors:￼

**Comment by keeganjk** [comment]
New colors?:


![Wallpaper](https://postimg.org/image/q8bkx5xt1/)

**Comment by keeganjk** [comment]
Maybe more blue than purple?

**Comment by Truestark** [comment]
@kimocoder I've resized it for the resolutions needed, check email :)

**Comment by kimocoder** [comment]
Got them sir, I'll make the commit in few hours sir

**Comment by kimocoder** [comment]
@Truestark the commit is more or less ready, but one (1) wallpapers are missing in the set and that is the "768x1280.png" if you send me the missing one, the commit would be pushed right away :)

Use the same email i noted above. Thanks for your great work btw, I was sure to put your handle in the credits into the commit.
