### ISSUE TITLE
Error: BAD CHECKSUM

### ISSUE THREAD

**Issue by bphd** [offensive-security/kali-nethunter#968]
Device:

A2003

OS version (KitKat/Lollipop/Marshmallow/Nougat):

7.1.2 secondary MultiROM 

Built from repo (date and build command) or downloaded from website (links):

https://forum.xda-developers.com/oneplus-2/development/nethunter-3-15-3-oneplus-2-cm-14-nougat-t3507548

Output of cat /proc/version in adb shell or NetHunter Terminal:

Linux version 3.10.107-Desolation (Savitar@Saturn) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jul 17 09:38:19 UTC 2017

## Issue:

30 août 2017 08:59:09 - New instalation log file: /storage/emulated/0/nh_install_20170830_085906.log
30 août 2017 08:59:15 - Deleting to make room for download&
30 août 2017 08:59:15 - /storage/emulated/0/kalifs-minimal.tar.xz found.
30 août 2017 08:59:15 - Starting download. Standby&
30 août 2017 08:59:15 - File deleted.
30 août 2017 09:01:02 - Chroot download completed: Total 123.0 MB.
30 août 2017 09:01:02 - Original SHA: 86752FBA98B54DAF5F66D04B1306EBEBB25EA434BD5F17AA53B53C75AEF6E9309084E0E6C01B94461DCB5615E4DD9EB97AC1D8973EBADCD1F6962B99312AE7E5
30 août 2017 09:01:14 - Error: BAD CHECKSUM: FAE5DEAAD07E45F712101457BAD8FA196110D842AA420FD49C6A591871AFEB8CDDB1353675707EEF8CDFAE2E80B55E454EF54FA21965E22BFFB6D30E03B8FF17
30 août 2017 09:01:14 - Checking for chroot at /data/local/nhsystem/kali-armhf
30 août 2017 09:01:14 - Something went wrong verifying the downloaded file. Whoops. Try again.
30 août 2017 09:01:14 - No Kali chroot directory was found.
30 août 2017 09:01:14 - Cleaning install directory

**Comment by kimocoder** [comment]
Open terminal, find the "kalifs-minimal.tar.xz" and verify the checksum with the command "sha512sum kalifs-minimal.tar.xz" give the output here and I may take a look at it.

**Comment by pingo-power** [comment]
OnePlus2:/ # sha512sum /storage/emulated/0/kali*
4c6a69c3f99406c33db1fcd5c0f19e0947dcc75ba917ea46bc9708a2c7a101dec03ef14f37bea7bf40b5fb0d34b398a77d026d3d664fb5e8583e9823c8d592ca  /storage/emulated/0/kalifs-full.tar.xz
fae5deaad07e45f712101457bad8fa196110d842aa420fd49c6a591871afeb8cddb1353675707eef8cdfae2e80b55e454ef54fa21965e22bffb6d30e03b8ff17  /storage/emulated/0/kalifs-minimal.tar.xz
OnePlus2:/ #

**Comment by kimocoder** [comment]
the latest "kalifs-arm64-minimal.tar.xz" is actually 137.2mb, not 123mb as seen [here](https://build.nethunter.com/kalifs/kalifs-latest/)  but anyways you could use a workaround until the problem gets solved.

* Howto?

Use "busybox tar xf kalifs-minimal.tar.xz" and move the unpacked folder into /data/local/nhsystem/ manually. Then restart the app and it should be installed

**Comment by pingo-power** [comment]
Segmentation fault

**Comment by kimocoder** [comment]
well, check your busybox installation & other options (try downloading the latest kalifs-minimal and unpack it other ways and place it manually) because im out of options for quick fixes at the moment, but looking into the main

**Comment by pingo-power** [comment]
kalifs-arm64-minimal.tar.xz ? Or other ?

**Comment by kimocoder** [comment]
Yeah, if your system is arm64. Remember renaming the file if not unpacking, and the folder if you choose to unpack & place manually

**Comment by pingo-power** [comment]
Okay i Will unpack all in /data/local/nhsystem/kalifs/

Just, take a look at my other issue please

**Comment by pingo-power** [comment]
Impossible to unpack it without a LOT of errors and duplicates

Any ideas ?
