### ISSUE TITLE
Help please stuck with the "no title" and crash issue

### ISSUE THREAD

**Issue by ortholinux** [offensive-security/kali-nethunter#971]
### OS version (KitKat 4.4.2)

###downloaded from website (offensive security):
as i couldn't find a method to build nethunter over mediatek chipset devices, and i actually used nexus and oneplus one zips. TWRp was not flashing nightly (generic zips nor any other)

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.4.67 (builder2008@server-ubuntu) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Thu Mar 19 09:40:04 CST 2015

## Issue:
It was installed all successfully and showed that kernel was patched using anykernel etc. 
Now nh-terminal is not working at all for kali,, Android and AndroidSU although still show no title but yet work, but tap kali and just saying no title the terminal crashes, now cant go for meta-packages neither any terminal command, i tried installing new nethunter and nh-terminal apks, created symlinks for bootkali_env, init,bash etc , nothing worked for me.
Help please, (i am also a bit new to android environment so don't really know what can be the cause) ?
Thanks

**Comment by ortholinux** [comment]
Edit: doing a su bootkali
says: missing a required folder. something isn't right
all the symlinks are there in /system/bin(bootkali, bootkali_bash, bootkali_env, bootkali_init, bootkali_login)
installed busybox several times
commaand busybox tells: busybox v1.27.1-stericson.
Also installed nh-term from "github.com/binkybear/Android-Terminal-Emulator/releases"
Can anyone help me with this problem or atleast show some direction ?

**Comment by XIV91774** [comment]
use a terminal app and log in as root, then do an "ls -la /data/local/nhsystem" and check if there's files in that folder.

**Comment by bozwald** [comment]
Im having the same issue I am on a SM-G955F running Nougat 7.0 I have Busybox Pro latest installed to system/bin but whenever i do setenforce 0 or bootkali or open terminal or update metapackages my phone reboots

**Comment by XIV91774** [comment]
Hey bozwald, I reckon this may be that the nethunter you installed is not ported for your device yet, as nethunter is relatively new I suggest you go to these pages to learn how to port nethunter on your device for yourself, I got off easy because I have a nexus 5 and nethunter is officially supported by offsec.

https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter

https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

**Comment by bozwald** [comment]
I use telegram @bozwald @XIV91774 ive managed the get past that and have got nethunter on my phone struggling to modify a kernel to add mac80211 and otg and bluetooth  at the moment ive compiled one twice but my phone wont boot with it not even a boot loop
