### ISSUE TITLE
The right version to download

### ISSUE THREAD

**Issue by beav0team** [offensive-security/kali-nethunter#972]
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
LineageOS 14.1

## Issue:
Can I get the link the the right version to download for my device I can't find my device on the official download page  thank you all

**Comment by beav0team** [comment]
Linux version 3.4.113-g61c9656 (jenkins@agrippa.acc.umu.se) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Aug 16 17:27:32 CEST 2017

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/wiki#20-downloading-nethunter
Read this, match kernel to your lineageos device codename
