### ISSUE TITLE
Nethunter terminal app closing when selecting kali 

### ISSUE THREAD

**Issue by XIV91774** [offensive-security/kali-nethunter#974]
### Device: LG nexus 5 
Hi there, I'm having an issue with installing the chroot using the manager in the nethunter app, I had checked that the /data/local/nhsystem folder did have the chroot installed, I was able however to use the custom commands tab, select wifite and escape from wifite into the kali chroot. Also I cannot install the full chroot, and the error I received 
in the logfile was 
Starting download. Standby&
6 Sep 2017 5:55:18 p.m. - Chroot download completed: Total 765.0 MB.
6 Sep 2017 5:55:18 p.m. - Original SHA: 68A3C557E14EC301FD37831793485C2280B9F706975CFF3F9F9CF4000C9703B27DD21B5E076BDED0CEFF6E5652EFC225B0DC76AA391AC5A7E90D683E3B43B647
6 Sep 2017 5:56:00 p.m. - Checking file integrity... MATCH
6 Sep 2017 5:56:00 p.m. - New SHA: 68A3C557E14EC301FD37831793485C2280B9F706975CFF3F9F9CF4000C9703B27DD21B5E076BDED0CEFF6E5652EFC225B0DC76AA391AC5A7E90D683E3B43B647
6 Sep 2017 5:56:02 p.m. - Unzipping and untarring....
6 Sep 2017 5:56:02 p.m. - Decompressing and deploying the Chroot& (~510 min)
6 Sep 2017 5:56:03 p.m. - Error: java.lang.RuntimeException: java.lang.RuntimeException
6 Sep 2017 5:56:03 p.m. - CreateChroot >> Error: java.lang.RuntimeException: java.lang.RuntimeException
6 Sep 2017 5:56:27 p.m. - New instalation log file: /storage/emulated/0/nh_install_20170906_055143.log

Thanks guys, this is pretty neat.

**Comment by ortholinux** [comment]
There is still a lot to fix with the nethunter suit, it shows dozens of problems to me as well but no one seems to help around here, i am thinking of buying a compatible device just to run nethunter particularly Kali, but afraid as if it wont work there either, and as everyone seems to be busy to help out so still hanging in there.

**Comment by XIV91774** [comment]
I was sure that the LG nexus 5 was already supported, its in the nethunter
downloads page.

**Comment by jcadduono** [comment]
using builds from build.nethunter.com/nightly ?

**Comment by ortholinux** [comment]
i've opened a thread before as well, please read it and help me out if its possible to run it on the device i mentioned otherwise i'd have to buy something else(tough decision), i'll provide all the logs and anything else.

**Comment by keeganjk** [comment]
@XIV91774 Are you trying to use Magisk? That's been causing problems for me...

**Comment by XIV91774** [comment]
Nah man, I used Kingo root to root my nexus 5 then installed SuperSU.
