### ISSUE TITLE
[Solved] no wlan1 showing still adapter is working & with right rom,kernel

### ISSUE THREAD

**Issue by hussaini1** [offensive-security/kali-nethunter#975]
### Device: All Nethunter supported device
My : klteduas

## Issue:
Wlan1 not showing.  the external wifi adapter is working fine in pc.
 Using all method
Airmon-ng
Wifite
Put wlan1 monitor mode
Wlan1 if up

M on right kernel
Kernel is official nightly : klteduas nought 
M on right Rom : RR official 5.8.xx
M check & my usb port is working with pendrive 

But no luck

After a lot of searching  & with the help of dev
I found a solution

Fix :

kernel isnt autoloading modules, maybe due to modprobe location

So load it manually

Its not a big problem

***********************************

Open terminal & type

"modprobe ath9tk_htc "

Then attache ur adapter then type

"Ifconfig"

Then u see wlan1 now  u able to use wlan1 

so just remember to modprobe ath9tk_htc before plugging in

**Comment by hussaini1** [comment]
U can also join our whatsapp nethunter group

https://chat.whatsapp.com/GZaQvIU0LGMJKhXW9vvTBS

**Comment by chadvavra** [comment]
Device: Nexus 7 wifi 2013
Kali built from source today
Android 6.0.1
Adapter: TPLINK TL-WN722N V2.1

AndroidSU terminal:  "/system/lib/modules': No such file or directory
kali root terminal: FATAL: Module ath9tk_htc not found in directory /lib/modules/3.4.0-gae95f7e-dirty

Any help greatly appreciated.

**Comment by chadvavra** [comment]
root@kali terminal: /lib/modules/  No such directory

**Comment by argtje99** [comment]
@chadvavra that means you dont have the drivers on your device..

**Comment by jcadduono** [comment]
Will be fixed in future app release. We simply need to bind mount /system/lib/modules on /lib/modules in kali rootfs

**Comment by jcadduono** [comment]
Use modprobe in AndroidSU for now

**Comment by kimocoder** [comment]
one more thing.. the TL-WN722n uses the ath9k_htc driver (which is supported with injection), but the v2 uses r8188eu which does not support either monitor nor injection.

more info [here](https://wikidevi.com/wiki/TP-LINK_TL-WN722N_v2)

**Comment by argtje99** [comment]
@kimocoder you are right. TPlink doesn't sell the V1 anymore

**Comment by hamzabarqich** [comment]
friernds i can't use external monitor too i have tp-link  tl-wn722n v1 but is noit working why

**Comment by ICY-OWL** [comment]
have the solution, instead of "modprobe ath9tk_htc" i typed `modprobe ath9tk_htc` (whithout the t) now it Works for me too ._.   (i have the TL-WN722N)

**Comment by ICY-OWL** [comment]
i have two otg Adapters both works fine when i use it with a usb drive or mice etc.., however only one does work with a external WiFi and a usb Controller... the other doesnt recognize it  _strange_

**Comment by yesrab** [comment]
That WhatsApp link not working
