### ISSUE TITLE
NetHunter terminal not working with Kali option

### ISSUE THREAD

**Issue by cristimiha** [offensive-security/kali-nethunter#976]
### Device:
Nexus 7

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Kitkat

### Built from repo (date and build command) or downloaded from website (links):

Nightly/3.20-20170903-2143

## Issue:
Hello,
I cannot open Nethunter terminal with Kali option.
Everytime i try I receive the error below:
Error
Could not find 
/Data/local/nhsystem/kali-armhf
Missing chrot. You need to Install from chrot manager.

I have downloaded the last one,and Evan tried some other versions that did not work.
Please advise

**Comment by jcadduono** [comment]
u installed this exact file? https://build.nethunter.com/nightly/3.20-20170903-2143/nethunter-generic-armhf-kalifs-full-rolling-3.20-20170903-2143.zip
if using nexus 7 2012 u will need a 3.4 kernel as well

**Comment by cristimiha** [comment]
Thank you for your fast answer.
Yes, this is the file I installed.

Can you please tell me how can I get a 3.4 kernel?
This is the reason I tried a nightly version, I needed a newer version.

**Comment by jcadduono** [comment]
i dunno how, its over 5 years old

**Comment by cristimiha** [comment]
And you say I cannot use the nexus 7 because it is too old?
Do I have any other option in order to run Kali on it?

**Comment by jcadduono** [comment]
use nethunter 3.0 release image for it, no support though

**Comment by cristimiha** [comment]
Can you please tell me if Nexus 7 2013 Marshmallow it is up to date and it will be updated? Or Nexus 9 should be better?
