### ISSUE TITLE
Speaker not functioned in Nexus 6 (Nougat 7.1.1)

### ISSUE THREAD

**Issue by flesh91** [offensive-security/kali-nethunter#978]
### Device:

Nexus 6

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat 7.1.1 Latest

### Built from repo (date and build command) or downloaded from website (links):

https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-shamu-nougat-3.20-20170903-2143.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40kali-g1d7b23e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #4 SMP PREEMPT Thu Aug 25 18:56:08 CDT 2016

## Issue:
No sound present in speaker, but works fine with headphone, it still can record sounds, just not able to output sound. I think maybe this kernel was not built with latest source code???
Except for this, anything seems work fine here.

**Comment by flesh91** [comment]
Ауу блять.

**Comment by rubencabrera** [comment]
Same issue here:
https://github.com/offensive-security/kali-nethunter/issues/873
