### ISSUE TITLE
How to patch kernel? And how to edit boot_patcher.sh?

### ISSUE THREAD

**Issue by stainslav** [offensive-security/kali-nethunter#980]
### Device:

Intex Aqua Power Plus

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Lollipop

## Issue:Hey all I want to install nethunter but I don't have any of the sources available can anyone help me in patching my kernel by extracting and repacking zImage, or tell me what to add in boot_patcher.sh in Kali nethunter so let it do his work it self it want boot block= my one is /dev/mmcblk0p6 and ramdisk compression what to add there.
Please help me!
Thanks in advance

**Comment by jcadduono** [comment]
dont need to edit anything just install https://build.nethunter.com/nightly/3.20-20170903-2143/nethunter-generic-armhf-kalifs-full-rolling-3.20-20170903-2143.zip in twrp and you will have everything except the kernel....need to do a lot of research on xda on how to build kernels
you will need the sources, without them it's pointless
