### ISSUE TITLE
Porting to magisk

### ISSUE THREAD

**Issue by xavkno** [offensive-security/kali-nethunter#981]
This is not an issue but a suggestion for compatibility : 
maybe it's a good idea to port nethunter as an magisk module if possible.
Or at least make this magisk compatible as supersu isn't  the root solution many use and trust anymore.

Thank you in advance.

**Comment by stainslav** [comment]
Hey please help me how to extract zImage:(

**Comment by keeganjk** [comment]
@stainslav Have you searched? Use 7zip or look at this: [https://forum.xda-developers.com/showthread.php?t=777380](https://forum.xda-developers.com/showthread.php?t=777380)

**Comment by keeganjk** [comment]
We really need help for this. There have been no replies in 12 days...

**Comment by keeganjk** [comment]
I got Magisk working!
This is what I did:

1. Go to https://forum.xda-developers.com/android/software-hacking/kali-nethunter-magisk-t3676681
2. Downoad the Magisk-nethunter module zip
3. Flash it in TWRP
4. De-compress the Magisk-nethunter module zip and manually install the APKs
5. Open NetHunter app
6. Go to Chroot manager, selected download and selected full Chroot
7. PROFIT
