### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by stainslav** [offensive-security/kali-nethunter#982]
### Device:
Intex aqua power plus

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Lollipop

## Issue:
Hey, binkybear , I have a problem I wanna extract zImage but there is no working method can you tell me how to extract it according to you or the method you know please because my device doesn't have any the sources help please send me method:(

**Comment by jcadduono** [comment]
no idea what extracting zImage will accomplish unless you're trying to build TWRP
you won't get much of anywhere with NetHunter on a device without a proper kernel source release

if you're rooted you can dd your boot partition to a file then use bootimg to extract it (used by nethunter installer) 
bootimg.exe available here for windows: https://build.nethunter.com/possibly-the-coolest-things/bootimg/
for linux compile from https://github.com/jcadduono/android_external_libbootimg
