### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by youssrii** [offensive-security/kali-nethunter#984]
Hello.. I have Samsung Galaxy S4 T-Mobile (M919) with custom ROM lineage os 14.1..
I tried to flash many versions of nethunter os and every time it show me insupported device..
Can any one help me with a link or something !

**Comment by youssrii** [comment]
Anyone?

**Comment by thenickvendetta** [comment]
I successfully install nethunter in my device lenovo a5000 (5.0.2 Lollipop CM ROM)
I use this link:kalinethunter.blogspot.com

**Comment by youssrii** [comment]
I successfully installed it.. But i have problèm on installing chroot.. Thx man

**Comment by youssrii** [comment]
I cant install the chroot.. Error
