### ISSUE TITLE
Install nethunter on my s4 with cm13 !!

### ISSUE THREAD

**Issue by youssrii** [offensive-security/kali-nethunter#986]
Can anyone help me.. plz

**Comment by rootinchase** [comment]
Before I can help, I have to ask, what is your current setup?
I need at least this information:
1. Do you have a custom recovery?
2. Do you have a Android 6.0.x ROM installed?
3. What device do you have?

Once I get that info (or more, more is always helpful), then I can help you.

I will say that you s4 CANNOT be an exynos one, you need a jflte device
