### ISSUE TITLE
Is Only SuperSu supported ?

### ISSUE THREAD

**Issue by dhanush-raj** [offensive-security/kali-nethunter#990]
Can you tell me ,that Kali - nethunter only works with SuperSU and not with magisk. Just to confirm. And can I know the reason.

**Comment by killergast113** [comment]
no it works with magisk tho had it before

**Comment by dhanush-raj** [comment]
@killergast113
Then with magisk 14 its not compatible, right ?

**Comment by killergast113** [comment]
it ill work with any version of magisk

**Comment by keeganjk** [comment]
I tried Magisk and it caused the terminal to crash. @killergast113 How did you get it to work?

**Comment by killergast113** [comment]
first install busy box and then flash kali nethunter

**Comment by killergast113** [comment]
and make sure u use a costom rom

**Comment by killergast113** [comment]
i.use a s7 not ege but s7 and i.run hydra rom or super man rom just a custom rom thats all

**Comment by killergast113** [comment]
and first install bussy box other wise u ill get a error

**Comment by dhanush-raj** [comment]
ok i will try and see if it works

**Comment by killergast113** [comment]
okey gl

**Comment by keeganjk** [comment]
Didn't work for me.

**Comment by keeganjk** [comment]
how do i make my phone background hentai

**Comment by justasmig** [comment]
Kernel doesn't flash when I installed magisk on my OP3, Oxygen os... Any ideas how to fix that?

**Comment by einsteinov** [comment]
uninstall magisk,  install kernel,  reinstall magisk.

**Comment by justasmig** [comment]
@einsteinov I think that kernel reverted when I installed magisk, because I needed to bypass safetynet and so I uninstalled supersu, then installed magisk... But it was 1-2months ago, not sure if that was a problem... I will try doing this tho

**Comment by keeganjk** [comment]
@einsteinov Don't you need stock kernel to install Magisk?

**Comment by einsteinov** [comment]
@dhanush-raj
both.

**Comment by einsteinov** [comment]
@keeganjk
No.
It's working very well on Lineage.

**Comment by keeganjk** [comment]
@einsteinov Hmmm... I thought about installing Lineage, but I just installed FreedomOS and I really love it.

**Comment by keeganjk** [comment]
I'm using the OnePlus 5.

**Comment by justasmig** [comment]
wiped and installed new oos, installed magisk, flashed kernel and it was working fine... then I rebooted and kernel is gone, not flashing again.. Any ideas how to fix that? :/

**Comment by atarii** [comment]
Regarding Magisk, I've created a pull request (https://github.com/offensive-security/nethunter-app/pull/173) with a fix for the Terminal hanging (or working after you type exit).

I've also created a Magisk module for Nethunter here: https://forum.xda-developers.com/android/software-hacking/kali-nethunter-magisk-t3676681 so you can install without touching /system

**Comment by keeganjk** [comment]
@atarii How do I use it?

**Comment by kimocoder** [comment]
Either wait for the commit to be merged, or fork the "nethunter-app" repo, get the commit/patch from atarii to your own fork & build it with Android Studio

**Comment by keeganjk** [comment]
I got Magisk working!
This is what I did:

1. Go to https://forum.xda-developers.com/android/software-hacking/kali-nethunter-magisk-t3676681
2. Downoad the Magisk-nethunter module zip
3. Flashed it in TWRP
4. De-compress the Magisk-nethunter module zip and manually install the APKs
5. Open NetHunter app
6. Go to Chroot manager, selected download and selected full Chroot
PROFIT
Haven't tried with Burgerhunter kernel (yet)

**Comment by bozwald** [comment]
Mine reboots everytime I open terminal following Atarii's steps but also with SuperSU installed instead. I cannot for the life of me fix it i think its because system links arent being created properly or something but I have no experience debugging or sorting this stuff out. Im using S8+ Exynos

**Comment by keeganjk** [comment]
@bozwald Maybe uninstall everything from Kali Nethunter and then reinstall?

**Comment by bozwald** [comment]
@keeganjk when I try to remove CHROOT it reboots my phone and is still there, i cannot even find any mention of the s8 and nethunter on the internet

**Comment by keeganjk** [comment]
Hmmm... Did you make a backup in TWRP that you can restore?

**Comment by bozwald** [comment]
yes

**Comment by bozwald** [comment]
It's strange too because my Busybox version changes inside Nethunter one of the is v1.25.0-NetHunter and the other is the latest busybox pro version which I actually installed myself before nethunter could these be conflicting, anyway I can remove the nethunter one? or set it up?

**Comment by kimocoder** [comment]
Im building a kernel for S8 (dreamlte) right now :)

**Comment by bozwald** [comment]
My tummy fizzled a little reading that

On 30 Sep 2017 17:22, "Christian &lt;kimocoder&gt;" <
notifications@github.com> wrote:

Im building a kernel for S8 (dreamlte) right now :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/990#issuecomment-333319193>,
or mute the thread

**Comment by bozwald** [comment]
@kimocoder I am having troubles because my file system stays as RO bootkali cant init and reboots my phone because it cant write

**Comment by kimocoder** [comment]
Have you flashed no-verity-opt-encryøt from https://build.nethunter.com/android-tools/no-verity-opt-encrypt/ ? The latest one must be flashed in TWRP ;)

**Comment by bozwald** [comment]
@kimocoder I just restored my TWRP with root, reflashed DM verity zip and then installed terminal apk/vnc apk/nethunter apk checked if I could make a file with touch hi.txt in / and it still says read only file system

**Comment by kimocoder** [comment]
From Terminal (with su permission), type "mount -o remount,rw /system"

**Comment by bozwald** [comment]
@kimocoder thanks for your replies so far

this is the output "dream2lte:/ # mount -o remount,rw /system

mount: '/dev/block/platform/1120000.ufs/by-name/SYSTEM'->'/system': Device or resource busy"

this is the furthest I have been able to get overcoming small issues on the way

**Comment by kimocoder** [comment]
also try remounting the "/" instead of the "/system" too, using the same readwrite command above

**Comment by bozwald** [comment]
@kimocoder 

I get "mount: 'rootfs'->'/': No such device"

**Comment by atarii** [comment]
You guys using Magisk with or without my Nethunter module?

**Comment by kimocoder** [comment]
Im on SuperSu infact..dont know with bozwald, but I dont have these problems over here at all

**Comment by bozwald** [comment]
@atarii I had used your magisk module and found the same error, I thought it was your module in my inexperience at first but after flashing supersu and getting root that way i get the same outcomes your module worked fine other than the fact my phone reboots opening kali or nethunter or trying to use any of the services

**Comment by atarii** [comment]
Is your SELinux mode set to permissive? Are all these issues on same device; S8?

**Comment by bozwald** [comment]
yes... when i use setenforce 0 my phone again reboots and it doesnt stay in that state and I cant seem to use sestatus

**Comment by kimocoder** [comment]
got my hands on the "dreamlte" (S8) today so I should stay quiet until I have looked more into it I'd think

**Comment by bozwald** [comment]
mine is a s8+ but in the terminal also says dreamlte - I've been at this for 24 odd hours now probably need some time away from it, i shall get nethunter working on my s8+!

**Comment by kimocoder** [comment]
The problem would be porting the kernel.. was just asking @jcadduono on IRC about this, and he says it would be quite some work..

I've got the NetHunter app and all that working, but the problem will be using the features like HID + wifi attacks (mac80211 patch for kernel) :/

Time will tell if someone would jump through all that to get it working

**Comment by bozwald** [comment]
@kimocoder Im gutted I was going to trade this phone in for a nexus 6 and have less problems but now ive flashed it they wont let me trade it in and im stuck with it. wish there was a way to reset boot counter

**Comment by bozwald** [comment]
@kimocoder any chance of linking the files you've used to get the nethunter app working? can you open terminal for root kali?

**Comment by kimocoder** [comment]
was testing this now, no the terminal force closes.. bootkali not working either, but the app is working though

**Comment by kimocoder** [comment]
![received_1104698289664794](https://user-images.githubusercontent.com/4252297/31049054-87c388c6-a62b-11e7-9700-7b8770cd84b1.png)

**Comment by bozwald** [comment]
@kimocoder you've gotten as far as I've been able to get.  I've not had that specific problem though, Busybox for me gets installed to /system/bin  and i've used the busybox pro and also one from osm0sis and another one that was packaged in kalifs full

**Comment by atarii** [comment]
Have you got Nethunter app, Nethunter Terminal and Nethunter VNC installed? All those are needed

**Comment by bozwald** [comment]
@Atarii yes I have all three of them installed, read some places it needs to go in this order Terminal > VNC >Nethunter i've tried that, and other combinations

**Comment by kimocoder** [comment]
Yeah, I've just found that permissions was not given.. Manually had to set them in "Settings"

**Comment by bozwald** [comment]
@kimocoder root permissions sorry? are you able to change the rw of /system? do you have the same issue

**Comment by kimocoder** [comment]
Well, have tried different things, but now im experiencing the same issue as you do when choosing Kali in Term-NH, it reboots..

This is after i flashed the .zip file with the kalifs. Earlier i unpacked it with busybox xz & busybox tar, then it just force closed. I say we should make a S8 thread to get people involved in making support for the S8

**Comment by bozwald** [comment]
@kimocoder agreed. where can you suggest we'd do that?

**Comment by bozwald** [comment]
@kimocoder I was thinking the same but I wasn't sure whether the edge or what not was likely to be the most similar, i believe were on armhf please correct me if i'm wrong. I have a brand new account on XDA so im not sure how well people would respond to it, I'll do some more research too and then we can hit eachother up with what we get and get a thread going asap im glad at least one other people has an s8 and wants nethunter :P

**Comment by kimocoder** [comment]
system arch is arm64, jcadd's source for S7 NetHunter is [here](https://github.com/jcadduono/android_kernel_samsung_universal8890/tree/nethunter-6.0)

**Comment by killergast113** [comment]
nice

**Comment by jcadduono** [comment]
Difference to S7 is probably quite major I would look at S8 custom kernels and see what they do to OS and boot image and implement that I NetHunter patch.d for device

**Comment by bozwald** [comment]
thanks @jcadduono I read about Jesses s8 Kernel today with SE Permissive, trying that, but it seems my system is still stuck on Read only. Is that the problem that the system is read only so nethunter can't actually do anything? 

im considering running through your s7 build and having a look to see if that'd work

**Comment by kimocoder** [comment]
jcadd's build is for 6.0 anyway, so it wont work.. if you by any means should get Kali Terminal working, give me a shout

**Comment by bozwald** [comment]
@kimocoder with Jesse's Kernel for s8 I now no longer get rebooted I just have the common no title error and crash, but no reboot. When trying to mount and remount drive to rw i still have the same error about resource being busy.

**Comment by killergast113** [comment]
hello can anny body inform me what kernel is for s7 sm-g930f nm7.0

**Comment by killergast113** [comment]
i.mean nougat 7.0

**Comment by bozwald** [comment]
@killergast113 SM-G930F, SM-G930FD, SM-G930W8, SM-G930X: kernel-nethunter-herolte-* that's for nethunter you can find them at build.nethunter.com lucky man for having an s7 right now :D

**Comment by killergast113** [comment]
yeah i.hope you will figer it out good luck with s8 cheers :D

**Comment by killergast113** [comment]
k i.m at build build.nethunter.com
so where do i.need to go next?

**Comment by bozwald** [comment]
@killergast113 into the nightly folder then i'd do a ctrl f and search hero2lte, you might wanna double check that's correct by cross referencing me with something else because theres a risk you can brick your phone

**Comment by kimocoder** [comment]
Also, do READ the NetHunter Wiki for information, it's found [here](https://github.com/offensive-security/kali-nethunter/wiki)

**Comment by killergast113** [comment]
i.m pretty sure herlote not 2 but just herlote

**Comment by bozwald** [comment]
@kimocoder omg ive done it bro....

https://stackoverflow.com/questions/6066030/read-only-file-system-on-android i read this then mounted the system as rw then removed the chroot by rm -rf /data/local/nhsystem/kali* then i reinstalled minimal chroot in the manage and it booted in

**Comment by bozwald** [comment]
@kimocoder i cant see to run apt-get update yet but I am still inside the terminal with kali

**Comment by kimocoder** [comment]
Great, but it's an dirty workaround.. bwah, a kernel + support for this device would be awesome :p

**Comment by bozwald** [comment]
@kimocoder after reboot it works fine

**Comment by kimocoder** [comment]
do apt-get work after reboot? If that's the case, could you re-produce the exact steps on what you did to manage get it working?

**Comment by bozwald** [comment]
@kimocoder yes it does doing upgrade now, so i flashed jesses kernel, then i had to flash supersu for root again, i reinstalled nethunter terminal vnc, nethunter then I used that https://stackoverflow.com/questions/6066030/read-only-file-system-on-android commands fix, then i made file system rw with adb commands and added symbolic links between data/data/com.offsec.nethunter/files/scripts/bootkali and /system/bin/bootkali then I removed the current chroot, with command line, then i reinstalled through sd card and ch manager and did a reboot and it works for me..

I am by no means good at android just been googling my ass off

**Comment by kimocoder** [comment]
Thanks. Hahahahah Google actually got the answers most of the time :D it's still dirty, but this is anyway great news for getting the base NetHunter up and running. Could you also post a link to Jesses kernel, that would be the last im asking for at this time until we get kernel support. I asked NOTORIOUS kernel devs to include the mac80211 stack with injection patches + drivers, so we'll have to wait for that one to appear somewhere, then there is the NetHunter support.. Lots to do there yet. Anyway, great work sir

**Comment by bozwald** [comment]
https://forum.xda-developers.com/galaxy-s8/samsung-galaxy-s8--s8-cross-device-development/kernel-jesse-s-kernel-galaxy-s8-exynos-t3603521

@kimocoder 


https://imgur.com/a/1ewae

**Comment by bozwald** [comment]
thanks to all in this thread as this is where I got most my help.

**Comment by bozwald** [comment]
i also mounted /system in twrp settings in customer recovery.. @kimocoder sorry I forgot that.

**Comment by kimocoder** [comment]
When did you do that exactly?  After/before what?

**Comment by kimocoder** [comment]
The command to mount it read/write that worked was:

mount -o remount,rw -t ext4 /system

**Comment by kimocoder** [comment]
Actually, by mounting the system readwrite before installing, there is no need for symlinking :) everythibg works great with just installing

**Comment by bozwald** [comment]
@kimocoder have you managed to get wifite to find a device or get bluetooth to work? I tried to uninstall chroot and reinstall it but i still cant uninstall it, also I don't seem to be able to navigate around the vnc but these are all odd little issues, is yours any different?

**Comment by kimocoder** [comment]
well, wifite wont work anyway, because mac80211 stack + drivers needs to be in kernel. Also the mac80211 injection patch needs to be there

**Comment by bozwald** [comment]
@kimocoder and for instance when I do something like apt-get install cowsay, when i then type cowsay it will say command not found, same for other packages too, any ideason that?

**Comment by kimocoder** [comment]
wifite and everything seems to be working fine over here..

**Comment by bozwald** [comment]
@kimocoder would you mind posting your steps too get where you are for me to try

**Comment by kimocoder** [comment]
Followed steps

* Uninstalled all apps
* Flashed kernel
* Flashed supersu
* Mounted "/system" in TWRP
* Rebooted
* ADB SHELL: su (confirm on device)
* "mount -o remount,rw -t ext4 /system" ADB SHELL
* Installed apps (NH-Term, VNC, then NetHunter)
* Started NetHunter app, downloaded and installed full chroot (before it would not because of the readwrite i think.. got java error on unpacking)

Everything worked.. Dont think i missed something

**Comment by bozwald** [comment]
@kimocoder thanks this works for me too... my other error was a new one for me and I had stomped my PATH and had to reconfigure that, was unrelated. During the week lets see about getting that post on XDA maybe set up interest for a bounty

**Comment by kimocoder** [comment]
Yes sir, currently looking into the sourcecode for Jessie's kernel, will do some tests on adding NetHunter additions to it and run it. Please let me know if you stumble upon something new, then I'll do the same back. Thanks for all help getting the basics up & running.

**Comment by bozwald** [comment]
@kimocoder sure thing i will keep updating with advances i downloaded kernel stuff last night but way over my head at the moment but ill keep at it, i used jesses kernel because i searched for roms and kernels with SE permissive constant

**Comment by killergast113** [comment]
this sucks its only for s7 sm-930f marshmello ffs i.m running marsh mello hydra rom and nethunter marsh mello kernel plz help me to get 7.0 for s7 sm-930f any help would be nice

**Comment by killergast113** [comment]
this is the link https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-herolte-marshmallow-3.20-20170903-2143.zip

**Comment by killergast113** [comment]
this sucks its only for s7 sm-930f marshmello ffs i.m running marsh mello hydra rom and nethunter marsh mello kernel plz help me to get 7.0 for s7 sm-930f any help would be nice btw forgot to put link https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-herolte-marshmallow-3.20-20170903-2143.zip

**Comment by bozwald** [comment]
@killergast you might need to flash stock package through smart switch and start again, id check first to see what version of android it will put you on but that should work. Otherwise youd be "dirty flashing".

@kimocoder when you mentioned that wireless wouldnt work due to the mac patch etc does that include bluetooth? Silly question I know I just dont want to waste time looking into bluetooth if its a fruitless endeavour.

**Comment by kimocoder** [comment]
No it's not related to.bluetooth, but for wifi to work as in NetHunter, the mac80211 stack needs to be enabled in "make menuconfi" / kernel .config, the injection support needs the mac80211 injection patch found in patches.aircrack-ng.org as described on the wiki and also several drivers needs to be in kernel .config

**Comment by bozwald** [comment]
Can we modify jesses kernel to add it on the wiki for NH it shows the mac patch and stack im not confident to edit jesses kernel can we just open it with menuconfig and then simply add it? @kimocoder

So if we added it i could flash it and then supersu again then install the nethunter and chroot. ? @jcadduono

**Comment by kimocoder** [comment]
well, tried yesterday but stumbled upon some issues.. [here](https://github.com/jesec/android_kernel_samsung_universal8895) is the link to kernel source. both TW-7.0 and Stock-7.0 is in that repo

**Comment by bozwald** [comment]
@kimocoder i understand that we can download the drivers from samsung opensource then we could open the fresh exynos defconfig into menuconfig and one with jesses kernel open in menuconfig and match it all up but add the mac stack??? Im talking of getting wireless working and once a build is ok there then we can look at HID but im unsure about editting kernels, what problems are you getting with a modified jesses kernel? Did u just add the prompts that the nethunter wiki suggested?

**Comment by killergast113** [comment]
so guy back in the day i.was doing good on wifi adaptetrs but but but there was a litle isu with my s7 sm-930f so it was the isu that i.had to port a linux 4.0 driver down to 3.18 so may be this might save me my live

**Comment by killergast113** [comment]
so guy back in the day i.was doing good on wifi adaptetrs but but but there was a litle isu with my s7 sm-930f so it was the isu that i.had to port a linux 4.0 driver down to 3.18 so may be this might save me my live link https://github.com/maage/mt7610u_wifi/tree/some_changes so if u need baseband and modem plz tel me ty

**Comment by killergast113** [comment]
so plz look in to that stuf i.have a usb AC51 wifi adapter and kernel is 3.16 on driver so how the hell do i.know wtf my base band is or firewarme version becuse i.use twrp and updated my modem and boot loader so onece agian plz help me reach the stuff i.need if u dont know why i.need the know the base band is becuse of samsung opensorce ty guy

**Comment by bozwald** [comment]
@kimocoder I also cannot detect any OTG device i plug in atm, usb sticks, external wifi etc, I plugged in a mouse and it recieved power, just couldn't use it in VNC. I have no idea what would attribute to this issue, are you able to mount a USB stick on your phone for an example?

**Comment by kimocoder** [comment]
OTG also have to be activated in kernel through "make menuconfig"

I've just removed SuperSu, changed to Magisk with NetHunter module.. It also works great with "dreamlte"

**Comment by bozwald** [comment]
@kimocoder so @atarii build now works for you - So this means we only need a kernel made now for our device? which will have HID/Wireless/OTG Support? I think these are the only problems were having now??? 

Shall we approach xda or something soon to request a kernel out of love for the s8 or to see if maybe some people want to put a bounty together?

**Comment by kimocoder** [comment]
Kernel would be the missing link yup

**Comment by bozwald** [comment]
@kimocoder how did your convo go with the developer you mentioned up the thread, I understand this will be a meaty kernel to produce?

**Comment by keeganjk** [comment]
Whenever I try to delete the chroot it reboots (as it should) and then after about 15-30 seconds it says "Delete chroot request found", "Deleting chroot", and then it freezes, reboots, and repeats. I had to delete the Magisk module, Nethunter, Nethunter Terminal, and Nethunter VNC. How can I delete the chroot without it freezing?

**Comment by kimocoder** [comment]
Been having that issue on several phones.. get to android su terminal, then "rm -rf /data/local/nhsystem/*"

**Comment by keeganjk** [comment]
@kimocoder I tried removing that from ES File Explorer, will try from AndroidSU. (I'll probably try through TWRP terminal)

**Comment by jcadduono** [comment]
Please only do rm -rf of chroot from TWRP!!!!!!!!
If anything happens to be mounted in OS when you do that (chroot started) then you will probably also end up deleting your entire internal storage and sdcard contents!

**Comment by keeganjk** [comment]
@jcadduono Thanks! Every time I froze, I thought it might be because the OS was trying to delete itself...

**Comment by jmingov** [comment]
> will ~~probably also~~ end up deleting your entire internal storage and sdcard contents!

Hes totally right. That shit is true. ^^

my best

**Comment by keeganjk** [comment]
`rm -rf /data/local/nhsystem/*` worked, I deleted the `/data/local/nhsystem` folder from a file manager afterwords.

**Comment by bozwald** [comment]
@kimocoder a number of kernels work for what weve got so far, jesses nemesis and notorius but i tried to compile a boot img last night but it wouldnt boot on my phone

**Comment by bozwald** [comment]
@kimocoder i was speaking to djp77 and he was thinking of cleaning his kernel up and might add our parameters

**Comment by keeganjk** [comment]
I got the [https://forum.xda-developers.com/oneplus-5/development/burgerhunter-t3638810/page1](https://forum.xda-developers.com/oneplus-5/development/burgerhunter-t3638810/page26) BurgerHunter kernel to work with the Magisk Module.

**Comment by kimocoder** [comment]
Great! Im looking at it too, but notice me if you got something going :)

**Comment by keeganjk** [comment]
@kimocoder They haven't added HID support yet, but it's been going on for a while.

**Comment by kimocoder** [comment]
Yeah, my ref. was to @bozwald but anyway, take a look [here](https://github.com/offensive-security/nethunter-devices/commits/master) the HID is working on the OnePlus5 kernel thanks to the work by @binkybear -- on the other hand, SuperSu should be replaced by Magisk with the NetHunter module too, agreed?

**Comment by keeganjk** [comment]
@kimocoder Yeah, Magisk would be great. And I'm pretty sure binkybear only got it working with LineageOS; I want to use OxygenOS.

**Comment by kimocoder** [comment]
Aaah yes that would be correct, it's for lineage.. but porting would be possible, if it's open source and some skills (",)

**Comment by keeganjk** [comment]
@kimocoder Yeah... I wish I could help, but I know virtually nothing about Android app development, much less about ROM development.

**Comment by keeganjk** [comment]
The BurgerHunter kernel messed up the boot animation, I'm restoring a backup and trying binkybear's kernel for the OnePlus 5: [https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-oneplus5-oos-nougat-3.20-20170903-2143.zip](https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-oneplus5-oos-nougat-3.20-20170903-2143.zip)

**Comment by keeganjk** [comment]
binkybear's kernel worked.

**Comment by keeganjk** [comment]
This has been an ongoing problem for me: When I try to use anything in MITM in cSploit, it crashes and reboots. Does anyone else have this problem/know a solution?

**Comment by ozsteyr** [comment]
I have loooked at djp77's kernel and looks good. I dont have a pc/laptop and was wondering if anyone has a build available for the S8+? I'd be very grateful.

**Comment by ozsteyr** [comment]
Or maybe someone could teach me how to build this kernel within chroot if it is even possible?
Please...

**Comment by jcadduono** [comment]
i will be closing this as new nightly builds now come without supersu and you can choose to install either supersu or magisk depending on which you prefer. i recommend magisk now.

**Comment by keeganjk** [comment]
@kimocoder What's dreamlte?

**Comment by jcadduono** [comment]
dreamlte is exynos galaxy s8
