### ISSUE TITLE
StartX problem

### ISSUE THREAD

**Issue by jdmcwhinnie** [offensive-security/kali-nethunter#991]
### Device:

LG Prepaid

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Android version 5.0.1

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.49-gacc13996-00001-g6c9d187 (lgmobile@LGEACI5R12) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Tue Jun 16 17:13:08 KST 2015

## Issue:
Can not startX

**Comment by jdmcwhinnie** [comment]
parse_vt_setting: cannot open /dev/tty0 (No such file or directory)

**Comment by jcadduono** [comment]
this is a kernel issue, this is why nethunter uses a nethunter kernel
