### ISSUE TITLE
Remove Nethunter from my devices

### ISSUE THREAD

**Issue by Koploseus** [offensive-security/kali-nethunter#993]
### Device:

One Plus 3T

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat (7.0)

Hello :) ! I want to Uninstall NetHunter from my Android without losing my data :), is there a tutorial ? 

Thanks!

**Comment by jcadduono** [comment]
you should have made a twrp backup of boot and system before flashing nethunter, then you restore that and delete the apps and /data/local/nhsystem and it should be fully uninstalled

if you don't have a backup to restore, then simply flashing a boot image for your rom along with supersu or no-verity-opt-encrypt-5.1.zip then deleting apps and /data/local/nhsystem should be sufficient (although you will still have the boot animation, sorry)
