### ISSUE TITLE
Support Alcatel A5 LED

### ISSUE THREAD

**Issue by phtom** [offensive-security/kali-nethunter#994]
## Issue: Support

Hi!
Alcatel A5 LED is a new super powerful octa-core smartphone! Would it be possible to make a security OS for it? An android rom for it? This smartphone is unique, and i'd like very much to get nethunter for it since i work in cybersec and have a ethical hacker course (fisical course)

**Comment by jcadduono** [comment]
can't be supported, closed source device, don't support companies by buying mediatek devices
