### ISSUE TITLE
 Can we re-lock the bootloader after flashing Nethunter

### ISSUE THREAD

**Issue by Ne0user** [offensive-security/kali-nethunter#995]
### Built from repo (date and build command) or downloaded from website (links):
https://github.com/offensive-security/nethunter-LRT

## Issue:
Hi,

I am a new user of Nethunter, and I would like to know it it makes sense to re-lock the bootloader after flashing Nethunter.
Actually, when i lock the bootloader i can't boot anymore because of the android security.
this message is prompted : "Your device is corrupt. It can't be trusted and may not work properly"
And if it is possible how can we do that ?
If not what is the risk of letting the bootloader unlocked ?

Thanks

**Comment by jcadduono** [comment]
The point of a locked bootloader is only to prevent non OEM signed boot images from booting
We can't sign our images, we are not the OEM.
Leave your bootloader unlocked if you wish to root or use anything other than stock.

**Comment by Ne0user** [comment]
hi @jcadduono,

Thanks a lot for your help ! :)
