### ISSUE TITLE
Busybox problem

### ISSUE THREAD

**Issue by madScript01** [offensive-security/kali-nethunter#996]
When I have bettercap installed and have the nethunter busybox somehow bettercap can't detect the wifi IP's/MACs but if I have for example the stericson busybox it can detect them, but of course then I have to type the interface and the gateway because the stericson busybox isn't linked to nethunter.
Any fix or solution ??

Thanks in advance

**Comment by jcadduono** [comment]
ya i will probably just fork meefik's busybox (its up to date and maintained)
i gave up on trying to maintain our own fork of it

**Comment by madScript01** [comment]
Thanks :)
