### ISSUE TITLE
DEVICE REBOOT ON DISCONNECTING THE WIFI ADAPTER(TP-LINK TL-WN722N) :(

### ISSUE THREAD

**Issue by lightakun** [offensive-security/kali-nethunter#997]
### Built from repo (date and build command) or downloaded from website (links):Downloaded from official nightly builds (https://build.nethunter.com/nightly/) KERNAL flashed: 
https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-s2-nougat-3.20-20170903-2143.zip   Chroot File flashed: https://build.nethunter.com/nightly/3.20-20170903-2143/nethunter-generic-amrm64-kalifs-full-rolling-3.20-20170903-2143.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:root@kali:~# cat /proc/version
Linux version 3.10.84-NetHunter-g60206e38e60-dirty (rishabhrao@devs) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Feb 1 12:45:42 UTC 2017

## Issue: First of all Hats off to OFFensive security for making masterpiece like this to our devices :)
Been using Kali nethunter on my device (LE 2 X526) with ease and awsmness but only 1 problem.
I have my TP LINK TL-WN722N Wireless adapter and it work flawless in my device with all its features to the fullest, but whenever i plug out my wireless adapter the device reboots with a blue light on the notification led. I tried to power off the adapter first by "ifconfig wlan1 down" before removing but still the device rebooted.Also  Tried to remove the interface by "iw dev wlan1 del" before pluging it out but still it rebooted.ill be able to give full logs as you say. Please Help me asap :). Thank You. @binkybear @jcadduono

**Comment by jcadduono** [comment]
```
# LeEco Le 2
[s2]
author = "Rishabh Rao"
version = "1.0"
```
@rishabhrao you might have a prima/pronto/qcacld-2.0 in your tree that needs netdev notifier worker removal (breaks external adapter unplug)
here is an example commit for fixing it: https://github.com/jcadduono/nethunter_kernel_mako/commit/bda7cf4b08a04152a868e87b2f90070db6b88134

**Comment by lightakun** [comment]
@jcadduono @rishabrao is not online this days.
So is there a workaround for this problem that i can use ?

**Comment by lightakun** [comment]
problem solved!! tysm
