### ISSUE TITLE
Cannot capture handshake with Edimax dongle (RTL8188CUS) connected to OnePlus One

### ISSUE THREAD

**Issue by hugoender** [offensive-security/kali-nethunter#998]
### Device:
OnePlus One A0001
Edimax (RTL8188CUS) Wifi Dongle

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
CM-13.0-20161220
Android Version: 6.0.1 Marshmallow
Kernel Version: 3.4.112-cyanogenmod-g8fbc62e

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from website: https://build.nethunter.com/release/marshmallow/nethunter-oneplus1-marshmallow-kalifs-full-3.20-20170717-1810.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.4.112-cyanogenmod-g8fbc62e (root@nhbuild-box) (gcc version 4.7 (GCC) ) #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016

### Output of `lsusb`:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

## Issue:
Cannot capture handshake with Edimax dongle (RTL8188CUS). I am able to put the dongle in monitor mode as well as send deauth with `aireplay-ng` but it does not seem to capture handshakes. If I connect this same dongle to my laptop running Kali Linux, it captures handshake just fine. Also, if I connect my Alfa card to my OnePlus One phone, I can capture handshakes just fine as well.

I have done an `apt-get update`, `upgrade` and `dist-upgrade` and still have this issue. 

When connecting the Edimax dongle to my Kali Linux laptop, the `airmon-ng` output shows the Driver for it as being RTL8192CU. This Nethunter page (https://github.com/offensive-security/kali-nethunter/wiki/Wireless-Cards) says:
**"The following chipsets are supported by default in most, if not all, NetHunter kernels:"**
**Realtek**
- RTL8192CU

So it seems like it should be supported. That said, the output of `airmon-ng` in Nethunter shows the drivers for Edimax dongle and other wifi adapters as being "??????". Just an FYI in case that means anything.

Any help in this matter would be greatly appreciated. Thank you for your time.

**Comment by hugoender** [comment]
### Output of `dmesg`:
 8877.436712] init: Starting service 'su_daemon'...
[ 8877.495955] init: Untracked pid 23300 exited with status 1
[ 8877.497616] init: Service 'su_daemon' (pid 23298) exited with status 0
[ 8877.497736] init: Service 'su_daemon' (pid 23298) killing any children in process group
[ 8878.378533] usb 1-1: USB disconnect, device number 2
[ 8881.057816] msm-dwc3 msm_dwc3: DWC3 in low power mode
[ 8881.728454] msm-dwc3 msm_dwc3: DWC3 exited from low power mode
[ 8881.952626] usb 1-1: new high-speed USB device number 3 using xhci-hcd
[ 8881.971458] usb 1-1: New USB device found, idVendor=7392, idProduct=7811
[ 8881.971973] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 8881.972366] usb 1-1: Product: 802.11n WLAN Adapter
[ 8881.973015] usb 1-1: Manufacturer: Realtek
[ 8881.973295] usb 1-1: SerialNumber: 00e04c000001
[ 8881.980642] rtl8192cu: Chip version 0x10
[ 8882.099742] rtl8192cu: MAC address: 80:1f:02:be:bb:c8
[ 8882.099943] rtl8192cu: Board Type 0
[ 8882.100225] rtlwifi: rx_max_size 15360, rx_urb_num 8, in_ep 1
[ 8882.100677] rtl8192cu: Loading firmware rtlwifi/rtl8192cufw.bin
[ 8882.105595] ieee80211 phy10: Selected rate control algorithm 'rtl_rc'
[ 8882.113142] rtlwifi: wireless switch is on
[ 8882.503891] init: Starting service 'su_daemon'...
[ 8882.563859] init: Untracked pid 23311 exited with status 1
[ 8882.566309] init: Service 'su_daemon' (pid 23309) exited with status 0
[ 8882.566429] init: Service 'su_daemon' (pid 23309) killing any children in process group

Seems like it's getting the proper driver.

**Comment by hugoender** [comment]
The following line shows that indeed Nethunter should have the proper driver for it: https://github.com/binkybear/AK-OnePone/blob/cm-13.0/arch/arm/configs/kali_defconfig#L1636

**Comment by pddevins** [comment]
I’m having the same issue with this single on a Nexus 7 2013. dmsg is showing the same output as well.
