### ISSUE TITLE
postgresql cannot create shared memory segment

### ISSUE THREAD

**Issue by domald** [offensive-security/kali-nethunter#999]
### Device:
oneplus 3T

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

OOS4.1.6

### Built from repo (date and build command) or downloaded from website (links): 
download from:https://build.nethunter.com/nightly/
kali nethunter: nethunter-generic-arm64-kalifs-full-rolling-3.20-20170903-2143

kernel: kernel-nethunter-oneplus3T-oos-nougat-3.20-20170903-2143

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.18.31-perf++ (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jul 17 13:44:23 CDT 2017

## Issue:

root@kali:~# service postgresql start
[....] Starting PostgreSQL 9.6 database server: main[....] The PostgreSQL server failed to start. Please check the log output: 2017-09-23 06:17:11.595 UTC [12433] FATAL: could not create shared memory segment: Function not implemented 2017-09-23 06:17:11.595 UTC [12433] DETAIL: Failed system call was shmget(key=5432001, size=40, 03600). 2017-09-23 06:17:11.596 UTC [12433] LOG: database system is shu[FAILn ... failed!
 failed!

**Comment by MyPuppet** [comment]
I have the same problem, will you solve it?

**Comment by SymbianSyMoh** [comment]
Anyone got a solve for this issue?

**Comment by pyc0de** [comment]
reflash kernel.

**Comment by jmmmbnnn** [comment]
If custom kernel, make sure the kernel has System V IPC enabled.  Otherwise as @pyc0de said, reflash working Kali Nethunter kernel.

See https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel
